### PR TITLE
[TS] LPS-146666

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi @robertoDiaz ,

Can you help review this PR?

Please let us know if you have any questions.
Thanks!

**Notes from @noornajj:**

> https://issues.liferay.com/browse/LPS-146666
> 
> The issue here was an infinite loop was caused when the default friendly URL was left empty. The reason this occurred is because the layoutId was being passed into layoutFriendlyURLEntryValidator.validateFriendlyURLEntry instead of the plid of the layout.
> To fix the issue, I passed the layout's plid when the friendly URL being validated belongs to an already existing layout. However, I also added an else statement to handle the validation when a new layout is being created.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1307401_2130

**Comment by adolfopa** [comment]
ci:reevaluate:1307401_2130

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
