### PR TITLE
LPS-144290 Preview window shows in Item Selector for non-previewable files

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by boton** [comment]
@IstvanD I haven´t the time to test it but in my mind doesn't work please correct me if I am wrong. 

With these changes, you are not to be able to add the PDF because you only have the `Add` button in the preview component.

image

I think is better to get a broken preview but with the possibility of adding the file. 

IMHO the best solution is to add something like in the [URLSelector](https://github.com/liferay/liferay-portal/blob/master/modules/apps/item-selector/item-selector-url-web/src/main/resources/META-INF/resources/js/ItemSelectorUrl.es.js#L137) that when the file doesn't have a preview render a message instead of a broken image and disable/hide the edit button too (pencil).

Tomorrow I can talk with the team and we decide if we have enough bandwidth to take care of it.
/ cc @AliciaGarciaGarcia

**Comment by IstvanD** [comment]
Hi @boton thank you for taking a look at it.
PDF and other non-image files are added automatically as soon they are picked in the native file explorer. The `onItemSelected` function [takes care of this](https://github.com/liferay-lima/liferay-portal/pull/2583/commits/1a889ec10aeb130d7987c2f053aac8af953d2fb6#diff-81fdd7b7dad6809b8ac8e52094618a68a243558e9fed43ef6f17fa28c9418f73R166).
The only difference compared to image files is the absence of the extra steps of the appearance of the Preview window and then pressing the Add button.

**Comment by boton** [comment]
Ohhh I see @IstvanD you are right. I tested today and it works. 

Sadly talking with @emiliano-cicero and @pablo-agulla we prefer to open the preview and inform the user that doesn't preview available for this file and click the `Add` and maintain the same interaction with all types of files.

Lima team can take care of the preview solution on master, it's OK for you?

**Comment by IstvanD** [comment]
Hi @boton 

I'm hoping you had a pleasant holiday!

Yes, I'm fine with this arrangement, but I would like to ask for a little clarification.
So, if a non-image file is uploaded, a text that says something like "No preview is available for this file" should appear instead of the empty image icon, and this is the solution that you'll implement on master.

Thanks in advance!

**Comment by boton** [comment]
> So, if a non-image file is uploaded, a text that says something like "No preview is available for this file" should appear instead of the empty image icon, and this is the solution that you'll implement on master.

Yep, this is a better explanation :D

**Pull request closed without merging**
