### PR TITLE
Fix wrong URL usage in DeepL Translator

### PR DESCRIPTION
**Pull request by matthiasblaesing**
As described in https://liferay.dev/ask/questions/development/reply-for-lps-183137-lps-187034-breaks-deepl the fix for LPS-187034 introduces an issue for DeepL:

The refactoring of the DeepL translator code to use the company configuration as basis for requests (LPS-187034) breaks translations because the wrong URL is used to create translation requests. There are two different URLs used by the DeepL translator. One is used to fetch the valid languages (validatedLanguageUrl) and the second to do the translation (url). After the refactoring for both cases `validatedLanguageUrl` is used, which breaks the translation call.

In LPS-183137 a user with name Austin pinged me for this. I can't access the JIRA anymore, so there is neither a tracking issue, nor can I answer this person. If required, please create an issue, I can update the commit message accordingly.

The fix was coded against 7.4.3.83 and tested in our staging environment, I rebased it onto current master for inclusion in mainline.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by matthiasblaesing** [comment]
As liferay decided, that contributors can't create issues anymore, the report of ci:test:sf is meaningless from a review POV, an issue creation request is in the PR description and the ask article, I hope that one of these will be answered.

**Comment by adolfopa** [comment]
Thanks for your contribution @matthiasblaesing 

@austinchiang Can we continue the discussion about the original issue in this PR?

**Comment by adolfopa** [comment]
@matthiasblaesing The changes look good. I'll approve and forward this once we create the required tickets.

**Comment by adolfopa** [comment]
@matthiasblaesing See https://github.com/liferay-lima/liferay-portal/pull/4458

**Comment by matthiasblaesing** [comment]
@adolfopa thank you for your help!

**Comment by adolfopa** [comment]
@austinchiang I've already sent the changes, so there's nothing else to do here. Thanks!

**Pull request closed without merging**
