### PR TITLE
LPS-175851, LPS-180049 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-175851
https://issues.liferay.com/browse/LPS-180049

The tests passed on CI:  https://testray.liferay.com/zh/home/-/testray/case_results?testrayBuildId=2299961105&testrayRunId=2299967067

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by austinchiang — COMMENTED** [review]
LGTM

**Review by austinchiang — APPROVED** [review]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
