### PR TITLE
LPS-170286 | Refactor method to get fragment resource title properly

### PR DESCRIPTION
**Pull request by jaimelr10**
**Descripción**: Modify method `getTitle()` from `HorizontalCardTag.java` to make same as the one in `VerticalCardTag.java` and avoid escaping lowercase **a** to **%A**
image

**Jira Ticket**: https://liferay.atlassian.net/browse/LPS-170286

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — COMMENTED** [review]
I prefer that someone from backend. analise this pull. This change will affect to other horizontal cards.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@jaimelr10 This looks good to me. Can you send it to the frontend team for further review?

Thanks!

**Comment by jaimelr10** [comment]
> @jaimelr10 This looks good to me. Can you send it to the frontend team for further review?
> 
> Thanks!

Cool @adolfopa! I sent it to https://github.com/liferay-frontend/liferay-portal/pull/3590

**Pull request closed without merging**
