### PR TITLE
LPS-200661 Handle root folder in all cases

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPS-200661

When selecting multiple documents, the "Copy From" field would show up empty.

# How am I fixing it?

We need to check both nullness and for the root folder ID, returning the predefined "Home" name when appropriate.

# How can you verify that it works?

Follow the steps described in https://liferay.atlassian.net/browse/LPS-200661.

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:stable

**Comment by WYZ-Issac** [comment]
Failures are unrelated

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
