### PR TITLE
[TS] LPS-137263

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-137263

### Update overview

Resend of a past pull request.

* https://github.com/brianchandotcom/liferay-portal/pull/106718
* https://github.com/liferay-lima/liferay-portal/pull/2238
 
Renamed parameter (`parentDDMStorageId` -> `copyDDMStorageId`) which makes it more obvious that we're not trying to deprecate the old method. Also applied the requested parameter reordering.

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
```
LocalFile.OpenGraphImages#CanViewImageWithMetaTags 
LocalFile.OpenGraphImages#CanEditAltDescription
LocalFile.OpenGraphPreview#CanViewPreview
LocalFile.SERPPreview#CanViewPreview
```

These cases **only** failing in this PR because they will navigate to the page admin without a success message after saving the changes (See the following gif file). But When we doing the same steps on the head of the master, they will stay on the configure page with a success message after saving the changes, then we can assert the open graph or SERP preview. 

Current Bundle

/cc @holatuwol @adolfopa

**Comment by holatuwol** [comment]
Code raises an exception with these steps, will re-send.

**Pull request closed without merging**
