### PR TITLE
LPS-186688 Fail when trying to copy to the live version of a site

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-186688

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-186688.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1317401_8304

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
Nice refactoring!

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
