### PR TITLE
LPS-137112 Fix issues with findByExtraSettings and countByExtraSettings in Oracle DB

### PR DESCRIPTION
**Pull request by mbowerman**
The extraSettings column in DLFileEntry and DLFileVersion is a CLOB-type column. Unfortunately, Oracle DB has some weird restrictions surrounding CLOB-type columns:
1. The WHERE clause included a "[clob_column] != ''" operation, which isn't allowed in Oracle.
2. We were SELECTING a DISTINCT set of columns, which isn't allowed when one or more of the columns being DISTINCTED is a CLOB type in Oracle.

I applied the following fixes for problems 1 and 2:
Problem 1: If an Oracle database is in use, change the WHERE clause to use "LENGTH([clob_column]) > 0".
Problem 2: If an Oracle database is in use, separate the query into multiple queries. In the first query, we select the DISTINCT fileEntryIds from the database. Then, we do a separate query(ies) to select all the column values for each fileEntryId. (I know this isn't ideal performance-wise to split it into multiple queries, but I couldn't find any way to do it in a single query.)

https://issues.liferay.com/browse/LPS-137112

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@mbowerman Sorry for the delay, I was on PTO.

Why not apply your changes unconditionally? The Oracle version should work for all cases, so I'd prefer to remove the conditionals and keep things simple and general.

**Comment by mbowerman** [comment]
Hi @adolfopa,

I would prefer not to apply the changes unconditionally for two reasons:

1. I'm not 100% sure if we handle the LENGTH function correctly for all database types, as I was unable to find any existing usages of the LENGTH function in a custom-sql.java file. I would have to test the function against all database types to have confidence that it doesn't cause regressions.
2. The performance with the new logic is not ideal, as it has to make multiple data calls (one initial database call, then one for each result that is returned). By separating out the Oracle logic, we preserve the ideal performance in other databases, and only Oracle databases will suffer the performance penalty.

**Comment by adolfopa** [comment]
@mbowerman I haven't found a single case of db vendor specific logic in regular persistence classes (only in infrastructure ones), so I'm not sure about this.

@shuyangzhou Can you take a look at this changes? Do you think these changes are fully portable or would we need to update the query processors to take this case into account?

**Comment by mbowerman** [comment]
Hi @adolfopa,

> @mbowerman I haven't found a single case of db vendor specific logic in regular persistence classes (only in infrastructure ones), so I'm not sure about this.

Sorry, I'm not sure what you mean by "regular persistence classes" vs. "infrastructure classes". [There is some Sybase-specific logic in UserFinderImpl](https://github.com/liferay/liferay-portal/blob/08a9072bc2b8367e3cb30378ad874fff90fd4056/portal-impl/src/com/liferay/portal/service/persistence/impl/UserFinderImpl.java#L183-L252), which I think is similar to the DLFileEntryFinderImpl.

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
@mbowerman By "infrastructure" I meant query processors, DB impls, etc. But you're right, there are usages in regular finders; I'll forward it to Brian then.

See https://github.com/liferay-lima/liferay-portal/pull/2157 for some minor SF changes.

**Pull request closed without merging**
