### PR TITLE
LPS-159744 DM - remove FF for icons in dropdowns

### PR DESCRIPTION
**Pull request by austinchiang**
- [x]  Check if checkin_js.ftl could be removed (Not possible, is it been used by a ToolbarItem :( )
- [x] Remove compate_to_js.ftl

Context:

The current dropdowns were rendered using the liferay-ui:menu-item taglib. This didn't allow to add icons in an easy way (in fact it caused a regression bug, and to solve this many changes in an "old" taglib were needed). So the approach was to replace that dropdowns and render Clay Dropdowns instead.

So in this pull I've tried to get rid of any xxxMenuItems configured in the backend side, as they were not going to be rendered anymore. But while doing this, I realised there were other dropdowns that need to be replaced (thus stories were created for [File entry detail](https://issues.liferay.com/browse/LPS-153216), [Media Gallery ](https://issues.liferay.com/browse/LPS-154737)and [Versions](https://issues.liferay.com/browse/LPS-154043)). Now, I see there are still some MenuItems that needs to be rendered in the clay dropdown:

Google Drive (DLOpenerGoogleDriveDLViewFileVersionDisplayContext.java)
Google Docs (in Media Gallery?) (GoogleDocsIGViewFileVersionDisplayContext.java)
Video shortcut (DLVideoExternalShortcutDLViewFileVersionDisplayContext.java)
So do not forward this pull until those options are migrated, otherwise they will not show up in the dropdowns and we will cause regressions.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
Hey @ambrinchaudhary I believe I fixed the rest of the tests (confirming with ci:test now).

There was one unique failure that happened in all the runs we trigged (some [current URL exception for DL](https://testray.liferay.com/reports/production/logs/2022-08/test-1-27/test-portal-acceptance-pullrequest(master)/4403/functional-upgrade-tomcat90-mysql57-jdk8/0/11/jenkins-console.txt.gz?authuser=0) ) caught in an upgrade test from 7.4 (https://testray.liferay.com/home/-/testray/case_results/1941007056) but I couldn't reproduce it locally. If it looks suspicious enough feel free to investigate it, otherwise we should be able to forward this.

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
New tests are failing after some changes...gonna have to fix them too @ambrinchaudhary 

whack-a-mole-cute

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/3352

**Pull request closed without merging**
