### PR TITLE
LPS-148306 Preserve original owner when updating a page

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @adolfopa 
The test WikiPage#CannotPublishWikiPageWithInvalidTitle failed because there is no Owner user for the Frontend page(before it is TestTest).
I want to confirm with you the Frontpage user should be empty or TestTest?
WikiUser

**Comment by adolfopa** [comment]
@Hanlf That doesn't look good; I'll work on a fix.

**Comment by adolfopa** [comment]
@Hanlf After a bit of investigation, that's expected now. From now on we'll consider the FrontPage as owned by the system (that's why it shows no user name there).

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @Jeremy-Ch 
Could you update the test WikiPage#CannotPublishWikiPageWithInvalidTitle according to the above comments, I am PTO today, thanks!

**Comment by Jeremy-Ch** [comment]
ci:test:bundle

**Comment by Jeremy-Ch** [comment]
Please see the new pull request: https://github.com/liferay-lima/liferay-portal/pull/2803

/cc @Hanlf

**Pull request closed without merging**
