### PR TITLE
LPS-125442 when the dataDefinitionId is used, the link on DDMStructureLink between the ddm and the fileentry is not needed and this entry is preventing the deletion of the fileEntryType when it is not used anymore

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive730 seems a flaky issue.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Review by adolfopa — CHANGES_REQUESTED** [review]
@AliciaGarciaGarcia Can we move this upgrade to the document-library-service module?

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa I made the changes you proposed, looking into your review :)

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
https://github.com/liferay-lima/liferay-portal/pull/1345

**Pull request closed without merging**
