### PR TITLE
LPS-143242 check if the article has an primary key to obtain the classPK ...

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
check if the article has primary key  to obtain the classPK or is generated by the values on the structure

If the structure has default values, an article (not saved) is generated. So I thought that maybe check if the article has primaryKey

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1287401_1130

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:echo

**Pull request closed without merging**
