### PR TITLE
LPS-181146 add LogCaptures to avoid unnecessary warning logs on WEBDav tests

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-181146

The `beforeClass`from `WebDAVEnvironmentConfigClassTestRule`  the message that was thrown was by `org.apache.poi.util.XMLHelper` and on `setUp` of `WebDAVOSXTest` the message origin is `org.apache.xmlbeans.impl.common.SAXHelper`

to test : 
```
❯ gw tI --tests "*WebDAV*"
```

From `portal/modules/apps/document-library/document-library-test`

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
It looks good. However, I could not reproduce the `XMLHelper` warning before your changes 🤷

**Comment by AliciaGarciaGarcia** [comment]
> It looks good. However, I could not reproduce the `XMLHelper` warning before your changes 🤷

Taking into account that the `XMLHelper` was the original log on the LPS,  maybe that what you couldn't reproduce was the `SAXHelper` warning.
That "hidden" error can be for 2 reasons

- the warning message has a countdown of 5 minutes. So to be again warned you should wait or reboot the server.
- one error encapsules the other so once you "LogCapture" one, the other is triggered.

@marcogalluzzi please remember once reviewed if you are ok, to put the label and/or forward it

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
