### PR TITLE
LPS-169119 Remove usages of toolbar item tag in DM

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/issues/browse/LPS-169119

Remove usage of legacy tag for toolbar items in DM, using dropdown items instead. As this was the only usage in the whole codebase, remove the tag itself and supporting classes too.

# How do I test it?

- Drop the Documents and Media widget in a content or widget page.
- Configure the portlet, enabling the "Show Actions" checkbox.
- Add a document if necessary.
- Enter the document details by clicking its title in the card.

You should see two main differences with respect to current master:

- The info button looks like an actual info button.
- Instead of a row of button -- one per available actions -- there should be a list of dropdow items to the right of the info button.

The actions should be the same as they were before, and all should work.

# Any pending work?

Yes. Dear frontend developers, I need your help fixing the visuals (see attached screenshot).
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@ambrinchaudhary @boton I need your help fixing the visuals (see attached screenshot).

**Comment by ambrinchaudhary** [comment]
@adolfopa done! This is how it looks now. Works perfect with the info panel

Screenshot 2022-11-22 at 16 53 21

**Comment by adolfopa** [comment]
Rebased and rerun baseline.
@ambrinchaudhary I removed an `aria-label` attribute (see last commit) as that tag doesn't support it. Should we ask them to add it? Or is that tag obsolete and should we use alternative tags/markup?

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
> 



> Rebased and rerun baseline. @ambrinchaudhary I removed an `aria-label` attribute (see last commit) as that tag doesn't support it. Should we ask them to add it? Or is that tag obsolete and should we use alternative tags/markup?

Sorry I missed this comment. It is ok for now. I think this taglib is kind of obsolete but there are few cases in portal. Let me check with FI the status of this taglib, and if needed we can create a separate task to replace all of them (or just this case, requires a little work).

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
The Poshi failures are related to this PR, I am fixing them.

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @adolfopa 
The failure of [semantic-versioning-jdk8/0/0](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122291//consoleText) should be related to this PR, could you please take a look?
```
jar:
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-portal/portal-kernel/classes/META-INF/maven/com.liferay.portal/com.liferay.portal.kernel
[propertyfile] Creating new property file: /opt/dev/projects/github/liferay-portal/portal-kernel/classes/META-INF/maven/com.liferay.portal/com.liferay.portal.kernel/pom.properties
 [sync-dir] Synchronizing /opt/dev/projects/github/liferay-binaries-cache-2020/.gradle/caches/modules-2/files-2.1 into /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1
 [sync-dir] 0 files synchronized in 383ms
     [echo] Executing Gradle task: baseline
     [exec] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
     [exec] > Task :classes UP-TO-DATE
     [exec] > Task :jar SKIPPED
     [exec] 
     [exec] > Task :baseline
     [exec] [Baseline Warning] Bundle Version Change Recommended: 89.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/88.0.0/930d212948bcca5874e500c2731386f112f38b5a/com.liferay.portal.kernel-88.0.0.jar
     [exec] Gradle build finished at 2022-11-28 04:29:21.590.
     [exec] 
     [exec] BUILD SUCCESSFUL in 2s
     [exec] 1 actionable task: 1 executed
     [exec] 
     [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/portal-kernel/build/reports/profile/profile-2022-11-27-20-29-19.html
     [exec] A fine-grained performance profile is available: use the --scan option.
     [exec] 
```

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
