### PR TITLE
LPS-160224 DeepL translator

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@yasuflatland-lf I've squashed all your SF commits, regenerated build lang and added an additional commit with the (imo) last necessary SF changes. Please review the last commit and if everything is fine we can forward it to Brian.

**Comment by adolfopa** [comment]
* Add my repo as a remote: `git remote add adolfopa git@github.com:adolfopa/liferay-portal.git'
* Fetch the branch: `git fetch adolfopa pr-3422`
* Checkout it: `git checkout pr-3422`

**Comment by yasuflatland-lf** [comment]
@adolfopa Thank you for the info! I'll check at my local and get back to you.

**Comment by adolfopa** [comment]
The `Boolean` business sounds good.

About the translation, you're probably seeing the automatic one. That's simply a copy of the original message (it will be traduced to japanese eventually). If that's not the case, we can fix it in a different ticket to avoid blocking the pr.

**Comment by yasuflatland-lf** [comment]
@adolfopa No, it's not even automated translation. I see the message-key itself, even in English. Let me look into it a little bit further and I couldn't figure out, I'll skip it for now. As to Boolean, I revert it and send PR here.
スクリーンショット 2022-09-14 5 42 03

**Comment by adolfopa** [comment]
Closing in favor of https://github.com/liferay-lima/liferay-portal/pull/3485

**Pull request closed without merging**
