### PR TITLE
LPS-158914 prevent NPE

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-158914 prevent NPE

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@AliciaGarciaGarcia merged to master and the temp branch

**Pull request closed without merging**
