### PR TITLE
Lps 139816

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-139816

Update from #2693: Made adjustments based on conversation [2693#discussion_r794388454](https://github.com/liferay-lima/liferay-portal/pull/2693#discussion_r794388454)

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
