### PR TITLE
LPS-189037, LPS-189441, LPS-189444 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://liferay.atlassian.net/browse/LPS-189037
https://liferay.atlassian.net/browse/LPS-189441
https://liferay.atlassian.net/browse/LPS-189444

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
