### PR TITLE
LPS-159744 (DM icons - remove dev FF) | master

### PR DESCRIPTION
**Pull request by liuxingye**
On Hold until https://issues.liferay.com/browse/LPS-154043 is completed

- [x] ~~Check if checkin_js.ftl could be removed~~ (Not possible, is it been used by a ToolbarItem :( )
- [x] Remove compate_to_js.ftl

**Context**: 

The current dropdowns were rendered using the `liferay-ui:menu-item` taglib. This didn't allow to add icons in an easy way (in fact it caused a regression bug, and to solve this many changes in an "old" taglib were needed). So the approach was to replace that dropdowns and render Clay Dropdowns instead. 

So in this pull I've tried to get rid of any _xxxMenuItems_ configured in the backend side, as they were not going to be rendered anymore. But while doing this, I realised there were other dropdowns that need to be replaced (thus stories were created for [File entry detail](https://issues.liferay.com/browse/LPS-153216),  [Media Gallery ](https://issues.liferay.com/browse/LPS-154737)and [Versions](https://issues.liferay.com/browse/LPS-154043)). Now, I see there are still some MenuItems that needs to be rendered in the clay dropdown: 

- Google Drive (_DLOpenerGoogleDriveDLViewFileVersionDisplayContext.java_)
- Google Docs (in Media Gallery?) (_GoogleDocsIGViewFileVersionDisplayContext.java_)
- Video shortcut (_DLVideoExternalShortcutDLViewFileVersionDisplayContext.java_)

So do not forward this pull until those options are migrated, otherwise they will not show up in the dropdowns and we will cause regressions.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
Resent here with more fixes: https://github.com/liferay-lima/liferay-portal/pull/3343

**Pull request closed without merging**
