### PR TITLE
LPS-149694 Create placeholder view for DM size limit settings

### PR DESCRIPTION
**Pull request by adolfopa**
@ambrinchaudhary @boton Here I've created an empty JSP and wired it so that is shows up in site settings. Note that there will be 2 "Size Limit Configurations" available: the autogenerated one and the placeholder. This is intentional, to make it easier to compare both views. I'll remove the default one later.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Thanks a lot @adolfopa, great idea having both "components". I will start with this ASAP.

**Comment by ambrinchaudhary** [comment]
Hey @adolfopa, I added a commit that renders the new frontend component. Now you have to pass data to the component, just like you did [here](https://github.com/liferay/liferay-portal/blame/master/modules/apps/depot/depot-web/src/main/java/com/liferay/depot/web/internal/display/context/DepotAdminDLDisplayContext.java#L58-L58), and process the action. As we spoke, to do this in system and instance settings I need you to render a JSP for them just like you did here. 

Let me know if I can help you with something. Thanks!

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by adolfopa** [comment]
Will send a followup pr with additional changes later.

**Pull request closed without merging**
