### PR TITLE
LPS-171687 Removes descriptive view for the moment

### PR DESCRIPTION
**Pull request by ealonso**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-171687)

Adapt asset list entry item selector to use default item selector views.

## Proposed solution

In order to make possible adapt asset list entry item selector view to use default item selector views it adds a new interface called **TableItemView** on **item-selector-api**. In that way we can customize the table view of item selector. Also, it includes a default implementation **DefaultTableItemView**, it is going to be used if the item selector didn't provide a new one.

Result with default view

Window_y_Home_-_Liferay_DXP__Editing_

Result after customization

Home_-_Liferay_DXP__Editing_

Please let me know what do you think abut this approach.

Thanks!!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
Hi @ealonso, After the changes, the list view is missing when selecting a collection in the AP widget, the reproduce steps as below, Could you help to take look? Thanks.

1. Add a widget page with an asset publisher
2. Go to the page
3. Go to the configuration of the AP widget
4. Select the collection
5. View the view styles in the modal (Details see the image)

image

**Comment by ealonso** [comment]
Hey @Jeremy-Ch,

I did it on purpose, I removed it in the last commit [1678886](https://github.com/liferay-lima/liferay-portal/pull/3878/commits/16788866575920d4effb802f9a8def9c1a23488f)

**Comment by Jeremy-Ch** [comment]
> Hey @Jeremy-Ch,
> 
> I did it on purpose, I removed it in the last commit [1678886](https://github.com/liferay-lima/liferay-portal/pull/3878/commits/16788866575920d4effb802f9a8def9c1a23488f)

Hi @ealonso OK, Thanks. I will update the poshi tests once the pr is ready to forward.

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
Updated the Poshi tests and see the new pr: https://github.com/liferay-lima/liferay-portal/pull/3891

**Pull request closed without merging**
