### PR TITLE
LPS-128046 add delete actions to let management toolbar to delete MetadataSets

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@julien you will need to rebase your work on top of this.

**Comment by julien** [comment]
@4lejandrito thanks for notifying

**Review by 4lejandrito — APPROVED** [review]

**Pull request closed without merging**
