### PR TITLE
LPS-156207 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-156207
https://issues.liferay.com/browse/LPS-154443

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:reevaluate:1317401_3859

**Comment by Jeremy-Ch** [comment]
ci:reevaluate:1317401_3859

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:reevaluate:1317401_3859

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1387401_1748

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1327401_4481

**Comment by adolfopa** [comment]
ci:reevaluate:1327401_4481

**Comment by liuxingye** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/3200

**Pull request closed without merging**
