### PR TITLE
LPS-181933 Disable SPA in Add Category button within Message Boards

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hey guys,

The first solution I sent for this LPS fixed the case... sometimes. 

It's hard to figure out  a pattern about when it is actually reproducible, but I managed to figure out disabling SPA is not happening anymore. Actually, I've seen we do the same in our Management Toolbar so that avoids cases like this in many occasions through our portal.

Thanks!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — CHANGES_REQUESTED** [review]
Hey @antonio-ortega, thanks for looking deeper in this issue. I'm ok with disabling SPA in this case, but I wonder if it should be put in the form of the [edit category page](https://github.com/ambrinchaudhary/liferay-portal/blame/master/modules/apps/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/edit_category.jsp#L86-L86), not in the link. 
In the mayority of cases in portal where SPA is disabled this is put in the form tag with an attribute `data-senna-off="true"`, and it makes sense because you may access to this page through different links. Could you please test if this also works, and then change it? Thanks a lot!

**Comment by antonio-ortega** [comment]
Hey @ambrinchaudhary ,

That wouldn't work because adding `data-senna-off="true"` for the form is going to force a full reload when saving form data, but our problem is when we initially load the form. Our `name` field is being populated as soon as we load the form, that's the reason why we should force a full reload to open the form rather than to save it.

I don't have a wide knowledge about Message Boards to know from how many places we can access this form, but we should probably check whether this issue is also reproducible there.

If there are too many place to disable SPA from all the possible access, we might need to re-think the solution and have a look to figure out why in this form, `name` field is automatically populated.

I hope this helps!

**Comment by ambrinchaudhary** [comment]
Thanks for the explanation @antonio-ortega. 

I've checked MB and you can access to this page through _subscribe/unsubscribe_ actions, or other actions like _delete_ or _restore_ which implies a reload of the content, but all of them form icons `<liferay-ui:icon>`, not links (I don't know if this is really relevant). 

For now I am forwarding this. Thanks!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Review by ambrinchaudhary — APPROVED** [review]

**Pull request closed without merging**
