### PR TITLE
LPS-206531 Inconsistent behavior when tagging/categorizing a document belonging to an Asset Library from a connected site

### PR DESCRIPTION
**Pull request by manuelRives**

### CODE REVIEW

**Comment by manuelRives** [comment]
ci:test:sf

**Review by marcogalluzzi — COMMENTED** [review]
I'm not 100% sure about using the `repositoryId` here. I will add Adolfo as reviewer.

**Comment by robertoDiaz** [comment]
Hi @marcogalluzzi 

it seems to be right.

In this case the repositoryId is the groupId of the repository you are seeing.

In the default DL configuration (show the current group repository) repositoryId will be the themeDisplay.getScopeGroupId(), so it will behave as it did.

If you select an AL folder as root folder, we don't want to use the themeDisplay.getScopeGroupId() anymore, since it will show elements that should not be used in AL scope. In this case the repositoryID it will be AL's groupId: so the getCurrentAndAncestorSiteAndDepotGroupIds will return the AL and the global group ids, and this is the expected behavior.

**Review by robertoDiaz — COMMENTED** [review]
As said in my previous comment the use of the repositoryId seems to be ok, anyway, we have to know if it could 0 in any case (because it will break the current behavior)

To avoid this, and minimize possible problems, we could 

1. guarantee that the repositoryId is allways populated and is the right one
2. (if 1 is not possible) use the scopeGroupId as fallback if repositoryId is 0

**Comment by manuelRives** [comment]
Hi @robertoDiaz, @marcogalluzzi

In both cases that I have modified repositoryId is validated to not have a 0 value.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/display/context/DLAdminDisplayContext.java#L313C1-L337C3

https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/edit_file_entry.jsp#L21-L26

**Review by marcogalluzzi — APPROVED** [review]

**Comment by adolfopa** [comment]
I don't think the usage of the repositoryId is correct. You're assuming that the repository ID is a valid group ID, but it can refer to a group ID (for the default repository) or an entry in the RepositoryEntry table. I understand you need to use the repository ID in some cases, but the logic needs to take into account all cases; e.g.:
```
long getGroupId(long scopeGroupId, long repositoryId) {
    Repository repository = RepositoryLocalServiceUtil.fetchRepository(repositoryId);

    if (repository != null) {
        return repository.getGroupId(); 
    }

    Group group = GroupLocalServiceUtil.fetchGroup(repositoryId);

    if (group != null) {
        return group.getGroupId();
    }

    return scopeGroupId;
}
```

**Comment by manuelRives** [comment]
Hi @adolfopa,

In this case, with the getGroupId we use and the usage of that Id I think it is safe to use the repositoryId.

The method we use tries to retrieve the groupId of the folder and in case it can't get it it uses the configured repository id, and in the worst case it uses the `_themeDisplay.getScopeGroupId())`; which is the original behavior before these changes.
	
```
public long getRepositoryId() {
		if (_repositoryId != 0) {
			return _repositoryId;
		}

		long repositoryId = 0;

		Folder folder = getFolder();

		if (folder != null) {
			repositoryId = folder.getRepositoryId();
		}
		else {
			repositoryId = _dlPortletInstanceSettings.getSelectedRepositoryId();
		}

		if (repositoryId == 0) {
			repositoryId = ParamUtil.getLong(
				_httpServletRequest, "repositoryId",
				_themeDisplay.getScopeGroupId());
		}

		_repositoryId = repositoryId;

		return _repositoryId;
	}
```

Also, since the use of this groupId is to get the Ancestors of the item through getCurrentAndAncestorSiteAndDepotGroupIds, any Id within the site we want to use should be a valid Id.

But if you see any case that I missed, I'll check it without problems

**Comment by adolfopa** [comment]
@manuelRives It is not safe; `folder.getRepositoryId()` may not be a group ID (that assumption is wrong in general).

**Comment by manuelRives** [comment]
@adolfopa, But it would be a valid Id within the site, right?

**Comment by manuelRives** [comment]
Hi @adolfopa, Updated with suggested changes. Thank you!

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1407401_8420

**Comment by manuelRives** [comment]
The test failures do not seem to be related to this pull. Forcing forward.

**Comment by manuelRives** [comment]
ci:forward:force

**Pull request closed without merging**
