### PR TITLE
LPS-118398 Baseline

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hey @adolfopa @AliciaGarciaGarcia, text (like the title of a web content) and textarea fields are not showing up in the preview... I only see "HTML" fields. Could you please check?

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/638

**Pull request closed without merging**
