### PR TITLE
LPS-191931 check if message is null

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-191931

```
com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest > testGetSharepointObjectsByFileName STARTED
     [exec] 
     [exec] com.liferay.sharepoint.soap.repository.connector.SharepointConnectionTest > testGetSharepointObjectsByFileName FAILED
     [exec]     java.lang.NullPointerException
     [exec]         at com.liferay.sharepoint.soap.repository.connector.internal.util.RemoteExceptionSharepointExceptionMapper.map(RemoteExceptionSharepointExceptionMapper.java:30)
     [exec]         a
```

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sharepoint

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sharepoint

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sharepoint

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
test failures do not show the NPE.
it shows:  `com.liferay.portal.kernel.exception.SystemException: com.liferay.sharepoint.soap.repository.connector.SharepointException: Unable to communicate with the Sharepoint server http://cloud-10-0-15-44:80/`

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@austinchiang If the error mentioned by @AliciaGarciaGarcia is expected, please forward this pr.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_13639

**Comment by austinchiang** [comment]
Errors are from https://liferay.atlassian.net/browse/LPS-182299

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
