### PR TITLE
LPS-168067 HR_221 SR is not announcing "Open Graph Image" Dialog box

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Follow up on https://github.com/liferay-lima/liferay-portal/pull/4381 
Already reviewed by PEDS

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
