### PR TITLE
LPS-157775 on some cases the steps needed for upgrading the configuration are not fulfilled due the version so re-upgrade it again

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-157775

- LPS-157775 extract methods of upgrade dl configurations processes to reuse several times
- LPS-157775 add new step because sometimes the configuration is not correctly upgraded, so we must redo it
- LPS-157775 only do the upgrade if there was not user changes on the new properties or the old ones are still with data
- LPS-157775 semver
- LPS-157775 extract methods to clarification

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:upgrade

**Comment by AliciaGarciaGarcia** [comment]
ci:test:upgrade

**Review by robertoDiaz — CHANGES_REQUESTED** [review]
As agreed in slack in order to make it clear that we are repeating some upgrades, instead of add all the logic in a single upgrade step class I suggest to add some upgrade step classes with the same name as original ones.

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
One comment only: the new Helper doesn't look to be generic or some method names should be changed. For instance, method `DLConfigurationUpgradeHelper.updateSystemConfiguration()` suggests the update of the entire DL System Configuration but it isn't the case.

Some methods of the Helper are currently generic while others are not.

While doing what Roberto suggested you may think about it.

**Review by robertoDiaz — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:upgrade

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:upgrade-all

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
