### PR TITLE
LPS-191479 - Normalized URL doesn't point to the same source as the accented version did

### PR DESCRIPTION
**Pull request by henriquelimadotcom**
**Ticket:** https://liferay.atlassian.net/browse/LPS-191479
@dacousalr 

REBASE ERROR

# Problem Description
Previously, it was possible to create web content containing accented links in the application. However, due to recent changes, this functionality was removed, resulting in broken accented links for customers who created content during the period when this option was available. This situation has caused disruptions and a negative impact on the user experience, as well as the integrity of friendly URLs.

# Solution Objective
The proposed solution aims to restore the functionality of the existing accented links, allowing them to function correctly, even though it will no longer be possible to create new links with accents in the future. The focus is on ensuring the continuity of the integrity of friendly URLs and providing a consistent user experience.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:friendly-url

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1347401_4494

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1347401_4494

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
