### PR TITLE
LPS-128068 Tensorflow download issue on CentOS

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @liuxingye,

Can you please verify this fixes the issue before forwarding?

Thanks!

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:bundle

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
