### PR TITLE
LPS-96800, LPS-154007 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-154007
https://issues.liferay.com/browse/LPS-96800

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
