### PR TITLE
LPS-165484 Dot in friendly URL should be replaced like the Spaces

### PR DESCRIPTION
**Pull request by sontruongces**
Hi team,

This is the PR for the [LPS-165484](https://issues.liferay.com/browse/LPS-165484), the original has passed my review at sontruongces#48. Please help me to review and give feedback.

Thanks!
cc: @quanhuynhces

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
We have to talk about the change of behavior on the component.

And
Test failure relevant with this PR .[com.liferay.friendly.url.internal.util.FriendlyURLNormalizerImplTest.testNormalizeWithEncodingRemove](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/267719//testReport/com.liferay.friendly.url.internal.util/FriendlyURLNormalizerImplTest/testNormalizeWithEncodingRemove)


Please change the test

**Comment by adolfopa** [comment]
@sontruongces This is too much of a change, as this will affect friendly urls across all the portal. The fix should be applied locally to web content (similar to what we did for documents) so that we don't break other friendly urls.

**Pull request closed without merging**
