### PR TITLE
LPS-155979 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-155979

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:close

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/3150

**Pull request closed without merging**
