### PR TITLE
LPS-118602 Delete structure link when updating DLFileEntry's type

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @noornajj:

> https://issues.liferay.com/browse/LPS-118602
> 
> The issue here was caused by a thrown exception, MustNotDeleteStructureReferencedByStructureLinks, in DDMStructureLocalServiceImpl.deleteStructure(). When a file entry is updated to use a different document type, the DDMStructureLink table is not updated to delete the link to the old document type. Therefore, deleteStructure thinks that the document type is still in use which, in turn, leads to the exception to be thrown.
> To solve this issue, I updated the updateFileEntry method to delete the old structure link if the document type is being changed. I also added a condition that the old document type must not be a Basic Document because a structure link is not created for Basic Document types.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/612

**Pull request closed without merging**
