### PR TITLE
[TS] LPS-153234 Move publishButton disabling at draft saving

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

https://issues.liferay.com/browse/LPS-153234

Previous discarded PR: https://github.com/liferay-lima/liferay-portal/pull/3030

Issue:
 "Publish Button" becomes disabled in Blogs widget when adding a "New entry" if we have a vocabulary with associated asset type "Blogs Entry" set to "Required" whether we choose a required category or not.
 
 
image
---------------
image

Solution:
I discussed this issue and the previous PR, and upon debugging the code, we discovered that the frontend request does not actually send the filled "categoryIds" value during **automatic** draft saving. So after draft saving the required category stays empty (we concluded that this is another issue and needs an LPS ticket [LPS-153629](https://issues.liferay.com/browse/LPS-153629)). That is why "categoryIds" is always empty in isMissingRequiredCategory() when saving draft, so the validation will always fail (and the Publish button won't turn enabled even after selecting category).
The solution for this issue now is to move the "publishButton" disabling after the validations/draft saving process to prevent unnecessary disabling, because the publish process (and the "Save as draft" process) will check the required categories, but unlike the automatic draft saving, publish (and "Save as draft") will save the required category too. (and with the other LPS, the root cause will be solved)

Please review my PR!

Best regards,
Évi

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hi @evibudai, 

I'm looking into your solution and although I understand the issue, the fix does not make sense. See, we are disabling the publish button just before the `Liferay.Util.fetch` is triggered, and the idea is to enable it when it finishes. But you moved the code outside the _fetch_ statement so this is useless (will go from disabled to enabled inmediately, and this is like not disabling it at all).

So here I have two questions:  

1. Do we get an especific error during this draft saving? If it does, and enters on the `catch` statement, we could enable here the publish button. If it doesn't, can't we send an specific error and catch it? 
2. Why `categoryIds` is not sent? Although, it could happen that you don't fill the value, and draft is saved and we have the same problem.

**Review by ambrinchaudhary — CHANGES_REQUESTED** [review]
see https://github.com/liferay-lima/liferay-portal/pull/3039#issuecomment-1125920283

**Comment by evibudai** [comment]
Hi @ambrinchaudhary,
I'm answering the second question first to hopefully clear things a bit.

It seems like sending categoryIds was never implemented, but that is why I created the mentioned LPS [LPS-153629](https://issues.liferay.com/browse/LPS-153629). 
What I meant to write is that, when we select a category, it appears on frontend, but is never sent during automatic draft saving. Looking at the automatic saving request, we can see, that "assetCategoryIds" is missing from the query/form parameters. So in backend, categoryIds will be always an empty array, and if the category is set to required, the validation will fail.                                                                                                    
So the real solution would be to solve the LPS first that I linked. That solution would mean, that when the required category is not selected, the publish button remains disabled, but when it is selected, the publish button is enabled. Because right now it does not matter if we select the category, since it is missing from the request.

I'm still trying to find an answer to the first question.

**Comment by evibudai** [comment]
Hi @ambrinchaudhary,
I discussed the issue with our senior TS and to preserve the user experience, we concluded that the best solution is to solve the other LPS (https://issues.liferay.com/browse/LPS-153629) the PR for this is: https://github.com/liferay-lima/liferay-portal/pull/3048
And to move the publish button enabling to the finally block. This way the user can see the "Can not save draft" error message, but is able to click the "Save as draft" or the "Publish" button. So now the automatic draft saving which is a background task does not interfere with the saving or publishing process, and the "Save as draft" and "Publish" buttons are validating the missing/required parameters if it is necessary.

**Comment by ambrinchaudhary** [comment]
> to preserve the user experience, we concluded that the best solution is to solve the other LPS (https://issues.liferay.com/browse/LPS-153629) the PR for this is: https://github.com/liferay-lima/liferay-portal/pull/3048
> And to move the publish button enabling to the finally block.

That sounds much better! Thank you @evibudai

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
