### PR TITLE
LPD-15182 use escaped value

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPD-15182

how to test it: 

--

1. Change User First Name to `'"></option>`
2. Create a page with the following name: `'"></option>`
3. Add a Page Flags widget to the page created in step 2
4. Click "Flag This Page"
5. Select "Other Reason" as the reason
6. In the Other Reason field, enter `'"></option>`
7. Click the Report button
8. Profile Menu > Notifications

--

1. Change User First Name to `'"></option>`
2. Add a Message Board thread with the following subject `'"></option>`
3. View the message added in step 2
4. Click the Report flag
5. Select "Other Reason" as the reason
6. In the Other Reason field, enter `'"></option>`
7. Click the Report button
8. Profile Menu > Notifications 
9. Vulnerable Result: JavaScript is executed (three times)
10. Fixed Result: JavaScript is encoded and is not executed

image

- LPD-15182 use the escaped value
- LPD-15182 rename method
- LPD-15182 add test to check the body of the message on flags notification

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
@robertoDiaz 

i changed the asset publisher value you found too. Thanks

**Review by robertoDiaz — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1277401_11187

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward:force

**Pull request closed without merging**
