### PR TITLE
LPS-114056 - Apply the use of clay content taglib in site-item-selector-web

### PR DESCRIPTION
**Pull request by marcoscv-work**
@ambrinchaudhary @boton

As part of our effort to Improve HTML Layout Generation Strategies in DXP, here a PR about changing autofit-* and sheet-* for clay:sheet* and clay:content*

This "PR" updates markup with new taglibs. What we expect is to see the same visual design, so no visual changes are required.
The way to validate the changes is to see the same visual result. if is there any previously agreed difference it would be correctly pointed in comments

LPS-114035 - Apply the use of clay content taglib in journal-content
LPS-114036 - Apply the use of clay sheet and clay content taglib
LPS-114037 - Apply the use of clay sheet taglib in journal-web
LPS-114050 - Apply the use of clay content taglib in ratings-taglib
LPS-114051 - Apply the use of clay content taglib in redirect-web
LPS-114056 - Apply the use of clay content taglib in site-item-selector

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
resend here:
https://github.com/liferay-lima/liferay-portal/pull/134

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/134

**Pull request closed without merging**
