### PR TITLE
LPS-167443 KB CKEditor custom required message

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
By default, editors take its name to render a validation message, and in this case was content-editor. Fortunately this can be manually defined. 

**Before:** 

Screenshot 2022-11-03 at 14 24 36

**After:** 

Screenshot 2022-11-04 at 11 40 52

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
The same problem exists for the editor of a template, file `edit_kb_template.jsp`. Would it be a good idea to also fix this one in this PR?

**Comment by ambrinchaudhary** [comment]
> The same problem exists for the editor of a template, file `edit_kb_template.jsp`. Would it be a good idea to also fix this one in this PR?

Totally right! I've updated the commit to cover it. Good catch!

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
