### PR TITLE
LPS-151357 | Automate LPS-151172

### PR DESCRIPTION
**Pull request by jaimelr10**
Description: Creation of Priority 4 test to verify that a template is rendered give some preconditions as described in [LPS-148397](https://issues.liferay.com/browse/LPS-151172)

Jira Ticket: https://issues.liferay.com/browse/LPS-151357

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Putting on hold until https://issues.liferay.com/browse/LPS-151172 is fixed

**Comment by adolfopa** [comment]
The fix won't be merged in the near future, so I'm closing this to remove background noise.

**Pull request closed without merging**
