### PR TITLE
LPS-172546 KB Interacion and Animations with Product Menu

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Story requirements: https://issues.liferay.com/browse/LPS-166645
Dependant Clay Issue: https://github.com/liferay/clay/pull/5298 (I may need to change animation duration after this issue is merged in portal)

**Final result:**

https://user-images.githubusercontent.com/8373764/212881929-df335b35-3899-4e96-ad59-02d5369ef4a7.mp4

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
As far I can see the changes are OK

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
