### PR TITLE
LPS-154652 Convert .heic to .jpg for profile image

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-154652

/cc @hongvo2308

### Solution notes

The solution models [LPS-151510](https://issues.liferay.com/browse/LPS-151510), which has adaptive media invoke imagemagick in order to perform the conversion. In this case, the solution is localized to image-uploader-web.

The original solution from the TSE created a new ImageMagickException with a more detailed error message telling a user to reach out to their portal administrator to install ImageMagick with HEIC support.

I didn't think that was necessary (the default Unexpected Error message seemed okay to me) and so I removed the extra complexity to avoid the kernel exception package version update. Let me know if you disagree, and I can instead move it to an internal package in image-uploader-web as an alternate way to avoid the kernel exception package version update.

### Testing steps

Note from the TSE, applicable to developers running Linux:

> PS: You will need to install the ImageMagick based on these instructions https://gist.github.com/hurricup/e14ae5bc47705fca6b1680e7a1fb6580 and [LPS-151510](https://issues.liferay.com/browse/LPS-151510) to test.
Update the portal-ext.properties with this value
`mime.types.web.images=image/gif,image/jpeg,image/pjpeg,image/png,image/x-png,image/heic`

If your local system is not Linux, you can also install a minimal ImageMagick with HEIC support to a Liferay Docker container (the default ImageMagick installed to the Docker container does not have HEIC support) using the instructions mentioned in the comment on [LPS-154652](https://issues.liferay.com/browse/LPS-154652)

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@holatuwol I don't think putting this logic in the action is the right approach. Image processing can be a costly operation, and here it is performed before the DL service does any size validation; also, the image upload portlet can be accessed by guest, so this could easily lead to a DoS attack.

This kind of processing should be performed asynchronously, and ideally in a different process (like AM or the old preview generation does).

**Comment by hongvo2308** [comment]
Hi @adolfopa 
I am looking at this ticket now. I understand that this process is heavy and it should be executed in an async thread. However, this function is triggered in an MVCActionCommand. So could you suggest a good approach for this situation?
For example:
 - What should be displayed during the process on the UI?
 - How to respond to the current actionResponse when the process is finished?
 - And what if the user cancels the process during waiting?
Thank you

**Pull request closed without merging**
