### PR TITLE
LPS-157803 File name label does not appear for Video Shorcuts

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**BEFORE:**
Screenshot 2022-07-07 at 12 32 30

**AFTER:**

Screenshot 2022-07-07 at 13 00 35

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]
LGTM

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
