### PR TITLE
LPS-172520 Specific DPT not working for kb articles

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-172520

Depending on the status, KB articles use the article ID or resource prim key as class PK. This means we need to check both when looking for articles or related resources.

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-172520.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1397401_2520

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
