### PR TITLE
LPS-132005 Image not selectable from item selector when translating Web Content

### PR DESCRIPTION
**Pull request by boton**
**Details:** https://issues.liferay.com/browse/LPS-132005

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @boton could you please add a link to the JIRA Ticket in the description (just to follow the pr etiquette).

Anyway, unassigning this from myself and adding `backend review needed` label, I'm not sure if that's the best way to get the namespace so it's better that someone of the backend army take a look.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
