### PR TITLE
LPS-148095 blogs more entries card layout stacked

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-148095

We want to recover the old layout (50/50 layout) in blogs more entries.

In the past, we applied some CSS in this fix http://issues.liferay.com/browse/LPS-132211 maintaining this layout but [the limits](https://github.com/liferay-lima/liferay-portal/pull/1899/commits/a67ea1a2cfe0056fbe48d56818a57a8f23e05d91) are hardcoded and some changes I don't know which ones break it.

With this PR, instead of trying to fit all space and break when the spacing changes, we want to fit 50% and put min and max limits, but without causing a regression on http://issues.liferay.com/browse/LPS-132211

@fortunatomaldonado Can you please check if this solution works for you? Also, I'm checked but Can you please double-check that this PR does not cause a regression on http://issues.liferay.com/browse/LPS-132211?

### 1 col (full width)
image

### 2 cols (70%)
image

### 2 cols (30%)
image

### 1 col (full width)
image

### 2 cols (70%)
image

### 2 cols (30%) we need to mantain entries stacked with this little space
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
I was able to test this and it does not seem to cause any regression to LPS-132211.

**Comment by liuxingye** [comment]
@boton Those POSHI failures are not related to your changes. They are should be working fine after [LPS-148145](https://issues.liferay.com/browse/LPS-148145). Thanks.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
