### PR TITLE
LPS-205933 We have to use the right models (DLFolder instead of Folder)

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
Hi @robertoDiaz,

There is a unique failure caused by this pull request.
[com.liferay.document.library.internal.exportimport.data.handler.test.FolderStagedModelDataHandlerTest
](https://testray.liferay.com/home/-/testray/case_results/2487036907)
```
[beanshell]      [exec] com.liferay.document.library.internal.exportimport.data.handler.test.FolderStagedModelDataHandlerTest > testCleanStagedModelDataHandler STARTED
[beanshell] 2024-01-11 17:35:10.530 ERROR [com.liferay.document.library.test-executor-thread][LoggerExportImportLifecycleListener:390] Staged model {class: com.liferay.document.library.kernel.model.DLFolder, groupId: 36073, uuid: eaf01abe-11bd-2deb-c377-441377e37349} import failed
[beanshell] com.liferay.document.library.kernel.exception.NoSuchFolderException: No DLFolder exists with the primary key 36086
[beanshell] 	at com.liferay.portlet.documentlibrary.service.persistence.impl.DLFolderPersistenceImpl.findByPrimaryKey(DLFolderPersistenceImpl.java:14879) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.documentlibrary.service.persistence.impl.DLFolderPersistenceImpl.findByPrimaryKey(DLFolderPersistenceImpl.java:14897) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.documentlibrary.service.impl.DLFolderLocalServiceImpl.getFolder(DLFolderLocalServiceImpl.java:355) ~[portal-impl.jar:?]
[beanshell] 	at sun.reflect.GeneratedMethodAccessor1410.invoke(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy143.getFolder(Unknown Source) ~[?:?]
[beanshell] 	at com.liferay.document.library.internal.exportimport.data.handler.FolderStagedModelDataHandler.doImportStagedModel(FolderStagedModelDataHandler.java:297) ~[?:?]
[beanshell] 	at com.liferay.document.library.internal.exportimport.data.handler.FolderStagedModelDataHandler.doImportStagedModel(FolderStagedModelDataHandler.java:53) ~[?:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importStagedModel(BaseStagedModelDataHandler.java:358) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:380) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:366) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.doImportReferenceStagedModel(StagedModelDataHandlerUtil.java:453) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importReferenceStagedModel(StagedModelDataHandlerUtil.java:295) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importReferenceStagedModels(BaseStagedModelDataHandler.java:854) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importStagedModel(BaseStagedModelDataHandler.java:356) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:380) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.test.util.lar.BaseStagedModelDataHandlerTestCase.testCleanStagedModelDataHandler(BaseStagedModelDataHandlerTestCase.java:240) [bundleFile:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_381]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_381]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_381]
[beanshell] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344) [bundleFile:?]
[beanshell] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [bundleFile:?]
[beanshell] 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90) [bundleFile:?]
[beanshell] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [bundleFile:?]
[beanshell] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50) [bundleFile:?]
[beanshell] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20) [bundleFile:?]
[beanshell] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307) [bundleFile:?]
[beanshell] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86) [bundleFile:?]
[beanshell] 	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_381]
[beanshell] 2024-01-11 17:35:10.533 ERROR [com.liferay.document.library.test-executor-thread][LoggerExportImportLifecycleListener:390] Staged model {class: com.liferay.document.library.kernel.model.DLFolder, groupId: 36073, uuid: b2574042-82c0-208b-5152-cefe9df59091} import failed
[beanshell] com.liferay.exportimport.kernel.lar.PortletDataException: No DLFolder exists with the primary key 36086
[beanshell] 	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importStagedModel(BaseStagedModelDataHandler.java:399) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:380) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:366) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.doImportReferenceStagedModel(StagedModelDataHandlerUtil.java:453) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importReferenceStagedModel(StagedModelDataHandlerU
```

**Comment by robertoDiaz** [comment]
ci:reevaluate:1377401_15848

**Comment by robertoDiaz** [comment]
Hey @adolfopa 

Since it seems that the previous logic broke some tests, I recheck this and I've found an alternative solution.

I think that it has to be reviewed by @4lejandrito's team. Is it right?

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@robertoDiaz Yes, as this changes part of the Staging classes, we need to send this to them.

**Comment by adolfopa** [comment]
LGTM, by the way :-)

**Comment by 4lejandrito** [comment]
:wave: 

First of all, I think it would be great if you could add an integration test.

Then send it to [our repo](https://github.com/liferay-headless/liferay-portal) so that we add it to our queue.

**Comment by robertoDiaz** [comment]
I've agreed with @4lejandrito that they are going to handle this ticket.

Closing and resending to @liferay-headless

**Pull request closed without merging**
