### PR TITLE
Translation destroys html structure/text data

### PR DESCRIPTION
**Pull request by matthiasblaesing**
While testing the DeepL translator we noticed a strange behavior of the translation system. Seemingly trivial paragraphs looked strange after translation. Investigating the problem I could hunt this down into the way the DeepL API is called.

DeepL needs to know whether plain text or HTML is translated. In many cases using the "text" format works ok, but in our "corner cases", translation is only well usable if DeepL is told, that HTML is translated. We noticed for example, that DeepL inserted fullstops  outside the expected tags, damaging the HTML structure.

While investigating I also noticed, that plain text is ran through "unescapeHTML", although not HTML is provided, basicly destroying text, that contains "\&amp;" (yeah worst case scenario).

To fix both issues frontend and backend both need to take into account, in which format is used in a field. The approach taken here only fixes the codepath for DeepL, ensuring that the old codepath can still be used by the other translators. The information, whether HTML or plain text is transfered in a field is send is encoded in a map alongside the existing "fields" entry. That way unmodified callers can ignore that codepath, while fixed callers can use this improved path.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by matthiasblaesing** [comment]
Steps to reproduce:

- Setup liferay 7.4.3.83 with:
  - Binary: https://github.com/liferay/liferay-portal/releases/download/7.4.3.85-ga85/liferay-ce-portal-tomcat-7.4.3.85-ga85-20230711212016429.7z
  - Language: German
  - Timezone: Central European Summertime
- Configure DeepL Translator with a free token
- Go to "Inhalte" ("Contents & Data") -> "Webcontent" ("Web Content")
- Create a "Basic Web Content" with German content:
  title: "Hallo &amp; Welt"
  content: 
  ```
  <h4 style="margin-left: 40px;">Vergünstigungen in der Mensa</h4>
  <p style="margin-left: 40px;">In allen <strong>gastronomischen Einrichtungen</strong> des Studierendenwerks XYZ können Sie sich ganz einfach mit XXXXXX-M in der YYY-App ausweisen, um die vergünstigten Tarife für Mitarbeitende zu erhalten.</p>
  <h4 style="margin-left: 40px;">Bibliothek</h4>
  <p style="margin-left: 40px;">Sie können XXXXXX-M nutzen, um Medien in der Bibliothek auszuleihen.</p>
  <h4 style="margin-left: 40px;">XYZ-Bahn-Nutzung</h4>
  <p style="margin-left: 40px;">Zusammen mit einem amtlichen Lichtbildausweis kann XXXXXXId-M als Berechtigung zur Nutzung der XYZ-Bahn genutzt werden.</p>
   ```
  The content should be entered when editor is switch to "Source" view, the quote characters should not be entered, HTML editor needs to be switch to preview mode before "publish", else the content is lost
- Choose "Übersetzen" from the Contextmenu of webcontent and request translation to en-US

In a screenshot this might be better visible:

Bildschirmfoto vom 2023-07-18 20-05-40

After the PR:

Bildschirmfoto vom 2023-07-18 20-07-43

**Comment by matthiasblaesing** [comment]
This was created without an issue ID as I can't create issues, so I hope that discussion can happen here and is looked at regardless of that fact. Thank you.

**Comment by austinchiang** [comment]
Thanks for your contribution @matthiasblaesing!  I opened a ticket for the issue [here](https://liferay.atlassian.net/browse/LPS-190935) and resubmitted this PR in https://github.com/liferay-lima/liferay-portal/pull/4501

**Pull request closed without merging**
