### PR TITLE
LPS-196217 Avoid creating unnecessary companies for tests

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Speed up tests

Proposed solution
----
Create companies only when it is necessary:

* Use default company if it is possible.
* If we need to create a new company, create it only in the test that we need it.

You can find average of tests executions right here https://test-1-0.liferay.com/userContent/reports/master/test-duration-report/index.html

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
Manual forward since failures are unrelated: https://github.com/brianchandotcom/liferay-portal/pull/140826

**Pull request closed without merging**
