### PR TITLE
[TS] LPS-184468 If the file cannot be found then update the file entry (bring back the behavior of LPS-53033)

### PR DESCRIPTION
**Pull request by jonathanmccann**
This is how the portal behaved as a result of https://issues.liferay.com/browse/LPS-53033 but was broken by the changes made in https://issues.liferay.com/browse/LPS-110426. This is bringing back the functionality that was lost.

If there are any questions or concerns please let me know.

This has already been reviewed by the Staging team - https://github.com/liferay-staging/liferay-portal/pull/306

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failure is not related to this PR

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
