### PR TITLE
LPS-147320 delete blog entries from antisamy whitelist but add permision to show iframes a data- structures

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
On one hand, we need to delete the blog entries from the whitelist for the antiSamy because it's letting execute scripts from the 
For example to adding this to the code of the blog, when viewing it on the widget
`<p></p>`
execute the alert.

On the other hand we have to allow to show `iframes` or `<div data-...>` structures to show videos for example whose code is like

`<div class="embed-responsive embed-responsive-16by9" data-embed-id="https://www.youtube.com/embed/dQw4w9WgXcQ?rel=0" data-styles="{&quot;width&quot;:&quot;77%&quot;}" style="width:77%"><iframe allow="autoplay; encrypted-media" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ?rel=0" width="560"></iframe></div>
`

So we must add a proper configuration for the blogs for the antisamy configurator

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
This is the behavior after the patch
https://user-images.githubusercontent.com/47524751/154050829-259bbd50-afaa-4ae4-b662-c1b17bb96763.mp4

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
This is the behavior after the patch



https://user-images.githubusercontent.com/47524751/154054373-e15f427b-7da5-45ab-8cb5-7aff8f243cd1.mp4

I do not know @boton if there is another cases that can apply.

**Review by boton — APPROVED** [review]
LGTM, but I don't know anything about `AntiSamy` and maybe have some side effects in blog content.
Can we run all blog tests? And maybe test the PR with care in master before backporting it.

**Comment by boton** [comment]
ci:test:blogs

**Comment by boton** [comment]
> I do not know @boton if there is another cases that can apply.

I don't know either. I'm going to launch blogs tests trying to catch side effects 🙏

**Comment by AliciaGarciaGarcia** [comment]
https://user-images.githubusercontent.com/47524751/154071465-cef49adc-df0d-4f03-880d-b6621a073e6c.mp4

**Comment by liuxingye** [comment]
I'm automating [LPS-147379](https://issues.liferay.com/browse/LPS-147379) using <p></p> based on this PR. For now, the alert is not pop up when viewing the biogs detail. But it still pops up when publishing the entry and it only occurs when first time to add the entry via the blogs widget on page. Could you take a took when you have time? @AliciaGarciaGarcia @boton Thanks.

**Comment by AliciaGarciaGarcia** [comment]
thanks @liuxingye 

I added some info on the slack channel

**Comment by samuelkong** [comment]
Hi guys. If you need to allow for iframes and videos, I want to suggest that you implement LPS-137198. It's more work but it's probably the right direction in terms of giving users the flexibility to do what they want and still maintain security.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:blogs

**Pull request closed without merging**
