### PR TITLE
[TS] LPS-159600

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a proposal for [LPS-159600](https://issues.liferay.com/browse/LPS-159600) based on the conclusion obtained in [PTR-3223](https://issues.liferay.com/browse/PTR-3223)

This solution adds a new parameter that is added for pages' URLs in the page administration and read by FriendlyURLServlet and a new JSPDynamicInclude in order to know if an info message with a link to the skipped redirect has to be displayed.

Only users with update permissions can skip the redirect with the new parameter informed.

Additionally, the redirections are skipped for the exclusive and pop-up window states.

Please, feel free to let me know if any clarifications are needed or if any suggestion or any different approach could be taken for this fix.

Thanks in advance!

\cc @robertoDiaz

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:129null_4002

**Review by AliciaGarciaGarcia — APPROVED** [review]
My only doubt is if `skippedRedirect` should be named (and the `String redirect`renamed) but LGTM

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by ambrinchaudhary — CHANGES_REQUESTED** [review]
Hey @dacousalr, thank you for sending us this fix. 

In frontend side we are trying to not use that "old pattern" with `script` tags in JSP. Considering we just want to show and alert and this is done by js side, we may get rid of the jsp and directly have this code in a .js file. I've seen examples for this for example in `TabsBottomDynamicInclude.java`, `ClayTooltipBottomDynamicInclude.java`, `WalkthroughBottomJSPDynamicInclude.java`... 
```
		ScriptData scriptData = new ScriptData();

		String initModuleName = _npmResolver.resolveModuleName(
			"frontend-js-tooltip-support-web/index");

		scriptData.append(
			null, "TooltipSupport.default()",
			initModuleName + " as TooltipSupport", ScriptData.ModulesType.ES6);

		scriptData.writeTo(httpServletResponse.getWriter());
```

Do you think we can do something similar? Would you need help from us? 
@boton what do you think? do you think is better the way @dacousalr implemented? 

Also... could `'com.liferay.friendly.url.web_ignoreRedirectOptions'` be a constant?

**Comment by ricardocousolr** [comment]
Thanks for your comments, @ambrinchaudhary!

@dacousalr is on PTO until the 22nd so I'll be taking care of his pr until then.

About
> Do you think we can do something similar? Would you need help from us?
> @boton what do you think? do you think is better the way @dacousalr implemented?
I'll wait on @boton for his feedback. If I need guidance I'll ask.

About
> Also... could 'com.liferay.friendly.url.web_ignoreRedirectOptions' be a constant?
Sure thing!

**Review by boton — COMMENTED** [review]
I'm with @ambrinchaudhary [here](https://github.com/liferay-lima/liferay-portal/pull/3340#pullrequestreview-1069320446) it's better to load only the js and avoid scripts tags.

**Comment by ricardocousolr** [comment]
Thanks @boton!

I'll implement those changes and send them.

**Comment by ricardocousolr** [comment]
Hi @ambrinchaudhary,

Please close this pr in favor of https://github.com/liferay/liferay-portal/pull/4933 (I couldn't add more commits to this one, unfortunately).

**Comment by ambrinchaudhary** [comment]
Hey @ricardocousolr , please send it to liferay-lima user, you did it to liferay.

**Comment by ricardocousolr** [comment]
Thanks for telling me, @ambrinchaudhary!

This is the correct one: https://github.com/liferay/liferay-portal/pull/4934

**Comment by ricardocousolr** [comment]
Thanks for telling me @ambrinchaudhary!

This is the correct one: https://github.com/liferay-lima/liferay-portal/pull/3389

**Pull request closed without merging**
