### PR TITLE
LPS-183137 Fix DeepL Translator authentication

### PR DESCRIPTION
**Pull request by matthiasblaesing**
According to the documentation the authentication key for DeepL has to transfered in the header:

> The authentication key is provided by setting the Authorization HTTP
> header to DeepL-Auth-Key [yourAuthKey].

https://www.deepl.com/de/docs-api/api-access/authentication/

Experimentally it was found, that both the languages and translate endpoints need to be authenticated.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by matthiasblaesing** [comment]
@adolfopa thank you for review. I have to ask your help again though. The CI/CD system seems to be unable to do the forwarding and I can't access the console output.

**Comment by adolfopa** [comment]
ci:forward

**Comment by matthiasblaesing** [comment]
@adolfopa thank you.

**Pull request closed without merging**
