### PR TITLE
[TS] LPS-127143

### PR DESCRIPTION
**Pull request by ChrisKian**
[LPS-127143](https://issues.liferay.com/browse/LPS-127143)

From @jesseyeh-liferay:

> After being redirected to a custom 404 .jsp page, a `NoSuchLayoutException`/`NoSuchGroupException` session error is added. As a result, when navigating back to a previous page, a corresponding error is shown.
> 
> Instead of removing the session error after the 404 resolves (see [LPS-123054](https://github.com/liferay-lima/liferay-portal/pull/1133/commits/ab5aa5a4a7757d0909bd7e406d762ed30df612f7)), this solution avoids adding the session error to begin with in the event of a redirect to a custom 404 page.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
hi @ChrisKian,

Thank you very much for this fix. At some point we thought about doing it this way unfortunately we could not. 

The problem is that when you set a non existing 404 page like:

```
layout.friendly.url.page.not.found=/html/portal/somefilethatdoesnotexist.jsp
```
and you request a missing page it will take you to the home with no errors instead of the default not found page (status.jsp). This is because the session message is no longer present and [this code](https://github.com/liferay/liferay-portal/blob/f6ebfc85ee8349fd6bb0246a54dc853d50ae13de/portal-web/docroot/html/portal/layout.jsp#L20-L24) does not run.

We have been investigating how to fix both things with no luck. We will look into it again tomorrow. Could you please have a look too to see if you can come up with a fix?

Thanks!

**Comment by 4lejandrito** [comment]
Let's move to this new proposal which signals the error in the scope of the request instead of the session: https://github.com/liferay-lima/liferay-portal/pull/1471. We will develop it further on Monday.

**Pull request closed without merging**
