### PR TITLE
LPS-194502 show tooltip with the scheduled date/time

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-194502

How to test it:

FF: LPS-188060

since you can not select the display date on the edition of the KB Article, the only way to test this now is or modifying the UpdateKBArticleMVCActionCommand.java or changing the date on the database

Result: 
image

- LPS-194502 add the tooltip if the article is scheduled
- LPS-194502 expiring soon if the article is not scheduled

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
Smoke log
```
org.elasticsearch.ElasticsearchStatusException: [liferay-20096-workflow-metrics-processes] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-20096-workflow-metrics-processes]]] java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: [liferay-20096-workflow-metrics-processes] ElasticsearchStatusException[Elasticsearch exception [type=index_not_found_exception, reason=no such index [liferay-20096-workflow-metrics-processes]]]  at 
```
IMO is not related with this PR

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
