### PR TITLE
 LPS-197415 change message of mimetype limit

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
image

- LPS-197415 change message to match the design
- LPS-197415 buildLang

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
I will ask Maria about the names. Thanks!

**Comment by mariapmartins** [comment]
hey, let's keep "Mimetype Limit", and "Mimetype" to maintain consistency ;) Thanks for the heads up @marcogalluzzi

**Comment by AliciaGarciaGarcia** [comment]
image

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
checking the failures

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
