### PR TITLE
[TS] LPS-196542 Cannot import translations is SPA is disabled

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1407401_6168

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
