### PR TITLE
LPS-164483 KB preview article child items

### PR DESCRIPTION
**Pull request by Hanlf**
## Issue https://issues.liferay.com/browse/LPS-164483

Build on top of https://issues.liferay.com/browse/LPS-164481 #3541 we need to wait until #3562 is merged. Maybe I cause some poshi test failure because I update some markup.

### Before PR
image

### After PR
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
