### PR TITLE
LPS-194897 Add alert on preview

### PR DESCRIPTION
**Pull request by marcogalluzzi**
See: https://liferay.atlassian.net/browse/LPS-194897

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
Hi @marcogalluzzi There are some backend tests failed. It should be related to this pull request. Could you help to take a look? Thank.

- com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetGroupMaxNumberOfPagesCompanyLimited

- com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetGroupMaxNumberOfPagesWithInvalidGroupId

- com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetSystemMaxNumberOfPagesDefaultValue 

Console error:
```
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetGroupMaxNumberOfPagesCompanyLimited FAILED
     [exec]     java.lang.AssertionError: expected:<10> but was:<3>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest.lambda$null$4(PDFPreviewManagedServiceFactoryTest.java:160)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest._withGroupConfiguration(PDFPreviewManagedServiceFactoryTest.java:292)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest.lambda$testGetGroupMaxNumberOfPagesCompanyLimited$5(PDFPreviewManagedServiceFactoryTest.java:156)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest._withCompanyConfiguration(PDFPreviewManagedServiceFactoryTest.java:270)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest.testGetGroupMaxNumberOfPagesCompanyLimited(PDFPreviewManagedServiceFactoryTest.java:152)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] 
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetGroupMaxNumberOfPagesSystemLimited STARTED
     [exec] 
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetGroupMaxNumberOfPagesSystemLimited PASSED
     [exec] 
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetGroupMaxNumberOfPagesSystemValue STARTED
     [exec] 
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetGroupMaxNumberOfPagesSystemValue PASSED
     [exec] 
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetGroupMaxNumberOfPagesWithInvalidGroupId STARTED
     [exec] 
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetGroupMaxNumberOfPagesWithInvalidGroupId FAILED
     [exec]     java.lang.AssertionError: expected:<0> but was:<3>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest.testGetGroupMaxNumberOfPagesWithInvalidGroupId(PDFPreviewManagedServiceFactoryTest.java:211)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] 
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetSystemMaxNumberOfPages STARTED
     [exec] 
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetSystemMaxNumberOfPages PASSED
     [exec] 
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetSystemMaxNumberOfPagesDefaultValue STARTED
     [exec] 
     [exec] com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest > testGetSystemMaxNumberOfPagesDefaultValue FAILED
     [exec]     java.lang.AssertionError: expected:<0> but was:<3>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.document.library.preview.pdf.internal.configuration.admin.service.test.PDFPreviewManagedServiceFactoryTest.testGetSystemMaxNumberOfPagesDefaultValue(PDFPreviewManagedServiceFactoryTest.java:238)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
     [exec]     	at java.lang.Thread.run(Thread.java:745)

```

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
