### PR TITLE
LPS-132088 Migrate selection modals in depot-web

### PR DESCRIPTION
**Pull request by markocikos**
Hey @liferay-lima ,

This is a part of [an ongoing epic](https://issues.liferay.com/browse/LPS-129246) to replace legacy AUI-based modals with Clay/React-based `openSelectionModal`. In this PR, we are fixing previous migration of a modal in depot-web.

Notes:
- We migrated the select depot role modal to `openSelectionModal` [a while back](https://github.com/liferay/liferay-portal/commit/0cef31651c89f4f260dc34b8379c6dc2774a262f). What got my attention now is the usage of `Util.selectEntityHandler` in `select_depot_role.jsp `. That entire block can be safely deleted after that migration, and we are doing this in this PR.
- While testing to doublecheck modal is ok, I noticed buggy behavior (see the 'before' gif). As this was likely caused by the original migration, I set out to fix the behavior.
- The root cause of the bug is the fact that in `openSelectionModal` we are [checking `dataset.entityid`](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L434) to determine if an item should be disabled. In `depot-web` modal, different ids got mixed up. We are inconsistently dealing with `groupId`, `roleId`, `rowId` and `entityId`. In this PR, we are setting `entityId = groupId + '-' + roleId` and consistently use this everywhere.
- Since I was already making a lot of changes, I moved all JS to separate `liferay-frontend:component`, to use modern syntax, imports, etc.
- I needed to tweak URL getter a bit, as `liferay-frontend:component` does not auto-convert to string 
- We are adding support for toggling instead of just setting disabled. Currently, if you delete an item, you cannot re-select it, button stays disabled.
- A second of delay before disable toggle cannot be fixed in modal utility, as this is delay between server-side rendering and hydration. To improve this behavior, we may do something like modify url that opens modal, add selected items as param. This is beyond the scope of this task.

/cc @kresimir-coko @jonmak08

Test plan:
1. Users and Organizations > Open a user > Asset Library Roles > Select

Before:
before

After:
after

### CODE REVIEW

**Comment by carloslancha** [comment]
Hey @markocikos thx for the PR!

Just FYI we're implementing a new [PR Etiquette](https://liferay.atlassian.net/wiki/spaces/ENGLIMA/pages/1477903027/Pull+Request+Etiquette) you'll probably find pretty familiar, with some additions like:
- Add `frontend` or `backend` labels
- Run `ci` sf and relevant tests.

Please, take a look for further prs, it will be very helpfull! 😄

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
hey @markocikos 
> A second of delay before disable toggle cannot be fixed in modal utility, as this is delay between server-side rendering and hydration. To improve this behavior, we may do something like modify url that opens modal, add selected items as param. This is beyond the scope of this task.

Is there any ticket about this we can track?

**Comment by markocikos** [comment]
> Is there any ticket about this we can track?

@carloslancha I don't think so. This is not a bug, or an improvement we can make in a utility. It falls in the domain of the product team, you can decide if and when you want to restructure solution to improve it.

**Comment by carloslancha** [comment]
> I don't think so. This is not a bug, or an improvement we can make in a utility. It falls in the domain of the product team, you can decide if and when you want to restructure solution to improve it.

Oh, sorry, I understood that it was something related with te ssr/hydration of the modal.

**Comment by markocikos** [comment]
@carloslancha I have an idea how we might do this in the modal utility. I'll explore it in https://issues.liferay.com/browse/LPS-132187

This is not a blocker for this PR.

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
