### PR TITLE
LPD-2816 Do not allow upload blog attachments if workflow is active for blog entries.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]
LGTM!

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Comment by robertoDiaz** [comment]
Failures seem related.

Checking that

**Comment by robertoDiaz** [comment]
ci:forward:force

**Pull request closed without merging**
