### PR TITLE
LPS-185764 Add success message after publishing a blog entry that was previously drafted

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-185764

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-185764.

### CODE REVIEW

**Review by jaimelr10 — APPROVED** [review]
This looks good to me! :smile:

**Comment by jaimelr10** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
