### PR TITLE
LPS-138898 Blogs related assets items have strange margins between subtitles

### PR DESCRIPTION
**Pull request by boton**
https://issues.liferay.com/browse/LPS-138898

**Before this PR**

image

**After this PR**

image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
@adolfopa I added you as a reviewer because it's very old code and maybe we're missing something. 
I double-check with Emiliano and affect in other blogs editor places but in all places looks better with these styles.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
