### PR TITLE
LPS-148107 translations import multiple files

### PR DESCRIPTION
**Pull request by boton**
- [x] Add input file support for multiple files
- [x] Review the literal for multiple files / final design
- [x] Review the buttons text update based on state and the interactions
- [x] Add initial markup in JSP (SSR)
- [x] Add backend multiple file support

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by boton — COMMENTED** [review]
LTGM ✅ 

image

**Comment by boton** [comment]
I split this story into 2 subtasks [LPS-148107](https://issues.liferay.com/browse/LPS-148107) **this one** and [LPS-148109](https://issues.liferay.com/browse/LPS-148109) to avoid waiting for the new design implementation to be merged [LPS-146890](https://issues.liferay.com/browse/LPS-146890).

**Comment by boton** [comment]
I tested and accepts and processed weel, we will apply the new design [LPS-148109](https://issues.liferay.com/browse/LPS-148109) as soon as we can.

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
