### PR TITLE
LPS-190862 | Add displayDate to KnowledgeBaseArticle schema

### PR DESCRIPTION
**Pull request by jaimelr10**
**Resend from**:  https://github.com/brianchandotcom/liferay-portal/pull/141622

**Description**: Add property displayDate to KnowledgeBaseArticle schema as well as its DTO converter

**Jira ticket**: https://liferay.atlassian.net/browse/LPS-190862

### CODE REVIEW

**Comment by jaimelr10** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1397401_7696

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by jaimelr10** [comment]
ci:forward:force

**Pull request closed without merging**
