### PR TITLE
LPS-113857 Fix NullPointerException

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Pending: fix frontend errors

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
I will take a look today, code a solution and confirm tomorrow with @ambrinchaudhary and @4lejandrito  😄

**Comment by boton** [comment]
See #70

**Pull request closed without merging**
