### PR TITLE
LPS-190942 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-190942

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:depot

**Comment by austinchiang** [comment]
@Jeremy-Ch in this test instead of checking if the contents were added, reindexing search might be the solution. The flaky issue is still happening after your fix, and checking the logs it looks like the assets were all added correctly so I don't think that's the issue

**Comment by Jeremy-Ch** [comment]
> @Jeremy-Ch in this test instead of checking if the contents were added, reindexing search might be the solution. The flaky issue is still happening after your fix, and checking the logs it looks like the assets were all added correctly so I don't think that's the issue

Hi @austinchiang You are right, I added those steps just for debug.

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
