### PR TITLE
LRQA-64791 | Master only

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LRQA-64791

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Hanlf** [comment]
[AppBuilder#DeployAppChoosingBetweenDifferentTableViews](https://testray.liferay.com/zh/home/-/testray/cases/1310785127) is fluke, will rerun it

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
[AppBuilderWorkflow#AssignEntryThroughTableView](https://testray.liferay.com/zh/home/-/testray/cases/1310779498) fluke, try again.

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
