### PR TITLE
LPS-203900 set the group on the search context the proper group/repository on the case is connected or is ancestor

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-203900

**Steps to Reproduce**

1. Create AL: MyAL
2. Connect site: Liferay DXP
3. Go to MyAL > Documents and Media
4. Create a folder MyFolder and upload a document MyDoc to that folder.
5. Apply a tag to MyDoc: al-tag
6. Go to Liferay DXP > Home page and add a D&M widget
7. In the widget Configuration > Root Folder, select the Asset Library > MyFolder
8. Use Filter and Order > Tags

**Expected**
al-tag is shown. If you select that tag, MyDoc is found

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
