### PR TITLE
LPS-136179 obtain the video when uuid is not present

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-136179

The uuid on the import/export is eliminated so we must look for the video without the uuid (result of https://issues.liferay.com/browse/LPS-135706) 

This behavior is the same than in the images (that are obtained without the uuid)

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @4lejandrito I want to talk about WHy on the original method only you let obtain the video with 5 params.

Ping me if you have time :)

**Comment by 4lejandrito** [comment]
> Hi @4lejandrito I want to talk about WHy on the original method only you let obtain the video with 5 params.
> 
> Ping me if you have time :)

The fix seems to be OK. Export/Import removes the uuid also for images so it is expected behaviour that we should consider in the video logic.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:reevaluate:1287401_201

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1287401_201

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1287401_201

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
