### PR TITLE
LPS-194379 Move property to settings

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-194379

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
Should the property be removed also from file "portal.properties" ?

And question: why do we save removed properties in classes called Legacy*PropsKeys ?

**Review by marcogalluzzi — APPROVED** [review]
Very good!

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:reevaluate:1387401_8855

**Comment by Jeremy-Ch** [comment]
Hi @adolfopa Please help to solve the conflicts, Thanks.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Hi @adolfopa , there are some conflicts in this PR. Could you please fix them and resend? Thanks

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
