### PR TITLE
LPS-138272 Workflow should not apply to reviewer comments

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

I figured that the only information the request includes whether the comment was sent in the context of a Workflow review is the namespace, which contains the ID of the portlet.
This can be either `com_liferay_portal_workflow_task_web_portlet_MyWorkflowTaskPortlet` (`edit_workflow_task.jsp`) or `com_liferay_portal_workflow_web_internal_portlet_UserWorkflowPortlet` (`edit_workflow_instance.jsp`).

Please let me know if you're fine with this approach.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
@IstvanD See https://github.com/liferay-lima/liferay-portal/pull/2284 for some small SF changes. Thanks!

**Comment by IstvanD** [comment]
Hi @adolfopa 

The changes look fine to me. 
I opened a new pull request including them: https://github.com/liferay-lima/liferay-portal/pull/2285

**Pull request closed without merging**
