### PR TITLE
LPS-145475 First part of the change of signature of the DLFileEntryLocalService adding the urlTitle on the creation/update of the file

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa Im not sure if we want to send this right now or with the other signatures changes.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:documents

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Some of these errors look legit. Can you take a look at them?

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/2755

**Pull request closed without merging**
