### PR TITLE
LPS-189853 Refactor view_item_selector_view_descriptor

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-189853)

Ey, @Liferay-lima !! 😄 

I’ve been working on some issues and i saw this view_item_selector_view_descriptor.jsp  that could be refactored. I made it and I would like to know your opinion. 

## Proposed solution

Extract code to JS and simplify it. Also use TypeScript.

## Test Scenario 1

1. Create a Display Page Template
2. Create a new Web Content
3. Try to change the Display Page Template for this Web Content
4. Also try to add some Related Assets (this one it’s for the multiple selector)

image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@BarbaraCabrera This looks good to me, but I'm not a frontend guy. As @ambrinchaudhary in on PTO, could you ask someone on your team to take a look to help us move forward? Thanks!

**Comment by BarbaraCabrera** [comment]
Hi, @adolfopa ! Yes, this pr has been reviewed by my team (@p2kmgcl) before sending it to you 😄

**Comment by adolfopa** [comment]
@BarbaraCabrera Thanks! I'll forward it then.

**Comment by adolfopa** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
