### PR TITLE
LPS-124202 Try to keep aspect ratio

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@4lejandrito Can you check if this behaves as you expect? Note that when failing to scale by crazy amounts (the _RATIO_THRESHOLD part), the video may be a bit too large/wide to fit in the container (scrolling bars may appear); this is a compromise I'm willing to accept (I favor correct aspect ratio vs fitting 100% of the container).

**Comment by 4lejandrito** [comment]
@adolfopa it works like a charm! Don't worry about the aspect ratio because that is handled by the video tag and it will be fine:

Screenshot 2020-12-02 at 14 55 30

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
