### PR TITLE
LPS-119291 Remove unused code

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
This pull request has an issue:


Uploading Screen Recording 2021-03-10 at 15.26.11.mov…

**Comment by boton** [comment]
@4lejandrito updated and working

**Comment by 4lejandrito** [comment]
@adolfopa can you review https://github.com/liferay-lima/liferay-portal/pull/1606/commits/0efbe085932e1f86722c55089bfba66c4fce25d7? @boton found that we were still editing in the live page instead of the control panel when clicking on ... + Edit on a Blog entry. 

I remember you worked on this in the past and that every edit operation should be redirecting to the control panel.

Thanks!

**Comment by boton** [comment]
@carloslancha can you check this cad6ee2 please? @4lejandrito and I think that the new clay:dropdown-actions better render nothing if items don't exist like the old version.

Thanks!!

**Comment by adolfopa** [comment]
Good catch, @boton ! Looks good.

**Review by adolfopa — APPROVED** [review]

**Comment by boton** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:bundle

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
@boton this must be send to frontend infra team for them to analyze and approve (or not 😅)

**Comment by boton** [comment]
> @boton this must be send to frontend infra team for them to analyze and approve (or not 😅)

Yep sure that is the way this is only a precheck with you, Does it make sense to you?
If you have nothing against it, I send it to FI

**Comment by carloslancha** [comment]
I'm not sure if this is the behavior we want to have but yep, better send it so they can give us their opinion ;)

**Comment by boton** [comment]
See  liferay-frontend#898

**Pull request closed without merging**
