### PR TITLE
LPS-165773 Search results are returned in the wrong order when searching for entry content

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Steps for testing are in https://liferay.atlassian.net/browse/LPS-165773

Changes done are:

1.  Fixed the sort direction when searching: it was incorrectly set to be the opposite
2. When searching, the sort direction cannot be changed if sorting by relevance, it is always Descending
3. Relevance sorting is not saved in Portal Preferences, otherwise it used in non-search view where the "relevance" sort option doesn't apply

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR, BlogsNotifications#CanViewEmailNotificationForFlaggedEntry failed at https://liferay.atlassian.net/browse/LPS-189281

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
