### PR TITLE
LPS-166785 Remove PWC versions as soon as possible

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

Up until now, PWC data in the store wasn't deleted immediatelly. This may eat a lot of unnecessary storage space; this is a big problem for customers that pay for storage (e.g. LXC).

This PR will try to delete the data as soon as possible, freeing up space after documents are checked in.

# How to test this?

This PR includes integration tests that verify the correct behavior.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
It looks good to me

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1267401_5699

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1257401_5203

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
