### PR TITLE
LPS-120609 Remove POSHI test

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@austinchiang I've removed the Asset Library configuration and a related POSHI test. Can you review this and forward if you're ok with it?

Thanks!

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
Test failures are legit. I'll resend with further changes.

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/768

**Pull request closed without merging**
