### PR TITLE
[TS] LPS-151748

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
@crodriguezy and @liferay-lima 

See the LPS comments

**Comment by robertoDiaz** [comment]
We've been reviewing it and it seems that we've found an alternative.

@crodriguezy is testing it

**Comment by crodriguezy** [comment]
The alternative analyzed is not working. 

FYI, this is also happening with Blogs, so it seems a general item-selector issue.

**Comment by robertoDiaz** [comment]
I'm working on this.

**Comment by robertoDiaz** [comment]
@crodriguezy will send a new PR with a different solution

**Comment by crodriguezy** [comment]
Please see https://github.com/liferay-lima/liferay-portal/pull/2951

**Pull request closed without merging**
