### PR TITLE
[TS] LPS-170287 Documents and Media - Wrong name is set when creating a folder with a lowercase

### PR DESCRIPTION
**Pull request by thienquach87**
Hi Team,

Here is the PR for fixing https://issues.liferay.com/browse/LPS-170287.
Please help to review and leave your comments.
This issue is because [LanguageUtil.get](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/HorizontalCardTag.java#L83-L84) function.
In some cases, the title of HorizontalCardTag is one of keys in the resources of portal-language-lang, so the return value gotten from portal-language-lang is not right.
Solution: Add condition to avoid using LanguageUtil.get() function in needed.

Thank you!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1307401_5797

**Comment by austinchiang** [comment]
Hey @thienquach87 , there are semver issues with this pull. See https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315452/testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_frontend_taglib_frontend_taglib_clay_/

**Comment by thienquach87** [comment]
ci:test:relevant

**Comment by thienquach87** [comment]
> Hey @thienquach87 , there are semver issues with this pull. See https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/315452/testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_frontend_taglib_frontend_taglib_clay_/

I updated source to solve the issue. Thank you!

**Comment by adolfopa** [comment]
@thienquach87 Can you send this pr to @liferay-frontend? This is a general change, not specific to DM, so it should be reviewed by them.

**Comment by thienquach87** [comment]
> @thienquach87 Can you send this pr to @liferay-frontend? This is a general change, not specific to DM, so it should be reviewed by them.

I forwarded https://github.com/liferay-frontend/liferay-portal/pull/2917. Thank you

**Pull request closed without merging**
