### PR TITLE
LPS-145475 Add url title to add and update methods from the DLApp services // LPS-149177 Remove Deprecated Methods

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
On this PR we are updating the calls from the DLAppService and DLAppLocalService adding the parameter urlTitle to the 'add' and 'update' methods as we made previously to the DLFileService and Repository methods below them.

We are also deleting almost all the deprecated methods and updating the calls to the new ones.
Note that we're keeping some of the deprecated methods around. 
The reason is: https://issues.liferay.com/browse/LPS-149177

There are some Poshi tests that depend on the deprecated method and if deleted there are more that 100 Poshi test failures.
We have to make a research and change those references soon, but we need this changes to be merged first.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa this PR is the same as the https://github.com/liferay-lima/liferay-portal/pull/2837 with the removal of the deprecated methods that are not needed for the Poshi test as @Hanlf research concluded

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Looks like there are conflicts on the branch now @AliciaGarciaGarcia 😵‍💫

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
SF errors not related to this PR.

**Comment by Hanlf** [comment]
Hi @AliciaGarciaGarcia and @adolfopa 
It seems that the addFileEntry method without expirationDate and reviewDate parameters is removed under https://github.com/liferay-lima/liferay-portal/pull/2833/commits/986f8145bbceb008912e4cd097bda4a55aa540f5, so 100+ Poshi tests failed again, could you take a look?
Just to clarify the method we still need in case of any misunderstanding:
```
addFileEntry(
			long userId, long repositoryId, long folderId,
			String sourceFileName, String mimeType, String title,
			String description, String changeLog, File file,
			ServiceContext serviceContext)
```

**Comment by AliciaGarciaGarcia** [comment]
@Hanlf there was an misunderstanding on one of the rebases because the files were modified by another user (she was cleaning deprecated methods) and some commits were lost.

I will send the rebased one with the lost in the translation commits.

Thanks for pointing at it!!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa I changed a little the story of commits, splitting the two main tickets.

Do you think this way we explain better why we do it on the way we are doing it?

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
the SF failure was not related on this PR but I sent a auto - sf to fix it because it annoys me :D

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia We need to add some information to the PR description to make sure we avoid misunderstandings.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @AliciaGarciaGarcia ,
Sorry, I realized we still need another method, jsonws still doesn't work with the one method I asked for before.
```
addFileEntry(
			long repositoryId, long folderId, String sourceFileName,
			String mimeType, String title, String description, String changeLog,
			File file, ServiceContext serviceContext)
```
And if the above method addFileEntry needs to add the "urlTitle" parameter, you also need to fetch [this commit](https://github.com/Hanlf/liferay-portal/pull/338/commits/8dd7fb2daa4818a2e13b38a091e3faa7abd170be) to make sure Poshi tests work.
Sorry again for the extra work I caused.

**Comment by Hanlf** [comment]
The ci job is running more than 10 hours, should be some ci issue, stop it.

**Comment by Hanlf** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @Hanlf 

I just sent the PR rebased.
I think that I do let the method(s) that Poshi needs.
If there are another, please reach me.

I added the https://github.com/Hanlf/liferay-portal/pull/338 too on the PR.

thanks for the review!

**Comment by Hanlf** [comment]
Ran one Poshi test: DMFileEntry#CanMoveDocumentToRecycleBin based on the latest commits, it passed!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
These Poshi failures are not related to this PR, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @AliciaGarciaGarcia 

All failures should not be related to this PR. I think it is ready to go! let me know if you need me to send it to BChan directly.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
@Hanlf if the forward do not work and the errors are not related to the PR, please send directly with your superpowers!

thanks!!

**Pull request closed without merging**
