### PR TITLE
LPS-170626 Remove menu-item usages in wiki

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-170626

Remove all usages of the `menu-item` taglib in wiki, replacing it with `dropdown-actions`.

# Do I need to do something with this?

@ambrinchaudhary I need help with the Js logic. I've created the props transformer, but it is not being invoked.  I'm sure I'm missing some important step, but I have no idea which one.

# How do I test it?

These are internal changes; the app should behave the same way as before.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1257401_5693

**Comment by ambrinchaudhary** [comment]
I guess there are poshi tests that needs to be updated. Could we add the qa review label @adolfopa, or there is still some work pending here?

**Comment by adolfopa** [comment]
@ambrinchaudhary I'll take a look at the failures first. Thanks!

**Comment by adolfopa** [comment]
@austinchiang For what I've seen, all error are caused by markup changes (the `dropdown-toggle` class is looked for, but it is no longer there). Did some manual tests and all operations seem to be working fine. Can you guys take a look at the tests? Thanks!

**Review by marcogalluzzi — APPROVED** [review]
Everything looks fine!

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Hi @adolfopa, all failure tests have been fixed and all CI checks have passed.

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
