### PR TITLE
LPS-175130 Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-175130 use service instead util
- LPS-175130 add test to check that the generated pdf has the correct number of pages
- LPS-175130 on case of invalid group return system settings
- LPS-175130 test PDF preview managed service

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
rebase and fix

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1347401_3611

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
