### PR TITLE
LPS-125917 + LPS-124911 - Alloy/ck editor bugs

### PR DESCRIPTION
**Pull request by boton**
Hello guys,

I think that the bug is fixed, @ambrinchaudhary @4lejandrito  please if you can check it in case I forget some case. 

I have some questions.

**Do you think it is better to use `%` or `px`?**

Because I was missing logic and it is because it was deleted on purpose https://github.com/brianchandotcom/liferay-portal/pull/89635/commits/3259a99805fd2173828ee8fc63f0d6c157d9cf5e but this part is related to this [LPS-114255](https://issues.liferay.com/browse/LPS-114255) and it doesn't seem to fix it. :(

We have left some of the logic that calculates the `%` https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/videoembed/plugin.js#L503-L517

@julien do you think it is better to rescue the `%` calculation or eliminate it?

~~On the other hand, the use of providers before we pass directly to their template the ID that was then used to fill in a part of the URL. Deleted here https://github.com/liferay/liferay-portal/commit/68f167a826ddc5a758d6d2a63578dcd788477226.~~

~~For example, if someone is using an implementation like the one that existed from youtube https://github.com/liferay/liferay-portal/commit/68f167a826ddc5a758d6d2a63578dcd788477226#diff-8a7f3b2fbfc7b4852c5fb8d5ee634d216a8417bdL.~~

~~Executing it now will return the iframe with an incorrect URL, as far as I understand.~~

~~**Returned:**~~
```
src="https://www.youtube.com/embed/https://www.youtube.com/embed/Mu0LcyOPadQ?rel=0"
```

~~**Expected:**~~
```
src="https://www.youtube.com/embed/Mu0LcyOPadQ?rel=0"
```

~~**Do you think is better to remove providers completely or fix them?**~~

Chat with @ambrinchaudhary @4lejandrito about providers. 
We think that providers should work with these changes in the old way.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
Doesn't work in CKEditor but works in Alloy :_

**Comment by boton** [comment]
In the last commit https://github.com/liferay-lima/liferay-portal/pull/1386/commits/05f910da53cb3df05f45c976de7217d5ae9aff71 I move the plugin CSS outside of Alloy scope but inside _editor_alloy.scss maybe is better to make a separate SCSS file for the plugin.

The resize in the CKEditor isn't working well either in this PR and master. 

This fixes problem of the infinite wrapping and unstyled message in the video preview.

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1397

**Pull request closed without merging**
