### PR TITLE
LPS-131646 Hide Autotranslate button when no valid configuration is present

### PR DESCRIPTION
**Pull request by adolfopa**
Enable the Auto-translate button only when the configuration is valid (and the feature flag is enabled).

To test this, simply try to enable/disable the Google Cloud configuration is System Settings, and observe that the button in the side by side goes away/shows up as appropriate.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@austinchiang I've changed the names used in the UI/classes as we talked about. Let me know if we need to do more changes.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa 

The button is hidden but on the ticket says:

> Steps to reproduce:
>     Enable Google Auto Translations in Portal
>     Navigate to System Settings > Google Cloud Translator
>     Check the box to enable the feature but don't type anything into the account key field
>     Save the configuration
> Expected result:
> An error message appears saying a key is required.

I do not know if this part is omitted:


https://user-images.githubusercontent.com/47524751/117803104-88fac700-b256-11eb-8dcf-f7e831adac93.mp4

Except this question, this looks ok for me.

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1117401_8875

**Comment by adolfopa** [comment]
Ohh, I see. You're right. I'll work on that in a different ticket so that this can be merged. /cc @austinchiang

**Comment by boton** [comment]
The button part works fine but like @AliciaGarciaGarcia says the user does not have any errors if the key is invalid.

Some errors are logged in Catalina when the key is invalid, I don't know if this is expected.

```
2021-05-11 14:05:41.762 WARN  [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.translation.google.cloud.translation.translator.internal.configuration.GoogleCloudTranslationTranslatorConfiguration)][AutoTranslateServlet:99] bundle com.liferay.translation.web:2.0.3 (675)[com.liferay.translation.web.internal.servlet.AutoTranslateServlet(6437)] : Could not get service from ref {com.liferay.translation.translator.Translator}={enabled=true, serviceAccountPrivateKey=--{_"type": "s....service.id=18779, service.bundleid=592, service.scope=bundle, service.pid=com.liferay.translation.google.cloud.translation.translator.internal.configuration.GoogleCloudTranslationTranslatorConfiguration, component.name=com.liferay.translation.google.cloud.translation.translator.internal.translator.GoogleCloudTranslationTranslator, component.id=2433}  [Sanitized]
11-May-2021 14:05:41.767 SEVERE [CM Event Dispatcher (Fire ConfigurationEvent: pid=com.liferay.translation.google.cloud.translation.translator.internal.configuration.GoogleCloudTranslationTranslatorConfiguration)] org.apache.catalina.core.ApplicationContext.log Servlet cannot be null
        java.lang.IllegalArgumentException: Servlet cannot be null
                at org.eclipse.equinox.http.servlet.internal.context.ContextController.addServletRegistration(ContextController.java:484)
                at org.eclipse.equinox.http.servlet.internal.customizer.ContextServletTrackerCustomizer.addingService(ContextServletTrackerCustomizer.java:63)
                at org.eclipse.equinox.http.servlet.internal.customizer.ContextServletTrackerCustomizer.addingService(ContextServletTrackerCustomizer.java:1)
                at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943)
                at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1)
                at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256)
                at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229)
                at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903)
```

```
2021-05-11 14:05:41.767 WARN  [Framework Event Dispatcher: Equinox Container: a30f29f6-1bba-4ea3-a62d-0c5590fec0a4][Framework:99] FrameworkEvent WARNING
org.osgi.framework.ServiceException: org.apache.felix.scr.impl.manager.SingleComponentManager.getService() returned a null service object
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:232) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceUse.newServiceObject(ServiceUse.java:96) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$1.getService(ServiceConsumer.java:30) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:524) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceObjectsImpl.getService(ServiceObjectsImpl.java:89) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.equinox.http.servlet.internal.context.ContextController$ServiceHolder.<init>(ContextController.java:52) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.context.ContextController.addServletRegistration(ContextController.java:478) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.customizer.ContextServletTrackerCustomizer.addingService(ContextServletTrackerCustomizer.java:63) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.customizer.ContextServletTrackerCustomizer.addingService(ContextServletTrackerCustomizer.java:1) ~[?:?]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) ~[org.eclipse.osgi.jar:?]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
        at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[org.eclipse.osgi.jar:?]
        at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) ~[org.eclipse.osgi.jar:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) ~[org.eclipse.osgi.jar:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:906) ~[?:?]
```

**Comment by austinchiang** [comment]
Hey @adolfopa I just heard back from legal and looks like we should go with `Translator for Google Cloud`

> I would go with the first option: "Translator for Google Cloud".
> The descriptive element "for" shows from a trademark perspective that we are providing the translator FOR the third party service. But we are NOT providing the third party service and we are NOT the trademark owner of the third party service (e.g. Google Cloud).
> We should be cautious not to confuse about the ownership in Google Cloud. Google Cloud is a Google brand and is owned by Google.
> And we should avoid displaying a third party-service in any manner that implies a relationship or affiliation with the third party-service (e.g. Google). So if we call it "Integration with Google Cloud Vision" this might sound as if we have a relationship or affiliation with Google.
> Fyi - we once had a discussion about our marketplace connectors for third party software and touched some trademark aspects and maybe this provides for some helpful insights, here: https://issues.liferay.com/browse/FOSS-18 and https://issues.liferay.com/browse/FOSS-19 .

Do you mind updating it? Thx in advance.

**Comment by adolfopa** [comment]
Hey guys,

As some questions have been raised about the naming, I'm going to resend these changes without updating the module/class/key names.

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1814

**Pull request closed without merging**
