### PR TITLE
LPS-138272 Workflow should not apply to reviewer comments

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

As the changes affect the **Workflow** component as well, a [pull request with the same content](https://github.com/liferay-workflow/liferay-portal/pull/510) has been sent to the @liferay-workflow team where they approved it and asked me to send it to you as well so you can review the changes in the DiscussionTag.

Currently, when an approval Workflow (eg. Single Approver) is set for Comments, even the Comments made on the Workflow Task are sent for review. The Comments made on that Workflow Task are in turn sent for review as well and so on.

The changes in the pull make the comments on the Workflow Task exempt from the workflow process.
Please let me know if this behavior should be rather made optional by turning it on/off with a configuration.

Thank you and best regards,
István

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
[WorkflowMetricsWorkloadByAssignee#WorkloadByAssigneeCardDisplaysUpTo10Users](https://testray.liferay.com/zh/home/-/testray/cases/1539867673): fluke. re-ran it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Semantic-versioning-jdk8/0 was filed here: [LPS-138527](https://issues.liferay.com/browse/LPS-138527)
Others should be Ci flaky.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:stop

**Comment by adolfopa** [comment]
@IstvanD and I agreed on an alternative solution. Istvan will send a followup PR.

**Pull request closed without merging**
