### PR TITLE
LPS-195902 When publishing from Staging to Live, the FriendlyUrlEntryLocalization information is not correctly updated

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://liferay.atlassian.net/browse/LPS-195902

When publishing from Staging to Live, the FriendlyUrlEntryLocalization information is not correctly updated, this is only reproduced in case you end having a FriendlyUrlEntryLocalization entry in Live with a different value than the Staging value and you try publishing the content to fix the mismatch information

One cause of the mismatch information between Staging and Live is the bug, as it can cause inconsistent data, but you can end having this wrong information following the steps explained in the ticket description.

I didn't escalated this ticket to the Lima IPT as in the beginning I thought it was Staging issue and when I realized it belonged to Lima, I had already implemented the fix. 

Let me know if you have any question.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
The failures are unrelated. Forward directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
