### PR TITLE
LPS-160824 DM folders - dropdown items

### PR DESCRIPTION
**Pull request by Jeremy-Ch**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
I'm going to check the issue with the delete confirm message and the permissions error. Will send a new pull. Thanks @Jeremy-Ch

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/3400

**Pull request closed without merging**
