### PR TITLE
LPS-182766 | Add feedback to the user when moving an element using Move Modal in Knoledge Base

### PR DESCRIPTION
**Pull request by jaimelr10**
**Resend from:** https://github.com/brianchandotcom/liferay-portal/pull/137642

**Description**: We need to provide the user a way to identify which and where is moving an element when using the new move modal for knowledge base.

**Jira Ticket**: https://issues.liferay.com/browse/LPS-182766

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:reevaluate:1397401_6064

**Review by adolfopa — APPROVED** [review]

**Comment by austinchiang** [comment]
Hey @jaimelr10 there was a semver issue in https://testray.liferay.com/home/-/testray/case_results/2384748551 which looks relevant
`[exec] > Task :apps:knowledge-base:knowledge-base-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec]   com.liferay.knowledge.base.constants               UNCHANGED  2.4.0      2.3.0      2.3.0      EXCESSIVE VERSION INCREASE
     [exec] 	-   version    2.3.0
     [exec] 	+   version    2.4.0`

Can you please check to see if you can reproduce it? (Normally I would just do it but my gradle doesn't work to be working properly locally today...)

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
