### PR TITLE
LPS-116622 SF - Sort by usage

### PR DESCRIPTION
**Pull request by adolfopa**
@AliciaGarciaGarcia Take a look at my changes.

About the SF issue, I'd use "SubDocument" so that it matches the type name. Before sending to Brian, we can add an SF exclusion for this file and explain to him the problem. We should also mention Hugo Huijser so that he can take a look.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
see https://github.com/liferay-lima/liferay-portal/pull/445

**Pull request closed without merging**
