### PR TITLE
LPS-127963 format current date value if not initialValueMemoized

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPS-127963

When changing to a locale with a format in which the current date is incorrect (20/02/2020 to MM/dd/yyyy) it put a invalid value and shows a message of error on the datePicker (and you can't change it again without exiting the WC)

So format the current value seems to solve it, not only the initialValueMemoized

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @carloslancha and @boton 

I send this PR to review. If some of you think is't ok, we can send to @liferay-data-engine 

Thanks for the review ;)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by boton** [comment]
LGTM, because I work on this fix with you the past week.

But I'm not sure why the initialValueMemoized has no value because. 

I think that is a good idea to send it to @liferay-data-engine before forwarding it.

**Review by boton — APPROVED** [review]

**Comment by carloslancha** [comment]
That component seems pretty complex when (I think) it shouldn't,  and the fix is pretty much a band aid. Let me try to take a look, if I don't find the time today to do it just push it forward and let's keep going with our lives :P

Thx!

**Comment by AliciaGarciaGarcia** [comment]
see https://github.com/liferay-lima/liferay-portal/pull/1537

**Pull request closed without merging**
