### PR TITLE
LPS-133387 Add Image Editor visual improvements

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-133387

- Toolbar is not floating anymore
- Fixed background color
- Improve crop handlers and lines

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@boton pr updated

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
