### PR TITLE
LPS-129643 Buttons are overlapping the pagination in DM move modal

### PR DESCRIPTION
**Pull request by boton**
**Steps to reproduce:**

1. Go to documents and media
2. Create 21 folders
3. Upload a file
4. Select the file and use the dropdown menu to move the file

**Before the fix** 
A dialog opens showing the first 20 folders, but the pagination has covered by the frame at the bottom.

image
image

**After the fix**  
The pagination display normally.

image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]
lg2m

**Comment by boton** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
