### PR TITLE
LPS-164773 | LPS-164777 KB Display/Article widget: remove tabs in configuration page

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Before the PR:** 
Screenshot 2022-10-05 at 19 20 03
Screenshot 2022-10-05 at 19 20 16

**After the PR:** 
Screenshot 2022-10-05 at 19 30 55

Also added changes for KB Article widget: 
Screenshot 2022-10-06 at 10 20 20

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:knowledge-base

**Review by boton — APPROVED** [review]
LGTM!

**Comment by austinchiang** [comment]
https://github.com/liferay-lima/liferay-portal/pull/3571

**Pull request closed without merging**
