### PR TITLE
[NOT-FOR-7.3] LPS-120183 Build lang

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
@austinchiang I need help updating the Poshi tests here.

In this PR, I've renamed the two settings portlets. Previously, both were named "Settings"; now there's a "Site Settings" and a "Asset Library Settings" portlet. There are tests that assert that the menus display "Settings", so naturally they're failing.

Thanks!

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/927

**Pull request closed without merging**
