### PR TITLE
LPS-129597 Remove obsolete usages of Liferay.Util.selectEntityHandler in document-library

### PR DESCRIPTION
**Pull request by kresimir-coko**
Part 1 of [LPS-129597](https://issues.liferay.com/browse/LPS-129597).

This PR removes usages of `Liferay.Util.selectEntityHandler` that are no longer necessary as they're included in the implementation of `openSelectionModal`.

I've tested both these removals with the help of @adolfopa.

# 🧪 Test scenarios
For both of these files you need to go to `Content & Data > Documents and Media`

## `select_file_version.jsp`
1. Upload a simple `*.txt` file, any other format won't work
2. Edit the file inside the DXP UI to create an another version
3. Select the uploaded file, click on the `i` button to show Information about the file
4. Go to the `Versions` tab, Click `Compare to...` and choose a version to compare with
5. This opens a modal that has been changed with this PR

image

## `select_restricted_file_entry_type.jsp` 
1. Make a Folder
2. Edit the Folder
3. Under the Name & Description there's a `DOCUMENT TYPE RESTRICTIONS AND WORKFLOW` tab
4. Select `Define Specific Document Type Restrictions and Workflow for This Folder (The Folder)`
5. Click on `Select Document Type`
6. A modal opened is changed in this PR

image

Part 2 of the LPS will be done (sent as a separate PR) once https://github.com/brianchandotcom/liferay-portal/pull/100629 is merged.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Similar changes to these have caused some regressions: see https://github.com/liferay-echo/liferay-portal/pull/4214

**Comment by kresimir-coko** [comment]
> @adolfopa Similar changes to these have caused some regressions: see liferay-echo#4214

Here's the explanation on what happened with the regression https://github.com/liferay-echo/liferay-portal/pull/4214#issuecomment-818470453. 

As far as this PR is concerned I have tested both of these occurrences, with your help, so they _should not_ cause any bugs, but I'm gonna double check now.

**Comment by kresimir-coko** [comment]
@adolfopa I've rebased with `master` and tested these changes, updating the PR description with the steps to test. Everything works as intended, you can test for yourself if you want to triple-check 😄 
I haven't pushed the new branch state but I can if you want.

**Comment by adolfopa** [comment]
@kresimir-coko Do you mind if we wait for the release? We're almost there ...

**Comment by kresimir-coko** [comment]
Sure @adolfopa 👍

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by boton — APPROVED** [review]
Tested both scenarios and working like a charm to me.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
