### PR TITLE
LPS-132774 Add redirection fields to index mapping

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
I will not forward till ci:test:search  finish :)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:search

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hello Folks, @liferay/qa-search

Can you please check the failures and help Adolfo to proceed?

Thanks,
Tibor

**Comment by lipusz** [comment]
:information_source: For Search related known CI results, please refer to [this](https://docs.google.com/spreadsheets/d/1cDzu4itg1XPtK4EyuwWB3MBwK3m7MpT3LqLcXltx9QA/edit?pli=1#gid=0) spreadsheet. This  can be accessed through https://search-ci.liferay.com/.

If you are not sure, feel free to reach out to the Search QA team in [#t-search-z-cont-integ](https://liferay.slack.com/archives/CLBEAPQ5D) or mention them through `@liferay/qa-search`.

Regards,
Tibi

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:search

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1037401_9734

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
Hello Folks, @liferay/qa-search

Can you please help the Lima team to decide if the search failures are relevant?

Thanks,
Tibor

**Comment by brookedalton** [comment]
Hi @Tibor, the search failures are relevant. It looks like there is a NullPointerException happening at `StringUtil.read` which is causing the search engine to not initialize.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:search

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:search

**Comment by adolfopa** [comment]
ci:test:search

**Comment by adolfopa** [comment]
ci:test:search

**Comment by adolfopa** [comment]
ci:test:search

**Comment by adolfopa** [comment]
ci:test:search

**Comment by adolfopa** [comment]
Failures seem unrelated. I'll send to search team for review and further analysis.

**Pull request closed without merging**
