### PR TITLE
LPS-182299 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-182299

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:reevaluate:1287401_7364

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
