### PR TITLE
LPS-123371 master

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi @robertoDiaz 

i tested your simplifed solution and it works.
Could you please push it forward?

Thanks, Roland

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
