### PR TITLE
LPS-121871 Migrate v2 usages in document-library/document-library-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan**:
- Navigate to **Content & Data** > **Documents and Media**
- Uploading new files should work as expected
- Editing tags should work as expected
- Deleting items should work as expected
- Moving items to a new folder should work as expected
- Creating Document Types should work as expected
- Creating Metadata Sets should work as expected

**Test plan to test edit Categories**

- Navigate to Categorization > Categories
- Add New vocabulary
- Add new categories
- Navigate to Content & Data > Documents and Media
- New icon edit categories

**Additional notes**
Originally reviewed [here](https://github.com/liferay-frontend/liferay-portal/pull/805)

**[EDIT]**
In order to test this properly, navigate to **Content & Data** > **Documents and Media**, you'll see three tabs: 
**Documents and Media**, **Document Types** and **Metadata Sets**. 

Each of these tabs has a management toolbar that is affected by these changes, and they should work as they previously used to.

You'll also have to go to the **Documents and Media** tab, create a folder (via the management toolbar), and then click on that folder's name to view and test if the management toolbar works there.

The last thing to do, is to go to the **Document Types**  tab, create a lot of document types (>20) at which point the clicking on the "More" button of the creation menu should open a modal window that has another management toolbar.

Since it seems that it's not possible to create document types right now (changes in DDM), I'm putting this on hold, but feel free to review when DDM is working again.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
