### PR TITLE
LPS-194396 Show error if AL/Site are not connected 

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Same as https://github.com/liferay-lima/liferay-portal/pull/4633 changing one word of the message.

https://liferay.atlassian.net/browse/LPS-194396

How to test it

1. Create an Asset Library
2. Create a document
3. Create a shortcut
4. Create a folder
5. try to copy to a site (liferay or _Global_)

✔️ error message is thrown (the error now is: _the site and asset library **are** not connected_
image

1. Connect to a site
2. try to copy to _the connected site_

✔️ item copied

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
no review needed, is the same as https://github.com/liferay-lima/liferay-portal/pull/4633 with an "are" instead an "is" :D

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
