### PR TITLE
[TS] LPS-180462 max-age config shouldn't have space between equals and value

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-180462

According to https://www.rfc-editor.org/rfc/rfc9111.html#name-max-age-2, max-age shouldn't have a space between the "=" and the value.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures should not be related to this PR.

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
