### PR TITLE
LPS-141019 Mentioning a user from a page they cannot access results in a broken link

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-141019

### Issue overview

When mentioning a user in a comment, we don't check to see if the user can access the page and portlet where the comment is made. Since it's related to notifications and discussions, Lima seemed like the best fit based on its current list of key DXP components.

### Steps to reproduce

1. Start a clean bundle
1. Login as admin
1. Go to [Global site > Web Content]
1. Create any random Basic Web Content
1. Go to [CP > Sites > Site Template]
1. Create a new template
1. Add an Asset Publisher to the page and configure it to:
   * Asset Selection > Scope: Global
   * Display Settings > ENABLE > Comments: ON
1. Go to [CP > Users and Organizations]
1. Create 2 users (user1 and user2)
1. For each user, in Profile and Dashboard, set the created template for Dashboard
1. Login as user1
1. Go to [User icon > My Dashboard]
1. Add a new comment to the web content and mention @user2
1. Login as user2
1. Note there is 1 notification
1. Go to [User icon > Notifications]
1. Click on the notification

### Solution overview

To resolve the issue, the fix adds information to the URL so that ServicePreAction will, when processing the request, add information about the page and portlet to the ThemeDisplay. This allows code later on to check the ThemeDisplay for the page and portlet to use for permission checks.

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
LGTM

**Comment by holatuwol** [comment]
Test failure is related, investigating.

**Comment by holatuwol** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
@holatuwol Can you take a look at the SF error? Thanks!

**Comment by holatuwol** [comment]
Whoa, it caught an actual mistake in the code.

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
