### PR TITLE
LPS-151323 bug DM uploader styles drag and drop

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-151323

Some styles are lost on DM drag and drop feedback.

**Before this PR**
image
image

**After this PR**
image
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
