### PR TITLE
LPS-162701 redirect to login if PromptEnabled is active

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
@robertoDiaz

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
@liferay-lima 

I suggest this code in https://issues.liferay.com/browse/PTR-3311 (so do not assign this PR to me)

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
