### PR TITLE
LPS-175522 KB Table View

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Description:** Add new table view page to knowledge base to show users some relevant info.

image

**Jira Ticket:** https://issues.liferay.com/browse/LPS-175523

Previously approved in https://github.com/liferay-lima/liferay-portal/pull/4021

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
Trying one more time... if it does not pass, QA please review if it could be forwarded manually, we have been patient with CI for many many days :'-(

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
The above failures are not related to this PR, sent it to BChan: https://github.com/brianchandotcom/liferay-portal/pull/131371

**Pull request closed without merging**
