### PR TITLE
LPS-170604 Depot config screen collapsible sections

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-170604

**After the fix:** 
Screenshot 2022-12-09 at 13 58 18

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
