### PR TITLE
LPS-157415 KB - frontend tests for the Vertical Bar

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @boton, I know we could add more tests here, but for now it serves as a base and we could add them later. 

Screenshot 2022-08-16 at 12 51 35

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
Review and added two things, a navigate test 75762c8ba8823b82db339f1ddbce5718f3ad94ec and avoid InnerHTML 0684ebf54168f338ec7ea4fd401937b51c97f263.

**Comment by boton** [comment]
@ambrinchaudhary check I'm not doing anything crazy and forward if you are okay with my updates. 😄

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
