### PR TITLE
[TS] LPS-159600 Active redirections on widget pages do not let users add or configure widgets

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
See [Brian's comment ](https://github.com/brianchandotcom/liferay-portal/pull/122096#issuecomment-1225556752)for context. 

> p_l_skip_redirect is not a part of PortalImpl

Only review last commit

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
cc/ @ricardocousolr @dacousalr

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1267401_4657

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_4657

**Comment by ambrinchaudhary** [comment]
Flaky test. Previously confirmed with QA and team that this can manually forwarded. See https://github.com/brianchandotcom/liferay-portal/pull/122158

**Pull request closed without merging**
