### PR TITLE
LPS-137642 Remove FFLayoutTranslatedLanguagesConfiguration

### PR DESCRIPTION
**Pull request by adolfopa**
https://issues.liferay.com/browse/LPS-137642

Don't forward until https://issues.liferay.com/browse/LPS-110354 is closed.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
tests: 
```
OpenGraphTopHeadDynamicIncludeTest. testIncludeLinkAssetDisplayPage
OpenGraphTopHeadDynamicIncludeTest. testIncludeLinkAssetDisplayPageLayoutTranslatedLanguagesCompanyEnabled
OpenGraphTopHeadDynamicIncludeTest. testIncludeLinkAssetDisplayPageLayoutTranslatedLanguagesContentLayout
OpenGraphTopHeadDynamicIncludeTest. testIncludeLinkAssetDisplayPageLayoutTranslatedLanguagesOpenGraphDisabled
OpenGraphTopHeadDynamicIncludeTest. testIncludeLinkAssetDisplayPageLayoutTranslatedLanguagesSiteEnabled
```

Will fail because : https://issues.liferay.com/browse/LPS-138244 not because this PR

**Comment by AliciaGarciaGarcia** [comment]
rebase and push :)

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The root cause of the above failures was reverted here: https://github.com/liferay/liferay-portal/compare/78e7911baadcc5baafca8a05b0a7db73c8c1c6f0...da5431eca174cb11ca689cd49ae7f4bd0616751a, re-run it.

**Comment by Hanlf** [comment]
It seems to be a CI issue, rerun it

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
[com.liferay.change.tracking.service.test.CTEntryLocalServiceTest.testGetCTRowCTCollectionId](https://testray.liferay.com/zh/home/-/testray/cases/1509069925) failure only occurs on this PR.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/106436

Though the status says LPS-110354 is still in QA review, it has been validated already and tests have been pushed in so we're good to go there.

**Pull request closed without merging**
