### PR TITLE
LPS-178109 Users are able to see Wiki pages and attachments which are still pending in the workflow

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-178109

@ChrisKian To save some time I've done some changes (mainly SF). Can you please review it? If you're ok with it, we can forward it.

Resent from https://github.com/liferay-lima/liferay-portal/pull/4110

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-178109.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
Adolfo changes look good 👍

**Comment by ChrisKian** [comment]
The changes look fine to me @adolfopa, thanks for making them!

**Comment by Jeremy-Ch** [comment]
Failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr. Send to BChan manually, see https://github.com/brianchandotcom/liferay-portal/pull/132169

**Pull request closed without merging**
