### PR TITLE
LPS-197121 DM Info Alert has the incorrect style.

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-197121

### AFTER
**Preview info**
preview - after

**Lock Info**
lock - after

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1407401_6343

**Comment by ambrinchaudhary** [comment]
ci:test:documents

**Comment by ambrinchaudhary** [comment]
ci:test:document

**Comment by ambrinchaudhary** [comment]
I think the failures given by ci:test:document are not related to this pulls. I'm going to try again ci:test:relevant to see if the previous failure it now fixed.

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
QA please review my last commit (seems it works because previously poshi test doesn't fail) and check if failures are related.  Thanks a lot!

**Comment by adolfopa** [comment]
@ambrinchaudhary QA is going to be out due to holidays, so we'll need to look into these things ourselves. Anyway, your test is failing due to markup changes (there's a missing container). Can you ping qa-flex-global in our public channel so that they can take a look?

**Comment by ambrinchaudhary** [comment]
> @ambrinchaudhary QA is going to be out due to holidays, so we'll need to look into these things ourselves. Anyway, your test is failing due to markup changes (there's a missing container). Can you ping qa-flex-global in our public channel so that they can take a look?

Requested help via slack https://liferay.slack.com/archives/CLD39UKM5/p1695910643550659

**Comment by epark18** [comment]
The test results look good to me. There are no cases of unique failures or regressions caused by this PR according to the test results for both relevant and document test suites. All listed failures are currently tracked under the following tickets:
https://liferay.atlassian.net/browse/LRQA-83134 - DMDocumentType#CanCreateDocumentwithEditedUploadField
https://liferay.atlassian.net/browse/LRQA-83138 - DMDocumentType#CanCreateDocumentwithEditedImageField
https://liferay.atlassian.net/browse/LPS-197488 - PortalSmoke#Smoke and PortalLogAssertor tests related to workflow across all environments are recent flaky issues.
https://liferay.atlassian.net/browse/LRQA-82277 - DMFileEntry#CanViewDocumentWithEditedDisplayPageTemplate - The test mentioned above for the missing container. Looks like this issue has been documented in the past, but due to its flakiness has been closed. This test ran multiple times across this PR and only failed once so I can confidently say that the work in this PR is not the cause. 
Good to go on QA side!

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
