### PR TITLE
LPS-135678 Remade the previous PR with some changes

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
This Bugs:

[ LPS-143128](https://issues.liferay.com/browse/LPS-143128) Show wrong GroupId on the Latest Version URL in the DM widget
[LPS-143129](https://issues.liferay.com/browse/LPS-143129) Portlet is temporarily unavailable for DM after deactivating staging
[ LPS-143130](https://issues.liferay.com/browse/LPS-143130) Unable to edit a file in DM portlet when staging is enabled	
[ LPS-143132](https://issues.liferay.com/browse/LPS-143132) Documents and folders in Sharepoint Repository are not displayed on DM widget
[LPS-143141](https://issues.liferay.com/browse/LPS-143141) Site Template resource doesn't inherite on personal site

Was originated by the original PR. We made some changes to fix them without this issues.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:staging

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
