### PR TITLE
LPS-194603 Handle the external repository use cases and simplify logic

### PR DESCRIPTION
**Pull request by robertoDiaz**
Seems to be related with https://github.com/liferay-lima/liferay-portal/pull/4623

I've check if this changes break this functionality, but it seems to work :)

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:help

**Comment by Jeremy-Ch** [comment]
ci:test:sharepoint

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
