### PR TITLE
LPS-163268 Revert "LPS-147681 Add javax.portlet.version=3.0"

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
This reverts commit a8ae859b27db81c4c737c7864b2c99e820d8126d.

The update of portlet version to 3 must be done to all the components or will throw an 
`Caused by: java.lang.UnsupportedOperationException: Requires 3.0 opt-in`

and when calling  `ItemSelectorPortlet` that is v2 and blocks the functionality of knowledge base.

This is a release blocker, so we're reverting the changes.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Hey @AliciaGarciaGarcia I just sent a PR with changes for opt-in 3.0 on other portlets https://github.com/brianchandotcom/liferay-portal/pull/123232

**Comment by AliciaGarciaGarcia** [comment]
Hi @ling-alan-huang 

I will close this PR, hope the blocker is solved.

Thanks!!

cc // @adolfopa

**Pull request closed without merging**
