### PR TITLE
LPS-190935 | Translation destroys html structure/text data

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-190935

See https://github.com/liferay-lima/liferay-portal/pull/4500

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by matthiasblaesing** [comment]
@ambrinchaudhary no problem. I created an internal test build of Liferay 7.4.3.85 with my URL fix and this changeset applied to test and maybe put into production. My intention of the patches if primary, that later updates don't create regressions.

I tested with another text today and noticed another issue in the DeepL translator implementation. The input text was this this (shortend):

> Warnung vom 26. Juli 2023 – IT-Sicherheit

The dash in the middle is the unicode char "En Dash (unicode U+2013)". I noticed, that after translation a question mark was present in the text after the date, before the translation of "IT-Sicherheit".

I checked the send data and got this:

```
target_lang=EN&source_lang=DE&text=%3Cdiv+class%3D%22portlet-content-container%22%3E%0A%3Cdiv+class%3D%22portlet-body%22%3E%0A%3Cdiv+data-fragments-editor-item-id%3D%2210078-11782228%22+data-fragments-editor-item-type%3D%22fragments-editor-mapped-item%22%3E%0A%3Cdiv+class%3D%22journal-content-article+%22+data-analytics-asset-id%3D%2211782226%22+data-analytics-asset-title%3D%22Aktuelle+Meldungen_text%22+data-analytics-asset-type%3D%22web-content%22%3E%0A%3Cp%3EWarnung+vom+26.+Juli+2023+%3F+IT-Sicherheit%3C%2Fp%3E%0A%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3C%2Fdiv%3E%0A%3C%2Fdiv%3E&tag_handling=html
```

At the critical place I see `%3F`, which is an URL encoded question mark. Indeed the http client does not receive a charset and without that, latin-1 is used, which can't map the "en dash".

I tried to check if it is possible to pass the encoding to the http client and did not find one. The alternative approach is to drop the urlencoded-formdata API from deepl and use the JSON one. Then you can encode the JSON directly as body for the request, set the content type for that and it will be correctly transmitted.

Indeed, that fixed the problem for me. The patch below was attached. This can be either be included by you/@austinchiang through this PR or I supply the changeset after this is done.

```diff
--- a/modules/apps/translation/translation-translator-deepl/src/main/java/com/liferay/translation/translator/deepl/internal/translator/DeepLTranslator.java
+++ b/modules/apps/translation/translation-translator-deepl/src/main/java/com/liferay/translation/translator/deepl/internal/translator/DeepLTranslator.java
@@ -160,9 +160,7 @@
 
 		options.addHeader(
 			HttpHeaders.AUTHORIZATION, "DeepL-Auth-Key " + authKey);
-		options.addHeader(
-			HttpHeaders.CONTENT_TYPE,
-			ContentTypes.APPLICATION_X_WWW_FORM_URLENCODED);
+
 		options.setLocation(url);
 
 		try {
@@ -215,19 +213,31 @@
 			return text;
 		}
 
+		JSONObject requestJSONObject = _jsonFactory.createJSONObject();
+
+		if ((html != null) && html) {
+			requestJSONObject.put("tag_handling", "html");
+		}
+
+		requestJSONObject.put(
+			"source_lang", sourceLanguageCode
+		).put(
+			"target_lang", targetLanguageCode
+		).put(
+			"text", new String[] {text}
+		);
+
+		Http.Body body = new Http.Body(
+			requestJSONObject.toString(), ContentTypes.APPLICATION_JSON,
+			"UTF-8");
+
 		Http.Options options = new Http.Options();
 
 		options.addHeader(
-			HttpHeaders.AUTHORIZATION,
-			"DeepL-Auth-Key " + deepLTranslatorConfiguration.authKey());
+			HttpHeaders.CONTENT_TYPE, ContentTypes.APPLICATION_JSON);
 
-		if ((html != null) && html) {
-			options.addPart("tag_handling", "html");
-		}
+		options.setBody(body);
 
-		options.addPart("source_lang", sourceLanguageCode);
-		options.addPart("target_lang", targetLanguageCode);
-		options.addPart("text", text);
\ No newline at end of file
 		options.setMethod(Http.Method.POST);
 
 		JSONObject jsonObject = _jsonFactory.createJSONObject(
```

**Comment by AliciaGarciaGarcia** [comment]
Hi @matthiasblaesing @ambrinchaudhary and @austinchiang 

I can not push changes on this PR so I will create a new one and push there the changes sugested by @matthiasblaesing on this [comment](https://github.com/liferay-lima/liferay-portal/pull/4501#issuecomment-1654459019) (thanks!!) 
And some minor changes as semVer

**Pull request closed without merging**
