### PR TITLE
[TS] LPS-186835 - truncating to solely the body when transforming AM HTML content can cause template content loss

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-lima!

https://issues.liferay.com/browse/LPP-49128
https://issues.liferay.com/browse/LPS-186835

I'm sending this specifically to you guys since this deals with partially reverting changes made in [LPS-148916](https://issues.liferay.com/browse/LPS-148916) - "Regex in AMBackwardsCompatibilityHtmlContentTransformer.java has exponential complexity". We have a client reporting that when they use the getArticleDisplay() API in JournalArticleLocalServiceUtil that they are not retrieving the full content of their template.

For example, if their template is:
```
<html>
<head>
</head>
<body>
<p> Group Id - ${groupId} - PRINT THIS PAGE AND BRING TO CENTER -</p>
<img alt="Logo graphic" src="${LogoUpdate.getData()}"/>
</body>
</html>
```

They're seeing only the `<p>` and `` parts.

This is due to us specifically grabbing only the body of the document. I reverted this specific part of the change back to being the entire document so we don't lose non-body content. I did test using the reproduction steps in LPS-148916 and was not able to reproduce the issues reported, but please let me know if there's something I'm missing and I'll take a look. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @wanderlast 
The two AM failure is related to this PR, could you take a look?
failure1: [com.liferay.adaptive.media.image.content.transformer.test.AMImageContentTransformerTest](https://testray.liferay.com/reports/production/logs/2023-06/test-1-31/test-portal-acceptance-pullrequest(master)/8292/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
```
     [exec] com.liferay.adaptive.media.image.content.transformer.test.AMImageContentTransformerTest > testTransformASingleImage STARTED
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.test.AMImageContentTransformerTest > testTransformASingleImage FAILED
     [exec]     java.lang.AssertionError
     [exec]     	at org.junit.Assert.fail(Assert.java:87)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:42)
     [exec]     	at org.junit.Assert.assertTrue(Assert.java:53)
     [exec]     	at com.liferay.adaptive.media.image.content.transformer.test.AMImageContentTransformerTest.testTransformASingleImage(AMImageContentTransformerTest.java:106)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
[beanshell] 2023-06-07 05:24:43.311 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:80] STOPPED com.liferay.adaptive.media.image.content.transformer.test_1.0.0 [1535]
```
failure2: [com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest](https://testray.liferay.com/reports/production/logs/2023-06/test-1-31/test-portal-acceptance-pullrequest(master)/8292/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
```
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReturnsBlankForBlankContent PASSED
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReplacesImageTagsWithDoubleQuotes STARTED
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReplacesImageTagsWithDoubleQuotes FAILED
     [exec]     org.junit.ComparisonFailure: expected:<<[p>Prefix[REPLACED]Suffix</p]>> but was:<<[html><head></head><body><p>Prefix[REPLACED]Suffix</p></body></html]>>
     [exec]         at org.junit.Assert.assertEquals(Assert.java:115)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:144)
     [exec]         at com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest.testReplacesImageTagsWithDoubleQuotes(AMBackwardsCompatibilityHtmlContentTransformerTest.java:125)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
     [exec]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec]         at java.lang.Thread.run(Thread.java:745)
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReplacesImageTagsWithLongTitleWithSpaces STARTED
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReplacesImageTagsWithLongTitleWithSpaces FAILED
     [exec]     org.junit.ComparisonFailure: expected:<<[p>Prefix[REPLACED]Suffix</p]>> but was:<<[html><head></head><body><p>Prefix[REPLACED]Suffix</p></body></html]>>
     [exec]         at org.junit.Assert.assertEquals(Assert.java:115)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:144)
     [exec]         at com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest.testReplacesImageTagsWithLongTitleWithSpaces(AMBackwardsCompatibilityHtmlContentTransformerTest.java:149)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
     [exec]         at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
     [exec]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     [exec]         at java.lang.Thread.run(Thread.java:745)
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReturnsTheSameHTMLIfNoImagesArePresent STARTED
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReturnsTheSameHTMLIfNoImagesArePresent PASSED
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReplacesImageTagsWithSingleQuotes STARTED
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReplacesImageTagsWithSingleQuotes FAILED
     [exec]     org.junit.ComparisonFailure: expected:<<[p>Prefix[REPLACED]Suffix</p]>> but was:<<[html><head></head><body><p>Prefix[REPLACED]Suffix</p></body></html]>>
     [exec]         at org.junit.Assert.assertEquals(Assert.java:115)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:144)
     [exec]         at com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest.testReplacesImageTagsWithSingleQuotes(AMBackwardsCompatibilityHtmlContentTransformerTest.java:157)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
     [exec]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec]         at java.lang.Thread.run(Thread.java:745)
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReturnsNullForNullContent STARTED
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReturnsNullForNullContent PASSED
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReplacesImageTagsWithLegacyContent STARTED
     [exec] 
     [exec] com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest > testReplacesImageTagsWithLegacyContent FAILED
     [exec]     org.junit.ComparisonFailure: expected:<<[p>Prefix[REPLACED]Suffix</p]>> but was:<<[html><head></head><body><p>Prefix[REPLACED]Suffix</p></body></html]>>
     [exec]         at org.junit.Assert.assertEquals(Assert.java:115)
     [exec]         at org.junit.Assert.assertEquals(Assert.java:144)
     [exec]         at com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest.testReplacesImageTagsWithLegacyContent(AMBackwardsCompatibilityHtmlContentTransformerTest.java:139)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]         at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
     [exec]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec]         at java.lang.Thread.run(Thread.java:745)
```

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failure is not related to this PR

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR>

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failure is unrelated.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward

**Pull request closed without merging**
