### PR TITLE
LPS-121084 Create a wrapper method that will send the multipleSelection param to the backend views

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by jbalsas — COMMENTED** [review]
It feels weird that this is exported from `item-selector-taglib` when the portlet is (I guess) in `item-selector-web`. 

Other than that, it looks good to me! 👍

**Review by 4lejandrito — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
@4lejandrito thinks the same. I'll change that. Thank you both!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/813.

**Pull request closed without merging**
