### PR TITLE
LPS-190860 add the displayDate on the creation and update methods of the KBArticle

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
This is a follow up PR from the

https://liferay.atlassian.net/browse/LPS-188060 : Schedule a Knowledge Base Article

On this PR I added the new field of the KBArticle table to the add and update methods.

The user will not have information about this field.
Field must not be null so validation is done.

Now the update will update every time the displayDate field.

Rebased from https://github.com/liferay-lima/liferay-portal/pull/4503

- LPS-190860 add displayDate parameter on addKBArticle and updateKBArticle methods
- LPS-190860 add the displayDate to the validation method
- LPS-190860 buildService
- LPS-190860 baseline
- LPS-190860 add displayDate parameter to addKBArticle
- LPS-190860 fix updateKBArticle calls
- LPS-190860 add displayDate to service
- LPS-190860 buildService
- LPS-190860 add displayDate on calls of the service
- LPS-190860 fix updateKBArticle on tests
- LPS-190860 autoSF
- LPS-190860 add test to check the validation of the displayDate

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1377401_13487

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1307401_7344

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:help

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1267401_10864

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
The failures are unrelated. Forward directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
