### PR TITLE
LPS-116355 User does not receive mail for own blog entry creation

### PR DESCRIPTION
**Pull request by IstvanD**
Dear @liferay-lima 

A customer wanted to receive notifications about their own Blog Entries.
I added a configuration option for that.

In your opinion, is this the correct approach?

As you see, a major version bump happened with these changes.
Should the solution be modified so that only a minor version elevation takes place?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @IstvanD,

I think that's not a bad approach. The major change is caused by the fact that [BlogsGroupServiceOverriddenConfiguration](https://github.com/liferay/liferay-portal/blob/ed74f4842f4231a94fc60847316fef247a73f6d1/modules/apps/blogs/blogs-api/src/main/java/com/liferay/blogs/configuration/BlogsGroupServiceOverriddenConfiguration.java#L24) extends from your configuration. 

If you change the new method to:

```
	@Meta.AD(
		deflt = "false", name = "send-notifications-to-blogs-entry-creator",
		required = false
	)
	public default boolean sendNotificationsToBlogsEntryCreator() {
            return false;
        }
```

It will require just a minor change.

What do you think @adolfopa?

**Comment by IstvanD** [comment]
Hi @4lejandrito 

Thank you for the suggestions. I modified the solution and created a new pull
https://github.com/liferay-lima/liferay-portal/pull/346

**Comment by adolfopa** [comment]
Closing in favor of https://github.com/liferay-lima/liferay-portal/pull/346

**Pull request closed without merging**
