### PR TITLE
LPS-136388 Apply DL validation only to DL repositories

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:liferay-online

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:liferay-online

**Comment by adolfopa** [comment]
ci:test:liferay-online

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
@adolfopa @AliciaGarciaGarcia The failure in the liferay-online upgrade test is unrelated to this change. The smoke test is passing, so this fixes the issue with the file extension validation when liferay-online properties are applied. CC @vicnate5

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Pull request closed without merging**
