### PR TITLE
LPS-164161 Declare missing parameters in other macros

### PR DESCRIPTION
**Pull request by austinchiang**
On is the second PR we add the new fields to the KBArticleService and we let it prepare to the fields to be added on the pages.

LPS-164161 add expiration date and review date to service add and update methods
LPS-164161 buildService
LPS-164161 fix calls to KBArticleService

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1397401_1016

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1297401_5030

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
