### PR TITLE
LPS-171232 The description field can not be displayed after enabling it on the widget

### PR DESCRIPTION
**Pull request by hongvo2308**
Hi, 
This is the PR for the ticket https://issues.liferay.com/browse/LPS-171232.
Please review this and leave your comments.
Thank you.

**Summary:**
There is no implementation for displaying descriptions on KB widget
**Reproduce Step:**
Please see the ticket https://issues.liferay.com/browse/LPS-171232
**Solution:**
Add new implementation for description displaying

CC: @ces-huynguyen

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
We're thinking of removing the description field altogether (it's never been really useful). Putting this on hold until we decide.

**Comment by AliciaGarciaGarcia** [comment]
Hi

This we will take care of this issue on the https://issues.liferay.com/browse/LPS-172372 story

Thanks!!!

**Pull request closed without merging**
