### PR TITLE
LPS-137689 Add custom editor config for layout translation

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@boton No changes other than minor refactorings. It looks good to me; maybe we can show it to Pablo tomorrow to make the PM review faster/painless.

**Comment by boton** [comment]
LGTM, I haven't tried it yet, but maybe we can try Pablo tomorrow as you said.

**Review by boton — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:bundle

**Comment by liuxingye** [comment]
Hi @boton 
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive621021](https://testray.liferay.com/zh/home/-/testray/case_results/1555392222)
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive70106](https://testray.liferay.com/zh/home/-/testray/case_results/1555392245)
These failing cases are related to this pull, the error occurs as following when upgrading from [6.2.10.21](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/6.2.10.21/data-archive/data-archive-portal-mysql.zip) or [7.10.6](https://github.com/liferay/liferay-qa-portal-legacy-ee/blob/master/7.0.10.6/data-archive/data-archive-portal-mysql.zip) to head (I used the [bundle](https://github.com/liferay-lima/liferay-portal/pull/2168#issuecomment-904217194) here).

>     [java] 2021-08-24 00:37:38.681 ERROR [main][LayoutTranslateEditorConfigContributor:93] bundle com.liferay.translation.web:2.0.15 (974)[com.liferay.translation.web.internal.editor.configuration.LayoutTranslateEditorConfigContributor(8403)] :  Error during instantiation of the implementation object 
>      [java] java.lang.ExceptionInInitializerError: null
>      [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_121]

Details [here](https://testray.liferay.com/reports/production/logs/2021-08/test-1-14/test-portal-acceptance-pullrequest(master)/8472/functional-upgrade-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz)

Thanks.

**Comment by boton** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
I'll resend with further changes.

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/2185

**Pull request closed without merging**
