### PR TITLE
LPS-133166 Order By Modification date for Docs and Media folders will display the Last Post Date

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

One of the customers finds it confusing that while the folders are sorted by modification date the Modified Date column in shows their Last Post Date.
To be clear, these two fields are updated at different events:

- `modifiedDate` is updated when the folder itself is modified eg. its title is changed or a description is added
- `lastPostDate` is updated when a file or subfolder is created in the folder

The customer would be fine with it when the `modifiedDate` would be shown instead of `lastPostDate`. The changes in the pull achieve exactly that.
But I'm not sure if we should alter the behavior this way. For example, other users would expect to still view the `lastPostDate`.

Maybe we could add an option for sorting by `lastPostDate`? This would be tricky though as all of the sortings for files, folders and shortcuts are done by Repository Model Comparators (for example [RepositoryModelModifiedDateComparator](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/document/library/kernel/util/comparator/RepositoryModelModifiedDateComparator.java)), and while all repository entries have a `modifiedDate` field, only folders have a `lastPostDate` field. A Repository Model Comparators thus would not be able to compare base on `lastPostDate`.

Alternatively, should we suggest a workaround/customization for the customer?

Thank you and best regards,
István

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@IstvanD I'll keep this on hold for a while. I would like to keep using lastPostDate, and change the sorting logic so that it uses lastPostDate for folders. If it is too tricky to fix that, I'll forward your PR.

**Comment by IstvanD** [comment]
Hi @adolfopa 

I have tried to find a method for adding lastPostDate sorting option for folder's but I ran into the complex problems outlined above, so I couldn't make it.

Therefore, please forward the PR.

Thank you and best regards,
István

**Comment by IstvanD** [comment]
Hi @adolfopa 

Will this pr be forwarded or should we indeed go with another solution?

Best regards,
István

**Comment by adolfopa** [comment]
I'll look into that tomorrow. I'll try to extend the RepositoryModelComparator API to cater for this case.

**Comment by adolfopa** [comment]
It is not impossible to support this, but it is too messy, and involves creating new API in core. I think it is best to keep it simple and uniform, so I'll forward your pull (even if it changes behaviour slightly, it is more consistent).

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
