### PR TITLE
LPS-146060 Use repository ID defined in portlet settings

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa :

It solves the bug but breaks the staging on the D&M widget like happened on this tickets: 
[[LPS-143128] Show wrong GroupId on the Latest Version URL in the DM widget](https://issues.liferay.com/browse/LPS-143128)
[[LPS-143130] Unable to edit a file in DM portlet when staging is enabled](https://issues.liferay.com/browse/LPS-143128)
And it do not let upload files on the DM Widget (it fails silently)

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
Hi @adolfopa :

It solves the bug but breaks the staging on the D&M widget like happened on this tickets: 
[[LPS-143128] Show wrong GroupId on the Latest Version URL in the DM widget](https://issues.liferay.com/browse/LPS-143128)
[[LPS-143130] Unable to edit a file in DM portlet when staging is enabled](https://issues.liferay.com/browse/LPS-143128)
And it do not let upload files on the DM Widget (it fails silently)

**Comment by adolfopa** [comment]
Need additional work.

**Pull request closed without merging**
