### PR TITLE
LPS-197416 | Correct misalignment of long titles on DDM and KB

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description:** Corrected misalignment found between icons and titles for items with long titles after  [LPS-196690](https://liferay.atlassian.net/browse/LPS-196690) 
image

**Jira Ticket:** https://liferay.atlassian.net/browse/LPS-197416

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Hey @jaimelr10 thanks for the fix. On the original [pull](https://github.com/brianchandotcom/liferay-portal/pull/141128) that caused this regression there were changes in `DocumentLibrary.js` that I guess we should also add here. Probably the row classes are not needed:

```
const TPL_ENTRY_ROW_TITLE = `<div class="autofit-row ${
	CSS_APP_VIEW_ENTRY + STR_SPACE + CSS_ENTRY_DISPLAY_STYLE
}">
```

You can test this section when you drag&drop an item to the Document library from your file browser.

**Comment by jaimelr10** [comment]
ci:test:relevant

**Review by ambrinchaudhary — COMMENTED** [review]
My only concern here is that the original ticket https://liferay.atlassian.net/browse/LPS-196690 says the margin should be 8px, but `pr-1` adds 16px if I'm not wrong. I think we can talk to UX/Design to see if this solution fits their expectations.

**Comment by jaimelr10** [comment]
> My only concern here is that the original ticket https://liferay.atlassian.net/browse/LPS-196690 says the margin should be 8px, but `pr-1` adds 16px if I'm not wrong. I think we can talk to UX/Design to see if this solution fits their expectations.

In bootstrap, when we put [pr-1, it means 0.25rem](https://getbootstrap.com/docs/4.0/utilities/spacing/#:~:text=1%20%2D%20(by%20default)%20for%20classes%20that%20set%20the%20margin%20or%20padding%20to%20%24spacer%20*%20.25). In this case it would be `4px`, so `pr-1` and `pl-1` makes `8px`
image

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1257401_3544

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
