### PR TITLE
LPS-125108 CKEditor in comments

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Before (AlloyEditor): 
Comments CKEditor - Before

**After (CKEditor):** 
Comments CKEditor - After

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
@austinchiang @Jeremy-Ch @Hanlf @liuxingye could someone please help me to fix this poshi errors? Now AlloyEditor is replaced by CKEditor for comments. 
Thanks a lot!

**Comment by Hanlf** [comment]
ci:test:bundle

**Comment by Hanlf** [comment]
Closed it and resend it here: https://github.com/liferay-lima/liferay-portal/pull/1279

**Pull request closed without merging**
