### PR TITLE
LPS-190686 remove the read only on RelatedContent on BlogPosting

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-190686

- LPS-190686 remove the read only on RelatedContent on BlogPosting
- LPS-190686 buildRest

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:headless

**Comment by AliciaGarciaGarcia** [comment]
ci:test:blogs

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
