### PR TITLE
LPS-121946 Revert LPS-92325

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test.sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:document

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Only Sharepoint REST and Google Docs (marketplace) tests were failing, but they don't look related. All other tests are passing so I will foward this pull. https://liferay.spiraservice.net/16/Build/59476.aspx

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
