### PR TITLE
LPS-172863 enabling description field on KB widgets

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-172863 on the edition show the description field
- LPS-172863 show the description panel on the view of the article
- LPS-172863 view the article description only if is enabled and is not empty
- LPS-172863 on searching the value of the attribute is lost so we must recreate it

Decisions taken here.

The editor of the file will be always be active because the change of the way we are creating the edit url (always with the admin_portlet)
On the admin portlet the description field will be always shown, the difference will be on the widgets.

use on the KB Article Wdget:
https://user-images.githubusercontent.com/47524751/213459226-65d96812-9240-4036-8d84-167cb69755b3.mp4

On the KB Display Widget
https://user-images.githubusercontent.com/47524751/213459635-6cc61f97-3869-42af-bab8-5efc35213975.mp4

On the search Widget
https://user-images.githubusercontent.com/47524751/213459988-75030fb7-6933-41bd-921a-39b321891224.mp4

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
The section One:

You should create a (or several) sections on System Settings > Knowledge base > Section widget
After that add the section to the article, ONLY articles under a folder are elegibles to select the sections 
select the desired sections on the Widget

https://user-images.githubusercontent.com/47524751/213465118-ece0dd8d-1125-4ae7-ab84-0fd8648a2a05.mp4



https://user-images.githubusercontent.com/47524751/213464824-417650d8-0b59-4e33-9a70-2293785fccc4.mp4

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
