### PR TITLE
LPS-123392 Add servlet context to get the correct module name when using Asset Publisher

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-123392

We are unable to edit a message thread through an Asset Publisher because the module name was not rendering correctly.
To fix this issue, I followed the proposed solution from previous PR [comment](https://github.com/liferay-frontend/liferay-portal/pull/513#pullrequestreview-534392187)

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
