### PR TITLE
LPS-131706 add the company of the base model to the method of move image

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]
Very good job @AliciaGarciaGarcia :+1:

**Comment by adolfopa** [comment]
ci:forward

**Comment by vicnate5** [comment]
@AliciaGarciaGarcia @adolfopa Known regression (https://issues.liferay.com/browse/LPS-132540) still present on this change according to https://github.com/liferay-lima/liferay-portal/pull/1851#issuecomment-844435088.

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia It's complaining about autogen stuff. Can you rerun service builder and push any changes?

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia I'm going to work on the issue locally.

**Pull request closed without merging**
