### PR TITLE
LPS-191938 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-191938

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:notifications

**Comment by austinchiang** [comment]
ci:test:notifications

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
