### PR TITLE
LPS-182864 remove FF LPS-182020

### PR DESCRIPTION
**Pull request by marcogalluzzi**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
On Hold: There is some stories on Testing and some fixed on some of that stories.

**Comment by marcogalluzzi** [comment]
I've rebased the PR and removed a reference in "portal.properties". 

Please QA team have a look to this file where the FF LPS-182020 appears:

* MBAdmin.testcase

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by marcogalluzzi** [comment]
> I've rebased the PR and removed a reference in "portal.properties".
> 
> Please QA team have a look to this file where the FF LPS-182020 appears:
> 
> * MBAdmin.testcase

Hi @Jeremy-Ch can you please check this? Thanks

**Review by adolfopa — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
Hi @marcogalluzzi I removed the FF from the Poshi test, thanks.

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
I will check the failures after this run. If the failures are unrelated to the PR. I will send this pr to BChan directly.

**Comment by Jeremy-Ch** [comment]
The failed related Poshi test [LocalFile.MBAdmin#RootMessageSiblingsAndParentsAreDefinedInDefaultTemplates](https://testray.liferay.com/home/-/testray/case_results/2351966816?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2351966463%26testrayRunId%3D2351966504%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) passed locally. Besides that, other failures are not related to this PR.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
