### PR TITLE
LPS-196281 fix label

### PR DESCRIPTION
**Pull request by marcogalluzzi**
See: https://liferay.atlassian.net/browse/LPS-196281

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
I don't think failing tests are related. Forcing forward.

**Comment by marcogalluzzi** [comment]
ci:foward:force

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
