### PR TITLE
LPS-188418 Fallback into deleted area

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-188418

This is a WIP. There are some failing tests in `document-library-test` that need some work. In particular, there are two problems:
  * `DeleteStalePWCVersionsUpgradeProcessTest` is failing.
  * `DLFileVersionHistoryTest` takes too long to run (performance issue).

Other tests in `document-library-test` may fail as well, so after these two issues are fixed, it could be a good idea to run a selection of those (not all; in particular, those involving the persistence can be skipped).

To reproduce these issues, remember that you have to:
  * Enable feature flag `LPS-174816`.
  * Configure and enable the GCS store.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1297401_7641

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:stable

**Comment by WYZ-Issac** [comment]
The failures are unrelated. Forward directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
Hi @adolfopa, could you please fix the SF issue? Then I will forward it.

**Comment by austinchiang** [comment]
The SF issue is unrelated to this pull (it's happening in upstream now)

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Sent a fix for the SF issue in https://github.com/liferay-lima/liferay-portal/pull/4483

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
Test failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
