### PR TITLE
LPS-185222 Add new files to the 'new' area instead of 'live'

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-185222

Instead of adding new files to the 'live' area, add them to a new 'new' area.

The use case that makes this necessary is the following:
1. Add file A.
2. Take a DB snapshot.
3. Add file B.
4. Restore DB snapshot.

At this point, file B is an orphan, there's no reference in the database pointing to it and so it cannot be easily removed.  To avoid leaking storage space each time a backup is restored, we need a way of detecting these files that doesn't involve scanning the whole store.

By adding new files to the 'new' area, we can implement a background process (which I'll send in a followup pr) that will scan the 'new' area looking for unreferenced content. As the 'new' area will be much smaller than 'live', this process will consume less time and resources than if it had to scan the whole store.

Note that files in 'new' will be promoted to 'live' after 31 days (by default), as we won't support "going back in time" for periods longer that the configured value. That job will be performed by the same background process that cleans up 'new'. It will work similarly to the one we already have for the 'deleted' area.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Review by marcogalluzzi — APPROVED** [review]

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
