### PR TITLE
LPS-130384  extension now admit prefix

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPS-130384

Fixing some of the failed test on https://github.com/liferay-lima/liferay-portal/pull/1776

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
The failures above should not be related to this pull.
PortalSmoke#Smoke is an unstable failed test.
com.liferay.portal.search.indexer.scores.test.IndexerScoreDistortionTest.testTitleIndexedInTriplicateDistortsScores failure is filed here: [LPS-129707](https://issues.liferay.com/browse/LPS-129707), also an an unstable failure.
So I will rerun it

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia This looks good to me as is. Are you ok if I forward this directly?

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa perfect to forward for me,

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
