### PR TITLE
LPS-171491 baseline

### PR DESCRIPTION
**Pull request by ealonso**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-171491)

Remove old TrashService from portal-kernel and portal-impl

## Proposed solution

In order to remove old TrashService move related logic from portal-kernel and portal-impl to wrapper classes. Also create some necessary methods to make it possible.

## Notes

Commits to review:

* 4dafb80
* 4f8f728
* a7338cd
* 5cbb471

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @adolfopa @AliciaGarciaGarcia,

Could someone in your team review the test failures to know if those are related or not?

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Sending to Brian since the failures from https://github.com/liferay-lima/liferay-portal/pull/3872#issuecomment-1364336318 and https://github.com/liferay-lima/liferay-portal/pull/3872#issuecomment-1364128032 are not the same.

**Pull request closed without merging**
