### PR TITLE
LPS-175062 The suggestion pane was expanded on the left when closing the product menu

### PR DESCRIPTION
**Pull request by marcogalluzzi**
See related issue https://issues.liferay.com/browse/LPS-175062

I think the fix is OK but I have the feeling that the whole _VerticalBar.js_ can be refactored to better manage the _SuggestionPane_ specific case to avoid so many IF conditions.

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Review by jaimelr10 — APPROVED** [review]
LGTM! :)

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:forward

**Pull request closed without merging**
