### PR TITLE
LPS-148916 Regex in AMBackwardsCompatibilityHtmlContentTransformer.java has exponential complexity

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @IstvanD 
The above failures should be related to this PR, could you take a look?
[com.liferay.adaptive.media.image.content.transformer.test.AMImageContentTransformerTest](https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/2958/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
[com.liferay.adaptive.media.image.content.transformer.backwards.compatibility.internal.AMBackwardsCompatibilityHtmlContentTransformerTest](https://testray.liferay.com/reports/production/logs/2022-03/test-1-32/test-portal-acceptance-pullrequest(master)/2958/modules-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by IstvanD** [comment]
Hi @Hanlf 

I have corrected and force-pushed the solution.
Could you please test it again?

Thank you,
István

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
