### PR TITLE
LPS-186856 The Office 365 window can not pop up when adding a file in DM admin for first time

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Resending PR #4568 after fixing what suggested:

> REDIRECTING_OAUTH2_ATTRIBUTE_NAME should be in *WebKeys
> Everything in there is an attribute name.

Linked issue: https://liferay.atlassian.net/browse/LPS-186856

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by austinchiang** [comment]
Test failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
