### PR TITLE
LPS-199855 KB Search:  remove underline from results

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue: https://liferay.atlassian.net/browse/LPS-199855 

### Before: 
Screenshot 2023-10-24 at 21 00 58

### After: 
Screenshot 2023-10-24 at 20 58 27

### CODE REVIEW

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
