### PR TITLE
LPS-165773 | Change default sort order to fix LPS-165773

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description:** Change default sort order to fix the  bug described on [LPS-165773](https://liferay.atlassian.net/browse/LPS-165773) and also to match other portal appearances of the "Reverse Sort Direction" icon on search containers.

**Jira Ticket:** https://liferay.atlassian.net/browse/LPS-165773

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @jaimelr10 
This Poshi test failure is caused by this PR: when searching for a **blog title**, the search result is in the wrong order.
Steps to reproduce:
1. Go to Blogs
2. Add one blogs entry(Title: Unique Title, Content: Blogs Entry Content)
3. Add another blogs entry(Title: Blogs Entry Title, Content: Blogs Entry Text)
4. Go to the Blog admin page, change the show view to "list" and search "**Unique Title**" in the Search bar
5. Check the search result
Actual result:
Search results are returned in the wrong order: Blogs Entry Title as the first, then the Unique Title.

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
This change doesn't solve the problem. If I'm not mistaken, the problem is that when there is a search (only on a search) we have to set two things:
* Sort by column "Relevant"
* Sort by "Descending" order

**Comment by jaimelr10** [comment]
> This change doesn't solve the problem. If I'm not mistaken, the problem is that when there is a search (only on a search) we have to set two things:
> 
> * Sort by column "Relevant"
> * Sort by "Descending" order

So @marcogalluzzi, this should be done changing the default search sort order from ascending to descending? Or changing the Poshi test to do this extra step? Thanks!

**Comment by marcogalluzzi** [comment]
The proposed change doesn't fix the problem, so I discard this PR

**Pull request closed without merging**
