### PR TITLE
LPS-165024 Hide card body when we don't have actions

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
In order to stop using old frontend taglib replace the usages on image gallery of frontend vertical cards and replace with clay card

[LPS-165024](https://issues.liferay.com/browse/LPS-164539)

Proposed Solution
========
Creates new vertical card for file entry and replace the usages on jsps

----------

**NOTE** I added a new css class to hide the title when we don't have actions to keep the same logic that we have at this moment see: [7d87f12](https://github.com/liferay-lima/liferay-portal/pull/3566/commits/7d87f12e6eabf7450fe614dadf23c80cee55a4e3).

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1397401_677

**Comment by boton** [comment]
ci:stop

**Review by boton — CHANGES_REQUESTED** [review]
Sorry, It isn't working for me.

**Before PR clicking on any card open the modal:**
image

**After PR clicking on any card do nothing:**
image

The DLFileEntryDropdownPropsTransformer is expecting `{items, ...rest}` only the action part and getting the entry vertical card props, and sadly it is called when the actions are disabled.

image

**Comment by boton** [comment]
Another visual bug related to 7d87f12e6eabf7450fe614dadf23c80cee55a4e3 it is losing the bottom border-radius feels weird because the constructor is assuming that after the image we have a body and don't add the `card-item-last` CSS class internally.

image

@ealonso you are the real expert on vertical cards, if only pass here we can add an isolated fix like 7d87f12e6eabf7450fe614dadf23c80cee55a4e3 but if happens in another places maybe have more sense to update the  [VerticalCardTag](https://github.com/liferay/liferay-portal/blob/410123945a2bd55e8d58aa8e0baf51cd2235e4d0/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/VerticalCardTag.java#L440)

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
See: https://github.com/liferay-lima/liferay-portal/pull/3569

**Pull request closed without merging**
