### PR TITLE
LPS-167299 Management toolbar sort icon: include direction 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Previously approved and forwarded https://github.com/brianchandotcom/liferay-portal/pull/126989

Changed what Brian's suggested in https://github.com/brianchandotcom/liferay-portal/pull/126989#issuecomment-1330890982

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
Manually forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/127084

**Pull request closed without merging**
