### PR TITLE
LPS-141264 Update the text about depot auto tagging settings

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
This will change the message from "Enable Auto Tagging of Assets on This Asset Library" to "Enable Auto Tagging" to be more consistent with asset library
Captura de pantalla 2021-11-03 a las 7 28 03

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@Jeremy-Ch If you're ok with this PR, please do a forward after your review. Thanks!

**Comment by Jeremy-Ch** [comment]
Hi @adolfopa @AliciaGarciaGarcia  Do we need to update the auto-tagging switch text in the site settings?
image (2)

**Comment by Jeremy-Ch** [comment]
ci:forward

**Pull request closed without merging**
