### PR TITLE
LPS-139069 Filter Global site by ActionKeys.VIEW actionId

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you pleae review my fix?

**Description**
If a non admin user wants to select images from documents and media, the Global site is visible as well where the user does not have membership. Although the user does not see or has access to this site.

**Expected Result:**
The Global site is not visible and the pagination will show the number of pages where the user has access

**Actual Result:**
 The Global site is visible, although the user does not see or has access to this site.

Thanks, Roland

https://issues.liferay.com/browse/LPS-139069

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
I ran the GroupItemSelectorProviderImplTest on local and for me the **testGetGroups** PASSED

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @liuxingye 

I ran the GroupItemSelectorProviderImplTest on local and for me the testGetGroups PASSED
Could you please check this on your side too?

Thanks, Roland

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Hi @rolandpakai, I ran the GroupItemSelectorProviderImplTest on local and the testGetGroups **PASSED**. Thanks

**Comment by rolandpakai** [comment]
Hi @liuxingye 

Great!
Thank you for the testing.
How can we now forward this in case the relevant test always failes....?

Roland

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@rolandpakai Let's wait a little bit to give them time to fix the underlying issue.

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
@rolandpakai @liuxingye I run the tests on both master and on top of this PR, and I get the same failure as the CI. Can you please check again?

**Comment by rolandpakai** [comment]
Hi @adolfopa 

could you please share the details about how did you ran the test?

Thanks, Roland

**Comment by adolfopa** [comment]
@rolandpakai These were the steps:
1. Checkout latest master
2. Run `ant all`
3. Clean database, data and osgi/state if necessary.
4. Start the portal.
5. Go to the `item-selector/item-selector-test` and run `gw testIntegration`.
6. Checkout your PR; make sure to rebase it on top of master.
7. Deploy the affected module, `item-selector-impl`
8. Go again to item-selector-test, run `gw testIntegration`.

**Comment by liuxingye** [comment]
Hi @adolfopa, thank you for providing such detailed steps, I got the same failure.

**Comment by rolandpakai** [comment]
Thank you @adolfopa 
Based on your detailed steps i was able to reproduce the failed test.

**Pull request closed without merging**
