### PR TITLE
LPS-195866, LPS-195769 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://liferay.atlassian.net/browse/LPS-195866
https://liferay.atlassian.net/browse/LPS-195769

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:help

**Comment by Jeremy-Ch** [comment]
ci:test:online-editing

**Comment by Jeremy-Ch** [comment]
ci:forward

**Pull request closed without merging**
