### PR TITLE
LPS-122845 | Master only

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-122845

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
Hi @austinchiang , I will take care of this pull request and resend it.

**Comment by Jeremy-Ch** [comment]
ci:stop

**Comment by Jeremy-Ch** [comment]
Hi @austinchiang In order not to affect other tests. I have updated the variable for the tests and macro and I will improve the macro in another [ticket](https://issues.liferay.com/browse/LRQA-63733), the goal is to distinguish between image and video. for this pull request, I have resent it, please see #1217.

**Pull request closed without merging**
