### PR TITLE
LPS-194601 use the get to prevent the NPE and return the expected error

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-194601

- LPS-194601 create get MBCategory
- LPS-194601 buildService
- LPS-194601 baseline
- LPS-194601 use the get to prevent the NPE and return the expected error

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
The test failures :
MessageBoardSectionResourceTest. testGraphQLPostSiteMessageBoardSection
MessageBoardSectionResourceTest. testPatchMessageBoardSection
MessageBoardSectionResourceTest. testPostMessageBoardSectionMessageBoardSection
MessageBoardSectionResourceTest. testPostSiteMessageBoardSection
MessageBoardSectionResourceTest. testPutMessageBoardSection

Are not related with this changes.
I see that was failing and I created : https://liferay.atlassian.net/browse/LPS-194898 but investigation is needed

**Review by adolfopa — APPROVED** [review]

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
Hi @AliciaGarciaGarcia The test [service-builder-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2419422373?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2419393807%26testrayRunId%3D2419419828%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) can not be passed with pull request. According to the information in the console of the test. I'm not sure if it needs to do a regen or something else. Could you help to take a look? Thanks.
```
] diff --git a/modules/apps/message-boards/message-boards-service/src/main/java/com/liferay/message/boards/service/http/MBCategoryServiceHttp.java b/modules/apps/message-boards/message-boards-service/src/main/java/com/liferay/message/boards/service/http/MBCategoryServiceHttp.java
     [echo] index 2a5c5cf10e841..28792e4f2d911 100644
     [echo] --- a/modules/apps/message-boards/message-boards-service/src/main/java/com/liferay/message/boards/service/http/MBCategoryServiceHttp.java
     [echo] +++ b/modules/apps/message-boards/message-boards-service/src/main/java/com/liferay/message/boards/service/http/MBCategoryServiceHttp.java
     [echo] @@ -250,53 +250,13 @@ public class MBCategoryServiceHttp {
     [echo]  		}
     [echo]  	}
     [echo]  
     [echo] -	public static com.liferay.message.boards.model.MBCategory getMBCategory(
     [echo] -			HttpPrincipal httpPrincipal, long groupId, String friendlyURL)
     [echo] -		throws com.liferay.portal.kernel.exception.PortalException {
     [echo] -
     [echo] -		try {
     [echo] -			MethodKey methodKey = new MethodKey(
     [echo] -				MBCategoryServiceUtil.class, "getMBCategory",
     [echo] -				_getMBCategoryParameterTypes5);
     [echo] -
     [echo] -			MethodHandler methodHandler = new MethodHandler(
     [echo] -				methodKey, groupId, friendlyURL);
     [echo] -
     [echo] -			Object returnObj = null;
     [echo] -
     [echo] -			try {
     [echo] -				returnObj = TunnelUtil.invoke(httpPrincipal, methodHandler);
     [echo] -			}
     [echo] -			catch (Exception exception) {
     [echo] -				if (exception instanceof
     [echo] -						com.liferay.portal.kernel.exception.PortalException) {
     [echo] -
     [echo] -					throw (com.liferay.portal.kernel.exception.PortalException)
     [echo] -						exception;
     [echo] -				}
     [echo] -
     [echo] -				throw new com.liferay.portal.kernel.exception.SystemException(
     [echo] -					exception);
     [echo] -			}
     [echo] -
     [echo] -			return (com.liferay.message.boards.model.MBCategory)returnObj;
     [echo] -		}
     [echo] -		catch (com.liferay.portal.kernel.exception.SystemException
     [echo] -					systemException) {
     [echo] -
     [echo] -			_log.error(systemException, systemException);
     [echo] -
     [echo] -			throw systemException;
     [echo] -		}
     [echo] -	}
     [echo] -
     [echo]  	public static java.util.List<com.liferay.message.boards.model.MBCategory>
     [echo]  		getCategories(HttpPrincipal httpPrincipal, long groupId) {
     [echo]  
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategories",
     [echo] -				_getCategoriesParameterTypes6);
     [echo] +				_getCategoriesParameterTypes5);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(methodKey, groupId);
     [echo]  
     [echo] @@ -328,7 +288,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategories",
     [echo] -				_getCategoriesParameterTypes7);
     [echo] +				_getCategoriesParameterTypes6);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, status);
     [echo] @@ -363,7 +323,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategories",
     [echo] -				_getCategoriesParameterTypes8);
     [echo] +				_getCategoriesParameterTypes7);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, parentCategoryId, start, end);
     [echo] @@ -398,7 +358,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategories",
     [echo] -				_getCategoriesParameterTypes9);
     [echo] +				_getCategoriesParameterTypes8);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, parentCategoryId, status, start, end);
     [echo] @@ -433,7 +393,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategories",
     [echo] -				_getCategoriesParameterTypes10);
     [echo] +				_getCategoriesParameterTypes9);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, excludedCategoryId, parentCategoryId,
     [echo] @@ -473,7 +433,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategories",
     [echo] -				_getCategoriesParameterTypes11);
     [echo] +				_getCategoriesParameterTypes10);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, parentCategoryId, queryDefinition);
     [echo] @@ -515,7 +475,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategories",
     [echo] -				_getCategoriesParameterTypes12);
     [echo] +				_getCategoriesParameterTypes11);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, parentCategoryIds, start, end);
     [echo] @@ -550,7 +510,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategories",
     [echo] -				_getCategoriesParameterTypes13);
     [echo] +				_getCategoriesParameterTypes12);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, parentCategoryIds, status, start, end);
     [echo] @@ -586,7 +546,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategories",
     [echo] -				_getCategoriesParameterTypes14);
     [echo] +				_getCategoriesParameterTypes13);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, excludedCategoryIds, parentCategoryIds,
     [echo] @@ -620,7 +580,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesAndThreads",
     [echo] -				_getCategoriesAndThreadsParameterTypes15);
     [echo] +				_getCategoriesAndThreadsParameterTypes14);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, categoryId);
     [echo] @@ -653,7 +613,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesAndThreads",
     [echo] -				_getCategoriesAndThreadsParameterTypes16);
     [echo] +				_getCategoriesAndThreadsParameterTypes15);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, categoryId, status);
     [echo] @@ -686,7 +646,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesAndThreads",
     [echo] -				_getCategoriesAndThreadsParameterTypes17);
     [echo] +				_getCategoriesAndThreadsParameterTypes16);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, categoryId, status, start, end);
     [echo] @@ -720,7 +680,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesAndThreads",
     [echo] -				_getCategoriesAndThreadsParameterTypes18);
     [echo] +				_getCategoriesAndThreadsParameterTypes17);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, categoryId, status, start, end,
     [echo] @@ -756,7 +716,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesAndThreads",
     [echo] -				_getCategoriesAndThreadsParameterTypes19);
     [echo] +				_getCategoriesAndThreadsParameterTypes18);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, categoryId, queryDefinition);
     [echo] @@ -795,7 +755,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesAndThreadsCount",
     [echo] -				_getCategoriesAndThreadsCountParameterTypes20);
     [echo] +				_getCategoriesAndThreadsCountParameterTypes19);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, categoryId);
     [echo] @@ -828,7 +788,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesAndThreadsCount",
     [echo] -				_getCategoriesAndThreadsCountParameterTypes21);
     [echo] +				_getCategoriesAndThreadsCountParameterTypes20);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, categoryId, status);
     [echo] @@ -863,7 +823,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesAndThreadsCount",
     [echo] -				_getCategoriesAndThreadsCountParameterTypes22);
     [echo] +				_getCategoriesAndThreadsCountParameterTypes21);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, categoryId, queryDefinition);
     [echo] @@ -902,7 +862,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesCount",
     [echo] -				_getCategoriesCountParameterTypes23);
     [echo] +				_getCategoriesCountParameterTypes22);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, parentCategoryId);
     [echo] @@ -935,7 +895,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesCount",
     [echo] -				_getCategoriesCountParameterTypes24);
     [echo] +				_getCategoriesCountParameterTypes23);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, parentCategoryId, status);
     [echo] @@ -968,7 +928,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesCount",
     [echo] -				_getCategoriesCountParameterTypes25);
     [echo] +				_getCategoriesCountParameterTypes24);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, excludedCategoryId, parentCategoryId,
     [echo] @@ -1004,7 +964,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesCount",
     [echo] -				_getCategoriesCountParameterTypes26);
     [echo] +				_getCategoriesCountParameterTypes25);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, parentCategoryId, queryDefinition);
     [echo] @@ -1043,7 +1003,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesCount",
     [echo] -				_getCategoriesCountParameterTypes27);
     [echo] +				_getCategoriesCountParameterTypes26);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, parentCategoryIds);
     [echo] @@ -1076,7 +1036,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesCount",
     [echo] -				_getCategoriesCountParameterTypes28);
     [echo] +				_getCategoriesCountParameterTypes27);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, parentCategoryIds, status);
     [echo] @@ -1109,7 +1069,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoriesCount",
     [echo] -				_getCategoriesCountParameterTypes29);
     [echo] +				_getCategoriesCountParameterTypes28);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, excludedCategoryIds, parentCategoryIds,
     [echo] @@ -1143,7 +1103,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategory",
     [echo] -				_getCategoryParameterTypes30);
     [echo] +				_getCategoryParameterTypes29);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, categoryId);
     [echo] @@ -1182,7 +1142,7 @@ public class MBCategoryServiceHttp {
     [echo]  		try {
     [echo]  			MethodKey methodKey = new MethodKey(
     [echo]  				MBCategoryServiceUtil.class, "getCategoryIds",
     [echo] -				_getCategoryIdsParameterTypes31);
     [echo] +				_getCategoryIdsParameterTypes30);
     [echo]  
     [echo]  			MethodHandler methodHandler = new MethodHandler(
     [echo]  				methodKey, groupId, categoryId);
     [echo] @@ -1208,6 +1168,46 @@ public class MBCategoryServiceHttp {
     [echo]  		}
     [echo]  	}
     [echo]  
     [echo] +	public static com.liferay.message.boards.model.MBCategory getMBCategory(
     [echo] +			HttpPrincipal httpPrincipal, long groupId, String friendlyURL)
     [echo] +		throws com.liferay.portal.kernel.exception.PortalException {
     [echo] +
     [echo] +		try {
     [echo] +			MethodKey methodKey = new MethodKey(
     [echo] +				MBCategoryServiceUtil.class, "getMBCategory",
     [echo] +				_getMBCategoryParameterTypes31);
     [echo] +
     [echo] +			MethodHandler methodHandler = new MethodHandler(
     [echo] +				methodKey, groupId, friendlyURL);
     [echo] +
     [echo] +			Object returnObj = null;
     [echo] +
     [echo] +			try {
     [echo] +				returnObj = TunnelUtil.invoke(httpPrincipal, methodHandler);
     [echo] +			}
     [echo] +			catch (Exception exception) {
     [echo] +				if (exception instanceof
     [echo] +						com.liferay.portal.kernel.exception.PortalException) {
     [echo] +
     [echo] +					throw (com.liferay.portal.kernel.exception.PortalException)
     [echo] +						exception;
     [echo] +				}
     [echo] +
     [echo] +				throw new com.liferay.portal.kernel.exception.SystemException(
     [echo] +					exception);
     [echo] +			}
     [echo] +
     [echo] +			return (com.liferay.message.boards.model.MBCategory)returnObj;
     [echo] +		}
     [echo] +		catch (com.liferay.portal.kernel.exception.SystemException
     [echo] +					systemException) {
     [echo] +
     [echo] +			_log.error(systemException, systemException);
     [echo] +
     [echo] +			throw systemException;
     [echo] +		}
     [echo] +	}
     [echo] +
```

/cc @adolfopa

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
