### PR TITLE
LPS-124817 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @boton, things you must check: 

1. Do not forward second commit [TEST](https://github.com/liferay-lima/liferay-portal/pull/1430/commits/bcfc41f7672019a9194e1b823b6b4825f48bb124), as it says is only for testing and must be forwarded after all this and under https://issues.liferay.com/browse/LPS-125413
2. Check why listeners are not removed properly on the `onMouseUp` event
3. Drags the image to fast... please compare with the old component and try to reduce it. It probably need changes in the `onMouseMove` function
4. `onMouseMove` may need a debounce function

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
This was my old version with hooks: 

```
const CoverCropperImage = ({direction, imageSrc, portletNamespace}) => {
	const [position, setPosition] = useState({x: 0, y: 0});
	const [dragging, setDragging] = useState(false);
	const [rel, setRel] = useState(null);
	const ref = useRef(null);

	const vertical = direction === 'vertical';

	// calculate relative position to the mouse and set dragging=true

	const onMouseDown = (event) => {
		console.log('onMouseDown');

		// only left mouse button
		if (event.button !== 0) {
			return;
		}

		const pos = event.currentTarget.getBoundingClientRect();

		setDragging(true);

		setRel({
			x: event.pageX - pos.left,
			y: event.pageY - pos.top,
		});

		console.log('rel', {
			x: event.pageX - pos.left,
			y: event.pageY - pos.top,
		});
		event.stopPropagation();
		event.preventDefault();
	};

	const onMouseMove = (event) => {
			if (!dragging) {
				return;
			}

			setPosition({
				x: vertical ? position.x : event.pageX - rel.x,
				y: vertical ? event.pageY - rel.y : position.y,
			});

			console.log('position', {
				x: vertical ? position.x : event.pageX - rel.x,
				y: vertical ? event.pageY - rel.y : position.y,
			});

			event.stopPropagation();
			event.preventDefault();
		};

	const onMouseUp = (event) => {
		console.log('onMouseUp');
		setDragging(false);
		event.stopPropagation();
		event.preventDefault();

		console.log(position);

	};

	// When the element mounts, attach an mousedown listener
	useEffect(() => {
		ref.current.addEventListener('mousedown', onMouseDown);

		return () => {
			ref.current.removeEventListener('mousedown', onMouseDown);
		};
	}, [ref.current]);

	useEffect(() => {
		if (dragging) {
			document.addEventListener('mousemove', onMouseMove);
			document.addEventListener('mouseup', onMouseUp);
		}
		else if (!dragging) {
			console.log('removeListeners!');
			document.removeEventListener('mousemove', onMouseMove);
			document.removeEventListener('mouseup', onMouseUp);
		}

		return () => {
			document.removeEventListener("mouseup", onMouseUp);
			document.removeEventListener("mousemove", onMouseMove);
		};
	}, [dragging]);

	return (
		<div className="image-wrapper">
			<img
				alt={Liferay.Language.get('current-image')}
				className="current-image"
				id={`${portletNamespace}image`}
				ref={ref}
				src={imageSrc}
				style={{
					left: position.x,
					position: 'relative',
					top: position.y,
				}}
			/>
		</div>
	);
};
```

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
ci:close

**Comment by carloslancha** [comment]
Continues in https://github.com/liferay-lima/liferay-portal/pull/1449

**Pull request closed without merging**
