### PR TITLE
LPS-186343 Redirect to 404 page instead of throwing error, this preve…

### PR DESCRIPTION
**Pull request by SamZiemer**
https://liferay.atlassian.net/browse/LPS-186343

This change prevents transactions from being canceled when an adaptive media image does not exist but needs to be generated.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:reevaluate:1407401_3839

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
It looks good to me!

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Pull request closed without merging**
