### PR TITLE
LPS-122378 Do not confuse part of the host name with extension

### PR DESCRIPTION
**Pull request by IstvanD**
Dear @liferay-lima 

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
I tested poorly but looks good to me.

image


Nice catch @IstvanD thanks!

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
