### PR TITLE
LPS-113751 Add Blogs Aggregator to list of view portlets

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
The [test failure](https://github.com/liferay-lima/liferay-portal/pull/2788#issuecomment-1058036059) seems related
image
but testing on the portal works fine.

**Comment by adolfopa** [comment]
ci:reevaluate:1317401_2413

**Comment by boton** [comment]
ci:reevaluate:1317401_2413

**Comment by Hanlf** [comment]
Hi @adolfopa 
The failure of BlogsWidget#CanViewBlogWithFutureDisplayDateViaBlogsAggregator is a test fix, sent fix under https://github.com/liferay-lima/liferay-portal/pull/2791

cc/ @AliciaGarciaGarcia @boton

**Pull request closed without merging**
