### PR TITLE
[TS] LPS-130028 | Figure and figcaption tags are stripped in blogs.

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPP-40807
https://issues.liferay.com/browse/LPS-107732

Hi @liferay-lima,

Currently figure and figcaption tags, which were [added as a part of HTML5](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure) to help provide further native support for sectioning context, are not permitted in blogs posts as they are not a part of the allowedContent in our content contributor. This PR adds them to this permitted list.

Please let me know if you have any questions or concerns about this. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
SF failure isn't relevant, it's in build.properties:
```
     [java] 1: ./build.properties expected:<...ut,\
     [java]     #    apps/l[earn-taglib,\
     [java]     #    apps/l]icense-manager,\
     [java]    ...> but was:<...ut,\
     [java]     #    apps/l[]icense-manager,\
     [java]    ...>
     [java] 
     [java] 	at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:454)
     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:299)
```

Can also be seen failing in other pulls, e.g. https://test-1-4.liferay.com/job/test-portal-source-format/4546/

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
