### PR TITLE
LPS-133035 workflow

### PR DESCRIPTION
**Pull request by nhpatt**
Hi Lima! 👋 

Can you review https://github.com/liferay-lima/liferay-portal/pull/1894/commits/7e59a809767f5cc527958b7db9cae702bffccb5a ?

> LPS-133035 allow rankings in asset renderer factories. Right now depot picks the first one registered to a className and assigns the wrapper the MAX priority. If a later bundle tries to override the first component with one of higher priority it loses because OSGi, in a case of a draw, picks the one with the lower id. The pattern of MAX_VALUE - 1000 is used several times in the portal.

Maybe there is an easier way of doing this. We also want to change what the `AssetRenderer` displays for MBMessages but in the near future.

I do not know how urgent is this, if it has to be merged *before* Monday or Monday is Ok. It's the last thing Edu wants to change for Liferay Online.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by nhpatt** [comment]
@adolfopa I have the CI working here: https://github.com/liferay-frontend/liferay-portal/pull/1135 

Damn, a new conflict 😓

**Comment by nhpatt** [comment]
-- rebased

**Comment by nhpatt** [comment]
I guess that there are no issues :P

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:close

**Pull request closed without merging**
