### PR TITLE
LPS-161376 Add mimeTypeRestriction support to item-selector-upload-web

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
### Issue: https://issues.liferay.com/browse/LPS-161376

- LPS-161376 modify the creator of UploadItemSelectorCriterion adding a new param mimeTypeRestriction for some selector criterion
- LPS-161376 autoSF
- LPS-161376 baseline
- LPS-161376 KB attachment should have the ItemSelectorCriterionConstants.MIME_TYPE_RESTRICTION_IMAGE
- LPS-161376 the item selector upload view display context needs to make public the mimeTypeRestriction to be used by the react component

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@boton 
look if this works for you

I do not know if should be a draft or not. tellme tomorrow

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1377401_4490

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_4490

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
Looks good. I'm gonna check on Monday over #3409 and I think we can forward it if works fine.

**Review by boton — APPROVED** [review]
LGTM.

Rebased and added mimeTypeRestriction to Wiki 2e053fe66230b0f71380997f7669fb3f8d7fae98.

Tested on KB and Wiki on top of https://github.com/liferay-lima/liferay-portal/pull/3409 and working.
image
image

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
