### PR TITLE
LPS-167472 KB List view: remove extra info

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-167472 

**BEFORE:** 
Screenshot 2022-11-16 at 15 10 59

**AFTER:**
Screenshot 2022-11-23 at 13 53 20

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1347401_3185

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by boton — CHANGES_REQUESTED** [review]
Opened a conversation with design about `child articles` counter removal.

**Comment by marcogalluzzi** [comment]
> Opened a conversation with design about `child articles` counter removal.

Yes @boton this also look strange to me.

**Review by marcogalluzzi — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
Only passing here for asking a question: 

if the FF of vertical menu is not active, There is a way to go to the Child articles?

**Comment by adolfopa** [comment]
@ambrinchaudhary You cannot send this as is until we remove the feature flag for the navigation pane. Otherwise there will be no way to navigate to children articles.

**Comment by ambrinchaudhary** [comment]
After discussing with UX, we will move the child articles link to the info panel. Anyway... when you preview the parent article you see the list to its child articles... so there is a way to access them.

**Comment by ambrinchaudhary** [comment]
I've updated the pull following what UX described in [LPS-167472](https://issues.liferay.com/browse/LPS-167472). Please @boton @adolfopa @AliciaGarciaGarcia review

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
Updated the pull. I leave thee child article's info in the list while the FF is not removed. 

**With FF enabled:** 

Screenshot 2022-11-17 at 11 30 53

**Without FF:**

Screenshot 2022-11-17 at 11 31 54

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]
I like it more the "no FF then show the Childs!"

**Comment by ambrinchaudhary** [comment]
On hold. @boton prefers to discuss it internally.

**Comment by ambrinchaudhary** [comment]
@boton I've updated the pull, please review.

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
