### PR TITLE
LPS-169910, LPS-169792 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-169910
https://issues.liferay.com/browse/LPS-169792

@austinchiang , according to https://issues.liferay.com/browse/LPS-167774, KB priority will not be used to define the display order and is deprecated, so I removed some KB priority tests.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by austinchiang** [comment]
@Hanlf  KB priorities are being removed but the feature (positioning KB articles) is still there. I think it might be a good idea to save the tests and adapt them once the new changes are in

**Pull request closed without merging**
