### PR TITLE
LPS-147289 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-147289

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:reevaluate:1317401_2585

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
