### PR TITLE
LPS-200359 No cache header for DM file download

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi all,

As you could seen this PR contains a breaking change.

Please check the commit message and https://liferay.atlassian.net/wiki/spaces/TEAMRM/pages/2488172545/2023.Q4+Quarterly+Release+Notes+Open+for+edition#Breaking-Changes.5 to see if I've made any mistake (or if you detect missing relevant information)

Thanks!!

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
Hey @adolfopa I've seen a SF error:

`optionLabels = {"private", "public", "no-cache"},
`
Should be 

`optionLabels = {"no-cache", "private", "public"},
`

Following the alphabetical order

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
@adolfopa I changed the order (alphabetical) and push this to master

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
