### PR TITLE
LPS-200359 breaking changes amend

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by adolfopa** [comment]
@robertoDiaz Can you take a look at this?

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Hi @robertoDiaz , please fix the SF issue. Thanks.

**Comment by robertoDiaz** [comment]
Hi @WYZ-Issac 

I'm not sure that this SF error is related with my changes.

I've just modified the readme/BREAKING_CHANGES_AMENDMENTS.markdown and there's no reference to it.

In my local ant format-source-current-branch didn't modify it.

**Comment by qz1010** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:stop

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
Hi @robertoDiaz, after checking your commit. The SF error is not a known issue. It's about your commit message. There is an extra space at the beginning of your commit message. This is what causes this error. Please fix it and resend it. Thanks.

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:stop

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
