### PR TITLE
LPS-114056 - Apply the use of clay content taglib in site-item-selector-web

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
See https://github.com/marcoscv-work/liferay-portal/pull/336

**Pull request closed without merging**
