### PR TITLE
[TS] LPS-121583

### PR DESCRIPTION
**Pull request by jonathanmccann**
I followed the ordering of other assets with folders (DL, Bookmarks) but if it's better to have it in alphabetical order I can move it around. Please let me know if there are any questions or concerns about the changes.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
