### PR TITLE
LPS-180435 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-180435

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@Hanlf please add to test map, thx

**Review by austinchiang — APPROVED** [review]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
