### PR TITLE
LPS-117349 Details in Ratings

### PR DESCRIPTION
**Pull request by boton**
- [x] Review that all the titles have tooltip components and not only the native title.
- [x] Review the space thumbs between buttons
- [x] Avoid the focus on click in animated ratings
- [x] Fix for LPS-114508 is reopen by focus
- [x] Fix chrome bug triggered by recent layouts changes

### CODE REVIEW

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
