### PR TITLE
LPS-148815 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-148815

### CODE REVIEW

**Comment by austinchiang** [comment]
cc @manoelcyreno

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by manoelcyreno** [comment]
cc: @magjed4289

**Comment by magjed4289** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
