### PR TITLE
LPS-199272 Handle the I18nPath if necessary

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1397401_8249

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
checking

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
