### PR TITLE
LPS-189867 Do not Use the download return type for image field

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
Hi @robertoDiaz, I found two test failed caused by your commit: [LocalFile.ContentPagesWithContentsPanel#EditDisplayedDocument](https://testray.liferay.com/zh/home/-/testray/case_results/2374010272?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2374006340%26testrayRunId%3D2374006671%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[LocalFile.ContentPagesWithContentsPanel#ResizeDisplayedImageViaImageEditor](https://testray.liferay.com/zh/home/-/testray/case_results/2374011175?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2374006340%26testrayRunId%3D2374006671%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
The page content disappear when we access to the document editor via Page Content panel. Is this the expected result？If not please fix this issue. Thanks.

**Steps to reproduce:**
1. Add a site
2. Add a content page
3. Add an Image fragment to the content page
4. Directly select an image in the editable field
5. Click the page content button on the sidebar

You will find info "There is no content on this page".
image

**Comment by robertoDiaz** [comment]
Hi @WYZ-Issac 

I've rollback this changes and retest and the result is the same:

Captura de pantalla 2023-07-10 a las 9 05 16

Anyway, just to let you know, the error itself doesn't make sense to me because the only thing I'm changing is how the link is been returned and I do not touch nothing related with page content framework, just the link generation.

**Comment by WYZ-Issac** [comment]
Hi @robertoDiaz, I will check this issue to find the root cause because the test did only fail just in your PR. If it's unrelated to yours, I will forward this PR directly.

**Comment by robertoDiaz** [comment]
It's weird, because, as said, following the steps, if I understand it well the page content should not show "theres no content on this page", but I also see this message without my changes.

Thank you for your help.

**Comment by WYZ-Issac** [comment]
The failure was caused by this bug: https://liferay.atlassian.net/browse/LPS-190185. I will forward this PR directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
