### PR TITLE
LPS-199524 Add Flags web notifications

### PR DESCRIPTION
**Pull request by robertoDiaz**
This code had pass the review here: https://github.com/liferay-lima/liferay-portal/pull/4821

Anyway brian didn't merge it due: https://github.com/brianchandotcom/liferay-portal/pull/142669#issuecomment-1777753769:

> Inappropriate Content Flagged in {0}.
> is not a title or a sentence. Please resend. Thx.

I asked him and he told me this:

> It needs to be a sentence or a title.
> This is a Title
> This is a sentence.

So i've removed the dot in [this commit](https://github.com/liferay-lima/liferay-portal/pull/4830/commits/18a4236fcd2f3fb572156046a7498c076e183c4b). Now (as I understand)  it fits with the "title definition" explained by him.

Can you confirm that in the team review?

Thx!

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]
LGTM!

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
Hey @marcogalluzzi did you double check the title as explained in  https://github.com/liferay-lima/liferay-portal/pull/4830#issue-1961085336

Thanks!

**Comment by marcogalluzzi** [comment]
> Hey @marcogalluzzi did you double check the title as explained in [#4830 (comment)](https://github.com/liferay-lima/liferay-portal/pull/4830#issue-1961085336)
> 
> Thanks!

Yes, that's what I basically reviewed. I think now it's a correct title (following bchan rules)

**Comment by robertoDiaz** [comment]
> I think now it's a correct title 

Thanks! 👍

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Failures are unrelated.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
