### PR TITLE
LPS-153700 Preserve query string and avoid unnecessary redirections

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
LGTM but maybe [LocalFile.DisplayPageTemplatesForWebContentArticle#NavigateToDisplayPageTemplateViaFriendlyURL](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/21785//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DisplayPageTemplatesForWebContentArticle_NavigateToDisplayPageTemplateViaFriendlyURL_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-05/test-1-35/test-portal-acceptance-pullrequest(master)/1593/functional-tomcat90-mysql57-jdk8/4/23/LocalFile.DisplayPageTemplatesForWebContentArticle_NavigateToDisplayPageTemplateViaFriendlyURL/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-05/test-1-35/test-portal-acceptance-pullrequest(master)/1593/functional-tomcat90-mysql57-jdk8/4/23/LocalFile.DisplayPageTemplatesForWebContentArticle_NavigateToDisplayPageTemplateViaFriendlyURL/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-05/test-1-35/test-portal-acceptance-pullrequest(master)/1593/functional-tomcat90-mysql57-jdk8/4/23/jenkins-console.txt.gz) is from this PR

relauching relevant test

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:reevaluate:1357401_1616

**Comment by Hanlf** [comment]
The failure is related to this PR, checking locally..

**Comment by Hanlf** [comment]
@adolfopa 
There is a regression caused by this PR, could you take a look, thanks!
# Add a display page template for Web Content Article and Basic Web Content
# Add a web content and select the above display page template
# Navigate to "http://localhost:8080/w/${web content title}", it works as expected.
# Navigate to "http://localhost:8080/-/${web content title}", it doesn't work now
reproduced

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_2381

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
