### PR TITLE
LPS-180085 Recent Bloggers portlet throws unknown column name 'blogsEntryUserId' in 'on' clause

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
If the Recent Bloggers portlet is configured to show blog entries of users belonging to an organization, `BlogsStatsUserLocalServiceImpl` will generate a syntactically incorrect query, with these errors:

- column alias is used in the ON clause, `_userIdAlias`
- refers to a column in the WHERE clause that is neither in SELECT nor in the ON clause, `Users_OrgsTable.INSTANCE.organizationId`
 
Proposed Solution
========

- using the original name of the `userId` column
- testing for `Users_OrgsTable.INSTANCE.organizationId` in the ON clause

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://issues.liferay.com/browse/LPS-180085

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@IstvanD Can you write a test to verify that the query is valid?

**Comment by IstvanD** [comment]
Hi @adolfopa I added the test.

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above Poshi test failure is a flaky issue, it can pass locally.

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
