### PR TITLE
LPS-118826 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:blogs

**Comment by ambrinchaudhary** [comment]
ci:test:blogs

**Comment by ambrinchaudhary** [comment]
Dinamic `required` validations are not working. I mean: it should be possible to save the blog entry as draft without the title. 
this was captured before the click: 

```
saveButton.before(
	STR_CLICK,
	A.bind('_beforeSaveBtnClick', instance)
),
```

now it is triggered on the "on" click event, and the rule is added but at the same time that the "validate()" function runs, and must be added before to work. 

Would you mind having a look into this @boton?

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
See #1270.

**Pull request closed without merging**
