### PR TITLE
LPS-122267 creation of the methods on the superior layers of the service with the addFileEntry, and the modification of the methods on the repository files

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-122267 Manage review dates for documents

On this PR 3rd of the serie of several to change the structure and way we save the file Entries with 2 new parameters ( expirationDate and reviewDate) we go up on the layers of the services, propagating the changes from the tables to the DL.

This PR changes to the methods of the repositories, in this case changing the methods that @liferay-headless created not long ago. This movement is suggested  by the changes made by them. (thats the point I named @javierdearcos to review this PR, but I can not assign it to him too :( )

On the last 2 commits, I deleted the methods of the services that will not be called anymore, cause there was recently created and do not give nothing in particular to the files. If we decided not to do it, we can omit them!

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @javierdearcos

The last 2 commits delete the methods that you recently created.

Can you please take a look at it and tell me if I can do it or you prefer only the deprecation?


Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
> Hi @javierdearcos
> 
> The last 2 commits delete the methods that you recently created.
> 
> Can you please take a look at it and tell me if I can do it or you prefer only the deprecation?
> 
> Thanks!

Hello @AliciaGarciaGarcia 🙂 

It looks perfect to me and better to clean code, now that we have time and we are not making a breaking change. 

Thanks for taking care of this!

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
The test failing (ViewImageWithMetaTags ) is caused by my changes. 
I will fix it and resend the pr

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1257401_135

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1257401_149

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
