### PR TITLE
LPS-135449 Disable map content button when the selected value is already mapped

### PR DESCRIPTION
**Pull request by boton**
**Bug:** https://issues.liferay.com/browse/LPS-135449

This PR Disable map content button when the selected value is already mapped

Note that only have an `initialField` value when is called by `MappingSelector.js`

---

**Enable the feature flag**
```sh
cd ${LF_PORTAL_PATH} && echo "enabled=B\"true\"" > ../bundles/osgi/configs/com.liferay.layout.seo.web.internal.configuration.FFSEOInlineFieldMapping.config
```

**Before this PR**
image

**After this PR**
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
