### PR TITLE
LPS-135892 Update CXF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Only one thing (if all passes...)

maybe is needed to run the `ant build-lib-versions` to update the xml/html files ?

**Comment by Hanlf** [comment]
- The SF issue should not be related to this PR. will re-run it.

- com.liferay.portal.remote.soap.extender.test.JaxWsComponentHandlerRegistrationTest.testHandlerIsRegistered is not related to this PR, see [LRQA-68066](https://issues.liferay.com/browse/LRQA-68066).

- The rest of the three failures only occur on this PR, will re-run to verify them.

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia updated. If you're ok with this, can you do the forward?

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1257401_3210

**Comment by AliciaGarciaGarcia** [comment]
seems that java.lang.NoClassDefFoundError: com/sun/xml/txw2/TypedXmlWriter error is a known issue : https://issues.liferay.com/browse/LRQA-67175

Other is our old friend about max_allowed_packet

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
the SF failing It's not related with this PR...
😫 

@austinchiang or @Hanlf can you push it a little, 


thanks!!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
