### PR TITLE
LPD-15202 Change FF number from LPS-196648 to LPD-10793

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Due to Jira migration from LPS to LPD, ids for Epics have changed.

### CODE REVIEW

**Review by marcogalluzzi — COMMENTED** [review]
Changes look good. Was it necessary to change the FF number?

**Comment by ambrinchaudhary** [comment]
Changes look good. Was it necessary to change the FF number?
Yes, we discussed it yesterday in slack, see [LPS vs LPD numbers]. If not, if you want to test epic https://liferay.atlassian.net/browse/LPD-10793 you don't know which FF is, as there is no connection with the previous one. 

Thank you for reviewing

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1327401_3470

**Comment by ambrinchaudhary** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
