### PR TITLE
LPS-160883, LPS-160761 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-160883
https://issues.liferay.com/browse/LPS-160761

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:notifications

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:reevaluate:1377401_4263

**Comment by austinchiang** [comment]
Sent in https://github.com/brianchandotcom/liferay-portal/pull/121867

**Pull request closed without merging**
