### PR TITLE
LPS-190580 Add the new column displayDate to KBArticle table

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-190580 add the column displayDate on the table KBArticle to allow users to Schedule a Knowledge Base Article
- LPS-190580 buildService
- LPS-190580 upgrade process to add the new column and fill it with the creation date because last publish date can be null
- LPS-190580 semver
- LPS-190580 set provisionally the display date to the creation

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
https://liferay.atlassian.net/browse/LPS-190440 was causing a bunch of tests to fail. The fix was merged 7 hrs ago so I think it's best we rerun the tests again

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by austinchiang** [comment]
Test failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
