### PR TITLE
Lps 186953 2

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-186953

Resending based on Brian Chan's comments from https://github.com/brianchandotcom/liferay-portal/pull/136200#issuecomment-1588544718 and conversation here https://liferay.slack.com/archives/C01FP01V5L0/p1686665130822089

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
