### PR TITLE
LPS-135864 translation move export from modal to jsp

### PR DESCRIPTION
**Pull request by boton**
In this PR the export translation modal is moved into a new JSP and the `experience selector` is added behind a feature flag.

If the FF `com.liferay.translation.web.internal.configuration.FFLayoutExperienceSelectorConfiguration` is enabled and the content page have more than the default experience `experience selector` is rendered.

image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
I'm ok with this PR. See https://github.com/liferay-lima/liferay-portal/pull/2295 for the same changes with some additional commit reengineering. Once that's approved I'll close this one.

**Pull request closed without merging**
