### PR TITLE
LPS-201887 Check if sharing configuration is enabled

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-201887

Steps to reproduce:
Go to System settings> Sharing
Disable the sharing from the system scope> Save
Go to DM
See any document actions list

Expected Results:
The Sharing option should not be displayed after disabling

The error of:
Go to the “VIRTUAL INSTANCE SCOPE” under the “SYSTEM SCOPE“
Click Sharing
An error is displayed “Error: The entry could not be found.“ (This happens when the system is not slow enough to reload the configuration, but the code as far I saw is correct ( on SharingConfigurationFactoryImpl) if persist create another bug)
Go back to System settings> Sharing
The VIRTUAL INSTANCE SCOPE is missing (It will reappear after resetting default values)

- LPS-201887 check if sharing is enabled

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
