### PR TITLE
LPS-201827 sharing invite to collaborate icon

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-201827 

New icon only for Invite to Collaborate option. 
Screenshot 2023-11-16 at 10 21 38

Other Share icon keeps as before:
Screenshot 2023-11-16 at 10 22 28

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
Failures are unrelated.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
