### PR TITLE
LPS-128719, LPS-128718, LPS-128716 | Master only

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-128719
https://issues.liferay.com/browse/LPS-128718
https://issues.liferay.com/browse/LPS-128716

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
@austinchiang there are some SF issues, I will resend this pull.

**Comment by Hanlf** [comment]
Weird, the wrong commits didn't come from my pull and SF passed on my pull: https://github.com/austinchiang/liferay-portal/pull/979
Anyway, I resend it here and it forwarded: https://github.com/liferay-lima/liferay-portal/pull/1629.

**Pull request closed without merging**
