### PR TITLE
LPS-154515 As a documents manager I want to set permissions from folders to folders at creation time

### PR DESCRIPTION
**Pull request by tototrinh**
Hi team,
Please help review this PR and give your feedback.
cc: @hhtank @locpham97 @ces-quanhuynh @ces-luannguyen

# Motivation
[LPS-154515](https://liferay.atlassian.net/browse/LPS-154515) As a documents manager I want to set permissions from folders to folders at creation time

# Solution
Create a new entity `PermissionPropagationEntry` to map each _folderId_ with its propagation settings.
Also, add the logic that makes the new subfolder permissions follow these rules:
- When creating a new subfolder in a folder, the subfolder will inherit the permissions of the first parent folder ordered by proximity that has the permissions propagation setting set to TRUE.
- If there are no parent folders that have the permissions propagation setting set to TRUE, then the subfolder will have the default permissions.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by tototrinh** [comment]
Hi @adolfopa, Thanks for your feedback. Could you please clarify what exactly you would like me to do?
Should I split this PR into 3 independent PRs and send them to the respective teams, or should I reorder the commits and create a PR with all the commits for the teams, while also mentioning the commits that each team will review?
Thanks.

**Comment by adolfopa** [comment]
@tototrinh It is always best to send multiple, smaller, PRs. I'd start with the services+upgrade (send 1 pr to core infra), and once that's merged, send another one with the configuration part (core infra as well), then the one with the taglib (frontend infra), and finally the DM changes to us.

Sending PRs incrementally like this will make the review process smoother and you'll receive feedback faster than with a giant PR.

**Comment by tototrinh** [comment]
Thank @adolfopa, I will close this PR.

**Pull request closed without merging**
