### PR TITLE
LPS-173780 Include only page/content available languages in sitemap

### PR DESCRIPTION
**Pull request by marcogalluzzi**
This pull request includes the work done at [this previous PR](https://github.com/liferay-lima/liferay-portal/pull/3944) by @adolfopa plus the following:
* Updated package version of portal-util
* Fixed integration tests

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
Hi @marcogalluzzi Could you help to solve the conflicts for this pr? Thanks.

**Comment by marcogalluzzi** [comment]
Rebased and solved conflicts with master. Thanks @Jeremy-Ch

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Pull request closed without merging**
