### PR TITLE
LPS-152803 If we don't have order by keys then don't show the sorting icon

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Usually if we don't set order keys we are saying that the list of items is not sorted and we should not show the sorting icon.

Primary_Status_Status_-_Liferay_DXP

[Link to the issue](https://issues.liferay.com/browse/LPS-152803)

Proposed Solution
----
Implement **getSortingURL()** method on **ItemSelectorViewDescriptorRendererManagementToolbarDisplayContext** since if it is null the sorting icon is not showed, in this case if we don't have order keys we should return a null.

How to test it
---
Step-by-Step:

1. Navigate to Navigation Menus admin on the default site
2. Add a navigation menu
3. Add a Vocabulary item

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci stuck?
stoping ci

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
