### PR TITLE
LPS-197820 make ammends to the new service module and table

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
This is a continuation of the story about the creation of the new module.
I changed the structure of the table adding the uuid, added default permissions and add the remote service

- LPS-197820 add default permissions
- LPS-197820 move constants to api
- LPS-197820 add to new service for saved content the remote service and the uuid
- LPS-197820 not needed
- LPS-197820 update table with uuid
- LPS-197820 buildService

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
@robertoDiaz can you take a look to the upgrade, thanks!

**Comment by robertoDiaz** [comment]
@AliciaGarciaGarcia upgrade LGTM 👍

**Comment by AliciaGarciaGarcia** [comment]
something fishy is happening with this pr.

checking it

**Comment by AliciaGarciaGarcia** [comment]
On the `release_` the `com.liferay.saved.content.service` servletContextName so we do not need the registry nor from 0.0.1 to 1.0.0 
and if we do it, the table is not generated

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa 

I added 2 important commits about the permissions.
can you recheck it.
Thanks!

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:stop

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
