### PR TITLE
LPS-161758 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-161758

### CODE REVIEW

**Comment by Hanlf** [comment]
@austinchiang Please review it with Jeremy's PR about the story [Set review date for knowledge base articles](https://issues.liferay.com/browse/LPS-161759), I used some new macros from that PR.
@Jeremy-Ch , Maybe you can combine my commits under your PR if you are ready, It will be easier for Austin to review.

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
See the new pull request: https://github.com/liferay-lima/liferay-portal/pull/4039

**Pull request closed without merging**
