### PR TITLE
LPS-153629 Get all categories while automatic draft saving request

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Previous pull https://github.com/liferay-lima/liferay-portal/pull/3055

> Hi @ambrinchaudhary,
> I reviewed your changes and this line:
> input[name=${this._config.namespace + name}]
> must contain the *.
> like this:
> input[name*=${this._config.namespace + name}]
> 
> I understand it can seem like it is unnecessary, but the name that we search looks something like this:
> '_com_liferay_blogs_web_portlet_BlogsAdminPortlet_assetCategoryIds_40437'
> the last part (40437) being the unique id of the vocabulary.
> I used the * to search
> '_com_liferay_blogs_web_portlet_BlogsAdminPortlet_assetCategoryIds
> This returns the required nodes regardless the id.
> 
> This method returns a collection. If the user chooses multiple categories that is how it needs to be forwarded to backend.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
cc/ @evibudai

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
The code looks good but I´m going to test it before forward

**Comment by boton** [comment]
Now it's working for me 🎉 

image

Thanks, @evibudai @ambrinchaudhary ❤️

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
