### PR TITLE
LPS-201796 check the schedule date and if scheduler is enabled

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-201796

Reproduce Steps:
- Enable feature flag
- Go to user account settings> Preferences> Display Settings
- Change the time zone to “UTC+7“
- Go to Kb admin 
- Add a kb article and set the scheduled date
- Scheduled

Schedule enabler : disable scheduler

'scheduler.enabled=false'
Start portal
no scheduled fields (schedule, review or expiration) should be shown

- LPS-201796 check if the display date (schedule date) is after the actual date and not null, if not throw new KBArticleDisplayDateException
- LPS-201796 show the schedule options only if PropsValues.SCHEDULER_ENABLED is enabled
- LPS-201796 buildLang

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1257401_4255

**Comment by WYZ-Issac** [comment]
Failures are unrelated.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
