### PR TITLE
LPS-114034 - Apply the use of clay content taglib in journal-content-asset-addon-entry-conversions

### PR DESCRIPTION
**Pull request by marcoscv-work**
@ambrinchaudhary @boton

As part of our effort to Improve HTML Layout Generation Strategies in DXP, here a PR about changing autofit-* and sheet-* for clay:sheet* and clay:content*

This "PR" updates markup with new taglibs. What we expect is to see the same visual design, so no visual changes are required.
The way to validate the changes is to see the same visual result. if is there any previously agreed difference it would be correctly pointed in comments

LPS-114015 - comment-taglib
LPS-114023 - journal-content-asset-addon-entry-conversions
LPS-114025 - file_entry_history
LPS-114033 - item-selector-url
LPS-114034 - journal-content

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
See https://github.com/marcoscv-work/liferay-portal/pull/333

**Pull request closed without merging**
