### PR TITLE
LPS-181099 catch Pattern Exception and show the error toast to the user

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-181099

Before the transformation from string to pattern was be doing on the listener, but now it's the command who take this responsability so we will check it on the command creating a new exception because there is no reason to throw a ConfigurationModelListenerException on the action command (but without deleting it from the listener)

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
resent due : https://github.com/brianchandotcom/liferay-portal/pull/133201#issuecomment-1506788008

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
