### PR TITLE
LPS-169909 Handle duplicate name exceptions in repository tag

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-169909

When trying to create a duplicate entry (document or folder) no error is displayed in the UI, and an exception is logged.

Handle the error in the backend and display an error message to the user.

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-169909.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
