### PR TITLE
LPS-182364 MBThread UAD deletion errors 

### PR DESCRIPTION
**Pull request by robertoDiaz**
🤞 

The original changes, with some fixes that should avoid the test errors.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:message-boards

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
Hi @robertoDiaz Could you help to resolve the conflicts for the PR? Thanks.

**Comment by AliciaGarciaGarcia** [comment]
hi @Jeremy-Ch 

@robertoDiaz is on PTO, I rebased and solve the conflicts on this PR but I have no permissions to push, so I will create a new one ONLY with rebase and conflicts and close this:

Thanks!!!

**Comment by AliciaGarciaGarcia** [comment]
see https://github.com/liferay-lima/liferay-portal/pull/4533

**Pull request closed without merging**
