### PR TITLE
LPS-157971 Use non ambiguous friendly urls for cross-group references

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by brianchandotcom** [comment]
@adolfopa merged to master

**Comment by AliciaGarciaGarcia** [comment]
see https://github.com/liferay-lima/liferay-portal/pull/3256#issuecomment-1184587602

**Pull request closed without merging**
