### PR TITLE
LPS-119641 Remove feature flag

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
@austinchiang Here I've removed the translations feature flag; there are some poshi tests referencing it, so I will not forward this.

Can you guys change the poshi tests and send everything together?

Thanks!

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/665

**Pull request closed without merging**
