### PR TITLE
LPS-136123 add test to check the deletion of the depot after the deletion of the company

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-136123

It seems that deleting the virtual instance it’s not deleting the elements of the asset library, nor the groups nor nothing.

related:https://issues.liferay.com/browse/LPS-136408

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@4lejandrito I have doubts about the correct folder of the tests...

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Pull request closed without merging**
