### PR TITLE
LPS-190783 Bulk copy of file entries, folders and shortcuts

### PR DESCRIPTION
**Pull request by adolfopa**
https://liferay.atlassian.net/browse/LPS-190783

I've applied the changes suggested by Brian at https://github.com/brianchandotcom/liferay-portal/pull/141653

Only the last 6 commits need to be reviewed. The rest is the same (clean rebase).

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Failures are unrelated.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
