### PR TITLE
LPS 114310 [NOT FOR GA5] Translations permissions

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hola @adolfopa,

These are the changes to support permissions at language level. This is how the permissions section looks like with them:

Screenshot_2020-08-07 User - Control Panel - Liferay

We followed @csierra advice and everything seems to work fine. There are some pending things:

* **React to new languages and languages that are removed**. At the moment we are registering the available locales on portal initialization [here](https://github.com/liferay-lima/liferay-portal/pull/583/files#diff-6d2f122c7a1a7e69134504acdeee0ee7R40-R51). If new languages are added they won't be recognized until the portal is restarted (hopefully). I don't know if we really want to do this.
* We are also generating one XML per language on the fly. I might be better to generate just one for all of them using FTL.
* I think we can get rid of the `moduleServiceLifeCycle` and the `immediate=true` from [here](https://github.com/liferay-lima/liferay-portal/pull/583/files#diff-83b5d9c5538eec3add8a5ff49950697dR81).
* We might want to alphabetically sort the list from the screenshot.
* Pablo was ok to go in this direction but it would be nice if he could test it just in case.

@AliciaGarciaGarcia if I've missed something please feel free to comment.
@csierra if you want to have a look your feedback is always welcome unless it is not good feedback 😜

Thanks!

🏖

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/590

**Pull request closed without merging**
