### PR TITLE
LPS-167436 External video shorcut - two nested legend fields: "New External Video Shortcut".

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-167436

> There is one new issue I see, which is that there are two nested fieldsets that have the same legend: "New External Video Shortcut". This results in "New External Video Shortcut Group" being announced twice when the first input is focused. It's only this last part that I believe still needs to be fixed.

There were two legends being added by two different taglibs with the same title: 
- `<aui:form>` adds it whenever there is an [onSubmit fn ](https://github.com/liferay/liferay-portal/blame/master/portal-web/docroot/html/taglib/aui/form/start.jsp#L26-L26)
- `<aui:fieldset>` adds it when there is[ no label](https://github.com/liferay/liferay-portal/blame/master/portal-web/docroot/html/taglib/aui/fieldset/start.jsp#L80-L80)

Which resulted in the following markup:

DM nested legend fields

As we cannot remove the `<aui:form>` taglib because it adds neccessary logic, but the <aui:fieldset> was not adding any value if there is no label, I choosed to remove the fieldset to not have two nested legends

### CODE REVIEW

**Review by jaimelr10 — APPROVED** [review]
LGTM! :+1:

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
