### PR TITLE
[TS] LPS-181899 Item Selector won't show all Sites grouped to the paginated page

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

I have incorporated Brian's [suggestions](https://github.com/brianchandotcom/liferay-portal/pull/134992#issuecomment-1553309060) in the newest version of the solution.

Could you please check it?

Thank you!

Best regards,
István

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
