### PR TITLE
LPS-122895

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi!
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
Hi @liferay-lima ,
I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.
Thank you and best regards,
Marci

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
