### PR TITLE
LPS-147822 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-147822

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:blogs

**Comment by austinchiang** [comment]
ci:test:blogs

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:blogs

**Comment by austinchiang** [comment]
ci:test:blogs

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:blogs

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
