### PR TITLE
LPS-161697 Rename display contexts and jsps that refer to kb models

### PR DESCRIPTION
**Pull request by adolfopa**
This is a followup to https://github.com/brianchandotcom/liferay-portal/pull/122496

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
