### PR TITLE
LPS-154730 | master

### PR DESCRIPTION
**Pull request by liuxingye**
Solved conflicts with rebase so you can move forward with the review. Original PR: https://github.com/liferay-lima/liferay-portal/pull/3304

Hi guys, I've opened this PR because most of the service changes I've made are related to your components. I'm going to introduced what are the changes that you should reviewed. Our team has verified that the errors appearing in the CI are not related, but we still want your approval, you can see [here](https://github.com/liferay-frontend/liferay-portal/pull/2548). You can check the desciption in the link of the PR from frontend-infra. Let's give you a little context.

## Main Objective
The main of this PR is to expose `externalReferenceCode` in DocumentsFolder. For that reason I have made some changes in the service part and in the API part.

## Service part
The main changes that you should review, are the following:

- Those changes related to `documentlibrary` in portal-impl. These changes are related because we add the new argument using `externalReferenceCode`.
- In the same way, in those modules I have implemented two new methods to obtain a DLFolder usign the `externalReferenceCode`, which are `fetchFolderByExteranlReferenceCode` and `getFolderByExteranlReferenceCode`.
- As there are some changes that affect the service part of DLFolder, I want to be sure that the Staging mode works correctly, some changes are added.
- New Upgrade process, if the `externalReferenceCode` is `null` or "", the data base will save the `externalReferenceCode` using the `UUID`.
- Requested changes in https://github.com/brianchandotcom/liferay-portal/pull/121934#issuecomment-1221215791 

## API part
However, this part can be ignored, beause it is reviewed by our members of the team.

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-154730

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Analyzed latest [test results](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1964194746&testrayRunId=1964234491) of relevant, they are unrelated to this pull.

**Comment by sergiojimcos** [comment]
Hi @liuxingye, this PR can be forwarded?

**Comment by liuxingye** [comment]
Hi @sergiojimcos, 

I think QA will never forward if we don't see a dev run ci:forward on the pull. But this probably needs to resolve conflicts first.

Thanks. 

cc @adolfopa

**Comment by sergiojimcos** [comment]
Hi @liuxingye I will open a new PR with the new changes to solve the conflicts

Thanks.

**Comment by sergiojimcos** [comment]
See here: https://github.com/liferay-lima/liferay-portal/pull/3454

**Comment by liuxingye** [comment]
Hi @sergiojimcos, you didn't fetch my POSHI changes in the new PR https://github.com/liferay-lima/liferay-portal/pull/3433/commits/1817a7eee6170d2a1e80fc9f67ecee0ba27f3df0

**Pull request closed without merging**
