### PR TITLE
LPS-199736 Move Invite Members widget to react

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
follow up of pull https://github.com/liferay-lima/liferay-portal/pull/4887 

## Motivation

In echo Team we are replacing AUI() usages with js, but in this case, it was a bit difficult to move it to js, so we decided to migrate it ro react

## Steps 

- Go to Control Panel > Users and Organisations 
- Create some users 
- Go to Site Builder > Pages > Create a Content Page
- Add a "invite members" widget to the Content Page > Publish
- View the Content Page > click on Invite Members button and see modal

**To send an invitation to an user:**

- Go to Control Panel > Users and Organisations > Create an user
- Go back to the page in view mode > click on invite members 
- Click on the user created > Send Invitations 
- Go to Control Panel > Users and Organisations > Impersonate the user created
- In the user Profile > Notifications
- Go to Request list tab > see the invitation

Screenshot 2023-11-17 at 14 47 43

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
cc/ @DiegoHu97 please review my changes and let me know if something needs clarification. 

You did a great job with this pull, thank you very much!!!

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
