### PR TITLE
LPS-169931 MimeTypesUtil getContentType can return a null so we have to check if the mimetype is null or not and return an empty string if it is

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
MimeTypesUtil getContentType can return a null so we have to check if the mimeType is null or not and return an empty string if it is

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:lima

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:lima

**Comment by Hanlf** [comment]
Checked the result of oauth2 and lima suite results, the Poshi failures are not unique to this pull.
The relevant job failures are not related to this pull.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failures are not related to this PR, sent it to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/127159

**Pull request closed without merging**
