### PR TITLE
LPS-127581 remove empty list item

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@boton I think it's ok to remove that <li> that in my opinion was doing nothing.

if ok, forward it

Thanks!!

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by boton — APPROVED** [review]
Tested, worked and LGTM

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
