### PR TITLE
LPS-126199 Update the classes manually here because isn't selectable

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
LGTM!

**Comment by boton** [comment]
Hi @marcoscv-work,
I need to update the markup of the update to get it working, new card containers... 

Please can you check I made something terrible? :)

**Comment by marcoscv-work** [comment]
simple and cool, LGTM!

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
