### PR TITLE
LPS 191041

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Since for cards we are already escaping title and subtitle, we should find a way to not double escaping those fields.

[Link to the issue
](https://liferay.atlassian.net/browse/LPS-191041)

Proposed solution
----
Removes escape from title and subtitle in **ItemSelectorViewDescriptor.ItemDescriptor** and add it to item selector table and descriptive view, in that way we are going to escape it only once.

Steps to reproduce
----

1. Add a new user with special characters in first name and last name
><script>alert(1)</script> and ><script>alert(2)</script>
2. Add a new site
3. Navigate to the Memberships admin
4. Open the Assign Users to This Site modal
5. Change the display style to list
6. The special characters are shown
7. Change the display style to cards

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1257401_2034

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by ealonso** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/138242

**Pull request closed without merging**
