### PR TITLE
LPS-164776 KB Display widget: navigation for folders

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Notes agreed with UX: 

1. left navigation is always visible if the user selected a folder. 
2. if selected folder has no subfolders, the select is disabled. 
3. Cannot add icons for folder in the select. 

Screenshot 2022-10-26 at 15 29 30

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@ambrinchaudhary I think we should get rid of the root content selector altogether. Maybe we can talk about this tomorrow with design/product. I really dislike that "feature".

**Comment by ambrinchaudhary** [comment]
> @ambrinchaudhary I think we should get rid of the root content selector altogether. Maybe we can talk about this tomorrow with design/product. I really dislike that "feature".

yeah let's discuss it. I don't have enough context to have clear that we should remove it... in addition, I've seen mockups for future improvements and the root selector is there.

**Review by boton — COMMENTED** [review]
I tested on the `Knowledge Base Display` and looks weird with one full with select above the title.

image

After the morning discussion, do we want to translate folder navigation to the final user?

**Comment by ambrinchaudhary** [comment]
Hey @boton that is really strange, are you sure you deployed correctly the module? Because that was removed on my first [commit](https://github.com/liferay-lima/liferay-portal/pull/3650/commits/88c9f120e21c9817e2c1139fc2e013646e0c732d)

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
