### PR TITLE
LPS-136275 create commerce image service to upgrade the image table to include correct companyId on commerce tables

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-136275

I tested it with the issue on https://issues.liferay.com/browse/LPS-136206 to check if error is throw or server do not start.

I looks ok

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
cc/ @adolfopa for futures references

**Review by 4lejandrito — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
