### PR TITLE
LPS-114611 Update path to the test components

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @adolfopa, please not that we should generate the buildLang in _portal-impl_, (sorry I don't know how should I generate it) before sendiing this pull to frontend infra. 
Thank you!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/ambrinchaudhary/liferay-portal/pull/370

**Pull request closed without merging**
