### PR TITLE
LPS-178719 | Master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://issues.liferay.com/browse/LPS-178719

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@WYZ-Issac please resend with changes we discussed:
- Delete default Liferay folder via JSON instead of changing the max storage size

**Review by austinchiang — CHANGES_REQUESTED** [review]
.

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
