### PR TITLE
LPS-127694 Make title a link to be consistent with other listings

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Hey @adolfopa which other listings are implementing this same pattern? At first sight it looks  not ok to make something a useless link just for styling purposes.

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
