### PR TITLE
LPS-183040 Remove download action if the file has no content

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-183040

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-183040.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failure is not related to this PR.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
