### PR TITLE
Rollback LPD-15082 since strongly modifies web content logic

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
cc/ @liferay-forms

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
Errors seem to be unrelated: forcing forward

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
