### PR TITLE
LPS-154342 Filter depot groups same as GroupItemSelectorProviderImpl

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

Can you help review this PR? 

**Notes from @noornajj**
> https://issues.liferay.com/browse/LPS-154342
> 
> The issue here was that no permission check was done when accessing Asset Libraries in GroupItemSelectorProvider
> To fix the issue, I added a _filterGroup method same as the one in GroupItemSelectorProviderImpl

- Here is a link to the mentioned method: [GroupItemSelectorProviderImpl.java#L123-L141
](https://github.com/liferay/liferay-portal/blob/7.4.3.27-ga27/modules/apps/item-selector/item-selector-impl/src/main/java/com/liferay/item/selector/internal/provider/GroupItemSelectorProviderImpl.java#L123-L141)

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — CHANGES_REQUESTED** [review]
Logic looks good, but I think the changes should be made in the DepotEntryServiceImpl. Can you  modify the `getGroupConnectedDepotEntries` methods in the service so that only depot entries whose groups satisfy the check are returned?

Thanks!

**Comment by adolfopa** [comment]
@ericyanLr @noornajj Did you see my comment?

**Pull request closed without merging**
