### PR TITLE
LPS-168348 Allow multiple model document contributors for WikiPage and KBArticle to make Semantic Search sentence embedding working

### PR DESCRIPTION
**Pull request by lipusz**
https://issues.liferay.com/browse/LPS-168348

Hi,

We need these changes so `WikiPageSentenceEmbeddingModelDocumentContributor` and `KBArticleSentenceEmbeddingModelDocumentContributor` can start working (residing in `modules/dxp/apps/search-experiences-service`) in created part of our Semantic Search Epic ([LPS-163688](https://issues.liferay.com/browse/LPS-163688)).

We introduced similar changes for JournalArticle previously in https://github.com/liferay/liferay-portal/commit/4cabf7e23fdf15892525e48f0cff7ed97bfbb7ba

(Note: preliminary single model document contributor support was implemented for JournalArticle in [LPS-148010](https://issues.liferay.com/browse/LPS-148010), followed the pattern from there to make the necessary changes for WikiPage and KBArticle.)

Passed manual testing.

Thanks,
Tibor

/cc @peerkar

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
:information_source: [LPS-86734](https://issues.liferay.com/browse/LPS-86734) [LPS-86733](https://issues.liferay.com/browse/LPS-86733) are in the backlog for migrating WikiPage and KBArticle from the legacy indexers to the composition based implementation.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by joshchong** [comment]
ci:test:bundle

**Pull request closed without merging**
