### PR TITLE
LPS-122269

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-122269

@adolfopa ,

We need to include this edge case commit specifically for ".lar" extensions as per LPS-122269.

Sincerely,
Brian

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
@brianikim Sorry, but I will send a revert for the original changes. To me, this is proof that changing the document extension arbitrarily will cause problems. This will happen with other kinds of files (e.g. LPKG, lightweight markup formats other than Markdown, etc.).

Adding special cases as problems arise is not a solution, we should guarantee that things work predictably for the general case. If people want certain kinds of documents to use particular extensions, they should upload the document with that extension, and not rely in some "guessing" heuristic.

Sorry, but I think it is better to revert everything to avoid more problems in the future.

Thanks!

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/913

**Pull request closed without merging**
