### PR TITLE
LPS-145475 Update DLFileEntry services to take url title

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_1853

**Comment by adolfopa** [comment]
@austinchiang Can you guys help me with this PR? Can you examine the test results to see if the failures are relevant? Thanks!

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
Can you take a look @liuxingye

**Comment by liuxingye** [comment]
Resending this pull directly to BChan https://github.com/brianchandotcom/liferay-portal/pull/113839. Thanks.

cc/ @adolfopa

**Pull request closed without merging**
