### PR TITLE
LPS-177483 Reset the input stream to avoid adding files with 0 bytes

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://issues.liferay.com/browse/LPS-177483

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
The above failures are not related to this PR, sent it to BChan: https://github.com/brianchandotcom/liferay-portal/pull/131449

**Pull request closed without merging**
