### PR TITLE
revert_change_about_httpcomponents_on_sharepoint

### PR DESCRIPTION
**Pull request by jeffwu0724**
Hi team, 

This is for the regression in ticket https://issues.liferay.com/browse/LPS-171756.
I partially reverted the change that was made in sharedpoint.
Please let me know if this will fix the bug.
Thanks for checking.

cc: @Hanlf

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @jeffwu0724 the regression LPS-171756 is fixed with this PR, thanks!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
