### PR TITLE
LPS-141976 / LPS-107367 / LPS-141143 Apply friendly URL tag to Blogs and Journal

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
@adolfopa I missed some of my commits on #2473 fixing test and updating it, I´m going to recover it and push on your branch.

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Pull request closed without merging**
