### PR TITLE
LPS-157570 Fix grammar for OneDrive alert

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-157570 Create new message more accurate and use it
- LPS-157570 delete old message
- LPS-157570 build lang
- LPS-157570 change message on test

I couldn't test it because the OneDrive credentials failure :( 

maybe put on hold?

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:online-editing

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
Hi @AliciaGarciaGarcia 
Tested this PR with OneDrive Suite, all OneDrive functional tests passed. The OneDrive credentials seem to work fine, at least the ones we use for CI. Let me know if you need the test credentials.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
