### PR TITLE
LPS-152917 Test Scenarios Coverage LPS-129803 Keep a history of friendly URLs for documents

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-152917 tests that the Old friendlyURL can be removed from the history

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
