### PR TITLE
LPS-167321 [a11y bug] site selector open new window

### PR DESCRIPTION
**Pull request by boton**
## Issue: https://issues.liferay.com/browse/LPS-167321 

I have updated the markup to use `clay:link` instead of `aui:a` in this specific case.

### After this PR
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failures are not related to this PR, sent it to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/126971

**Pull request closed without merging**
