### PR TITLE
LPS-127598 Fixing edit file form submission

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @boton,

These changes are related to https://issues.liferay.com/browse/LPS-123711 which you worked on. Can you please review and verify everything works as expected?

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by boton — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
