### PR TITLE
LPS-163033, LPS-162370 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-162730
https://issues.liferay.com/browse/LPS-163033
https://issues.liferay.com/browse/LPS-162837

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
