### PR TITLE
[7.4.x only] LRQA-62922 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-62922

@adolfopa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
LGTM! 👍

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
Sent in https://github.com/liferay-lima/liferay-portal/pull/1042/

**Pull request closed without merging**
