### PR TITLE
LPD-15353 Bring back DLStore.deleteFile method

### PR DESCRIPTION
**Pull request by robertoDiaz**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-15353

Some usages of the `DLStore.deleteDirectory` method assume behavior that is not satisfied by the advanced file system store. This causes deletion to leave orphaned files in the file system.

# How am I fixing it?

By bringing back the old `DLStore.deleteFile` method.

# How can I verify that it works?

Automated tests are included in this same PR.

Additionaly, you may follow the manual steps described in https://liferay.atlassian.net/browse/LPD-15353.

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
Tests seem unrelated.

**Comment by robertoDiaz** [comment]
ci:forward:force

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
