### PR TITLE
LSP-136390 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-136390

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:translation

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:close

**Comment by liuxingye** [comment]
@austinchiang  I've rebased and resent this PR here See https://github.com/liferay-lima/liferay-portal/pull/2530

**Pull request closed without merging**
