### PR TITLE
LPS-176777 Mentions tests fail intermittently

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-176777

# How do I test it?

This is a flaky test, so you may not be able to reproduce the error. Follow the steps described in https://issues.liferay.com/browse/LPS-176777.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — COMMENTED** [review]
**The PR is ok**, but It worries me that we are creating a company each test.


```
	@Before
	public void setUp() throws Exception {
		_company = CompanyTestUtil.addCompany();
```
		
It takes a lot of time and resources to do it each time,

I tried to do something like this:
```


	@BeforeClass
	public static void setUpClass() throws Exception {
		_company = CompanyTestUtil.addCompany();
	}


	@AfterClass
	public static void tearDownClass() throws Exception {
		_companyLocalService.deleteCompany(_company);
	}

	private static Company _company;

	@DeleteAfterTestRun
	private Group _group;

	@DeleteAfterTestRun
	private Layout _layout;

	@Inject
	private static CompanyLocalService _companyLocalService;
```

And the test time (on my machine) downs from 8 minutes to 2

~but `testServletResponseWithQueryWithWildcardAndNoResults` starts to fail and I can't find the reason. (neither I put much effort)~

@adolfopa do you think that is worth ~to look into~ or better to forward this PR?


_Edited:_ 

I fix it with my changes and :
```

	private User _addUser(String screenName) throws Exception {
		User adminUser = UserTestUtil.getAdminUser(_company.getCompanyId());

		_user = UserTestUtil.addUser(
			_company.getCompanyId(), adminUser.getUserId(), screenName,
			LocaleUtil.getDefault(), RandomTestUtil.randomString(),
			RandomTestUtil.randomString(), new long[] {_group.getGroupId()},
			ServiceContextTestUtil.getServiceContext(_company.getGroupId()));

		return _user;
	}

	@DeleteAfterTestRun
	private User _user;
```

Do you think I can send this commit for this pr?

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Sounds good, but as this PR is green, do you mind sending the change in a different PR?

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
