### PR TITLE
LPS-137042 ComparisonFailure in FileEntryInfoDisplayContributorTest because now depends of the value of LOCALE_PREPEND_FRIENDLY_URL_STYLE and the default locale

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
ComparisonFailure in FileEntryInfoDisplayContributorTest : https://issues.liferay.com/browse/LPS-137042

Is caused by https://issues.liferay.com/browse/LPS-135692

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by 4lejandrito — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
