### PR TITLE
LPS-129603 When importing blog entries via a LAR file, the small image URL field is missing

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The upgrade test failure is caused by [LPS-134610 ](https://issues.liferay.com/browse/LPS-134610), no related to this pr, So I think it’s safe to send directly to BChan.
Hi @adolfopa If you need help resending, please let me know.

**Comment by adolfopa** [comment]
Thank you @Hanlf . Can you move it forward? (I'm not in the whitelist).

Thanks!

**Comment by Hanlf** [comment]
@adolfopa Resent it here: https://github.com/brianchandotcom/liferay-portal/pull/103682

**Pull request closed without merging**
