### PR TITLE
LPS-163853, LPS-163261 KB edit article updates - attachments

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
After the changes
Screenshot 2022-10-13 at 18 15 59

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
LGTM. I added a function to manage events 15c3b4797d1daf2f7e1204a555038f9db4a3b8e5 and remove the submit event on portlet dispose 3a917c1f13835ef5ff1d9da8663ff4fa8014fecb

**Comment by boton** [comment]
> LGTM. I added a function to manage events [15c3b47](https://github.com/liferay-lima/liferay-portal/commit/15c3b4797d1daf2f7e1204a555038f9db4a3b8e5) and remove the submit event on portlet dispose [3a917c1](https://github.com/liferay-lima/liferay-portal/commit/3a917c1f13835ef5ff1d9da8663ff4fa8014fecb)

@ambrinchaudhary if this makes sense to you feel free to forward it.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
