### PR TITLE
LPS-163268 Caused by: java.lang.UnsupportedOperationException: Requires 3.0 opt-in

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
This reverts commit a8ae859b27db81c4c737c7864b2c99e820d8126d.

The update of portlet version to 3 must be done to all the components or will throw an 
`Caused by: java.lang.UnsupportedOperationException: Requires 3.0 opt-in`

and when calling  `ItemSelectorPortlet` that is v2 and blocks the functionality of knowledge base.

This is a release blocker, so we're reverting the changes.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
I do not know why my system decided to make 2 reverts...
Resend to 
https://github.com/liferay-lima/liferay-portal/pull/3502.

**Pull request closed without merging**
