### PR TITLE
LPS-200765 Show the next year on the DatePicker

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-200765 

Now it is possible to select the next year: 
Screenshot 2023-11-03 at 14 49 58

### CODE REVIEW

**Review by boton — APPROVED** [review]
LGTM, tested and working

image

**Comment by boton** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
