### PR TITLE
LPS-135447 No meta tag `og:image:alt` displays on the page source for Web Content

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
The image is not null and the alt image description is stored on the infovalues from the wc.

i'm not sure if this approximation is the better.

What do you think about it?

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
The `OpenGraphTopHeadDynamicIncludeTest.testIncludeMappedTitleAndDescription` was the test failing me on local, but now It's failing here.
I'll rebase and retest on local and upload.

thanks!

**Comment by AliciaGarciaGarcia** [comment]
OK, It's failing (on local) if the `FFSEOInlineFieldMapping` is enabled, so @adolfopa maybe this is a deeper error?

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia The behaviour of the template class changes depending on the value of the feature flag. It may be necessary to change test expectations if you enable the feature flag. Take a look at the LayoutSEOTemplateProcessorImpl class.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
