### PR TITLE
LPS-125413 Use new ImageSelector component in image-selector tag and remove old one

### PR DESCRIPTION
**Pull request by carloslancha**
Following up on https://github.com/liferay-lima/liferay-portal/pull/1484

https://issues.liferay.com/browse/LPS-125413

In this pr we're removing the old `image-selector` AUI component in favor of the new React one.

We're adding some missing markup in the React component and removing no needed one for SSR in the JSP

Made also some refactor and renaming in the React Components.

Deprecate `draggableImage` in favor of new `imageCropDirection` attribute in `ImageSelector` tag to improve naming.

imageselector

Test Plan 1:
- Go to Content & Data / Blogs
- Create a new Blog
- Select an image bigger than the container
- Click and move vertically the picture to crop it in the desired position
- Publish
- Edit the blog
- Check that the image has been cropped correctly

Test Plan 2:
- Go to Content & Data / Blogs
- Edit an existing Blog with an image
- Check that you can't move the image since it's already cropped
- Remove the image and repeat Test plan 1 from point 3.

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
I think the failure is not from this PR but it had not been detected until now, when a draft is autosaved we find the input coverImageFileEntryCropRegion and on blogs.js we are trying to retrieve the value with getElementById https://github.com/liferay/liferay-portal/blob/5860529bcad88ac3c9b2f76f7e5cd7c877e5cc23/modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/js/blogs.js#L363-L365 so it would be fine to add that missing id 😄 

image


It is a little trickier to see because that part of the code is only passed when drafts are saved in the background, you only have to leave it open for a few seconds with some type of content to see the failure.

**Comment by carloslancha** [comment]
Thx @boton yup, it looks like some ids were missing there since the creation of the component. Just added'em and pushed the commit ;)

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
For this pr to pass the tests we will to update some poshi ones since `Select File` link is no longer a link but a button. Who should I mention for it? 

cc @boton @4lejandrito @adolfopa

**Comment by boton** [comment]
I'm not sure because our team is on new year's Chinese vacation, @adolfopa @4lejandrito do you remember?

**Comment by 4lejandrito** [comment]
If the tests fail we can replace those literals in the poshi tests ourselves and forward.

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Retested and the bug is gone, thanks @carloslancha 🎉 ❤️

**Review by boton — APPROVED** [review]

**Comment by carloslancha** [comment]
>If the tests fail we can replace those literals in the poshi tests ourselves and forward.

@4lejandrito where and how? Thx!

**Comment by 4lejandrito** [comment]
Hi @carloslancha,

https://github.com/liferay/liferay-portal/blob/2ba16705f5dda7ca1195953ef167b0e279e550a8/modules/apps/item-selector/item-selector-test/src/testFunctional/tests/ImageSelector.testcase

and 

https://github.com/liferay/liferay-portal/blob/e6e768a6a4294e53789b0ab8e514e0591561869b/modules/apps/item-selector/item-selector-test/src/testFunctional/tests/ItemSelector.testcase

Search for `Select File`.

**Comment by boton** [comment]
I'm going to add some docs https://qa-compendium.readthedocs.io/en/latest/poshi/writing/writing-a-test-case.html#running-the-test but IMHO maybe it is a best idea to ping QA

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by carloslancha** [comment]
Hey @nikki-pru could you please take a look to the failing poshi test? Not sure if it's something we're breaking or sth we need to update on the tests because these changes. Thx!!

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by nikki-pru** [comment]
Hi @carloslancha, it looks like the changes to `resources/image_selector/page.jsp`, specifically around `<div class="image-wrapper>` could be causing the failure. If the change is intentional, the test might need a fix. I'll pull your branch now and send you the fix.

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
