### PR TITLE
LPS-105950 Auto SF

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
Auto SF [looks strange](https://github.com/liferay-lima/liferay-portal/pull/407/commits/311472653bc978484a94968a07b9e5ce0b75d54a#diff-75769fbf893b766339af9637a098a199R70-R80), not sure if this is expected. Asking @hhuijser to take a look

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Confirmed this is expected

**Comment by adolfopa** [comment]
Will resend among other LPS to avoid rebase conlicts.

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/410

**Pull request closed without merging**
