### PR TITLE
LPS-150718 Localice translations error report file

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-150718

### After this PR

**EN**
image

**ES (test translation)**
image

@adolfopa @AliciaGarciaGarcia @ambrinchaudhary I'm not sure if we have a better way https://github.com/liferay-lima/liferay-portal/commit/a4d7d7f8fe2f2504224f64cc50291d531c7ba130#diff-ef119629946c9b5876f3ddaf7e739fa3316781f38535fa10141db62509a5d684R5217 to indicate that it is the name of a real file that the user will download.

### CODE REVIEW

**Comment by boton** [comment]
test:ci:sf

**Comment by boton** [comment]
test:ci:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
