### PR TITLE
LPS-134126 Move import translation logic into translation-web

### PR DESCRIPTION
**Pull request by adolfopa**
Everything was moved, so checking the usual import/export process is enough to verify this works.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Review by ambrinchaudhary — APPROVED** [review]
Checked code and tested (is working as expected). Thanks!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
