### PR TITLE
LPS-144021 Add config. to disable 404 tracking

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@austinchiang This is the PR that adds the configuration to disable 404s (see 2fcda07e509d5f3caefb8009ba49e6616ce72b39). By default will be disabled, so you need to update the tests.

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa Baseline apart .

LGTM

Forward after baseline

**Comment by Hanlf** [comment]
Sent it with Poshi test fix under: https://github.com/liferay-lima/liferay-portal/pull/2567

**Pull request closed without merging**
