### PR TITLE
LPS-148819 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-148819

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:acceptance-functional

**Comment by austinchiang** [comment]
ci:reevaluate:1297401_2620

**Comment by austinchiang** [comment]
ci:test:acceptance-functional

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/2964

**Pull request closed without merging**
