### PR TITLE
LPS-146951 Detect group change and navigation out of external repo

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1297401_1765

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — DISMISSED** [review]
Unfortunately , this changes seems that make some issues with the breadCrumb

https://user-images.githubusercontent.com/47524751/154669085-c3a34893-9d59-41f8-91f4-dc4635686bde.mp4

On other hand, with local staged AL/site (this is not related to this PR, i think) 
on the DM widget we are always pointing to the staged AL.

and if we de-stage AL, and this happens to with de-staging the AL and the site, the portlet is unavailable

image

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
