### PR TITLE
[TS] LPS-179148 MS SQL cannot handle aliases in GROUP BY clause

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
Recent Bloggers portlet throws Invalid column name 'blogsEntryGroupId' with MS SQL server.
This is because MS SQL cannot handle aliases in the GROUP BY clause.
https://stackoverflow.com/questions/497241/how-do-i-perform-a-group-by-on-an-aliased-column-in-sql-server

Proposed Solution
========
Instead of the aliases, use the column names directly in the GROUP BY clause.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://issues.liferay.com/browse/LPP-48372

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
Hi @IstvanD your changes look good! Just please be sure this is working in MS SQL since I don't have a local installation and I cannot test it.

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by IstvanD** [comment]
Hi @marcogalluzzi thanks for forwarding it! I tested the solution on MS SQL 2019.

**Pull request closed without merging**
