### PR TITLE
LPS-125016 Make global file size limit an instance scoped configuration

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-125016

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/2834

**Pull request closed without merging**
