### PR TITLE
LPS-128547 Fix Language selector alignment in translations

### PR DESCRIPTION
**Pull request by victorg1991**
https://issues.liferay.com/browse/LPS-128547

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]
Changes LGTM. Anyway, I'm trying to test it but I'm getting errors while runing portal, so I'll check it next day. Unless @victorg1991 you want to paste some screenshot or video that shows this works ;-)

**Comment by boton** [comment]
@victorg1991 thanks for the PR, works awesome!

**Before PR**
image

**After PR**
image

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
