### PR TITLE
LPS-121865 Migrate v2 usages in bookmarks/bookmarks-web

### PR DESCRIPTION
**Pull request by julien**
**Orignally reviewed [here](https://github.com/liferay-frontend/liferay-portal/pull/765)**

In this change we've updated the `<clay:management-toolbar-v2 />`
to `<clay:management-toolbar />` (which uses clay v3), adding new
bookmarks and bookmarks folders or deleting them works as expected.

**Test plan**:
- Navigate to **Content & Data > Bookmarks**
- From the management toolbar you should be able to 
    - Create a bookmark
    - Create a bookmark folder
    - Delete a bookmark
    - Delete a bookmark folder

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by carloslancha — APPROVED** [review]
This pr is not horrible @julien :P (I missed it xD)

Thx!

**Comment by julien** [comment]
@carloslancha :joy: I missed that too - thanks for reviewing.

**Comment by carloslancha** [comment]
@boton I tested it and it looks it's working as expected, feel free to test it or just forward it, thx!

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
