### PR TITLE
LPS-178095 Unable to update documents if the antivirus is enabled - File version is invalid

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-178095

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
It looks good to me, although I don't think is a good practice changing an input parameter.

@adolfopa can you also please review this PR? With your knowledge, maybe you can see more implications of this change.

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
It looks good. I'll need to make further changes to that method as part of another story, so we can fix any stylistic issues there and forward this as is.

**Comment by adolfopa** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
Hi @austinchiang can you have a look to the error of this PR? It seems not related to the PR. Thanks

**Comment by austinchiang** [comment]
Test failures unrelated to the pull

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
