### PR TITLE
LPS-202129 Do not allow now valid keywords in Redirections

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://liferay.atlassian.net/browse/LPS-202129

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:stop

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
Hi @robertoDiaz Could you help to confirm if this backend test failure is related to this PR? Thanks.
[com.liferay.friendly.url.servlet.test.FriendlyURLServletTest](https://testray.liferay.com/en/home/-/testray/case_results/2466352660?redirect=https%3A%2F%2Ftestray.liferay.com%2Fen%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2466351178%26testrayRunId%3D2466351243%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
```
 [exec] com.liferay.friendly.url.servlet.test.FriendlyURLServletTest > testServiceRedirectWithRedirectEntry FAILED
[beanshell]      [exec]     com.liferay.portal.kernel.exception.LayoutFriendlyURLException
[beanshell]      [exec]     	at com.liferay.portal.service.impl.LayoutLocalServiceHelper.validateFriendlyURLKeyword(LayoutLocalServiceHelper.java:515)
[beanshell]      [exec]     	at com.liferay.redirect.service.impl.RedirectEntryLocalServiceImpl._validate(RedirectEntryLocalServiceImpl.java:454)
[beanshell]      [exec]     	at com.liferay.redirect.service.impl.RedirectEntryLocalServiceImpl.addRedirectEntry(RedirectEntryLocalServiceImpl.java:86)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)
[beanshell]      [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
[beanshell]      [exec]     	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:51)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
[beanshell]      [exec]     	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:55)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
[beanshell]      [exec]     	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:70)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40)
[beanshell]      [exec]     	at com.sun.proxy.$Proxy816.addRedirectEntry(Unknown Source)
[beanshell]      [exec]     	at com.liferay.friendly.url.servlet.test.FriendlyURLServletTest._testServiceRedirectWithRedirectEntry(FriendlyURLServletTest.java:709)
[beanshell]      [exec]     	at com.liferay.friendly.url.servlet.test.FriendlyURLServletTest.testServiceRedirectWithRedirectEntry(FriendlyURLServletTest.java:587)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
[beanshell]      [exec]     	at java.lang.Thread.run(Thread.java:750)
```

**Comment by robertoDiaz** [comment]
@Jeremy-Ch 

Yes, it is.

Analyzing

**Comment by robertoDiaz** [comment]
```
	@Test
	public void testServiceRedirectWithRedirectEntry() throws Exception {
		_testServiceRedirectWithRedirectEntry("hu/path", true, 301);
		_testServiceRedirectWithRedirectEntry("path", true, 301);
		_testServiceRedirectWithRedirectEntry("path", false, 302);
	}
```
This test is creating a non valid redirect entry. 

`_testServiceRedirectWithRedirectEntry("hu/path", true, 301);`  has to be removed.

**Comment by robertoDiaz** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/4959

**Pull request closed without merging**
