### PR TITLE
LPS-159744 DM icons - remove dev FF 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
On Hold until https://issues.liferay.com/browse/LPS-154043 is completed

- [x] ~~Check if checkin_js.ftl could be removed~~ (Not possible, is it been used by a ToolbarItem :( )
- [x] Remove compate_to_js.ftl

**Context**: 

The current dropdowns were rendered using the `liferay-ui:menu-item` taglib. This didn't allow to add icons in an easy way (in fact it caused a regression bug, and to solve this many changes in an "old" taglib were needed). So the approach was to replace that dropdowns and render Clay Dropdowns instead. 

So in this pull I've tried to get rid of any _xxxMenuItems_ configured in the backend side, as they were not going to be rendered anymore. But while doing this, I realised there were other dropdowns that need to be replaced (thus stories were created for [File entry detail](https://issues.liferay.com/browse/LPS-153216),  [Media Gallery ](https://issues.liferay.com/browse/LPS-154737)and [Versions](https://issues.liferay.com/browse/LPS-154043)). Now, I see there are still some MenuItems that needs to be rendered in the clay dropdown: 

- Google Drive (_DLOpenerGoogleDriveDLViewFileVersionDisplayContext.java_)
- Google Docs (in Media Gallery?) (_GoogleDocsIGViewFileVersionDisplayContext.java_)
- Video shortcut (_DLVideoExternalShortcutDLViewFileVersionDisplayContext.java_)

So do not forward this pull until those options are migrated, otherwise they will not show up in the dropdowns and we will cause regressions. 

cc/ @adolfopa @AliciaGarciaGarcia

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test

**Comment by AliciaGarciaGarcia** [comment]
Hi @ambrinchaudhary 

can you take a look at this error
```

     [echo] /Users/aliciagarcia/liferay/ce/portal/modules/dxp/apps/document-library-opener/document-library-opener-onedrive-web/src/main/java/com/liferay/document/library/opener/onedrive/web/internal/display/context/DLOpenerOneDriveDLViewFileVersionDisplayContext.java:143: error: method does not override or implement a method from a supertype
     [echo] 	@Override
     [echo] 	^
     [echo] /Users/aliciagarcia/liferay/ce/portal/modules/dxp/apps/document-library-opener/document-library-opener-onedrive-web/src/main/java/com/liferay/document/library/opener/onedrive/web/internal/display/context/DLOpenerOneDriveDLViewFileVersionDisplayContext.java:154: error: cannot find symbol
     [echo] 			return super.getMenu();
     [echo] 			            ^
     [echo]   symbol: method getMenu()
     [echo] /Users/aliciagarcia/liferay/ce/portal/modules/dxp/apps/document-library-opener/document-library-opener-onedrive-web/src/main/java/com/liferay/document/library/opener/onedrive/web/internal/display/context/DLOpenerOneDriveDLViewFileVersionDisplayContext.java:157: error: cannot find symbol
     [echo] 		Menu menu = super.getMenu();
```

**Comment by ambrinchaudhary** [comment]
ci:test

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test

**Review by AliciaGarciaGarcia — APPROVED** [review]
LGTM

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Waiting QA review of `ci:test`

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Reviewing...

**Comment by liuxingye** [comment]
@ambrinchaudhary @AliciaGarciaGarcia 
Just want to confirm that after merging this PR, there's an alert "Are you sure you want to delete this? It will be deleted immediately." when deleting DM files. Does it meet our expectations? Thanks.

**Comment by ambrinchaudhary** [comment]
Hey @liuxingye, we shouldn't bee introducing any behaviour change with this PR, so let me check what youo described.

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
hi @ambrinchaudhary 

I re-tested with the changes we talk,

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1387401_2826

**Comment by liuxingye** [comment]
Hi @ambrinchaudhary 

Thanks for looking into the issue, I've send a new pull https://github.com/liferay-lima/liferay-portal/pull/3341 to solve the Poshi failures about failing to click on ellipsis icons. 

cc @AliciaGarciaGarcia

**Pull request closed without merging**
