### PR TITLE
LPS-189878 | Master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://liferay.atlassian.net/browse/LPS-189878

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by austinchiang — CHANGES_REQUESTED** [review]
Please use VerifyElementPresent

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Please use a for loop for the macro to make it more reusable

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
Looks much cleaner now, thanks @WYZ-Issac

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
