### PR TITLE
LPS-112756 update addFileEntryType method

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa I will close this pr to create a new ticket with smaller tasks

see https://github.com/liferay-lima/liferay-portal/pull/62

Sorry for the inconvenience and thanks!!!

**Comment by adolfopa** [comment]
Just started reviewing :)

**Pull request closed without merging**
