### PR TITLE
LPS 164161.reorder params

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-164161 add expiration date and review date to service add and update methods
- LPS-164161 buildService
- LPS-164161 fix calls to KBArticleService
- LPS-164161 add expirationDate reviewDate to macro addkBArticle
- LPS-164161 Declare missing parameters in other macros
- LPS-164161 reorder expirationDate and reviewDate as service.xml order
- LPS-164161 buildService
- LPS-164161 reorder sections param as service.xml order
- LPS-164161 buildService

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @AliciaGarciaGarcia 
The [service-builder-jdk8/0/0](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/295150//consoleText) failure should be related to this PR, could you please take a look, thanks!

About the ci:test:knowledge-base result, All except [KBDisplayPage#CanUpdateMaxNestingForArticleNavigation](https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/87288//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_KBDisplayPage_CanUpdateMaxNestingForArticleNavigation_) are known issues, could you fix it @austinchiang, thanks!

**Pull request closed without merging**
