### PR TITLE
LPS-172334 | Fix DepotWorkflow#CanRestoreWCFolderWorkflowToDefault test

### PR DESCRIPTION
**Pull request by jaimelr10**
Description: Fix for DepotWorkflow#CanRestoreWCFolderWorkflowToDefault
Jira Ticket: https://issues.liferay.com/browse/LPS-172334

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:test:lima

**Comment by austinchiang** [comment]
Test passed in https://testray.liferay.com/home/-/testray/case_results/2159749266

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
