### PR TITLE
LPS-137405 Move deletion logic to a scheduled task to avoid race conditions #2228

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
I have to check the broken test

**Comment by robertoDiaz** [comment]
I've run the test in my local system and it works as expected:

`> Task :apps:redirect:redirect-test:testIntegration

com.liferay.redirect.internal.messaging.test.CheckRedirectNotFoundEntriesMessageListenerTest STANDARD_OUT
 ....

com.liferay.redirect.internal.messaging.test.CheckRedirectNotFoundEntriesMessageListenerTest > testDeletesEntriesOlderThan30Days STARTED

com.liferay.redirect.internal.messaging.test.CheckRedirectNotFoundEntriesMessageListenerTest > testDeletesEntriesOlderThan30Days PASSED

com.liferay.redirect.internal.messaging.test.CheckRedirectNotFoundEntriesMessageListenerTest > testDeletesEntriesOverflowing1000Elements STARTED

com.liferay.redirect.internal.messaging.test.CheckRedirectNotFoundEntriesMessageListenerTest > testDeletesEntriesOverflowing1000Elements PASSED`

@liferay-lima could you review the current code and once the review is passed I could fix the conflicts (just removing the last 2 commits and regenerating them)

Thanks!!

**Comment by adolfopa** [comment]
@robertoDiaz Sorry, there's a rebase conflict with the new portal-lang module. Can you resolve it?

Thanks!

**Comment by robertoDiaz** [comment]
Hey @adolfo, it seems that this rebase error is going to be happen over and over again if the PR review takes more than one day. :(

I fact have resolved it yet a couple of times.

This is why I ask you:

> @liferay-lima could you review the current code and once the review is passed I could fix the conflicts (just removing the last 2 commits and regenerating them)

Anyway, I'm going to fix it and resend, but please review ASAP to avoid this kind of problems!! 😝 

Thanks!!

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @robertoDiaz 
Could you recheck the failure about `com.liferay.redirect.service.test.RedirectNotFoundEntryLocalServiceTest`, I checked the [test history](https://testray.liferay.com/zh/home/-/testray/cases/1518351221), it seems that this error only occured under this PR relevant test.

cc/ @adolfopa

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
