### PR TITLE
LPS-142108 Cannot select document with non-image file in item selector

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
I decides to create a "new" class item-preview-editable to the count of the editable image on the editor (pencil) of the item selector

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
I will need @boton review, because It’s a class issue
I solved it but maybe totally “not right”
it’s because we are using the class item-preview for two totally different things

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
no. I don't like this solution

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
