### PR TITLE
[TECHNICAL SUPPORT] LPS-168994 Users can mention non-site members in Message Boards

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
If an instance is configured that only site members and friends can mention each other, a user who is neither shouldn't be able to be mentioned. Currently, if _Allow Users to Mention Other Users_ is enabled on a Site level, any user can be mentioned.
https://issues.liferay.com/browse/LPS-168994

Proposed Solution
========
I added a filter in `DefaultMentionsUserFinder.getUsers()` that lets users pass only if they are friends with the mentioner OR a member of the current site.
If neither one applies, the user won't be returned by `DefaultMentionsUserFinder.getUsers()`.

**In order to be able to pass groupId, I extended the strategy/finder API.**

Steps to Verify
========
Please see the linked LPS.

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1397401_1827

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
