### PR TITLE
LPS 163065

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
Hi @robertoDiaz A lot of tests failed with the below errors. Could you help to take a look? Thanks.

```[junit] 2022-12-27 15:05:42.877 ERROR [http-nio-8080-exec-2][IncludeTag:128] Current URL /web/guest generates exception: Unable to compile class for JSP: 
    [junit] 
    [junit] An error occurred at line: [540] in the jsp file: [/html/common/themes/top_js.jspf]
    [junit] groupTypeSettings cannot be resolved
    [junit] 537: 		<c:when test='<%= StringUtil.equalsIgnoreCase(analyticsType, "googleAnalytics4") %>'>
    [junit] 538: 
    [junit] 539: 			<%
    [junit] 540: 			String googleAnalytics4Id = groupTypeSettings.getProperty("googleAnalytics4Id");
    [junit] 541: 			%>
    [junit] 542: 
    [junit] 543: 			<c:if test="<%= Validator.isNotNull(googleAnalytics4Id) %>">
    [junit] 
    [junit] 
    [junit] An error occurred at line: [553] in the jsp file: [/html/common/themes/top_js.jspf]
    [junit] groupTypeSettings cannot be resolved
    [junit] 550: 					gtag('config', '<%= HtmlUtil.escapeJS(googleAnalytics4Id) %>');
    [junit] 551: 
    [junit] 552: 					<%
    [junit] 553: 					String googleAnalytics4CustomConfiguration = groupTypeSettings.getProperty("googleAnalytics4CustomConfiguration");
    [junit] 554: 					%>
    [junit] 555: 
    [junit] 556: 					<c:if test="<%= Validator.isNotNull(googleAnalytics4CustomConfiguration) %>">
    [junit] 
    [junit] 
    [junit] Stacktrace:
    [junit] org.apache.jasper.JasperException: Unable to compile class for JSP: 
    [junit] 
    [junit] An error occurred at line: [540] in the jsp file: [/html/common/themes/top_js.jspf]
    [junit] groupTypeSettings cannot be resolved
    [junit] 537: 		<c:when test='<%= StringUtil.equalsIgnoreCase(analyticsType, "googleAnalytics4") %>'>
    [junit] 538: 
    [junit] 539: 			<%
    [junit] 540: 			String googleAnalytics4Id = groupTypeSettings.getProperty("googleAnalytics4Id");
    [junit] 541: 			%>
    [junit] 542: 
    [junit] 543: 			<c:if test="<%= Validator.isNotNull(googleAnalytics4Id) %>">
    [junit] 
    [junit] 
    [junit] An error occurred at line: [553] in the jsp file: [/html/common/themes/top_js.jspf]
    [junit] groupTypeSettings cannot be resolved
    [junit] 550: 					gtag('config', '<%= HtmlUtil.escapeJS(googleAnalytics4Id) %>');
    [junit] 551: 
    [junit] 552: 					<%
    [junit] 553: 					String googleAnalytics4CustomConfiguration = groupTypeSettings.getProperty("googleAnalytics4CustomConfiguration");
    [junit] 554: 					%>
    [junit] 555: 
    [junit] 556: 					<c:if test="<%= Validator.isNotNull(googleAnalytics4CustomConfiguration) %>">
    [junit] ```

**Comment by robertoDiaz** [comment]
Checking that

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
The above failures are not related to this PR, sent it to BChan:https://github.com/brianchandotcom/liferay-portal/pull/128337

**Pull request closed without merging**
