### PR TITLE
LPS-145357

### PR DESCRIPTION
**Pull request by vendeltoreki**
Original: https://github.com/liferay-staging/liferay-portal/pull/33

Hi @liferay-lima ,

I'm forwarding this PR to you. I've checked it from staging perspective and it looks ok to me.

Please review the changes.

cc: @mbowerman , @robertodiaz 

Thanks,
Vendel

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @vendeltoreki 

I think it's better to sent this PR to @liferay-echo to review because it's a WC / pages issue

Thanks!

**Comment by vendeltoreki** [comment]
Thanks @AliciaGarciaGarcia , I'm forwarding through https://github.com/liferay-echo/liferay-portal/pull/7030 .

**Comment by ealonso** [comment]
Hey @AliciaGarciaGarcia @vendeltoreki, it is not Echo, wait a minute.

**Comment by ealonso** [comment]
Hey @vendeltoreki @AliciaGarciaGarcia,

The owner of Dynamic Data Mapping is Data Engine Team, so, you should send the pr to them.

**Comment by vendeltoreki** [comment]
Thanks @ealonso , forwarding to @liferay-data-engine then.
Btw, is there a definitive guide on which code belong to which team? This one seems to be the staging aspect of the web-content/DDM converter.

**Comment by ealonso** [comment]
Hey @vendeltoreki,

Here you have more information about teams https://liferay.atlassian.net/wiki/spaces/PRDDXP/pages/1322191816/DXP+Product+Teams.

In this case, since the code is in a dynamic data mapping module, you should send it to the owner of this module. This code is not affecting only to web content since DDM is a framework and it can be used by other applications like DL and DDL.

Regards,
Eudaldo.

**Pull request closed without merging**
