### PR TITLE
LPS-162225 

### PR DESCRIPTION
**Pull request by mbowerman**
Ticket: https://issues.liferay.com/browse/LPS-162225

Please see my full commit message for a detailed explanation of why I believe this is optimal from a performance perspective.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
a comment failure also failed on other jobs.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The semantic versioning failure is not related to this PR, [LPS-162281](https://issues.liferay.com/browse/LPS-162281).

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @adolfopa 
Tried a few times and always had flaky issues for the forward, so I sent this pull directly to Bchan.

**Pull request closed without merging**
