### PR TITLE
LPS-148887 Use X variant to avoid substring

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-148887 Use an X variant
- LPS-148887 Semver

Changes asked on https://github.com/brianchandotcom/liferay-portal/commit/8dc731f0b8762c0dfaf7977a305c750c56d58ef7

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
the failing test are related to this PR

Fixing the test and resending

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1377401_935

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
