### PR TITLE
LPS-202903 Use the right attribute name

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]

**Review by marcogalluzzi — COMMENTED** [review]
Changes are OK. Just a question, related to the new quality process, should this bug have a functional test?

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
HI @marcogalluzzi 

By now we do not have any test (as most of teams).

From my perspective a customer issue resolution is not the best option to do develop the first one.

cc/ @adolfopa do you agree?

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
