### PR TITLE
[7.4-only] LPS-121960 Migrate v2 usages of clay:vertical-card in depot-web

### PR DESCRIPTION
**Pull request by markocikos**
Followup on:
- https://github.com/liferay-lima/liferay-portal/pull/1102
- https://github.com/liferay-lima/liferay-portal/pull/1118
- https://github.com/liferay-lima/liferay-portal/pull/1129

Before:
before

After:
after

@ambrinchaudhary @carloslancha @julien

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by julien** [comment]
@liferay-lima please review and forward when you get a chance thanks!

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
