### PR TITLE
LPS-130379 Eliminate wildcard usage for the url field and use a different type of query

### PR DESCRIPTION
**Pull request by adolfopa**
Changes to the URL indexer, so that we match prefixes of the URL component instead of using wilcard matching.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
