### PR TITLE
LPS-194893 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-194893

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
@AliciaGarciaGarcia in https://github.com/liferay-lima/liferay-portal/pull/4717/commits/6675b5edbc5548478d7d9b8fe1bf0ae66b864751 I didn't update the key to "site" because "group" seems to be used elsewhere in the code. If it should be updated too please lmk

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
