### PR TITLE
LPS 124334

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by 4lejandrito** [comment]
ci:open

**Comment by 4lejandrito** [comment]
ci:reopen

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1175.

**Pull request closed without merging**
