### PR TITLE
LPS-150652 the input tag url is double encoded, so we need to escape the url to let the user see the xml and the proper value of the url title

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
the input tag url is double encoded, so we need to escape the url to let the user see the xml and the proper value of the url title

The error of shown code is due to try to insert the same bad friendlyURL (<script...) several times, the system show a message of warning that if is a script breaks the portal

Whit the fix it shows as follows

image

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1337401_1582

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
