### PR TITLE
LPS-117661 Provide a library for video previewing with support

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@adolfopa can you please test this in you brand new Linux?
@AliciaGarciaGarcia can you please apply your hardcore testing skills to this?
@austinchiang in order to run the integration tests in CI we need to install [ffmpeg](https://ffmpeg.org/download.html) on the CI boxes. Can you help with that?

**Comment by adolfopa** [comment]
Just started reviewing :)

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by austinchiang** [comment]
See https://issues.liferay.com/browse/LRCI-2121

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @austinchiang,

Can you help me test this in  http://test-5-1/computer/cloud-10-0-11-53? (See [this comment](https://issues.liferay.com/browse/LRCI-2121?focusedCommentId=2408468&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2408468)).

Thanks!

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @austinchiang,

I tried to fix the poshi test in https://github.com/liferay-lima/liferay-portal/pull/1668/commits/bb535323e8868099227b44f207920154d8d8b0de but it is still failing. I get a 404 when trying to open the Poshi report. Can you please help me find out what's going on?

Thanks!

**Comment by austinchiang** [comment]
ci:reevaluate

**Comment by austinchiang** [comment]
ci:reevaluate:c21920c3212fb50f434ad73837f0f47c19c7d95b

**Comment by austinchiang** [comment]
ci:reevaluate:1237401_7600

**Comment by 4lejandrito** [comment]
I'll fix the conflict and resend.

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1703.

**Pull request closed without merging**
