### PR TITLE
LPS-155227

### PR DESCRIPTION
**Pull request by holatuwol**
## Motivation

https://issues.liferay.com/browse/LPS-155227
https://issues.liferay.com/browse/PTR-3104

## Proposed solution

The issue arises because a user subscribes to a parent folder, and then Liferay checks to see if they should receive notifications for a child folder. However, the permission check only checks whether they have still subscribe permissions on the parent folder they'd subscribed to, not whether they have permissions on the child folder.

This solution introduces a new `DLSubscriptionSender` which has a reference to the original folder that we are sending notifications on, which we can then use for permission checks.

In theory, this pattern may be needed on other assets where you can subscribe to a parent asset (message boards being one example), but we are focusing on document library for this one, as we've established that it's not desirable behavior there and we do not know whether it's desirable on other assets.

## Steps to verify

Please see linked LPS.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_2939

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by liuxingye** [comment]
Hi @holatuwol , I've tested the changes locally based on failures from POSHI tests. Could you take a took the following issues?

**Issue1:**
1. Go to documents and media > Type > Add a custom type with the text field
2. Use the custom type to add a document
3. Publish 
4. The actual result is failing to publish the document with NPE in console.

**Issue2:**
1. Go to documents and media 
2. Add a document 
3. The actual result is failing to publish the document with NPE in console.

Thanks.

cc @adolfopa

**Comment by AliciaGarciaGarcia** [comment]
Hi @holatuwol

Did you read this [comment ](https://github.com/liferay-lima/liferay-portal/pull/3183#issuecomment-1169463893)?  

Thanks!

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
Sorry, didn't see the comment until today. The TSE provided an update which changes the check to account for files uploaded to the root folder.

**Comment by adolfopa** [comment]
LGTM. @AliciaGarciaGarcia Can you take a look at the latest changes? If you're ok with this, we can forward it.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
