### PR TITLE
LPS-142110 Add margin to card's widget

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Added space between buttons and card's header, same than with other templates. 
Screenshot 2022-03-25 at 11 42 40

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
unrelated CI error, trying again....

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
