### PR TITLE
LPS-127143

### PR DESCRIPTION
**Pull request by 4lejandrito**
@AliciaGarciaGarcia,

I investigated the issue and I think this is the best we can get without using the session. 

Everything seems to work fine except for the case where the 404 page configured in `layout.friendly.url.page.not.found` doesn't exist. I believe it is acceptable to assume that as a known issue but fix both this issue and https://issues.liferay.com/browse/LPS-127465 which are much more severe.

We can discuss this on Monday though.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
I just pushforced. 

@AliciaGarciaGarcia please test it just in case I missed something.
@allen-ziegenfus can you please verify that this solves all your problems? 

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by allen-ziegenfus** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by allen-ziegenfus** [comment]
@4lejandrito I found a different way to test and it looks like this does solve the issue, thanks!

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
