### PR TITLE
LPS-192388 Message boards: replace font awesome icons

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Before, with font-awesome:** 
Screenshot 2023-08-03 at 19 01 02

**After the changes:**

Screenshot 2023-08-03 at 14 38 22

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Manually forwarding to BChan

**Comment by austinchiang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138874

**Pull request closed without merging**
