### PR TITLE
LPS-131956 There is a import missing on the test

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Integration test compile failure within :apps:document-library:document-library-test (https://issues.liferay.com/browse/LPS-131956)

There is a import missing 

On the @liferay-lima we decided to send this PR independently from the https://github.com/liferay-lima/liferay-portal/pull/1797 cause the other PR is complex and maybe will be need more work than the simple PR.

cc// @javierdearcos

Thanks!

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1017401_6631

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
The failing test seems to be a flaky ones (https://issues.liferay.com/browse/LPS-130617)

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
rebase and commit with a delete of an override not needed

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
