### PR TITLE
LPS-162042 Remove feature flag

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
Don't tested but LGTM

**Comment by boton** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1267401_4807

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
flaky failures, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1357401_2504

**Comment by Hanlf** [comment]
The failure is not related to this PR, also happens on other PR.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures should be flaky issue, not related to this PR.

**Comment by adolfopa** [comment]
Forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/122679

**Pull request closed without merging**
