### PR TITLE
LPS 116786

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@JorgeFerrer I am forwarding this one because I think it is pretty straightforward. Let me know if you have any concerns and we can either stop it or change it tomorrow.

I am now working on the multiline property which I will send directly to you guys since that one will probably require more thought.

Thanks!

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/396.

**Pull request closed without merging**
