### PR TITLE
LPS-171894 Cannot access to documents and media children folders after upgrading from 7.3 or lower to 7.4

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-171894

After some discussions, we have agree here https://liferay.slack.com/archives/CLD39UKM5/p1675244196745199?thread_ts=1672247653.675749&cid=CLD39UKM5 that we have to revert the ACCESS validation added in [LPS-152740](https://issues.liferay.com/browse/LPS-152740)

**So I am reverting:**
 - [LPS-152740](https://issues.liferay.com/browse/LPS-152740) changes where we added the check of the ACCESS permission in DM portlets
 - [LPS-152927](https://issues.liferay.com/browse/LPS-152927) changes where we added the ACCESS permission in some tests
 - [LPS-153082](https://issues.liferay.com/browse/LPS-153082) changes where we added the ACCESS permission in some tests
 - [LPS-152997](https://issues.liferay.com/browse/LPS-152997) new test that tests the LPS-152740 changes
 - Partial revert of [LPS-149366](https://issues.liferay.com/browse/LPS-149366) commit where we add the ACCESS permission in some tests

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_8600

**Comment by jorgediaz-lr** [comment]
ci:reevaluate:1377401_8600

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_8600

**Comment by Hanlf** [comment]
ci:test:document

**Comment by Hanlf** [comment]
No related failures were found from the `ci:test:relevant` and `ci:test:document` suite.

**Review by austinchiang — APPROVED** [review]

**Comment by austinchiang** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The above failures are not related to this PR, sent it to BChan: https://github.com/brianchandotcom/liferay-portal/pull/129723

**Pull request closed without merging**
