### PR TITLE
[TS] LPS-134650 | Alternate URLs don't change when setting a custom canonical URL

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
I modified the alternateURL based on this [PTR](https://issues.liferay.com/browse/PTR-2499) to try to fetch the custom canonicalURLs for the alternateURLS as well if possible. If there is no custom canonicalURL for a language it will use the original alternateURL variant for the given language.

https://issues.liferay.com/browse/LPS-134650
Thank you!

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
Hi @liferay-lima,

I was wondering if you had the opportunity to check this PR. Could you please update me at your convenience?

Best,

Attila

**Comment by AliciaGarciaGarcia** [comment]
Hi @bakayattila 

We will wait till the release to forward PR to master.

Sorry for the inconvenience.

Alicia

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by zsoltbalogh** [comment]
@AliciaGarciaGarcia, do you consider this PR risky? Support requests should go through unless they are very risk, as we would need to deliver these fixes to our customers in time. See https://liferay.slack.com/archives/CL8DNJYB0/p1627331571173800

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
Hi

I talked the team and as it is customer-related and I think that the risk is low, I will forward it to brian.

thanks for all

**Pull request closed without merging**
