### PR TITLE
LPS-126779 & LPS-127645

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
Hi @vicnate5,

I've added a new downloadable file for the tensorflow model (https://github.com/liferay-lima/liferay-portal/pull/1481/commits/abab72a8bc46b737413fa04f5d789ee0503ff163). Is there anything else needed for the tests to properly run?

Thanks!

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by vicnate5** [comment]
@4lejandrito We just need a URL that works both 1)externally and 2)in our LAX office network (for CI).

Change to `https://repository-cdn.liferay.com/nexus/service/local/repositories/public/content/org/tensorflow/libtensorflow_jni/1.15.0/libtensorflow_jni-1.15.0.jar`

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
Thanks @vicnate5. Just updated it.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
