### PR TITLE
LPS-131435 Optimize UrlSubject upgrade process

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @jesseyeh-liferay
> [LPS-131435](https://issues.liferay.com/browse/LPS-131435) improves the performance of the UrlSubject upgrade process by using a `Map` to keep track of the number of previously-seen subjects instead of querying the database for the number of occurrences in each iteration. Local testing showed an average 45% improvement in the time taken to complete the process with these changes.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@SamZiemer Not sure about this. Have you tested how much memory does this consume in relation to the number of rows in MBMessage? If there are no urlSubject conflicts, we'll have one entry in the map per row in the database, which is a bit scary. For customers with too much data in the MBMessage table, it may not be possible to finish the upgrade without buying more ram.

**Comment by SamZiemer** [comment]
Hi @adolfopa, @jesseyeh-liferay is currently looking into your questions and will update the PR soon.

**Comment by jesseyeh-liferay** [comment]
Hi, @adolfopa. Here is a new approach with constant memory usage: https://github.com/jesseyeh-liferay/liferay-portal/commit/ffaea2941730f8df87c8508b3e1319bf0840347d. In it, we sort by subject and messageId, and maintain a count as we iterate over each entry. Local testing with a database containing 15k messages showed an average 37% improvement compared to the current implementation in master. Would this approach be acceptable?

**Comment by adolfopa** [comment]
The new approach looks great @jesseyeh-liferay :+1:

**Comment by adolfopa** [comment]
@jesseyeh-liferay I'm changing the status of this PR to "Changes requested" until you send your current changes. Let me know if you prefer me to close it.

**Review by adolfopa — CHANGES_REQUESTED** [review]
Waiting for the changes in https://github.com/liferay/liferay-portal/compare/master...jesseyeh-liferay:LPS-131435-2

**Comment by jesseyeh-liferay** [comment]
@adolfopa This PR can be closed. New changes sent here: https://github.com/liferay-lima/liferay-portal/pull/1790

**Pull request closed without merging**
