### PR TITLE
LPS-132332 Create and update updateFileEntry methods on repository and dlAppService

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
On this PR we update the methods with the new fields expirationDate and ReviewDate

As requested, instead of follow the same ticket (https://issues.liferay.com/browse/LPS-122267), I created a new one https://issues.liferay.com/browse/LPS-132332 only for this.

It's pararell to the https://github.com/brianchandotcom/liferay-portal/pull/101846 till it pass, I made rebase (on local) and nothing was needed to merge)

As the last PR I changed all (or that was my intention) the calls for the deprecated methods.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Not doing the forward in case there are conflicts. I'll let you handle that.

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa I tested with the pending PR rebasing it... So...
WISH ME LUCK!

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
Test failing because update values on test is not good idea when you are making a update of null values...

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
ContentPagesWithInlineContent#EditInlineContentOfTextFragment failure should be a test fix, asked Echo team to take a look at it: [LPS-132379](https://issues.liferay.com/browse/LPS-132379).
Rerun it to check the failures about modules-integration-mysql57-jdk8/0.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
