### PR TITLE
LPS-117693

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @liferay-lima 

I'm not sure if we could consider this as a bug or a customization. (I tend to think that it's not a bug)

Anyway, could you double check it??

cc/ @linolaoj

**Comment by 4lejandrito** [comment]
Hi @robertoDiaz @linolaoj,

Wouldn't it be simpler to allow styles for any element? According to the [CKEditor Docs](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_allowed_content_rules.html#string-format) we can do that just by adding:

```java
sb.append("*{*};");
```

With that line we allow all the styles in all the elements (but not the elements themselves).

If we do that it would be more future proof because we are only enabling it for specific elements now. I tested it locally and it seems to work fine.

What do you think?

**Comment by linolaoj** [comment]
Hi @4lejandrito,
Yes, it looks better. Should I send a new pull with this change?
Thanks!

**Comment by robertoDiaz** [comment]
Hi @linolaoj 

I've agreed with @4lejandrito that this could not be considered as a bug but as an improvement, so it has to be validated by the team, and it's possible that even in the case that we add this to the master branch, we do not backport it

In order to provide a solution to customers, can you create a new fast-track in the help center to explain how customers could customize this??

Thanks!!

**Comment by linolaoj** [comment]
Hi @robertoDiaz,
ok, thank you for the update. I'll inform the CSE that we need a fast-track for it, and provide the necessary information.

**Comment by 4lejandrito** [comment]
We will discuss this internally with UX and Product and create a new story if necessary. 

Closing for now. 

Thanks!

**Pull request closed without merging**
