### PR TITLE
PR-3422

### PR DESCRIPTION
**Pull request by yasuflatland-lf**
@adolfopa I couldn't figure out the cause of language key issues. Can I push this PR as it is as of now?

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@yasuflatland-lf Yes, I'm ok with the changes as is. But first, can you squash the SF/fix/fix changes together?

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
