### PR TITLE
LPS-166147  Fix test after  LPS-161174 

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-165147 fix test

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:message-board

**Comment by AliciaGarciaGarcia** [comment]
ci:test:message-boards

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
