### PR TITLE
LPS-115140 Change section name

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
Hey @ambrinchaudhary the tests [are failing](https://testray.liferay.com/reports/production/logs/test-1-17/1591788968254/test-portal-acceptance-pullrequest(master)/5993/functional-tomcat90-mysql57-jdk8/1/0/LocalFile.DocumentsadministrationUsecase_AddDocumentTypeAndMetadata/index.html.gz) because now both name fields are gone. I've confirmed locally.

dm

Can you please take a look?

**Comment by ambrinchaudhary** [comment]
Thanks @austinchiang, I'll check again. It shouldn't have been removed form that form... point for poshi! ;-)

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/216

**Pull request closed without merging**
