### PR TITLE
LPS-157472, LPS-157473, LPS-157472 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-157473
https://issues.liferay.com/browse/LPS-157472
https://issues.liferay.com/browse/LPS-157474

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
