### PR TITLE
LPS-119280 SF - Sort methods

### PR DESCRIPTION
**Pull request by boton**
follow up brianchandotcom#92908.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
@boton shouldn't this go to liferay-frontend?

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:forward

**Review by ambrinchaudhary — APPROVED** [review]

**Pull request closed without merging**
