### PR TITLE
LPS-147044 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-147044

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test

**Comment by Hanlf** [comment]
@austinchiang fyi, there was some web content failure upstream before, see https://github.com/liferay-lima/liferay-portal/pull/2712#issuecomment-1034375089 for details, in case of duplication work for it.

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:reevaluate:1277401_1766

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1257401_1690

**Comment by adolfopa** [comment]
ci:reevaluate:1257401_1690

**Comment by liuxingye** [comment]
Trying to send a new pull to avoid the conflict.

**Comment by liuxingye** [comment]
see https://github.com/liferay-lima/liferay-portal/pull/2752

**Pull request closed without merging**
