### PR TITLE
LPS-172556 KB View Template: more actions dropdown

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
See issue https://issues.liferay.com/browse/LPS-172556.
Enable FF
`feature.flag.LPS-166643=true `

Notes for the review: 

1. For some reason the new delete option throws a null pointer exception. It is the same action that from other dropdowns (from the navigation pane or each search container row), but my guess is that it has to do with this [conditional](https://github.com/liferay/liferay-portal/blob/6293b25e091b558eac6d8c921132b62b418b12b1/modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/util/KBDropdownItemsProvider.java#L536). I need a hand here from any back to debug and fix this. 
2. I removed the option "Use this template". It was redirecting to the edit template. 

**After the changes:** 
Screenshot 2023-01-11 at 22 41 20

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
Please do not forward this yet, I need someone to take a look to 

>  delete option throws a null pointer exception

Thanks!

**Comment by ambrinchaudhary** [comment]
Pending to fix the issue with the delete option

**Comment by AliciaGarciaGarcia** [comment]
please see https://github.com/liferay-lima/liferay-portal/pull/3911

**Pull request closed without merging**
