### PR TITLE
LPS-148380 remove ff bulk translation

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-148380

- [x] [LPS-145209](https://issues.liferay.com/browse/LPS-145209) Multiple translation import (frontend)
- [x] Removed on translation
- [x] Removed on journal
- [x] Removed on layout

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
> ?? [LPS-142736](https://issues.liferay.com/browse/LPS-142736) Allow exporting all/default experiences of pages (I'm not sure @ambrinchaudhary if it is considered inside bulk translations or apart with the new FF)

Better ask @adolfopa, I think he merged two features inside one feature flag...?

**Comment by adolfopa** [comment]
@boton @ambrinchaudhary We should keep the default/all ff around for a bit longer, as that depends on changes that haven't been merged yet. But you can remove the other three ones freely.

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by boton** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@austinchiang Can you guys take a look and update the tests to remove the FF?

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/2909

**Pull request closed without merging**
