### PR TITLE
LPS-155869 DM set icons in PortletIcons

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
https://issues.liferay.com/browse/LPS-155869

Not under a feature flag because some of this portlet icons had icons before, and in the original epic we were settings icons in the dropdowns. 

Also not that there are more icons than described in the issue (access a folder to see them). I haven't tested the sharepoint repository but I hope these actions are already covered here. 

Screenshot 2022-06-14 at 11 59 28

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
If no need of icon on Home Folder Permission LGTM

image

**Comment by ambrinchaudhary** [comment]
> If no need of icon on Home Folder Permission LGTM

Added!!! thanks for testing it.

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Poshi error seems related but these changes shouldn't affect the toolbar icons, and I've just checked in local and works fine for me (paginated, select All and click move icon from the management toolbar)

Running ci:test:relevant again and if it fails again, I may need guidance from QA...

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
See the new pull request: https://github.com/liferay-lima/liferay-portal/pull/3160

**Pull request closed without merging**
