### PR TITLE
LPS-198676 Renamed feature flag

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Renamed feature flag LPS-188060 (story) to LPS-188058 (epic)

See https://liferay.atlassian.net/browse/LPS-198676

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]
Thank you for this @marcogalluzzi!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
