### PR TITLE
LPS-140965 Share Modal has extra bottom space in the footer

### PR DESCRIPTION
**Pull request by MrJohn1911**
Issue: https://issues.liferay.com/browse/LPS-140965

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by boton** [comment]
Hi @MrJohn1911, thanks for your contribution!

Your solution fix the current UI. 
Sadly if we need to add more content in that modal, like a new option or text the height change. 
The modal will show double scroll bars.

image

Sorry 🙏 , I prefer to give you feedback and guide you to the proper solution but tomorrow I will be some days on PTO and prefer to do it before leaving.

I create a new PR #3279 with another solution based on the Manage Collaborators modal.
With the new PR, if you need more space for the content, one scrollbar for the `modal-body` will show but not double.

image

**Comment by MrJohn1911** [comment]
> Hi @MrJohn1911, thanks for your contribution!
> 
> Your solution fix the current UI. Sadly if we need to add more content in that modal, like a new option or text the height change. The modal will show double scroll bars.
> 
> image
> 
> Sorry pray , I prefer to give you feedback and guide you to the proper solution but tomorrow I will be some days on PTO and prefer to do it before leaving.
> 
> I create a new PR #3279 with another solution based on the Manage Collaborators modal. With the new PR, if you need more space for the content, one scrollbar for the `modal-body` will show but not double.
> 
> image

Hi @boton, I didn't notice that was possible to add more content, so I did this simple change, so thanks for the help! 😀

**Pull request closed without merging**
