### PR TITLE
LPS-195228 Move property to company scope settings to make it LXC friendly

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@robertoDiaz There's some overlap with https://github.com/liferay-lima/liferay-portal/pull/4653. Instead of creating a new company configuration for this, why not follow the same approach and reuse the group level configuration? I think this will keep things easier for both us and the customers (and as a bonus, different sites will be able to customize this as well).

**Comment by robertoDiaz** [comment]
Sure!

I'll also check this PR and follow the same steps as you did (the upgrade and everything).

**Comment by robertoDiaz** [comment]
I'll resend once https://github.com/liferay-lima/liferay-portal/pull/4653 is merged in master

**Pull request closed without merging**
