### PR TITLE
LPS-165929 KB order in search container lists

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-165929
Changed order for folders, articles, templates and suggestions. 

**Before:** 
Screenshot 2022-10-19 at 11 16 27

**After:** 
Screenshot 2022-10-19 at 12 01 38

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:knowledge-base

**Comment by ambrinchaudhary** [comment]
Not sure if errors are related to this pull, could be but poshi error messages don't give me any clue. Could you @qa-lima please help me?

**Comment by ambrinchaudhary** [comment]
Thanks a lot @Hanlf. Then I guess I can forward this pull and the poshi test failing will be fixed with the bug you opened.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
