### PR TITLE
LPS-191730, LPS-191731 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-191730

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:lima-upgrade

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:lima-upgrade

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:test:lima-upgrade

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138869

**Pull request closed without merging**
