### PR TITLE
LPS-182299 Sharepoint connection problems

### PR DESCRIPTION
**Pull request by marcogalluzzi**
This fix should solve some connection problems like:

* https://liferay.atlassian.net/browse/LPS-182299
* https://liferay.atlassian.net/browse/LPS-158050

What I've found after deep research is that Axis2 doesn't seem to support Preemptive Authentication (see this [search](https://github.com/search?q=repo%3Aapache%2Faxis-axis2-java-core%20preemptive&type=code) on Github repo) because of security concerns. So, even if we set the authentication to be Preemptive this option is ignored. This means that a retry mechanism is needed because the first attempt to connect to the server will respond with the authentication methods supported, and only after that, repeating the request would work.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:reevaluate:1307401_7452

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
> [exec] * What went wrong:
> [exec] Execution failed for task ':runPoshi'.
> [exec] > There were failing tests. See the report at: file:///opt/dev/projects/github/liferay-portal/portal-web/tests/index.html

Hi QA team, do you know why are we having errors with the Sharepoint testing? Is it related to specific Sharepoint tests or to the CI infrastructure?

**Comment by Jeremy-Ch** [comment]
Hi @marcogalluzzi I have checked the failures. Looks like the error still appears when adding SharePoint. Could you help to take a look? Or we can forward this change first. Thanks. image

**Comment by marcogalluzzi** [comment]
Hi @Jeremy-Ch this PR at least fix a connection problem I experienced so I would forward it. Meanwhile I will continue working on other SharePoint failures.

**Pull request closed without merging**
