### PR TITLE
LPS-164218 User is not notified when subscribing to KB

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-164218 add NotificationHandler for Knowledge base
- LPS-164218 add the className and classPK to the subscriptionSender
- LPS-164218 add KBAddEntryUserNotificationDefinition and KBUpdateEntryUserNotificationDefinition
- LPS-164218 buildLang
- LPS-164218 add notification type to the subscriber
- LPS-164218 obtain the entryURL to go to the article when selected on the notification
- LPS-164218 extract method

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant (Sorry, I had to abort the previous test before it started)

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
