### PR TITLE
LPS-145948 Use the theme display if possible to get the port and server data from theme display and avoid getting it from _portalServerInetSocketAddress (since it depends on the first server call)

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@robertoDiaz Can you fix the LPS number? It's causing an SF error (push force the change into this pr).

**Comment by adolfopa** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
