### PR TITLE
LPS-191375

### PR DESCRIPTION
**Pull request by manuelRives**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
Hi @manuelRives I'm not sure why this PR keeps running the SF command. And it's not allowed to run a new SF. Could you help to take a look? Thanks.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
source-format is failing and unable to update this pull request/
It looks like there is a merge conflict with upstream.

```
[beanshell] Executing commands: git rebase master master-temp-1692917872725
[beanshell] Executing commands: git rebase --abort
[beanshell] com.liferay.jenkins.results.parser.GitWorkingDirectory$GitWorkingDirectoryRuntimeException: Runtime exception  occurred in liferay-portal
[beanshell] Unable to rebase master-temp-1692917872725 to master
[beanshell] Rebasing (1/2)
[beanshell] error: could not apply 5fd136cec3ef... LPS-191375 SF
[beanshell] Resolve all conflicts manually, mark them as resolved with
[beanshell] "git add/rm <conflicted_files>", then run "git rebase --continue".
[beanshell] You can instead skip this commit: run "git rebase --skip".
[beanshell] To abort and get back to the state before "git rebase", run "git rebase --abort".
[beanshell] Could not apply 5fd136cec3ef... LPS-191375 SF
```

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
Hi @manuelRives can you please rebase your changes with last master and send it again? Thanks

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/4641

@robertoDiaz Some commits were dropped. Can you double check everything is all right?

**Pull request closed without merging**
