### PR TITLE
LPS-128335 - Bulk status bar is partially covered by Management toolbar in bulk actions like Edit Tags / Categories in DM

### PR DESCRIPTION
**Pull request by 4lejandrito**
**[Details, test plan](https://issues.liferay.com/browse/LPS-128335)**

**Before the fix:**
image

**After the fix:**
image

### CODE REVIEW

**Comment by boton** [comment]
@ambrinchaudhary can you please check that I'm not doing something crazy with the status bar? 🙏 

- 8f810be 
- 8f810be

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
@4lejandrito @boton Following the steps described in the Jira ticket I don't see any status bar. Am I missing something?

**Comment by boton** [comment]
@carloslancha I need a bunch of documents and operations add and remove tags to show it

**Comment by boton** [comment]
If you want to inspect the bulk status bar without the real interaction, run `document.querySelector('.bulk-status').classList.toggle('closed')`

**Review by carloslancha — APPROVED** [review]
LGTM

**Comment by boton** [comment]
Updated this master rebased

**Comment by boton** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
> @ambrinchaudhary can you please check that I'm not doing something crazy with the status bar? 🙏
> 
>     * [8f810be](https://github.com/liferay-lima/liferay-portal/commit/8f810be8ac92a249a8c1ff711f8a2d9f60d8c060)
> 
>     * [8f810be](https://github.com/liferay-lima/liferay-portal/commit/8f810be8ac92a249a8c1ff711f8a2d9f60d8c060)

Sorry for my late reply @boton. Anyway, it was not crazy at all, so all good from my side!

**Pull request closed without merging**
