### PR TITLE
LPS-139939 AWS auto translation support

### PR DESCRIPTION
**Pull request by adolfopa**
Hey Brian,

I'll send the removal of Translator.isEnabled in a different PR to avoid conflicts with the Azure one.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia I've converted this to a draft because I forgot to include an additional lang key. Please review as is, and I'll push force that change later (I don't want to abort the current build).

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Changes pushed. I simply added the validation lang key to https://github.com/liferay-lima/liferay-portal/pull/2649/commits/e50eb6813e44c3dbc9149c1e4152f6aa0d7e1da9 and rebuilt lang keys.

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @adolfopa 
There are some rebase errors for this PR, you need to rebase it and retest:
```
Target exception: java.lang.RuntimeException: Unable to rebase master-temp-1642520488834 to master
Rebasing (1/5)
Rebasing (2/5)
Rebasing (3/5)
Rebasing (4/5)
Rebasing (5/5)
error: could not apply dc478a3a09cd... LPS-139939 Build lang
Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply dc478a3a09cd... LPS-139939 Build lang
```

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
