### PR TITLE
LPS-169428 MediaGallery input security bug

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-169428

Apparently search container sets an [input with all the primary keys](https://github.com/ambrinchaudhary/liferay-portal/blame/LPS-169428_MediaGallery_input_security/portal-web/docroot/html/taglib/ui/search_iterator/deprecated/list.jsp#L384-L384). By default, these are the [model](https://github.com/ambrinchaudhary/liferay-portal/blame/LPS-169428_MediaGallery_input_security/util-taglib/src/com/liferay/taglib/ui/SearchContainerRowTag.java#L310-L310) in json format. 

I changed it to set only the id's of the entries shown in the media gallery, so it does not contain any internal info

Screenshot 2023-01-05 at 11 59 55

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @ambrinchaudhary 
There is a Media Gallery issue should be related to this PR, could you please take a look? Thanks!
Steps:
1. Add a Media Gallery to a page
2. Enable 'Show Actions' for the Media Gallery
3. Upload an image
4. Click the vertical ellipsis icon next to the image on the Media Gallery widget
5. Assert that the operation options display
Actual result: the image preview page is open, and no operation options displayed.

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1277401_6439

**Comment by Hanlf** [comment]
Hey @ambrinchaudhary 
Rebuilt a new bundle and retested it, the Media Gallery issue was gone.
And the above functional failures are not related to this PR, from the QA side, it is ready to forward.

**Comment by ambrinchaudhary** [comment]
Thanks a lot @Hanlf, I'm gonna try one more time, if it fails again I will send it manually to Brian.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1387401_5612

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:reevaluate:1387401_5612

**Comment by ambrinchaudhary** [comment]
Manually forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/128539

**Pull request closed without merging**
