### PR TITLE
LPS-162088 Display page friendly url support for kb articles

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1317401_4841

**Comment by Hanlf** [comment]
ci:reevaluate

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Also failed on other runs, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1307401_4492

**Comment by adolfopa** [comment]
Cannot reproduce test failure locally, so it seems to be flaky.

**Comment by adolfopa** [comment]
ci:reevaluate:1307401_4492

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The failure is not related to this PR.

**Comment by adolfopa** [comment]
Forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/122680

**Pull request closed without merging**
