### PR TITLE
LPS-118827 comments remove AUI

### PR DESCRIPTION
**Pull request by boton**
This PR is a follow up of #1986 started by Ambrin,

### Pass the refreshURLData
~~I have passed the refreshURLData through data attr with a JSON in the value 449c5e6  I dislike the result and all portlets rendering a JSON object in the data attribute are awful.~~

~~I think this part can be improved, can you think of a better solution?~~

I add a param in the portlet.js refresh method 8d3a03f to avoid recover the `refreshURLData` outside of AUI.

### Reply Popover
I have created a replay popover component in react, to be able to remove the old one from AUI.
By the way, I have fixed the styles that had been lost, I created a bug for this https://issues.liferay.com/browse/LPS-134941

**Before this PR**
image

**After this PR**
image

### General
I have tried reducing the use of global functions, without redoing all the logic.

I have moved all the inline js that were left.

### Problems

~~Improve the way that refreshURLData is passed to the js~~

---

We have a lot of errors like `Component with id "null" is being registered twice. This can lead to unexpected behaviour in the "Liferay.component" and "Liferay.componentReady" APIs, as well as in the "*:registered" events.`

The `<liferay:component>` produces this code  **`Liferay.component('null',`** :( 

```js
(function() {
    var ViewMessageThread = _liferayCommentTaglib406DiscussionJsViewMessageThread;
    Liferay.component('null', new ViewMessageThread.default({
        "namespace": "_com_liferay_blogs_web_portlet_BlogsPortlet_",
        "index": 1,
        "spritemap": "http:\/\/localhost:8080\/o\/classic-theme\/images\/clay\/icons.svg",
        "randomNamespace": "jqae_"
    }), {
        destroyOnNavigate: true,
        portletId: 'com_liferay_blogs_web_portlet_BlogsPortlet'
    });
}
)();
```
---

~~I'm not sure if the b45d293 works as expected because doesn't work in master.~~ talked with @ambrinchaudhary

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
@liferay-frontend I add a param in `Liferay.Portlet.refresh` adding the possibility of merge the new data with the current `refreshURLData`.

Do you see any problem with this? 

More context in the description
> ### Pass the refreshURLData
> ~I have passed the refreshURLData through data attr with a JSON in the value [449c5e6](https://github.com/liferay-lima/liferay-portal/commit/449c5e6ea3d48842085a9b139bd36e438c15a39f) I dislike the result and all portlets rendering a JSON object in the data attribute are awful.~
> 
> ~I think this part can be improved, can you think of a better solution?~
> 
> I add a param in the portlet.js refresh method [8d3a03f](https://github.com/liferay-lima/liferay-portal/commit/8d3a03fd95916171091e4cc770ca88de3ac65689) to avoid recover the `refreshURLData` outside of AUI.
>

**Comment by boton** [comment]
@edalgrin I update some styles of `frontend-css-web` in https://github.com/liferay-lima/liferay-portal/blob/1ba37e40f79ff42388f901b56787f7da203a2a3d/modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/taglib/_discussion.scss

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by edalgrin** [comment]
> @edalgrin I update some styles of `frontend-css-web` in https://github.com/liferay-lima/liferay-portal/blob/1ba37e40f79ff42388f901b56787f7da203a2a3d/modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/taglib/_discussion.scss

Don't worry about it, it seems a small change so it will be easy to include it in our PR 👍

**Comment by boton** [comment]
> > @edalgrin I update some styles of `frontend-css-web` in https://github.com/liferay-lima/liferay-portal/blob/1ba37e40f79ff42388f901b56787f7da203a2a3d/modules/apps/frontend-css/frontend-css-web/src/main/resources/META-INF/resources/taglib/_discussion.scss
> 
> Don't worry about it, it seems a small change so it will be easy to include it in our PR 👍

@edalgrin Thanks for checking it out.

**Review by ambrinchaudhary — APPROVED** [review]

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
@boton There are some SF issues. Can you take a look?

**Comment by boton** [comment]
> @boton There are some SF issues. Can you take a look?

Yep for sure

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
