### PR TITLE
LPD-15353 Bring back `DLStore.deleteFile` method

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPD-15353

Some usages of the `DLStore.deleteDirectory` method assume behavior that is not satisfied by the advanced file system store. This causes deletion to leave orphaned files in the file system.

# How am I fixing it?

By bringing back the old `DLStore.deleteFile` method.

# How can I verify that it works?

Automated tests are included in this same PR.

Additionaly, you may follow the manual steps described in https://liferay.atlassian.net/browse/LPD-15353.

### CODE REVIEW

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
@adolfopa [test-portal-acceptance-pullrequest(master)](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/5236/) seems related:

```
     [exec] /opt/dev/projects/github/liferay-portal/modules/dxp/apps/antivirus/antivirus-async-store/src/main/java/com/liferay/antivirus/async/store/internal/AntivirusAsyncDLStore.java:170: error: cannot find symbol
     [exec]     validate(fileName, false);

```

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:report:2531385397

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by robertoDiaz** [comment]
ci:close

**Comment by robertoDiaz** [comment]
Closed in favour of https://github.com/liferay-lima/liferay-portal/pull/5097

**Pull request closed without merging**
