### PR TITLE
LPS-154171  DM drag and drop uploader frozen if image not compatible with database

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-154171 default error on the upload response when failure
- LPS-154171 if is drag and drop send to the multipleUploadResponseHandler.onFailure for each exception

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
