### PR TITLE
LPS-195246 Remove feature flag

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-195246

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:lima

**Comment by WYZ-Issac** [comment]
Failures are unrelated. Forward directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
