### PR TITLE
LPS-133688 Do not escape title in the card views

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Issue**: on card's view the title was escaped. Not happening in table or list view. 

**Before the fix:** 

Screenshot 2021-06-15 at 13 34 50

**After the fix:**

Screenshot 2021-06-15 at 13 36 52

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Review by AliciaGarciaGarcia — APPROVED** [review]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
