### PR TITLE
LPS-199214 validate file size when copying files to show error

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-199214 get the messages from the upload exception to show the user a proper message
- LPS-199214 validate file size when coping files

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
