### PR TITLE
LPS-168389, LPS-168393, LPS-168422, LPS-168423 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-168389
https://issues.liferay.com/browse/LPS-168393
https://issues.liferay.com/browse/LPS-168422
https://issues.liferay.com/browse/LPS-168423

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:document

**Comment by Hanlf** [comment]
The above failures are not related to my PR.

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
