### PR TITLE
LPS-154977 DM Extension's filter

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Previous reviewed pull: https://github.com/liferay-lima/liferay-portal/pull/4068 

Once tests passes send this to Tango team.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
Sent to Tango: https://github.com/liferay-tango/liferay-portal/pull/3317

**Pull request closed without merging**
