### PR TITLE
[TS] LPP-46307 > LPS-161706 Allows users to view redirectEntries they have View permission

### PR DESCRIPTION
**Pull request by chileces**
Dear Team,

Our customer reported an issue related to permission of Power user at ticket https://issues.liferay.com/browse/LPS-161706
This PR is to fix that issue, please help review this PR and leave me your comments.
Solution:
Implement an extended class of PortalInstanceLifeCycleListener to register new permission for the Power User site.
similar function:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/application-list/application-list-my-account-permissions/src/main/java/com/liferay/application/list/my/account/permissions/internal/instance/lifecycle/PanelAppPermissionsPortalInstanceLifecycleListener.java

best regards,
cc:@tototrinh
Previous PR:
https://github.com/liferay-core-infra/liferay-portal/pull/1575

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@chileces Maybe I'm missing something, but this only changes the permissions in the personal site of the default user. Wouldn't it be better to change the RedirectEntryModelResourcePermission to check if a user is the owner of the site? Also, even if your current approach would be correct, an upgrade process would be required to update already existing personal sites.

**Comment by tototrinh** [comment]
Hi @adolfopa,
Thanks for your time on this PR.
As discussion on [PTR-3295](https://issues.liferay.com/browse/PTR-3295?focusedCommentId=2748289&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2748289), adding view RedirectEntry permission for Power User on the User Personal Site is preferred.
I am not sure we should change the RedirectEntryModelResourcePermission to check if a user is the owner of the site:
- This is the current logic on [RedirectEntryServiceImpl.java](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/redirect/redirect-service/src/main/java/com/liferay/redirect/service/impl/RedirectEntryServiceImpl.java#L105-L139).
- I tried using RedirectEntryModelResourcePermission to check the View permission of Redirect Entry. However, it may introduce a performance issue since I have to fetch all entries to be able to return a correct list. ([my previous solution](https://issues.liferay.com/browse/LPS-161706?focusedCommentId=2753244&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2753244)).
Could I continue this approach and add an upgrade process?
Thanks,
To

**Comment by tototrinh** [comment]
Hi @adolfopa,

> Are you sure changing the default user will somehow propagate to other users?

I'm not sure If I get what you mean. This change only solves the issue for the Power User role. So that means users who are Power User holders are able to access the Redirection dashboard on their personal site. As far as I know, Power User is the only regular role that can access Site Setting on their personal sites except for Portal Administrator.

btw, the title doesn't exactly describe the solution. Sorry if it confused you.
Thanks.

**Comment by adolfopa** [comment]
Hey @tototrinh ,
I'm asking about this piece of code:
```
private void _initUserPersonalSitePermissions(long companyId)
		throws Exception {

		Role powerUserRole = _roleLocalService.fetchRole(
			companyId, RoleConstants.POWER_USER);

		if (powerUserRole == null) {
			return;
		}

		Group userPersonalSiteGroup =
			_groupLocalService.fetchUserPersonalSiteGroup(companyId);

		if (userPersonalSiteGroup == null) {
			return;
		}

		long userPersonalSiteGroupId = userPersonalSiteGroup.getGroupId();

		_addResourcePermission(
			companyId, RedirectEntry.class.getName(),
			ResourceConstants.SCOPE_GROUP,
			String.valueOf(userPersonalSiteGroupId), powerUserRole.getRoleId(),
			ActionKeys.VIEW);
	}
```
You're adding the permissions to the default user's site (that's the value returned by _groupLocalService.fetchUserPersonalSiteGroup(companyId)). How does this solve the problem for other power users?

**Comment by tototrinh** [comment]
Hi @adolfopa 
There is the result when creating a new Portal Instance after applying the change
image

**Comment by adolfopa** [comment]
Thanks for the info @tototrinh.
We can proceed with this solution + an upgrade process to update existing instances.
Thanks!

**Comment by tototrinh** [comment]
Of course, I will add an upgrade process and resend PR. Thanks.

**Comment by tototrinh** [comment]
Hi @adolfopa,
I double-checked and saw that this change solved the issue for the existing instances as well. No need to create an upgrade process.
Thanks.

**Pull request closed without merging**
