### PR TITLE
[TS] LPS-156003 Uploaded document is lost after changing Document Type in Documents and Media

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

Previous PR: https://github.com/liferay-lima/liferay-portal/pull/3306

I modified the solution with the requested changes, as Orsolya went onto a sick leave.
I tested the fix and the message is only displayed, when there was an uploaded document in the field before we changed the doctype.

Please review the changes.

Thanks,

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by toomanycurls** [comment]
Wording is great -- Thanks!

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by boton** [comment]
@NemethNorbert we will put this PR on hold, we found different scenarios, we are talking internally about this  @robertoDiaz is involved :D

**Comment by balazssk** [comment]
Hi @boton ,
Can you please share any updates on this?
Thanks

**Comment by boton** [comment]
@balazssk sorry about the delay, after talking with the team we decide that it's better to show a prompt before the errors happen instead of informing that the error occurs.

Ideally we can ask for confirmation before `function <portlet:namespace />changeFileEntryType`. 

The only thing missing is the text for the confirmation prompt, I will put the copy here as soon we have it.

/ cc @robertoDiaz

**Comment by balazssk** [comment]
cheers @boton

**Comment by robertoDiaz** [comment]
Following the internal documentation message could be:

> Changing the document type will cause data loss and it won't be possible to recover it. Are you sure you want to change the document type?

cc/ @boton

**Comment by boton** [comment]
Hi @balazssk, 

can I close this PR and reimplement it on a new one?

With a prompt warning to the user

> Ideally we can ask for confirmation before submit and data manipulation on function <portlet:namespace />changeFileEntryType.

and the next message

> Changing the document type will cause data loss and it won't be possible to recover it. Are you sure you want to change the document type?

Thank you so much for your attention and participation.

/cc @NemethNorbert @orsolyaDekany

**Comment by balazssk** [comment]
Hi @boton 
Thank you for your help.
Yes, I think creating a new PR would be the best course of action here. @orsolyaDekany or @NemethNorbert will monitor it during the next week.

**Comment by boton** [comment]
I closed it and updated the ticket to preserve the conclusions. 
Thanks to all.

**Pull request closed without merging**
