### PR TITLE
LPS-156639 Add lenient store wrapper

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1307401_3611

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1387401_1744

**Comment by liuxingye** [comment]
ci:forward

**Comment by austinchiang** [comment]
@adolfopa Unrelated; this was happening before in https://issues.liferay.com/browse/LPS-150714. I'll send it to BChan

**Comment by austinchiang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/119484

**Pull request closed without merging**
