### PR TITLE
LPS-135864 Refactor translation export from modal to JSP

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom PortletURLBuilder doesn't directly support resource urls (ResourceURL doesn't implement PortletURL), so I've been conservative with the change. Fixing PortletURLBuilder will require some refactor, and I'm not sure if we want to do that now due to the release.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1297401_378

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
