### PR TITLE
[TS] LPS-159458-2

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

Previous PR: https://github.com/liferay-lima/liferay-portal/pull/3320

/cc @AliciaGarciaGarcia 

As suggested, this PR no longer includes the Read more link for the tooltip message.

I'll include updated notes below.

Please let me know if you have any questions.
Thanks!

**Notes**
https://issues.liferay.com/browse/LPS-159458

The goal of this PR is to restore the **'Read more'** link that was removed by [LPS-138008](https://issues.liferay.com/browse/LPS-138008).

**Changes**

- Restore **'Read more'** link that was removed by [LPS-138008](https://issues.liferay.com/browse/LPS-138008)
  - Looking at the ticket description in [LPS-138008](https://issues.liferay.com/browse/LPS-138008), the goal was to only remove the **'patch'** link, not the **'Read more'** link
- Update link to use **Liferay Learn** article instead of **Help Center** article
- Do not include **'Read more'** link for the tooltip message (since we found out it's not clickable)

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1307401_4010

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1267401_4282

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
