### PR TITLE
LPS-123898

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by 4lejandrito** [comment]
Hi @adolfopa can you review, specially https://github.com/liferay-lima/liferay-portal/pull/1112/commits/ee355837689c23a07aa0fb859fb3a8e392460b25 and https://github.com/liferay-lima/liferay-portal/pull/1112/commits/f0d86e9e2e4f5330f1cb506b1d8259dc437552ad for the way I am using custom thumbnail URLs.

Thanks!

**Comment by adolfopa** [comment]
@4lejandrito I think it is ok to send this as is. But I think we should create a proper extension point (maybe create a spike for this?). But that can wait until this is done.

**Review by adolfopa — APPROVED** [review]

**Comment by 4lejandrito** [comment]
Ok I'll add it to my todo list. Thanks!

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
