### PR TITLE
LPS-202246 Deleted KB objects are shown on KB Display widget

### PR DESCRIPTION
**Pull request by marcogalluzzi**
### The following has been fixed

Widget KB Display shows deleted articles:

* On the left navigator, when there is at least one valid article.
* On the next and previous links of an article (siblings)

Commits from previous approved PRs are needed to completely check fix: #4926 #4930 

See: https://liferay.atlassian.net/browse/LPS-202246

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
The versioning error is not related to my changes. I suppose it has been introduced into master inadvertently

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
Hi @marcogalluzzi,

There is a unique failure on this pull request. The failure was not found on head.
[service-builder-jdk8](https://testray.liferay.com/home/-/testray/case_results/2463414558)
[Jenkins Console](https://testray.liferay.com/reports/production/logs/2023-11/test-1-29/test-portal-acceptance-pullrequest(master)/8725/service-builder-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
[History](https://testray.liferay.com/home/-/testray/cases/1325412853)
```
  [exec] A fine-grained performance profile is available: use the --scan option.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/build.services.output.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/build.services.diff.txt
     [echo] diff --git a/modules/apps/knowledge-base/knowledge-base-api/src/main/java/com/liferay/knowledge/base/service/persistence/KBArticlePersistence.java b/modules/apps/knowledge-base/knowledge-base-api/src/main/java/com/liferay/knowledge/base/service/persistence/KBArticlePersistence.java
     [echo] index 84f8d93c3fc9f..2604983f2d56b 100644
     [echo] --- a/modules/apps/knowledge-base/knowledge-base-api/src/main/java/com/liferay/knowledge/base/service/persistence/KBArticlePersistence.java
     [echo] +++ b/modules/apps/knowledge-base/knowledge-base-api/src/main/java/com/liferay/knowledge/base/service/persistence/KBArticlePersistence.java
     [echo] @@ -5804,19 +5804,18 @@ public interface KBArticlePersistence
     [echo]  		long groupId, long[] parentResourcePrimKeys, boolean main);
     [echo]  
     [echo]  	/**
     [echo] -	 * Returns all the kb articles where groupId = &#63; and parentResourcePrimKey = &#63; and main = &#63; and status &ne; &#63;.
     [echo] +	 * Returns all the kb articles where groupId = &#63; and parentResourcePrimKey = &#63; and status = &#63;.
     [echo]  	 *
     [echo]  	 * @param groupId the group ID
     [echo]  	 * @param parentResourcePrimKey the parent resource prim key
     [echo] -	 * @param main the main
     [echo]  	 * @param status the status
     [echo]  	 * @return the matching kb articles
     [echo]  	 */
     [echo] -	public java.util.List<KBArticle> findByG_P_M_NotS(
     [echo] -		long groupId, long parentResourcePrimKey, boolean main, int status);
     [echo] +	public java.util.List<KBArticle> findByG_P_S(
     [echo] +		long groupId, long parentResourcePrimKey, int status);
     [echo]  
     [echo]  	/**
     [echo] -	 * Returns a range of all the kb articles where groupId = &#63; and parentResourcePrimKey = &#63; and main = &#63; and status &ne; &#63;.
     [echo] +	 * Returns a range of all the kb articles where groupId = &#63; and parentResourcePrimKey = &#63; and status = &#63;.
     [echo]  	 *
     [echo]  	 * <p>
     [echo]  	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>KBArticleModelImpl</code>.
     [echo] @@ -5824,18 +5823,17 @@ public interface KBArticlePersistence
```
```
[exec] > Task :apps:layout:layout-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.layout.converter                       MINOR      1.0.0      1.0.0      1.1.0      VERSION INCREASE REQUIRED
     [exec] 	+   class      com.liferay.layout.converter.ConditionTypeConverter
     [exec] 		+   field      externalToInternalValuesMap
     [exec] 			+   access     final
     [exec] 			+   access     static
     [exec] 			+   return     java.util.Map
     [exec] 		+   method     <init>()
     [exec] 			+   return     void
     [exec] 		+   method     clone()
     [exec] 			+   access     protected
     [exec] 			+   return     java.lang.Object
     [exec] 		+   method     convertToExternalValue(java.lang.String)
     [exec] 			+   access     static
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     convertToInternalValue(java.lang.String)
     [exec] 			+   access     static
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     equals(java.lang.Object)
     [exec] 			+   return     boolean
     [exec] 		+   method     finalize()
     [exec] 			+   access     protected
     [exec] 			+   return     void
     [exec] 		+   method     hashCode()
     [exec] 			+   return     int
     [exec] 		+   method     toString()
     [exec] 			+   return     java.lang.String
     [exec] * com.liferay.layout.util.structure                  MAJOR      10.5.0     10.5.0     11.0.0     VERSION INCREASE REQUIRED
     [exec] 	<   class      com.liferay.layout.util.structure.CollectionItemLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.CollectionStyledLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.ColumnLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.ContainerStyledLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.DropZoneLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.FormStyledLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.FragmentDropZoneLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.FragmentStyledLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 	>   class      com.liferay.layout.util.structure.LayoutStructure
     [exec] 		+   method     addCollectionItemLayoutStructureItem(java.lang.String,java.lang.String,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addCollectionStyledLayoutStructureItem(java.lang.String,java.lang.String,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addCollectionStyledLayoutStructureItem(java.lang.String,java.lang.String,java.lang.String,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addColumnLayoutStructureItem(java.lang.String,java.lang.String,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addContainerStyledLayoutStructureItem(java.lang.String,java.lang.String,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addDropZoneLayoutStructureItem(java.lang.String,java.lang.String,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addFormStyledLayoutStructureItem(java.lang.String,java.lang.String,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addFragmentDropZoneLayoutStructureItem(java.lang.String,java.lang.String,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addFragmentStyledLayoutStructureItem(long,java.lang.String,java.lang.String,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addLayoutStructureItem(java.lang.String,java.lang.String,java.lang.String,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addRootLayoutStructureItem(java.lang.String)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     addRowStyledLayoutStructureItem(java.lang.String,java.lang.String,int,int)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     updateLayoutStructureRule(com.liferay.portal.kernel.json.JSONArray,com.liferay.portal.kernel.json.JSONArray,java.lang.String,java.lang.String,java.lang.String)
     [exec] 			+   return     com.liferay.layout.util.structure.LayoutStructureRule
     [exec] 		-   method     updateLayoutStructureRule(java.lang.String,java.lang.String)
     [exec] 			-   return     com.liferay.layout.util.structure.LayoutStructureRule
     [exec] 	<   class      com.liferay.layout.util.structure.LayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.LayoutStructureRule
     [exec] 		+   method     <init>(com.liferay.portal.kernel.json.JSONArray,com.liferay.portal.kernel.json.JSONArray,java.lang.String,java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 		+   method     getActionsJSONArray()
     [exec] 			+   return     com.liferay.portal.kernel.json.JSONArray
     [exec] 		+   method     getConditionType()
     [exec] 			+   return     java.lang.String
     [exec] 		+   method     getConditionsJSONArray()
     [exec] 			+   return     com.liferay.portal.kernel.json.JSONArray
     [exec] 		+   method     setActionsJSONArray(com.liferay.portal.kernel.json.JSONArray)
     [exec] 			+   return     void
     [exec] 		+   method     setConditionType(java.lang.String)
     [exec] 			+   return     void
     [exec] 		+   method     setConditionsJSONArray(com.liferay.portal.kernel.json.JSONArray)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.RootLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.RowStyledLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] 	<   class      com.liferay.layout.util.structure.StyledLayoutStructureItem
     [exec] 		+   method     <init>(java.lang.String,java.lang.String)
     [exec] 			+   return     void
     [exec] [Baseline Warning] Bundle Version Change Recommended: 42.0.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/tools/sdk/dist/com.liferay.layout.api-41.0.1.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay/com.liferay.layout.api/41.0.0/5dc518260a288831128acd8e4da037cfad968283/com.liferay.layout.api-41.0.0.jar
```

**Comment by marcogalluzzi** [comment]
Hi @SylviaLuan I've rebased my changes onto master, but I don't know why the unique failure: the complaining API has not been changed.

Let's try testing again...

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
Hi @SylviaLuan not it is complaining about an incorrect semantic versioning in a different package 🤦  [service-builder-jdk8/0/0](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/462303//consoleText)

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
