### PR TITLE
[TS] LPS-151307

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-151307

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]
It looks good to me

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by austinchiang** [comment]
@robertoDiaz we don't have any tests for DM that configure some value in system settings then run an upgrade against it. We'll look into automating this; if there are any other DM configuration stuff you think we should have automation coverage for please let me know and we'll be happy to add it. Thanks!

**Pull request closed without merging**
