### PR TITLE
LPS-163961 We should use custom getInputName

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
cc: @ambrinchaudhary

**Comment by ambrinchaudhary** [comment]
Tested and working fine. Thanks @ealonso!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
