### PR TITLE
LPS-135864 Add placeholder render command

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-135864

Thing to review:

- [x] Set the defaultLanguageId in https://github.com/liferay/liferay-portal/blob/e07a5fd603928778a2def63d9b7b0badff905cae/modules/apps/translation/translation-web/src/main/java/com/liferay/translation/web/internal/portlet/action/GetExportTranslationAvailableLocalesMVCResourceCommand.java#L97-L100
- [x] obtain properly availableSourceLocales in `modules/apps/translation/translation-web/src/main/java/com/liferay/translation/web/internal/display/context/ExportTranslationDisplayContext.java`
- [ ] add data to `modules/apps/translation/translation-web/src/main/java/com/liferay/translation/web/internal/display/context/ExportTranslationDisplayContext.java`
- [x] get the keys array or the key (plid or aricleId) 🤔 https://github.com/liferay/liferay-portal/blob/8e1a4f3ef962d16fd12da46aca4cbe6441380c78/modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/js/actions.js#L42-L48 https://github.com/liferay/liferay-portal/commit/42ea5664109d402a2377a6c606adcea636b8a7b1 used here https://github.com/liferay/liferay-portal/blob/92efb7330eb983b133ebe2ace3c43752d1590c49/modules/apps/translation/translation-web/src/main/java/com/liferay/translation/web/internal/portlet/action/ExportTranslationMVCResourceCommand.java#L162-L168

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
rebase of https://github.com/liferay-lima/liferay-portal/pull/2072

**Comment by AliciaGarciaGarcia** [comment]
lol

**Comment by boton** [comment]
https://github.com/liferay-lima/liferay-portal/pull/2184#discussion_r694704126

**Comment by boton** [comment]
See #2286

**Pull request closed without merging**
