### PR TITLE
LPS-197820 New module and structure for "Saved Content"

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
> As a user accessing content, I would like to save content for future reference, so that later I can easily access a list of my saved content.
> The “Save Content” fragment will mark/unmark the referenced content on the page so that the user can save it for later reference.

For this we will need an structure to store the user saved content, as Pages, Blogs, Documents, Knowledge Base Articles (that is the epic needs).

- LPS-197820 create new app to save content
- LPS-197820 add new app structure
- LPS-197820 add tables and service of save content entry
- LPS-197820 buildService
- LPS-197820 add needed dependencies and exports
- LPS-197820 AutoSF

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1327401_2385

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
