### PR TITLE
LPS-202233 Change Configuration view for KB

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-202233)

## Changes

Change the configuration for Knowledge Base because it should be open in a new page instead of a modal.

> [!NOTE]
> **You need to activate the LPS-197692 FF.**

## Test Scenario 1

1. Go to Knowledge Base
2. Click on the kebab menu in the top right
3. Navigate to the sections to check the behaviour and styles

image

cc:// @BarbaraCabrera, @sandrodw3

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]

**Review by marcogalluzzi — COMMENTED** [review]
Nice job also here. Just the same optional change as described [here](https://github.com/liferay-lima/liferay-portal/pull/5009#discussion_r1424203705)

**Comment by jkappler** [comment]
@marcogalluzzi, would it be okay to forward the PR? And in case the change in the method is done, we can do it in a follow up. What do you think?

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
