### PR TITLE
LPS-165180 KB Display modal alignment

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**BEFORE:**
Screenshot 2022-10-14 at 13 36 25

**AFTER:** 
Screenshot 2022-10-14 at 13 50 25

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — COMMENTED** [review]
LGTM. Tested and working
image

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
