### PR TITLE
LPS-128451 Escape content to avoid running embedded Js code

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by carloslancha — APPROVED** [review]
LGTM

**Review by boton — APPROVED** [review]
LGTM tested and working.

Would it be better if we pass it on to FI or forward it directly?

**Comment by boton** [comment]
See liferay-frontend#851

**Pull request closed without merging**
