### PR TITLE
LPS-154737 Move IG display context classes to DM API module

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by adolfopa** [comment]
@ambrinchaudhary Do you want to send this along your other changes? Or want me to rebase and forward?

**Comment by ambrinchaudhary** [comment]
Hey @adolfopa, there is a conflict in `portal-kernel/bnd.bnd`, could you please fix it and I'll forward the pull. Thanks a lot.

**Comment by ambrinchaudhary** [comment]
> @ambrinchaudhary Do you want to send this along your other changes? Or want me to rebase and forward?

Yeah that is much better, as I have my pull ready. I will send it with my pull, thanks.

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by boton** [comment]
Some semantic versioning error on `com.liferay.document.library.display.context `.

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/3100

**Pull request closed without merging**
