### PR TITLE
LPS-148753 create test to check the behavior when call from DLAppService and DLAppLocalService

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPS-148753 create test to check the behavior when call from DLFileEntryService, DLAppService and DLAppLocalService, to ensure te creation of the urlFriendly from upper layers without error

To pass this PR the PR : https://github.com/liferay-lima/liferay-portal/pull/2833 must be merged on master and then tested.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
CI will fail till the https://github.com/liferay-lima/liferay-portal/pull/2833 is merged because needs methods on that PR

So till then DO NOT CI it :D

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
