### PR TITLE
LPS-117460 The URL should contain the path to the right locale, for example /es if is spanish /en if this is english.

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

Minor change: the alternates URLs should contain the language, for example, for a Spanish URL:

`<link data-senna-track="temporary" href="http://localhost:8080/es/-/alicia-en-el-pa-c3-ads-de-las-maravillas" hreflang="es-ES" rel="alternate">`

instead

`<link data-senna-track="temporary" href="http://localhost:8080/web/guest/-/alicia-en-el-pa-c3-ads-de-las-maravillas" hreflang="es-ES" rel="alternate">`

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @cgoncas,

Can you check if https://github.com/liferay-lima/liferay-portal/pull/577 also fixes the issue? The algorithm defined by https://issues.liferay.com/browse/LPS-37809 was not in sync with Portalmpl's logic.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
