### PR TITLE
LPS-151002 - Add unit tests

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Requested by Brian https://github.com/brianchandotcom/liferay-portal/pull/115803#issuecomment-1091615474

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
