### PR TITLE
LPS-189072 Message Boards: problem with dropdowns when click on More Messages 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
https://liferay.atlassian.net/browse/LPS-189072
No need to run scripts, otherwise dropdowns are registered twice. 

When `<liferay-ui:icon-menu>` is added to the markup (this is done for new replies loaded when you click on More Messages button), this automatically registers the "dropdown", so there is no need to call `runScriptsInElement()` fn, otherwise, the dropdown shows and hides inmediatelly. 
One possible solution could be to call runScriptsInElement for the last elements, 
```
runScriptsInElement(messageContainer.lastChild);
```
but I think there are no other scripts that need to be loaded and every button/feature works as expected, that is why I prefer to remove the call.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:message-boards

**Review by marcogalluzzi — APPROVED** [review]
I've tested it and it looks good to me!

**Comment by marcogalluzzi** [comment]
The message board error doesn't seem to be related: the flag icon has not been found. I will re-run the test.

**Comment by marcogalluzzi** [comment]
ci:test:message-boards

**Comment by Hanlf** [comment]
The above failures are not related to this PR, the MB flag issue is filed here: https://liferay.atlassian.net/browse/LPS-189281

**Comment by Hanlf** [comment]
ci:test:stable

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
