### PR TITLE
LPS-186420 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-186420
https://liferay.atlassian.net/browse/LPS-129663

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
