### PR TITLE
LPS-147438 add error message to exception to audio and video processor

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-147438 add error message to exception to audio and video processor to be properly consumed by the test because without message assert can't process it properly

Without message, the ExpectedLog from the tests is "null" so it cannot be processed properly and assert fails but not for the test

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1297401_1755

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_1818

**Comment by AliciaGarciaGarcia** [comment]
rebase and push

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
