### PR TITLE
LPS-124734 & LPS-124050 & LPS-124777 & LPS 124779

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Looks like there's a legitimate test failure in `DLVideoExternalShortcutResolverTest.testResolveFromYouTube`

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1227.

**Pull request closed without merging**
