### PR TITLE
LPS-136123 add test to check the deletion of the depot after the deletion of the company

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-136123

It seems that deleting the virtual instance it’s not deleting the elements of the asset library, nor the groups nor nothing.

related:https://issues.liferay.com/browse/LPS-136408

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
@4lejandrito I made the changes requested by Brian on https://github.com/brianchandotcom/liferay-portal/pull/105006#issuecomment-891413694 can you check if the test is properly moved and some SF changes must be done.

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
