### PR TITLE
LPS-139175 Update english translation for reading Time for blogs

### PR DESCRIPTION
**Pull request by boton**
https://issues.liferay.com/browse/LPS-139175

> The wording around reading time doesn't make sense in the English language. Where the reading time is given as "8 Minutes Read" the addition of the word Read after the time  means that the s should be dropped from Minutes.

~~@adolfopa I have some questions about this PR:~~

- ~~It is better not to update the language key and leave minutes in the key? `x-minutes-read` => `x-minute-read` If I did, maybe we would lose the translations that are already done and I want to avoid it.~~
- ~~When I run the `buildLang` tasks the pending key `site-navigation-menu-name` is added to all Language files. I have decided to ignore all these changes. But maybe it´s better to add in the `buildLang` commit or add in an extra commit~~

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@boton Sadly, I think we should change the lang key as well; to give time for the new key to get translated, maybe it is better to wait until the release is done (this is a relatively minor issue anyway).
About you second point, I don't think I understand. I'd add whatever buildLang does, but I'm not sure if you're seeing some weird behaviour.

**Comment by boton** [comment]
@adolfopa I've updated the key and only update the `Automatic Copies` in the `Language_*.properties`. 

I think that is safe to forward it, what do you think?

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
