### PR TITLE
LPS-189775 copy tags and categories on shortcut

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
On this PR I want to solve 2 things

the tags were not copied on the shortcut because the class was incorrect
the categories never were obtained from the file

additionally I added the tag/category taglib to the info_panel to show them. This maybe will cause some poshi failures.

- LPS-189775 use DLFileEntryConstants.getClassName to get the tags
- LPS-189775 copy asset categories to the new shortcut
- LPS-189775 show the categories and the tags on the info panel

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
The failures are unrelated. I will forward this directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
