### PR TITLE
LPS-190860 add the displayDate on the creation and update methods of the KBArticle

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
This is a follow up PR from the 

https://liferay.atlassian.net/browse/LPS-188060 : Schedule a Knowledge Base Article

On this PR I added the new field of the KBArticle table to the add and update methods.

The user will not have information about this field. 
Field must not be null so validation is done.

Now the update will update every time the displayDate field.

- LPS-190860 add displayDate parameter on addKBArticle and updateKBArticle methods
- LPS-190860 add the displayDate to the validation method
- LPS-190860 buildService
- LPS-190860 baseline
- LPS-190860 add displayDate parameter to addKBArticle
- LPS-190860 fix updateKBArticle calls
- LPS-190860 add displayDate to service
- LPS-190860 buildService
- LPS-190860 add displayDate on calls of the service
- LPS-190860 fix updateKBArticle on tests
- LPS-190860 autoSF
- LPS-190860 add test to check the validation of the displayDate

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]
@AliciaGarciaGarcia The changes look good, but I wonder if it wouldn't be simpler to accept a `null` display date as valid, an then automatically set it to the creation date. Also, with the current approach, it is possible for the display date to be less than the creation date (as the creation date may be created just before the db update, but the display date is created afresh before that).

I don't think this is a big deal, just something that we should take into account.

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa 

Thanks for pointing at it.

The story says that the article is published or scheduled so the display Date, so in my opinion should have a date when the data arrives to the service, so a null value should trigger an exception. 

At this point, that the date is before the creation it's not an issue. we are only creating the data on the table but not using it. on posterior PRs we should validate the date but for this we need the input of the frontend, and if published, the date will be the moment of the creation, and the difference between creation and display do not should be more than a second and IMO it's a valid value.


If do you think that this should be changed, we can do it on this PR or on a following story

Thanks!

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Hey @AliciaGarciaGarcia in the last ci:test:relevant there were some failing backend tests that are related to this pull. I'm guessing they're going to fail again after this relevant is finished. Can you take a look? https://testray.liferay.com/home/-/testray/case_results/2388110804 
`PortalLogAssertorTest#testScanXMLLog: null com.liferay.knowledge.base.exception.KBArticleDisplayDateException: Display date is null  at com.liferay.knowledge.base.service.impl.KBArticleLocalServiceImpl._validate(KBArticleLocalServiceImpl.java:2355)`

The functional tests are all good to go, so feel free to forward

**Comment by austinchiang** [comment]
Checking failures

**Comment by austinchiang** [comment]
@AliciaGarciaGarcia Actually there is one more issue found from ci:test:relevant related to headless API's (I thought the API tests ran with ci:test:knowledge-base but I guess not). It seems like displayDate is now expected based on this error:
Screenshot from 2023-07-24 09-12-55

But after passing in a value I'm getting a bad request
Screenshot from 2023-07-24 09-14-01

Checking the v1.0/sites/{siteId}/knowledge-base-articles endpoint I don't see displayDate being used there, so maybe it needs to be exposed?

**Comment by AliciaGarciaGarcia** [comment]
Thnaks @austinchiang 

I will add rebase and see if is needed to add the new parameter to the headless API

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
I will push up the test fixes again and rerun the tests

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
Test results LGTM

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by austinchiang** [comment]
ci:test:stable

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
