### PR TITLE
LPS-164481, LPS-164246, LPS-162852, LPS-162970, LPS-164773, LPS-164774, LPS-164777 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-164481
https://issues.liferay.com/browse/LPS-164246
https://issues.liferay.com/browse/LPS-162852
https://issues.liferay.com/browse/LPS-162970
https://issues.liferay.com/browse/LPS-164773
https://issues.liferay.com/browse/LPS-164774
https://issues.liferay.com/browse/LPS-164777

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
@ambrinchaudhary @boton Once I combined two more pulls into this. https://issues.liferay.com/browse/LPS-165135 is fixed the remaining tests should pass and we can forward this.

**Comment by boton** [comment]
Resent in #3573

**Pull request closed without merging**
