### PR TITLE
LPS-164550 | Automate LPS-163801

### PR DESCRIPTION
**Pull request by jaimelr10**
Description: Creation of Priority 3 test to verify that user is able to save a page after the Site Default locales has been changed as described in [LPS-163801](https://issues.liferay.com/browse/LPS-LPS-163801)

Jira Ticket: https://issues.liferay.com/browse/LPS-164550

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Review by austinchiang — APPROVED** [review]
@jaimelr10 Two things to note:
- Try to search for JSON macros whenever possible to use. In this case we have JSONLayout we can use (layout = page). We also have JSONGroup (group = site)
- No need to delete the page in the test because in the [global teardown](https://github.com/brianchandotcom/liferay-portal/blob/773a927c59f18efadd6c3c137bb61b3e8abb76d8/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagesadmin/PagesAdmin.testcase#L20-L28) we already delete either the virtual instance (basically all the test added into the browser during runtime) or in this case the group, in which case everything inside that group is deleted as well

**Comment by austinchiang** [comment]
Sent here https://github.com/liferay-lima/liferay-portal/pull/3783

**Pull request closed without merging**
