### PR TITLE
LPS-166637 - Alerts for required fields with matching style

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**After** the changes: 

Screenshot 2022-11-21 at 14 13 33

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
