### PR TITLE
LPS-124411 Fix - Black screen when our video loading or video error is present

### PR DESCRIPTION
**Pull request by boton**
On top of brianchandotcom#96935 (fixes tests).

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@ambrinchaudhary please review.

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
ci:forward

**Review by 4lejandrito — APPROVED** [review]

**Pull request closed without merging**
