### PR TITLE
LPS-195020 Use obtain not only the vocabularies from the site and ancestors but the asset libraries connected too

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-195020

Steps to reproduce

1. Start a clean Liferay environment
2. Navigate to System Settings > Search > Category Facet Field
3. Change from the default field (assetCategoryIds) to the assetVocabularyCategoryIds field
4. Navigate to Applications > Content > Asset Libraries
5. Create a new Asset Library
6. Connect the new Asset Library with Liferay DXP
7. Enter the Asset Library > Categories
8. Add a new Vocabulary and under it a new Category
9. Go to Categorization > Categories
10. Go to DM, select a file and click on the Categories button in the action bar

- LPS-195020 Obtain not only the vocabularies from the site and ancestors but the asset libraries connected too
- LPS-195020 bulk-rest-impl: Use connected groups as well

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by robertoDiaz — APPROVED** [review]
Changes seem to be right because _portal.getCurrentAndAncestorSiteGroupIds does not include all the needed groups in this case.

Anyway we should be careful with this low level changes because in other cases change [TaxonomyVocabularyResourceImpl.java](https://github.com/liferay-lima/liferay-portal/pull/4742/files#diff-24257d9ef53747accc0cf9d724665d90ce2447f6afeae9cf02d36236edec046c) could impact  other tools we have in portal.

See https://liferay.atlassian.net/browse/LPP-50706?focusedCommentId=2462036 for an example.

**Comment by robertoDiaz** [comment]
One question to @adolfopa 

Does it make sense using the SiteConnectedGroupGroupProviderUtil  in _portal.getCurrentAndAncestorSiteGroupIds so this method could return all the methods (doing this we could avoid change all - or most - of the getCurrentAndAncestorSiteGroupIds to the new method.

Regards

**Comment by adolfopa** [comment]
@robertoDiaz The main problem is that PortalImpl is in core, while the util class is in depot-api.

**Comment by robertoDiaz** [comment]
👍 

We could wrap this method, anyway. 

Anyway I understand that in some cases the depot group is not needed.

**Comment by adolfopa** [comment]
@robertoDiaz Can we then forward this?

**Comment by ambrinchaudhary** [comment]
> @ambrinchaudhary
> 
> This is the commented PR, Can you recheck the modal?
> 
> Thanks!!!

As we already talked, I will do in a separate task to not stop this (your work doesn't cause the modal issues)

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
