### PR TITLE
LPS-138401 The asset title with script in the sharing pop-up window can not be displayed correctly

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-138401

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by boton — APPROVED** [review]
I fix this bug with @AliciaGarciaGarcia, and now the HTML tags are properly escaped by React.

**Before PR**
image

**After PR**
image

In neither case is an alert prompted.

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
