### PR TITLE
LPS-139938 Implement Azure translator

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
rebased due merger problems with master

**Review by AliciaGarciaGarcia — APPROVED** [review]
LGTM but I can not use the service because I don't have the key.

It fails as expected if you introduce a "fake" key

If you have test it, forward it

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
