### PR TITLE
LPS-132211 Blog Navigation Card Overflow when "Time To read" activated

### PR DESCRIPTION
**Pull request by boton**
Follow up #1891

> Hey @liferay-lima,
> 
> Attached is an update for http://issues.liferay.com/browse/LPS-132211.
> 
> When the “Time To Read” option is selected for blogs, the words overflow the card when the blogs widget is placed in the 30 column of a 30/70 page.
> 
> **Test Plan:**
> 
> 1. Create two blog entries
> 2. Enable Time To Read by navigating to Control Panel > Configuration > System Settings > Content and Data > Blogs > Widget Scope > Blogs > check Enable Reading Time, and save
> 3. Create a widget page with a 70/30 columns split
> 4. Put a blogs portlet into the 30 column
> 5. Navigate to a blog entry and scroll to the card navigation
> 
> Please let me know if you have any questions. Thanks!

First, I add the @pat270 then I try to [fill better](https://github.com/liferay-lima/liferay-portal/commit/a67ea1a2cfe0056fbe48d56818a57a8f23e05d91) space for the `More Blog entries` block.

Confirm if these changes work for you @fortunatomaldonado @jonmak08 @pat270.

In the team, we commented about this issue and we are not sure why is expected that blogs work in a 30% column? 
Because Blogs is developed with the 1 col layout in mind (full width).
Could we be missing something?

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @boton,

Thank you for the help on this! The changes looks good to me. @pat270, what do you think?

> In the team, we commented about this issue and we are not sure why is expected that blogs work in a 30% column?
Because Blogs is developed with the 1 col layout in mind (full width)

Thank you for the information as I did not know this about Blogs. Is there documentations on the specifics of this, and other components, so I can reference it in the future?
The assumption was that Blogs as well as other components should still be functional and appear correctly despite the column length. In this case, the Reading Time should not extend past the card in a 30% column. 

Let me know if there are any more questions or comments about this.
Thank you again for the help!

**Comment by boton** [comment]
Hi @fortunatomaldonado,

> Thank you for the information as I did not know this about Blogs. Is there documentations on the specifics of this, and other components, so I can reference it in the future?

Honestly, I think we don't have any documentation about it

> The assumption was that Blogs as well as other components should still be functional and appear correctly despite the column length. In this case, the Reading Time should not extend past the card in a 30% column.

I completely ok with this fix, but maybe blogs don't work as expected in 30% col.

@pat270 @jonmak08 the changes looks good to you?, I'm waiting for your confirmation to forward it :D

**Review by jonmak08 — APPROVED** [review]
LGTM.  Thanks @boton!  @pat270 is on PTO and will not be back until next week if you want to wait for his review too.

**Comment by boton** [comment]
@jonmak08 @fortunatomaldonado your reviews are enough for me. Thanks!

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
