### PR TITLE
LPS-191945 Remove dev FF for Advanced Search and Filtering

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by marcogalluzzi — APPROVED** [review]
Good work!

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:document

**Comment by Jeremy-Ch** [comment]
Hi @ambrinchaudhary Thanks for helping to remove the FF from Poshi tests. From the QA perspective, this pr is good to forward. Thanks.

/cc @austinchiang @marcogalluzzi

**Review by Jeremy-Ch — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
