### PR TITLE
LPS-152217: Expose ERC in WikiPageAttachment

### PR DESCRIPTION
**Pull request by sergiojimcos**
**What is new?**
- Expose **External Reference Code** in `WikiPageAttachment`.
- Endpoint implementation of `GET` and `DELETE` by **External Reference Code**.
- Including some tests in API part.
- Implement new exception: `NoSuchWikiPageAttachment`.
- Requested changes in https://github.com/brianchandotcom/liferay-portal/pull/121987

## SERVICE
This PR supports the implementation of external reference code in `PortletFileRepository` service to be able to GET and DELETE by external reference code. 

**NOTE:** New Exception created if a WikiPage's ERC is wrong introduced. So the `NoSuchWikiPage` will be caught indicating that there is no wiki page associated to that ERC. The same occurs when a WikiPageAttachment's ERC is not indicated well, the `NoSuchWikiPageAttachment` will be caught.

## API
In the API section, this PR contains the new endpoints to operate using the ERC:

image

To see this new endpoint you have to follow these steps:

1. Deploy `wiki-api` and `wiki-service` in this order. Later, deploy `document-library-repository-portlet-file-repository-impl`
2. Deploy `headless-delivery-api` and `headless-delivery-impl` in this order.
3. Go to `/o/api`
4. Go to `WikiPageAttachment`

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-152217

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@sergiojimcos errors seem to be related to your changes. Can you take a look?

**Comment by sergiojimcos** [comment]
> @sergiojimcos errors seem to be related to your changes. Can you take a look?

Yes, sure I will do it

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_4458

**Comment by adolfopa** [comment]
@sergiojimcos baseline errors seem legit (wiki headless).

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:stop

**Comment by sergiojimcos** [comment]
Rebased and make changes in baselines

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:wiki

**Comment by liuxingye** [comment]
This does not affect any wiki tests after analysis the test results [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1962711636&testrayRunId=1962712076)

**Comment by sergiojimcos** [comment]
> This does not affect any wiki tests after analysis the test results [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1962711636&testrayRunId=1962712076)

Thanks @liuxingye!!

**Comment by liuxingye** [comment]
This does not affect any relevant tests after analyzing the test results [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1960841459&testrayRunId=1960841648).

**Comment by liuxingye** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122430

**Pull request closed without merging**
