### PR TITLE
LPS-136644 layouts SEO mapping remove feature flag

### PR DESCRIPTION
**Pull request by boton**
Removing the frontend part of the SEO mapping feature flag, updating the test, and remove some old code.

@adolfopa please check this out 49f2d74e4a361ef35a3634d84be1c88e29ee8396 in case it's convenient to create a constant.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/2173 for conflict resolution and further changes.

**Pull request closed without merging**
