### PR TITLE
LPS-206512 Enable Lock icon tooltip on hover in D&M

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-206512

Steps to Reproduce

1) Go to Documents & Media
2) Check out a Document
3) Hovering the mouse over the lock icon on the card.

- LPS-206512 add title and  lfr-portal-tooltip class to show the tooltip, and aria label for accessibility
- LPS-206512 buildLang

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @ambrinchaudhary / @boton 

I found something funny (not funny) with the hover:

see my video
https://github.com/liferay-lima/liferay-portal/assets/47524751/13e9b3a4-be14-4c08-96e3-ea8074bab864


Can you take a look at it?

**Comment by ambrinchaudhary** [comment]
@AliciaGarciaGarcia could you try this to see if that doesn't happen? 
```
<span class="lfr-portal-tooltip" title="X">
	<clay:icon....>
</span>
```

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
