### PR TITLE
LPS-117661 Provide a library for video previewing with support

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1705.

**Pull request closed without merging**
