### PR TITLE
LPS-182876 Add menu option for copy in Folders 

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Sending a PR for the third time (previous one is #4288). Now I've changed a name of a method in class `DLAppServiceWhenCopyingAFolderTest` because of [Brian comment](https://github.com/brianchandotcom/liferay-portal/pull/134665#issuecomment-1543601649):

* Before: `_createFoldersAndFiles`
* Now: `_addFoldersAndFileEntries`

🤞

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by Hanlf** [comment]
Hi @marcogalluzzi there are some conflicts, could you please take a look, thanks!

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
The ci:test:relevant failures are not related to this PR.

**Pull request closed without merging**
