### PR TITLE
escape the title of the SharingEntry for XSS problems showing the notification when sharing on sharing content

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-138409 escape the title of the SharingEntry for XSS problems showing the notification when  sharing

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
