### PR TITLE
LPS-167607 HR_87 The basic web content template is not accessed from the template iframe by the keyboard 

### PR DESCRIPTION
**Pull request by veroglez**
Fixes https://issues.liferay.com/browse/LPS-167607

Hi guys! I send you a fix for this accessibility issue. The main problem is that the cards are not focusable elements and they don't have an associated keyboard event to select the item, so the following solution has been applied:
- Give a `role="button"` and `tabindex="0"` to the card.
- Add an `aria-label` to the card with the text `select-x` to have more context of the action to be carried out. For example,  the screen reader will read `Select Basic Web Content`.
- A new keyboard event has been created to select the item when it's pressed.

Let me know If you have any doubt! thanks in advance!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
