### PR TITLE
LPS-161368 Upload Image tab is not working on KB

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-161368 Create UploadKBArticleAttachmentsMVCActionCommand
- LPS-161368 rename action
- LPS-161368 let edit the image on the item selector

https://user-images.githubusercontent.com/47524751/186644867-b7cbf371-bbe5-437d-9a45-01393d414a26.mp4

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@boton 

This PR solves the part of the back that did not work about the upload selector on KB.

**Comment by boton** [comment]
> @boton
> 
> This PR solves the part of the back that did not work about the upload selector on KB that maybe is blocking you.

Thanks, @AliciaGarciaGarcia when is merged on master I will check on #3409. For lucky isn't blocking me.

**Review by boton — APPROVED** [review]
Tested and worked with the current uploader and the new one on #3409. I don't look soo much at the code

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
