### PR TITLE
LPS-190185 Send also the classNameId so that we receive the same values thant we used to when using the FileEntryDownloadFileEntryItemSelectorReturnTypeResolver

### PR DESCRIPTION
**Pull request by victorg1991**
This was caused by https://liferay.atlassian.net/browse/LPS-189867. Since we are no longer receiving the classNameId, we cannot compute the usages

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by victorg1991** [comment]
Hey @adolfopa added the commit where we update the javadoc here too :)

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
Test failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
