### PR TITLE
LPS-136185 add filename/extension validation for multiUpload, drag and drop and if you skip the validation on the system when selecting the accepted exception

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Test1

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by 4lejandrito — COMMENTED** [review]
I think it would be safer to perform this validation at the service level ([DLFileEntryLocalServiceImpl.java#L2712-L2728](https://github.com/liferay/liferay-portal/blob/d604052686d2d9bc2ef19ea7c53ffc31ffe0bcd3/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLFileEntryLocalServiceImpl.java#L2712-L2728)). What do you think?

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
👍 I think these changes are much better, but I don't know if the failures are related, you'll have to investigate 😄 .

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
