### PR TITLE
LPS-176119

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
In order to fix [LPS-176119](https://issues.liferay.com/browse/LPS-176119), I revert some changes done in LPS-175547 since we need to set multiple selection parameter through the request.

As I could see, we are adding this logic only for assets:

```
new DynamicServletRequest(
	httpServletRequest,
	HashMapBuilder.put(
		"multipleSelection",
		_toStringArray(
			!assetEntryItemSelectorCriterion.isSingleSelect())
	).build());
```
so, in other places we are going to have the same problem if we follow the LPS steps.

Proposed Solution
----
Adds a new method on [ItemSelectorViewDescriptor.java](https://github.com/liferay-lima/liferay-portal/pull/4016/files#diff-0b7a1d83a7872f0a5186997e1eb1a0f754ee2f2b26bf30cbd3ed37bd5acb12ac) to specify if we allow multiple selection or not. This method is implemented as default returning false.

In that way we are not going to loose the multiple selection when we navigate through site or asset library selector. Also, we are avoiding to use the request to share this kind of information.

Steps to verify
----
1. Add a shortcut video to document&media
2. Add a web content
3. Open the Related Assets panel to select the External Video Shortcut
4. You can see the checkbox and shortcut video title on the default page
5. Try to click the Sites and Libraries button and re-navigate to the Liferay DXP page

I send the first commit to fix the problem that we have for assets to echo use (https://github.com/liferay-echo/liferay-portal/pull/11194), but I would like to fix it for all cases, please let me know what do you think, maybe it is not the correct solution.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Some failures are related to this PR, @ealonso could you please take a look at the failure1? Thanks

- Failure1: [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/reports/production/logs/2023-02/test-1-38/test-portal-acceptance-pullrequest(master)/6474/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0) 

```
     [exec] > Task :apps:item-selector:item-selector-api:baseline
     [exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.item.selector                          MINOR      4.9.0      4.9.0      4.10.0     VERSION INCREASE REQUIRED
     [exec] 	<   interface  com.liferay.item.selector.ItemSelectorViewDescriptor
     [exec] 		+   method     isMultipleSelection()
     [exec] 			+   return     boolean
     [exec] [Baseline Warning] Bundle Version Change Recommended: 6.7.0
```

- Failure2(Test Fix):
[PagesAdminWithThemeCSSExtension#AddThemeCSSExtension](https://testray.liferay.com/home/-/testray/case_results/2202689748)
[PagesAdminWithThemeCSSExtension#ChangeThemeCSSExtensionOfInheritorPage](https://testray.liferay.com/home/-/testray/case_results/2202687164)
[PagesAdminWithFaviconExtension#ChangeFavicons](https://testray.liferay.com/home/-/testray/case_results/2202689876)

Since the failure2 are all Echo tests, asked @yang.cao for help fixing them, thanks!

**Comment by Tim-Cao** [comment]
Hi @ealonso, there are two regression issues happens on change favicon and theme CSS client extension selectors.
Both selectors are single item selector not multi items selector.
The user cannot select the item by clicking the body of item except clicking the checkbox.
image
Would you mind having a look at? Thanks

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Thanks @Tim-Cao for checking Echo failures.
@ealonso There is another failure [modules-compile-jdk8/0/8](https://testray.liferay.com/home/-/testray/case_results/2202839195?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2202830631%26testrayRunId%3D2202830669%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) should be related to this PR, could you mind taking another look, thanks!
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/client-extension/client-extension-type-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.client.extension.type                  MINOR      3.3.0      3.3.0      3.4.0      VERSION INCREASE REQUIRED
     [exec]     	<   interface  com.liferay.client.extension.type.ThemeSpritemapCET
     [exec]     		+   method     isEnableSVG4Everybody()
     [exec]     			+   access     abstract
     [exec]     			+   annotated  com.liferay.client.extension.type.annotation.CETProperty
     [exec]     				+   property   defaultValue='false'
     [exec]     				+   property   name='enableSVG4Everybody'
     [exec]     				+   property   type='Boolean'
     [exec]     			+   return     boolean
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 6.3.0
```

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @Hanlf,

I didn't change nothing related with that module, but I already update it. Let's see what happen now.

**Comment by Hanlf** [comment]
@ealonso Thanks for fixing it, the error is gone.
@adolfopa There are no related failures to this PR, from the QA side, it is ready to forward. Not sure if you need to re-review, so I leave it up to you to forward.

**Comment by ealonso** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/130628

**Pull request closed without merging**
