### PR TITLE
LPS-193765 Create a mechanism to allow get the proper Portlet Ratings classname

### PR DESCRIPTION
**Pull request by robertoDiaz**
Resending the initial approach to be able to get the right classname in ratings tag du using the InfoSearchClassMapper is not possible

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:reevaluate:1377401_14108

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Test failures not related

**Pull request closed without merging**
