### PR TITLE
Master | LPS-206087, LPS-205358

### PR DESCRIPTION
**Pull request by Hanlf**
https://liferay.atlassian.net/browse/LPS-206087
https://liferay.atlassian.net/browse/LPS-205358

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
