### PR TITLE
LPS-182869 - Add new fields to show more information on the message boards mails

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPS-182869 - Add new fields to show more information on the message boards mails

To test: 
FF : LPS-182020

- LPS-182869 extract method to get the message body of a mbMessage
- LPS-182869 add new definitions terms to the page
- LPS-182869 buildLang
- LPS-182869 add FF
- LPS-182869 add the new fields to the sender
- LPS-182869 extract how to obtain the getMessageBody to a helper
- LPS-182869 add markup elements to the use for the new fields with styles
- LPS-182869 obtain the root message body
- LPS-182869 obtain the different level messages to show the user
- LPS-182869 obtain the same level messages, of the new message, to show the user

Follow up PR from https://github.com/liferay-lima/liferay-portal/pull/4261

image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Style used :
```
<style type="text/css">.mb-mail-message {
        margin: auto;
        width: 50%;
        padding: 10px;
    }

    .mb-message-thread {
        border-radius: 4px;
        border: 1px solid #E7E7ED;
        margin-bottom: 0.2rem;
        font-size: 0.9rem;
        padding: 1rem;
    }

    .mb-new-message {
        color: #272833;
        font-size: 0.875rem;
        border-radius: 4px;
        border: 1px solid #E7E7ED;
        border-left: 4px solid #80ACFF;
        padding-left: 0.75rem;
    }

    .mb-new-comment-lable {
        margin-top: 1.5rem;
        margin-bottom: 1rem;
    }

    .mb-new-message-content {
        color: #272833;
        font-size: 0.9rem;
        font-weight: 400;
        margin-bottom: 0.1rem;
    }

    .mb-new-message-content p {
        margin-top: 0rem;
    }

    .mb-new-message-label {
        border-radius: 4px;
        background-color: #2E5AAC;
        color: #FFFFFF;
        font-weight: 600;
        font-size: 0.625rem;
        padding-left: 4px;
        padding-right: 4px;
        padding-bottom: 3px;
        padding-top: 3px;
    }

    .mb-new-message-timestamp {
        margin-top: 0.1rem;
    }

    .mb-new-message-user-name {
        color: #272833;
        font-size: 0.875rem;
        font-weight: 600;
        margin-bottom: 0.1rem;
    }

    .mb-new-message-user-name p {
        margin-bottom: 0.25rem;
    }

    .mb-parent-message {
        border-radius: 4px;
        border: 1px solid #E7E7ED;
        margin-bottom: 0.2rem;
        padding-left: 0.75rem;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;

    }

    .mb-parent-message-user {
        font-weight: 600;
        color: #6B6C7E;
        margin-bottom: 0.25rem;
    }

    .mb-parent-message-body {
        color: #6B6C7E;
    }

    .mb-root-message-body {
        font-size: 0.9rem;
        color: #272833;
    }

    .mb-root-message-user {
        margin-top: 0.25rem;
        margin-bottom: 0.25rem;
        font-weight: 600;
    }

    .mb-root-message-link {
        font-size: 1rem;
        font-weight: 700;
        color: #0B5FFF;
    }

    .quote {
        background: #fff left top no-repeat;
        border-radius: 4px;
        border: 1px solid #E7E7ED;
        margin-right: 0.5rem;
        margin-top: 1rem;
        margin-bottom: 1rem;
    }

    .quote-content {
        background: transparent right bottom no-repeat;
        padding: 8px 12px 8px;
        color: #6B6C7E;
        font-style: italic;
    }

    .quote-content::first-line {
        font-style: normal;
        font-weight: 600;
    }

    .quote-title {
        font-weight: bold;
        padding: 5px 0;
    }

    ul {
        list-style-type: none;
        padding-top: 0.5rem;
        padding-left: 0.5rem;
        padding-bottom: 0rem;
        margin-top: 0rem;
        margin-bottom: 1.5rem;
    }

    .mb-sibling-message-thread {
        border-radius: 4px;
        border: 1px solid #E7E7ED;
        margin-bottom: 0.5rem;
        margin-top: 1.5rem;
        padding-top: 0.5rem;
        padding-left: 0.75rem;
    }

    .mb-sibling-message {
        margin-bottom: 0.5rem;
    }

    .mb-sibling-message-user {
        font-weight: 600;
        color: #6B6C7E;
        margin-bottom: 0.25rem;

    }

    .mb-sibling-message-body {
        color: #6B6C7E;
        font-weight: 400;
    }

    .mb-parent-message-thread {
        margin-bottom: 0.6rem;
    }
  
    .mb-reply-btn {
        border-style: solid;
        border-width: 0.0625rem;
        border-radius: 0.25rem;
        cursor: pointer;
        display: inline-block;
        font-size: 1rem;
        font-weight: 600;
        line-height: 1.5;
        padding: 0.4375rem 0.9375rem;
        text-align: center;
        transition: color 0.15s ease-in-out 0s, background-color 0.15s ease-in-out 0s, border-color 0.15s ease-in-out 0s, box-shadow 0.15s ease-in-out 0s;
        user-select: none;
        vertical-align: middle;
        background-color: rgb(11, 95, 255);
        border-color: rgb(11, 95, 255);
        color: rgb(255, 255, 255);
        margin-top: 1rem;
    }

    .mb-reply-btn a:link {
        color: #FFFFFF;
        text-decoration: none;
    }
  
   .mb-reply-btn a:visited {
        color: #FFFFFF;
        text-decoration: none;
    }
</style>
<div class="mb-mail-message">
<p>There is <strong>1 new reply </strong>in the thread.</p>

<div class="mb-message-thread">
<div class="mb-root-message-link"><a href="[$MESSAGE_URL$]">[$MESSAGE_SUBJECT$]</a></div>

<div class="mb-root-message">[$ROOT_MESSAGE_BODY$]</div>

<p><strong>1 New Comment</strong></p>
[$MESSAGE_PARENT$]

<p><strong>Replies To Last Message</strong></p>
[$MESSAGE_SIBLINGS$]

<div class="mb-new-message">
<div class="mb-new-message-user-name">
<p><span><b>[$MESSAGE_USER_NAME$]</b></span> <span class="mb-new-message-label">NEW</span></p>
</div>

<div class="mb-new-message-timestamp"> </div>

<div class="mb-new-message-content">
<p>[$MESSAGE_BODY$]</p>
</div>
</div>
</div>

<div class="mb-reply-btn"><a href="[$MESSAGE_URL$]">Reply </a></div>
</div>
```

**Comment by adolfopa** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1347401_4017

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1357401_4121

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
Hi @AliciaGarciaGarcia, the above failures are not related to this PR. I will forward this directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
