### PR TITLE
LPS-134192 Decouple import display context from Journal

### PR DESCRIPTION
**Pull request by adolfopa**
We cannot send this right now, as it causes a version increment in the info-api module. Other than that, once reviewed it should be ready to forward whenever the release allows for it.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
LGTM, great work!

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
