### PR TITLE
LPS-126693 Check if maxFileSize is unlimited 0

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
@ambrinchaudhary [Older file](https://github.com/liferay/liferay-portal/blob/ffdb4cc9f1d79fabce82a7e8b16ba4fb1b07d9d9/modules/apps/frontend-js/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/item_selector_repository_entry_browser.js#L463) has the same logic. 

Please would you know if this file is still used somewhere?

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
