### PR TITLE
LPS-134658 Display preview title like how facebook and twitter does

### PR DESCRIPTION
**Pull request by boton**
**Bug:** https://issues.liferay.com/browse/LPS-134658
**Context:** https://github.com/liferay-lima/liferay-portal/pull/1976

---

@AliciaGarciaGarcia and I work on this solution on top of #1976, for adding default title values with suffix included.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
The Poshi case `OpenGraphPreview#Smoke` is failed because the PREVIEW_TITLE only shows the **Custom Title**, the previous one is **Custom Title - Site Name - Site Name**.

/cc @boton

**Comment by boton** [comment]
@liuxingye the PR is removing the ** - Site Name** on purpose when the custom title is enabled (only in OG) and maintain the **Custom Title - Site Name** when the title is the default (custom title disabled).

Can we update the test to check that the preview shows only the Custom title when enabled, and check the **Custom Title - Site Name** when the title is the default?

thx!

**Review by adolfopa — APPROVED** [review]

**Comment by liuxingye** [comment]
ci:test:bundle

**Comment by liuxingye** [comment]
> Can we update the test to check that the preview shows only the Custom title when enabled, and check the Custom Title - Site Name when the title is the default?

Hi @boton, I've checked above ^ locally and the preview shows **only** the `Custom title` when enabled, but the preview **still** shows `Test Page Name - Test Site Name - Liferay DXP` when the title is the default. Could you take a look when you get a chance? Thanks in advance.

Record

**Pull request closed without merging**
