### PR TITLE
LPS-119254 modify formDate on serviceContext pass the validation on a modified journal Article

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia What is the purpose of FormDate? Does it affect the modification date as well?

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa the formDate is checked and compared with the modificationDate of the article, so we have to change the date of the translation to allow the approval.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
