### PR TITLE
LPS-115934 workflow to import translation

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/91061

**Pull request closed without merging**
