### PR TITLE
LPS-165967 DM make file picker accessible

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-165967 Attached video with the fix

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1387401_4376

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1387401_4376

**Pull request closed without merging**
