### PR TITLE
LPS-204979 BUG DM image editor zoom small images

### PR DESCRIPTION
**Pull request by boton**
# LPS: https://liferay.atlassian.net/browse/LPS-204979

## Implementation

First I limited the first render zoom to 100% of the image 58d98b167ccbe3cab56a05bff2377a4dfcccde89 allowing manual zoom after it.

After a conversation with Maria Martins we decided to hide the zoom percentage. We decided that because in some cases we are showing not the real zoom (the crop size is limited by the image size).

After I move from fixed zoom values to min, max and step config.

## Before the PR
image

## After the PR
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
LGTM! I like this approach. Also tested it and working perfectly, thanks @boton!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
