### PR TITLE
LPS-199510 Escape in all cases

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by robertoDiaz** [comment]
I'll rebase my changes and forward it to brian

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by WYZ-Issac** [comment]
ci:test:stable

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
