### PR TITLE
LPS-198648 XSS vulnerability with KB attachments

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-198648. 

> updateMultipleKBArticleAttachments in EditKBArticle  uses user supplied data filesChecked[i].value without encoding the value. Please encode filesChecked[i].value before using it in the <input> tag.

I followed what it is done in Message Boards: https://github.com/liferay/liferay-portal/blob/master/modules/apps/message-boards/message-boards-web/src/main/resources/META-INF/resources/message_boards/js/MBPortlet.es.js#L275

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1407401_6718

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
