### PR TITLE
LPS-113971 Autogenerated

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa , 
This is the https://github.com/AliciaGarciaGarcia/liferay-portal/pull/55 that you sent me, with the changes talked on the review.

If it seems ok to you, I'll send it.

Thanks!!

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/144

**Pull request closed without merging**
