### PR TITLE
LPS-192690 KB schedule modal

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @sofiamendozalr, this is a work in progress and I would like you to continue from here. 

For now, I created a new button "schedule" when editing an article. Once you have your pull merged, we will remove it an attach the listener to your dropdownItem. 

I would like you to complete the modal and the validations needed based on the Figma mockups, as well to understand the basic principles of react (how to render elements, useState and useEffect functions, ...)  and the use of Clay componentes (ClayDatePicker in this case)

Probably I will need to change the `openSelectionModal` and use another function to disable/enable footer buttons, but I will take care of it later. This should not affect to your work this days. 

Screenshot 2023-08-17 at 13 54 40

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/4632

**Pull request closed without merging**
