### PR TITLE
LPS-162465, LPS-162381 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-162381
https://issues.liferay.com/browse/LPS-162465

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
