### PR TITLE
LPS-189976 In a clustered environment the empty attribute could be an Object[] instead of a String[] and could produce a Cast error

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
These changes look good, however the test failure [LocalFile.DMFileEntry#CanAutocompleteCategory](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/594999//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DMFileEntry_CanAutocompleteCategory_) looks like it is related to these changes. @austinchiang is this failure related to these changes?

**Comment by robertoDiaz** [comment]
@austinchiang  If it does, please explain the use case to me to test it.

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@SamZiemer @robertoDiaz That failure is happening on other PR's as well so it's not related. I think it might be caused by some test infrastructure changes (here)[https://liferay.slack.com/archives/CD7939WBE/p1688697869870989] that was fixed last Friday

**Review by SamZiemer — APPROVED** [review]

**Comment by SamZiemer** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
