### PR TITLE
LPS-184698 Add the category to the filters

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-184698

It's under FF LPS-84424

To test :
- Create some Categories
- Go to Documents & Media
- Create a Document with those category/ies 
- Check the filter and order Dropdown
- You can see a modal with the categories of the site and global
- select the previous created category

https://github.com/liferay-lima/liferay-portal/assets/47524751/7319a500-bb25-4844-ae0a-54e8627ee84e

- LPS-184698 get only the categories that can be shown on the site and for the DLFileEntries
- LPS-184698 add onSelect action to the modal
- LPS-184698 clean categories on reload
- LPS-184698 put the category names on the label item List if selected
- LPS-184698 select all option when no categories
- LPS-184698 add the asset category ids to the filter of the searching
- LPS-184698 add the category filter to the sorting url in the same order that it appears on the dropdown filters
- LPS-184698  add as parameters the category filters to the displayStyleURL to persist the filters when changing the display view

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
