### PR TITLE
LPS-152104 Remove LayoutSEOLinkManager and LayoutSEOCanonicalURLProvider deprecated methods

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-152104

See: https://github.com/brianchandotcom/liferay-portal/pull/116341#issuecomment-1103844397
and
https://github.com/brianchandotcom/liferay-portal/pull/116559#issuecomment-1109547547

Thanks! :heart:

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:acceptance-functional

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Tested both ci:test:acceptance and ci:test:relevant, the POSHI failures are not related to this pull.

cc @adolfopa

**Comment by lfbesada** [comment]
I am sorry. There was a compilation error because of deleted methods in an integration test of the module layout-seo-test. I have fixed it.

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:acceptance-functional

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by lfbesada** [comment]
The SF failure is because it is rebased on Brian's repo and it happens there.

**Comment by lfbesada** [comment]
Should I resend it rebased on the Liferay repo instead of Brian's one?

**Comment by lfbesada** [comment]
Rebase against Liferay repo

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
