### PR TITLE
LPS-179854 Use store file name instead of raw version label

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-179854

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-179854.

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1347401_3826

**Comment by adolfopa** [comment]
ci:reevaluate:1347401_3826

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Pull request closed without merging**
