### PR TITLE
LPS-177939 know if a given user agent is a crawler user agent (via a configuration list) and act according to that

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Made some changes after : 
https://github.com/brianchandotcom/liferay-portal/pull/133367#issuecomment-1508087608

to activate : FF : LPS-175850

On the second last commit I'm making not visible the configuration due to the story of the configuration (that will merge and need to be refined is https://issues.liferay.com/browse/LPS-180049

- LPS-177939 generate new configuration for the crawler user agents.
- LPS-177939 generate CrawlerUserAgentsProvider that will be used to obtain the crawler user agents for the other services
- LPS-177939 use the new provider to get the crawler user agents that now is a set strings
- LPS-177939 when updating the configuration the returned crawlerUserAgents are processed
- LPS-177939 create a method to know if a given user agent is a crawler user agent
- LPS-177939 fix test
- LPS-177939 no longer needed
- LPS-177939 rename to align with the functionality
- LPS-177939 add test to check the new class
- LPS-177939 buildLang
- LPS-177939 hide the configuration till the story is made
- LPS-177939 baseline

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Just a suggestion, not a request for change: I think it would be better to name the matcher class "UserAgentMatcher" (singular and without the crawler at the front).

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
