### PR TITLE
LPS-129264 Disable bulk mode in localization tests

### PR DESCRIPTION
**Pull request by adolfopa**
@brianchandotcom I had to create the "test-util" module instead of moving it to portal-test because I need PropsValues (located in portal-impl), but portal-test doesn't have a dependency on it. If I recall correctly, this is so to avoid a circular dependency (although things may have changed).

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
SF failure has been fixed under [here](https://github.com/liferay/liferay-portal/commit/bc9aa34a9c54739ae6bb4342cd3f11a79b549f75#diff-c014540ac80a048d1bb4ad5f4b2e0d6ef43c140d33e315fb0f8155ad9ddfce88), rerun it.

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Pull request closed without merging**
