### PR TITLE
LPS-162866 If virus detected, message is skipped on the create/edit page on DM

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-162866 Error Tag compares by name not by instanceOf, and we are getting an AntivirusVirusFoundException so no message is found
- LPS-162866 rename exception

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1287401_4355

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
