### PR TITLE
LPS-170297 KB ItemSelector: remove priority and view count

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**BEFORE**

Screenshot 2022-12-02 at 10 35 56

**AFTER**

Screenshot 2022-12-02 at 12 43 47

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr. Forward it one more time. If it fails, I will send it to BChan manually.

**Comment by Jeremy-Ch** [comment]
ci:forward

**Pull request closed without merging**
