### PR TITLE
LPS-162718 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-162718

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:lima

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1327401_5737

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by liuxingye** [comment]
Analyzed POSHI failures from test [results](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1982221203), they are unrelated to the changes of this PR.

**Comment by liuxingye** [comment]
Forwarded to BChan https://github.com/brianchandotcom/liferay-portal/pull/123306

**Pull request closed without merging**
