### PR TITLE
LPS-137659 Add feature flag for the experience selector

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
@boton This includes only backend changes, but may cause conflicts with your local branches, so it may interest you.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Review by boton — APPROVED** [review]
I check with the side by side editor and the experiences selector is hidden 😄

**Before this PR**
image

**After this PR**
image

Maybe we can have some conflict in our local work with @AliciaGarciaGarcia but this is ready to go.

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
