### PR TITLE
LPS-193609 Add language selector to multiple uploader

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPS-193609

No language selector was displayed in the multiple uploader.

@ambrinchaudhary This needs some frontend magic applied to it; right now the button looks terrible, it is too close to the document type selector.

image

# How can you verify that it works?

Follow the steps described in https://liferay.atlassian.net/browse/LPS-193609.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Hi @adolfopa, I don't know what was exactly missing here, I improved the margins for the language selector and now you will see it like: 
Screenshot 2023-11-27 at 13 42 44

Let me know if I can do something else. Otherwise pull LGTM.

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
Hi @adolfopa 

This error appears when you try to save file(s) but in a language different than the default

image


But if you try to add a single file, it let you (see video)



https://github.com/liferay-lima/liferay-portal/assets/47524751/d2c22847-23a5-4d78-b16a-e7bd8b185332

Can you take a look.
If not, I do not see the value on let select the language.

thanks

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Works as long as you provide a translation for the default language. The failure occurs with a single document as well if you don't provide it.

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
