### PR TITLE
LPS-162585: Incorrect Subscribe icon in the Info Panel

### PR DESCRIPTION
**Pull request by liuxingye**
Previous PR: https://github.com/liferay-lima/liferay-portal/pull/3487

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
Analyzed POSHI failures [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1983005375&testrayRunId=1983006433), they are unrelated to the changes

**Comment by liuxingye** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1277401_5074

**Comment by adolfopa** [comment]
ci:reevaluate:1277401_5074

**Comment by liuxingye** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1327401_5889

**Comment by liuxingye** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
@austinchiang Can we forward this? The errors don't look relevant to me.

**Comment by liuxingye** [comment]
Forwarded to BChan directly https://github.com/brianchandotcom/liferay-portal/pull/123657 since the failures are unrelated to the changes.

**Pull request closed without merging**
