### PR TITLE
LPS-130108 Workflow-based moderation for Message Boards

### PR DESCRIPTION
**Pull request by epgarcia**
These changes introduce a workflow-based moderation for message boards. In particular, message board messages are assigned a workflow definition that enables automatic approval when the user has a certain number of already approved messages (defined by configuration). Otherwise, messages have to be reviewed and approved by a reviewer.

I included a test to illustrate and validate the expected behavior.

@liferay-headless
@sammonsjl
@pablo-agulla

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
@liferay-lima This PR contains the same changes as #1686, which was already reviewed by @adolfopa . I only changed the LPS ticket. Please feel free to review it again, and then please forward it to Brian. Thx!

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
