### PR TITLE
LPS-133164 in some cases google gives escaped html code and we need to unescape it when we put on the fields

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-133554 : Rendering incorrectly some characters with auto-translation

In some cases the values that google translator provides are escaped and shows `& number ; ` characters (in the case of the french see the ticket)
This only happens on the text fields, on the textarea/rich text the field is unescaped automatically.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
> This only happens on the text fields, on the textarea/rich text the field is unescaped automatically.

Just for curiosity: the `textarea` is used time ago like an HTML decoder https://stackoverflow.com/questions/1912501/unescape-html-entities-in-javascript/1912522#1912522 I imagine that CKEditor works in a similar way, 

Our [unescapeHTML](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/util/html_util.js#L48) works with a DOMParser :D

**Comment by AliciaGarciaGarcia** [comment]
@boton https://github.com/liferay-lima/liferay-portal/pull/1910#issuecomment-853080970

**Comment by boton** [comment]
Front tests are failing ❌ 
I'm going to check

**Comment by AliciaGarciaGarcia** [comment]
fixed the test with @boton

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
