### PR TITLE
LPS-129698 Remove usage of Liferay.Util.selectEntityHandler in message-boards

### PR DESCRIPTION
**Pull request by kresimir-coko**
Fixes [LPS-129698](https://issues.liferay.com/browse/LPS-129698).

I've manually tested if this works, and indeed it does!
The reason just removing it works is because we handle that functionality in our modern implementation of [Modal.js](https://github.com/liferay-frontend/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L410-L420).

## Testing

1. Go to Content & Data > Message Boards
2. Create a Thread
3. Create a Category
4. In the ellipsis menu of the Thread, click on `Move`
5. Click on `Select` button in the opened page
6. A modal should open, Select the category to move the thread into
7. Profit!

https://user-images.githubusercontent.com/24564752/112968611-c1ce5900-914c-11eb-9fa0-598208898740.mp4

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Tested and working. Thanks @kresimir-coko.

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
