### PR TITLE
LPS-114260 create upgrade process for DLFileEntryType to add new column and populate data, same update pattern than on UpgradePorletPreferences to update the tables

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa 

This is the upgrade process
When LPS-113971 passes (https://github.com/liferay-lima/liferay-portal/pull/144) we can send this.

Can you review if the pattern of the update is correct?
I followed a similar path than on UpgradePortletPreferences.

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/165

**Pull request closed without merging**
