### PR TITLE
LPS-196865 Can't map DisplayPage for KnowledgeBase Article

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-196865)

As the ticket mentions, at the moment there's no way to map the display page URL in an editable element of fragment. The PR addresses the issue

## Change summary:

* Adds a new display page URL field so that the user can map it in an editable element.
* Changes InfoFormProvider and InfoFieldsValuesProvider to take it into account

## Test Scenario 1

The first test scenario addresses the issue in the steps provided in the ticket. When the user wants to map the display page URL, it will be shown for the selection.

Screenshot 2023-09-25 at 16 11 53

## Test Scenario 2

The second test scenario involves enablig feature flag for LPS-195205. When the user wants to map the display page URL, a list of all the display page templates for KBArticle will me available for selection.

Screenshot 2023-09-25 at 16 03 35

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
Hi @jkappler The below failure should be related to this pr. Could you help to take a look? Thanks.

com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest
```
 com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest > testGetInfoForm STARTED
     [exec] 
     [exec] com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest > testGetInfoForm FAILED
     [exec]     java.lang.AssertionError: [{name: authorName, type: text, uniqueId: KBArticle_authorName}, {name: authorProfileImage, type: image, uniqueId: KBArticle_authorProfileImage}, {name: categories, type: categories, uniqueId: AssetCategory_categories}, {name: content, type: html, uniqueId: KBArticle_content}, {name: description, type: text, uniqueId: KBArticle_description}, {name: displayPageURL, type: url, uniqueId: KBArticle_displayPageURL}, {name: tagNames, type: tags, uniqueId: AssetTag_tagNames}, {name: title, type: text, uniqueId: KBArticle_title}, {name: topic, type: categories, uniqueId: AssetVocabulary_33594}] expected:<8> but was:<9>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest.testGetInfoForm(KBArticleInfoItemFormProviderTest.java:86)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
```

/cc @adolfopa

**Comment by jkappler** [comment]
Hi @Jeremy-Ch, @adolfopa, will update the tests and update the PR. Thanks

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
