### PR TITLE
[TS] LPS-203255 Friendly url input is not loaded correctly when web content's language is different from site's language

### PR DESCRIPTION
**Pull request by dcarrillolf**
Friendly url input's language is not loaded correctly when web content's language is different from site's language. 
Please check:
- https://liferay.atlassian.net/browse/LPS-203255

Lima needs to check [taglib extension](https://github.com/liferay-echo/liferay-portal/pull/14606#issuecomment-1838819322)

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
@dcarrillolf please review the SF error.

**Comment by dcarrillolf** [comment]
Sorry @ambrinchaudhary , It was my vim configuration.
Should be fixed now, please check again.

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:stable

**Comment by WYZ-Issac** [comment]
Failures are unrelated

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
