### PR TITLE
LPS-138162 Remove content page translations feature flag

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR, contacted Echo QA about the failures.
FragmentsEditor#ViewDraftAutoSaved: [LPS-138232](https://issues.liferay.com/browse/LPS-138232)
DisplayPageTemplatesForWebContentArticle tests failure: [LPS-138186](https://issues.liferay.com/browse/LPS-138186)
MenuDisplay tests failure: [LPS-138234](https://issues.liferay.com/browse/LPS-138234)
PortalSmokeUpgrade#ViewPortalSmokeArchive621021 is a flaky: [LPS-136151](https://issues.liferay.com/browse/LPS-136151)

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The root cause of the above failures was reverted here: https://github.com/liferay/liferay-portal/compare/78e7911baadcc5baafca8a05b0a7db73c8c1c6f0...da5431eca174cb11ca689cd49ae7f4bd0616751a, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
[com.liferay.change.tracking.store.service.persistence.test.CTSContentPersistenceTest failure](https://testray.liferay.com/zh/home/-/testray/cases/1509069853) only occurs under this PR, will re-run it to see if it ia a flaky.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/106436

**Pull request closed without merging**
