### PR TITLE
LPS-197990 Replace usage of icon-list taglib

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
## Before:
Screenshot 2023-10-06 at 11 54 46

## After:
Screenshot 2023-10-06 at 11 55 21

### User notifications 
dropdown actions looks like before and are working correctly!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@ambrinchaudhary it looks really good, thanks you very much!!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
Checking the failures.

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
Backend approved changes ✅

**Comment by Jeremy-Ch** [comment]
Hi @marcogalluzzi @ambrinchaudhary  There is a strange failure. It should be related to this pull request. I suspect this may be a backend issue or a frontend issue. I'm not sure if these changes will affect this module. But there are indeed some related tests that fail on this PR. Could you help to confirm it?

Reproduce steps:

1. Go to Instance settings> SSO> OpenID Connect
2. Enable OpenID Connect
3. Go to System settings> SSO> OpenID Connect Provider Connection
4. Add a new Provider (If you need the configuration details please let me know)
5. Logout current user
6. Click login

Actual: The "OpenID Connect" Link can not be displayed on the login page.

Expected:

**Comment by ealonso** [comment]
Hey @Jeremy-Ch, @ambrinchaudhary, @marcogalluzzi,

I'll take a look at it, I think it is related with my changes.

Thanks for letting me know.

**Comment by ealonso** [comment]
see: https://github.com/liferay-lima/liferay-portal/pull/4773

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
