### PR TITLE
LPS-131801 Single file uploader in D&M

### PR DESCRIPTION
**Pull request by boton**
Steps to reproduce: 
- Go to Documents and Media 
- On + button, select File Upload or Google Drive shortcut

**Before** for File Upload option: 
Screenshot 2021-07-09 at 13 44 23

**After**  for File Upload option: 
Screenshot 2021-07-09 at 13 38 48

**Before** Google Drive shortcut:
image

**After** Google Drive shortcut: 
image

### CODE REVIEW

**Comment by boton** [comment]
@liuxingye Can you please help us to update the POSHI test?

Thanks in advance

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
Sorry, @liuxingye forget it for now. I'm just detecting a bug about the max file, I will try to fix it tomorrow

**Comment by boton** [comment]
@liuxingye Now it´s ready to go. Can you please help us to update the POSHI test?

Thanks in advance

**Comment by liuxingye** [comment]
ci:test:bundle

**Comment by liuxingye** [comment]
@boton I've moved all the changes to https://github.com/liferay-lima/liferay-portal/pull/2058

**Pull request closed without merging**
