### PR TITLE
LPS-121864 Migrate management toolbar v2 usages in blogs-web

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
Fixes https://issues.liferay.com/browse/LPS-121864

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by boton** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward

**Pull request closed without merging**
