### PR TITLE
LPS-132752 clay:label tag should allow for literal values

### PR DESCRIPTION
**Pull request by adolfopa**
Clay:label translates the label by default; this makes it awkward to use any label that happens to have a lang key with the same name.

We cannot change the default behaviour to keep backwards compatibility, so I've added a new "translateLabel" attribute to let callers choose the behaviour they need.

See https://issues.liferay.com/browse/LPS-132752 for the reproduction steps and a description of the issue.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by carloslancha** [comment]
Makes sense to me, not sure if it's something FI wants to implement it in other tags (and not sure if we have to add this to the model `LabelItem` too. I'd resend this to `liferay-frontend` so they can evaluate it, but LGTM!

**Comment by adolfopa** [comment]
Will resend to FI

**Pull request closed without merging**
