### PR TITLE
LPS 124161

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci.forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@bryceosterhaus can you please verify this wasn't introduced in any other places?

Thanks!

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
See #1162.

**Comment by bryceosterhaus** [comment]
@4lejandrito I fixed some related issues last week in this commit, https://github.com/brianchandotcom/liferay-portal/pull/96264/commits/454e80c42638dd2dcd240e0f877e708c9dc38880

**Pull request closed without merging**
