### PR TITLE
LPS-166066 Accessibility: title required field message

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-166066 

Screenshot 2022-10-20 at 14 14 36

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@ambrinchaudhary There is a small sf error. Other than that, it looks good.

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1347401_3026

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:reevaluate:1287401_4849

**Comment by Hanlf** [comment]
ci:reevaluate:1347401_3026

**Comment by Hanlf** [comment]
The above failures should not be related to this PR, re-run it to make sure.

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:reevaluate:1327401_6308

**Comment by ambrinchaudhary** [comment]
Manually forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/125029

**Pull request closed without merging**
