### PR TITLE
LPS-167676: Use unique ID for panel - there can be multiple structures per DLFileEntry

### PR DESCRIPTION
**Pull request by matthiasblaesing**
Each DLFileEntry can be associated with multiple metadata entries (extracted metadata, document type, metadata fields). Each of these entries is displayed in a new panel which can be individually collapsed.

The panels were identified by an id build from a fixed prefix and the fileEntryId. So when multiple panels are present, the ids are duplicated in the page. Instead of using the fileEntryId, the id of the ddmstructures is used.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
