### PR TITLE
LPS-124095 change message on exception

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @4lejandrito , can you take a look on the names of the class/methods
Thanks!

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1170.

**Pull request closed without merging**
