### PR TITLE
LPS-119619 Fix height

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Before:** 
Screenshot 2020-08-24 at 12 49 11

**After (agreed with UX):**
Translation - no available languages - AFTER

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/661

**Pull request closed without merging**
