### PR TITLE
LPS-157684 KB Vertical Navigation Bar

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Follow up of https://github.com/brianchandotcom/liferay-portal/pull/120550

The only new commit is https://github.com/liferay-lima/liferay-portal/pull/3276/commits/30a9dadfb9b513c8660dd9c2644c71935bc229c8

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1287401_3670

**Comment by ambrinchaudhary** [comment]
Send with https://github.com/liferay-lima/liferay-portal/pull/3278

**Pull request closed without merging**
