### PR TITLE
LPS-148012 Truncate text for Table view documents and media

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-148012

If a title is too long in Documents and Media, the title is not being truncated and will display the full title. To fix this, I added `text-truncate` as well as a `title` in order to have it truncated and display the full title when hovered over. 

Let me know if there are any questions or comments about this.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by boton** [comment]
Hey, @fortunatomaldonado talking with our designer Maria and @pablo-agulla, we decided don't truncate the Title. We consider the information valuable and prefer line break and display the full title.

**Pull request closed without merging**
