### PR TITLE
LPS-161160 Add VIEW action support to com.liferay.blogs resources

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-161160

Hi Team,
From Echo team, we are adding permission checks in some points of the page editor.
For example, we want that when adding a display page the user can choose only those models of which he has visibility. So, for example, a user shouldn't be able to create a Journal display page if doesn't have permission to VIEW its model resource, in this case, com.liferay.journal. This should be applied to all implementations of the info framework.
Applying this to BlogsEntry we have found that the "com.liferay.blogs" model does not support the VIEW action. In order to control these permissions also for BlogsEntry we would need to either add VIEW to the supported actions or know what the equivalent of the available permissions that we should check in this case is.
This PR adds support to the model for the action VIEW please, could you review it?
Thank you in advance! ❤️

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:blogs

**Comment by adolfopa** [comment]
ci:test:blogs

**Comment by adolfopa** [comment]
@lfbesada Shouldn't we add the new VIEW permission to guest and site member by default?

@achaparro I think this will need an upgrade process as well? Do you have any info/example on how should we write the upgrade process (if it is necessary)?

**Comment by lfbesada** [comment]
> @lfbesada Shouldn't we add the new VIEW permission to guest and site member by default?
> 
Hi @adolfopa 
I think probably yes because of aligning it with Journals and Documents that have it like that.
But, IMHO since those default permissions can't be unassigned via the UI and deployment is required to do so, maybe it's a decision that should be carefully considered.
We want to use those permissions to determine whether or not a user can create Blog display pages, and map Blogs in the page editor.
If we make it the default, all editors will be able to map and create Blog display pages and this permission cannot be unassigned without customization.
If we don't set it by default, in order for an editor to map Blogs and create Blog display pages, they will have to be specifically assigned this permission.
Regards

**Comment by adolfopa** [comment]
@lfbesada Makes sense :+1:

**Comment by adolfopa** [comment]
ci:test:blogs

**Comment by adolfopa** [comment]
ci:test:blogs

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1327401_5418

**Comment by achaparro** [comment]
Hi @adolfopa, @lfbesada,

> @achaparro I think this will need an upgrade process as well? Do you have any info/example on how should we write the upgrade process (if it is necessary)?
Yes, I think we need an upgrade process for at least:
- Update the bitwise value for ResourcePermissions associated with blog objects.
- Insert the new resourceAction permission (I am not sure if this is created automatically)

You also have to be sure that the bitwise value for VIEW permission is the same for new installations and upgraded installations, otherwise, we can get conflicts with sharding, LARs, etc.

Regarding existing upgrade processes like this one, I remember we had something almost the same but for 6.1 or older versions, maybe this one:
https://github.com/liferay/liferay-portal/blob/6.1.x/portal-impl/src/com/liferay/portal/upgrade/v6_0_12/UpgradePermission.java#L100

Other newer cases to look at are:
com.liferay.announcements.web.internal.upgrade.v1_0_2.PermissionUpgradeProcessÇ 
com.liferay.calendar.internal.upgrade.v1_0_6.ResourcePermissionUpgradeProcess

However, check carefully because these examples are not exactly for what you are looking for.

**Comment by lfbesada** [comment]
@achaparro Thanks a lot for the tips ❤️  The new resourceAction permission is automatically created but I'll analyze what you say about the bitwise value to take into account.

@adolfopa  if it's okay with you, I'll close this PR and send another one with the upgrade process. Did you want me to add VIEW as default permission for Guest and Site Member? It is that it seems to me as correct to assign it as not to do it, it is a matter of knowing if we want it or not.

Thanks!

**Comment by adolfopa** [comment]
@lfbesada Thinking twice about this, I'd prefer to assign the permission by default, so that existing installation won't get unexpected permission errors down the road. That way, only the users that care about the restriction will need to take action. Thanks!

**Pull request closed without merging**
