### PR TITLE
LPS-133083 Remove feature flag for Image Editor in DL

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-133083

Just removing FF for Image Editor in DL.

To test:
- Go to DL
- Upload an image
- Click on the actions menu of the image
- Edit Image action should appear

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
