### PR TITLE
LPS-137759 Bring text styles from AlloyEditor to Balloon Editor/CKEditor

### PR DESCRIPTION
**Pull request by diegonvs**
See the entire context here: 

https://github.com/liferay-frontend/liferay-portal/pull/1836

CI ran green but this thing is under a feature flag and I think we aren't running tests for it. I would recommend fetch and enable the feature flag before testing. Also, you need this PR: https://github.com/liferay-lima/liferay-portal/pull/2624

/cc @markocikos

### CODE REVIEW

**Comment by diegonvs** [comment]
ci:test:relevant

**Comment by diegonvs** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Review by boton — APPROVED** [review]

**Review by boton — CHANGES_REQUESTED** [review]
Sorry, @diegonvs I approved the PR the first time because the code looks good but testing it I discover something.

If you try to add style with a small text/editor the style dropdown is cut by the editor box.

image

And get worst if I scroll trying to select a style.

image

**Comment by diegonvs** [comment]
Hmmm, I think it was already fixed in https://github.com/liferay-lima/liferay-portal/pull/2624. I guess you haven't rebased with https://github.com/brianchandotcom/liferay-portal/pull/112301, which is in Brian queue yet

**Comment by boton** [comment]
> Hmmm, I think it was already fixed in #2624. I guess you haven't rebased with [brianchandotcom#112301](https://github.com/brianchandotcom/liferay-portal/pull/112301), which is in Brian queue yet

My bad, I thought it was already merged in master yesterday.

I'm going to test properly.

**Review by boton — APPROVED** [review]
Tested and working awesome, with the proper rebased PR

image

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
