### PR TITLE
LPS-129742 / LPS-129743 Add file upload and video options to item selectors

### PR DESCRIPTION
**Pull request by adolfopa**
- Add "File Upload" option to all item selectors.
- Add "External Video Shortcut" option to generic item selectors.

You can see the first change in any Item Selector (e.g. try to add a cover image to a blogs entry). For the second case, go to message boards, edit/create a thread, and in the body insert a link and choose "Browse Server". The "Documents & Media" tab will display the video shortcut option.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
