### PR TITLE
LPS-197541 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-197541

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
@adolfopa per Alberto's request this change will trigger CI to run SF in the Lima repo. Please forward if you are okay with it. If you think keeping the current logic is fine then feel free to reject the pull. Thx

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
Thanks @austinchiang Tomorrow I'll remove the commenting logic from our webhook so that we don't get duplicate comments (we may get some in the meantime).

**Pull request closed without merging**
