### PR TITLE
LPS-198713 Move deleted KB articles & folders to Recycle Bin 2

### PR DESCRIPTION
**Pull request by marcogalluzzi**
This is based on previous PR #4876 plus:

* Two commits from Brian
* 2 commits fixing what Brian says in https://github.com/brianchandotcom/liferay-portal/pull/143880
* 1 commit to fix a minor bug

Original pull request comment:
https://liferay.atlassian.net/browse/LPS-198713

Enable feature flag: [LPS-188058](https://liferay.atlassian.net/browse/LPS-188058)

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Comment by pyoo47** [comment]
ci:reopen - Temporarily reopening this pull request to test a CI forwarding fix.

**Comment by pyoo47** [comment]
ci:close

**Pull request closed without merging**
