### PR TITLE
LPS-193840 Not needed form

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-193840

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by pyoo47** [comment]
@ambrinchaudhary I had to abort the `relevant` test because it froze in CI

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
ci:stop

**Comment by SylviaLuan** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
