### PR TITLE
LPS-168391, LPS-173117 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-173117
https://issues.liferay.com/browse/LPS-168391

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The failures are not related to this PR, sent it to BChan: https://github.com/brianchandotcom/liferay-portal/pull/128966

**Pull request closed without merging**
