### PR TITLE
LPS-128003 Message Boards quick reply doesn't work

### PR DESCRIPTION
**Pull request by boton**
In this task https://issues.liferay.com/browse/LPS-126737 the commit https://github.com/liferay/liferay-portal/commit/bc85ae13a80e75fabd80e363e2f61f442e1858a2 updates the selector but not all the cases are updated in the markup.

**Steps to reproduce**

1. Go to Content and Data > Message Boards
2. Add a message boards thread
3. Click in reply button
4. Write something and Publish

**Expected result:**
The reply is published and added to the thread

**Actual result:**
Nothing happens

---

**After the fix:**

https://user-images.githubusercontent.com/67901/108201938-b553eb00-7120-11eb-97d0-a28ba58d71c4.mp4

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
hey @boton what is the rationale of this fix?

**Comment by boton** [comment]
> hey @boton what is the rationale of this fix?

I updated the description :D

**Comment by boton** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
I can't test it @boton, message boards is not working on my master. Looks fine overall but I see in the video that the Reply Button is positioned wrong (no margin) when you add a reply. Don't know if it's related to this pr (but if not maybe we can fix it if it's easy enough)

**Comment by boton** [comment]
It isn't related but I will fix it

**Comment by boton** [comment]
@carloslancha this was driving me crazy since it only happens in the admin.
I think that is unrelated to PR, anyways fixed

image

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
