### PR TITLE
Lps 120647

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @noornajj 
> https://issues.liferay.com/browse/LPS-120647
> 
> The issue here was that the wrong header title was being displayed in edit_message.jsp. When editing a reply, curParentMessage will never be null, and therefore, the "Edit" title will never be displayed.
> To fix the issue, I switched the order of the if/else if statements, that display the header title, so that it'll check whether the current message is null first, then the parent message second.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
