### PR TITLE
[TS] LPS-152930 | Robots meta tag contains unwanted language locale

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-152930
Thank you!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:stop

**Comment by bakayattila** [comment]
ci:test:sf

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
