### PR TITLE
LPS-192690 KB schedule modal 

### PR DESCRIPTION
**Pull request by sofiamendozalr**
- LPS-192690 Create empty react component for the schedule modal
- LPS-192690 Use ClayDatePicker
- LPS-192690 Add language key
- LPS-192690 buildLang
- LPS-192690 Use eventName to connect modal and opener
- LPS-192690 SF
- LPS-192690 Rename componentId
- LPS-192690 Increase modal height
- LPS-192690 Show an error message when selecting an invalid date or time
- LPS-192286 Add behavior to schedule item into the dropdown menu
- LPS-192690 Put modal buttons inside our component so we can handle them
- LPS-192690 Save the schedule date
- LPS-192690 Remove unnecessary state variable
- LPS-192690 Schedule acts as a publish action
- LPS-192690 Simplify code
- LPS-192690 Change name from scheduleDate to displayDate
- LPS-192690 Code improvements

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
