### PR TITLE
LPS-116497 Semver

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Will resend after fixing db unique restriction.

**Pull request closed without merging**
