### PR TITLE
[NOT-FOR-7.3] LPS-114569 Update macro for depot test

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:documents

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/860

**Pull request closed without merging**
