### PR TITLE
LPS-153892 Show linked videos in media gallery

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
push a baseline

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa 
The functionality is finished?

the video is show only as the preview image 

image


and when open on the carousell  it show a generic image  

image


On videos it shows the video

it's this the correct behavior?

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Yes, the two issues are independent. We can fix the preview in another PR.

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
