### PR TITLE
LPS-117460

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@adolfopa @AliciaGarciaGarcia @cgoncas

I changed the commits to [LPS-117460](https://issues.liferay.com/browse/LPS-117460) because the original issue ([LPS-105422](https://issues.liferay.com/browse/LPS-105422) is not fixed by these changes. We will investigate it separately but for now this solves @cgoncas issue.

**Comment by 4lejandrito** [comment]
@cgoncas please have a look at my changes and `ci:stop` it if necessary.

**Comment by cgoncas** [comment]
Hey @4lejandrito!!! 

I totally love the changes, the new method added to API is really useful.

Thanks!

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
Will fix and resend

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
