### PR TITLE
LPS-121648 Remove specific class and styles in favor of document_library_preview.scss

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM !

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Hi @boton @ambrinchaudhary Poshi tests caught a bug. Basically when you add a document and view it, the expanded sidebar shows up in the document view by default. See video [here](https://user-images.githubusercontent.com/8635473/96112665-95fc4580-0f15-11eb-9718-9a3acb77e02a.gif)

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
