### PR TITLE
LPS-148380 remove ff bulk translation

### PR DESCRIPTION
**Pull request by boton**
https://issues.liferay.com/browse/LPS-148380

Review here: #2899 =>  #2909

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
@adolfopa @ambrinchaudhary @austinchiang I rebase the PR and add this commit to remove the multiple pages and multiple experiences exportable

**Comment by boton** [comment]
ci:reevaluate:1317401_3350

**Comment by adolfopa** [comment]
ci:reevaluate:1317401_3350

**Review by adolfopa — APPROVED** [review]

**Comment by boton** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by austinchiang** [comment]
@boton @adolfopa test results look good here. We can forward this after we complete manual validation for the last story in the epic (https://issues.liferay.com/browse/LPS-152702)

**Comment by austinchiang** [comment]
https://issues.liferay.com/browse/LPS-153256 needs to be fixed before this is forwarded

**Comment by boton** [comment]
> https://issues.liferay.com/browse/LPS-153256 needs to be fixed before this is forwarded

Ok @austinchiang, but the issue is reproducible without the FF on master

**Comment by ambrinchaudhary** [comment]
https://issues.liferay.com/browse/LPS-153256 was fixed and merged yesterday. 
Could we move on with this FF removal?

**Comment by boton** [comment]
Yes I'm only double-checking it and it's gone :D 
image

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
