### PR TITLE
LPS-146765 Avoid exporting references that don't belong to the current group

### PR DESCRIPTION
**Pull request by adolfopa**
Each group is responsible of importing/exporting their own data, so we should avoid trying to import things that don't belong to the group being exported/imported (in the best of cases, it will do nothing).

### CODE REVIEW

**Comment by adolfopa** [comment]
This depends on https://github.com/liferay-lima/liferay-portal/pull/2711; we won't forward until that's merged.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:depot

**Comment by Hanlf** [comment]
The same failures of https://github.com/liferay-lima/liferay-portal/pull/2711#issuecomment-1031169996, no new issues from this PR.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:depot

**Comment by Hanlf** [comment]
The [above 5 failures](https://testray.liferay.com/home/-/testray/case_results/index?testrayBuildId=1608472990&testrayRunId=1608478278&cur=1&delta=20) are not related to this PR.
DepotPermission#CanDeleteImageInMG is a test fix, and js-unit-jdk8/0/0 is also occurring on other PR, which should be a flaky issue.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
I was analyzing what was happening with the staging (site/asset lib)

Y tried to reproduce the errors that @Hanlf found on the https://github.com/liferay-lima/liferay-portal/pull/2711#issuecomment-1031169996


> Issue 1: Asset library cannot be selected on connected site when staging is enabled

I can not reproduce it.

> 
> **Issue 2: Show the depot name in the Connected sites table after enabling local staging**
> Steps:
> 1. Add a new site
> 2. Add a depot and connect to the added site
> 3. Go to Asset Library Settings > Sites to assert the Name is site name in the Connected sites
> 4. Enable local staging for the depot
> 5. Go to Asset Library Settings > Sites to assert the Name column
> **Result:** The name is updated to depot name, instead of the site name

@adolfopa I do not know/think if this is a bug, because a staging AL only can be connected to a staging site

> **Issue 3: Fail to publish documents to live on the site when using DM type from depot**

It's a remote staging issue, and I think that this do not work previously

And Only FYI
The issues that I found is more about the selection from the D&M widget between the AL and the site

if the selection of the folder is made previous of the staging process, the repository selected is the live one and if after the staging is the staged one (in both live and staged)

This cause that in the first you can not add files because you have no permission to do it.
And in the second one, once you disable the staging, the portlet is unavailable.

@adolfopa , 
Knowing those issues and with more work in the future. I have not see any impediment to forward this PR.

**Comment by Hanlf** [comment]
These two failures ```com.liferay.document.library.web.internal.exportimport.portlet.preferences.processor.test.DLExportImportPortletPreferencesProcessorTes``` and 
```com.liferay.change.tracking.internal.reference.test.MissingTableReferenceDefinitionTest``` should be related to this PR, only occurs on this PR.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:depot

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia I've removed the change tracking commits, fixed some tests and added a couple more. Can you take a look again? Thanks!

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by Hanlf** [comment]
For the Depot suite failures:
The failures are not related to this PR.
The new failures are caused by LPS-144442, which has been reverted under https://github.com/brianchandotcom/liferay-portal/pull/113269.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
