### PR TITLE
LPS-142835 Use getAttribute instead of dataset since it is an AUI instance

### PR DESCRIPTION
**Pull request by victorg1991**
This is a partial revert of https://issues.liferay.com/browse/LPS-142100 that caused this bug 

In this case link is an AUI instance so we cannot replace `getAttribute('data-` with `.dataset`

### CODE REVIEW

**Review by nhpatt — APPROVED** [review]

**Comment by nhpatt** [comment]
:P

**Comment by victorg1991** [comment]
Pushed another similar fix for Wiki in this case (thanks to @tim-cao :) )

**Comment by bryceosterhaus** [comment]
Thanks for fixing this @victorg1991!

We auto-fixed getAttribute for `data-*` attributes to dataset, but turns out that in a lot of cases that involve an AUI instance, getAttribute is the only way to retrieve that information and dataset doesn't exist.

**Comment by brianchandotcom** [comment]
@victorg1991 @nhpatt I merged this in manually. Thx guys.

**Pull request closed without merging**
