### PR TITLE
[TS] LPS-146530 Document Does Not Checkin after Edit in Office 365

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-146530](https://issues.liferay.com/browse/LPS-146530)

I'd like to start with the requirement to reproduce this issue is you will need a company account at Office 365 with active license to the programs like word. I had to request it trough IS and it took a bit of time.
In case you want just reach out to me and we can schedule a call for reproduction on my machine with my credentials.

About the issue: We are using effects in a functional component in a dangerous way.
When the user edits a document trough office 365, we will open a new tab and reload the documents and media page.
The problem here, is that our Liferay.component registered modal is still alive and its open method will reference setState methods that are not part of the current React component's scope.

As per [the react documentation about useEffect](https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1) I refactored the code to make sure we handle this effect in our component proper lifecycles and also clean up after we unmount the react component.

Please review my change

**Resent after resolving the SF error**

/cc @boton @robertoDiaz

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
Hey @boton ,

I would also like to point out the same pattern can be found
https://github.com/liferay-lima/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/js/categorization/categories/EditCategories.es.js#L37-L52
and
https://github.com/liferay-lima/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/js/categorization/tags/EditTags.es.js#L37-L52

I have no idea where to test these modules in Liferay and I did not want to mix additional code refactoring with my bug LPS, as we work with the principle of 1 issue / ticket. However I wanted to point out those should be looked after as well.

Thank you

**Comment by boton** [comment]
> Hey @boton ,
> 
> I would also like to point out the same pattern can be found https://github.com/liferay-lima/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/js/categorization/categories/EditCategories.es.js#L37-L52 and https://github.com/liferay-lima/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/js/categorization/tags/EditTags.es.js#L37-L52
> 
> I have no idea where to test these modules in Liferay and I did not want to mix additional code refactoring with my bug LPS, as we work with the principle of 1 issue / ticket. However I wanted to point out those should be looked after as well.
> 
> Thank you

Thanks for bringing this out, I´m going to create 1 task to update these modules.

**Comment by boton** [comment]
See #2705

**Pull request closed without merging**
