### PR TITLE
LPS-165024 Simplify

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
In order to stop using old frontend taglib replace the usages on image gallery of frontend vertical

[LPS-165024](https://issues.liferay.com/browse/LPS-164539)

Proposed Solution
========
Replace old frontend vertical with html markup

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @boton,

Instead of adding more custom fix, I decided to replace the taglib with html markup.  With this solution we don't need to make custom fixes and we don't need to update actions.

Regards,
Eudaldo

**Review by adolfopa — APPROVED** [review]

**Review by boton — APPROVED** [review]
Thanks, @ealonso works like a charm.

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
