### PR TITLE
LPS-186307 Background process to evict files from 'new' area

### PR DESCRIPTION
**Pull request by adolfopa**
https://issues.liferay.com/browse/LPS-186307

Here is the rest of the code to manage new files using multiple store areas. This PR contains the background task to periodically clean up new (but orphan) files from the store and to evict them to the 'live' area when they're old enough.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
