### PR TITLE
LPS-152334 Unable to 'Select File' on Blogs Entry using mobile

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-152334

**Before PR**
image

**After PR**
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
