### PR TITLE
LPS-136141 Restore the configuration for Enable Only Translated Hreflangs to the instance settings

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Restore the configuration to the instance settings

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
lack of test

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
