### PR TITLE
LPS-161294 Remove the Feature Flag LPS-160919

### PR DESCRIPTION
**Pull request by marcogalluzzi**
In the issue [LPS-161294](https://issues.liferay.com/browse/LPS-161294) says that the `ItemSelectorPreview` could be removed, but I've seen it is still in use after removing the legacy `ItemSelectorRepositoryEntryBrowser`.

I don't understand what it means to remove `unmountComponentAtNode`.

Please have a look dear frontend experts!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
LGTM

> I don't understand what it means to remove unmountComponentAtNode.

I added a commit [4e93b5a](https://github.com/liferay-lima/liferay-portal/pull/3702/commits/4e93b5ae8d7315c6965c3836e7a8005e6acc7962) to remove the unmount logic only used by `ItemSelectorRepositoryEntryBrowserLegacy`.

I try to manually test over DM, Blogs, KB, and Wiki and seems to work.

This ratio is amazing :D 
image

**Comment by boton** [comment]
ci:test

**Comment by boton** [comment]
@marcogalluzzi I am going to launch a global test to double-check and add a review to our teammates at QA, I am not sure about all the uses of `ItemSelectorRepositoryEntryBrowser` across the portal. 🤞

**Comment by austinchiang** [comment]
ci:test:item-selector

**Comment by Jeremy-Ch** [comment]
ci:help

**Comment by Jeremy-Ch** [comment]
ci:test:item-selector

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:item:selector

**Comment by Jeremy-Ch** [comment]
These failures are caused by LPS-167658.

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
