### PR TITLE
LPS-197820 New module and structure for "Saved Content"

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
> As a user accessing content, I would like to save content for future reference, so that later I can easily access a list of my saved content.

For this we will need an structure to store the user _saved content_, as Pages, Blogs, Documents, Knowledge Base Articles (that is the epic needs).

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa @marcogalluzzi and @robertoDiaz 

I want your feedback about the naming of the new module and the new table

As the module I put 
**saved-content** name
and **SavedContentEntry** as the main table/entry

but I want to know your opinion about it (before making more changes)

Thanks!

**Comment by marcogalluzzi** [comment]
It looks good to me!

**Comment by AliciaGarciaGarcia** [comment]
> After reading https://liferay.atlassian.net/browse/LPS-188147 I fount "saved content" little bit "generic" and a little bit confusing.
> 
> From my understanding this is something similar to a "bookmarked" content (in fact the work bookmark appears in the LPS-188147 description some times):
> 
> > When the fragment is placed in a Display Page Template and the user clicks on the fragment, the content referenced by the display page will be saved/removed from the bookmark list.
> 
> I think that "BookmarkContent" and "BookmarkContentEntry" could have more semantics, at least for the backend entities, since Bookmark is a well know concept (and clearer for me than Saved)
> 
> Hope that it helps :)

My fear is that the word "bookmark" can be confused by the next "developer" (the user will read "saved content") on the develop and the jira component.

**Comment by robertoDiaz** [comment]
Imagin someone searching for WebContentArticles in the database 😆 (or AssetLibraryEntry)

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa 

Any thoughts on this?

**Comment by marcogalluzzi** [comment]
From my point of view, a feature name and the logic should match. Unless:

* The logic may represent different features
* The feature name has changed
* Some other strange situations

Why adding complexity to maintenance?

**Comment by robertoDiaz** [comment]
Sorry:

> From my perspective, the "user friendly" feature and the name of the logic entry should not match

it should be:

From my perspective, the "user friendly" feature and the name of the logic entry COULD not match

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
rebased with master and solved some issues with the sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
