### PR TITLE
[TS] LPS-124696

### PR DESCRIPTION
**Pull request by jonathanmccann**
Please let me know if the Search bar was not displayed on purpose so that I can relay that reasoning to the client.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]
Looks good. The semver issue is not related to this PR; I'll forward when fixed upstream.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
