### PR TITLE
LPS-189751 Change blog's placeholders color

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Before:**

Screenshot 2023-07-12 at 16 24 22

**After:** 
Screenshot 2023-07-12 at 16 22 19

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci.forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
The failures are unrelated. Forward directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
