### PR TITLE
LPS-119158 obtain ddmstructure from the metadata

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa
can you review if this solution is ok??
I think is the intended behavior  but I prefer to check with you.

Thanks!

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
