### PR TITLE
LPS-133931 display templates SEO basic UI mixing text and field values in metatags

### PR DESCRIPTION
**Pull request by boton**
[LPS-133931](https://issues.liferay.com/browse/LPS-133931) It's a preview of the basic version enabling the SEO/OG templates in Display Templates. 

Any feedback on the Feature Flag name ac20956?

The variables to update with the display template values are sending in [this format](https://github.com/liferay-lima/liferay-portal/commit/535e22a4e1a8deac0505254c34f22c96e3636094#diff-1bdc80afbb662a2785a5e17e8efcdd4b28f347cf71d78e6b736c9d0d3fad6825R27) `${variableName}` adding a space before and after when the user inserts it.

### CODE REVIEW

**Comment by adolfopa** [comment]
About the feature flag name, I think it is too generic. What about "FFSEOInlineFieldMapping"?

**Comment by boton** [comment]
> About the feature flag name, I think it is too generic. What about "FFSEOInlineFieldMapping"?

I'm going to update the name, thanks

**Comment by boton** [comment]
Updated, but I have a problem with the Feature Flag doesn't work with a configuration file :(  only works when I update the default value.

I'm going to check this with @AliciaGarciaGarcia after lunch 🥺

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See followup https://github.com/liferay-lima/liferay-portal/pull/1949.

**Pull request closed without merging**
