### PR TITLE
LPS-115826 We can safely pass the values to the frontend, it will show unmapped if there is no match

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/282.

**Pull request closed without merging**
