### PR TITLE
LPS-143182 Delete workflow instance link when deleting the translation entry

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-143182 on removal of the translation entry, delete workflow instance link too
- LPS-143182 when deleting the journal article remove the workflow instance link too

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
