### PR TITLE
LPS-182364 MBThread UAD deletion errors

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
The original changes, with some fixes that should avoid the test errors and a rebase.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
Directly forward to Bchan. https://github.com/brianchandotcom/liferay-portal/pull/138581

**Pull request closed without merging**
