### PR TITLE
LPS-122663 Not the Site language is shown on the language selector button during multiple file upload

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@IstvanD Can you take a look at the SF issue? Thanks!

**Comment by IstvanD** [comment]
Hi @adolfopa 

The SF issues are not related to the fix.
they have been fixed since then.

**Comment by IstvanD** [comment]
https://github.com/liferay-lima/liferay-portal/pull/982

**Pull request closed without merging**
