### PR TITLE
LPS-121332 Adding upgrade to add the new columns

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @4lejandrito 

The only significant change I've made is in the last commit. The original upgrade assigned the same UUID to all rows; I've changed it so that an unique UUID is used. I've squashed it to keep the PR clean.

Other than that, I've also squashed some minor SF issues in 0d45dae and ca0b487. Also check the impl of `deleteStagedModels` in the repository (previously it was empty, now throws exception).

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
