### PR TITLE
LPS-130633 Add div to keep alert message above the buttons

### PR DESCRIPTION
**Pull request by naraandrade**

### CODE REVIEW

**Comment by naraandrade** [comment]
ci:test:sf

**Comment by naraandrade** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
I'm only updating the markup to fit in the solution for message boards. 
See #1770.

Thanks @naraandrade

**Pull request closed without merging**
