### PR TITLE
LPS-144295 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-144295

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:translation

**Comment by austinchiang** [comment]
cc @adolfopa

**Comment by austinchiang** [comment]
ci:reevaluate:1287401_2079

**Comment by austinchiang** [comment]
From a functional test perspective this pull looks good.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
