### PR TITLE
LPS-154163 Support auto tagging on update for blogs

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1277401_3662

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by adolfopa** [comment]
@austinchiang Those two blog tests that are failing, I cannot reproduce locally (I get the draft save message). Can you guys take a look in case tests need to be updated (or I'm missing something)? Thanks!

**Comment by austinchiang** [comment]
Hey @adolfopa this should be a bug. With the new commits a blog entry can be manually saved as a draft but the autosave feature doesn't work anymore (the text is missing). I was able to manually reproduce the issue.

draft

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
