### PR TITLE
LPS-187945 | Master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://liferay.atlassian.net/browse/LPS-187945

### CODE REVIEW

**Review by austinchiang — CHANGES_REQUESTED** [review]
@WYZ-Issac please use the Select All option to select files to bulk copy instead of selecting each individual entry. You may need to remove the default picture folder first before doing that

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:stop

**Pull request closed without merging**
