### PR TITLE
Master | LRQA-59087, LRQA-46679

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-59087
https://issues.liferay.com/browse/LRQA-46679

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:forward

**Comment by jpince** [comment]
ci:forward

**Comment by Hanlf** [comment]
Should be a flaky issue, rerun it.

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
