### PR TITLE
LPS-151526 make the cacheControl value be required

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
There is a Bug on the configuration part

https://issues.liferay.com/browse/LPS-151870

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Failures look legit.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
