### PR TITLE
LPS-121870 Migrate v2 usages in depot/depot-web

### PR DESCRIPTION
**Pull request by julien**
When we sent [https://github.com/liferay-lima/liferay-portal/pull/1478](https://github.com/liferay-lima/liferay-portal/pull/1478), we forgot to migrate one of the usages.

**Test plan**:
- From the global menu, select the **Applications** tab
- Navigate to **Asset Libraries**
- Create a new Asset Library
- Set the **Sites** tab
- In the **Connected Sites** section click on the **Add** button
- Select a site
- From the global menu, select the **Control Panel** tab
- Navigate to **Users and Organizations**
- Select the **Test Test** user
- In the **Roles** tab, scroll down to **Asset Library Roles**
- Click on the **Select** button

**Additional Notes**:

Currently it seems that filtering is not working properly in `master`,
so this has the same issue, so I created a [Jira Ticket](https://issues.liferay.com/browse/LPS-128902)

### CODE REVIEW

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
@liferay-lima sorry for the noise, closing this because it's actually already been done in [this PR](https://github.com/jonmak08/liferay-portal/pull/2135) which should get forwarded here at some point.

**Comment by julien** [comment]
ci:close

**Comment by julien** [comment]
PS: @liferay-lima , this comment 

> Currently it seems that filtering is not working properly in master,
so this has the same issue, so I created a Jira Ticket

Might still be something you want to look at.

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay-lima/liferay-portal/pull/1608

**Pull request closed without merging**
