### PR TITLE
LPS 130271 bug DM multiple upload with DE

### PR DESCRIPTION
**Pull request by boton**
@adolfopa Please I need a review and maybe help on this part f8e214c81c2af06993202914adf38aa4fc302fc1

Is there a more effective way to pass the new `submittable` taglib attribute through all the java stuff to DDMFormTemplateContextFactoryImpl.java to get it back on the js side?

Thanks in advance

Please don't forward it, I'm going to forward it to DE team :D

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]
Looks good, but we need to send this to the DE team (liferay-dataengine) for review. If they've already approved this, then go ahead and do a ci:forward.

**Comment by boton** [comment]
See liferay-data-engine#416.

**Pull request closed without merging**
