### PR TITLE
LPS-200202 Show "copy link" action even when sharing is disabled

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPS-200202

When disabling sharing, the "copy link" action is omitted as well. We want to always show the copy action, no matter the state of sharing.

# How am I fixing it?

I had to move the logic that checks Sharing status around, and simply include the lone "Copy" action when disabled.

# How can you verify that it works?

1. Enable feature flag LPS-197477.
2. Upload a document and click on its dropdown actions. A "Share" group should be available, containing two actions: "Invite collaborators" and "Copy link".
3. Go to system settings > Sharing and disable sharing.
4. Go back to the same document, click in the dropdown actions and verify that only the "Copy Link" action is available.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
I tested this, here are the results: 

**When Sharing is enabled**, this is how it appears in DM or Blogs: 
Screenshot 2023-11-07 at 10 51 59

Screenshot 2023-11-07 at 10 52 08

**When Sharing is disabled**, Share dropdown or action is hidden, and Copy Link is part of the main dropdown: 
Screenshot 2023-11-07 at 10 52 39

Screenshot 2023-11-07 at 10 52 23


That is great, I also confirmed with Maria that this works. Thanks @adolfopa

**Review by ambrinchaudhary — APPROVED** [review]

**Review by ambrinchaudhary — CHANGES_REQUESTED** [review]
Hey @adolfopa, I tested this again, and when Sharing is disabled, the Copy Link button doesn't work, it doesn't copy the link. But it works properly when Sharing is enabled. 
Could you please check what is missing?

**Review by AliciaGarciaGarcia — APPROVED** [review]
LGTM

**Comment by adolfopa** [comment]
@ambrinchaudhary Added an additional commit with the fix.

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
@adolfopa just thinking... should the js be included only depending on the feature flag?

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1377401_15353

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
checking

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
Hi @adolfopa  Some upgrade tests catch an issue that should be related to this PR. Could you help to take a look? Thanks.

Full Log see: https://testray.liferay.com/reports/production/logs/2023-11/test-1-39/test-portal-acceptance-pullrequest(master)/8265/functional-upgrade-tomcat90-mysql57-jdk8_stable/0/2/jenkins-console.txt.gz?authuser=0
```
2023-11-08 10:39:21.364 ERROR [http-nio-8080-exec-5][PortletServlet:109] Unable to process portlet com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_EpfqzfURlZId: org.apache.jasper.JasperException: java.lang.NullPointerException
[beanshell] javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.NullPointerException
[beanshell] 	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:298) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:114) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:611) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:627) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:497) ~[portal-kernel.jar:?]
[beanshell] 	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:300) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.document.library.web.internal.portlet.DLPortlet.render(DLPortlet.java:70) ~[bundleFile:?]
[beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:118) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:49) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:115) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:62) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.
```

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
Maybe what I've found is related to the errors appeared in tests.

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Failures are unrelated.

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
