### PR TITLE
LPS-168158 DM - Remove dev FF (AUI)

### PR DESCRIPTION
**Pull request by Jeremy-Ch**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:document

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1327401_6912

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
QA has finished the review. No failures are related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
Awesome ratio!!
image

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
@Jeremy-Ch @WYZ-Issac @Hanlf @austinchiang could you please check if these failures are related to this pull? Thanks!

**Comment by Jeremy-Ch** [comment]
Hi @ambrinchaudhary Could help to confirm if the below error is related to this pr? Thanks.
```[beanshell] 2022-11-17 08:24:40.240 ERROR [http-nio-8080-exec-3][ComboServlet:374] Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_EpfqzfURlZId:/o/document-library-web/document_library/js/legacy/main.js because its content type is not CSS or JavaScript
[beanshell] 2022-11-17 08:24:40.241 ERROR [http-nio-8080-exec-3][ComboServlet:374] Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_EpfqzfURlZId:/o/document-library-web/document_library/js/legacy/upload.js because its content type is not CSS or JavaScript
     [exec]     LIFERAY_ERROR: Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_EpfqzfURlZId:/o/document-library-web/document_library/js/legacy/main.js because its content type is not CSS or JavaScript
     [exec]     LIFERAY_ERROR: Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_EpfqzfURlZId:/o/document-library-web/document_library/js/legacy/upload.js because its content type is not CSS or JavaScript```

**Comment by ambrinchaudhary** [comment]
Hey @Jeremy-Ch, yeah that must be related to this PR but I don't get the error, because I removed those files....

**Comment by Jeremy-Ch** [comment]
> Hey @Jeremy-Ch, yeah that must be related to this PR but I don't get the error, because I removed those files....

@ambrinchaudhary Some smoke upgrade tests failed with this error when I check the failures. Could you help to take a look? Thanks.

[error log](https://testray.liferay.com/reports/production/logs/2022-11/test-1-39/test-portal-acceptance-pullrequest(master)/1715/functional-upgrade-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)
Failed tests:
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive70106](https://testray.liferay.com/zh/home/-/testray/case_results/2059648738?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2059647612%26testrayRunId%3D2059647678%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7310](https://testray.liferay.com/zh/home/-/testray/case_results/2059648872?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2059647612%26testrayRunId%3D2059647678%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive621021](https://testray.liferay.com/zh/home/-/testray/case_results/2059648953?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2059647612%26testrayRunId%3D2059647678%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[LocalFile.DMWidget#SelectAssetFromSecondWidgetInvokesSecondManagementToo...](https://testray.liferay.com/zh/home/-/testray/case_results/2059648758?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2059647612%26testrayRunId%3D2059647678%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7413](https://testray.liferay.com/zh/home/-/testray/case_results/2059648754?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2059647612%26testrayRunId%3D2059647678%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

Error:
``` LIFERAY_ERROR: Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_wcVmGX0VHYUT:/o/document-library-web/document_library/js/legacy/main.js because its content type is not CSS or JavaScript
     [exec]     LIFERAY_ERROR: Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_wcVmGX0VHYUT:/o/document-library-web/document_library/js/legacy/upload.js because its content type is not CSS or JavaScript
     [exec]     LIFERAY_ERROR: Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_wcVmGX0VHYUT:/o/document-library-web/document_library/js/legacy/upload.js because its content type is not CSS or JavaScript
     [exec] 
     [exec] 
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/PortalSmokeUpgrade.testcase[ViewPortalSmokeArchive70106]:140
     [exec]     	at com.liferay.poshi.runner.selenium.LiferaySeleniumUtil.assertNoPoshiWarnings(LiferaySeleniumUtil.java:221)
     [exec]     	at com.liferay.poshi.runner.PoshiRunner.test(PoshiRunner.java:271)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
     [exec]     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
     [exec]     	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.poshi.runner.PoshiRunner$RetryTestRule$RetryStatement.evaluate(PoshiRunner.java:382)
     [exec]     	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
     [exec]     	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
     [exec]     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
     [exec]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
     [exec]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
     [exec]     	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
     [exec]     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
     [exec]     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
     [exec]     	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
     [exec]     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
     [exec]     	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
     [exec]     	at org.junit.runners.Suite.runChild(Suite.java:128)
     [exec]     	at org.junit.runners.Suite.runChild(Suite.java:27)
     [exec]     	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
     [exec]     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
     [exec]     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
     [exec]     	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
     [exec]     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
     [exec]     	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
     [exec]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]     	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]     	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]     	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]     	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]     	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]     	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
     [exec]     	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
     [exec]     	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
     [exec]     	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]     	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)```

**Comment by Jeremy-Ch** [comment]
> Hey @Jeremy-Ch, yeah that must be related to this PR but I don't get the error, because I removed those files....

Hi @ambrinchaudhary Can we igonre this error? this error just appears in some smoke upgrade tests. 
```beanshell] 2022-11-17 08:23:24.088 ERROR [http-nio-8080-exec-2][ComboServlet:374] Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_wcVmGX0VHYUT:/o/document-library-web/document_library/js/legacy/main.js because its content type is not CSS or JavaScript
[beanshell] 2022-11-17 08:23:24.089 ERROR [http-nio-8080-exec-2][ComboServlet:374] Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_wcVmGX0VHYUT:/o/document-library-web/document_library/js/legacy/upload.js because its content type is not CSS or JavaScript
     [exec]     LIFERAY_ERROR: Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_wcVmGX0VHYUT:/o/document-library-web/document_library/js/legacy/main.js because its content type is not CSS or JavaScript
     [exec]     LIFERAY_ERROR: Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_wcVmGX0VHYUT:/o/document-library-web/document_library/js/legacy/upload.js because its content type is not CSS or JavaScript
[beanshell] The top level build is alive.
     [exec] 
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive70106] STANDARD_ERROR
     [exec]     java.lang.Exception: 
     [exec]     ##
     [exec]     ## 3 Liferay Exceptions were thrown
     [exec]     ##
     [exec] 
     [exec]     LIFERAY_ERROR: Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_wcVmGX0VHYUT:/o/document-library-web/document_library/js/legacy/main.js because its content type is not CSS or JavaScript
     [exec]     LIFERAY_ERROR: Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_wcVmGX0VHYUT:/o/document-library-web/document_library/js/legacy/upload.js because its content type is not CSS or JavaScript
     [exec]     LIFERAY_ERROR: Skip com_liferay_document_library_web_portlet_DLPortlet_INSTANCE_wcVmGX0VHYUT:/o/document-library-web/document_library/js/legacy/upload.js because its content type is not CSS or JavaScript
     [exec] 
     [exec] 
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/upgrades/PortalSmokeUpgrade.testcase[ViewPortalSmokeArchive70106]:140
     [exec]     	at com.liferay.poshi.runner.selenium.LiferaySeleniumUtil.assertNoPoshiWarnings(LiferaySeleniumUtil.java:221)
     [exec]     	at com.liferay.poshi.runner.PoshiRunner.test(PoshiRunner.java:271)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
     [exec]     	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]     	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
     [exec]     	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.poshi.runner.PoshiRunner$RetryTestRule$RetryStatement.evaluate(PoshiRunner.java:382)
     [exec]     	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
     [exec]     	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
     [exec]     	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
     [exec]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
     [exec]     	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
     [exec]     	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
     [exec]     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
     [exec]     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
     [exec]     	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
     [exec]     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
     [exec]     	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
     [exec]     	at org.junit.runners.Suite.runChild(Suite.java:128)
     [exec]     	at org.junit.runners.Suite.runChild(Suite.java:27)
     [exec]     	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
     [exec]     	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
     [exec]     	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
     [exec]     	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
     [exec]     	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
     [exec]     	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
     [exec]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]     	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]     	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]     	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]     	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]     	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]     	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]     	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]     	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]     	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
     [exec]     	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
     [exec]     	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
     [exec]     	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]     	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]     	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec]     	at java.lang.Thread.run(Thread.java:745)```

**Comment by Jeremy-Ch** [comment]
ci:test:document

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
> > Hi @ambrinchaudhary Can we igonre this error? this error just appears in some smoke upgrade tests.
> 
> Yeah I think they can be ignored

@Jeremy-Ch please add to our ignore list

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Pull request closed without merging**
