### PR TITLE
[NOT-FOR-GA4] LPS-102564 Add custom icons for applications that have one

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by austinchiang** [comment]
Hey @adolfopa @ambrinchaudhary we'll have to fix our Poshi tests for this pull to pass. Is this supposed to be included in GA4? If not we can hold onto it until the end of the week before sending

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
ci:test:depot

**Comment by adolfopa** [comment]
@austinchiang It is ok to wait, this isn't required for GA4. In the meantime, let me know if we need to make any changes in case some failures are real (vs tests that need to be updated).

Thanks!

**Comment by austinchiang** [comment]
@adolfopa Great! We're currently refactoring our tests, and if they look good we'll forward it once the GA4 coast is clear.

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/357

**Pull request closed without merging**
