### PR TITLE
LPS-137328

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-137328

In order for the solution to be tested according to the reproduction steps in LPS-137328, it also requires commits from COMMERCE-7063: https://github.com/liferay-commerce/liferay-portal/pull/1666

Keep original implementation, but add deletion when the urlTitle is STRINGPOOL.BLANK

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
@liferay-lima , please prioritize this PR if possible.

**Comment by adolfopa** [comment]
Just started reviewing :)

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
