### PR TITLE
LPS-169193

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

This is the follow-up of https://github.com/liferay-lima/liferay-portal/pull/3777
with the changes requested by Brian on https://github.com/brianchandotcom/liferay-portal/pull/127039#issuecomment-1332041469

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
