### PR TITLE
LPS-167099 HR_198 label history icon

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-167099

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
Do we need to forward the accessibility bugs to FI or directly to Brian?  What is the workflow?

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
