### PR TITLE
LPS-145442 Change labels for bulk translation

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-145442 create and change labels to meet design
- LPS-145442 buildLang

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
functional-tomcat90-mysql57-jdk8/4 failed at connecting mysql, re-run it.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
