### PR TITLE
LPS-161264 When generating FriendlyURL on Display Pages with other site/asset Libraries add the group name to identify them.

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-161264 change test to adapt to new behavior
- LPS-161264 on case of the group of the site and the group of the file are different return groupName/urlTitle instead urlTitle or /fileEntryId
- LPS-161264 now we can receive a friendlyURL composed by /groupName/urlTitle so we must decompose it and obtain the file from the correct group

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Don't we need to update com.liferay.document.library.internal.friendly.url.resolver.FileEntryFriendlyURLResolverImpl as well? That class is used to resolve urls received by WebServerServlet.

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa 

I could not find a user case that introducing the display page link 
`http://localhost:8080/web/sitename/d/asset-library-43494/al_doc?redirect=%2Fweb%2Fsitename%2Fcontentpage
`Uses the `FileEntryFriendlyURLResolverImpl`

And if you can provide me one the changes should be made on the `WebServerServlet` because on that file we split all the friendly urls by `/` 

More info is needed please.

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa 
I tested what we talked on slack and 2 things:


1) we are using the old way of downloading the file
2) It works because do not use the display page prefix to call the url so if we use the new, the behavior should not be modified.


https://user-images.githubusercontent.com/47524751/186426988-db2b499d-93a9-4f06-a804-04836e5b8a11.mp4

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Thanks for the info. Everything looks good then.

**Comment by adolfopa** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Pull request closed without merging**
