### PR TITLE
Create a mechanism to allow get the proper Portlet Ratings classname

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi @liferay-lima 

About the solution:

The problem here is that in some cases the ratings tag is been called with alternative file entry names (in this case LiferayFileEntry).

In this use case I see that it this was the caller: https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/fragment/fragment-impl/src/main/java/com/liferay/fragment/internal/renderer/BaseContentFragmentRenderer.java#L61-L79

When the file entry is rendered following the jira ticket steps the ClassedModel in the infoItem is the mentioned LiferayFileEntry (and I assume that change that could be a little bit tricky).

The only questions I have is about the naming of the new interface an the package (I do not like the className particle) but I haven't found better patters or option to that.

Do you have any alternative?

Thanks!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@robertoDiaz There's already an interface that does the same: `InfoSearchClassMapper`. It is used in the info framework to map between `FileEntry` and `DLFileEntry`. Can you take a look at that and see if it can be used here?

**Comment by robertoDiaz** [comment]
Sure, 

If I understand it well I have to create a new InfoSearchClassMapper typing it with LiferayFileEntry and return the DLFileEntry.class.getName(). 

Is it right?

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by austinchiang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139594

**Pull request closed without merging**
