### PR TITLE
LPS-122540 methods to know if we are selecting only one item and show the info of it.

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1416.

**Pull request closed without merging**
