### PR TITLE
LPS-202129 Do not allow now valid keywords in Redirections

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
Hi @robertoDiaz,

There are two failures caused by this pull request.
**Issue 1:**
[com.liferay.redirect.search.test.RedirectEntrySearchTest
](https://testray.liferay.com/home/-/testray/case_results/2463014417)
```
[Jenkins Console](https://testray.liferay.com/reports/production/logs/2023-11/test-1-34/test-portal-acceptance-```
pullrequest(master)/5286/modules-integration-mysql57-jdk8/4/1/jenkins-console.txt.gz?authuser=0)
[beanshell]      [exec] com.liferay.redirect.search.test.RedirectEntrySearchTest > testSearchSortingBySourceURL FAILED
[beanshell]      [exec]     com.liferay.portal.kernel.exception.LayoutFriendlyURLException
[beanshell]      [exec]     	at com.liferay.portal.model.impl.LayoutImpl.validateFriendlyURLKeyword(LayoutImpl.java:189)
[beanshell]      [exec]     	at com.liferay.portal.service.impl.LayoutLocalServiceHelper.validateFriendlyURLKeyword(LayoutLocalServiceHelper.java:429)
[beanshell]      [exec]     	at com.liferay.redirect.service.impl.RedirectEntryLocalServiceImpl._validate(RedirectEntryLocalServiceImpl.java:454)
[beanshell]      [exec]     	at com.liferay.redirect.service.impl.RedirectEntryLocalServiceImpl.addRedirectEntry(RedirectEntryLocalServiceImpl.java:86)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)
[beanshell]      [exec]     	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
[beanshell]      [exec]     	at com.liferay.portal.service.ServiceContextAdvice.invoke(ServiceContextAdvice.java:51)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
[beanshell]      [exec]     	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:55)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
[beanshell]      [exec]     	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:70)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
[beanshell]      [exec]     	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40)
[beanshell]      [exec]     	at com.sun.proxy.$Proxy492.addRedirectEntry(Unknown Source)
[beanshell]      [exec]     	at com.liferay.redirect.search.test.RedirectEntrySearchTest.testSearchSortingBySourceURL(RedirectEntrySearchTest.java:344)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
[beanshell]      [exec]     	at java.lang.Thread.run(Thread.java:750)

```
**Issue 2:**
[LocalFile.Redirect#DefaultRedirectCanNotOverrideLocalizedRedirect
](https://testray.liferay.com/home/-/testray/case_results/2463011391)

- Add a site Test Site Name with two pages Test Source Page and Test Destination Page
- Navigate to Test Site Name > Configuration > Redirection
- Add a new Redirect with the following parameters:Source URL: hu/google  Destination URL: https://google.hu/
- Visit to http://localhost:8080/web/test-site-name/hu/google

Expected behaviour: Redirection occurs to https://google.hu/
Actual behaviour: Stay on http://localhost:8080/web/test-site-name/hu/google with error page Not found

**Comment by robertoDiaz** [comment]
hey @adolfopa 

I've fix the broken test and also add more test, If you are ok I could push it to Brian

**Comment by robertoDiaz** [comment]
@SylviaLuan 

The second case has to be changed.

We do not allow language paths in the sourceURL anymore (it should fit the page friendlyURLs pattern and this paths are not allowed there)

Thanks!

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@robertoDiaz LGTM. Not sure if this can be forwarded (does QA need to update any poshi tests?)

**Comment by robertoDiaz** [comment]
> @robertoDiaz LGTM. Not sure if this can be forwarded (does QA need to update any poshi tests?)

I think that this test ([LocalFile.Redirect#DefaultRedirectCanNotOverrideLocalizedRedirect](https://testray.liferay.com/home/-/testray/case_results/2463011391)) should be changed (or removed) since it's using a language path in the sourceURL and now it is not allowed anymore.

**Comment by robertoDiaz** [comment]
@adolfopa agreed with the test removal/change.

Removing the on hold label

**Comment by Jeremy-Ch** [comment]
Updated the POSHI test and the new pull request see: https://github.com/liferay-lima/liferay-portal/pull/4957

cc @robertoDiaz

**Pull request closed without merging**
