### PR TITLE
LPS-158880 if no view permission return false

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-158880 if no view permission return success false
- LPS-158880 prefer reference instead util
- LPS-158880 if call is from GET request

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translation

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
