### PR TITLE
LPS-160255 KB Updates: remove dev FF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Most of the stories on this epic were developed without FF, so there are just few cases under it. 

QA Team: please review. Actually I have no idea how should I remove FF from your tests, so apologises if I made it wrong and feel free to change the pull.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:knowledge-base

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The knowledge-base suite failures are not related to this PR.
The ci:test:relevant failures are not related to this PR.

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1397401_1937

**Review by adolfopa — APPROVED** [review]

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
> The knowledge-base suite failures are not related to this PR.
> The ci:test:relevant failures are not related to this PR.

By this comment I get that QA approves this pull... and there are also 2 more approvals so I'm going to forward it. Thanks all!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failures are not related to this PR, sent it to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/126974

**Pull request closed without merging**
