### PR TITLE
LPS-155219 bug file limit missing title

### PR DESCRIPTION
**Pull request by boton**
#### Missing title:
image

#### Missing panel collapsible:
image

#### Title:
image

#### Panel collapsible:
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
