### PR TITLE
LPS-157985 Adds supports for status and display views on Item Selector

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
In order to allow use ItemSelectorViewDescriptor in more places instead of having custom jsps, adds support to set status for the entity and allow specify the views, at this moment we always have the tree views (table, card and descriptive)

Also, it creates a new item selector for DDMStructures and it replaces the customs selector in DL and WC. It is using the new method to specify the views.

[Link to the issue](https://issues.liferay.com/browse/LPS-157985)

Proposed Solution
----
* Adds new method on **ItemSelectorViewDescriptor.ItemDescriptor** called **getStatus** and implemented as default returning null, use this method on card, table and descriptive view to show the status.
* Adds new method on **ItemSelectorViewDescriptor** called **getDisplayViews** and implemented as default returning the tree views and use it on **ItemSelectorViewDescriptorRendererManagementToolbarDisplayContext**
* Adds a new item selector for DDMStructures and replace the usages for DM and WC, and removes the unnecessary code  

How to test it on Documents and Media
---
Step-by-Step:

1. Go to DM
2. Creates a new Metadata Set
3. Creates a Document Type
4. Click on Additional Metadata Fields and Select a new one

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
tested in DM, code LGTM, thanks!

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
After talk to eudaldo, this change is expected. We will adapt the failing tests.

**Comment by ealonso** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Manually forward please see: https://github.com/brianchandotcom/liferay-portal/pull/120469

**Pull request closed without merging**
