### PR TITLE
LPS-158906 themeDisplay needs to have a httpServletRequest so create it and take the theme display of it

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-158906 do not create a theme display everytime we want to use it inside the for
- LPS-158906 themeDisplay needs to have a httpServletRequest so create it and take the theme display of it

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
