### PR TITLE
LPS-131159 Include item selector preview tests again

### PR DESCRIPTION
**Pull request by carloslancha**
PR reviewed at https://github.com/liferay-lima/liferay-portal/pull/1802 already

Rebasing and resending here because https://github.com/brianchandotcom/liferay-portal/pull/101743

Updating npm-script version to support `css` flies in jest tests, so we're including item selector preview tests again.

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
I love when source format format things that ci will complain about...

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
The item selector in Blogs is now working for me :D
The tests is green ✅ 

Ready to forward!

**Comment by boton** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
https://github.com/liferay-lima/liferay-portal/pull/1842

**Pull request closed without merging**
