### PR TITLE
LPS-186688 Fail when trying to copy into staged site

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-186688

I applied the suggestions in https://github.com/brianchandotcom/liferay-portal/pull/136256 as an additional commit.

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
