### PR TITLE
[TS] LPS-165023 Added required field attribute to editor for KB templates

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Dear team,
Could you please help me to review this PR for the ticket [LPS-165023](https://issues.liferay.com/browse/LPS-165023)?
And leave your comments.
@sontruongces
Thanks,
Tai

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Review by boton — APPROVED** [review]
Thanks, @TaiPhamLR @sontruongces, LGTM.

image

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
@TaiPhamLR @sontruongces please take care of updating the Jira issue (adding the PR, moving the workflow) next time, thanks in advance.

**Pull request closed without merging**
