### PR TITLE
LPS-154730: Expose ERC in DocumentsFolder

### PR DESCRIPTION
**Pull request by javierdearcos**
Solved conflicts with rebase so you can move forward with the review. Original PR: https://github.com/liferay-lima/liferay-portal/pull/3291

Original message from @sergiojimcos:
---
Hi guys, I've opened this PR because most of the service changes I've made are related to your components. I'm going to introduce what are the changes that you should review. Our team has verified that the errors appearing in the CI are not related, but we still want your approval, you can see https://github.com/liferay-frontend/liferay-portal/pull/2548. You can check the description in the link of the PR from frontend-infra. Let's give you a little context.

### Main Objective
The main of this PR is to expose `externalReferenceCode` in DocumentsFolder. For that reason I have made some changes in the service part and in the API part.

### Service part
The main changes that you should review, are the following:

- Those changes related to `documentlibrary` in portal-impl. These changes are related because we add the new argument using `externalReferenceCode`.
- In the same way, in those modules, I have implemented two new methods to obtain a DLFolder using the `externalReferenceCode`, which are `fetchFolderByExteranlReferenceCode` and `getFolderByExteranlReferenceCode`.
- As there are some changes that affect the service part of DLFolder, I want to be sure that the Staging mode works correctly, some changes are added.
- New Upgrade process, if the `externalReferenceCode` is `null` or "", the data base will save the `externalReferenceCode` using the `UUID`.

### API part

However, this part can be ignored, because it is reviewed by our team members.

If you have any problem or any doubt, please contact me 😃

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-154730

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1357401_2129

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by AliciaGarciaGarcia** [comment]
Hi @javierdearcos and @sergiojimcos 
I want to know if letting the old methods (addFolder without externalReferenceCode) it's for something you plan to deprecate or delete on next PR or is something made with purpose.

**Comment by javierdearcos** [comment]
I was afraid of removing them for all the infrastructure that is in the middle with the Repository interface and implementations, as they are not our components, we don't have all the knowledge and I didn't want to cause you trouble.

I would leave it for the next iteration to be sure we don't break anything. But maybe Brian request it now...

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1307401_3910

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Checked ci:test:documents results [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1917616165&testrayRunId=1917631645), there's no one related to this PR.

**Comment by liuxingye** [comment]
Checked ci:test:relevant results [here](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1917346417&testrayRunId=1917346621), there's no Poshi failures related to this PR.

**Comment by AliciaGarciaGarcia** [comment]
Thanks @liuxingye !!

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
Hi guys! I'm going to close this PR because I don't have any permissions to modify Javi's PR and rebase the new cahnges. I will link the new PR

**Comment by sergiojimcos** [comment]
New PR: https://github.com/liferay-lima/liferay-portal/pull/3321

**Comment by sergiojimcos** [comment]
ci:close

**Pull request closed without merging**
