### PR TITLE
LPS-162409 bookmarks-service: Update status fields when create and update a bookmarks

### PR DESCRIPTION
**Pull request by gustavolimav**
https://issues.liferay.com/browse/LPS-162409

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — CHANGES_REQUESTED** [review]
@gustavolimav This is not correct. `updateStatus` assumes it is only used for the recycle bin events; for example, when the status is approved, and activity of type `TYPE_RESTORE_FROM_TRASH` will be created.

You need to update `updateStatus` so that it works correctly for other status changes.

**Comment by gustavolimav** [comment]
@adolfopa could you please take a look again? I refactored that based on journalArticleLocalService [addArticle](https://github.com/liferay/liferay-portal/blob/7ad75178c91535c9beabafac629472d9a44f8d87/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L625) and [updateArticle](https://github.com/liferay/liferay-portal/blob/7ad75178c91535c9beabafac629472d9a44f8d87/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L5889-L5892).

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by gustavolimav** [comment]
ci:forward

**Comment by gustavolimav** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1287401_4381

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
