### PR TITLE
LPS-169658 some errors with tests checking the Existing External Reference Code

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
@sergiojimcos @LuismiBarcos As we talked (thanks for the HELP) i will sent this PR with changes on the services to check the existence on KBArticle and WikiPage of the ERC and the group WITH the version

the revert is partial to this commit 02bcc1ecfcb5fdc37d0e7c691268c6ca7c7b4065 

- LPS-169658 fix test, blog entry can not have same urlTitle
- LPS-169658 throw proper exception
- LPS-169658 no longer needed
- LPS-169658 baseline
- LPS-169658 baseline
- LPS-169658 rename exception to match others
- LPS-169658 baseline
- LPS-169658 partial revert of LPS-163008 Remove_validateExternalReference method in LocalServices
- LPS-169658 rename exception
- LPS-169658 autoSF
- LPS-169658 buildService

This is a follow PR of https://github.com/liferay-lima/liferay-portal/pull/3775

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:test:blogs

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1397401_1970

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
liferay/ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:test:blogs

**Comment by Hanlf** [comment]
The knowledge-base, blogs and wikis suite failures are known issue, not related to this PR.

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia What has changed since the previous PR?

**Comment by AliciaGarciaGarcia** [comment]
> @AliciaGarciaGarcia What has changed since the previous PR?

Brian ask me to delete the Exception classes that now are not in use :
https://github.com/liferay-lima/liferay-portal/pull/3784/commits/b6b9f9a519c0c70d2ca52a424e0f9d8594a80ba4
and proper baselines

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
