### PR TITLE
LPS-120076 Make Sites app impl independent of Asset Libraries

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:forward @adolfopa taking the liberty since you commented `ci:forward` earlier :smile:

**Comment by jpince** [comment]
not sure if you were aware, but next time you can comment `ci:forward` again instead of `ci:test:relevant`. It will skip any test suites (in this case, SF) that have already passed.

**Pull request closed without merging**
