### PR TITLE
LPS 115230 Builder pattern

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:Stop

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/270.

**Comment by JorgeFerrer** [comment]
ci:test:sf

**Pull request closed without merging**
