### PR TITLE
LPS-200661 Always use container name in "Copy From" field

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPS-200661

# How can you verify that it works?

Follow the steps described in https://liferay.atlassian.net/browse/LPS-200661.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa 
Can  you resend the commit with the correct LPS (the last 0 is not needed :P ) for tracking purpouses?

Thanks!!

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
