### PR TITLE
LPS-205929 Site applications show up in the Asset Libraries

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPS-205929

Extra (unsupported) applications show up in the depot dashboard.

# How am I fixing it?

By making the panel app filter a regular DS component. Depending on
the `activate` lifecycle method of the controller is not reliable as
the component is not immediate.

# How can you verify that it works?

Follow the steps described in https://liferay.atlassian.net/browse/LPS-205929.

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]
Nice work!

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1357401_5137

**Comment by austinchiang** [comment]
ci:reevaluate:1357401_5137

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
