### PR TITLE
LPS-201681 Enable image AI-creator from instance & site settings

### PR DESCRIPTION
**Pull request by robertoDiaz**
Added the new options in the view:

Intance settings level:

Captura de pantalla 2023-11-14 a las 12 58 48

Group Seettings level:

Captura de pantalla 2023-11-14 a las 13 01 04

More relevant changes in the PR:

1. Changed the configuration naming in methods and values (from *ICreatorOpenAI* pattern to *AICreatorChatGTP*) in order to make it consisten with *AICreatorDALLE* naming
2. Added a upgrade process to migrate current saved configurations at company and group level
3. Updated the current tests
4. Added the FF: LPS-196648

### CODE REVIEW

**Comment by robertoDiaz** [comment]
`> Task :apps:ai-creator:ai-creator-openai-test:testIntegration

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyAndGroupEnabledWithAPIKeyInCompany STARTED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyAndGroupEnabledWithAPIKeyInCompany PASSED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyAndGroupEnabledWithAPIKeyInGroup STARTED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyAndGroupEnabledWithAPIKeyInGroup PASSED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyAndGroupEnabledWithAPIKeyNoJournalPortlet STARTED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyAndGroupEnabledWithAPIKeyNoJournalPortlet PASSED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyAndGroupEnabledWithoutAPIKey STARTED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyAndGroupEnabledWithoutAPIKey PASSED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyDisabledGroupEnabled STARTED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyDisabledGroupEnabled PASSED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyEnabledGroupDisabled STARTED

com.liferay.ai.creator.openai.web.internal.editor.configuration.test.AICreatorOpenAIEditorConfigurationTest > testAICreatorToolbarCompanyEnabledGroupDisabled PASSED`

Related tests seems to work in my end

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
Thank you @ambrinchaudhary for the insights.

Now the info message is show as it should:
Captura de pantalla 2023-11-14 a las 14 02 38

**Review by adolfopa — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:stop

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
Failures are unrelated

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
