### PR TITLE
LPS-127938 Using the right preview to embed GIFs properly

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
Tests are broken by these changes. I'll fix them and update this pull request.

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
