### PR TITLE
LPS-167717 Manually triggering scheduled jobs invokes all jobs

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The web interface triggers the job invocation through SchedulerResponseManagerImpl#run. The method uses a call to SchedulerEngineHelper#getScheduledJob to fetch the SchedulerResponse, which is used to access the message, that is then send over the liferay MessageBus.

The message is received by SchedulerEventMessageListenerWrapper, which uses the message parts DESTINATION_NAME, JOB_NAME and GROUP_NAME to find the right scheduled job to invoke.

If DESTINATION_NAME is missing, the complete check will be skipped and all jobs will be triggered by this message. If JOB_NAME or GROUP_NAME are missing a NullPointerException could be raised.

To fix this described parts need to be added to the message in QuartzSchedulerEngine#getScheduledJob.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by matthiasblaesing** [comment]
Hi @AliciaGarciaGarcia,

thank you for the hint. Could you point me into the right direction which is the right github repository to look for?

**Comment by AliciaGarciaGarcia** [comment]
> Hi @AliciaGarciaGarcia,
> 
> thank you for the hint. Could you point me into the right direction which is the right github repository to look for?

https://github.com/liferay-core-infra

**Comment by matthiasblaesing** [comment]
Thank you - moved to https://github.com/liferay-lima/liferay-portal/pull/3691

**Pull request closed without merging**
