### PR TITLE
LPS-155980 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-155980

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
A couple of things @david-gutierrez-mesa:
- I didn't find an "Asset Framework" testray.main.component so I didn't add a property under those modules (If it is Info Framework you can add it in later)
- Though I listed the test modules in the table [here](https://issues.liferay.com/browse/LPS-155980) I decided not to add test.properties to them since I don't think it's necessary
- For the asset-list modules I only added the "Asset Lists" Testray component. There are Asset List/Collections tests under Collections.testcase but they are under the Segmentation component 🤔 I'm not really sure why that is but if we also want to run those tests we can add that property in later. I'll let you guys decide on that 
- It seems "Asset Lists" == "Collections" == "Content Sets". Maybe we can refactor/standardize the language across all our tests since we are still using all of those terms and it could get a bit confusing

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
