### PR TITLE
LPS-152103 Integration test for canonical url are not valid for DPT

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-152103

Hi @liferay-lima 
This is a follow-up pull request of https://github.com/liferay-lima/liferay-portal/pull/2943
It adds integration tests for Layout SEO links of contents.
Could you please review it?
Thanks a lot! :heart:

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
