### PR TITLE
LPS-183504 Add mimssing parameters

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failed backend test should be related to this pull request
[com.liferay.content.dashboard.web.internal.portlet.action.test.GetContentDashboardItemsXlsMVCResourceCommandTest](https://testray.liferay.com/home/-/testray/case_results/2288212729?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2288207687%26testrayRunId%3D2288211626%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
[Full Log](https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/7981/modules-integration-mysql57-jdk8/1/7/jenkins-console.txt.gz?authuser=0)
```
testServeResource: org.junit.ComparisonFailure: expected:<[-]> but was:<[1970-01-01T00:02:30]>  at org.junit.Assert.assertEquals(Assert.java:117)  at org.junit.Assert.assertEquals(Assert.java:146)  at com.liferay.content.dashboard.web.internal.portlet.action.test.GetContentDashboardItemsXlsMVCResourceCommandTest._assertWorkbookRow(GetContentDashboardItemsXlsMVCResourceCommandTest.java:177)  at com.liferay.content.dashboard.web.internal.portlet.action.test.GetContentDashboardItemsXlsMVCResourceCo...
```

/cc @robertoDiaz

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
