### PR TITLE
LPS 165780 BUG iten selector accept wildcard

### PR DESCRIPTION
**Pull request by boton**
## Issue: https://issues.liferay.com/browse/LPS-165780

It's a draft because the last commit 71571fe5106ef3f52911b38bb205bbf6cb592111 is only for testing proposes we need to drop it before forward.

### Before the PR
image

---

### After the PR
image
image
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by boton** [comment]
Ignore the `liferay/ci:test:sf` failing until we remove the testing commit 71571fe5106ef3f52911b38bb205bbf6cb592111

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/3662

**Pull request closed without merging**
