### PR TITLE
LPS-190824 The directly selected image is not shown on Page Content panel

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-190824

Hi Team
The bug I am fixing was caused by [this pull request](https://github.com/liferay-lima/liferay-portal/pull/4451) because the new return type doesn't have the classNameId property. So in this pull request, I am adding it.
Could you please review my proposed solution?
Thanks in advance!

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@lfbesada Isn't this the same as https://github.com/liferay-lima/liferay-portal/pull/4493? Can you please talk with [victorg1991](https://github.com/victorg1991) about it? Yours seems to include additional changes.

**Comment by lfbesada** [comment]
Hi @adolfopa Thanks! We both solved the bug on our own without realizing that it was duplicated.
The solution is the same, I just added a variable to cache the classNameID (I don't understand why we never cache it if it would never change once the DB is created) and I updated the return type javadoc, IMHO, is useful.
As the ticket that is duplicated is this one, I will close this PR.
I am sorry for the noise.
Regards

**Pull request closed without merging**
