### PR TITLE
LPS-128657 Don't add the documentType fields twice

### PR DESCRIPTION
**Pull request by victorg1991**
Hey!

This PR adds the metadata fields into the infoform of fileentry

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @victorg1991,
The integration test failure about `com.liferay.document.library.web.internal.info.item.provider.test.FileEntryInfoItemFieldValuesProviderTest.testGetInfoItemFieldValues` should be related to your commits, could you please take a look? Thanks!

**Comment by victorg1991** [comment]
Hey @Hanlf, thanks for the heads up! I'll take a look asap

**Comment by victorg1991** [comment]
Should be fine now :)

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
