### PR TITLE
LPS-132769

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-132769

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
As I was said, the PortalSmokeUpgrade tests should fail at this bug: https://issues.liferay.com/browse/LPS-134610

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
Hi @lfbesada 

Can you check the test failing testWronglyLocalizedSiteLayoutPublicFriendlyURLWithTagsMapping2 in the case it's caused by the pr?

Thanks!

**Comment by lfbesada** [comment]
Hi @AliciaGarciaGarcia 

I have run all that class tests on the branch of this PR and they have worked ok, so it should not be the cause of the failure.

Thanks!

**Pull request closed without merging**
