### PR TITLE
LPS-126848, et. al | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-127168
https://issues.liferay.com/browse/LPS-127169
https://issues.liferay.com/browse/LPS-126829
https://issues.liferay.com/browse/LPS-127820
https://issues.liferay.com/browse/LPS-126848
https://issues.liferay.com/browse/LPS-127169

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by Hanlf** [comment]
AppBuilderWorkflow#ValidateFormViewModes should be flaky, rerun it.

**Comment by Hanlf** [comment]
ci:forward

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1470

**Pull request closed without merging**
