### PR TITLE
LPS-167651 bug DM drag and drop files on folders

### PR DESCRIPTION
**Pull request by boton**
# Issue https://issues.liferay.com/browse/LPS-167651

### Before PR (after dropping file/files on folder)
image

### After PR (after dropping file/files on folder)
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by boton** [comment]
This PR meed be synced with https://github.com/liferay-lima/liferay-portal/pull/3679

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
I'll apply this fix in https://github.com/liferay-lima/liferay-portal/pull/3679

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
