### PR TITLE
LPS-138676 Fixed logic in isRootFolder method

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-138676

/cc @javalosjr96

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
