### PR TITLE
LPS-162097 Index Expired documents.

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
Currently expired documents are not searchable in DXP
[Link to story or ticket](https://issues.liferay.com/browse/LPS-162097)

Proposed Solution
========
I have indexed expired documents

Steps to Verify:
----------------
1. Expire a document
1. Go to the Content Dashboard
2. The document should be visible.

Screencaps:

https://user-images.githubusercontent.com/5776822/188123238-81c85277-f8ef-4042-82e4-7901ef09bbf0.mp4

Notes
========
No integration tests have been included in this PR, because I don't understand how D&M Search tests work, but if you give me some guide on it, I will try to add it

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
[com.liferay.portal.modules.ModulesStructureTest.testScanGradleFiles](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/88919//testReport/com.liferay.portal.modules/ModulesStructureTest/testScanGradleFiles) is a comment failure.
Seems the second failure is a flaky failure, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
The failures should be not related to this PR, I will wait for the result of the last attempt, and if it still fails, I will send it directly to BChan.
cc/ @adolfopa

**Comment by Hanlf** [comment]
The above failures are not related to this PR, sent this pull directly to BChan: https://github.com/brianchandotcom/liferay-portal/pull/122754.

**Pull request closed without merging**
