### PR TITLE
LPS-135269 Add test to "Allow site admins to configure if hreflang tags in pages are filled only for the translated languages"

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Rebase and resend because mixed PRs causing failures

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
