### PR TITLE
LPS-152255 Changing the wiki title string handler

### PR DESCRIPTION
**Pull request by titokenzo**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@titokenzo I'm ok with the wiki changes. Can you send the PR to @liferay-echo so that they can take a look at the changes to the fragment renderer? Thanks!

**Comment by titokenzo** [comment]
New pull request containing just the LPS 152255
https://github.com/liferay-lima/liferay-portal/pull/3000

**Pull request closed without merging**
