### PR TITLE
LPS-171687 Removes descriptive view for the moment

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-171687)

Adapt asset list entry item selector to use default item selector views.

## Proposed solution

In order to make possible adapt asset list entry item selector view to use default item selector views it adds a new interface called **TableItemView** on **item-selector-api**. In that way we can customize the table view of item selector. Also, it includes a default implementation **DefaultTableItemView**, it is going to be used if the item selector didn't provide a new one.

Result with default view

Window_y_Home_-_Liferay_DXP__Editing_

Result after customization

Home_-_Liferay_DXP__Editing_

Please let me know what do you think abut this approach.

Thanks!!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:reevaluate:1377401_7584

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
The above failures are not related to this PR, sent it to BChan:https://github.com/brianchandotcom/liferay-portal/pull/128336

**Pull request closed without merging**
