### PR TITLE
LPS-156162, LPS-156470, LPS-150909 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-156162
https://issues.liferay.com/browse/LPS-156470
https://issues.liferay.com/browse/LPS-150909

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
