### PR TITLE
LPS-164539 Replace frontend vertical cards with markup, since those are old taglib and are going to be deleted.

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
In order to stop using old frontend taglib replace the usages on item selector and document library

[LPS-164539](https://issues.liferay.com/browse/LPS-164539)

Proposed Solution
========
Since it is not possible to reuse clay:cards, replace old frontend taglib with the markup that we have in old taglibs, in that way we can remove the old taglibs.

----------

**NOTE** IMHO, We should start a conversation with frontend infra about supporting the customizations that we have in DL and Item selector on clay:cards or if we want to keep the logic as it is.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @adolfopa,
I think there is a bug see https://issues.liferay.com/browse/LPS-163589

**Comment by ealonso** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
@ealonso stable and relevant have passed, so I think this can be forwarded manually.

**Comment by ealonso** [comment]
Manually forward here: https://github.com/brianchandotcom/liferay-portal/pull/124043

**Pull request closed without merging**
