### PR TITLE
LPS-164481, LPS-164246, LPS-162852, LPS-162970, LPS-164773, LPS-164774, LPS-164777 | Master 

### PR DESCRIPTION
**Pull request by boton**
https://issues.liferay.com/browse/LPS-164481
https://issues.liferay.com/browse/LPS-164246
https://issues.liferay.com/browse/LPS-162852
https://issues.liferay.com/browse/LPS-162970
https://issues.liferay.com/browse/LPS-164773
https://issues.liferay.com/browse/LPS-164774
https://issues.liferay.com/browse/LPS-164777

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:knowledge-base

**Comment by boton** [comment]
ci:test:knowledge-base

**Comment by ambrinchaudhary** [comment]
failures look related, as they are failing repeatedly. Will need to take a look at them

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
- LocalFile.KBAdmin#CanRemoveParentArticle - fixed the test (assertion value was missing)
- LocalFile.KBFolder#CanDeleteFolderViaNavigationPane - Known issue we can fix later
- LocalFile.KBExportImport#ViewImportedKBArticleWithImagesAsKBAttachments - Feature flag needs to be added to test https://issues.liferay.com/browse/LPS-165142 (can do later)
- LocalFile.KBNotification#CanSubscribeToHomeFolderViaNavigationPane - Known Bug https://issues.liferay.com/browse/LPS-164218
- LocalFile.KBPageTree#PageTreeIsCollapsedAfterOpeningProductMenu - Known issue we can fix later https://issues.liferay.com/browse/LPS-164609

cc @ambrinchaudhary @boton

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/3578

**Pull request closed without merging**
