### PR TITLE
LPS-202025 Able to download file with no VIEW permission over folder

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPS-202025

With permission inheritance enabled, and no VIEW permission granted over the parent folders, it should not be possible to download documents (even if DOWNLOAD is granted on them).

# How can you verify that it works?

Follow the steps described in https://liferay.atlassian.net/browse/LPS-202025.

### CODE REVIEW

**Comment by robertoDiaz** [comment]
LGTM

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
