### PR TITLE
[TS] LPS-173562 Adding Friendly URL redirect configuration for locale.prepend.friendly.url.style=2

### PR DESCRIPTION
**Pull request by danielmijarra**
Hello @liferay-lima,
this pull fixes https://issues.liferay.com/browse/LPS-173562.
The Friendly URL Redirection configuration functionality now also applies to locale.prepend.friendly.url.style=2.

We used a _ConfigurationProvider_ pattern, following Brian comment ([https://github.com/brianchandotcom/liferay-portal/pull/131955#issuecomment-1476577928](https://github.com/brianchandotcom/liferay-portal/pull/131955#issuecomment-1476577928))

Previous pull: [https://github.com/liferay-lima/liferay-portal/pull/4100](https://github.com/liferay-lima/liferay-portal/pull/4100) ([https://github.com/brianchandotcom/liferay-portal/pull/131955](https://github.com/brianchandotcom/liferay-portal/pull/131955))

Please let me note if you have any questions.

cc: @adolfopa @robertoDiaz

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
There are some FriendlyURLService Poshi tests failing on this PR, I'll continue to investigate these poshi test failures after finishing some urgent tasks.

**Comment by Hanlf** [comment]
Sent to BChan directly with the Poshi test fix: https://github.com/brianchandotcom/liferay-portal/pull/133875

**Pull request closed without merging**
