### PR TITLE
LPS-197792 DM Edit Categories modal

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
### BEFORE: 

Screenshot 2023-10-02 at 12 12 52

### AFTER: 

Screenshot 2023-10-02 at 13 16 32

**(scroll keeps working)**
Screenshot 2023-10-02 at 12 59 58

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:document

**Review by adolfopa — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Checking failures

**Comment by austinchiang** [comment]
Failures unrelated

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
