### PR TITLE
[TS] LPS-159600 | Fix missed name change and justification for reserved parameter

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @liferay-lima !

This pr address two issues:

1. One missed case of name change (from `p_l_skip_redirect` to `skipRedirect`) caught in https://github.com/brianchandotcom/liferay-portal/pull/122320. 
2. A question about the relevance of having `skipRedirect` be a reserved parameter, asked in https://github.com/brianchandotcom/liferay-portal/pull/122320#issuecomment-1230602289.

About the 2nd issue, the justification for making `skipRedirect` reserved is that this parameter is not attached or namespaced by a portlet. It can be relevant to a variety of requests. 

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by ricardocousolr** [comment]
Hi @adolfopa,

Maybe this pr needs to be manually forwarded given the continuous problems to do it using the ci.

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
@ricardocousolr one last try. If this doesn't work I'll forward it manually.

**Comment by ricardocousolr** [comment]
Hi @adolfopa, shall we try again or give up?

**Comment by adolfopa** [comment]
Please no :-D

I'll forward it myself.

**Pull request closed without merging**
