### PR TITLE
LPS-195737 Remove feature flag

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-195737

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-195737.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
