### PR TITLE
LPS-121857 Migrate v2 usages in adaptive-media/adaptive-media-web

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-lima,

Attached is an update for http://issues.liferay.com/browse/LPS-121857.

**Test Plan:**

1. Login to Liferay
2. Click on the **Applications Menu**
3. Click on **Adaptive Media** under **Configuration**

adaptive-media

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
LGTM checked and working @carloslancha feel free to forward it directly

**Review by boton — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Hey @jonmak08 thx for the pr!

After testing it everything seems to work fine but the button "Clear" on the filters results bar, which does nothing on click:

image

Could you please take a look? Thx!!

**Comment by jonmak08** [comment]
Hey @carloslancha,

It looks like the clear link never worked to begin.  I just tested on master and this is what I got:
adaptive-media-master

I added a fix for the clear link with https://github.com/liferay-lima/liferay-portal/pull/1488/commits/620859e16eb055ca34df129f00927818741aa3e1 and it looks like it resolved the issue, but I do not know if that fix is the correct one.

This is the outcome of my fix:
adaptive-media-fix

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Hey @jonmak08 thx! Didn't know it wasn't working before, makes sense that we need to add `clearResultsURL` param. So LGTM!

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
