### PR TITLE
LPS-165400 | [HR_155] Add title to buttons

### PR DESCRIPTION
**Pull request by M-IgorFranca**
Related Issue: https://issues.liferay.com/browse/LPS-165400

Related HR: HR_155
Add title to two buttons: Search and Back button

Reproduction Steps:

Turn on JAWS and navigate to Documents & Media.
Navigate "Menu button to the top left. Click on Content and Data-> Documents & Media->Document types ->Add new Document types.
Navigate the toggle buttons beside the side navigation bar.
Click on "Builder" button. Focus on "search icon" in the side bar.
Expected Results
HR_155: 1.Search button in side bar 2.Back button for all the elements in the fields section

Actual Results
HR:_155: Significant image buttons do not have proper alt text Example: Search button

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by M-IgorFranca** [comment]
this [PR](https://github.com/liferay-echo/liferay-portal/pull/9930) fix the search button

**Comment by M-IgorFranca** [comment]
warning:

Exist one questions not answer [here](https://github.com/ethib137/liferay-portal/pull/72#issuecomment-1281318712), so i would like to know if my fix is ok.

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
For future pulls related to data-engine,  please send to https://github.com/liferay-data-engine

**Pull request closed without merging**
