### PR TITLE
[TS] LPS-152732 Use the original URI by default as a partial layoutFriendlyURL match should not take over it

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Can you please review?
https://issues.liferay.com/browse/LPS-152732

Thanks,
Balázs

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@balazssk Can you take a look at the SF errors?

**Comment by balazssk** [comment]
on it

**Pull request closed without merging**
