### PR TITLE
LPS-151302 component to Set a limit on file size and mimetypes at asset library level

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-151302

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by boton** [comment]
@ambrinchaudhary I resolve the issue with add/remove buttons here https://github.com/liferay-lima/liferay-portal/commit/a956d34541c9f4d09f527406f6a8bac42931e5e0.

Did we want to synchronize the main state with that of the inputs?

If we don't want it, with this commit I'm switching from component filed internal state to uncontrolled inputs https://github.com/liferay-lima/liferay-portal/commit/19e268df686b553ad1572b5257f8e988daaecec1 but the values of {mymeType, size} sizesList of FileSizePerMimeType will be always ''. But maybe is a better idea to update the sizesList of FileSizePerMimeType when some field change.

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
