### PR TITLE
LPS-163680 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-163680

cc @Jeremy-Ch

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:lima

**Comment by liuxingye** [comment]
Forwarded directly to BChan https://github.com/brianchandotcom/liferay-portal/pull/123720.

**Pull request closed without merging**
