### PR TITLE
LPS-166870 Clean up templates view

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

This pr is a clean up of the templates jsp. No logic changes.

# How do I test this?

Go to the templates tab. If you:
- Can create templates,
- See the templates listed in the search container,
- Search for templates, and
- Delete templates, both individually and in bulk,

then everything works as expected.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:reevaluate:1277401_5594

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Fixed conflict and push-forced. No other changes.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1387401_4588

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
