### PR TITLE
LPS-137660 Use draft layout if available

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:close

**Comment by adolfopa** [comment]
Will send an alternative solution.

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/2167

**Pull request closed without merging**
