### PR TITLE
LPS-157505 rename jsp to more adecuate to KB module

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
First part of renaming jsp to more adequate to KB module

this task will be done in parts to be sure the changes do not create to many issues.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1307401_3909

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
`LocalFile.KBAdmin#CanViewImageInKBAfterMovingToFolder` AND `LocalFile.KBAdmin#CanViewVideoInKBAfterMovingToFolder`Was caused by this PR.
made changes on the test

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
