### PR TITLE
LPS-143549

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Lima Team,

The original fix got reverted because it caused a regression ([LPS-143834](https://issues.liferay.com/browse/LPS-143834)). I added a [new commit](https://github.com/liferay-lima/liferay-portal/commit/1149cf7bbaf1efcdadfa888e283ea3c207a4614f) on top of this which fixes the regression, and should fix any other potential regressions as well).

The reason for the regression is that the new API that we used, omits several types of groups that the old API returned (all of which deal with UserGroups or Organizations in some way):

- Groups that the user's UserGroup is a member of
- Groups that represent an Organization that the user is _directly_ a member of
- Groups that the user's _direct_ Organization is a member of

By studying the SQL query that was generated by the old API, I was able to gain confidence that this is a comprehensive List of groups that were returned by the old API but not the new one. You can see that query here: https://gist.github.com/mbowerman/45ef6b0218f3f9c05b181a8547a596e1

The new commit adds all of those Groups back in.

Feel free to forward this to the USM team if you think it would be more appropriate to send it to them.

https://issues.liferay.com/browse/LPS-143549

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@drewbrokke Can you guys take a look at this PR? I'm ok with the changes, but I think this affects you directly.

**Comment by drewbrokke** [comment]
@adolfopa looking now. Thanks for the heads up.

@mbowerman this seems like a good situation for a new test case as well.

**Comment by drewbrokke** [comment]
@mbowerman this change seems reasonable, but I generally favor trying to change as little as possible. I see two other possible approaches:

1. The absolute simplest approach would be to add an additional check to this conditional (https://github.com/liferay/liferay-portal/blob/c04d47b24343ed4ce170a2db63de56b0c28e2f60/modules/apps/depot/depot-service/src/main/java/com/liferay/depot/internal/security/permission/contributor/DepotRoleContributor.java#L59): 
```java
_groupLocalService.hasUserGroup(userBag.getUserId(), roleCollection.getGroupId())
```

This approach does not address the concern that the UserBagFactory logic may miss some other types of groups in the future, but is the smallest impact and least likely to cause other regressions.

2. A slightly more complex approach would be to register a `UserBagFactoryImpl` service that wraps the original one and returns the original UserBag with the `userGroupIds` value updated to include depot groups.

Thoughts?

**Comment by mbowerman** [comment]
Hi @drewbrokke,

I'm not really too keen on solution (1) because, like you mentioned, it doesn't solve the problem for other potential types of groups in the future, or even other userBag calls that we may make in the depot module in the future. I think the developer should be able to reasonably expect that `userBag.hasUserGroup()` will return accurate information about whether the user is a member of that group.

(2) sounds like a good solution, but it may take me a while to implement because I'm not very well-versed in OSGi.

**Comment by mbowerman** [comment]
Hey @drewbrokke I sent you a new pull request at https://github.com/liferay-usm/liferay-portal/pull/390. I solved it in a different way than you suggested, because it is a lot of new infrastructure to implement solution (2) and therefore may cause problems when backporting. I believe the solution I implemented should be safe. Let me know whether you agree with it.

**Pull request closed without merging**
