### PR TITLE
LPS-183713 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-183713

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:item-selector

**Comment by austinchiang** [comment]
ci:test:item-selector

**Comment by austinchiang** [comment]
ci:stop

**Pull request closed without merging**
