### PR TITLE
LPS-132497 Replace Image Editor crop icon with text

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-132497

Implementing design change to avoid confuse interaction with crop icon.

To test:
- Upload an image in DL
- Edit it with Image Editor

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
