### PR TITLE
LPS-140020 Add multiple experience support for translation export

### PR DESCRIPTION
**Pull request by adolfopa**
There's a feature flag in the frontend that prevents users from triggering these changes (old behavior has been preserved). Safe to merge.

### CODE REVIEW

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia only the last 5 commits need review.

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Rebased on top of current master (prerrequisite changes were merged).

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
