### PR TITLE
LPS-163051 Create services to retrieve paginated file versions for DL 

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to story](https://issues.liferay.com/browse/LPS-161544)

Tango Team is working in improving the information panel in content dashboard, and one of these improvements is adding the version history of the elements in the sidebar.  Since an element can have many versions, we would like to provide the user the ability to paginate through them.

But we have noticed that there are no services in DL that provide this feature, and we can only retrieve all versions at a time

## Proposed Solution

Since persistance layer already has a method to retrive the DLFileVersions by status, range and orderByComparator, our proposal is to implement it. In case of external repositories, the complete version list would be retrieved by calling the existing method.

## Steps to Verify:

There are no steps to verify this since it's planned for the coming weeks

## Change summary:

* Change FileVersionVersionComparator so that it can be used when calling services
* Implement the new method at local service layer
* Implement the new method in generic FileEntry class
* Integration test for retrieving versions by range
* Integration test for retrieving versions by range and status

## Notes:

* As mentioned, external repositories are not paginates
* Change in comparator requires a major bump in version 
* Versions are retrieved always in descending order, like the existing method that retrieves by status
* We didn't change existing methods, but now we could use the new comparator to order results at persistance layer instead of after retrieving them

## Acknowledments

Thanks to @robertoDiaz, @AliciaGarciaGarcia and @adolfopa  for their suggestions ❤️ 

Please let me know if I should make some changes

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@cgoncas

**Comment by AliciaGarciaGarcia** [comment]
@jkappler 
Semantic version error ([modules-semantic-versioning-jdk8/0/0](https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93333//consoleText)) looks relevant for this PR

On other hand, LGTM

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@jkappler Looks good. When you finish fixing the baseline error, you can forward it directly -- no need for this to go through lima again.

**Comment by jkappler** [comment]
Update the PR with the baseline. Thanks @AliciaGarciaGarcia and @adolfopa!

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1337401_2239

**Comment by liuxingye** [comment]
Analyzed the relevant [failures](https://testray.liferay.com/zh/home/-/testray/case_results?testrayBuildId=1983878511&testrayRunId=1983878539), they are unrelated to the changes in this PR. Forwarded it directly to BChan https://github.com/brianchandotcom/liferay-portal/pull/123471.

**Pull request closed without merging**
