### PR TITLE
LPS-163275 KB article preview social ratings layout

### PR DESCRIPTION
**Pull request by boton**
### Before PR
image

### After PR
image

I decide to inline the `kb_article_social_bookmarks.jsp` 8b7d5639b9e2f935d020002331a81c984438b176 if you prefer to keep it in a separate file feel free to drop the commit.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by boton** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
