### PR TITLE
Lps 182364

### PR DESCRIPTION
**Pull request by SamZiemer**
https://liferay.atlassian.net/browse/LPS-182364
Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/138581

Resending this LPS as a simplified version as Brian noted the changes to service builder cannot be backported.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:reevaluate:1327401_1762

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hi @austinchiang, can these changes be forwarded? The failures do not look related.

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@SamZiemer there was a semver issue. I fixed it and resent this PR in https://github.com/liferay-lima/liferay-portal/pull/4656

**Pull request closed without merging**
