### PR TITLE
LPS-170143 | Fix test DepotApplication#CanNotSelectDisabledAssetsFromItemSelector

### PR DESCRIPTION
**Pull request by jaimelr10**
Description: Fix test `DepotApplication#CanNotSelectDisabledAssetsFromItemSelector` to catch correct error message (`Info:This application is not supported for Asset Libraries. Please, go back to scope selection.`) instead of default one (`Info:Web Content is disabled for this scope.`).

Jira Ticket: https://issues.liferay.com/browse/LPS-170143

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:test:sf

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Review by austinchiang — APPROVED** [review]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
