### PR TITLE
Lps 139816

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-139816

I have been working on this fix with @robertoDiaz and there was a discussion about this issue through PTR-2680

Originally, the issue here was that a new page cannot be created with a name that is the same as an old friendly URL. However, after the changes made by LPS-143165, the page can now successfully be created but the increment of the friendly URL is not consistent with a duplicate FURL that is being currently used. If the duplicated FURL is a currently used one, then the name will be incremented by "i" but if the FURL is an old one, then it's incremented by "-i". (Please see updated ticket steps for clarity)

To fix the issue, I created an extra validation step for layoutFriendlyURLs against the friendlyURLEntry table.

Update: updated this PR with suggested changes [from this comment](https://github.com/liferay-lima/liferay-portal/pull/2575#discussion_r776238908)

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
@liferay-lima I'll review this today

**Comment by robertoDiaz** [comment]
Just started reviewing :)

**Comment by noornajj** [comment]
Hello @robertoDiaz, is there an update on this PR?
Thank you

**Comment by robertoDiaz** [comment]
I sent you a PR yesterday.

Please see https://github.com/noornajj/liferay-portal/pull/4

**Comment by robertoDiaz** [comment]
ci:close

**Pull request closed without merging**
