### PR TITLE
LPS-127935 Doclib database table DLFileEntry renamed during upgrade process

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

The failed tests are related to the fix.

Thank you and best regards,
István

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
