### PR TITLE
LPS-148526 Update the icons in depot dashboard

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-148526

We need to update the icons of import/export and use the new staging icon.

### Before this PR
image

### After this PR
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_1948

**Comment by boton** [comment]
ci:reevaluate:1267401_1948

**Comment by Hanlf** [comment]
The failure should not be related to this PR, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
flaky issue, re-ran it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
