### PR TITLE
LPS-129804 Adds cite as an allowed tag in blogs content

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:stable

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Checked with @AliciaGarciaGarcia and it looks good to us.

**Comment by boton** [comment]
ci:forward

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:reevaluate:1067401_8257

**Comment by epgarcia** [comment]
@boton @adolfopa I tried to re-evaluate, but it still fails. However, the errors also occur in #1672 (with unrelated changes).

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:forward

**Pull request closed without merging**
