### PR TITLE
LPS-153216 DM add icons to the file entry detail dropdown

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Before:**
Screenshot 2022-05-10 at 14 48 49

**After:**
Screenshot 2022-05-10 at 13 55 33

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_2125

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
