### PR TITLE
LPS-134293 Extract css to shared component

### PR DESCRIPTION
**Pull request by carloslancha**
Followup https://github.com/liferay-lima/liferay-portal/pull/1911

In this PR we're extracting all document preview css to a shared module `document-library-preview-css` so we can import it from the modules that makes use of it, as well as we enable the possibility to reuse any preview in other modules, as asked in https://github.com/liferay-lima/liferay-portal/pull/1898/

To test:
- Upload an image, a pdf, a video and an audio file to document library
- Click on each document name to access to its preview

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
Thanks, @carloslancha tested and working but looks safe to wait till the 7.4 is out :D

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
