### PR TITLE
LPS-131801 Single file uploader in D&M

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Steps to reproduce: 
- Go to Documents and Media 
- On + button, select File Upload or Google Drive shortcut

**Before** for File Upload option: 
Screenshot 2021-07-09 at 13 44 23

**After**  for File Upload option: 
Screenshot 2021-07-09 at 13 38 48

**Before** Google Drive shortcut:
image (3)

**After** Google Drive shortcut: 
Screenshot 2021-07-09 at 10 34 14

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Hi @boton & @ambrinchaudhary, for the failing POSHI cases, we can use `UploadCommonFile.uploadCommonFileHiddenNoMouseOver` instead of `UploadCommonFile`  for uploading after the changes. Let me know if you need any help. Thanks

**Comment by boton** [comment]
> Hi @boton & @ambrinchaudhary, for the failing POSHI cases, we can use `UploadCommonFile.uploadCommonFileHiddenNoMouseOver` instead of `UploadCommonFile` for uploading after the changes. Let me know if you need any help. Thanks

Thanks, we will need help with this after moving some icons and add some margins, I will ping you in the final PR :D

**Comment by boton** [comment]
See #2045.

**Pull request closed without merging**
