### PR TITLE
LPS-200659 Remove AUI() and replace code

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Continuation of https://github.com/liferay-lima/liferay-portal/pull/4871. 

I've checked the code and LGTM, also tested it and seems to be working correctly 🎉 . I will launch ci test to confirm it and then forward to Brian. 

Thanks @BarbaraCabrera
cc/ @p2kmgcl

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:document

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1387401_9660

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:document

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1327401_2795

**Comment by ambrinchaudhary** [comment]
ci:test:document

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
