### PR TITLE
[TECHNICAL SUPPORT] LPS-200885 Private page of type "Link to URL" is publicly available.

### PR DESCRIPTION
**Pull request by markomihalovics**
### Content

- **LPS-200885**
Logical order changes in the `FriendlyURLServlet.getRedirect` method to prevent unauthenticated users from accessing private URL pages and to handle `LayoutPermissionExceptions` properly. 
Additionally, removed a redundant if statement.

### How To Test

- Add a page with Name=`URLPage`, Type=`Link to URL` and URL=`http://www.google.com`
- Uncheck all permissions except Owner on the page and save
- Sign out
- Enter the URL http://localhost:8080/group/guest/urlpage

:white_check_mark: **Expected result**
If users do not have viewing permissions, they should not be redirected to the URL.

Please review this pull request, @robertoDiaz. Thanks in advance.

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hi @markomihalovics 

Did I introduce this bug or something like this?

Thanks!

**Comment by markomihalovics** [comment]
Hi @robertoDiaz,

You did not introduce the bug. Sorry for the misunderstanding.

I tagged you because you are the **Subject Matter Expert**.

Regards,
Márkó

**Comment by robertoDiaz** [comment]
@liferay-lima is under IPT.

SME does not apply to us. 

This will be handled and reviewed by the team if the fix is done in one of our componets.

Best regards

**Comment by markomihalovics** [comment]
Thank you for clarifying, @robertoDiaz! Have a great day! 😇

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
checking

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
