### PR TITLE
LPS-187934/ LPS-187938 Add configuration to limit copy batch size #136764

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Resend of https://github.com/brianchandotcom/liferay-portal/pull/136764#issuecomment-1602798689
Brian's comment: 

> @ambrinchaudhary @adolfopa language keys need to follow https://capitalizemytitle.com/ or be complete sentences. Please resend. Thx.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:test:stabl

**Comment by Hanlf** [comment]
ci:test:stable

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
