### PR TITLE
LPS-190085 Notifications select all

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-190085
This is a partial fix, bulk process is still needed. As we saw by slack call, the backend process to delete, mark as read or unread all the notifications needs to be implemented.

@robertoDiaz Now you can get the `selectAll` parameter in your _NotificationPorlet.java_. The rest of the selected notifications could be get as before, via `rowIds` parameter, or `selectedEntryIds`.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by robertoDiaz — APPROVED** [review]
@manuelRives will handle it.

I've explained him the problem and the solution we've agreed and he is working on that.

If you wish I could review the final PR

Regards!

**Comment by ambrinchaudhary** [comment]
> @manuelRives will handle it.
> 
> I've explained him the problem and the solution we've agreed and he is working on that.
> 
> If you wish I could review the final PR
> 
> Regards!

Sounds good, thanks @manuelRives and @robertoDiaz

**Comment by ambrinchaudhary** [comment]
Merged in pull https://github.com/liferay-lima/liferay-portal/pull/4595

**Pull request closed without merging**
