### PR TITLE
LPS-195228 Make property configurable through instance settings

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPS-195228

The `discussion.comments.always.editable.by.owner` property affects a whole server. In some use cases, it is necessary to configure this value at instance or group level.

# How am I fixing it?

I simply added a new property to an already existing configuration. The property in `portal.properties` has been removed, and an upgrade process implemented.

# How can you verify that it works?

There are multiple test cases available at <https://liferay.atlassian.net/browse/LPS-195006>.  The new configuration option is available at Settings > Content & Data > Comments.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
Everything looks good. I only miss the fixing of tests in `MBDiscussionPermissionImplTest`.

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:stable

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
Looks like this needs to be rebased @marcogalluzzi @adolfopa

**Comment by austinchiang** [comment]
@adolfopa MB integration tests are failing with related errors
Screenshot from 2023-09-20 10-08-37

[Example](https://testray.liferay.com/reports/production/logs/2023-09/test-1-28/test-portal-acceptance-pullrequest(master)/7667/modules-integration-mysql57-jdk8/2/22/jenkins-console.txt.gz?authuser=0)

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
Checking

**Comment by austinchiang** [comment]
Failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
