### PR TITLE
LPS-116355 User does not receive mail for own blog entry creation

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hey @IstvanD,

Have a look at my changes and let me know what you think. If you're happy we can forward it.

Thanks!

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by IstvanD** [comment]
Hi @4lejandrito 

The changes are looking good. Thanks!

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
