### PR TITLE
LPS-171672 KB tree navigation performance

### PR DESCRIPTION
**Pull request by boton**
# Issue: https://issues.liferay.com/browse/LPS-171672

The detailed analysis is here https://liferay.atlassian.net/wiki/spaces/ENGLIMA/pages/2178221771/LPS-169130+Performance+analysis+in+menu+navigation

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
Awesome!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:reevaluate:133null_2602

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
