### PR TITLE
LPS-131646 Hide autotranslate button when no configuration is present

### PR DESCRIPTION
**Pull request by adolfopa**
Enable the Auto-translate button only when the configuration is valid (and the feature flag is enabled).

To test this, simply try to enable/disable the Google Cloud configuration is System Settings, and observe that the button in the side by side goes away/shows up as appropriate.

~~I need to investigate how to add complex validations in System Settings. For the moment, we need to allow empty/invalid account key to allow users to disable the integration no matter its value.~~ The last two commits include the validation; it looks a bit off, but this seems to be a general issue. @drewbrokke, are errors expected to show on the top of the page?
translation-validation

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
Tested and working for me, only show when the translation is enabled and have the feature flag.
User error is shown and disabled the auto-translate when the JSON is malformend.

Ready to go!

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Are you ok with these changes?

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1827

**Comment by drewbrokke** [comment]
@adolfopa I can't recall if that's intended. I'll look at it, thank you for pointing it out.

**Pull request closed without merging**
