### PR TITLE
LPS-116772

### PR DESCRIPTION
**Pull request by robertoDiaz**
https://issues.liferay.com/browse/LPS-116772

Title is already escaped (added a `System.out.println(title)` to verify), so we don't need to escape it again.

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
@ambrinchaudhary @boton Changes are ok (double escaping issue), so I'm forwarding it directly.

**Pull request closed without merging**
