### PR TITLE
[TS] LPS-171955 | Sitemap gets generated even after the site is deactivated

### PR DESCRIPTION
**Pull request by GaborKomaromi**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-171955
Thank you!
---------
**Reproduction Steps:**

1. Create a new site
2. In the settings, the new site under SITE URL → Public Pages add a virtual host under which the site can be used.
3. Add at least one page to the site
4. Deactivate the site
5. Go to [virtualhost]:8080/sitemap.xml

**Expected outcome:** The sitemap cannot be generated or does not include pages referring to the site.
**Actual outcome:** The sitemap is generated and can be accessed.

The root cause is that before generating the sitemap.xml, it did not take in to consideration the active or deactive state of the group. It was an issue as through the sitemap the set virtualhost could be reached and the sitemap was generated. To fix this, I added a check before the sitemap generation.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hi @GaborKomaromi , could you please send this to @liferay-echo team instead? Thanks!

**Comment by GaborKomaromi** [comment]
Hi @ambrinchaudhary,
I sent the PR to echo team as requested: https://github.com/liferay-echo/liferay-portal/pull/10753

**Comment by bakayattila** [comment]
ci:close

**Pull request closed without merging**
