### PR TITLE
LPS-196690 Spacing between sticker and name on DM table

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-196690 
### Changes in DM: 

**Before:** 

Screenshot 2023-09-21 at 11 05 23

**After:** 

Screenshot 2023-09-21 at 11 05 37

### Changes in KB:

**Before:** 

Screenshot 2023-09-21 at 12 22 00

**After:** 

Screenshot 2023-09-21 at 12 20 14

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@ambrinchaudhary Looks good. Once the SF is fixed, you can forward this yourself.

**Comment by ambrinchaudhary** [comment]
c:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
