### PR TITLE
LPS-166292 Update file store README to reflect behavior of previews/thumbnails

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

What is described for Adaptive Media in the file system store README applies to previews/thumbnails for non-image content (PDFs, videos, etc.). This pr updates the readme file to reflect that.

# How to test this?

Nothing to test.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
This only updates a REAME file, so no code to review.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
