### PR TITLE
LPS-129537 Message Board links to pages

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @liferay-lima team, this is a fix for https://issues.liferay.com/browse/LPS-129537. Message Boards was wrongly using the `wikilink` plugin, which must be used only for wiki and for the Creole format. I removed it and replaced by the default link plugin. 

**Steps to Reproduce:**
1. Go to Site Builder > Pages > Create a new Widget page name CKEditor Page
2. Go to Content & Data > Message Board > Create a new thread name MBThread Message Subject
3. On the Editor, type "Link to Page" and link the newly create page "CKEditor Page"
4. Publish the thread
5. Go to newly create thread MBThread Message Subject and click on "Link to Page"

**Expected Result**
This link should bring user to CKEditor page (Widget page)

**Actual Result:**
The link does not take user anywhere

In addition, I checked wiki and it is not rendering the dialog that `wikilink` plugin provides, although the plugin is included in the config. In Creole, link to pages are formed with the title of the page, not the url, just like it is done [here](https://github.com/liferay/liferay-portal/blame/master/modules/apps/frontend-editor/frontend-editor-ckeditor-web/src/main/resources/META-INF/resources/_diffs/plugins/wikilink/dialogs/link.js#L119-L119) (this was causing the current bug in MB). So  I highly recommend you to check why this is happening because I guess this could cause another bug. 

/cc @adolfopa

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by boton — APPROVED** [review]
LGTM. Tested and working

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
