### PR TITLE
LPS-194478 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://liferay.atlassian.net/browse/LPS-194478

Added tests:

- BlogsPage#ViewRelatedAssetsInBlogs **Cover** LPS-194237: Select related assets
- BlogsWidget#CanViewEntryWithOrganizationViaBlogsAggregator **Cover** LPS-194248: Cannot select organization in the blogs aggregator widget
- CollectionDisplay#ViewManualCollectionWithAssetTypes **Cover** LPS-194231: Select assets in AP
- DMDocumentType#CanAddEntryWithMetadataSet **Cover** LPS-194228: Select metadata for document type
- DepotDocumentSiteIntegration#CanViewRelatedAssets **Cover** LPS-194225: Change site scope in item selector
- SiteMemberships#AddMember  **Cover** LPS-194223: Change display style in item select
- WebContentDisplay#ChangeTemplate **Cover** LPS-194222: Select structure in WC

CI results: https://testray.liferay.com/zh/home/-/testray/case_results?testrayBuildId=2415802849&testrayRunId=2416033746

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by austinchiang — APPROVED** [review]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
