### PR TITLE
LPS-132908

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@ealonso This prevents slashes to be included in friendly URLs. This directly affect you, as you want to allow for slashes in url titles. I won't forward until you comment (it looks fine to me).

**Comment by ealonso** [comment]
Hey @dacousalr,
Could you please take a look at it?
Regards,
Eudaldo

**Comment by adolfopa** [comment]
@dacouslar Any comments?

**Comment by dacousalr** [comment]
Sorry for the delay in my response.

The scenario for Asset Publisher links was addressed in https://issues.liferay.com/browse/LPS-105044.

The other scenario related to slashes in Asset Display Page Friendly URLs was addressed in https://issues.liferay.com/browse/LPS-128329.

Regarding the mentioned RFC-3986, I think that its interpretation and observation within the product should be discussed in a PTR ticket.

The solution as is would potentially break existing friendly URLs without any available upgrade path. I would only pass the third commit since it would solve a related, alghough different, issue.

Best,
Daniel

**Comment by adolfopa** [comment]
@marianoalvarosaiz Can you send the last commit to the Echo team for review? Closing this PR.

**Pull request closed without merging**
