### PR TITLE
LPS-142722 inline the creation of the html param

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPS-142722 we can put the function inside the json, do it and inline

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
@boton can you check if the html null value is ok if not video
thanks!

**Comment by AliciaGarciaGarcia** [comment]
change asked on https://github.com/brianchandotcom/liferay-portal/pull/110200#issuecomment-975684148

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
@boton

I looked into the code:

if null it's not included.


Thanks!!
```

try {
	Object value = valueUnsafeSupplier.get();
	if (value != null) {
		return put(key, value);
	}
}
catch (Exception exception) {
	throw new RuntimeException(exception);
}
```

**Review by boton — APPROVED** [review]

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
