### PR TITLE
LPS-190095 Fix wrong URL usage in DeepL Translator

### PR DESCRIPTION
**Pull request by adolfopa**
https://issues.liferay.com/browse/LPS-190095

As described in https://liferay.dev/ask/questions/development/reply-for-lps-183137-lps-187034-breaks-deepl the fix for LPS-187034 introduces an issue for DeepL:

The refactoring of the DeepL translator code to use the company configuration as basis for requests (LPS-187034) breaks translations because the wrong URL is used to create translation requests. There are two different URLs used by the DeepL translator. One is used to fetch the valid languages (validatedLanguageUrl) and the second to do the translation (url). After the refactoring for both cases `validatedLanguageUrl` is used, which breaks the translation call.

In LPS-183137 a user with name Austin pinged me for this. I can't access the JIRA anymore, so there is neither a tracking issue, nor can I answer this person. If required, please create an issue, I can update the commit message accordingly.

The fix was coded against 7.4.3.83 and tested in our staging environment, I rebased it onto current master for inclusion in mainline.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
