### PR TITLE
LPS-174898, LPS-176639 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-176639
https://issues.liferay.com/browse/LPS-174898

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
resent it under https://github.com/liferay-lima/liferay-portal/pull/4035.

**Pull request closed without merging**
