### PR TITLE
LPS-180065 Most Recent and Most Popular lists don't take into account take account Article / Folder permissions

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Read https://issues.liferay.com/browse/LPS-180065 to reproduce the test case

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
