### PR TITLE
LPS-121947 | Master only

### PR DESCRIPTION
**Pull request by Hanlf**
Fix the Poshi failures from https://github.com/liferay-lima/liferay-portal/pull/1118.
cc/ @ambrinchaudhary @markocikos @carloslancha and @julien

Quoting from https://github.com/liferay-lima/liferay-portal/pull/1118

> Fixes: https://issues.liferay.com/browse/LPS-121947
> Fixes: https://issues.liferay.com/browse/LPS-121960
> 
> In this PR we are replacing horizontal and vertical cards with the newly minted navigation card. This includes:
> 
> removing styles that were specific to the old horizontal card
> updating deploy-web model objects and display context to match the new card
> This PR is a followup on #1102, quoting from there:
> 
> Test plan:
> 
> Fetch this branch
> Deploy the depot-web and frontend-taglib-clay modules
> From the global menu, in the Applications tab, select Content > Asset Libraries
> Click on the + button in the top right corner of the page to
> create a new asset library
> Enter a name for this asset library
> Scroll down to the end of the page and click on the Save button
> Assert that the asset library has been created and that a card is
> visible and working as expected.

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by julien** [comment]
@Hanlf thanks!

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
