### PR TITLE
LPS-175896 KB child article permissions are not properly processed in KB widgets

### PR DESCRIPTION
**Pull request by marcogalluzzi**
This PR solves the problem described in issue https://issues.liferay.com/browse/LPS-175896

It also solves this problem. 

Steps to reproduce:
* Create a KB Article with two child articles
* Remove view permissions for guest from one child article
* Add a site page
* Add a KB display/article widget to display the parent KB article
* Assert that the parent with the two child articles is shown (this is expected because the user is still an admin)
* Log out
* As guest, navigate to the site page and view the parent article

Expected result: the parent with one child page is shown

Actual result: the parent with the two child pages is shown

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
