### PR TITLE
LPS-118395 if group is layout prototype find the parent group from the page template entry

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Pull request closed without merging**
