### PR TITLE
LPS-154737 Add icons in the dropdown of Media Gallery items

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
https://issues.liferay.com/browse/LPS-154737

**After the changes:** 
Screenshot 2022-05-30 at 16 40 15

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1387401_894

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
