### PR TITLE
LPS-146109 Let staging manage friendly url import

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by patriciajeanperez** [comment]
ci:test:usm

**Comment by patriciajeanperez** [comment]
ci:test:staging

**Pull request closed without merging**
