### PR TITLE
LPS-182012 Version increase in com.liferay.blogs.settings.BlogsGroupServiceSettings

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-182012

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
The above failures are not related to this pull. Forward this PR directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
