### PR TITLE
LPS-124725 Some vertical cards return null dynamic attribute map

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
@julien Some existing VerticalCard implementantions return a `null` dynamic attribute map. To keep backwards compatibility I changed the impl to accept `null` as a valid value.

This is a very small fix, so I'll forward it to Brian directly if you don't mind :-)

**Comment by adolfopa** [comment]
ci:forward

**Comment by julien** [comment]
Thanks for the fix @adolfopa :smile:

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
