### PR TITLE
[ON HOLD] LPS-114569 Quarantine tests

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Rebased and resent https://github.com/liferay-lima/liferay-portal/pull/489

**Pull request closed without merging**
