### PR TITLE
LPS-129013 Adding color back to google drive icons

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@boton please feel free to change this to the proper way of doing things. I don't know if the es6 methods I am using are supported by our tooling.

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
See liferay-frontend#893

**Pull request closed without merging**
