### PR TITLE
LRQA-64538, LRQA-64589, LRQA-64590 | master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-64538
https://issues.liferay.com/browse/LRQA-64589
https://issues.liferay.com/browse/LRQA-64590

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above two tests failed at [LRCI-1940](https://issues.liferay.com/browse/LRCI-1940), will rerun it.

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
Should be a fluke, rerun it

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
