### PR TITLE
LPS-150285 Restrict journal criterion to images

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
LGTM but I don't test it

**Comment by boton** [comment]
baseline :(

**Comment by adolfopa** [comment]
c:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
