### PR TITLE
LPS-132678 Fix WebDAVOSX test failures

### PR DESCRIPTION
**Pull request by adolfopa**
@hhuijser Please take a look at these changes; I had to partially revert a commit of yours.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1197401_8366

**Comment by adolfopa** [comment]
The root cause was reverted from master. Closing this PR, as it will cause conflicts (and is no longer necessary).

**Pull request closed without merging**
