### PR TITLE
LPS-115729 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
@AliciaGarciaGarcia please check this [commit](https://github.com/liferay-lima/liferay-portal/pull/262/commits/1f0482921690bf3cc1271ecb82e6a1ce80b82fea). Also, keep in mind the "Save as Draft" button, and the errors that can appear. Should we include them in _import_translation.jsp_?

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
> @AliciaGarciaGarcia please check this [commit](https://github.com/liferay-lima/liferay-portal/pull/262/commits/1f0482921690bf3cc1271ecb82e6a1ce80b82fea). Also, keep in mind the "Save as Draft" button, and the errors that can appear. Should we include them in _import_translation.jsp_?

Yes, I think that we should stay in the same page and show the errors on the jsp. what you think?


Other things:

- I think that we can omit (for now) the call to `_journalArticleService.updateArticleTranslation`
It's making the article inconsistent (approved and in draft at same time)

- I made a mistake on :

```
_translationInfoFormValuesExporter.importXLIFF(
	themeDisplay.getScopeGroupId(),
	new InfoItemClassPKReference(
		JournalArticle.class.getName(), article.getClassPK()),
			inputStream);
```

must be 

```
_translationInfoFormValuesExporter.importXLIFF(
	themeDisplay.getScopeGroupId(),
		new InfoItemClassPKReference(
			JournalArticle.class.getName(),
				article.getResourcePrimKey()),
			inputStream);
```
Can you change it?

- I didn't realize about the draft. I will need the cmd to check it.


Thanks for the awesome work!!
Alicia

**Comment by ambrinchaudhary** [comment]
Will resend

**Comment by ambrinchaudhary** [comment]
@AliciaGarciaGarcia about the draft, I'm actually sending you a "workflowAction" parameter in the request. I saw this parameter in other actions and I think is the standard.

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/267

**Pull request closed without merging**
