### PR TITLE
LPS-138888 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-138888

Hi @austinchiang 
Some upgrade tests(like TranslationsUpgrade and DepotUpgrade etc.) are not running in our Lima Suite, I think these upgrade tests should be included, please review.

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:reevaluate:1287401_261

**Comment by Hanlf** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
