### PR TITLE
LPS-116864 Add support for default display type to Default Item Selector View

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

Sometimes the 'descriptive' view is a better approach to be selected as the default view of the Item Selector. We can achieve it using a parameter in the URL, but maybe we need to debug it in order to find the right parameter.

**Provided Solution**

I have added a new method getDefaultDisplayStyle to ItemSelectorViewDescriptor, so we can decide in the implementation of the ItemSelectorViewDescriptor the default display Style.

**How to test it**

I have added unit tests for this pull.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
Thanks @cgoncas!

**Pull request closed without merging**
