### PR TITLE
LPS-159876 Use CDATA when serializing url title map

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
@adolfopa - I think this is safe to merge, it is only failing with whip errors.

This is the ticket related to this issue:
https://issues.liferay.com/browse/LPS-158474

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1277401_4628

**Comment by adolfopa** [comment]
Forwarded to bchan. See https://github.com/brianchandotcom/liferay-portal/pull/122095

**Pull request closed without merging**
