### PR TITLE
LPS-182968 Support download permission in external repos

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-182968

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:help

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
