### PR TITLE
LPS-188585 Change filter by document types title

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Screenshot 2023-06-23 at 11 28 21

Screenshot 2023-06-23 at 11 39 03

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
For some reason the modal is showing the tab (it should be hidden when there is only one tab). @adolfopa maybe we can check this in a different task/bug.

**Comment by Hanlf** [comment]
The above failure is not related to this PR.

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
