### PR TITLE
LPS-166077 DM create repository required field

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-166077
Confirmed with @marcoscv-work that this solution is enough. 

Screenshot 2022-10-20 at 12 09 55

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/124964

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
