### PR TITLE
LRQA-60304, LRQA-60277, LRQA-60276 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-60304
https://issues.liferay.com/browse/LRQA-60277
https://issues.liferay.com/browse/LRQA-60276

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by austinchiang** [comment]
Test disabled [here](https://github.com/brianchandotcom/liferay-portal/pull/91546)

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
