### PR TITLE
[TS] LPS-168805 delete the friendlyURLEntryLocalization after removing layoutFriendlyURL

### PR DESCRIPTION
**Pull request by jgarcialr**
Hello Lima Team,

Steps to reproduce:

1. Create a new widget page abcd
2. Go to configure page and add a translation for the page per example for spanish
- name: "aaa"
- friendlyurl "/aaa"

3. Save the page
4. delete spanish friendlyurl
5. save the page

**Expected result:**
Friendly url for spanish translation is deleted.

**Current result:**
Friendly url for spanish translation is not deleted.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
Hello Lima Team,

Steps to reproduce:

1. Create a new widget page abcd
2. Go to configure page and add a translation for the page per example for spanish
- name: "aaa"
- friendlyurl "/aaa"

3. Save the page
4. delete spanish friendlyurl
5. save the page

**Expected result:**
Friendly url for spanish translation is deleted.

**Current result:**
Friendly url for spanish translation is not deleted.

**Comment by jgarcialr** [comment]
I've found a corner case related to friendly url history. I'll close the PR and resend with the proper fix.

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Pull request closed without merging**
