### PR TITLE
LPS-117080 Autogenerated via buildLang

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/451.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
