### PR TITLE
LPS-163426: Allow same page and sites with same name, function properly in a virtual host

### PR DESCRIPTION
**Pull request by kristofloneck**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
[modules-integration-mysql57-jdk8/3/16](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/237625//consoleText) should be some CI issue.
[ClusteringMissingPlugins#ScheduleJobOnClusterNode1](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/269282//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ClusteringMissingPlugins_ScheduleJobOnClusterNode1_) is a flaky issue, not related to this PR.

**Comment by kristofloneck** [comment]
Hi @Hanlf 
Thank you for the checking. Could you push this one forward to Brian, please.
Thank you.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failures are not related to this PR, sent it to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/124762

**Pull request closed without merging**
