### PR TITLE
LPS-123574 Video button in AlloyEditor should open an item selector

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Hi @qa-lima, could you please update the poshi test? Now the video button should open an Item Selector. 
Thanks!

**Comment by Jeremy-Ch** [comment]
ci:test:bundle

**Comment by Jeremy-Ch** [comment]
@ambrinchaudhary I will fix the test and resend.

**Comment by Jeremy-Ch** [comment]
Hi @ambrinchaudhary

**Comment by ambrinchaudhary** [comment]
Depends on https://issues.liferay.com/browse/LPS-123941

**Comment by ambrinchaudhary** [comment]
As the bug https://issues.liferay.com/browse/LPS-123941 is resolved, running again ci:test:revelant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
@ambrinchaudhary I have updated and resend this pull request, please see #1155. Otherwise, I found a language key issue see [LPS-124280](https://issues.liferay.com/browse/LPS-124280). 

cc @austinchiang

**Pull request closed without merging**
