### PR TITLE
LPS-163230 KB hide suggestions panel

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
I added some changes on top. 
Please, @ambrinchaudhary check I'm doing nothing crazy.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1327401_6009

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1267401_5221

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
