### PR TITLE
LPS-180863 add onchange method on select to set UserAgent

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Comment by AliciaGarciaGarcia** [comment]
> LGTM!

it's your code !!! XD

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Pull request closed without merging**
