### PR TITLE
LPS-133714 Changes in Blogs Service settings do not take effect

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
[PortalSmokeUpgrade#ViewPortalSmokeArchive621021](https://testray.liferay.com/zh/home/-/testray/case_results/1542330234) is caused by LPS-134610.

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:bundle

**Comment by Hanlf** [comment]
Hi @adolfopa , could you please take a look at the failure `com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanOSGiLog`,  it occurs during running the PortalSmoke#Smoke. I’m not sure if it is related to this PR, but it only seems to happen under this PR.

Console: https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0,label_exp=!master/14941/consoleFull

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
