### PR TITLE
[TS] LPS-121035

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @jonathanmccann,

I've sent a simpler fix that avoids modifying the ids in the markup, which is less risky. See https://github.com/liferay-lima/liferay-portal/pull/812.

Thanks!

**Pull request closed without merging**
