### PR TITLE
LPS-169011 check if the url is on a different language to ensure uniqueness

### PR DESCRIPTION
**Pull request by jgarcialr**
Sending the PR again because the name for notLang is not standard.
https://github.com/brianchandotcom/liferay-portal/pull/126648#issuecomment-1323507225

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by boton** [comment]
> Failures unique to this pull:
> [functional-tomcat90-mysql57-jdk8/0/19](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313628//consoleText)
> [LocalFile.FriendlyURLService#CanAccessWithSpecificDisabledLanguageAfterSettingLocally](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/313628//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FriendlyURLService_CanAccessWithSpecificDisabledLanguageAfterSettingLocally_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-11/test-1-30/test-portal-acceptance-pullrequest(master)/5474/functional-tomcat90-mysql57-jdk8/0/19/LocalFile.FriendlyURLService_CanAccessWithSpecificDisabledLanguageAfterSettingLocally/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-11/test-1-30/test-portal-acceptance-pullrequest(master)/5474/functional-tomcat90-mysql57-jdk8/0/19/LocalFile.FriendlyURLService_CanAccessWithSpecificDisabledLanguageAfterSettingLocally/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-11/test-1-30/test-portal-acceptance-pullrequest(master)/5474/functional-tomcat90-mysql57-jdk8/0/19/jenkins-console.txt.gz) - [Failed 10 of last 24](https://testray.liferay.com/home/-/testray/case_results/2070534102/history)

@jgarcialr looks related. 
I'm not sure if we need to update some poshi tests or if we are breaking something.

**Comment by jgarcialr** [comment]
@boton 
I've tested on my end and it's working.

Hi, @austinchiang.
Could you test if this poshi test it's working as expected or could be flaky?
Thanks in advance.

**Comment by AliciaGarciaGarcia** [comment]
i will resend the test to check if fails again

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
This is a flaky test @jgarcialr @boton @AliciaGarciaGarcia . It's been failing intermittently on upstream runs as well and we'll stabilize it in https://issues.liferay.com/browse/LPS-166746. I'll manually forward this pull to BChan.

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/126780

**Pull request closed without merging**
