### PR TITLE
LPS-190704 | Master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://liferay.atlassian.net/browse/LPS-190704

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by austinchiang — APPROVED** [review]

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
@WYZ-Issac feel free to directly forward test fixes without my review if you feel comfortable with it

**Pull request closed without merging**
