### PR TITLE
LPS-130761 | Master

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by wincent** [comment]
ci:test:sf

**Comment by wincent** [comment]
- `LocalFile.WorkflowMetrics#ViewReports` looks very obviously unrelated.
- `ci:test:sf` failure is presumably legit.

**Comment by john-co** [comment]
Hi @austinchiang, can you verify if these test plans are or will be covered by lima team? Just want to check before diving deeper for FI QA to start including tests.

1. In blogs, add a cover image via drag an drop. Delete it. Change it and select a new file. Try this over and over again in different orders with the JS console open and see no errors. See the caption show/hide when changing the cover image.
2. Verify that the "small image" selector that appears under configuration still works as before (adding/removing/changing). Verify that changes to the "small image" do not affect the cover image or its caption in any way.

**Comment by john-co** [comment]
Reached out to @austinchiang on slack for status update.

**Comment by austinchiang** [comment]
@john-co -
1. We don't have any drag and drop tests since that seems to be a technical limitation. What we have is:
- `PGBlogs#CanUploadAndPublishCoverImage` - Uploads and publishes a cover image
- `CPBlogs#CanChangeCoverImage` - Changes the uploaded cover image to some other file in DM
- `StagingRemoteLiveChangeBlogsEntryCoverImage` - Same as above but using remote staging
- `CPBlogs#CanSaveCoverImageAsDraft`- Saves a draft of the cover image and views it
I don't think we have any delete tests. Oddly enough we are also not asserting the show/hide caption (thought we had a test for it).

2. For small images:
- `PGBlogs#CanRemoveSmallImageFromEntry` - Deletes the small image from an entry and views it
- `StagingBlogs#PublishEntryWithDeletedSmallImage` - Same as above but viewing on live after republishing on the staged site
- We don't have any tests that assert the cover image status after modifying the small image

So it seems like we're missing a few cases here.
- Removing a cover image
- Asserting the show/hide caption (and variations here)
- Replacing a small image

Let me know if your team is planning to write them or if you would like us to. If my team does it this might be backlogged since we're pretty swamped with other things right now

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by wincent** [comment]
I see `LocalFile.WorkflowMetrics#ViewReports` popped up again, which is rather weird, as I wouldn't expect it to have any relation. But I don't know how to interpret the Poshi report; screenshot just shows a loading spinner. Maybe it is a flakey test due to intermittent timeouts? I presume if there were a console error we would see it. Going to try another run in the meantime.

**Comment by wincent** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Yeah it might be a flaky test where performance was slower on that portal instance/slave/node. Looking at the before/after from the screenshot, it seems the test was trying to make an assertion before the list was rendered.

**Comment by wincent** [comment]
Just saw `LocalFile.WorkflowMetrics#ViewReports` [fail on a totally unrelated PR](https://github.com/liferay-frontend/liferay-portal/pull/986#issuecomment-823964212), so I am pretty confident that this is unrelated and we can forward this and follow-up with adding more test coverage in separate PRs based on what @austinchiang and @john-co agree is the right course.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by john-co** [comment]
I think this is ok to manually forward. It looks like running `ci:test:relevant` is not going to get past the flaky workflowmetrics test I've seen other PRs run into...

cc/ @rodrigocunhaa

**Comment by john-co** [comment]
Do you want us to quarantine this test @rodrigocunhaa or will you take care of it?

**Comment by rodrigocunhaa** [comment]
Hi @john-co , this test was already fixed here: https://github.com/brianchandotcom/liferay-portal/pull/100995.

You can manually forward this PR to save CI resources.

**Comment by austinchiang** [comment]
Resent in https://github.com/brianchandotcom/liferay-portal/pull/101039

**Comment by wincent** [comment]
Thanks @austinchiang, @john-co, @rodrigocunhaa!

**Pull request closed without merging**
