### PR TITLE
LPD-7114 Create AI Image button in the Item Selector for DM

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPD-7114 

This pull covers everything for the story https://liferay.atlassian.net/browse/LPD-6800 Generate AI Image when selecting media during content creation (6)

https://github.com/liferay-lima/liferay-portal/assets/8373764/8d12e0e5-e98e-4d34-9672-9624b247c48f

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
Good to go!

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1327401_3469

**Comment by ambrinchaudhary** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
