### PR TITLE
LPS-118826 Sometimes the contentEditor is not ready

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:blogs

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:test:blogs

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1248

**Pull request closed without merging**
