### PR TITLE
LPS-105652 Semver

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forwawrd

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Sent directly to BChan: https://github.com/brianchandotcom/liferay-portal/pull/88723

**Pull request closed without merging**
