### PR TITLE
LPS-163978 Make all actions point to the control panel

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @adolfopa 
There is a bug when adding a child KB article via the KB display widget, could you please take a look, thanks!
Test steps:
1. Add a KB article 
2. Add a new page with a KB display widget
3. Try to add a child kb for this KB article by clicking 'Add Child Article'
4. Assert it opens the parent KB article edit page, instead of the child article page.

**Comment by AliciaGarciaGarcia** [comment]
rebase and correct name

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Review by marcogalluzzi — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
