### PR TITLE
LPS-197123 use the getPreviewableProcessorMaxSize on the exception

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-197123 use the getPreviewableProcessorMaxSize on the exception

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @marcogalluzzi 

This is the last part I talked about on the other PR, now can be done because all is merged
Thanks!

**Review by adolfopa — APPROVED** [review]

**Review by marcogalluzzi — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_14794

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Comment by marcogalluzzi** [comment]
I don't think failures unique to this pull are related. Forcing forward.

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
