### PR TITLE
LPS-117779 Move error inside the form avoiding layout problems

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Some of the failures are issues : https://issues.liferay.com/browse/LPS-117864

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by boton** [comment]
See #528.

**Pull request closed without merging**
