### PR TITLE
LPS-121729 Removes Open In MS Office UI items

### PR DESCRIPTION
**Pull request by jbalsas**
Hey @liferay-lima!

IE11 will no longer be supported in Liferay DXP 7.4. That means that any specific features that require that browser won't be supported either.
* This commit removes the conditional addition of Open in MS Office items to different menus or toolbars since the condition they require to work (IE on Windows) are not to be satisfied in the next version.
* This commit does not remove MS Office support, simply the UI that can trigger the feature.

I'm sending this here based on the comments in [Remove OpenInMsOffice Support from Document Library](https://issues.liferay.com/browse/LPS-121729) by @adolfopa:

> This is the old integration with MS Office. This depends on a particular version of IE and some ActiveX components, so we should consider it legacy (and a clear candidate for removal). It has nothing to do with our integration with Office365.

I'm looking for guidance on how you want to proceed with this. The way I see it we can:
* Forward this and then you can decide wether to do a more thorough cleanup at your convenience
* Pile on the legacy MSOffice support in this PR before pushing it forward
* Discard this and work on it at a later time.
* Other...

Parking this here to run some tests and leave you time to decide on this.

Thanks!

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> LIFERAY_ERROR: Portlet com_liferay_change_tracking_web_portlet_PublicationsConfigurationPortlet from com.liferay.change.tracking.web_2.0.0 [1006] failed to initialize

Looks like the error was a fluke. Retesting again

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/924

**Pull request closed without merging**
