### PR TITLE
LPS 123651

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
compileOnly project(":core:petra:petra-function")
is needed on modules/apps/document-library-opener/document-library-opener-service/build.gradle

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
