### PR TITLE
LPS-167617 | Simplify tooltip label definition code

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description**: Simplify the translation code from the [prior pull request](https://github.com/liferay-lima/liferay-portal/pull/4107) to get the same outcome in fewer lines

**Jira Ticket**: https://issues.liferay.com/browse/LPS-167617

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
