### PR TITLE
LPS-109977 Make public documents cacheable by CDN

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — COMMENTED** [review]
An error es thrown when starting the server (clean and new) 

```
2022-01-13 18:19:38.044 ERROR [http-nio-8080-exec-1][CacheControlServletHttpHeaderCustomizer:93] bundle com.liferay.document.library.web:6.0.61 (1208)[com.liferay.document.library.web.internal.servlet.CacheControlServletHttpHeaderCustomizer(9862)] : The activate method has thrown an exception
java.lang.RuntimeException: Unable to create snapshot class for interface com.liferay.document.library.web.internal.configuration.CacheControlConfiguration
	at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil._createConfigurableSnapshot(ConfigurableUtil.java:99) ~[?:?]
	at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil.createConfigurable(ConfigurableUtil.java:59) ~[?:?]
	at com.liferay.document.library.web.internal.servlet.CacheControlServletHttpHeaderCustomizer.activate(CacheControlServletHttpHeaderCustomizer.java:82) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	
....

	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.56]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_202]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_202]
	at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil._createConfigurableSnapshot(ConfigurableUtil.java:96) ~[?:?]
	... 118 more
Caused by: java.lang.IllegalStateException: Attribute is required but not set cacheControl
	at aQute.bnd.annotation.metatype.Configurable$ConfigurableHandler.invoke(Configurable.java:83) ~[com.liferay.portal.bootstrap.jar:?]
	at com.sun.proxy.$Proxy1264.cacheControl(Unknown Source) ~[?:?]
	at com.liferay.document.library.web.internal.configuration.CacheControlConfigurationSnapshot.<init>(Unknown Source) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_202]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_202]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_202]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_202]
	at com.liferay.portal.configuration.metatype.bnd.util.ConfigurableUtil._createConfigurableSnapshot(ConfigurableUtil.java:96) ~[?:?]
	... 118 more
```

Can you review it?

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
