### PR TITLE
WIP LPS-166653 Allow same friendlyurl for a layout for different non-default locales

### PR DESCRIPTION
**Pull request by jgarcialr**
- LPS-166653 create new finder, remove unique from g_c_u
- LPS-166653 buildService
- LPS-166653 allow repeating same friendlyurl for different locale in same layout
- LPS-166653 check if language is null and use default as fallback
- LPS-166653 modify validate to take into account every possible language
- LPS-166653 these tests doesn't have to throw an exception
- LPS-166653 fix typo
- LPS-166653 SF
- LPS-166653 buildService
- LPS-166653 modify validation
- LPS-166653 SF
- LPS-166653 remove deprecated
- LPS-166653 throw duplicateException if different classpk and not layout

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/3668

**Pull request closed without merging**
