### PR TITLE
LPS-114566 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-114566

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
Hey @adolfopa @AliciaGarciaGarcia we've refactored the DM tests for Data Engine in this pull. All that is left to do is fetch this branch and then disable the feature flag on top of it (the tests won't pass by themselves now because we removed [the commit](https://github.com/Hanlf/liferay-portal/pull/152/commits/69a4213a131b63f4c94c06d25624934524558a60#) to enable DE here) and then ``ci:forward`` it. It's safe now to send post-GA4 pulls to BChan 😃 

A couple of known issues I wanted to highlight:
- https://issues.liferay.com/browse/LPS-116497 (affects a non-acceptance test)
- https://issues.liferay.com/browse/LPS-114635 (bumped up fix priority)

cc @Hanlf @liuxingye @Jeremy-Ch

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/433

**Pull request closed without merging**
