### PR TITLE
LPS-123008 Remove Image Editor tests

### PR DESCRIPTION
**Pull request by adolfopa**
This removes the Image Editor code from the portal.

@ambrinchaudhary Can you check if there's anything else to do? It seems every reference was in the Item Selector, but I'm not sure if there are more usages.

@austinchiang I've removed the Poshi tests. Can you double check if everything is ok?

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
> This removes the Image Editor code from the portal.

dontgo

**Comment by austinchiang** [comment]
@adolfopa @ambrinchaudhary Poshi test removal LGTM!

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1012. 

Please @adolfopa, close this pull and forward the new one if you agree

**Pull request closed without merging**
