### PR TITLE
LPS-190179, LPS-190190 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-190179
https://liferay.atlassian.net/browse/LPS-190190

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:forward

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
