### PR TITLE
LPS-120162, LPS-114309 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-120162
https://issues.liferay.com/browse/LPS-114309

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
@austinchiang This failure looks legit. Do you need help with this PR?

**Comment by austinchiang** [comment]
@adolfopa strange, that test is passing in upstream acceptance and we're only adding unique tests to this pull. I'll try rerunning forward again.

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Sending [straight to BChan](https://github.com/brianchandotcom/liferay-portal/pull/94367) because of CI instability and because [aint nobody got time for that](https://youtu.be/waEC-8GFTP4?t=27)

**Pull request closed without merging**
