### PR TITLE
LPS-177947 Set store UUID column size to 255

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-177947

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-177947.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_8102

**Review by marcogalluzzi — APPROVED** [review]

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
Hi @austinchiang can you please take a look to the failures unique to this pull? They don't seem related to the PR. Thanks

**Comment by austinchiang** [comment]
Looks fine to me

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
