### PR TITLE
[TS] LPS-158659 Add OptimizeImagesAllConfigurationsBackgroundTaskExecutor isTaskInProgress check

### PR DESCRIPTION
**Pull request by danielmijarra**
Hello @liferay-lima,
this pull fixes LPS-158659.

Adds a check to verify if `OptimizeImagesAllConfigurationsBackgroundTaskExecutor` background task is still running.

Please let me note if you have any questions.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by danielmijarra** [comment]
ci:test:sf

**Comment by danielmijarra** [comment]
ci:test:relevant

**Comment by danielmijarra** [comment]
ci:test

**Comment by AliciaGarciaGarcia** [comment]
ci:test:adaptive-media

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
