### PR TITLE
LPS-151756,LPS-151760

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Lima team,

Please see the relevant discussion on [PTR-3007](https://issues.liferay.com/browse/PTR-3007) and [PTR-3013](https://issues.liferay.com/browse/PTR-3013).

https://issues.liferay.com/browse/LPS-151756
https://issues.liferay.com/browse/LPS-151760

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
