### PR TITLE
LPS 119836

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @laszlopap,

We believe it's necessary to revert the changes added for [LPS-117484](https://issues.liferay.com/browse/LPS-117484). To avoid an error in the logs the functionality was broken and now friendlyURLS are being corrupted when normalized more than once.

Have a look at https://github.com/liferay-lima/liferay-portal/pull/693/commits/9bc9df4cbc4081cae629c709fb73b1524aa930d1 and its message.

Please let us know your thoughts.

@AliciaGarciaGarcia @adolfopa

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by laszlopap** [comment]
Hi @4lejandrito !

Sorry for the regression, and also Thank you for fixing it! :) 

Regards!

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
No problem @laszlopap,

This is very tricky logic, it took a long discussion to get to the decision. Hopefully for the best.

Thanks!

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
