### PR TITLE
LPS-178908 filter by multiple extensions

### PR DESCRIPTION
**Pull request by marcogalluzzi**
How to test:
* Go to Documents & Media
* Upload files with different extensions
* Filter by multiple extensions 

Additional test - you can also check that it is working in combination with "Document Type":
* Create a new DocumentType
* Upload files with different extensions using the new Document Type
* Filter by multiple extensions in combination with the new Document type.

Explanation of changes:
* Before it was using a `searchContext` created with attributes based on the request parameters. These attributes where automatically used for filtering. This doesn't work when a parameter has multiple values. This was the case for parameter `extension` which is an array of values.
* Now, a `searchContext` is created without attributes based on the request parameters. The filtering is done by explicitly add boolean clauses.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
