### PR TITLE
LPS-178618 Add the path context to the repository browser URL

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-178618

Dear Team,

Could you please review this PR? 

Thanks a lot! ❤️ 

Regards

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
No related failures.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
