### PR TITLE
LPS-154173 Certain img html tags in web content templates can lead to exponential time processing by Adaptive Media

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hello @liferay-lima !

This pr intends to solve [LPS-154173](https://issues.liferay.com/browse/LPS-154173). 

This is a performance issue with a regular expression in the class `AMBackwardsCompatibilityHtmlContentTransformer` that already gave some problems in [LPS-148916](https://issues.liferay.com/browse/LPS-148916). There, instead of parsing the whole web content template, only the `` was parsed. 

However, the regex string wasn't modified and still for some well crafted `` elements can leave the portal hanging when loading such an image from a web content. 

The approach to the solution is to parse, not the template or the `` element, but just the `src`-attribute value, that is, the URL that needs to be parsed for `groupId`, etc to then create Adaptive Media URLs. 

Please let me know if you have any questions. 

Thanks!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @ricardocousolr 

I do not know if the problematic case can be added to the `AMBackwardsCompatibilityHtmlContentTransformerTest` to check it.

thanks!

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
