### PR TITLE
LPS-163072 KB add navigation article preview

### PR DESCRIPTION
**Pull request by boton**
## Issue: https://issues.liferay.com/browse/LPS-163072

We need to show the side navigation always for the article preview.

@AliciaGarciaGarcia and I are not sure what it's the best idea when getting the `selectedItemId`:

- e597c44f7fefa8e16bca33e8140a9b78330b4ff3 getetting two params and only go for `selectedItemId` when `parentResourcePrimKey` is empty
- ea18132b2ed2b50429e9b1e33774471afbe6719f or duplicate params for folders and always get from `selectedItemId`

Feel free to drop the last commit if the first option is better.

### After PR
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Review by adolfopa — COMMENTED** [review]
Q: @AliciaGarciaGarcia I don't understand what you're trying to do here. Do you have more information?

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa 

A: When we select an article on the vertical menu, the idea is that the vertical menu always is on the left side and the preview of the article on the right.
with the commit e597c44f7fefa8e16bca33e8140a9b78330b4ff3 we want to mark on the vertical menu the selected item with a style on the selected item 
It works now with folders before this PR, but now we do not hide the menu so we want to mark the articles too.

the value of the selected item id is 
on the case of the folders it's : `parentResourcePrimKey`
It's filled here. 
https://github.com/liferay/liferay-portal/blob/ed9a01e08716acf7c7a119f107bf4ba72a16d6e8/modules/apps/knowledge-base/knowledge-base-web/src/main/java/com/liferay/knowledge/base/web/internal/display/context/KBAdminNavigationDisplayContext.java#L392

That was we found a little odd and suggested to add the parameter on the creation of the url of the folder
https://github.com/liferay-lima/liferay-portal/pull/3501/commits/ea18132b2ed2b50429e9b1e33774471afbe6719f

I hope this gives light to this matter

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
