### PR TITLE
LPS-158982 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-158982

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:foward

**Comment by austinchiang** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Sending to BChan here https://github.com/brianchandotcom/liferay-portal/pull/121528

**Pull request closed without merging**
