### PR TITLE
LPS-191476 Change the text of the alert when uploading a document

### PR DESCRIPTION
**Pull request by sofiamendozalr**
- LPS-191476 Change the text of the alert when uploading a document
- LPS-191476 buildLang

Before:
before

After when uploading one file:
singleFile

After when uploading some files:
multipleFiles

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
