### PR TITLE
LPS-114764 Use common usePrevious

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
Thanks for point this @wincent

/cc @ambrinchaudhary

**Comment by boton** [comment]
ci:forward

**Comment by wincent** [comment]
> Thanks for point this @wincent

Just think of all the bytes saved!

Possibly dozens!

dozens-of-us

**Comment by boton** [comment]
> dozens-of-us

The best TV show ever

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
