### PR TITLE
LPS-117473 Get all the needed vocabularies (as we do in the taglib)

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
Hi @robertoDiaz 

could you please push this forward?

Thanks, Roland

**Comment by robertoDiaz** [comment]
@rolandpakai 

This should be reviewed by the product team, not by me.

You could provide this as SDH to the customer if needed.

**Comment by rolandpakai** [comment]
@robertoDiaz 

I already provided an SDH with my solution for the customer and the related customer tickets where solved already.
I am just waiting for the merge to the master branch, to move forward with the backort to 72x.
My first PR for review was sent on 17th of July - almost 2 weeks ago. From the next week i will be on PTO for 2 weeks.
I am just wanted to close this issue before my PTO.

Thansk, Roland

**Comment by robertoDiaz** [comment]
This user (@liferay-lima) is handled by them, so they are aware of this pr and it's in their queue.

Some members are on PTO, so the merging times could be longer.

Thanks!

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
