### PR TITLE
LPS-156207 Remove feature flag

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/3169

**Pull request closed without merging**
