### PR TITLE
LPS-134773 Wiki Node may not exist in tests

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

A test failure during backport exposed the fact that the Wiki Node may not exist during a(n integrated) test.
The change below addresses this issue.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@IstvanD Do you know what tests are causing this failure? There should be no wiki pages without a node; I think we should fix the offending tests, not change that logic. /cc @robertoDiaz

**Comment by adolfopa** [comment]
@austinchiang This pr tries to fix a 7.3.x only issue (see failing tests in https://github.com/liferay/liferay-portal-ee/pull/24549#issuecomment-872217418). Can you help us figuring out the particular tests that is causing the logged errors? I cannot see it in the stacktrace. There's probably some change in wiki that we need to backport.

**Comment by austinchiang** [comment]
@Hanlf can you please take a look?

**Comment by Hanlf** [comment]
@adolfopa  `NoSuchNodeException` throws after running com.liferay.wiki.service.test.WikiNodeLocalServiceTest > testMediaLinks, [the stacktrace](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(7.3.x)/2584/AXIS_VARIABLE=1,label_exp=!master/consoleFull):
```     
     [exec] com.liferay.wiki.service.test.WikiNodeLocalServiceTest > testMediaLinks STARTED
     [exec] 
     [exec] com.liferay.wiki.service.test.WikiNodeLocalServiceTest > testMediaLinks PASSED
     [exec] 19:24:18,426 ERROR [com.liferay.wiki.test-executor-thread][WikiPageImpl:267] com.liferay.wiki.exception.NoSuchNodeException: No WikiNode exists with the primary key 54214
     [exec] com.liferay.wiki.exception.NoSuchNodeException: No WikiNode exists with the primary key 54214
     [exec] 	at com.liferay.wiki.service.persistence.impl.WikiNodePersistenceImpl.findByPrimaryKey(WikiNodePersistenceImpl.java:4836)
     [exec] 	at com.liferay.wiki.service.persistence.impl.WikiNodePersistenceImpl.findByPrimaryKey(WikiNodePersistenceImpl.java:4852)
     [exec] 	at com.liferay.wiki.service.impl.WikiNodeLocalServiceImpl.getNode(WikiNodeLocalServiceImpl.java:312)
     [exec] 	at sun.reflect.GeneratedMethodAccessor445.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:80)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec] 	at com.sun.proxy.$Proxy778.getNode(Unknown Source)
     [exec] 	at com.liferay.wiki.service.WikiNodeLocalServiceUtil.getNode(WikiNodeLocalServiceUtil.java:331)
     [exec] 	at com.liferay.wiki.model.impl.WikiPageImpl.getNode(WikiPageImpl.java:264)
     [exec] 	at com.liferay.wiki.web.internal.asset.model.WikiPageAssetRenderer.<init>(WikiPageAssetRenderer.java:90)
     [exec] 	at com.liferay.wiki.web.internal.asset.model.WikiPageAssetRendererFactory.getAssetRenderer(WikiPageAssetRendererFactory.java:92)
     [exec] 	at com.liferay.asset.kernel.model.BaseAssetRendererFactory.getAssetRenderer(BaseAssetRendererFactory.java:67)
     [exec] 	at com.liferay.depot.web.internal.asset.model.DepotAssetRendererFactoryWrapper.getAssetRenderer(DepotAssetRendererFactoryWrapper.java:74)
     [exec] 	at com.liferay.portlet.asset.model.impl.AssetEntryImpl.getAssetRenderer(AssetEntryImpl.java:46)
     [exec] 	at com.liferay.asset.entry.rel.service.impl.AssetEntryAssetCategoryRelLocalServiceImpl._reindex(AssetEntryAssetCategoryRelLocalServiceImpl.java:220)
     [exec] 	at com.liferay.asset.entry.rel.service.impl.AssetEntryAssetCategoryRelLocalServiceImpl.deleteAssetEntryAssetCategoryRelByAssetEntryId(AssetEntryAssetCategoryRelLocalServiceImpl.java:110)
     [exec] 	at sun.reflect.GeneratedMethodAccessor494.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec] 	at com.sun.proxy.$Proxy615.deleteAssetEntryAssetCategoryRelByAssetEntryId(Unknown Source)
     [exec] 	at com.liferay.asset.internal.service.AssetEntryAssetCategoryRelAssetEntryLocalServiceWrapper.deleteEntry(AssetEntryAssetCategoryRelAssetEntryLocalServiceWrapper.java:68)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66)
     [exec] 	at com.sun.proxy.$Proxy617.deleteEntry(Unknown Source)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec] 	at com.sun.proxy.$Proxy49.deleteEntry(Unknown Source)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule._smartDelete(DataGuardTestRule.java:564)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule._autoDeleteLeftovers(DataGuardTestRule.java:293)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule._autoDeleteAndAssert(DataGuardTestRule.java:193)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.afterClass(DataGuardTestRule.java:115)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.afterClass(DataGuardTestRule.java:73)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:66)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:181)
     [exec] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] 19:24:18,521 ERROR [com.liferay.wiki.test-executor-thread][WikiPageImpl:267] com.liferay.wiki.exception.NoSuchNodeException: No WikiNode exists with the primary key 54224
     [exec] com.liferay.wiki.exception.NoSuchNodeException: No WikiNode exists with the primary key 54224
     [exec] 	at com.liferay.wiki.service.persistence.impl.WikiNodePersistenceImpl.findByPrimaryKey(WikiNodePersistenceImpl.java:4836)
     [exec] 	at com.liferay.wiki.service.persistence.impl.WikiNodePersistenceImpl.findByPrimaryKey(WikiNodePersistenceImpl.java:4852)
     [exec] 	at com.liferay.wiki.service.impl.WikiNodeLocalServiceImpl.getNode(WikiNodeLocalServiceImpl.java:312)
     [exec] 	at sun.reflect.GeneratedMethodAccessor445.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:80)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec] 	at com.sun.proxy.$Proxy778.getNode(Unknown Source)
     [exec] 	at com.liferay.wiki.service.WikiNodeLocalServiceUtil.getNode(WikiNodeLocalServiceUtil.java:331)
     [exec] 	at com.liferay.wiki.model.impl.WikiPageImpl.getNode(WikiPageImpl.java:264)
     [exec] 	at com.liferay.wiki.web.internal.asset.model.WikiPageAssetRenderer.<init>(WikiPageAssetRenderer.java:90)
     [exec] 	at com.liferay.wiki.web.internal.asset.model.WikiPageAssetRendererFactory.getAssetRenderer(WikiPageAssetRendererFactory.java:92)
     [exec] 	at com.liferay.asset.kernel.model.BaseAssetRendererFactory.getAssetRenderer(BaseAssetRendererFactory.java:67)
     [exec] 	at com.liferay.depot.web.internal.asset.model.DepotAssetRendererFactoryWrapper.getAssetRenderer(DepotAssetRendererFactoryWrapper.java:74)
     [exec] 	at com.liferay.portlet.asset.model.impl.AssetEntryImpl.getAssetRenderer(AssetEntryImpl.java:46)
     [exec] 	at com.liferay.asset.entry.rel.service.impl.AssetEntryAssetCategoryRelLocalServiceImpl._reindex(AssetEntryAssetCategoryRelLocalServiceImpl.java:220)
     [exec] 	at com.liferay.asset.entry.rel.service.impl.AssetEntryAssetCategoryRelLocalServiceImpl.deleteAssetEntryAssetCategoryRelByAssetEntryId(AssetEntryAssetCategoryRelLocalServiceImpl.java:110)
     [exec] 	at sun.reflect.GeneratedMethodAccessor494.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec] 	at com.sun.proxy.$Proxy615.deleteAssetEntryAssetCategoryRelByAssetEntryId(Unknown Source)
     [exec] 	at com.liferay.asset.internal.service.AssetEntryAssetCategoryRelAssetEntryLocalServiceWrapper.deleteEntry(AssetEntryAssetCategoryRelAssetEntryLocalServiceWrapper.java:68)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66)
     [exec] 	at com.sun.proxy.$Proxy617.deleteEntry(Unknown Source)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec] 	at com.sun.proxy.$Proxy49.deleteEntry(Unknown Source)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule._smartDelete(DataGuardTestRule.java:564)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule._autoDeleteLeftovers(DataGuardTestRule.java:293)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule._autoDeleteAndAssert(DataGuardTestRule.java:193)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.afterClass(DataGuardTestRule.java:115)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.afterClass(DataGuardTestRule.java:73)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:66)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:181)
     [exec] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] 19:24:18,683 ERROR [com.liferay.wiki.test-executor-thread][WikiPageImpl:267] com.liferay.wiki.exception.NoSuchNodeException: No WikiNode exists with the primary key 54224
     [exec] com.liferay.wiki.exception.NoSuchNodeException: No WikiNode exists with the primary key 54224
     [exec] 	at com.liferay.wiki.service.persistence.impl.WikiNodePersistenceImpl.findByPrimaryKey(WikiNodePersistenceImpl.java:4836)
     [exec] 	at com.liferay.wiki.service.persistence.impl.WikiNodePersistenceImpl.findByPrimaryKey(WikiNodePersistenceImpl.java:4852)
     [exec] 	at com.liferay.wiki.service.impl.WikiNodeLocalServiceImpl.getNode(WikiNodeLocalServiceImpl.java:312)
     [exec] 	at sun.reflect.GeneratedMethodAccessor445.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.change.tracking.internal.aop.CTTransactionAdvice.invoke(CTTransactionAdvice.java:80)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec] 	at com.sun.proxy.$Proxy778.getNode(Unknown Source)
     [exec] 	at com.liferay.wiki.service.WikiNodeLocalServiceUtil.getNode(WikiNodeLocalServiceUtil.java:331)
     [exec] 	at com.liferay.wiki.model.impl.WikiPageImpl.getNode(WikiPageImpl.java:264)
     [exec] 	at com.liferay.wiki.web.internal.asset.model.WikiPageAssetRenderer.<init>(WikiPageAssetRenderer.java:90)
     [exec] 	at com.liferay.wiki.web.internal.asset.model.WikiPageAssetRendererFactory.getAssetRenderer(WikiPageAssetRendererFactory.java:92)
     [exec] 	at com.liferay.asset.kernel.model.BaseAssetRendererFactory.getAssetRenderer(BaseAssetRendererFactory.java:67)
     [exec] 	at com.liferay.depot.web.internal.asset.model.DepotAssetRendererFactoryWrapper.getAssetRenderer(DepotAssetRendererFactoryWrapper.java:74)
     [exec] 	at com.liferay.portlet.asset.model.impl.AssetEntryImpl.getAssetRenderer(AssetEntryImpl.java:46)
     [exec] 	at com.liferay.asset.entry.rel.service.impl.AssetEntryAssetCategoryRelLocalServiceImpl._reindex(AssetEntryAssetCategoryRelLocalServiceImpl.java:220)
     [exec] 	at com.liferay.asset.entry.rel.service.impl.AssetEntryAssetCategoryRelLocalServiceImpl.deleteAssetEntryAssetCategoryRelByAssetEntryId(AssetEntryAssetCategoryRelLocalServiceImpl.java:110)
     [exec] 	at sun.reflect.GeneratedMethodAccessor494.invoke(Unknown Source)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec] 	at com.sun.proxy.$Proxy615.deleteAssetEntryAssetCategoryRelByAssetEntryId(Unknown Source)
     [exec] 	at com.liferay.asset.internal.service.AssetEntryAssetCategoryRelAssetEntryLocalServiceWrapper.deleteEntry(AssetEntryAssetCategoryRelAssetEntryLocalServiceWrapper.java:68)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66)
     [exec] 	at com.sun.proxy.$Proxy617.deleteEntry(Unknown Source)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
     [exec] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
     [exec] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
     [exec] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
     [exec] 	at com.sun.proxy.$Proxy49.deleteEntry(Unknown Source)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule._smartDelete(DataGuardTestRule.java:564)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule._autoDeleteLeftovers(DataGuardTestRule.java:293)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule._autoDeleteAndAssert(DataGuardTestRule.java:193)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.afterClass(DataGuardTestRule.java:115)
     [exec] 	at com.liferay.portal.kernel.test.rule.DataGuardTestRule.afterClass(DataGuardTestRule.java:73)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:66)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec] 	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:181)
     [exec] 	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec] 	at java.lang.Thread.run(Thread.java:745)
     [exec] 
     [exec] com.liferay.wiki.service.test.WikiPageLocalServiceTest > testAddFrontPageWithoutRequiredCategory STARTED```

**Comment by adolfopa** [comment]
Thanks a lot @Hanlf !

@IstvanD can you take a look and see if you can reproduce it locally?

**Comment by IstvanD** [comment]
Hi @adolfopa 

Thank you for the help!

I could reproduce the behavior both on 7.3.x **and** master.
My debugging efforts showed me the following: when the post-test cleanup happens, `DataGuardTestRule._smartDelete` will create an Asset Renderer for each object to be deleted. When it comes to Wiki Pages, the Asset Renderer's constructor will call [this part](https://github.com/liferay/liferay-portal/blob/master/modules/apps/wiki/wiki-web/src/main/java/com/liferay/wiki/web/internal/asset/model/WikiPageAssetRenderer.java#L90), but for both master and 7.3.x, it will fail to find the Page's Node and execute [this line](https://github.com/liferay/liferay-portal/blob/master/modules/apps/wiki/wiki-service/src/main/java/com/liferay/wiki/model/impl/WikiPageImpl.java#L270) and then return with a new WikiNode.
The difference between master and 7.3.x is that on master, logging an error (`_log.error(exception, exception);`) will not cause a test failure while on 7.3.x it will.

Best regards,
István

**Comment by adolfopa** [comment]
I see. If this only happens in this test, we could fix it by adding that error message as expected (hacky, but at least we avoid changing production code to cater for test needs). Otherwise, we have a bit of a problem.

Maybe it would be possible to make 7.3.x behave in the same way as master?

**Comment by IstvanD** [comment]
Hi @adolfopa 
You mean, that we should lower the message's log level to WARN?

**Comment by adolfopa** [comment]
I mean adding an annotation to the test, something like this:
```
	@ExpectedLogs(
		expectedLogs = {
			@ExpectedLog(
				expectedLog = "com.liferay.document.library.kernel.exception.NoSuchFileException",
				expectedType = ExpectedType.CONTAINS
			)
		},
		level = "ERROR", loggerClass = DynamicQueryUADExporter.class
	)
	@Test
	public void testExportAllWithMissingBinary() throws Exception {
        ....
```
But this will only work if that's the only test failing. If there are too many, we'll need to do something else.

**Comment by IstvanD** [comment]
Thanks for the hint! Would this work though, as it is not the test case itself (`WikiNodeLocalServiceTest.testMediaLinks`) that throws the exception but the cleanup process (`DataGuardTestRule._autoDeleteAndAsser`)?
What should be the value of `loggerClass`?

**Comment by IstvanD** [comment]
Hi @adolfopa 

I added a `WikiPageLocalServiceUtil.deletePage(importedPage);` to the end of `WikiNodeLocalServiceTest.testMediaLinks` but alas, the error persists.

**Comment by adolfopa** [comment]
@IstvanD See my followup https://github.com/liferay-lima/liferay-portal/pull/2037 With that change, I no longer get the error when running the tests.

Please review it, and if you're ok, I'll forward it to Brian.

**Comment by adolfopa** [comment]
@IstvanD Can you handle the backport to 7.3.x if the changes are fine?

**Comment by IstvanD** [comment]
@adolfopa thx. I tested [your changes](https://github.com/liferay-lima/liferay-portal/pull/2037) ported to 7.3.x and the error indeed is resolved.

**Comment by IstvanD** [comment]
@adolfopa of course, I'll handle the backport.

**Comment by adolfopa** [comment]
Closing in favor of https://github.com/liferay-lima/liferay-portal/pull/2037

**Pull request closed without merging**
