### PR TITLE
LPS-189879 DM View History option

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Added View History option to the dropdown, only for file entries. 
Screenshot 2023-07-07 at 11 05 57

Also, separated folder actions in two groups: 
Screenshot 2023-07-07 at 11 08 02

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
