### PR TITLE
LPS-197121 DM Audio preview Alert

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
### **Before:**
Screenshot 2023-10-02 at 13 24 35

### **After:**
Screenshot 2023-10-02 at 13 33 29

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
@AliciaGarciaGarcia I cannot make it work the preview of videos, but I guess it renders the same _.jsp,_ so this fix will work in both cases, could you please confirm me this?

**Comment by AliciaGarciaGarcia** [comment]
@ambrinchaudhary 

image on video
image

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Checking failures

**Comment by austinchiang** [comment]
Looks like we'll need to update some tests

**Comment by austinchiang** [comment]
ci:test

**Comment by austinchiang** [comment]
Test results look good

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
