### PR TITLE
LPS-160889 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-160889

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:lima

**Comment by austinchiang** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @austinchiang,
According to [ci:test:echo](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1948164999&testrayRunId=1948165032), there are three affected cases still failing.
https://testray.liferay.com/home/-/testray/case_results/1948166347
https://testray.liferay.com/home/-/testray/case_results/1948168189
https://testray.liferay.com/home/-/testray/case_results/1948166474

**Pull request closed without merging**
