### PR TITLE
LPS-160252, LPS-177305, LPS-176368

### PR DESCRIPTION
**Pull request by austinchiang**
LPS-160252 Remove Dev FF from code
Removed Developer Feature Flag LPS-156421 from code
See https://issues.liferay.com/browse/LPS-160252

LPS-177305 Remove Dev FF for KB navigation and interaction
Removed Developer Feature Flag LPS-166643 from code
See https://issues.liferay.com/browse/LPS-177305

LPS-176368 Add KB tests to acceptance
https://issues.liferay.com/browse/LPS-176368

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
KBAdmin#ExpirationNotificationShowsWhenNotificationDateIsReached seems flaky since it passed here https://github.com/liferay-lima/liferay-portal/pull/4060

KBDisplayPage#CanViewArticlesViaKBNavigation failure is a known issue

So PR looks fine

**Comment by marcogalluzzi** [comment]
This PR is waiting for this other PR to pass: [Allow Resize in <VerticalBar.Panel> ](https://github.com/liferay/clay/issues/5348)

**Comment by austinchiang** [comment]
@ambrinchaudhary @marcogalluzzi FYI looks like we need to rebase this pull before sending it. I'm not sure if it's better to do that now or wait until the Clay is merged

**Comment by ambrinchaudhary** [comment]
> @ambrinchaudhary @marcogalluzzi FYI looks like we need to rebase this pull before sending it. I'm not sure if it's better to do that now or wait until the Clay PR is merged

Personally, I would wait to Clay PR to resolve conflicts here, just to avoid doing this one more time.

**Comment by ambrinchaudhary** [comment]
Closing in favor of https://github.com/liferay-lima/liferay-portal/pull/4141

**Pull request closed without merging**
