### PR TITLE
LPS-137782 bug depot member organizations breadcrumb alignment

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-137782

**Before this PR**
image

**After this PR**
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
@boton in my opinion there is no need to call another team

**Comment by Hanlf** [comment]
The ci job is running more than 15 hours, should be some ci issue, stop it.

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
