### PR TITLE
LPS-192636 Make directory deletion asynchronous

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-192636

When deleting a whole store directory (e.g. when removing all file versions for a document), the portal no longer tries to reference that content in any way (even to check that it is not present). As it doesn't matter when content is removed as long as it is deleted eventually, we can trigger the deletion asynchronously. This will make things faster for stores where directory deletion is not particularly efficient (e.g. Google Cloud Storage).

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
Please help to solve the SF issue.

**Comment by AliciaGarciaGarcia** [comment]
rebased and sf'd

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:lima

**Comment by AliciaGarciaGarcia** [comment]
ci:test:headless

**Comment by Jeremy-Ch** [comment]
Hi @AliciaGarciaGarcia Could you help to solve the conflicts? Thanks.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1327401_1498

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
