### PR TITLE
LPS-171740 KB Navigation Pane options BUG

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
The above failures are not related to this PR, sent it to BChan:https://github.com/brianchandotcom/liferay-portal/pull/128332

**Pull request closed without merging**
