### PR TITLE
LPS-118539 The table borders are missing in wiki

### PR DESCRIPTION
**Pull request by boton**
The table borders don't show when the user is editing a wiki entry.

**Before**

image

**After**
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
See liferay-frontend#213.

**Comment by ambrinchaudhary** [comment]
Closing PR... Frontend team will send it after review. 
Thanks @boton!

**Pull request closed without merging**
