### PR TITLE
LPS-159602 add child articles to the vertical menu

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-159602 add child articles to the vertical menu
- LPS-159602 order by priority

https://user-images.githubusercontent.com/47524751/183691603-da492fcc-4e96-47f7-89d3-b7adad0f123f.mp4

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
LGTM, Thanks! 

Just check there is a conflicting file in this pull

**Comment by AliciaGarciaGarcia** [comment]
rebase and merge conflicts

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
