### PR TITLE
LPS-128916 Parser error appears when uploading ogg file while Xuggler is enabled

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

The `org-vorbis-java-tika` library throws an exception during parsing of an .ogg file if it's `xmpDM:duration` property has more than one value.
I patched the library to skip extracting the duration in this case and continue with the parsing instead of failing with an exception.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by adolfopa** [comment]
ci:forward

**Comment by IstvanD** [comment]
Thanks for reviewing and forwarding, @adolfopa!

**Pull request closed without merging**
