### PR TITLE
LPS-117787 Include scope information

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
This will probably fail again :( should be caused by https://issues.liferay.com/browse/LPS-117858 which still needs to be fixed

**Comment by boton** [comment]
I think that we have the same problem because https://issues.liferay.com/browse/LPS-117858 I presume is fixed here but isn't merged brianchandotcom#91846.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
