### PR TITLE
LPS-155973 Add loading to render the correct wiki tree

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-155973

When adding a second wiki tree to the page, the portlet will be stuck with an animation. This was due to getting the first wiki tree and ignoring all the other trees. By adding `.loading`, we are able to grab the first tree and then continue with the next tree when the script runs again.
Let me know if there are any questions or comments about this.

Thank you.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
