### PR TITLE
LPS-148585 The field help text of the DM cache settings could be more fluent

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-148585 change message to be more fluent
- LPS-148585 build lang
Change the message:

image

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
rebase and solve merge properties

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1287401_2192

**Comment by adolfopa** [comment]
ci:reevaluate:1287401_2192

**Comment by austinchiang** [comment]
@AliciaGarciaGarcia I was reviewing https://issues.liferay.com/browse/LPS-146749 and there is another minor issue I detected about the grammar. Since this pull has not been sent to BChan yet can you add the following changes? 

Since there is an article ("the", "a") in the help text under Max Age and Uncacheable Mime Types, we should try to keep the formatting the same with the text under Cache Control. So:
"Set cache control policy for documents with view permissions for guests" --> "Set the cache control..."

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
