### PR TITLE
LPS-187517 Apply the correct modal name to the item selector

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
LGTM, thanks @robertoDiaz

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
