### PR TITLE
LPS-121858 Migrate v2 usages in announcements/announcements-web

### PR DESCRIPTION
**Pull request by julien**
The `<clay:management-toolbar-v2 />` tag has been replaced with the
`<clay:management-toolbar />` tag (which uses clay v3).

Creating announcements and alerts as well a deleting them works as
expected.

**Test plan**:
- From the global menu, navigate to "Communication > Announcement and Alerts"
- Create a new Announcement
- From the management toolbar, select it and delete it.
- Select the **Alerts** tab
- Create one or several alerts
- From the management toolbar, selecting and deleting should work as expected.

Additionally, I've created [this LPS](https://issues.liferay.com/browse/LPS-127443) to warn the Lima team about a bug (also happening with `<clay:management-toolbar-v2 />`, [discussed on Slack](https://liferay.slack.com/archives/CLD39UKM5/p1612519927036100))

**Orignally reviewed [here](https://github.com/liferay-frontend/liferay-portal/pull/761)**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by julien** [comment]
@boton thanks ... maybe you should wait for CI to finish it's tests?

**Review by boton — APPROVED** [review]
LGTM :) @carloslancha feel free to forward it's tested and checked

**Comment by boton** [comment]
> @boton thanks ... maybe you should wait for CI to finish its tests?
> 
> (What I want to say is, there's no rush but I appreciate the quick review)

Ok I don't forward directly, but check and review it is done

**Comment by julien** [comment]
@boton thanks a lot for that. Let's see if @carloslancha is OK with these changes too. And then we can see if CI is happy too.

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
LGTM. Thx for reporting that issue @julien !

**Comment by carloslancha** [comment]
ci:forward

**Comment by julien** [comment]
@carloslancha no worries :+1:

**Pull request closed without merging**
