### PR TITLE
[TS] LPS-151886 Infinite redirect loop when using a language with a variant

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-151886

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@jorgediaz-lr Can you send this PR to someone from Core Infrastructure? Thanks!

**Comment by jorgediaz-lr** [comment]
ok @adolfopa

**Comment by jorgediaz-lr** [comment]
Sent to https://github.com/liferay-core-infra/liferay-portal/pull/663

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Pull request closed without merging**
