### PR TITLE
LPS-194259 file should add the action copy if has download permission and if is not external repository

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
… and if is not external repository

and the active FF

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
> Hi @AliciaGarciaGarcia I don't understand how this PR is related to the issue https://liferay.atlassian.net/browse/LPS-194259 It seems that you are removing the check specified in the issue (disabling if file size = 0)

@marcogalluzzi 
The impedibug is that : _if file size is 0 the copy is disabled_. This behavior is wrong. So I'm solving it.
The "copy to" action on the management toolbar has to have the same conditions than on the dropdown action of the file.

**Review by marcogalluzzi — COMMENTED** [review]
Very good!

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
