### PR TITLE
LPS-175916 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://liferay.atlassian.net/browse/LPS-175916

@austinchiang The impedibug is not fixed and it should not be fixed this week, so I just wrote the test with the expected behavior.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by austinchiang — APPROVED** [review]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
