### PR TITLE
LPS-122144 Declare portlet CSS in portlet properties

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@austinchiang We need to update the Poshi tests. See the failure in https://github.com/liferay-lima/liferay-portal/pull/946.

As we moved the views to the Translations portlet, we need to update the portlet ID.

Thanks!

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
ci:test:translations

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/969

**Pull request closed without merging**
