### PR TITLE
LPS-160889 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-160889

This is only for master.

@austinchiang
cc @liuxingye

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:lima

**Comment by austinchiang** [comment]
ci:test:echo

**Comment by austinchiang** [comment]
Testing fixes here as well https://github.com/liferay-lima/liferay-portal/pull/3376 @Tim-Cao

**Comment by Tim-Cao** [comment]
Hi @austinchiang, according to [ci:test:echo](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1948130406&testrayRunId=1948143751), all affected cases are fixed and no more cases broken.

**Comment by Tim-Cao** [comment]
Compare ci:test:lima and routine suite
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1948252270&testrayRunIdA=1948706233&testrayTeamId=1609378000&statusB=3

**Comment by Tim-Cao** [comment]
image
image
image

Hi @austinchiang, there are three kinds of ellipsis icons from affected lima cases. I've sent additional fix.
Would you mind double checking?

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:lima

**Comment by Tim-Cao** [comment]
Unique failures from ci:test:lima https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1949012343&testrayRunIdA=1948706233&testrayTeamId=1609378000&statusB=3

**Comment by Tim-Cao** [comment]
Sent additional fix to cover this kinds of failure.
https://testray.liferay.com/home/-/testray/case_results/1949014168

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
