### PR TITLE
LPS-131996 Add preview support for some source code formats

### PR DESCRIPTION
**Pull request by adolfopa**
To test this, enable the OpenOffice integration and upload a Js, CSS, JSP, JSPF, Java or SH file.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
@adolfopa - Some of the builds were aborted in this pull request test. Please retest if results needed. Sorry for any inconvenience.

**Review by AliciaGarciaGarcia — APPROVED** [review]
Works OK with LibreOffice.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
