### PR TITLE
LPS-131604 Use a jspf file instead of buffer

### PR DESCRIPTION
**Pull request by boton**
A follow up of https://github.com/brianchandotcom/liferay-portal/pull/101975#issuecomment-843475434.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
