### PR TITLE
LPS-182204 Disable comments when in a display page

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-182204

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Review by marcogalluzzi — APPROVED** [review]
Good refactorization!

**Comment by marcogalluzzi** [comment]
Something strange happens with the your branch @adolfopa 

> The sender branch SHA could not be found on https://github.com/liferay-lima/liferay-portal/pull/4235. The sender branch
> may have been force pushed or deleted after the pull request test was initiated.
>
> fatal: Not a valid branch point: 'b4fdbd9b6347507af65f0e09e4bfd0a866c29067'.

**Comment by adolfopa** [comment]
@marcogalluzzi Yes, I made a ci stop and a push-force soon after opening the pr (a silly sf mistake). Maybe the ci didn't get the message soon enough and got confused with the old branch.

**Comment by adolfopa** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
Hi @adolfopa I've been checking the failing tests and I've found the following error.

Steps
* Add the "Blogs" widget to a page
* Add a blog entry
* Go to the configuration of the blog widget
* Set the "Display Template" option to "Card"
* The following error is shown instead of the blog entry:

```
An error occurred while processing the template.
Multiple compatible overloaded variations were found with the same priority.
The FTL type of the argument values were: Null, extended_hash+string (com.liferay.blogs.model.impl.BlogsEntryImpl wrapped into f.e.b.StringModel).
The Java type of the argument values were: Null, com.liferay.blogs.model.impl.BlogsEntryImpl.
The matching overload was searched among these members:
    static com.liferay.blogs.web.internal.util.BlogsEntryUtil.getDisplayTitle(ResourceBundle, com.liferay.blogs.model.BlogsEntry),
    static com.liferay.blogs.web.internal.util.BlogsEntryUtil.getDisplayTitle(Locale, com.liferay.blogs.model.BlogsEntry)

...
```

**Comment by adolfopa** [comment]
Thanks @marcogalluzzi. I've removed the BlogsEntryUtil.getDisplayTitle(locale, blogsEntry) override in https://github.com/liferay-lima/liferay-portal/pull/4235/commits/cf65405fab5fdb2f9261c71ca4534b33f1c905be, using instead the resource bundle (in the BlogsViewEntryDisplayContext#getBlogsEntryTitle method).

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Added two additional commits to fix the failing test. No other changes.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
@Hanlf SF failures are not related to this PR.
We already sent the SF fix: https://github.com/ling-alan-huang/liferay-portal/pull/1810 https://github.com/ling-alan-huang/liferay-portal/pull/1809

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
