### PR TITLE
LPS-118380 Do not show redirection pages in the child pages list

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @robertoDiaz,

What do you think about https://github.com/liferay-lima/liferay-portal/pull/548?

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
