### PR TITLE
LPS-159175 Add version details to kb article edit view

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Note**: **NOT** behind a Feature Flag, as this seems like a bug in current master version and does not depend on the revamp

**BEFORE:** 
KB Versions BEFORE

KB Versions actions BEFORE

**AFTER:**

Screenshot 2022-08-05 at 13 50 23

KB Versions icons AFTER

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
