### PR TITLE
LPS-194217 Cannot change favicon from favicon extension

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-194217)

Ey, @Liferay-lima !

 I’m sending you the fix for this blocker. 

 This also fix: 
- [LPS-194219](https://liferay.atlassian.net/browse/LPS-194219)
- [LPS-194221](https://liferay.atlassian.net/browse/LPS-194221)
- [LPS-194231](https://liferay.atlassian.net/browse/LPS-194231)

## Test Scenario 1

1. Add a theme favicon extension using https://www.google.com/favicon.ico
2. Add a new site
3. Add a widget page
4. Navigate to the Design section
5. Change the favicon to the favicon extension

Screenshot 2023-08-23 at 11 45 52

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
@adolfopa reviewed :+1:

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by epark18** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/4624

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
