### PR TITLE
LPS-172556 KB View Template: more actions dropdown

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Follow up from https://github.com/liferay-lima/liferay-portal/pull/3911

See issue https://issues.liferay.com/browse/LPS-172556.
Enable FF
feature.flag.LPS-166643=true

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
