### PR TITLE
LPS 115318 LPS 115558

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
@4lejandrito compile failure at fragment service. Looks unique to this pull. Reproduced locally
```
   [exec] > Task :apps:fragment:fragment-service:compileJava
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/fragment/fragment-service/src/main/java/com/liferay/fragment/service/impl/FragmentEntryLocalServiceImpl.java:372: error: method fetchByG_FEK_First in interface FragmentEntryPersistence cannot be applied to given types;
     [exec] 		return fragmentEntryPersistence.fetchByG_FEK_First(
     [exec] 		                               ^
     [exec]   required: long,String,OrderByComparator<FragmentEntry>
     [exec]   found: long,String
     [exec]   reason: actual and formal argument lists differ in length
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 1 error
     [exec] 
     [exec] > Task :apps:fragment:fragment-service:compileJava FAILED
     [exec] > Task :apps:fragment:fragment-impl:processResources
     [exec] 
     [exec] > Task :apps:dynamic-data-mapping:dynamic-data-mapping-form-report-web:packageRunBuild
     [exec] Bundling took 49s
     [exec] Done in 52.18s.
```

**Comment by 4lejandrito** [comment]
Totally unrelated to my changes :(

**Comment by austinchiang** [comment]
Can we rebase the repo and try again?

**Comment by 4lejandrito** [comment]
It won't get merged soon enough so I will keep working on top of it and resend in the evening.

Thanks!

**Pull request closed without merging**
