### PR TITLE
LPS-128523 Only replace if exist

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by boton — APPROVED** [review]
I avoid undefined given a default value and add change the `getValue` function too.

@carloslancha Can you review these changes? 🙏

**Comment by jpince** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
