### PR TITLE
[TS] LPS-172530 Root Folder configuration in the Document & Media widget is lost when searching.

### PR DESCRIPTION
**Pull request by thienquach87**
Hi Team,
Here is the PR for fixing  https://issues.liferay.com/browse/LPS-172530. The original PR(https://github.com/thienquach87/liferay-portal/pull/24) was passed my review.
Please help review it and leave your comments. 
Thanks.

Notes:
Since we are indexing the treePath to search in folders and the tree path of the folder includes its folderId, that's why the search folder will be shown in the result. The idea is to index the folders with the tree path without the folderId.

cc:@tototrinh

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
Hi, I checked this and I found little things:

on the ticket is said
image
but I still can see the folder
image

This is correct and the ticket should be updated or it failing?

and another thing is the behavior with the Asset Libraries and the searching

If you :
(after the steps of the ticket)
1. create an asset library 
2. Link to the site
3. configure the D&M widget to show the home folder of the Asset library
4. Click the search icon in the search box (inside the Documents and Media widget)

it shows the data of the site, not the asset library

I do not know if this can be another issue, but take it into consideration and maybe create another issue.

Thanks!!

**Comment by thienquach87** [comment]
> Hi, I checked this and I found little things:
> 
> on the ticket is said image but I still can see the folder image
> 
> This is correct and the ticket should be updated or it failing?
> 
> and another thing is the behavior with the Asset Libraries and the searching
> 
> If you : (after the steps of the ticket)
> 
> 1. create an asset library
> 2. Link to the site
> 3. configure the D&M widget to show the home folder of the Asset library
> 4. Click the search icon in the search box (inside the Documents and Media widget)
> 
> it shows the data of the site, not the asset library
> 
> I do not know if this can be another issue, but take it into consideration and maybe create another issue.
> 
> Thanks!!

@tototrinh Could you help to double check?

**Comment by tototrinh** [comment]
Hi @AliciaGarciaGarcia. Thanks for your feedback.
Could you please give me the steps that you get the issue?
Here's what happens in my local:

https://user-images.githubusercontent.com/52560165/212257588-6dd8cd96-c15d-4bb4-85dc-0e605aa4970a.mp4

**Comment by AliciaGarciaGarcia** [comment]
Hi @tototrinh 

on the case of the 

> **Expected result** 
> FolderA is not shown,  and FolderB has only “Home” as breadcrumb display.

I followed the steps of the [ticket](https://issues.liferay.com/browse/LPS-172530) 

Ant this is the result: 
https://user-images.githubusercontent.com/47524751/212301428-a276767a-8362-4b78-9aac-bde7f10b9b84.mp4


FYI : I rebased with master 55c669f0211d2ccca71b1c0f290dacb84f1f89a2 , made an `ant all` and I'm on dxp

**Comment by tototrinh** [comment]
Hi @AliciaGarciaGarcia,
After applying this change folder A should be indexed by the tree path without its folder Id. It means the folder will be indexed by `"treePath" : ""` instead of ` "treePath" : [
            "",
            "[folderId of folderA]"
          ],
` 
```
      {
        "_index" : "liferay-20097",
        "_type" : "LiferayDocumentType",
        "_id" : "com.liferay.document.library.kernel.model.DLFolder_PORTLET_43946",
        "_score" : 3.3853865,
        "_source" : {
          "entryClassPK" : "43946",
          "publishDate_sortable" : 1673838525992,
          "hidden" : "false",
          "groupId" : "20121",
          "priority_sortable" : 0.0,
          "publishDate" : "20230116030845",
          "createDate_sortable" : 1673838525992,
          "title" : "FolderA",
          "uid" : "com.liferay.document.library.kernel.model.DLFolder_PORTLET_43946",
          "groupRoleId" : "20121-20114",
          "scopeGroupId" : "20121",
          "title_sortable" : "foldera",
          "modified" : "20230116030845",
          "modified_sortable" : 1673838525992,
          "assetEntryId_sortable" : 43948,
          "expirationDate_sortable" : 9223372036854775807,
          "viewCount" : "0",
          "createDate" : "20230116030845",
          "expirationDate" : "99950812133000",
          "statusByUserId" : "0",
          "visible" : "true",
          "entryClassName" : "com.liferay.document.library.kernel.model.DLFolder",
          "roleId" : [
            "20105",
            "20106"
          ],
          "viewCount_sortable" : 0,
          "userName" : "test test",
          "priority" : "0.0",
          "userId" : "20125",
          "folderId" : "0",
          "assetEntryId" : "43948",
          "localized_title_zh_CN" : "foldera",
          "localized_title_zh_CN_sortable" : "foldera",
          "localized_title_es_ES" : "foldera",
          "localized_title_es_ES_sortable" : "foldera",
          "localized_title_sv_SE" : "foldera",
          "localized_title_sv_SE_sortable" : "foldera",
          "localized_title_ja_JP" : "foldera",
          "localized_title_ja_JP_sortable" : "foldera",
          "localized_title_nl_NL" : "foldera",
          "localized_title_nl_NL_sortable" : "foldera",
          "localized_title_hu_HU" : "foldera",
          "localized_title_hu_HU_sortable" : "foldera",
          "localized_title_ar_SA" : "foldera",
          "localized_title_ar_SA_sortable" : "foldera",
          "localized_title_pt_BR" : "foldera",
          "localized_title_pt_BR_sortable" : "foldera",
          "localized_title_de_DE" : "foldera",
          "localized_title_de_DE_sortable" : "foldera",
          "localized_title_ca_ES" : "foldera",
          "localized_title_ca_ES_sortable" : "foldera",
          "localized_title_fi_FI" : "foldera",
          "localized_title_fi_FI_sortable" : "foldera",
          "localized_title_fr_FR" : "foldera",
          "localized_title_fr_FR_sortable" : "foldera",
          "localized_title" : "foldera",
          "localized_title_en_US" : "foldera",
          "localized_title_en_US_sortable" : "foldera",
          "stagingGroup" : "false",
          "companyId" : "20097",
          "treePath" : "",
          "status" : "0"
        }
      },

```
I rebased with Master 923f924efd027680f0669216761d55546f07a9b0 and it works as expected in my local.
It's really weird that folder A still being searched by folderA's folderId while it is not indexed by this Id in the tree path.
Could you please help re-check it? Thanks.

**Comment by thienquach87** [comment]
Hi @AliciaGarciaGarcia,

 I also could not reproduce this issue after applying the To's fixing source. It works as the expectation. Could you help to double check?

Thank you!

**Comment by AliciaGarciaGarcia** [comment]
Hi @thienquach87 and @tototrinh 

Today I can not reproduce the issue as I reproduced it on Friday.

I'm confused :D but I won't complain

however the problem with the Asset library still happens.


https://user-images.githubusercontent.com/47524751/212666820-f405522a-d54b-4247-ab06-34f70f777998.mp4



do you want open an issue about it and me to follow this PR or you will take a look?

thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @tototrinh 

do not worry, I'll create a new one.

have nice holidays. And happy new year :)

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
Hi @tototrinh 

baseline needed on portal-impl and portal-kernel

```
     [echo] run.batch.test.action.start.timestamp: 01-16-2023 05:35:39:707 PST
     [echo] Checking for baseline log files.
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-impl.log
     [echo] ##
     [echo] 
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 65.1.0
[beanshell] 
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log
     [echo] ##
     [echo] 
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 93.1.0
```

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by thienquach87** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @thienquach87 Could you please check this failure: [com.liferay.portal.search.facet.faceted.searcher.test.FolderFacetTest](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/8005/modules-integration-mysql57-jdk8/3/1/jenkins-console.txt.gz?authuser=0), it should be related to this PR, because it only failed on this PR relevant tests.

```
     [exec] com.liferay.portal.search.facet.faceted.searcher.test.FolderFacetTest > testTreePathSelection FAILED
     [exec]     java.lang.AssertionError: [{contentLength_en_US=[9], entryClassPK=[45169], fileName=[1JCCOaz3], localized_title_sv_SE=[1jccoaz3], groupId=[45151], publishDate=[20230116132118], mimeType=[text_plain], classNameId=[0], createDate_sortable=[1673875278621], readCount=[0], localized_title_nl_NL=[1jccoaz3], classPK=[0], localized_title_zh_CN=[1jccoaz3], scopeGroupId=[45151], modified=[20230116132118], localized_title_ar_SA_sortable=[FTwuLkYqXBkBDAEMAA==], modified_sortable=[1673875278677], localized_title_pt_BR=[1jccoaz3], localized_title_ca_ES_sortable=[FTwuLkYqXBkBDAEMAA==], mimeType_String_sortable=[text_plain], content_en_US=[��������!���������], localized_title_zh_CN_sortable=[FbqsrMSo2hkBDAEMAA==], localized_title_ca_ES=[1jccoaz3], localized_title_hu_HU_sortable=[FTwuLkYqXBkBDAEMAA==], visible=[true], localized_title_nl_NL_sortable=[FTwuLkYqXBkBDAEMAA==], fileEntryTypeId=[0], viewCount_sortable=[0], priority=[0.0], classTypeId=[0], folderId=[45164], companyId=[20098], size=[8], localized_title_fr_FR=[1jccoaz3], title_en_US=[1JCCOaz3], status=[0], localized_title_hu_HU=[1jccoaz3], versionCount=[1.0], localized_title_pt_BR_sortable=[FTwuLkYqXBkBDAEMAA==], publishDate_sortable=[1673875278621], hidden=[false], dataRepositoryId=[45164], localized_title_fi_FI_sortable=[FTwuLkYqXBkBDAEMAA==], title=[1JCCOaz3], uid=[com.liferay.document.library.kernel.model.DLFileEntry_PORTLET_45169], localized_title_de_DE_sortable=[FTwuLkYqXBkBDAEMAA==], localized_title_en_US_sortable=[FTwuLkYqXBkBDAEMAA==], groupRoleId=[45151-20115], localized_title_fr_FR_sortable=[FTwuLkYqXBkBDAEMAA==], title_sortable=[1jccoaz3], assetEntryId_sortable=[45173], expirationDate_sortable=[9223372036854775807], viewCount=[0], localized_title_sv_SE_sortable=[FTwuLkYqXBkBDAEMAA==], localized_title_ja_JP=[1jccoaz3], localized_title_fi_FI=[1jccoaz3], size_sortable=[8], createDate=[20230116132118], expirationDate=[99950812133000], localized_title_es_ES_sortable=[FTwuLkYqXBkBDAEMAA==], entryClassName=[com.liferay.document.library.kernel.model.DLFileEntry], roleId=[20106, 20107], contentLength_en_US_sortable=[9], userName=[livh0duc 2n2ej1yw], userId=[45155], localized_title_ja_JP_sortable=[FTwuLkYqXBkBDAEMAA==], assetEntryId=[45173], localized_title=[1jccoaz3], stagingGroup=[false], localized_title_es_ES=[1jccoaz3], localized_title_en_US=[1jccoaz3], localized_title_ar_SA=[1jccoaz3], ddmContent=[text/plain; charset=ISO-8859-5 ISO-8859-5], treePath=[, 45164], localized_title_de_DE=[1jccoaz3]}}, length=1, query=null] expected:<2> but was:<1>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.portal.search.facet.faceted.searcher.test.FolderFacetTest.testTreePathSelection(FolderFacetTest.java:202)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] 
```

**Comment by thienquach87** [comment]
> Hi @thienquach87 Could you please check this failure: [com.liferay.portal.search.facet.faceted.searcher.test.FolderFacetTest](https://testray.liferay.com/reports/production/logs/2023-01/test-1-37/test-portal-acceptance-pullrequest(master)/8005/modules-integration-mysql57-jdk8/3/1/jenkins-console.txt.gz?authuser=0), it should be related to this PR, because it only failed on this PR relevant tests.
> 
> ```
>      [exec] com.liferay.portal.search.facet.faceted.searcher.test.FolderFacetTest > testTreePathSelection FAILED
>      [exec]     java.lang.AssertionError: [{contentLength_en_US=[9], entryClassPK=[45169], fileName=[1JCCOaz3], localized_title_sv_SE=[1jccoaz3], groupId=[45151], publishDate=[20230116132118], mimeType=[text_plain], classNameId=[0], createDate_sortable=[1673875278621], readCount=[0], localized_title_nl_NL=[1jccoaz3], classPK=[0], localized_title_zh_CN=[1jccoaz3], scopeGroupId=[45151], modified=[20230116132118], localized_title_ar_SA_sortable=[FTwuLkYqXBkBDAEMAA==], modified_sortable=[1673875278677], localized_title_pt_BR=[1jccoaz3], localized_title_ca_ES_sortable=[FTwuLkYqXBkBDAEMAA==], mimeType_String_sortable=[text_plain], content_en_US=[��������!���������], localized_title_zh_CN_sortable=[FbqsrMSo2hkBDAEMAA==], localized_title_ca_ES=[1jccoaz3], localized_title_hu_HU_sortable=[FTwuLkYqXBkBDAEMAA==], visible=[true], localized_title_nl_NL_sortable=[FTwuLkYqXBkBDAEMAA==], fileEntryTypeId=[0], viewCount_sortable=[0], priority=[0.0], classTypeId=[0], folderId=[45164], companyId=[20098], size=[8], localized_title_fr_FR=[1jccoaz3], title_en_US=[1JCCOaz3], status=[0], localized_title_hu_HU=[1jccoaz3], versionCount=[1.0], localized_title_pt_BR_sortable=[FTwuLkYqXBkBDAEMAA==], publishDate_sortable=[1673875278621], hidden=[false], dataRepositoryId=[45164], localized_title_fi_FI_sortable=[FTwuLkYqXBkBDAEMAA==], title=[1JCCOaz3], uid=[com.liferay.document.library.kernel.model.DLFileEntry_PORTLET_45169], localized_title_de_DE_sortable=[FTwuLkYqXBkBDAEMAA==], localized_title_en_US_sortable=[FTwuLkYqXBkBDAEMAA==], groupRoleId=[45151-20115], localized_title_fr_FR_sortable=[FTwuLkYqXBkBDAEMAA==], title_sortable=[1jccoaz3], assetEntryId_sortable=[45173], expirationDate_sortable=[9223372036854775807], viewCount=[0], localized_title_sv_SE_sortable=[FTwuLkYqXBkBDAEMAA==], localized_title_ja_JP=[1jccoaz3], localized_title_fi_FI=[1jccoaz3], size_sortable=[8], createDate=[20230116132118], expirationDate=[99950812133000], localized_title_es_ES_sortable=[FTwuLkYqXBkBDAEMAA==], entryClassName=[com.liferay.document.library.kernel.model.DLFileEntry], roleId=[20106, 20107], contentLength_en_US_sortable=[9], userName=[livh0duc 2n2ej1yw], userId=[45155], localized_title_ja_JP_sortable=[FTwuLkYqXBkBDAEMAA==], assetEntryId=[45173], localized_title=[1jccoaz3], stagingGroup=[false], localized_title_es_ES=[1jccoaz3], localized_title_en_US=[1jccoaz3], localized_title_ar_SA=[1jccoaz3], ddmContent=[text/plain; charset=ISO-8859-5 ISO-8859-5], treePath=[, 45164], localized_title_de_DE=[1jccoaz3]}}, length=1, query=null] expected:<2> but was:<1>
>      [exec]     	at org.junit.Assert.fail(Assert.java:89)
>      [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
>      [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
>      [exec]     	at com.liferay.portal.search.facet.faceted.searcher.test.FolderFacetTest.testTreePathSelection(FolderFacetTest.java:202)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
>      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
>      [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
>      [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
>      [exec]     	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
>      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
>      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
>      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
>      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
>      [exec]     	at java.lang.Thread.run(Thread.java:745)
>      [exec] 
> ```

@tototrinh ,
Please help double check! thank you.

**Comment by locpham97** [comment]
ci:close

**Pull request closed without merging**
