### PR TITLE
LPS-153891 partial revert from LPS-147681 Add javax.portlet.version=3.0

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
The changes on the reading time is making to fail the Blogs Entry portlet.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
If we add the property `"javax.portlet.version=3.0"` to the `BlogsPortlet` the issue is solved BUT a Worst error is thrown because there is an error when trying to add the blog portlet on a widget page because the property is not on all the system portlets.

image


cc @ling-alan-huang

Error on console: 
```
2022-05-18 08:51:02.443 ERROR [http-nio-8080-exec-2][PortletRequestDispatcherImpl:304] Unable to dispatch request: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
2022-05-18 08:51:02.444 ERROR [http-nio-8080-exec-2][PortletServlet:119] null
javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:307) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:123) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:620) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:636) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:506) ~[portal-kernel.jar:?]
	at com.liferay.product.navigation.control.menu.web.internal.portlet.ProductNavigationControlMenuPortlet.doDispatch(ProductNavigationControlMenuPortlet.java:89) ~[bundleFile:?]
	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:309) ~[portal-kernel.jar:?]
...	
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.56]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
Caused by: org.apache.jasper.JasperException: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:440) ~[jasper.jar:9.0.56]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.56]
...	
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:291) ~[portal-impl.jar:?]
	... 186 more
Caused by: java.lang.RuntimeException: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
	at com.liferay.portal.kernel.util.BaseMapWrapper.doPut(BaseMapWrapper.java:105) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.HashMapBuilder$HashMapWrapper.put(HashMapBuilder.java:135) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.HashMapBuilder.put(HashMapBuilder.java:58) ~[portal-kernel.jar:?]
	at com.liferay.product.navigation.control.menu.web.internal.display.context.AddContentPanelDisplayContext.getAddContentPanelData(AddContentPanelDisplayConte
...	
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:364) ~[?:?]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:376) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:291) ~[portal-impl.jar:?]
	... 186 more
Caused by: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
	at com.liferay.portlet.internal.PortletRequestImpl.getRenderParameters(PortletRequestImpl.java:523) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletURLImpl._initMutableRenderParameters(PortletURLImpl.java:1642) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletURLImpl.<init>(PortletURLImpl.java:1317) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletURLImpl.<init>(PortletURLImpl.java:117) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.RenderURLImpl.<init>(RenderURLImpl.java:44) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletURLFactoryImpl._create(PortletURLFactoryImpl.java:236) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletURLFactoryImpl.create(PortletURLFactoryImpl.java:161) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.PortletURLFactoryUtil.create(PortletURLFactoryUtil.java:107) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.RequestBackedPortletURLFactoryUtil$LiferayPortletResponseRequestBackedPortletURLFactory.createControlPanelPortletURL(RequestBackedPortletURLFactoryUtil.java:240) ~[portal-kernel.jar:?]
	at com.liferay.portal.util.PortalImpl.getControlPanelPortletURL(PortalImpl.java:1807) ~[portal-impl.jar:?]
	at com.liferay.blogs.web.internal.asset.model.BlogsEntryAssetRendererFactory.getURLAdd(BlogsEntryAssetRendererFactory.java:124) ~[?:?]
	at com.liferay.depot.web.internal.asset.model.DepotAssetRendererFactoryWrapper.getURLAdd(DepotAssetRendererFactoryWrapper.java:155) ~[?:?]
	at com.liferay.asset.internal.util.AssetHelperImpl.getAddPortletURL(AssetHelperImpl.java:150) ~[?:?]
	at com.liferay.asset.internal.util.AssetHelperImpl.getAssetPublisherAddItemHolders(AssetHelperImpl.java:354) ~[?:?]
	at com.liferay.product.navigation.control.menu.web.internal.display.context.AddContentPanelDisplayContext._getAddContentsURLs(AddContentPanelDisplayContext.java:332) ~[bundleFile:?]
	at com.liferay.product.navigation.control.menu.web.internal.display.context.AddContentPanelDisplayContext.lambda$getAddContentPanelData$0(AddContentPanelDisplayContext.java:116) ~[bundleFile:?]
	at com.liferay.portal.kernel.util.BaseMapWrapper.doPut(BaseMapWrapper.java:98) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.HashMapBuilder$HashMapWrapper.put(HashMapBuilder.java:135) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.HashMapBuilder.put(HashMapBuilder.java:58) ~[portal-kernel.jar:?]
	at com.liferay.product.navigation.control.menu.web.internal.display.context.AddContentPanelDisplayContext.getAddContentPanelData(AddContentPanelDisplayContext.java:112) ~[bundleFile:?]
	at org.apache.jsp.add_005fpanel_jsp._jspService(add_005fpanel_jsp.java:267) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.56]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.56]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.56]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.56]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:364) ~[?:?]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:376) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:291) ~[portal-impl.jar:?]
	... 186 more
2022-05-18 08:51:02.480 ERROR [http-nio-8080-exec-2][render_portlet_jsp:131] null
java.lang.UnsupportedOperationException: Requires 3.0 opt-in
	at com.liferay.portlet.internal.PortletRequestImpl.getRenderParameters(PortletRequestImpl.java:523) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletURLImpl._initMutableRenderParameters(PortletURLImpl.java:1642) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletURLImpl.<init>(PortletURLImpl.java:1317) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletURLImpl.<init>(PortletURLImpl.java:117) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.RenderURLImpl.<init>(RenderURLImpl.java:44) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletURLFactoryImpl._create(PortletURLFactoryImpl.java:236) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletURLFactoryImpl.create(PortletURLFactoryImpl.java:161) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.PortletURLFactoryUtil.create(PortletURLFactoryUtil.java:107) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.RequestBackedPortletURLFactoryUtil$LiferayPortletResponseRequestBackedPortletURLFactory.createControlPanelPortletURL(RequestBackedPortletURLFactoryUtil.java:240) ~[portal-kernel.jar:?]
	at com.liferay.portal.util.PortalImpl.getControlPanelPortletURL(PortalImpl.java:1807) ~[portal-impl.jar:?]
	at com.liferay.blogs.web.internal.asset.model.BlogsEntryAssetRendererFactory.getURLAdd(BlogsEntryAssetRendererFactory.java:124) ~[?:?]
	at com.liferay.depot.web.internal.asset.model.DepotAssetRendererFactoryWrapper.getURLAdd(DepotAssetRendererFactoryWrapper.java:155) ~[?:?]
	at com.liferay.asset.internal.util.AssetHelperImpl.getAddPortletURL(AssetHelperImpl.java:150) ~[?:?]
	at com.liferay.asset.internal.util.AssetHelperImpl.getAssetPublisherAddItemHolders(AssetHelperImpl.java:354) ~[?:?]
	at com.liferay.product.navigation.control.menu.web.internal.display.context.AddContentPanelDisplayContext._getAddContentsURLs(AddContentPanelDisplayContext.java:332) ~[?:?]
	at com.liferay.product.navigation.control.menu.web.internal.display.context.AddContentPanelDisplayContext.lambda$getAddContentPanelData$0(AddContentPanelDisplayContext.java:116) ~[?:?]
	at com.liferay.portal.kernel.util.BaseMapWrapper.doPut(BaseMapWrapper.java:98) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.HashMapBuilder$HashMapWrapper.put(HashMapBuilder.java:135) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.util.HashMapBuilder.put(HashMapBuilder.java:58) ~[portal-kernel.jar:?]
	at com.liferay.product.navigation.control.menu.web.internal.display.context.AddContentPanelDisplayContext.getAddContentPanelData(AddContentPanelDisplayContext.java:112) ~[?:?]
```

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
Thanks @AliciaGarciaGarcia

**Pull request closed without merging**
