### PR TITLE
LPS-121949 Migrate v2 usages of clay:horizontal-card in item-selector-web

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-121949

In this PR we are updating Soy-based Clay2 horizontal card with React-based Clay3 horizontal card.

I was not able to find a real test case, please re-test on such, or at least point me to it. What I did is took test plan from https://github.com/liferay-lima/liferay-portal/pull/1100 and changed [this](https://github.com/liferay/liferay-portal/blob/master/modules/apps/item-selector/item-selector-web/src/main/resources/META-INF/resources/view_item_selector_view_descriptor.jsp#L72) `itemDescriptor.isCompact()` to `true`. These are the before / after screenshots on bottom.

> **Test plan**:
> 
> * Navigate to **Content & Data** > **Blogs**
> * Create a new blog entry and publish it
> * Create a content page
> * Drag and drop an HTML fragment on the page
> * Map the content of the HTML fragment to a blog entry

Notes:
- I analysed if horizontal card can be replaced by navigation card. `card-interactive` class [on the component](https://github.com/liferay/liferay-portal/blob/master/modules/apps/item-selector/item-selector-web/src/main/java/com/liferay/item/selector/web/internal/servlet/taglib/clay/ItemDescriptorHorizontalCard.java#L39) is typically an indicator that we should use the navigation card. But, in this case, new v3 horizontal card is a much better fit. Its API makes more sense with the `ItemDescriptor` model. For example, there might be a multiple item selection somewhere that uses cards with checkboxes, which is outside of navigation card's simpler API. If all of this holds water, removing the `card-interactive` class should be considered for the future, so that the component has consistent l&f.
- There is a slight difference in appearance between old and new component - border shadow is darker. I consider this very minor and improvement, but let me know if we need to equalize styles.

/cc @carloslancha @julien

Before:
before

After:
after

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]
lgtm

**Review by julien — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Thank @markocikos, I found a real test plan, don't worry about it's really hidden


**Test Plan:**
1. Click in the user menu
1. Go to Shared content
image
1. Filter in the management toolbar by Asset Types
image


I talk with @Emiliano about the shadows issue.
We would like to have a simple shadow if possible.

It's a little wired for me the final markup further than the shadow.
A card within another card makes sense for you? Is it the expected markup?

**Before (only one card)**
image

**After (card inside card)**
image

**Comment by boton** [comment]
We have another issue with the alignment but it's our issue :D I'll take a look with @ambrinchaudhary

**Comment by markocikos** [comment]
@boton we are fixing the double `card` class in https://github.com/liferay/clay/pull/3820. We can pause this PR until that one is merged and applied to portal.

/cc @carloslancha @julien

**Comment by boton** [comment]
> @boton we are fixing the double `card` class in [liferay/clay#3820](https://github.com/liferay/clay/pull/3820). We can pause this PR until that one is merged and applied to portal.
> 
> /cc @carloslancha @julien

This makes sense for me, fix the box-shadow issue too 🎉

**Comment by julien** [comment]
[A new version of clay](https://liferay.slack.com/archives/CNBG06JS3/p1607027478370900) was released yesterday so this should be fixed.

**Comment by markocikos** [comment]
Force-pushed. No changes, apart from rebase.

No double card class, no difference in shadow. Icons are less fuzzy, but I don't think that's gonna be an issue :slightly_smiling_face: 

Before:
before

After:
after

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by boton** [comment]
Looks great, thanks @markocikos

**Comment by boton** [comment]
ci:forward

**Comment by carloslancha** [comment]
ci:forward

**Comment by carloslancha** [comment]
ci:stop

**Pull request closed without merging**
