### PR TITLE
LPS-113857, LPS-108820 Restore friendlyUrl

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by boton** [comment]
See #81.

**Pull request closed without merging**
