### PR TITLE
[7.4-only] LPS-121959 Migrate v2 usages of clay:vertical-card in blogs/blogs-web

### PR DESCRIPTION
**Pull request by julien**
**Original PR** https://github.com/liferay-frontend/liferay-portal/pull/526

In this change, we replace `<clay:vertical-card-v2 />` (clay 2.x:Metal+soy) with `<clay:vertical-card />`  (clay 3.x: React)

**Test plan**:
- Navigate to **Content & Data** > **Blogs**
- Create a new Blog Entry
- Navigate to the previous page

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hey @julien @carloslancha , I get a _NullPointerException_ even after running an `ant all,` did you guys miss something in the pull? 

```
2020-11-23 12:57:46.175 ERROR [http-nio-8080-exec-1][IncludeTag:128] Current URL /group/guest/~/control_panel/manage?p_p_id=com_liferay_blogs_web_portlet_BlogsAdminPortlet&p_p_lifecycle=0&p_p_state=maximized&p_v_l_s_g_id=20122&p_p_auth=iYgCQnQ0 generates exception: java.lang.NullPointerException
java.lang.NullPointerException
	at com.liferay.frontend.taglib.clay.servlet.taglib.BaseCardTag.doStartTag(BaseCardTag.java:39)
	at com.liferay.frontend.taglib.clay.servlet.taglib.VerticalCardTag.doStartTag(VerticalCardTag.java:45)
	at org.apache.jsp.blogs_005fadmin.view_005fentries_jsp._jspService(view_005fentries_jsp:875)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:368)
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:380)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
	at com.liferay.portal.servlet.DirectServletPathRegisterDispatcher.include(DirectServletPathRegisterDispatcher.java:67)
	at com.liferay.portal.servlet.DirectRequestDispatcherFactoryImpl$IndirectRequestDispatcher.include(DirectRequestDispatcherFactoryImpl.java:190)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.doDispatch(ClassLoaderRequestDispatcherWrapper.java:79)
	at com.liferay.portal.servlet.ClassLoaderRequestDispatcherWrapper.include(ClassLoaderRequestDispatcherWrapper.java:53)
	at com.liferay.taglib.util.IncludeTag.includePage(IncludeTag.java:407)
```

**Comment by julien** [comment]
@ambrinchaudhary yes sorry forgot to update this PR this morning saying it depends on [this fix](https://github.com/liferay-frontend/liferay-portal/pull/534) - so closing for now.
Sorry about that

**Pull request closed without merging**
