### PR TITLE
LPS-160246 KB: hide product menu when current panel is open

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Before the fix we had this issue that is solved now: 
Screenshot 2022-08-10 at 12 22 25

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by boton — CHANGES_REQUESTED** [review]
The logic is good but we can move the 

```
if (productMenuOpen) {
  productMenu.hide();
}
```

to the end and add the proper listener before based on `productMenuOpen` too.

And avoid the hideProductMenu flag

**Comment by ambrinchaudhary** [comment]
Thanks for your review @boton , I've updated the commit with your suggestion

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
Tested and working thanks @ambrinchaudhary!

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
