### PR TITLE
LPS-137143

### PR DESCRIPTION
**Pull request by jesseyeh-liferay**
[LPS-137143](https://issues.liferay.com/browse/LPS-137143)

**Previous Pull Request**: https://github.com/liferay-lima/liferay-portal/pull/2216

**Changelog**:
* Remove redundant default value (https://github.com/liferay-lima/liferay-portal/pull/2216#discussion_r700342019)
* Replace string literals with named constants (https://github.com/liferay-lima/liferay-portal/pull/2216#discussion_r700340331)

From the original pull request:
> **Issue**
> Web Content Displays have a scope setting in their configuration that allows for users to limit the scope of selectable Web Content. However, as of 7.3, WCDs now display the Sites and Libraries breadcrumb, which allows users to select content from any site (thus ignoring the portlet-configured scope). This has since been determined to be unintended behavior.
> 
> **Solution**
> Per PTR-2570, this solution makes it so that the Sites and Libraries breadcrumb behaves as follows:
> |Portlet Scope|Behavior|
> |---|---|
> |Page|Hide the breadcrumb|
> |Site|Show the breadcrumb. In the breadcrumb, if the user navigates to "Sites," only the current site will be displayed. If the user navigates to "Asset Libraries," only the Asset Libraries connected to the current site will be displayed.|
> |Global|Show the breadcrumb. In the breadcrumb, if the user navigates to "Sites,", only the global site will be displayed. If the user navigates to "Asset Libraries", only the Asset Libraries connected to the global site will be displayed.|
> 
> This is achieved with the following steps:
> 1. [Determine the `scopeGroupType` and pass it into the `assetEntryItemSelectorCriterion`](https://github.com/jesseyeh-liferay/liferay-portal/blob/1d521242120160b752a2443a65a763f986c7821c/modules/apps/journal/journal-content-web/src/main/java/com/liferay/journal/content/web/internal/display/context/JournalContentDisplayContext.java#L528)
> 1. [Pass the `scopeGroupType` into the request](https://github.com/jesseyeh-liferay/liferay-portal/blob/1d521242120160b752a2443a65a763f986c7821c/modules/apps/asset/asset-browser-web/src/main/java/com/liferay/asset/browser/web/internal/item/selector/AssetEntryItemSelectorView.java#L122-L125) and [forward it to the Sites and Libraries breadcrumb link](https://github.com/ChrisKian/liferay-portal/blob/1d521242120160b752a2443a65a763f986c7821c/modules/apps/asset/asset-browser-web/src/main/java/com/liferay/asset/browser/web/internal/display/context/AssetBrowserDisplayContext.java#L590-L592)
> 1. Depending on the value of `scopeGroupType`, the breadcrumb behavior will be in accordance to the table outlined above. In the absence of a value, the behavior will default to the implementation prior to these changes (refer to changes in AssetBrowserDisplayContext.java and GroupSelectorTag.java).

### CODE REVIEW

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by jesseyeh-liferay** [comment]
ci:stop

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:sf

**Comment by jesseyeh-liferay** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
[com.liferay.journal.asset.test.JournalArticleAssetSearchTest.testOrderByCreateDateDesc failure](https://testray.liferay.com/zh/home/-/testray/cases/1518349807) only occurs on the PR, re-run it,

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The failure is not related to this PR, seems ci flaky, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@david-gutierrez-mesa this pull removes an Echo test. Can you please review and if it looks good forward? Thx

**Comment by david-gutierrez-mesa** [comment]
It makes sense to remove this test.

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Pull request closed without merging**
