### PR TITLE
LPS-140308 Move remaining logic/markup into friendly URL tag

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa baseline needed

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Push-forced baseline commit.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
Tested and working!

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
