### PR TITLE
LPS-170189 Add size sorting, make title sorting the default

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/issues/browse/LPS-170189

We were missing two details in the DM browser tag: the size sorting and making title sort the default. I've also disabled sorting when searching; we will always rely on relevance sorting.

Additionally, I've fixed a small bug when only one action in the creation menu was enabled; the management toolbar events for these two cases are handled separately. Now both cases should work in exactly the same way.

# How do I test it?

Create a bunch of blog entries with cover images. Make sure to upload those images to the blogs repository. Then:
1. Check that the "size" filter is available in the management toolbar. Create files of different sizes and verify that these are sorted correctly.
2. The "title" sorting order should be the default.
3. When searching, the sorting controls are not available.

*Note:* This is under feature flag LPS-168174.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]
Code changes LGTM. But I've tried to test it locally and for some reason I don't see the create (+) button... Already checked that the FF is enabled and the new taglib is rendered. Any idea why @adolfopa? 
Screenshot 2022-12-01 at 22 30 02


Anyway, I am confident with the changes and everything should work, so do not consider this comment as a stopper for this pull.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
@ambrinchaudhary It is expected for the button to be hidden. I should have pointed that out in the description.

**Pull request closed without merging**
