### PR TITLE
LPS-189427 add host to prevent NPE

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
go to : (your path)`modules/apps/document-library/document-library-test`

run 
`gw tI --tests "*WebServerFriendlyURLTest*"`
(or similar)

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1267401_10433

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
The failures are unrelated. Forward this directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
