### PR TITLE
[7.4-only] LPS-121947 Migrate v2 usages of Clay cards in depot-web

### PR DESCRIPTION
**Pull request by markocikos**
Fixes: https://issues.liferay.com/browse/LPS-121947
Fixes: https://issues.liferay.com/browse/LPS-121960

In this PR we are replacing horizontal and vertical cards with the newly minted navigation card. This includes:
- removing styles that were specific to the old horizontal card
- updating `deploy-web` model objects and display context to match the new card

This PR is a followup on https://github.com/liferay-lima/liferay-portal/pull/1102, quoting from there:

> **Test plan**:
> 
> * Fetch this branch
> * Deploy the `depot-web` and `frontend-taglib-clay` modules
> * From the global menu, in the **Applications** tab, select **Content** > **Asset Libraries**
> * Click on the **+** button in the top right corner of the page to
>   create a new asset library
> * Enter a name for this asset library
> * Scroll down to the end of the page and click on the **Save** button
> * Assert that the asset library has been created and that a card is
>   visible and working as expected.

@julien @carloslancha

Before PR:
before

After PR:
after

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]

**Review by julien — APPROVED** [review]

**Comment by markocikos** [comment]
@john-co @PablitoBonito CI is failing because we are changing the component and the new component has different HTML markup. More specifically:
```
//div[contains(@class,'card')][contains(.,'Settings')]
```
is no longer true because the new element is
```
<a class='card'>...</a>
```
We need to update CI tests. I am not sure what is the latest process to do this, if I should do it, please point me to the spot where that code is.

**Comment by Hanlf** [comment]
ci:test:bundle

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
close it, resend it with Poshi fix: https://github.com/liferay-lima/liferay-portal/pull/1123

**Pull request closed without merging**
