### PR TITLE
LPS-135615 translations experience selector

### PR DESCRIPTION
**Pull request by boton**
https://issues.liferay.com/browse/LPS-135615

~~The test will fail because of 5a1f65f5e359a690ba58e626e17e6714b76b6a5a mock data and we need to pass down and validate when the real data is ready.~~

---

Feature Flag

```
(cd ${LF_PORTAL_PATH} && echo "enabled=B\"true\"" > ../bundles/osgi/configs/com.liferay.layout.admin.web.internal.configuration.FFLayoutTranslationConfiguration.config)'
```

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @boton 
On https://github.com/liferay-lima/liferay-portal/pull/2069/commits/0636bd216d234f58bb77b34a898af7c30e7dc480 I changed from experienceId to segmentExperienceId as we talked and we have to change it on the call of the request.

on https://github.com/liferay-lima/liferay-portal/pull/2069/commits/ec71061f25101bf09d19935fd5dac6f2ec830e9e I found (well the intelliJ :D) a misspelled word.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by boton** [comment]
Thanks, @AliciaGarciaGarcia for fix the wordsmith.

The experience selector it's almost done, the only thing I'm missing is to prevent passing the `experiencesSelectorData` when we don't have experiences like in Web Content

image

**Comment by boton** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by boton** [comment]
Tested and working with @AliciaGarciaGarcia.  

We wait until the release is out to forwarding this PR.

**Comment by boton** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
