### PR TITLE
LPS-193610 KB Move: Title must be in quotes

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Before: 
Screenshot 2023-08-16 at 10 51 27

After: 

Screenshot 2023-08-16 at 12 55 13

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
