### PR TITLE
LPS-132576 Set total properly

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @liferay-lima ,
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
@markgulacsy

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
