### PR TITLE
LPS-186856 The Office 365 window can not pop up when adding a file in DM admin for first time

### PR DESCRIPTION
**Pull request by marcogalluzzi**
The problem was affecting both the creation and the edition of an Office file. A new tab should always open when:

* Creating an Office file
* Selecting "Edit in Office365" option

However sometimes it doesn't. This happens when the OAuth2Manager.getAccessToken() returns null, this is when accessing Office365 for the first time or when the token has been invalidated (or something similar).

The problem was that we were passing request attributes and trying to read them in the JSP file "dynamic_include/view_post.jsp", having a redirection in between. This is not possible because the redirect action creates a new request, and previously set attributes are lost. So, solution is to set a *session* attribute and read it after the redirection, during the rendering phase. Once read, the session attribute is removed and used as request attribute to be available to the JSP file.

See issue: https://liferay.atlassian.net/browse/LPS-186856

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
