### PR TITLE
LPS-163978 Make all actions point to the control panel

### PR DESCRIPTION
**Pull request by Jeremy-Ch**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_5278

**Comment by ambrinchaudhary** [comment]
closing in favor of https://github.com/liferay-lima/liferay-portal/pull/3547

**Pull request closed without merging**
