### PR TITLE
item selector tabs

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
-----
Tab component is not scaling well when dealing with many types of elements inside item selector. As you can see:

Home_-_Liferay__Editing_

Proposed Solution
-----
Adapt the markup to change from tabs to vertical navigation when we have more than 5 navigation items. So, after the changes we are moving from this:

Home_-_Liferay__Editing_

To this:

Home_-_Liferay__Editing_

Steps to verify
-----
1. Go to a content page
2. Try to map an item

Please let me know what do you think.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
just put "on hold" to review the solution with UX.

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
