### PR TITLE
LRQA-64237, LRQA-64269 | master only

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-64269
https://issues.liferay.com/browse/LRQA-64237

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
see https://github.com/liferay-lima/liferay-portal/pull/1346

**Pull request closed without merging**
