### PR TITLE
LPS-161697 Refactor jsp and move logic to display context

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
Tested and nothing is broken ;-). LGTM!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
