### PR TITLE
LPS-141949 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-141949

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:stop

**Pull request closed without merging**
