### PR TITLE
LPS-123900 Wrap in form in some cases triggering add on submit not only on click

### PR DESCRIPTION
**Pull request by boton**
Hey @ambrinchaudhary and @4lejandrito 
I don't have the styles done yet but what do you think about the logic and abstraction?
If you view any potential pitfalls let me know.

Tomorrow I going to work in the styles 😄

### CODE REVIEW

**Comment by boton** [comment]
I broke the external video din DM working on that

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
I think it is ready to go.

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
I am reviewing this

**Comment by 4lejandrito** [comment]
@boton what do you think about the changes in https://github.com/liferay-lima/liferay-portal/pull/1143?

**Comment by 4lejandrito** [comment]
As discussed with @boton we will forward https://github.com/liferay-lima/liferay-portal/pull/1143.

**Pull request closed without merging**
