### PR TITLE
LPS 106905

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi @adolfopa,

I discussed this issue with Jorge and he said Global should appear, it was one of the goals of having global. Maybe we should always grant view permissions to the Global group at the GroupPermission level but I have decided to only modify the logic inside the item selector group provider to avoid unintended side effects.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:stable

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
