### PR TITLE
LPS-134513 Use translations wf status, not the wf of the model under translation

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:translation

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
the test seems failing because the changes, relaunching

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translation

**Comment by Hanlf** [comment]
Hi @adolfopa and @AliciaGarciaGarcia 
Yes, the translation tests failed because the button name was changed(`Publish to `Submit For Publication`), let me know if you want me to send a fix under this PR, or we can fix the test's failure after it merges.

**Comment by Hanlf** [comment]
ci:test:bundle

**Comment by Hanlf** [comment]
Hi @adolfopa , I found an issue when resubmitting a translation, reproduce steps:
1. Enable workflow for Translations
2. Add a Web Content
3. Export the translation and import it after translated
4. Reject the translation
5. Try to import a new translation, assert the button name is `Save as Draft`, should show as 'Save'
Translations:
reproduced
Blogs:
blogs

**Comment by Hanlf** [comment]
Resend it here: https://github.com/liferay-lima/liferay-portal/pull/2497

**Pull request closed without merging**
