### PR TITLE
LPS-116622 Prevent "WARN Discrepancy between expected target -- and target in document --, Using --" with the reading of the file attribute on XLIFF v2.0

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
https://github.com/liferay-lima/liferay-portal/pull/450#issue-449493423

> Hey @brianchandotcom, @hhuijser
> 
> We found an issue with AutoSF that AFAIK can only be fixed with an SF exclusion. The XLIFF library we're using has a class named `StartSubDocument`; this causes two SF rules to conflict with each other anywhere this is used in a variable/method name:
> 
> 1. The name of the variable should match its type name; e.g. `StartSubDocument startSubDocument = ...;`
> 2. When adding the "sub" prefix to a word, it has to be camel cased as a whole word (e.g. Document -> Subdocument).
> 
> So, if we try to satisfy rule 1, SF will complain about rule 2 and viceversa. As a workaround, we've added a file exclusion, but we wonder if there's anything we can do to solve this kind of issue.
> 
> Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by hhuijser** [comment]
@AliciaGarciaGarcia is a good workaround for now
I'll get a fix in for that one

**Comment by hhuijser** [comment]
See https://github.com/hhuijser/liferay-portal/pull/4520

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/464

**Pull request closed without merging**
