### PR TITLE
LPS-129063 | master

### PR DESCRIPTION
**Pull request by davidtellolr**
Hi @liferay-lima ,

As it was decided in the PTR-2291, I send this PR with the necessary changes to revert the LPS-119122. I recover the previous code to restore the previous behavior. If you have any doubts, please let me know.

Important note: The client told us that they plan a deployment in the production environment this weekend, and the problem with the folder permissions is the unique stopper currently. I'm working on a hotfix for them, and when you validate the solution, I'll send it as SDH.

Thanks.

### CODE REVIEW

**Comment by davidtellolr** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@davidtellolr Everything looks fine :+1:

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
@davidtellolr Can you rebase and resend? Thanks!

**Comment by davidtellolr** [comment]
@adolfopa , Sure, I'll do it. Thanks.

**Pull request closed without merging**
