### PR TITLE
LPS-173659 | master

### PR DESCRIPTION
**Pull request by chaowang-123**
https://issues.liferay.com/browse/LPS-173659

cc @austinchiang

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by chaowang-123** [comment]
ci:close

**Comment by chaowang-123** [comment]
ci:reopen

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
