### PR TITLE
LPS-115564 Adding logging for AMServlet

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

If an exception is thrown from `S3Store` it is silently swallowed in `AMServlet`. I added a logging object for that class to print the exception to the console.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
Dear @liferay-lima 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/327

**Pull request closed without merging**
