### PR TITLE
LPS-196436 prevent the value 0 on the repository id

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-196436

How to test it:

add an Asset Library
Go D&M
Create document or upload it
create a Folder
Move Document to Folder

- LPS-196436 make a failsafe value in the case that the referer group is 0
- LPS-196436 use the method ot obtain the repositoryId instead of call directly

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
LGTM 👍

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
Test failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
