### PR TITLE
LPS-154735 register missing hook after comment loaded to the screen

### PR DESCRIPTION
**Pull request by kristofloneck**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@boton @ambrinchaudhary Can one of you take a look at this?

**Review by boton — COMMENTED** [review]
Sadly with this solution, we are only enabling the first loaded comment we have the same problem in the next ones.

@kristofloneck does it work for you in all the comments loaded or like me only in the first one loaded?

I will take a look as soon as I can.

**Comment by boton** [comment]
Looks like we are generating this js code in the response https://github.com/liferay-lima/liferay-portal/pull/3145/files#diff-4b78a43edff7de41fa6a225ed89cf3f53a1988513757c5231742475523d33778R95 but something is failing :(

**Comment by kristofloneck** [comment]
I try to check here as well asap

**Comment by kristofloneck** [comment]
Yep it doesn't work for me either. I close this PR and make a new one when I got a new solution

**Pull request closed without merging**
