### PR TITLE
[TS] LPS-124520

### PR DESCRIPTION
**Pull request by jonathanmccann**
From @brianikim:

>The reason the issue occurs is because we are not able to fetch an assetEntry due to utilizing the classNameId of FileEntry when we should be using the classNameId of DLFileEntry.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @liferay-lima ,

Any updates on this PR?

Sincerely,
Brian

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
