### PR TITLE
LPS-135864 translation move export from modal to jsp

### PR DESCRIPTION
**Pull request by adolfopa**
:information_source: @brianchandotcom This includes changes in the UI (we moved from a modal to a JSP), but no changes to the underlying translations import logic, and the experience selection stuff is behind a feature flag. So, this is safe to merge into master.

In this PR the export translation modal is moved into a new JSP and the `experience selector` is added behind a feature flag.

If the FF `com.liferay.translation.web.internal.configuration.FFLayoutExperienceSelectorConfiguration` is enabled and the content page have more than the default experience `experience selector` is rendered.

image

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by boton — COMMENTED** [review]
LGTM.

The only little thing that I miss is losing the information of [this commit](https://github.com/boton/liferay-portal/commit/cce321a0b95c8f304d172243554da71503ef9410).

Can we add more detail to https://github.com/adolfopa/liferay-portal/commit/19c3d4ace5029b5f639b0e1cba7173aca4328961 something like:

```
LPS-135864 Implement export UI and supporting classes

The nested components of old ExportTranslationModal.js are moved outside because are recreating in each render and the focus disappears.

Deeper explanation in this post: https://randyperez.tech/blog/nested-functional-components

```

**Comment by boton** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
> LGTM.
> 
> The only little thing that I miss is losing the information of [this commit](https://github.com/boton/liferay-portal/commit/cce321a0b95c8f304d172243554da71503ef9410).
> 
> Can we add more detail to [adolfopa@19c3d4a](https://github.com/adolfopa/liferay-portal/commit/19c3d4ace5029b5f639b0e1cba7173aca4328961) something like:
> 
> ```
> LPS-135864 Implement export UI and supporting classes
> 
> The nested components of old ExportTranslationModal.js are moved outside because are recreating in each render and the focus disappears.
> 
> Deeper explanation in this post: https://randyperez.tech/blog/nested-functional-components
> ```

Oh, I missed that. I'll add that to the commit message and push-force.

**Comment by boton** [comment]
Rebased and updated the message.

**Comment by boton** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
