### PR TITLE
LPS-146890 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
Issue: https://issues.liferay.com/browse/LPS-146890

On top of https://github.com/liferay-lima/liferay-portal/pull/2708

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:translation

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failed test: [LocalFile.AutoTranslation#CanTranslateWCToJapaneseWithGoogle](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/34359//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AutoTranslation_CanTranslateWCToJapaneseWithGoogle_) will be fixed in https://github.com/brianchandotcom/liferay-portal/pull/113465. The other failures are not related to this pr. Wait for the fixes merge and run ci again.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:translation

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:translation

**Comment by Jeremy-Ch** [comment]
ci:test:translation

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:translation

**Comment by Jeremy-Ch** [comment]
For now, the failed tests [TranslationsExportImport#CanImportMultipleWCs](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=24/449320//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_TranslationsExportImport_CanImportMultipleWCs_) and [TranslationsExportImport#CanPartiallyImportMultipleWCs](https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=24/449320//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_TranslationsExportImport_CanPartiallyImportMultipleWCs_) should be caused the LRQA-73071 and the rest of the translations tests are passed.

/cc @boton @Hanlf

**Comment by boton** [comment]
@Jeremy-Ch @Hanlf Is the PR good enough to be forwarded to Frontend Infra to review or is it better to wait to fix the tests that are failing?

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
See #2758.

**Pull request closed without merging**
