### PR TITLE
LPS-118398 Included missing taglibs

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @adolfopa, 

this is how the preview looks after my changes: 
Translation workflow preview

Is it possible to remove the language selector that appears on the top left corner? I doon't get what it is used for. 
Let me know if we need to change something else. 
Thanks.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
Everything looks fine. I'll send a PR to the WF team with the changes to hide the language selector from the preview.

Thanks!

**Comment by adolfopa** [comment]
See https://github.com/inacionery/liferay-portal/pull/998 for the language selector changes.

**Pull request closed without merging**
