### PR TITLE
[TS] LPS-130719 - comments and message boards should not share e-mail settings

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-lima team!

This is a fix for an issue that was declared a bug in [PTR-2371](https://issues.liferay.com/browse/PTR-2371). Currently, due to both sharing the same GroupServiceSettings settingsId of MBConstants.SERVICE_NAME, comments and message boards share the same email from name and address. By setting Comments to its own service name, the comments settings should no longer override message boards settings and visa versa.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
Failure unrelated to the pull, it was due to CI issue.

Retriggering test.

**Comment by yichenroy** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@robertoDiaz Can you review this PR? You were involved in the PTR.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
@wanderlast 

Could you check the broken test and if they are related with the PR??

Some of them are MB tests.

**Comment by Hanlf** [comment]
Hi @robertoDiaz 
The Poshi tests failures under previous relevant job are not related to this pull, it should be some CI error, and the relevant tests passed on the latest relevant job.

cc/ @wanderlast

**Comment by adolfopa** [comment]
@robertoDiaz In you opinion, is this ready to forward?

**Comment by wanderlast** [comment]
Hi @liferay-lima, @robertoDiaz:

Is there anything else I need to do for this fix to push it forward? The client is wondering if we have an ETA for delivery. Thanks!

**Comment by robertoDiaz** [comment]
Hi guys, sorry for the delay.

We have a peak of tickets in Spain and I didn't had time to check this before.

@adolfopa , Yes, it looks fine to me. Can you push it to master?

Thanks!

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
