### PR TITLE
LPS-148409 Video HTML <source> tag is being removed from Blogs

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Review by boton — APPROVED** [review]
LGTM, we need `<source>` tag if we are allowing `video` tag

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
should not be related to this pr, re-ran it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
