### PR TITLE
LPS-162970 KB Edit Article updated pane

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
Story: https://issues.liferay.com/browse/LPS-154208.

New look and feel:
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
Hi @ambrinchaudhary I have updated the Poshi tests, and most of the tests will be passed. But I'm pretty sure that we still have some tests to be failed. Maybe you have known the issues, I post them here for your information.

- The error message can not be displayed when publishing the article without a title.
- When I try to resize the browser, the edit page doesn't change. Some contents will go outside the browser.
 

https://user-images.githubusercontent.com/48118285/191930218-4dc3c664-26a0-4f96-bc01-46b5f7ae993e.mp4

- When I try to edit an article in the KB display widget, the side panel is pinned to the screen. It will block something.
 

https://user-images.githubusercontent.com/48118285/191931014-df93ce84-1d30-429c-8ae8-bd28108c6f32.mp4

 - For the title placeholder text, maybe we can use "Untitled Basic Article"
 - For the below issue, I'm not sure if it is an issue. I post here a comparison with web content.
Web content:

https://user-images.githubusercontent.com/48118285/191933702-9c297cf9-e4dd-4e3f-9ecd-53e014c63203.mp4

KB Article:


https://user-images.githubusercontent.com/48118285/191933735-00023d6d-b428-45c3-868e-9dd8c236f887.mp4

/cc @austinchiang

**Comment by Jeremy-Ch** [comment]
I will continue to fix the KB tests after @ambrinchaudhary resolve the rest of the issues.

**Comment by adolfopa** [comment]
@ambrinchaudhary To solve the issue where the panel is displayed in a widget page, we'll need to change the "edit" urls so that they point to the control panel. That's the way it works in other portlets (e.g. blogs).

**Pull request closed without merging**
