### PR TITLE
LPS-143973 add to the availableLocalesIds always the default language id of the layout

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
previously where adding the default language , but now the id of the default language is "defaultValue" and no language id Found. So We should add it (if not present) always.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Hi @AliciaGarciaGarcia , 
Could you take a look at the failure about [com.liferay.layout.admin.web.internal.info.item.provider.test.LayoutInfoItemLanguagesProviderTest](https://testray.liferay.com/reports/production/logs/2021-12/test-1-36/test-portal-acceptance-pullrequest(master)/121/modules-integration-mysql57-jdk8/0/0/jenkins-console.txt.gz), it seems only occur on this PR:
```
     [exec] com.liferay.layout.admin.web.internal.info.item.provider.test.LayoutInfoItemLanguagesProviderTest > testGetAvailableLanguagesContentLayout STARTED
     [exec] 
     [exec] com.liferay.layout.admin.web.internal.info.item.provider.test.LayoutInfoItemLanguagesProviderTest > testGetAvailableLanguagesContentLayout FAILED
     [exec]     array lengths differed, expected.length=1 actual.length=0; arrays first differed at element [0]; expected:<en_US> but was:<end of array>
     [exec]     	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:89)
     [exec]     	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)
     [exec]     	at org.junit.Assert.internalArrayEquals(Assert.java:534)
     [exec]     	at org.junit.Assert.assertArrayEquals(Assert.java:285)
     [exec]     	at org.junit.Assert.assertArrayEquals(Assert.java:300)
     [exec]     	at com.liferay.layout.admin.web.internal.info.item.provider.test.LayoutInfoItemLanguagesProviderTest.testGetAvailableLanguagesContentLayout(LayoutInfoItemLanguagesProviderTest.java:110)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec]     Caused by: java.lang.AssertionError: expected:<en_US> but was:<end of array>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:120)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:87)
     [exec]     	... 33 more
     [exec] 
```

**Comment by AliciaGarciaGarcia** [comment]
Thanks @Hanlf The failure on the test are caused by my changes.

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1297401_976

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
