### PR TITLE
LPS-199428 Some js are not been handled as expected by tika.

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
