### PR TITLE
Remove Line breaks

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
Tests need to be fixed

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/4574 since I can't force push the branch

**Pull request closed without merging**
