### PR TITLE
[TS] LPS-178109

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/liferay-lima/liferay-portal/pull/4092 with most changes made.  I wasn't sure how to implement the WikiPageModelResourcePermissionWrapper [suggestion here](https://github.com/liferay-lima/liferay-portal/pull/4092#discussion_r1135200613), so I added something (although it doesn't change this use-case).  Commits can be squashed as needed, I just left them for progressive understanding.

https://issues.liferay.com/browse/LPS-178109
https://issues.liferay.com/browse/PTR-3696

Fixes a few scenarios as described in PTR-3696. Please let me know if you have any questions, thanks!

CC @adolfopa

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@ChrisKian Can you fix the baseline errors?

**Review by adolfopa — CHANGES_REQUESTED** [review]
@ChrisKian Can you fix the baseline errors?

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1357401_3870

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@ChrisKian See https://github.com/liferay-lima/liferay-portal/pull/4121

**Pull request closed without merging**
