### PR TITLE
LPS-121591

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-121591

Resending from: https://github.com/liferay-lima/liferay-portal/pull/849

Both the add and update methods require the newly created helper method to get the correct extension.

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @liferay-lima ,

Let me know if you have any questions with the new PR.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @brianikim, @adolfopa,

I see that the change is only applied to the add method. What if we update the file replacing the .pdf with a .doc version?

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Hey @brianikim 

I understand the case where there's an unambiguous extension for the mime type (extensions.size() == 1), but I think the case for plain text is not ok. There are formats that will be recognized by tika as plain text that should keep the original extension (e.g. some lightweight markup formats).

So, I will be ok if we would have the following logic:
1. extensions.size == 1 -> return the "canonical" extension for that mime type (extensions.get(0))
2 otherwise, return the original extension.

No other special cases.

Also, can you rename the method to "_getExtension"?

Thanks!

**Pull request closed without merging**
