### PR TITLE
LPS-113298 Add to ckeditor classic impl needed features in blogs

### PR DESCRIPTION
**Pull request by carloslancha**
To test this you need to change your editor to `ckeditor_classic` in your `portal-ext.properties`

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:test:blogs

**Comment by carloslancha** [comment]
@ambrinchaudhary pushed new commits.

- onChangeMethod implemented
- saving fixed (saving was working actually but current content was not being passed to the component)
- About the missing toolbar buttons, they don't appear on the original ckeditor implementation. If they're missing please open a ticket about that so we can prioritize it.
- The same about `editorOptions`, please open a ticket.

If you (the team) have time for it, I thing that could be good to review the current CKEditor implementation to see if there's anything else missing an report it as bug so we can take care of it. Thx!

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
Sent to https://github.com/liferay-lima/liferay-portal/pull/69

**Pull request closed without merging**
