### PR TITLE
LPS-135620 Drag & drop for files in documents and media does not work with this enabled

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
on this case, the value of the date was incorrect (0/0/0) and throws an exception that is not catch and fails the creation of the file.
so never expire and never review must be true by default for the case of the upload that the fields are not loaded

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
