### PR TITLE
LPS-199510 Escape the title

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by boton — APPROVED** [review]
LGTM

Thanks @robertoDiaz applying d901dd4d459c1d08bd614cdb709ff368a946f7ae ❤️  this fixed the [LPS-199369 ](https://liferay.atlassian.net/browse/LPS-199369)

**Comment by boton** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
yes, see https://liferay.atlassian.net/browse/LPS-199510?focusedCommentId=2491002

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:stop

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
