### PR TITLE
LPS-159105 KB Folder Navigation: integration in the Vertical Bar

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
TODO:

- [x] Home folder 
- [x] URL for each item, and navigate to them
- [x] Get navigation items in correct order (now is on reverse order)
- [x] Only get navigation data when is needed
- [x] Validate [NavigationPanel.js](https://github.com/liferay-lima/liferay-portal/pull/3312/files#diff-a48ada17d4dfef0be763ea72daaf46b094fcb33d68d3d6cce68d0a73078ea821) Props
- [ ] Get child articles

Screenshot 2022-07-29 at 09 31 45

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by boton** [comment]
Tomorrow I will make a clean, split commit and drop some of yours.

**Comment by boton** [comment]
Cleaned and rebased!

**Comment by ambrinchaudhary** [comment]
> Cleaned and rebased!

Do you mean it is ready to send it? Do we want to work on these before? 

- [ ] Home folder
- [ ] Get navigation items in correct order (now is on reverse order)

**Comment by boton** [comment]
Updated

DONE
- [x] Home folder 
- [x] Get navigation items in correct order (now is on reverse order)
- [x] Only get navigation data when is needed
- [x] Validate [NavigationPanel.js](https://github.com/liferay-lima/liferay-portal/pull/3312/files#diff-a48ada17d4dfef0be763ea72daaf46b094fcb33d68d3d6cce68d0a73078ea821) PropTypes

I'm only missing 
- [ ] Get child articles

**Comment by ambrinchaudhary** [comment]
Just wondering... with the last commit https://github.com/liferay-lima/liferay-portal/pull/3312/commits/a934f66f9b255b35cbf8634be696edae5681d5fb does it work for templates and suggestions? I planned the same but [here](https://github.com/liferay-lima/liferay-portal/pull/3312/commits/3f74acbea7ecbffb991fe28810ca0c5d623d3acd) I'm setting the same navigation for the three elements. Maybe we can just leave those with blank panel like before...

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Created a separate story for getting the child articles https://issues.liferay.com/browse/LPS-159602

**Comment by boton** [comment]
> Just wondering... with the last commit [a934f66](https://github.com/liferay-lima/liferay-portal/commit/a934f66f9b255b35cbf8634be696edae5681d5fb) does it work for templates and suggestions? I planned the same but [here](https://github.com/liferay-lima/liferay-portal/pull/3312/commits/3f74acbea7ecbffb991fe28810ca0c5d623d3acd) I'm setting the same navigation for the three elements. Maybe we can just leave those with blank panel like before...

I think it is working with a blank panel because doesn't have items data

**Pull request closed without merging**
