### PR TITLE
LPS-154136 Update twelvemonkeys version

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — COMMENTED** [review]
Only 1 question @adolfopa 

Why 3.8.1 while 3.8.2 is the latest?

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia You're right. I looked at the README and there they use 3.8.1, so I assumed that was the latest version.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
update the readme is like... update the documentation...

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
