### PR TITLE
LPS-138161 Add missing lang key

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failures are not related to this PR, contacted Echo QA about the failures.
FragmentsEditor#ViewDraftAutoSaved: [LPS-138232](https://issues.liferay.com/browse/LPS-138232)
DisplayPageTemplatesForWebContentArticle tests failure: [LPS-138186](https://issues.liferay.com/browse/LPS-138186)
MenuDisplay tests failure: [LPS-138234](https://issues.liferay.com/browse/LPS-138234)

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/106357

**Pull request closed without merging**
