### PR TITLE
LPD-15755 Remove triple period from filters in DM

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPD-15755

### Before: 

Screenshot 2024-01-29 at 13 40 47

### After: 

Screenshot 2024-01-29 at 13 46 42

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
Errors do not seem to be related. Running `stable` tests again.

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
Closing... I'm going to open a new pull request

**Pull request closed without merging**
