### PR TITLE
LPS-160824 DM folders - dropdown items

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
@AliciaGarciaGarcia not sure if for sharepoints folders would work the delete option confirmation. Do you think we can find a solution here, or better work in that in bug https://issues.liferay.com/browse/LPS-160876? --> FIXED IN THIS PULL

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hey @ambrinchaudhary @Jeremy-Ch @adolfopa @AliciaGarciaGarcia 
I have tried to reproduce [this](https://github.com/liferay-lima/liferay-portal/pull/3388#issuecomment-1222322756) as well in a document as in a folder but I can't. I can change the assigned permissions to a document and to a folder successfully.
My local is on the hash d0dee6b4
Regards

**Comment by ambrinchaudhary** [comment]
Unable to see what failed in ci:test:relevant suite... trying again :-(

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1387401_3220

**Comment by Jeremy-Ch** [comment]
ci:reevaluate:1387401_3220

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@ambrinchaudhary 

I couldn't reproduce the issue with the permissions.

And I see that the sharepoint folder working ok


https://user-images.githubusercontent.com/47524751/186846683-4322f254-2c02-4f08-88a9-f80b4db58054.mp4

So

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Manually forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/122318

**Comment by ambrinchaudhary** [comment]
ci:stop

**Pull request closed without merging**
