### PR TITLE
LPS-168755 | Master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://issues.liferay.com/browse/LPS-168755

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by austinchiang — APPROVED** [review]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
@WYZ-Issac please add to test map

**Pull request closed without merging**
