### PR TITLE
LPS-144436 When selecting Home folder the selected folder name is empty

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-144436 if folder id is 0 folder name is "home"
- LPS-144436 the remove button now remove repository value too

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
