### PR TITLE
LPS-130443

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by adolfopa** [comment]
@marianoalvarosaiz This sounds a bit too weird for end users. Is it ok if we say "Introduce the configuration ID to override the default adaptive media behavior for document library custom thumbnail 2. This will be referred to internally as imageThumbnail 3."

**Comment by marianoalvarosaiz** [comment]
Ok @adolfopa, sounds good to me.

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1754

**Pull request closed without merging**
