### PR TITLE
LPS-170198 Remove wiki display context interfaces

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/issues/browse/LPS-170198

The Wiki display context interfaces were not used, and as an API, it was largely unmantained. Make all display contexts private to the web module and remove the interfaces and support classes.

# How do I test it?

This should not change how wiki works. As long as all tests pass, we're good.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @adolfopa 
There is an issue related to this PR: No wiki page entry is shown on the All pages on Wikis Widget, could you take a look, thanks!
Steps:
1. Add a page and place the Wiki widget on the page
2. Click All Pages 
3. Assert the Front page is displayed

**Note:** Other nav items also have the same issue, like Recent Changes Draft Pages...
reproduced

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:wiki

**Review by marcogalluzzi — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr, send to BChan directly, see https://github.com/brianchandotcom/liferay-portal/pull/127221

**Pull request closed without merging**
