### PR TITLE
LPS-166731 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-166731

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:lima-db-partition

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:lima-db-partition

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
