### PR TITLE
LPS-119185 Unread MB styles

### PR DESCRIPTION
**Pull request by boton**
We need a more obvious style for unread messages with accessibility in mind.

**Steps to reproduce:**

1. Add two message boards threads to an MB site widget
2. Add a new user, log in and view one of the posts
3. Navigate home
4. View difference in visual states of read/unread posts

**Before the fix:**
image

**After the fix:**
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
@austinchiang could someone please check the poshi errors? 
Thanks in advance!

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Looks like some markup has changed, so I'll need to fix the Poshi tests and resend.

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
Testing here: https://github.com/liferay-lima/liferay-portal/pull/648

**Pull request closed without merging**
