### PR TITLE
LPS-135868 Discussion adds wrong username when adding a comment while impersonating someone

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

When an URL parameter contains plus signs, the signs are automatically getting replaced with spaces when the request is submitted.
This can lead to problems when impersonating a user, as this replacement can alter the `doAsUserId` parameter if it contains plus signs.

A particular case is when an impersonated user wants to submit a comment. For example, if `doAsUserId` is `jtP9LViCzpjvR+ip/Dr1Ng==` this may lead to an EncryptorException.

```
2021-07-21 07:27:53.709 WARN  [http-nio-8080-exec-2][PortalImpl:7661] Unable to impersonate jtP9LViCzpjvR ip/Dr1Ng== because the string cannot be decrypted
com.liferay.petra.encryptor.EncryptorException: com.liferay.petra.encryptor.EncryptorException: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.

```

Please note that `jtP9LViCzpjvR+ip/Dr1Ng==` has been replaced to `jtP9LViCzpjvR ip/Dr1Ng==` (plus sign to space).

I'm employing a solution that is encoding the plus signs. I'm found the solution here:
https://stackoverflow.com/questions/7842547/request-parameter-losing-plus-sign

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Review by adolfopa — CHANGES_REQUESTED** [review]
Instead of a custom method, can you use `URLCodec.encode`?

**Comment by IstvanD** [comment]
Hi @adolfopa thank you for the suggestion. I tested it, and it works as well. I pushed the changes in this pr.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
