### PR TITLE
LPS-206555 create FF for LPS-197908  Epic

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
I just realized that if not used, the FF is deleted by the SF so I will wait to do this to an use.

**Review by marcogalluzzi — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
@AliciaGarciaGarcia numbers have changed. Maybe it would be better to close this pull and create a new one with the correct LPD number?

**Comment by AliciaGarciaGarcia** [comment]
see https://github.com/liferay-lima/liferay-portal/pull/5084

**Pull request closed without merging**
