### PR TITLE
LPS-166432 Show article in display page if available

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

When there is a display page for kb articles, use that page to display elements if possible.

# How do I test this?

- Create a display page template for kb articles. Mark it as default.
- Create a knowledge base article.
- Drop an Asset Publisher portlet in a page, configure it to display kb articles.
- Assert that the asset publisher portlet redirects the user to the display page when trying to view the kb article.

The old behavior will be kept as a fallback. See FindKBArticleStrutsAction.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Pull request closed without merging**
