### PR TITLE
LPS-155142 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-149586
https://issues.liferay.com/browse/LPS-156478
https://issues.liferay.com/browse/LPS-155142

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
