### PR TITLE
LPS-144021 Add config. to disable 404 tracking

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
@Hanlf I had to resend due to a rebase error in the last commit. Can you double check that https://github.com/liferay-lima/liferay-portal/pull/2596/commits/0f2adb17f8192093d8ccf34d9503118db9baabc5 is correct?

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
