### PR TITLE
LPS-144152 Provide specific message for Layout

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Hi @adolfopa, 
This PR causes a POSHI failure, I've summarized the steps as follows, could you take a look?

1. Add a content page with a heading fragment
2. Export content page translation with Spanish
3. Unzip the exported folder, translate the .xlf file
4. Import the translated .xlf file
5. Click on **Publish**

The message **1 file saved** is displayed. In the previous, it shows **1 file published** after clicking on publish.

Thanks.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
