### PR TITLE
LPS-200623 Failed upgrade process for module com.liferay.document.library.service

### PR DESCRIPTION
**Pull request by marcogalluzzi**
https://liferay.atlassian.net/browse/LPS-200623

The upgrade process was failing because of a missing service dependence. It was incorrectly removed in https://github.com/liferay-lima/liferay-portal/pull/4816/commits/304dd0dfa991969ba23bb509c04cb6559346e794

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:test:upgrade

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
Waiting to upgrade test finish to forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
