### PR TITLE
LPS-154333 Add loading state to wiki tree html

### PR DESCRIPTION
**Pull request by boton**
Follow up #3082.

I prefer to change the opacity to minimize the jump until is ready and apply some kind of loading state.

What do you think about it @fortunatomaldonado?

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @boton,
Yeah the added animation looks good. Thank you for the help!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
