### PR TITLE
LPS-127237  Upload to DM (Drag&Drop) in list view results in unusable UI, requiring reload

### PR DESCRIPTION
**Pull request by boton**
We have different bugs here:

**Bug link**: the link of the newly updated document doesn't work and points into a JSON and breaks the UI.
**Bug container**: If the folder isn't empty the uploader creates a new container with outdated markup.
**Bug style**: The UI looks ugly and break.

**Steps to reproduce:**

1. Go to Content & data > Documents and Media
2. Change to list view
3. Drag & Drop a document into the folder
4. View the upload and result document (**bug style**)
5. click the newly uploaded files' name (**bug link**)

If you try to update a document in a not empty folder the upload doesn't detect the current container and create a new one with outdated markup (**bug container**).

Visuals documented on https://youtu.be/xzX29Mda678

the bug link is fixed in 2f6e4831eba5537a11a0c89cdf557428bafaa48d,  the bug container is fixed dfa9e95970b1799321c547b28f154bac08df7950 the rest of commits are for styling.

**Before the fix**

image
image

**After the fix**

image
image

### CODE REVIEW

**Review by carloslancha — APPROVED** [review]
P'alante! Let's move on!

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
