### PR TITLE
LPS-167585 - Headings need to only increment by one.

### PR DESCRIPTION
**Pull request by ethib137**
https://issues.liferay.com/browse/LPS-167585

Hey Lima, I think this component is now yours, but if not please let me know. It's just a simple fix.

This PR fixes the use of headings so that headings properly increment by only 1 level at a time without changing the way things look at all.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failure([functional-smoke-tomcat90-db2115-jdk8/0/0](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/625807//consoleText)) is not related to this PR.

**Comment by adolfopa** [comment]
@ethib137 If I'm not mistaken, everything related to "notification" (singular) is handled by the Objects team. We maintain the "user notifications" component.

**Comment by ethib137** [comment]
Hey @adolfopa , yeah I thought this did fall under the user notifications component since I had seen a [previous ticket](https://issues.liferay.com/browse/LPS-158695) with that component. Maybe not though. @drewbrokke Do you know what team owns this component now?

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@ethib137 Everything is green and the changes look fine to me, so I'm forwarding this.

**Comment by adolfopa** [comment]
ci:forward

**Comment by ethib137** [comment]
@adolfopa Thanks for the help on this even though it's not your component! 💪🏻

**Pull request closed without merging**
