### PR TITLE
LPS-203217 Escape attributes

### PR DESCRIPTION
**Pull request by robertoDiaz**
how to test it: See LPS-203217

seems that in some cases this attributes could be problematic

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
Please fix the sf issue first. Thanks a lot.

**Comment by austinchiang** [comment]
This is a known issue. See https://liferay.slack.com/archives/C1SJ64S9X/p1701690739822459

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
> This is a known issue. See https://liferay.slack.com/archives/C1SJ64S9X/p1701690739822459

oh yes. I have just joined the SF channel and see the issue.

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
Hi @robertoDiaz, after checking your commit. The SF error is not a known issue. It's about your commit message. There is an extra space at the beginning of your commit message. This is what causes this error. Please fix it and resend it. Thanks.

cc @austinchiang

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Thanks for the catch @WYZ-Issac

**Comment by WYZ-Issac** [comment]
Failures are unrelated

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
