### PR TITLE
LPS-119983 extract method to simplify

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Pull request closed without merging**
