### PR TITLE
LPS-191493 Cannot open document for editing in Office 365 from the details page of the document

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Using same Props Transformer in Details page menu option "Edit in Office 365" as in menu option of item in DM folder view.
The inclusion of the component `DocumentLibraryOpener` was needed in this page also.

See: https://liferay.atlassian.net/browse/LPS-191493

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
