### PR TITLE
LPS-145325 Remove FF item selector single uploader

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
Issue: https://issues.liferay.com/browse/LPS-145325

I have not been able to reduce the logic as much as I would have liked because the old uploader is still in use on [item-selector-upload-web](https://github.com/liferay/liferay-portal/blob/30d870a990b049b4b2bb90249b8e303868292c17/modules/apps/item-selector/item-selector-upload-web/src/main/resources/META-INF/resources/js/index.es.js#L16).

I prefer to [create a new task](https://issues.liferay.com/browse/LPS-160919) to apply the new ItemSelectorSingleFileUploaderEnabled on [item-selector-upload-web](https://github.com/liferay/liferay-portal/tree/30d870a990b049b4b2bb90249b8e303868292c17/modules/apps/item-selector/item-selector-upload-web) I already have the logic clean on https://github.com/boton/liferay-portal/pull/231, I will apply it after update the item-selector-upload-web.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
See the new pr: https://github.com/liferay-lima/liferay-portal/pull/3411

**Pull request closed without merging**
