### PR TITLE
LPS-182480 Order is important, revert sort

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-182480

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-182480.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
