### PR TITLE
LPS-137112 Fix issues with findByExtraSettings and countByExtraSettings in Oracle DB

### PR DESCRIPTION
**Pull request by adolfopa**
The extraSettings column in DLFileEntry and DLFileVersion is a CLOB-type column. Unfortunately, Oracle DB has some weird restrictions surrounding CLOB-type columns:
1. The WHERE clause included a "[clob_column] != ''" operation, which isn't allowed in Oracle.
2. We were SELECTING a DISTINCT set of columns, which isn't allowed when one or more of the columns being DISTINCTED is a CLOB type in Oracle.

I applied the following fixes for problems 1 and 2:
Problem 1: If an Oracle database is in use, change the WHERE clause to use "LENGTH([clob_column]) > 0".
Problem 2: If an Oracle database is in use, separate the query into multiple queries. In the first query, we select the DISTINCT fileEntryIds from the database. Then, we do a separate query(ies) to select all the column values for each fileEntryId. (I know this isn't ideal performance-wise to split it into multiple queries, but I couldn't find any way to do it in a single query.)

https://issues.liferay.com/browse/LPS-137112

### CODE REVIEW

**Comment by adolfopa** [comment]
@mbowerman Can you review my SF changes?

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
@adolfopa Looks good to me! Thanks!

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
