### PR TITLE
LPS-175915 Auto SF

### PR DESCRIPTION
**Pull request by adolfopa**
https://issues.liferay.com/browse/LPS-175915

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
Fixed in upstream https://github.com/liferay/liferay-portal/commit/5dc511b7fbc51895c9fa95d963c58e86f0125345

**Pull request closed without merging**
