### PR TITLE
[7.4-only] LPS-121960 Migrate v2 usages of clay:vertical-card in depot/depot-web

### PR DESCRIPTION
**Pull request by julien**
**Original PR**: https://github.com/liferay-frontend/liferay-portal/pull/495

In this change, we replace `<clay:vertical-card-v2 />`(clay 2.x - Metal+soy) with
`<clay:vertical-card />` (clay 3x. React based)

**Test plan**:

- Fetch this branch
- Deploy the `depot-web` and `frontend-taglib-clay` modules
- From the global menu, in the **Applications** tab, select **Content** > **Asset Libraries**
- Click on the **+** button in the top right corner of the page to
create a new asset library
- Enter a name for this asset library
- Scroll down to the end of the page and click on the **Save** button
- Assert that the asset library has been created and that a card is
visible and working as expected.

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]

**Comment by julien** [comment]
@liferay-lima I'm not sure if the tests are failing because of a markup change or if it's an actual error, could you please help me figure it out - thanks.

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hey @julien, I see that the new cards add a bigger padding on the bottom of the card, is this intented/known and acceptable issue? Looks a bit weird to me... 

**Before:** 

AL Before

**After:** 

AL After

I'll have a look to the poshi failures...

**Comment by ambrinchaudhary** [comment]
Tests doesn't fail for me in local, trying again with CI...

**Comment by carloslancha** [comment]
First of all those are clear candidates to use `<clay:navigation-card>` instead `vertical-card` once https://issues.liferay.com/browse/LPS-123370 is completed, so we highly recommend the team to prioritize it and change it in the future.

About the padding that's because we're always rendering the `subtitle` container even if no subtitle is passed, so I guess that extra padding is because that empty `<p>`.

I'll ask Lexicon team if that's the expected behavior or not. Anyway, if it's not and we need to change it we'll do it in further prs since this will require changes in Clay and in the tags.

Thx for pointing it out @ambrinchaudhary !

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hey @austinchiang @Hanlf @Jeremy-Ch @liuxingye, could you please check the poshi failures? Cards have been replaced but there shouldn't be any visual changes...

**Comment by Hanlf** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
ci:test:bundle:norebase

**Comment by Hanlf** [comment]
Hi @ambrinchaudhary and @julien 

Without the commit: the user can click the card body to go into the item.
With the commit: the user can only go into the item by clicking the card title(link shows when mouse over),  clicking other areas of the card doesn't work. 
Our Poshi test is trying to click the card body, so it failed to go into Web Content.

Want to confirm: Is it expected behavior that can only go into the item by clicking the card title? Thanks!

**Comment by julien** [comment]
@Hanlf thanks for the details - yes this is something that was possible with clay 2.x tags but somehow isn't possible with the new one so we have to fix this.

**Comment by ambrinchaudhary** [comment]
Thank you very much @Hanlf for your input.

So, we have two big issues introduced with this pull:
1. Cards are not clicable, only the title

2. There is an extra padding at the bottom of the cards, due to the subtitle that is being rendered when it shouldn't. 

So we decided not to forward this until the issus are resolved in Clay. 

/cc @julien @carloslancha

**Comment by boton** [comment]
@julien @carloslancha I have to add a creative solution https://github.com/liferay/liferay-portal/commit/d07fccb1e328b7d8d2eaa0c79a1ae052f7b5110f with some help of @eduardoallegrini some context https://liferay.slack.com/archives/C25TXMD63/p1592547288010800 (in Spanish) to fix the clickable problem.

Maybe we can adapt it 🤔

**Comment by carloslancha** [comment]
@boton yeah, we just saw it. I'm talking with Clay guys about this because it makes no sense to have this fix in portal, it should be done in Clay since is a "NAVIGATION" card and you'd expect it to navigate on click. Thx!

**Comment by boton** [comment]
@carloslancha feel free to ping me if you need anything :D

**Comment by carloslancha** [comment]
ok, @ambrinchaudhary @boton this is fixed in `CardWithNavigation` which we're using in `<clay:navigation-card>` so in this case is not recommended to update this usage to `<clay:navigation-card>` but mandatory. We'll send this again migrating it to navigation when https://github.com/brianchandotcom/liferay-portal/pull/96257 is merged.

Thx again!

**Pull request closed without merging**
