### PR TITLE
LPS-167516 add missing params to show the navigation var from the link on the list view of the kb articles

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
…k on the list view of the kb articles
Before : 

https://user-images.githubusercontent.com/47524751/199755509-008710eb-0ade-4d28-bc7a-dccd48e4775a.mp4

After : 

https://user-images.githubusercontent.com/47524751/199755637-6300603c-3e48-41ae-99f1-77be74d1d654.mp4

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
