### PR TITLE
LPS-192862 Blogs do not upload larger files

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-192862 

Screenshot 2023-08-07 at 13 28 35

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by robertoDiaz — APPROVED** [review]
LGTM

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
