### PR TITLE
LPS-134496 Upgrade Lucene version

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia  I made significant changes to the last two commits. I need a re-review :pleading_face:

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1097401_4975

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
