### PR TITLE
LPS-119576 HTML wiki pages create absolute links

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @liferay-lima 

Could you please review this pull request?

Please see the explanation of the issue with reproductions steps in the LPS.

Thank you and best regards,
István

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Hi @adolfopa 

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
