### PR TITLE
LPS-179271 | master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-179271

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:lima-upgrade

**Comment by Hanlf** [comment]
ci:test:lima-upgrade

**Comment by Hanlf** [comment]
ci:test

**Comment by Hanlf** [comment]
ci:test

**Comment by Hanlf** [comment]
ci:test

**Comment by Hanlf** [comment]
ci:test

**Pull request closed without merging**
