### PR TITLE
LPS-156207, LPS-154443, LPS-157320 | master

### PR DESCRIPTION
**Pull request by liuxingye**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:reevaluate:1297401_3519

**Comment by Hanlf** [comment]
Hi @AliciaGarciaGarcia 
The below failures are related to this PR, could you take a look? Thanks!

- [com.liferay.document.library.change.tracking.test.DLFolderTableReferenceDefinitionTest](https://testray.liferay.com/reports/production/logs/2022-07/test-1-29/test-portal-acceptance-pullrequest(master)/3519/modules-integration-mysql57-jdk8/0/13/jenkins-console.txt.gz?authuser=0)
- [com.liferay.document.library.change.tracking.test.DLFolderTableReferenceDefinitionTest](https://testray.liferay.com/reports/production/logs/2022-07/test-1-29/test-portal-acceptance-pullrequest(master)/3519/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)
- [com.liferay.document.library.info.display.contributor.test.FileEntryInfoDisplayContributorTest](https://testray.liferay.com/reports/production/logs/2022-07/test-1-29/test-portal-acceptance-pullrequest(master)/3519/modules-integration-mysql57-jdk8/0/5/jenkins-console.txt.gz?authuser=0)
- [modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/reports/production/logs/2022-07/test-1-29/test-portal-acceptance-pullrequest(master)/3519/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by AliciaGarciaGarcia** [comment]
I do not know what changes we made to make fail 'DLFolderTableReferenceDefinitionTest > testDiscardCTEntry'....

**Pull request closed without merging**
