### PR TITLE
LPS-128074 Avoid buttons grow vertically

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
LGTM!

**Comment by marcoscv-work** [comment]
much better!

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
If @marcoscv-work is happy I'm happy :)

**Comment by carloslancha** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
