### PR TITLE
LPS-182018 The vote option cannot manually delete the rating when the ratingValue is decimal

### PR DESCRIPTION
**Pull request by marcogalluzzi**
If rating value has been set externally, i.e. from the API, and not from UI then the value can be valid (between 1 and 5) but not a specific value (0, 1, 2, 3, 4 or 5 stars). In those cases the deletion should be enabled.

For testing info see: https://liferay.atlassian.net/browse/LPS-182018

❗ I'm not sure if there is simpler way in JS/React to do the work but it looks OK to me.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1347401_4622

**Comment by marcogalluzzi** [comment]
I've checked the related failing tests and I know the solution but I cannot send the changes right now.

Line 52 of RatingsStars.js should be changed to:
```js
score === 0 && (userScore === undefined || userScore <= 0)
```

**Comment by marcogalluzzi** [comment]
I need also to add tests for this new use case: userScore > 0 and userScore not in {1, 2, 3, 4, 5}

**Comment by ambrinchaudhary** [comment]
Hi Marco, 
as we just discussed via slack, I think this approach is not the correct. It does not make sense to have a 0 score (which should mean the user has not voted yet) and have the Delete button enabled (should only be enabled when user has voted) 
We have seen that it is returning 0 becuase the value 0.5 sent via API does not match with the internal values we have: 
Screenshot 2023-08-25 at 10 59 38
And because this fn: 
```
const starScore = starScores.find(({value}) => score === value);
return (starScore && starScore.label) || 0;
```

I think that the correct approach would be to show a 3 (0.5 would be like a 0.6) and then the Delete option would be available, and this would make sense because the user really voted. So we decided to confirm if this would be the expected result with PM and UX and work in a different fix.

**Pull request closed without merging**
