### PR TITLE
Lps 153120 Max file size vs. Mime type size limits

### PR DESCRIPTION
**Pull request by thienquach87**
Fix comment on [brianchandotcom#122497](https://github.com/brianchandotcom/liferay-portal/pull/122497) rebase error

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Hey @ thienquach87, I'm sorry but this has conflicts again with master. Please update the pull. Thanks!

**Comment by thienquach87** [comment]
> Hey @ thienquach87, I'm sorry but this has conflicts again with master. Please update the pull. Thanks!

@ambrinchaudhary ,
Thank you for informing me know. I will rebase again next Monday after coming back from my vacation

**Comment by thienquach87** [comment]
ci:test:sf

**Comment by thienquach87** [comment]
ci:test:relevant

**Comment by thienquach87** [comment]
ci:reevaluate:1367401_1964

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by thienquach87** [comment]
Hi @Hanlf
It still has errors.

**Review by adolfopa — APPROVED** [review]

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
The failures should be not related to this PR, I will wait for the result of the last attempt, and if it still fails, I will send it directly to BChan.
cc/ @adolfopa

**Comment by Hanlf** [comment]
The above failures are not related to this PR, sent this pull directly to BChan: https://github.com/brianchandotcom/liferay-portal/pull/122753

**Pull request closed without merging**
