### PR TITLE
LPS-170770 | Master 

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-170770

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:document

**Comment by Hanlf** [comment]
ci:test:sharing

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
