### PR TITLE
LPS-121648 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by marcoscv-work** [comment]
LGTM !

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by marcoscv-work** [comment]
Finally, we are going to rebuild the solution to simplify, but we will create a story to homogenize the solution in the future

**Comment by boton** [comment]
See more simple solution #894 that @marcoscv-work mentioned.

**Comment by marcoscv-work** [comment]
The story
https://issues.liferay.com/browse/LPS-122156

**Pull request closed without merging**
