### PR TITLE
[7.4-only] LPS-121959 Migrate v2 usages of clay:vertical-card in blogs/blogs-web

### PR DESCRIPTION
**Pull request by julien**
In this change, we replace <clay:vertical-card-v2 />(clay 2.x:
Metal+soy) with <clay:vertical-card /> (clay 3.x: React)

**Test plan**:
- Navigate to **Content & Data** > **Blogs**
- Create a new Blog Entry
- Navigate to the previous page

### CODE REVIEW

**Comment by julien** [comment]
cc @carloslancha @markocikos

**Comment by julien** [comment]
ci:test:sf

**Review by carloslancha — APPROVED** [review]

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
@liferay-lima, this PR looks stuck so I [asked for help on slack](https://liferay.slack.com/archives/C19PWQ74J/p1606204450188400).

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
@liferay-lima, please forward this when you get a chance, thanks.

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hi @julien @carloslancha, see the before and after: 

**_Before:_** 
Blogs cards - Before


**_After:_** 
Blogs cards - After

I see that this class `aspect-ratio-item-fluid` added to the  tag must be replaced with `aspect-ratio-item-vertical-fluid` and the look and feel will be the same. 

I guess this is missing in the Clay taglib, so I don't know what is better here: I would close the PR unless you promise me that this "bug" will be solved soon in Clay ;-)

**Comment by carloslancha** [comment]
Se have a new mechanism to do that (instead adding classes): `flushHorizontal` and `flushVertical` attributes. I think `flushVertical`  should work in this case. Could you please try it @ambrinchaudhary ? If that works we'll update the pr. Thx!

**Comment by julien** [comment]
@carloslancha you're right this seems like a "flush" use case

**Comment by ambrinchaudhary** [comment]
Mmm.. it doesn't work very well, seems that it is expanding the image, look at the flowers: 

Screenshot 2020-11-25 at 12 00 54

@julien @carloslancha

**Comment by carloslancha** [comment]
Ok, let me ask to our css/clay experts ;)

**Comment by ambrinchaudhary** [comment]
Thank you @carloslancha. Anyways, I've just noticed that the sticker icon for the users is also missing on the new cards :-(

**Comment by carloslancha** [comment]
The icon stuff should be fixed in other pr that should be merged today

**Comment by julien** [comment]
@ambrinchaudhary we're putting this one on hold until we talk about image "aspect ratio" classes

**Comment by carloslancha** [comment]
@ambrinchaudhary @julien this has been addressed in https://github.com/liferay/clay/pull/3815/files

To not stay blocked with this I created [this ticket](https://issues.liferay.com/browse/LPS-123984) so we can fix the issue once the migration is done. 

So we can continue with this one. Thx! :)

**Comment by julien** [comment]
thanks @carloslancha seems like a good idea to me.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
