### PR TITLE
LPS-137475 Translated languages hreflang tag can not be generated on display page

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
What is happening : 

record2

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
