### PR TITLE
LPS-160252 Remove Dev FF from code

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Removed Developer Feature Flag LPS-156421 from code

See https://issues.liferay.com/browse/LPS-160252

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by Jeremy-Ch** [comment]
Checking the failures...

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:knowledge-base

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:knowledge-base

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
ci:stop

**Comment by Jeremy-Ch** [comment]
Combined #4038 and #4052, new pull request please see #4060

**Pull request closed without merging**
