### PR TITLE
LPS-171073 - Error when updating SEO information after changing localization language

### PR DESCRIPTION
**Pull request by AlmirFe**
https://issues.liferay.com/browse/LPS-171073

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AlmirFe** [comment]
ci:test:sf

**Comment by AlmirFe** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
Send to BChan directly see: https://github.com/brianchandotcom/liferay-portal/pull/128844

**Pull request closed without merging**
