### PR TITLE
LPS-180735 | LPS-180736 Crawler user agents and use it for Layout SEO dynamic Rendering

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-180049

This is a follow up PR from https://github.com/liferay-lima/liferay-portal/pull/4222 after changes request

On this PRs, we will use the configuration for the user agents that now is alone for the previous LayoutSEODynamicRenderingConfiguration

image

- LPS-180735 show the new configuration
- LPS-180736 update the value of the new configuration with the existing values of the LayoutSEODynamicRenderingConfiguration
- LPS-180736 add test to test the upgrade
- LPS-180736 use the method from the userAgentMatcher to know if the user agent is on the list of the crawler user agents
- LPS-180736 remove the crawlerUserAgents properties from the layout seo rendering configuration
- LPS-180736 put message to let the user know where the crawler user agent configuration is now
- LPS-180736 buildLang
- LPS-180736  no need of modify the include, hard code the message
- LPS-180736 change the message to add the route to the configuration
- LPS-180736 buildLang

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa 
Can you confirm (the last 3 commits) that is what is asked on https://github.com/brianchandotcom/liferay-portal/pull/133687#issuecomment-1515853621 because I'm not sure at all.

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
on draft till I talk with Design/PM about the changes on the messages

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia I think this is good.
As this is a draft I'm not doing the forward; do it yourself when this is ready.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Semver error looks legit.

**Comment by AliciaGarciaGarcia** [comment]
rebased with master and add lost baseline

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1277401_7845

**Comment by Hanlf** [comment]
ci:forward:force

**Comment by Hanlf** [comment]
The Poshi failure is not related to this PR, forward it.

**Pull request closed without merging**
