### PR TITLE
LPS 196817

### PR DESCRIPTION
**Pull request by robertoDiaz**
LPS-196817 Use current company as default

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are unrelated

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
