### PR TITLE
LPS-127165, LPS-126922 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-127165
https://issues.liferay.com/browse/LPS-126922

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
