### PR TITLE
LPS-121802

### PR DESCRIPTION
**Pull request by brianikim**
Resending from: https://github.com/liferay-lima/liferay-portal/pull/892

https://issues.liferay.com/browse/LPS-121802

This might fix:
https://issues.liferay.com/browse/LPS-118972
https://issues.liferay.com/browse/LPS-107452

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Thank you @brianikim !!

**Pull request closed without merging**
