### PR TITLE
LPS-154808 update metadata extractor lib version and dependencies

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-154808 update metadata extractor lib version and dependencies

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1387401_1024

**Comment by liuxingye** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
I thought that I put this early but....

@adolfopa do you think that it's good idea to revert the changes made on LPS-154808 ?

**Comment by AliciaGarciaGarcia** [comment]
rebased with master and reverted the changes

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
