### PR TITLE
LPS-202501 Using KBArticle.resourcePrimKey as key to store in TrashHandler

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Now we are using `resourcePrimKey` instead of `kbArticleId` as the primary key when storing to the TrashHandler

See: https://liferay.atlassian.net/browse/LPS-202501

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
