### PR TITLE
LPS-180051

### PR DESCRIPTION
**Pull request by icgsbr**
### Jira Link
[LPS-180051](https://issues.liferay.com/browse/LPS-180051)

### What was done:
- Enabled collection creation on different language from the default one
- Fixed collection locale reference in order to fix the asset publisher view when in a language different from the default one

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hey @icgsbr, this component does not belong to Lima. But I'm not sure if it should be forwarded to https://github.com/liferay-echo or other team, so I would try to send them the pull first.

**Comment by adolfopa** [comment]
@icgsbr Please send to @liferay-echo

**Comment by icgsbr** [comment]
Thanks guys!

**Pull request closed without merging**
