### PR TITLE
LPS-167590 DM Info Panel accesibility issues 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-167590 

**How to fix / recommendation:**

- `Adding roles to trigger button and panel (product menu example)`: "info" trigger button does not have a role, it belongs to the Management Toolbar and PEDS of FI can do the updates. Panel already had the role="tabPanel".
- `Add a button to close the panel in the panel`: was already added.
- `If we close the panel by activating the close button please return the focus to the trigger panel button`: was already working this way. 
- `When we open a panel/sidebar we should move the focus to the panel`: was already working this way. 
- `The panel will recibe de focus should have a description like aria-label="Info Panel" and tabindex="-1" in order to recibe the focus by JS`: added in this pull. Also added for the close button as described in https://liferay.atlassian.net/wiki/spaces/PEDS/pages/2289926432/Accessible+Panel+Sidebar

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
It looks good !

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
