### PR TITLE
LPS-150702 only change the folder id to default if the repository id of the folder is different from the scope group id

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Hi @adolfopa 

It's the (edited) task about the `FolderItemSelectorGroupSelector`

take a look and if you see something that can trigger some of the known issues. I tried some but maybe I'm forgetting some

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:staging

**Comment by Hanlf** [comment]
The four failed tests under ci:test:staging suite are not related to this PR.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
