### PR TITLE
LPS 118825

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Sent to Frontend Infrastructure team: https://github.com/liferay-frontend/liferay-portal/pull/481
Thanks @4lejandrito !!

**Pull request closed without merging**
