### PR TITLE
LPS-148819 Revert alloy editor enterMode change

### PR DESCRIPTION
**Pull request by jkappler**
- Revert "LPS-148819 Assert partial text"
- Revert "LPS-148819 Fix another path"
- Revert "LPS-148819 Update assertions"
- Revert "LPS-148819 Include alternative paths for different views"
- Revert "LPS-148819 Update blogs content test locator path"
- Revert "LPS-148819 Change the defaults behavior of the editor to CKEDITOR.ENTER_DIV (2)"

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@austinchiang, @john-co

**Comment by austinchiang** [comment]
ci:test:blogs

**Review by austinchiang — APPROVED** [review]
LGTM. Failing test is due to LPS-148695

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
