### PR TITLE
LPS-195032 merge settings under file preview limits

### PR DESCRIPTION
**Pull request by marcogalluzzi**
Resending PR #4668 with requested changes in https://github.com/brianchandotcom/liferay-portal/pull/142428 and on top of BChan commits

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Hi @marcogalluzzi , Please fix rebase errors and then I will continue to analyze this PR and forward. Thanks.

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:stop

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:stable

**Comment by WYZ-Issac** [comment]
Hi @marcogalluzzi, this stable failure only occurs in your PR. Could you please take a look? Thanks. [LocalFile.PortalSmoke#Smoke](https://testray.liferay.com/zh/home/-/testray/case_results/2445962800?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2445962746%26testrayRunId%3D2445962786%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
Hi @WYZ-Issac I've corrected the problem and re-launched the tests. Can you please force forwarding if current errors are unrelated? thanks!

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
ci:stop

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
Hi @marcogalluzzi, could you please resolve the conflict issue? And I will forward the PR.

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Hi @marcogalluzzi, unfortunately, there has been a conflict again. I think it may be because of the different time zones. After I went to work, the file you modified had other modifications. If possible, you can try to force forward directly after submitting the modification.

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
Hi @WYZ-Issac, I've just resolved the conflicts.

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
Failed to manually forward this PR to BChan's master. Because of the rebase error.

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:help

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Comment by marcogalluzzi** [comment]
Hi @SylviaLuan can you please check if errors are related and forward to bchan (manually if needed). I suppose they aren't but with last rebase and conflicts resolution I've changed these two lines of files `DMNavigator.macro` which I think were incorrectly "fixed". See the previous commit where the name of the _configurationScreenKey_ at the end of the URL is correctly changed but also the _scope_ (incorrectly)

The commit as it was originally sent: https://github.com/liferay-lima/liferay-portal/pull/4668/commits/c3ae55c20bb0fa3a538afc9c2b8449a1c98d54f3

The commit as it is now: https://github.com/liferay-lima/liferay-portal/pull/4816/commits/2886c4f9c71bb5af19b0dc50b270c426adadb45b

Thanks

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
ci:stop

**Comment by SylviaLuan** [comment]
ci:test:stable

**Comment by SylviaLuan** [comment]
Hi @marcogalluzzi,

Found a issue that realted to this pull request. 
[com.liferay.adaptive.media.image.internal.validator.test.AMImageValidatorTest
](https://testray.liferay.com/home/-/testray/case_results/2448838711)
```
[beanshell]      [exec] com.liferay.adaptive.media.image.internal.validator.test.AMImageValidatorTest > testIsProcessingSupported STARTED
[beanshell]      [exec] 
[beanshell]      [exec] com.liferay.adaptive.media.image.internal.validator.test.AMImageValidatorTest > testIsProcessingSupported FAILED
[beanshell]      [exec]     java.lang.NullPointerException
[beanshell]      [exec]     	at com.liferay.portal.kernel.repository.model.FileVersionWrapper.getGroupId(FileVersionWrapper.java:135)
[beanshell]      [exec]     	at com.liferay.adaptive.media.image.internal.validator.AMImageValidatorImpl.isValid(AMImageValidatorImpl.java:97)
[beanshell]      [exec]     	at com.liferay.adaptive.media.image.internal.validator.AMImageValidatorImpl.isProcessingSupported(AMImageValidatorImpl.java:74)
[beanshell]      [exec]     	at com.liferay.adaptive.media.image.internal.validator.test.AMImageValidatorTest.testIsProcessingSupported(AMImageValidatorTest.java:47)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
[beanshell]      [exec]     	at java.lang.Thread.run(Thread.java:750)
[beanshell]      [exec] 
[beanshell]      [exec] com.liferay.adaptive.media.image.internal.validator.test.AMImageValidatorTest > testIsValid STARTED
[beanshell]      [exec] 
[beanshell]      [exec] com.liferay.adaptive.media.image.internal.validator.test.AMImageValidatorTest > testIsValid FAILED
[beanshell]      [exec]     java.lang.NullPointerException
[beanshell]      [exec]     	at com.liferay.portal.kernel.repository.model.FileVersionWrapper.getGroupId(FileVersionWrapper.java:135)
[beanshell]      [exec]     	at com.liferay.adaptive.media.image.internal.validator.AMImageValidatorImpl.isValid(AMImageValidatorImpl.java:97)
[beanshell]      [exec]     	at com.liferay.adaptive.media.image.internal.validator.test.AMImageValidatorTest.testIsValid(AMImageValidatorTest.java:59)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
[beanshell]      [exec]     	at java.lang.Thread.run(Thread.java:750)
[beanshell] 2023-10-29 15:41:33.205 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:71] STOPPED com.liferay.adaptive.media.image.impl.test_1.0.0 [1553]
```
RCA tool: https://test-1-1.liferay.com/userContent/jobs/root-cause-analysis-tool/builds/12150/jenkins-report.html
Cause range: https://github.com/marcogalluzzi/liferay-portal/compare/00524f97a2151b67b6e9c727bc9e1f03a9e9641a...a7669bd6dc4738040bc847786dd9401651c296ea

**Comment by marcogalluzzi** [comment]
Hi @SylviaLuan I've fixed the failing test. Thanks for catching it.

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by austinchiang** [comment]
Manually forwarding pull

**Comment by austinchiang** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142970

**Pull request closed without merging**
