### PR TITLE
LPS-147439 There's no space between "Content text" and "This field is required"

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
https://issues.liferay.com/browse/LPS-147439

Instead of adding a margin, the background color was changed in accordance to the rest of the page, and visually there is no need to add a margin. 

**Before**
Blogs before

**After**
Blogs after
r

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
