### PR TITLE
LPS-162970 KB Edit Article updated pane

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issues detected by @Jeremy-Ch in the previous pull https://github.com/liferay-lima/liferay-portal/pull/3518

1. The error message can not be displayed when publishing the article without a title => I see same behaviour in WC. Just the title input is marked in red. 
2. When I try to resize the browser, the edit page doesn't change. Some contents will go outside the browser =>  fixed in this pull
3. When I try to edit an article in the KB display widget, the side panel is pinned to the screen. It will block something => Depends on pull https://github.com/liferay-lima/liferay-portal/pull/3523
4. For the title placeholder text, maybe we can use "Untitled Basic Article" => Different subtask created https://issues.liferay.com/browse/LPS-163852

With these changes the new look and feel is:
Screenshot 2022-09-29 at 15 27 13

**(mobile/reduced screens)**
Screenshot 2022-09-29 at 15 26 48

**Note**: parent story https://issues.liferay.com/browse/LPS-154208 is not complete. If something is missing in this pull, unless it brokes or introduces errors, could be handled in a different subtask. Feel free to open it in Jira.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:knowledge-base

**Comment by Jeremy-Ch** [comment]
Hi @ambrinchaudhary Don't worry, I will take look at this and fix the tests.

**Comment by ambrinchaudhary** [comment]
> Hi @ambrinchaudhary Don't worry, I will take look at this and fix the tests.

That would be great, thanks a lot @Jeremy-Ch!!! Let me know if I should fix something...

**Comment by Jeremy-Ch** [comment]
Hi @ambrinchaudhary  Only one Poshi test needs to be fixed, I have updated it. Other failures, please help take a look, thanks.

- The source URL can not be saved. The reproduced steps are as below.
      1. Go to system settings> Knowledge base> Service
      2. Enable the Source URL > Save
      3. Go to KB admin
      4. Add a new article with a source URL
      5. Publish
      6. Edit the published article
      7. Open the configuration panel
**Expected:** The source URL can be saved.
**Actual:** The source URL can not be saved.


https://user-images.githubusercontent.com/48118285/193301766-3faf7500-8d6e-45b0-80df-7ec2068cfc1e.mp4

- The suggestions panel can not be opened, for details see https://issues.liferay.com/browse/LPS-164471

**Comment by Jeremy-Ch** [comment]
New pull request see: https://github.com/liferay-lima/liferay-portal/pull/3542

**Pull request closed without merging**
