### PR TITLE
LPS-197819 use the new tag on the fragment

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
I think that the problem is the .lfrbuild-releng-ignore file on the saved-content parent module.
I will make all the service changes and then remove this file.
@adolfopa maybe we have to talk about it?

Thanks

**Comment by AliciaGarciaGarcia** [comment]
closed in favor of https://github.com/liferay-lima/liferay-portal/pull/4922

**Pull request closed without merging**
