### PR TITLE
[TS] LPS-161681 Fix NPE display context of AlertsPortlet

### PR DESCRIPTION
**Pull request by binhtran92**
The last PR is missing this case: https://github.com/liferay-lima/liferay-portal/pull/3430

cc: [adolfopa](https://github.com/adolfopa)

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by binhtran92** [comment]
ci:test:sf

**Comment by binhtran92** [comment]
ci:test:relevant

**Comment by binhtran92** [comment]
ci:test:sf

**Comment by binhtran92** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
