### PR TITLE
LPS-139554 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-139554

### CODE REVIEW

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
@liuxingye Let's wait for @boton to review this before forwarding.

**Comment by boton** [comment]
Sadly this view is common to the Asset Publisher and some things like the subtitle have been purposely removed by the Echo team. 

We are studying some possibilities like create a new view for shared content.

We are going to put this on hold at least after the release is out.

/cc @mbowerman @javalosjr96 @adolfopa

**Review by boton — CHANGES_REQUESTED** [review]
I mark as request changed but it's for ourselves @liferay-lima to try to find the best solution to this.

**Comment by javalosjr96** [comment]
@boton 
Ok, can I remove the subtitle from the fix and resubmit so that the issue regarding the image not scaling correctly can be given to the customer.

**Comment by boton** [comment]
> @boton Ok, can I remove the subtitle from the fix and resubmit so that the issue regarding the image not scaling correctly can be given to the customer.

@javalosjr96 I will try to add a minimum of changes to fix the image not scaling using the CSS of the blog portlet and avoiding add new CSS to Sharing. 

I will ping you when is ready.

**Pull request closed without merging**
