### PR TITLE
LPS-189854 Add button display type

### PR DESCRIPTION
**Pull request by sofiamendozalr**
Before:
885fa539-577f-4e24-9164-f17e61f1a4ea
After having changed the color of the configuration icon when editing a Knowledge Base Article:
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
The failures are unrelated. Forward directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
