### PR TITLE
LPS 134731 display templates SEO metatags template input

### PR DESCRIPTION
**Pull request by boton**
I've updated the code and the test to affecting only to new  MappingInput:

- Remove the unmapped option
- Clear the selected option when the mapping panel is closed
- Change the `Map content` literal of the mapping panel action button to `Add field`, leave the `Map content` on MappingSelector

**How to test it:**
1. Create a config file to enable the feature flag
```sh
cd ${LF_PORTAL_PATH} && echo "enabled=B\"true\"" > ../bundles/osgi/configs/com.liferay.layout.seo.web.internal.configuration.FFSEOInlineFieldMapping.config
```
2. Go to the Site menu > Design > Page Templates > Display Page Templates > [ + ] (create a new one)
3. **Blank**, add **Name:** whatever, **Content Type:** Web Content Article, **Subtype:** Basic Web Content
4. Click on the kebap menu of the new `Display Page Template` and select **configure**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The failure of `Container#MapManualURLToContainerElement` is not related to this PR, should be fixed by [LRCI-2329](https://issues.liferay.com/browse/LRCI-2329).
Not sure if the failure of `com.liferay.layout.test.LayoutCopyHelperTest.testCopyLayoutPortletPreferences` is related to this PR, only occours one time from the [test history](https://testray.liferay.com/zh/home/-/testray/cases/1518335178).
Will rerun it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
ci:reevaluate:1257401_2249

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The test failures about ContentPagesWithMapping#MapManualURLTo... is related to [LRCI-2329](https://issues.liferay.com/browse/LRCI-2329), not related to this pr, I will send it to BChan if it fails again.

**Comment by Hanlf** [comment]
The above failure about `Communications link failure` may be a ci flaky issue, no related to this PR. Resent it here: https://github.com/brianchandotcom/liferay-portal/pull/103834

**Pull request closed without merging**
