### PR TITLE
Lps 184965 Create configuration for file order

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-184965

Please let me know if I am missing something for creating a configuration that can be used to set default file orders. I think I have what is needed, but look forward to feedback.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
It looks good to me! Just need to correct a typo.

Also, in this PR, or in following one, please take into account to follow the layout design provided in [LPS-180478](https://issues.liferay.com/browse/LPS-180478), or at least discuss changes with designer.

**Comment by SamZiemer** [comment]
Hi Maroc,
I've updated the type and adjusted the wording for sort by, I've changed it to Sort Direction after speaking with Maria about keeping the wording consistent with the rest of Documents and Media.

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Pull request closed without merging**
