### PR TITLE
LPS-136611 Remove also data from DE when deleting a site

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-136611

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
@4lejandrito test was failing (estrepitosamente) because the service context and the user of the wrapper.

I investigate and I drop the commit about the action command and on the wrapper I only let the update of the file links

review another time if you could to assert all is ok

thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive621021 failure is not related to this PR, see [LPS-136711](https://issues.liferay.com/browse/LPS-136711)

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Still failed at [LPS-136711](https://issues.liferay.com/browse/LPS-136711).
@AliciaGarciaGarcia please let me know if you want me to send it to BChan directly.

**Comment by AliciaGarciaGarcia** [comment]
Thanks @Hanlf , let wait the reviewer :)

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
