### PR TITLE
LPS-185879 Preview and thumbnails are not override when checkin with “Keep Current Version Number

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-185879

resend after some changes were asked on : https://github.com/liferay-lima/liferay-portal/pull/4359

Steps to reproduce

It happens to with video (and I suppose that with audio/other preview)

1. Go to Content & Media > Documents and Media > “+” > File Upload
2. Select 1 PDF File which has Thumbnail and Publish
3. Select (⋮) button on it, and click “Checkout”
4. Select (⋮) button again and click “Edit”
5. Select PDF File (which is not include same Thumbnail with step3) and save
6. Note: Thumbnail is changed to New picture
7. Select (⋮) button, and click “Checkin”
8. Select “Keep Current Version Number” and Save

It happened that previews are no clean after the deletion of the fileVersion

A previous PR  https://github.com/liferay-lima/liferay-portal/pull/4349 caused https://issues.liferay.com/browse/LPS-186487  

The reason seemed to be a race condition that deleted the resources of the Folder (on this case, the permissions) before the files that were on the folder, and when some files needed to be checked (on the model listener) the error was thrown.
This should be solved by last [commit](https://github.com/liferay-lima/liferay-portal/pull/4365/commits/e996e31dafaa7432ff989fffca1d47c1bc0c4843).

- LPS-185879 when you delete a file entry that is a PWC make a cleanup of the previous trusted version of the file to make it new previews and thumbnails with the content con the correct version
- LPS-185879 remove the dlFileVersionPreview when removing the dlFileVersion
- LPS-185879 extract method
- LPS-185879 clean up the deleted file version previews and thumbnails
- LPS-185879 check null to prevent NPE when trying to delete the same file 2 times
- LPS-185879 move the delete resources method after the removal of the entity. Some dependencies of the main entity should need the resources to proper removal

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
