### PR TITLE
LPS-184793 Test failures in com.liferay.adaptive.media.document.library.web.internal.optimizer.test.DLAMImageOptimizerTest

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-184793

- LPS-184793 company2 is only used on one test so is no use to do the creation on the setUp
- LPS-184793 fix the number of images on the start
- LPS-184793 use AMImageCounter to count the expected images that a company should have after the creation and do not depend of an hardcored value

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
