### PR TITLE
LPS-132481 - Cannot add Google Drive Shortcut

### PR DESCRIPTION
**Pull request by boton**
https://issues.liferay.com/browse/LPS-132481

I have to remove deprecated groupPhotos (PHOTO_UPLOAD and WEBCAM): https://developers.google.com/picker/docs/reference#view-id

I guess with this fix we are losing

image
 
image

and I think that doesn't exist directed replacement.

**Before this PR**
Not working

**After this PR**
image
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
