### PR TITLE
LPS-157256 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-157256

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:onedrive

**Comment by austinchiang** [comment]
ci:test:online-editing

**Comment by austinchiang** [comment]
ci:test:online-editing

**Comment by austinchiang** [comment]
ci:test:onedrive

**Comment by austinchiang** [comment]
ci:reevaluate:1317401_4013

**Comment by austinchiang** [comment]
ci:reevaluate:1387401_1989

**Pull request closed without merging**
