### PR TITLE
LPS-159698 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-159698

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
ci:test:message-boards

**Comment by austinchiang** [comment]
ci:test:sharepoint

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/3348

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
