### PR TITLE
LPS-173880 KB TextFilter improvements in search results

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Given this navigation hierarchy:
 
Screenshot 2023-01-30 at 22 43 02

The results of search for "**folder**" would be: 

Screenshot 2023-01-30 at 22 42 50

And when there are no results: 

Screenshot 2023-01-30 at 22 43 17

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by jaimelr10 — APPROVED** [review]
LGTM! :smile:

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
