### PR TITLE
LPS-187728 | Refactor "Copy To" action code to make it servlet

### PR DESCRIPTION
**Pull request by jaimelr10**
Resend from: https://github.com/brianchandotcom/liferay-portal/pull/137598

Description: Refactor "Copy To" action code to make it servlet in order not to violate the ActionCommand standards

Jira Ticket: https://liferay.atlassian.net/browse/LPS-187656

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Pull request closed without merging**
