### PR TITLE
LPS-154730: Expose ERC in DocumentsFolder 

### PR DESCRIPTION
**Pull request by sergiojimcos**
Solved conflicts with rebase so you can move forward with the review. Original PR: https://github.com/liferay-lima/liferay-portal/pull/3304

Hi guys, I've opened this PR because most of the service changes I've made are related to your components. I'm going to introduced what are the changes that you should reviewed. Our team has verified that the errors appearing in the CI are not related, but we still want your approval, you can see [here](https://github.com/liferay-frontend/liferay-portal/pull/2548). You can check the desciption in the link of the PR from frontend-infra. Let's give you a little context.

## Main Objective
The main of this PR is to expose `externalReferenceCode` in DocumentsFolder. For that reason I have made some changes in the service part and in the API part.

## Service part
The main changes that you should review, are the following:

- Those changes related to `documentlibrary` in portal-impl. These changes are related because we add the new argument using `externalReferenceCode`.
- In the same way, in those modules I have implemented two new methods to obtain a DLFolder usign the `externalReferenceCode`, which are `fetchFolderByExteranlReferenceCode` and `getFolderByExteranlReferenceCode`.
- As there are some changes that affect the service part of DLFolder, I want to be sure that the Staging mode works correctly, some changes are added.
- New Upgrade process, if the `externalReferenceCode` is `null` or "", the data base will save the `externalReferenceCode` using the `UUID`.

## API part
However, this part can be ignored, beause it is reviewed by our members of the team.

If you have any problem, or any doubt, please contact me :smiley: 

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-154730

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
@sergiojimcos 
This is a nightmare but, can you re-re-rebase it again.

I will ask for help about this PRs, because it's hilarious right now... :(

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
I've rebased with master, let's try again!

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
>  [ 68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f533963726a436651584337385354363169762f67697068792e676966 ](https://camo.githubusercontent.com/16b293fd2f939209bd0f6941571f07936a969f78e259a7cc80ec3da75f4b9542/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f533963726a436651584337385354363169762f67697068792e676966) [ ](https://camo.githubusercontent.com/16b293fd2f939209bd0f6941571f07936a969f78e259a7cc80ec3da75f4b9542/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f533963726a436651584337385354363169762f67697068792e676966)

Yep, but I don't know way it show a bunch of commits :man_shrugging:

**Comment by AliciaGarciaGarcia** [comment]
@sergiojimcos 
the same error, make a baseline maybe the versions of the files are wrong.

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
