### PR TITLE
LPS-162970 KB Edit Article updated pane

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Story: https://issues.liferay.com/browse/LPS-154208. 

New look and feel: 
Screenshot 2022-09-22 at 22 48 49

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:knowledge-base

**Comment by Jeremy-Ch** [comment]
See the new pull request: https://github.com/liferay-lima/liferay-portal/pull/3518

**Pull request closed without merging**
