### PR TITLE
[TS] LPP-46887 > LPS-166040 Prepare the default AnnouncementsDisplayContext

### PR DESCRIPTION
**Pull request by tototrinh**
Hi guys,
Please help review this PR and leave your comments. Thanks.
https://issues.liferay.com/browse/LPS-166040
cc @hongvo2308

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
