### PR TITLE
LPS-126212 in the case that the NoSuchLayoutException is thrown and there is no LAYOUT_FRIENDLY_URL_PAGE_NOT_FOUND, we want that the title of the error page is the status language key as on 7.2

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @4lejandrito 

Instead to put the check on the TitleProvider I prefered to put it on the layoutSEOLinkManager for the title part.

Look if you think is better this or the other way

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
