### PR TITLE
LPS-118473 Override atlas style. As the atlas css is needed for the cards and we cannot restrict it to one single view (it is set at portlet level), we have to override this styles to solve the bug

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
Closing, will provide a different solution

**Comment by boton** [comment]
See #556.

**Pull request closed without merging**
