### PR TITLE
LPS-200534 Invite members: delete Confirm and Ignore button on success

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue: https://liferay.atlassian.net/browse/LPS-200534 

### Before 

Screenshot 2023-12-20 at 12 14 55

### After
Screenshot 2023-12-20 at 12 14 47

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1277401_11037

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
