### PR TITLE
LRQA-63227, LRQA-63838, LRQA-63839 | master only

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-63227
https://issues.liferay.com/browse/LRQA-63838
https://issues.liferay.com/browse/LRQA-63839

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The failures are not related, rerun it.

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
The failure test has been quarantined at the master head, rerun it

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
