### PR TITLE
LPS-133352 Use rotate icon in Image Editor

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-133352

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by boton — COMMENTED** [review]
LGTM. The rotate icon tells you the direction :D

**Comment by boton** [comment]
ci:forward

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
