### PR TITLE
LPS-167761 Remove bulk permissions ff

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
There are some unique failures for DM permissions tests in this pull so I'll need to verify some issues locally

**Comment by austinchiang** [comment]
Hey @adolfopa there is a bug in this PR. The **Access** permissions (checkboxes) are not loaded when opening up the permissions configuration iframe.



 I get 404's as well in the console:
```2022-11-08 07:47:47.439 WARN  [http-nio-8080-exec-1][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/classnames.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/classnames.js.map}
2022-11-08 07:47:47.443 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-components-web/__liferay__/index.js.map", uri=/o/frontend-js-components-web/__liferay__/index.js.map}
2022-11-08 07:47:47.442 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-web/__liferay__/index.js.map", uri=/o/frontend-js-web/__liferay__/index.js.map}
2022-11-08 07:47:47.442 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/index.js.map", uri=/o/frontend-js-react-web/__liferay__/index.js.map}
2022-11-08 07:47:47.441 WARN  [http-nio-8080-exec-6][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/react.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/react.js.map}
2022-11-08 07:47:47.443 WARN  [http-nio-8080-exec-5][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/prop-types.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/prop-types.js.map}
2022-11-08 07:47:47.453 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$label.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$label.js.map}
2022-11-08 07:47:47.453 WARN  [http-nio-8080-exec-10][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$button.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$button.js.map}
2022-11-08 07:47:47.453 WARN  [http-nio-8080-exec-2][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$drop-down.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$drop-down.js.map}
2022-11-08 07:47:47.453 WARN  [http-nio-8080-exec-1][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$icon.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$icon.js.map}
2022-11-08 07:47:47.453 WARN  [http-nio-8080-exec-7][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$card.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$card.js.map}
2022-11-08 07:47:47.453 WARN  [http-nio-8080-exec-8][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$form.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$form.js.map}
2022-11-08 07:47:47.456 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$multi-select.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$multi-select.js.map}
2022-11-08 07:47:47.456 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$link.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$link.js.map}
2022-11-08 07:47:47.457 WARN  [http-nio-8080-exec-6][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$navigation-bar.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$navigation-bar.js.map}
2022-11-08 07:47:47.457 WARN  [http-nio-8080-exec-5][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$pagination-bar.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$pagination-bar.js.map}
2022-11-08 07:47:47.458 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$shared.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$shared.js.map}
2022-11-08 07:47:47.459 WARN  [http-nio-8080-exec-10][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$sticker.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$sticker.js.map}
2022-11-08 07:47:47.459 WARN  [http-nio-8080-exec-2][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$alert.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$alert.js.map}
2022-11-08 07:47:47.463 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="404", msg="ProxyServlet: /o/portal-template-react-renderer-impl/__liferay__/index.js.map", uri=/o/portal-template-react-renderer-impl/__liferay__/index.js.map}
2022-11-08 07:47:47.463 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$layout.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$layout.js.map}
2022-11-08 07:47:47.462 WARN  [http-nio-8080-exec-8][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/react-dom.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/react-dom.js.map}
2022-11-08 07:47:47.462 WARN  [http-nio-8080-exec-7][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$modal.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$modal.js.map}
2022-11-08 07:47:47.460 WARN  [http-nio-8080-exec-1][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$loading-indicator.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$loading-indicator.js.map}
2022-11-08 07:47:47.467 WARN  [http-nio-8080-exec-6][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$table.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$table.js.map}
2022-11-08 07:47:47.467 WARN  [http-nio-8080-exec-5][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$autocomplete.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$autocomplete.js.map}
2022-11-08 07:47:47.468 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$pagination.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$pagination.js.map}
2022-11-08 07:47:47.470 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$core.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$core.js.map}
2022-11-08 07:47:47.471 WARN  [http-nio-8080-exec-8][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/react-dnd-html5-backend.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/react-dnd-html5-backend.js.map}
2022-11-08 07:47:47.470 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$data-provider.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$data-provider.js.map}
2022-11-08 07:47:47.472 WARN  [http-nio-8080-exec-7][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/react-dnd.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/react-dnd.js.map}
2022-11-08 07:47:47.475 WARN  [http-nio-8080-exec-1][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$badge.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$badge.js.map}
2022-11-08 07:47:47.476 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$panel.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$panel.js.map}
2022-11-08 07:47:47.476 WARN  [http-nio-8080-exec-6][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/clay-alert.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/clay-alert.js.map}
2022-11-08 07:47:47.476 WARN  [http-nio-8080-exec-5][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$list.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$list.js.map}
2022-11-08 07:47:47.478 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$progress-bar.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$progress-bar.js.map}
2022-11-08 07:47:47.481 WARN  [http-nio-8080-exec-8][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$tabs.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$tabs.js.map}
2022-11-08 07:47:47.482 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$popover.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$popover.js.map}
2022-11-08 07:47:47.483 WARN  [http-nio-8080-exec-7][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$toolbar.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$toolbar.js.map}
2022-11-08 07:47:47.484 WARN  [http-nio-8080-exec-1][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/clay-component.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/clay-component.js.map}
2022-11-08 07:47:47.485 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/clay-button.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/clay-button.js.map}
2022-11-08 07:47:47.485 WARN  [http-nio-8080-exec-6][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/clay-icon.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/clay-icon.js.map}
2022-11-08 07:47:48.238 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-state-web/__liferay__/index.js.map", uri=/o/frontend-js-state-web/__liferay__/index.js.map}
2022-11-08 07:47:48.242 WARN  [http-nio-8080-exec-8][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$tooltip.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$tooltip.js.map}
2022-11-08 07:56:49.854 WARN  [http-nio-8080-exec-5][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-state-web/__liferay__/index.js.map", uri=/o/frontend-js-state-web/__liferay__/index.js.map}
2022-11-08 07:56:49.876 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$tooltip.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$tooltip.js.map}
2022-11-08 07:56:49.877 WARN  [http-nio-8080-exec-8][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/classnames.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/classnames.js.map}
2022-11-08 07:56:49.883 WARN  [http-nio-8080-exec-2][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/react.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/react.js.map}
2022-11-08 07:56:49.883 WARN  [http-nio-8080-exec-7][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$shared.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$shared.js.map}
2022-11-08 07:56:49.886 WARN  [http-nio-8080-exec-6][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/react-dom.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/react-dom.js.map}
2022-11-08 07:56:49.886 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$button.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$button.js.map}
2022-11-08 07:56:49.889 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$icon.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$icon.js.map}
2022-11-08 07:56:49.889 WARN  [http-nio-8080-exec-10][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$link.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$link.js.map}
2022-11-08 07:56:49.893 WARN  [http-nio-8080-exec-5][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/index.js.map", uri=/o/frontend-js-react-web/__liferay__/index.js.map}
2022-11-08 07:56:49.894 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-web/__liferay__/index.js.map", uri=/o/frontend-js-web/__liferay__/index.js.map}
2022-11-08 07:56:49.898 WARN  [http-nio-8080-exec-2][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$alert.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$alert.js.map}
2022-11-08 07:56:49.898 WARN  [http-nio-8080-exec-8][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/prop-types.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/prop-types.js.map}
2022-11-08 07:56:49.902 WARN  [http-nio-8080-exec-6][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$form.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$form.js.map}
2022-11-08 07:56:49.902 WARN  [http-nio-8080-exec-7][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$layout.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$layout.js.map}
2022-11-08 07:56:49.905 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$loading-indicator.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$loading-indicator.js.map}
2022-11-08 07:56:49.905 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$modal.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$modal.js.map}
2022-11-08 07:56:50.194 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$card.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$card.js.map}
2022-11-08 07:56:50.194 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-components-web/__liferay__/index.js.map", uri=/o/frontend-js-components-web/__liferay__/index.js.map}
2022-11-08 07:56:50.198 WARN  [http-nio-8080-exec-1][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$drop-down.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$drop-down.js.map}
2022-11-08 07:56:50.199 WARN  [http-nio-8080-exec-5][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$label.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$label.js.map}
2022-11-08 07:56:50.201 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$sticker.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$sticker.js.map}
2022-11-08 07:56:50.202 WARN  [http-nio-8080-exec-10][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$table.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$table.js.map}
2022-11-08 07:56:50.204 WARN  [http-nio-8080-exec-2][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$multi-select.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$multi-select.js.map}
2022-11-08 07:56:50.204 WARN  [http-nio-8080-exec-8][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$autocomplete.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$autocomplete.js.map}
2022-11-08 07:56:50.206 WARN  [http-nio-8080-exec-7][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$core.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$core.js.map}
2022-11-08 07:56:50.207 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/react-dnd-html5-backend.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/react-dnd-html5-backend.js.map}
2022-11-08 07:56:50.207 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/react-dnd.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/react-dnd.js.map}
2022-11-08 07:56:50.210 WARN  [http-nio-8080-exec-1][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$navigation-bar.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$navigation-bar.js.map}
2022-11-08 07:56:50.212 WARN  [http-nio-8080-exec-5][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$pagination-bar.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$pagination-bar.js.map}
2022-11-08 07:56:50.213 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$pagination.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$pagination.js.map}
2022-11-08 07:56:50.215 WARN  [http-nio-8080-exec-2][code_jsp:161] {code="404", msg="ProxyServlet: /o/portal-template-react-renderer-impl/__liferay__/index.js.map", uri=/o/portal-template-react-renderer-impl/__liferay__/index.js.map}
2022-11-08 07:58:10.800 WARN  [http-nio-8080-exec-1][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-state-web/__liferay__/index.js.map", uri=/o/frontend-js-state-web/__liferay__/index.js.map}
2022-11-08 07:58:10.810 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$tooltip.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$tooltip.js.map}
2022-11-08 07:58:10.815 WARN  [http-nio-8080-exec-2][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/classnames.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/classnames.js.map}
2022-11-08 07:58:10.817 WARN  [http-nio-8080-exec-10][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/react.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/react.js.map}
2022-11-08 07:58:10.819 WARN  [http-nio-8080-exec-8][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$shared.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$shared.js.map}
2022-11-08 07:58:10.823 WARN  [http-nio-8080-exec-6][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/exports/react-dom.js.map", uri=/o/frontend-js-react-web/__liferay__/exports/react-dom.js.map}
2022-11-08 07:58:10.825 WARN  [http-nio-8080-exec-7][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$button.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$button.js.map}
2022-11-08 07:58:10.829 WARN  [http-nio-8080-exec-3][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$icon.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$icon.js.map}
2022-11-08 07:58:10.833 WARN  [http-nio-8080-exec-4][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-taglib-clay/__liferay__/exports/@clayui$link.js.map", uri=/o/frontend-taglib-clay/__liferay__/exports/@clayui$link.js.map}
2022-11-08 07:58:10.835 WARN  [http-nio-8080-exec-1][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-react-web/__liferay__/index.js.map", uri=/o/frontend-js-react-web/__liferay__/index.js.map}
2022-11-08 07:58:10.838 WARN  [http-nio-8080-exec-9][code_jsp:161] {code="404", msg="ProxyServlet: /o/frontend-js-web/__liferay__/index.js.map", uri=/o/frontend-js-web/__l
```
There are other tests failing because they are complaining about other missing checkboxes (Site Member-> Add Document, Site Member -> Subscribe, Site Member -> Add Subfolder, Site Member -> Add Shortcut, Guest -> View), but based on their screenshots and testing locally the elements are present so it might be a test issue (or some side effect caused by the issue described above).

**Pull request closed without merging**
