### PR TITLE
LPS-160252, LPS-177305, LPS-176368 Remove dev FF in Knowledge Base

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Previous pull: https://github.com/liferay-lima/liferay-portal/pull/4061

LPS-160252 Remove Dev FF from code
Removed Developer Feature Flag LPS-156421 from code
See https://issues.liferay.com/browse/LPS-160252

LPS-177305 Remove Dev FF for KB navigation and interaction
Removed Developer Feature Flag LPS-166643 from code
See https://issues.liferay.com/browse/LPS-177305

LPS-176368 Add KB tests to acceptance
https://issues.liferay.com/browse/LPS-176368

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:knowledge-base

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
Looks good from a backend perspective. @austinchiang Can someone of you guys take a look at the test changes?

**Comment by Jeremy-Ch** [comment]
I'm checking the failures.

/cc @adolfopa @austinchiang

**Comment by Jeremy-Ch** [comment]
ci relevant failures: Failures are not related to this pr.
ci test:knowledge-base failures: [LocalFile.KBDisplayWidget#CanViewArticlesWithDifferentSiteScopes](https://testray.liferay.com/home/-/testray/case_results/2243591854?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2243590482%26testrayRunId%3D2243590511%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) This failure is not a functional failure, we need to stabilize the test.

So this pr looks good from QA perspective.

/cc @austinchiang @adolfopa @ambrinchaudhary

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
