### PR TITLE
[TS] LPP-47606 > LPS-172261 | Modified Date is displayed incorrectly

### PR DESCRIPTION
**Pull request by sontruongces**
Motivation
=======
This work solves the problem reported in the [LPS-172261](https://issues.liferay.com/browse/LPS-172261) ticket.
cc: @TaiPhamLR @tototrinh 

Proposed Solution
========
Cause:
   - The modified date that displays on the "Documents and Media" UI is fetched from `DLFileVersion`.
   After updating the Permissions of a document, no records will be added to `DLFileVersion`. A new `DLFileVersion` record will be added when the user edits the document (use the 'Edit' action).
   Both actions can make updating the modified date of the document in table `DLFileEntry`.

What we did to solve this problem:
   - Using modified date from `DLFileEntry` for displaying.

Steps to Verify
========
1. Go to Default site > Content & Data > Documents and Media
2. Upload several documents (wait a few minutes between each upload)
3. Update a document permission settings
4. Sort Modified Date + descending-order

- Actual result: The document appears at the top of the list even though the Modified Date has not been updated.
- Expected result: The Modified Date is shown correctly.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR, since there is some new commit, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
one flaky failure about [modules-compile-jdk8/0/8](https://testray.liferay.com/zh/home/-/testray/case_results/2153008128?redirect=https%3A%2F%2Ftestray.liferay.com%2Fzh%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2153007451%26testrayRunId%3D2153007510%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc), re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not relate to this PR.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
Hi @sontruongces 
With this solution, the messages are confusing on cards and list view because the modified date is still the old one.


image

image


Can you take a look?

thanks!

**Comment by TaiPhamLR** [comment]
Hi @AliciaGarciaGarcia. Thanks for your comment. I fixed it.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by Hanlf** [comment]
The above failures are not related to this PR, they are some comment failures actually, see https://liferay.slack.com/archives/C19PWQ74J/p1673323578130039

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_7896

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
