### PR TITLE
LPS-155980 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-155980

This is a resend of https://github.com/brianchandotcom/liferay-portal/pull/120567

We redacted the batch and suite name from the queries to make it less verbose

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Resent in https://github.com/brianchandotcom/liferay-portal/pull/121709

**Pull request closed without merging**
