### PR TITLE
LPS-173780 Include only page/content available languages in sitemap

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-173780

Make sitemap include urls only for available languages (pages and web content).
# How do I test it?

1. Create a new page.
2. Translate its name to a couple of languages of your choice.
3. Request the sitemap (`/c/portal/sitemap`, then access the right one).

The returned XML should include only the languages with translations.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @adolfopa 
There are two failures that occur only on this PR and may be related to this PR, could you please take a look?
**Failure 1**: [com.liferay.layout.layout.admin.util.test.LayoutSitemapURLProviderTest](https://testray.liferay.com/reports/production/logs/2023-01/test-1-38/test-portal-acceptance-pullrequest(master)/6020/modules-integration-mysql57-jdk8/2/11/jenkins-console.txt.gz?authuser=0)
···
     [exec] 
     [exec] com.liferay.layout.layout.admin.util.test.LayoutSitemapURLProviderTest > testLayoutSitemapURLProviderContentLayoutTypePublished FAILED
     [exec]     java.lang.AssertionError: com.liferay.portal.xml.NodeList@72a193c expected:<13> but was:<1>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.layout.layout.admin.util.test.LayoutSitemapURLProviderTest.testLayoutSitemapURLProviderContentLayoutTypePublished(LayoutSitemapURLProviderTest.java:136)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] 
     [exec] com.liferay.layout.layout.admin.util.test.LayoutSitemapURLProviderTest > testLayoutSitemapURLProviderPortletLayoutType STARTED
     [exec] 
     [exec] com.liferay.layout.layout.admin.util.test.LayoutSitemapURLProviderTest > testLayoutSitemapURLProviderPortletLayoutType FAILED
     [exec]     java.lang.AssertionError: com.liferay.portal.xml.NodeList@462a893a expected:<13> but was:<1>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at com.liferay.layout.layout.admin.util.test.LayoutSitemapURLProviderTest.testLayoutSitemapURLProviderPortletLayoutType(LayoutSitemapURLProviderTest.java:176)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
···
Failure 2: [semantic-versioning-jdk8/0/0](https://testray.liferay.com/reports/production/logs/2023-01/test-1-38/test-portal-acceptance-pullrequest(master)/6020/semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)
```
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.util                            MINOR      42.0.0     42.0.0     42.1.0     VERSION INCREASE REQUIRED
[beanshell] 	<   class      com.liferay.portal.util.PortalImpl
[beanshell] 		+   method     getAlternateURLs(java.lang.String,com.liferay.portal.kernel.theme.ThemeDisplay,com.liferay.portal.kernel.model.Layout,java.util.Set)
[beanshell] 			+   return     java.util.Map
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 66.1.0
[beanshell] 
     [echo] 
     [echo] ##
     [echo] ## /opt/dev/projects/github/liferay-portal/baseline-reports/portal-kernel.log
     [echo] ##
     [echo] 
[beanshell]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
[beanshell] = ================================================== ========== ========== ========== ========== ==========
[beanshell] * com.liferay.portal.kernel.util                     MINOR      53.0.0     53.0.0     53.1.0     VERSION INCREASE REQUIRED
[beanshell] 	<   class      com.liferay.portal.kernel.util.PortalUtil
[beanshell] 		+   method     getAlternateURLs(java.lang.String,com.liferay.portal.kernel.theme.ThemeDisplay,com.liferay.portal.kernel.model.Layout,java.util.Set)
[beanshell] 			+   access     static
[beanshell] 			+   return     java.util.Map
[beanshell] 	<   interface  com.liferay.portal.kernel.util.Portal
[beanshell] 		+   method     getAlternateURLs(java.lang.String,com.liferay.portal.kernel.theme.ThemeDisplay,com.liferay.portal.kernel.model.Layout,java.util.Set)
[beanshell] 			+   access     abstract
[beanshell] 			+   return     java.util.Map
[beanshell] [Baseline Warning] Bundle Version Change Recommended: 95.1.0
```

**Comment by marcogalluzzi** [comment]
Hi @adolfopa I've rebased your PR, updated the package versions and, most important, fixed the integration tests. Can you please give me the permission to push my commits to your repository? Thank you

/cc @hanlf

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by adolfopa** [comment]
Manually forwarded to bchan: https://github.com/brianchandotcom/liferay-portal/pull/129543

**Pull request closed without merging**
