### PR TITLE
LPS-189073 Extract constant

### PR DESCRIPTION
**Pull request by robertoDiaz**
See https://github.com/brianchandotcom/liferay-portal/pull/137166 and https://github.com/brianchandotcom/liferay-portal/pull/137720 for context.

I've agreed with @adolfopa this approach (create the  DLFriendlyURLConstants constants class to add this DL_FRIENDLY_URL_PATH)

Feel free to suggest any other option!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:reopen

**Pull request closed without merging**
