### PR TITLE
LPS-156273 Add dropdown support for DM extensions

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Applied changes requested in https://github.com/brianchandotcom/liferay-portal/pull/120689

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
@qa-lima are this errors related to this pull? This was previously sent in https://github.com/liferay-lima/liferay-portal/pull/3175

**Comment by AliciaGarciaGarcia** [comment]
There is a problem with facebook :( 

Thats why [LocalFile.DMVideoShortcut#AddWithInvalidURL](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53802//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DMVideoShortcut_AddWithInvalidURL_) is failing 

image

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Let me check...

**Comment by AliciaGarciaGarcia** [comment]
> Let me check...

if it's about the facebook issue, it seem to be ok now

image

**Comment by austinchiang** [comment]
Ok. The rest of the test results LGTM, so feel free to send it unless there we want to wait for @adolfopa to review it

**Comment by boton** [comment]
ci:forward

**Review by boton — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
Manually forwarded to Brian https://github.com/brianchandotcom/liferay-portal/pull/120920. 

Thanks @AliciaGarciaGarcia and @austinchiang for looking into it

**Pull request closed without merging**
