### PR TITLE
LPS-119793 No need for a human readable friendly URL

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
@Jeremy-Ch  is fixing the tests for this pull and will resend

cc @adolfopa

**Comment by Jeremy-Ch** [comment]
Hi @adolfopa I've updated poshi tests and resend a new pull, see [#762 ](https://github.com/liferay-lima/liferay-portal/pull/762)

cc @austinchiang

**Pull request closed without merging**
