### PR TITLE
LPS-104152 Remove old DDM specific JSPs

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
DocumentsadministrationUsecase#AddDocumentTypeAndMetadata failed at LPS-117054.

**Comment by Hanlf** [comment]
Resend it here https://github.com/liferay-lima/liferay-portal/pull/429

**Pull request closed without merging**
