### PR TITLE
LRQA-60590, LRQA-60561 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-60590

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
@liuxingye looks like this needs a rebase

**Comment by liuxingye** [comment]
see https://github.com/liferay-lima/liferay-portal/pull/543

**Pull request closed without merging**
