### PR TITLE
LPS-155219 Moved description underneath content and added spacing.

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-155219

Forward: https://github.com/fortunatomaldonado/liferay-portal/pull/22

LPS-155219 Moved description underneath content and added spacing to make the section consistent with the rest of the page.

Let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1257401_3342

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by boton** [comment]
Instead of moving the explanation text under, talking with [Maria Martins](https://issues.liferay.com/secure/ViewProfile.jspa?name=maria.martins), we prefer to recover the forgotten title separator component as in design.

**Pull request closed without merging**
