### PR TITLE
LPS-150991

### PR DESCRIPTION
**Pull request by holatuwol**
## Motivation

https://issues.liferay.com/browse/LPS-150991
https://issues.liferay.com/browse/PTR-3050

## Proposed solution

Searching in the source code, we found several dozen instances where something called getStaticResourceURL and getContextPath, without also calling getPathProxy.

```bash
git ls-files -- '*.java' | xargs grep -Fl 'getStaticResourceURL' | xargs grep -Fl 'getContextPath()' | xargs grep -L 'getPathProxy()'
git ls-files -- '*.jsp*' | xargs grep -Fl 'getStaticResourceURL' | xargs grep -Fl 'getContextPath()' | xargs grep -L 'getPathProxy()'
```

I asked the TSE to open [PTR-3050](https://issues.liferay.com/browse/PTR-3050) in order to get a perspective on how to best fix the issue, and the conclusion was that we should fix all instances where we see the pattern appear, rather than fix the API itself to automatically account for potentially incomplete parameter values (as is done with ComboServlet).

After preparing the pull request https://github.com/liferay-core-infra/liferay-portal/pull/964, the core infrastructure team recommended that we split up the pull request by reviewer. According to the DXP Product Teams page, Lima is responsible for Blogs, Documents and Media, and SEO Tools, and so we're sending some of the changes here.

## Steps to verify

The TSE was not able to figure out how to reproduce the issue in all the instances where the pattern appears, but they were able to identify steps to reproduce for all of the issues fixed in this pull request. They have shared a Google Drive document describing what we need to access in the portal in order to see the issue introduced by that file having an erroneous pattern.

https://docs.google.com/document/d/1dmiP23za68PAbbvxp-GrTO_EkRQ6Di0Z1-cqlDZXNts/edit

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@austinchiang Do you guys have bandwidth to automate any of the scenarios described in the document? If possible, I'd prefer to send this pr with some tests.

**Comment by adolfopa** [comment]
@holatuwol  If you want us to forward these changes you'll need to update the commit history so that the CI is green.

**Comment by austinchiang** [comment]
@adolfopa we can take a look, though it might take a few days to finish it.

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Hey @adolfopa @holatuwol when I was testing this today I discovered https://issues.liferay.com/browse/LPS-157182 which blocks us from adding tests on Master (apparently this issue was already documented in https://issues.liferay.com/browse/LPS-150991 but maybe it never got fixed). So we can either wait for LPS-157182 to be resolved before continuing with adding tests or just write them for 7.3.x (assuming we merge this pull then backport it)

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:reevaluate:1387401_1895

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failure are all flaky issues, no related to this PR.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by adolfopa** [comment]
@Hanlf If the errors are not related, can you forward this to brian? Thanks!

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
@adolfopa let me double check the failures and resend if it looks ok

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Pull request closed without merging**
