### PR TITLE
 LPS-146954 Clay dropdown with icons in DM 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Just missing the Share option 
@adolfopa @AliciaGarciaGarcia 

Also noticed that _Edit Image_ and _Checkout_ option are failing in master. i will check again and open bugs for them. 

**Before**: 
Screenshot 2022-04-06 at 11 59 55

**After**: 
Screenshot 2022-04-06 at 12 17 14

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
I added some things, review an check if I did nothing wrong :) 

There is a little movement on the 3 points of the dropdown on the load.

**Comment by ambrinchaudhary** [comment]
Thanks a lot @AliciaGarciaGarcia! I will continue from here

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
@adolfopa @boton do not run ci:test:relevant. The last commit is still a WIP and needs to be completed. In fact, there is a compile issue. One option is to separate in tasks, and forward this if you wish, but create another subtask to add the "Share" option to the dropdown...

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
baseline needed I think, @adolfopa

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
As @adolfopa and @AliciaGarciaGarcia reviewed and even added commits, I'm going to suppose this can be forwarded. Anyway it is under a FF.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
