### PR TITLE
LPS-162735: Publish blog permission changes after auto-save

### PR DESCRIPTION
**Pull request by kristofloneck**
Please Review:
[LPS-162735 ](https://issues.liferay.com/browse/LPS-162735)

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@ambrinchaudhary Backend looks fine. Can you take a look at the js changes?

**Review by adolfopa — APPROVED** [review]

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1337401_2288

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
