### PR TITLE
LPS-124162 change liferay-ddm:html to liferay-data-engine:data-layout-renderer to se the new DE values on the upload multi-files option Alicia Garcia 10/12/20, 11:40

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @AliciaGarciaGarcia,

I've been looking at the changes and, even though they are exactly what I asked you to do, I changed my mind. The new method is too specific and just a utility so adding it to the display context public API doesn't sound so good now that I reviewed it in more detail. 

I've sent https://github.com/liferay-lima/liferay-portal/pull/1246 with a similar approach that does not require adding new API methods. 

What do you think?

**Pull request closed without merging**
