### PR TITLE
LPS-191468 Fix message boards resource test failure

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-191468

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-191468.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Failures are unrelated. Forward directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
