### PR TITLE
LPS-119692 Make redirect-service optional

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@4lejandrito Are you aware of any other places where it may make sense to make redirections optional?

**Comment by adolfopa** [comment]
ci:forward

**Review by 4lejandrito — APPROVED** [review]

**Pull request closed without merging**
