### PR TITLE
LPS-131645 Move lang keys to configuration-admin-web

### PR DESCRIPTION
**Pull request by adolfopa**
Config. admin looks for keys in its own module. Move them from the Google Cloud integration so that the category name is translated correctly.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]
added rebase and SF

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
