### PR TITLE
LPS-115230 Update dependencies

### PR DESCRIPTION
**Pull request by adolfopa**
/cc @JorgeFerrer

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:revelant

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Resent as https://github.com/liferay-lima/liferay-portal/pull/227 after fixing a conflict with (https://github.com/liferay-echo/liferay-portal/pull/1066)

**Comment by adolfopa** [comment]
Closing in favour of https://github.com/liferay-lima/liferay-portal/pull/227

**Pull request closed without merging**
