### PR TITLE
LPS-136652 Upgrade from DXP 7.0 to DXP 7.3 is getting failed with FriendlyURLLengthException

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
PortalSmokeUpgrade#ViewPortalSmokeArchive621021 failure is not related to this PR, see LPS-136711.
[PortalSmokeUpgrade#ViewPortalSmokeArchive70106](https://testray.liferay.com/zh/home/-/testray/cases/1310700728) should be a fluke, will rerun it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
