### PR TITLE
LPS-189823 Change headers for accesibility issues

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-189823 

Now Blog hierarchy will be: 
**h1** HOME
     **h2** Blog title ("sr-only" provided by the theme)
         p class="h3" the visible Blog title
         h3 Blog subtitle
    **h2** More blog entries
    **h3** Other blog entries title.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Tests will need to be updated

**Comment by austinchiang** [comment]
ci:test:blogs

**Review by adolfopa — APPROVED** [review]

**Comment by austinchiang** [comment]
Can't force push to this branch so testing changes in https://github.com/austinchiang/liferay-portal/pull/1497

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
