### PR TITLE
LPS-138891 Warning throws when adding google drive documents

### PR DESCRIPTION
**Pull request by boton**
https://issues.liferay.com/browse/LPS-138891

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by boton** [comment]
Just to assure please @edalgrin, can you confirm that this file is no longer exist?

**Comment by edalgrin** [comment]
if you mean `frontend-css-web`, yes. It was removed here https://github.com/brianchandotcom/liferay-portal/pull/105046/files#diff-5a70fda52cbd86998fc4dc6122907be313401ac01c2f5545b675b8e0d47b1fe1L33

**Comment by boton** [comment]
Yep, I mean `frontend-css-web` thank you @edalgrin

**Comment by boton** [comment]
ci:forward

**Comment by liuxingye** [comment]
Hi @boton, could you take a look at the SF issue when you get a chance? Thanks.

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
