### PR TITLE
LPS-175313 No folder shown in folder facet for documents and media

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
As said on [LPS-175313](https://issues.liferay.com/browse/LPS-175313?focusedCommentId=2854751&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2854751)  This PR restore the behavior of the model contributos
 

- LPS-175313 Revert "LPS-172530 Rename"
- LPS-175313 Revert "LPS-172530 SF"
- LPS-175313 Revert "LPS-172530 Add test integration"
- LPS-175313 Revert "LPS-172530 Update test"
- LPS-175313 Revert "LPS-172530 Don't show the searchFolder in the result."

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:search

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by Hanlf** [comment]
No relevant failures were found from `ci:test:search` and `ci:test:document`.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
