### PR TITLE
LPS-116506 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-116506

### CODE REVIEW

**Comment by austinchiang** [comment]
https://github.com/liferay-lima/liferay-portal/pull/2470

**Comment by austinchiang** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @austinchiang ,
I will close this PR, since it has some conflicts with this [commit](https://github.com/brianchandotcom/liferay-portal/pull/109913/commits/7e953090ea282830b326ac910bb22dc9bce7d066) in BChan's queue, the macro was renamed:(

**Comment by Hanlf** [comment]
resent it here: https://github.com/liferay-lima/liferay-portal/pull/2472

**Pull request closed without merging**
