### PR TITLE
LPS-166287 | Automate LPS-166040

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description:** Creation of Priority 5 test to verify that user is able to create an announcement following the path described in [LPS-166040](https://issues.liferay.com/browse/LPS-166040)

**Jira Ticket:** https://issues.liferay.com/browse/LPS-166287

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:test:sf

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:test:sf

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:test:relevant

**Comment by jaimelr10** [comment]
ci:stop

**Comment by jaimelr10** [comment]
ci:stop

**Comment by jaimelr10** [comment]
ci:test:relevant

**Pull request closed without merging**
