### PR TITLE
LPS-206120 DM AI Creator:  show success message

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-206120 

https://github.com/liferay-lima/liferay-portal/assets/8373764/6b7abbd3-c24f-4c41-b520-f3c28549af6f

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by robertoDiaz — APPROVED** [review]
LGTM

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
