### PR TITLE
LPS-148268 Fix errors caused by SF changes

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
no related to this PR, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci issue.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Pull request closed without merging**
