### PR TITLE
LPS-164086 Disable Sharepoint filter by default

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The failures are not related to this PR.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
All failures are not related to this PR, sent it to BChan directly: https://github.com/brianchandotcom/liferay-portal/pull/123919

**Comment by marianoalvarosaiz** [comment]
Thanks @Hanlf!

**Pull request closed without merging**
