### PR TITLE
LPS-197821 show the saved content entries on the My Saved Content user panel

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-197821 new methods to obtain the saved content entry, the list of saved content entries by user/group and the count of this searching
- LPS-197821 buildService
- LPS-197821 comparator for the saved entries by classname
- LPS-197821 create the display content to show the result
- LPS-197821 obtain the saved content entries for the group user and show
- LPS-197821 delete the entry from the page
- LPS-197821 show the url to see the content
- LPS-197821 extract method

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Right now the pages is shown as 
image
So @boton can you take a look at it?

**Comment by boton** [comment]
I converted the URLs in link buttons and added styles to the table, but it still miss better styling and `title` and `aria-label`.

image

**Comment by boton** [comment]
The PR is still in Draft because is on top of #4787

### Frontend tasks
- [x] Style the table
- [x] Added `title` attributes 
- [x] Added `aria-label` attributes
- [x] Tested with VoiceOver (SC)

### New styles and title attributes
image

### Aria-labels attributes VoiceOver
image

**Comment by AliciaGarciaGarcia** [comment]
closed in favor of https://github.com/liferay-lima/liferay-portal/pull/4911

**Pull request closed without merging**
