### PR TITLE
LPS-107366 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
@4lejandrito need to check the errors. An exception in the ActionCommand is not catched by the fetch request in the frontend side.
Also, do we need to add a feature flag for this feature?

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Closing PR. Will check SF issue and fix the exceptions that may throw the service...

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/35

**Pull request closed without merging**
