### PR TITLE
LPS-181169 Force 404 failure when rating doesn't exist

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-181169

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-181169.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]
we should update `DocumentFolderResourceTest.testDeleteDocumentFolderMyRating` ?

**Comment by adolfopa** [comment]
ci:close

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia @austinchiang Actually, it seems that 204 is the expected response. The autogenerated base tests check for that case explicitly. I'll close the ticket as won't fix.

**Comment by austinchiang** [comment]
Could it be that the autogenerated test(s) are incorrect? 🤔

**Pull request closed without merging**
