### PR TITLE
LPS-194117 | Master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://liferay.atlassian.net/browse/LPS-194117

### CODE REVIEW

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Review by austinchiang — APPROVED** [review]
If we can create macros that:
1. Add a document type through API
2. Add documents with custom document types through API 
that would be ideal, but we can work on it in a separate task.

**Comment by austinchiang** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
