### PR TITLE
[TS] LPS-180462 max-age config shouldn't have space between equals and value

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-180462

According to https://www.rfc-editor.org/rfc/rfc9111.html#name-max-age-2, max-age shouldn't have a space between the "=" and the value.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The two DMCache Poshi tests need to be updated after the fix, re-sent it with the test fix under https://github.com/liferay-lima/liferay-portal/pull/4177

**Pull request closed without merging**
