### PR TITLE
LPS-192286 Replace Publish button by a dropdown

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
https://liferay.atlassian.net/browse/LPS-192286
- LPS-192286 Change publish button for a dropdown menu
- LPS-192286 Add getEditKBArticleActionDropdownItems method
- LPS-192286 Force submit behavior in publishButtonOnClick
- LPS-192286 Add FF

image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Previously approved: https://github.com/liferay-lima/liferay-portal/pull/4602

**Comment by Jeremy-Ch** [comment]
Hi @ambrinchaudhary Please help to solve the SF issue.

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
