### PR TITLE
LPS-199108 Add missing PortletRatingsDefinition for PageRatingsPortlet

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:stop

**Comment by Jeremy-Ch** [comment]
Hi @robertoDiaz A failure should be related to this pr. Could you help to take a look? Thanks.
com.liferay.ratings.transformer.test.RatingsDataTransformerUtilTest > testTransformCompanyRatingsData
com.liferay.ratings.transformer.test.RatingsDataTransformerUtilTest > testTransformGroupRatingsData 

```
 [exec]     java.lang.IllegalArgumentException: Invalid value 
[beanshell]      [exec]     	at com.liferay.ratings.kernel.RatingsType.parse(RatingsType.java:50)
[beanshell]      [exec]     	at com.liferay.ratings.kernel.transformer.RatingsDataTransformerUtil.transformCompanyRatingsData(RatingsDataTransformerUtil.java:58)
[beanshell]      [exec]     	at com.liferay.ratings.transformer.test.RatingsDataTransformerUtilTest.testTransformCompanyRatingsData(RatingsDataTransformerUtilTest.java:100)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
[beanshell]      [exec]     	at java.lang.Thread.run(Thread.java:745)
[beanshell]      [exec] 
[beanshell]      [exec] com.liferay.ratings.transformer.test.RatingsDataTransformerUtilTest > testTransformGroupRatingsData STARTED
[beanshell]      [exec] 
[beanshell]      [exec] com.liferay.ratings.transformer.test.RatingsDataTransformerUtilTest > testTransformGroupRatingsData FAILED
[beanshell]      [exec]     java.lang.IllegalArgumentException: Invalid value null
[beanshell]      [exec]     	at com.liferay.ratings.kernel.RatingsType.parse(RatingsType.java:50)
[beanshell]      [exec]     	at com.liferay.ratings.kernel.transformer.RatingsDataTransformerUtil.transformGroupRatingsData(RatingsDataTransformerUtil.java:101)
[beanshell]      [exec]     	at com.liferay.ratings.transformer.test.RatingsDataTransformerUtilTest.testTransformGroupRatingsData(RatingsDataTransformerUtilTest.java:110)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:228)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:50)
[beanshell]      [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:307)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:86)
[beanshell]      [exec]     	at java.lang.Thread.run(Thread.java:745)
[beanshell] 2023-10-13 12:47:27.879 INFO  [Arquillian-Connector-Thread][BundleStartStopLogger:71] STOPPED com.liferay.ratings.test_1.0.0 [1542]
[beanshell]      [exec] There were failing tests. See the report at: file:///opt/dev/projects/github/liferay-portal/modules/apps/ratings/ratings-test/build/reports/tests/testIntegration/index.html
[beanshell]      [exec] 
[beanshell]      [exec] 33 tests completed, 2 failed
[beanshell]      [exec] 
[beanshell]      [exec] > Task :apps:ratings:ratings-test:stopTestableTomcat
[beanshell]      [exec] Gradle build finished at 2023-10-13 12:47:28.056.
[beanshell]      [exec] 
[beanshell]      [exec] BUILD SUCCESSFUL in 1m 4s
[beanshell]      [exec] 248 actionable tasks: 23 executed, 225 up-to-date
[beanshell]      [exec] 
[beanshell]      [exec] See the profiling report at: file:///opt/dev/projects/github/liferay-portal/build/reports/profile/profile-2023-10-13-05-46-28.html
[beanshell]      [exec] A fine-grained performance profile is available: use the --scan option.
[beanshell]      [exec] 
[beanshell] 
[beanshell] BUILD SUCCESSFUL
```

**Comment by robertoDiaz** [comment]
Analyzing it.

**Comment by robertoDiaz** [comment]
Fix implementation was the problem.

They were hardcoding the avaliable portlet data definitions, so when adding a new one the test fails. I've change it in order to handle all the available elements in a dynamic way

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward

**Pull request closed without merging**
