### PR TITLE
LPS-177633 add validation for negative values

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
[LPS-177633](https://issues.liferay.com/browse/LPS-177633)

Steps to reproduce:

1. Set the Maximum Number of Pages in the system setting (e.g. set 200 as the maximum number)
2. Navigate to the site setting
3. Choose the PDF Preview site scope
4. Configure the number of pages as -1

- LPS-177633 add validation for negative numbers on command
- LPS-177633 add min value to the input
- LPS-177633 add aria-label to input

asked to resend rebased due rebase [errors](https://github.com/brianchandotcom/liferay-portal/pull/131331#issuecomment-1460167248)

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
