### PR TITLE
LPS-180152, LPS-180409, LPS-180150, LPS-180157, LPS-179827 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-180152
https://issues.liferay.com/browse/LPS-180409
https://issues.liferay.com/browse/LPS-180150
https://issues.liferay.com/browse/LPS-180157
https://issues.liferay.com/browse/LPS-179827

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:help

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:forward

**Pull request closed without merging**
