### PR TITLE
LPS-182364 MBThread UAD deletion errors - service builder changes

### PR DESCRIPTION
**Pull request by robertoDiaz**
This should be merged and published to pass #4331

The proble we have right now is that we are also using the annonimizable fields to delete the entities.

It means that if someone hits an entity (and it is persisted) this entity will be deleted (for example the statusByUserId field)

This is wrong, only owned elements should be removed on deletion action.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Review by marcogalluzzi — APPROVED** [review]

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:test:stable

**Comment by Hanlf** [comment]
Sent to Bchan here: https://github.com/brianchandotcom/liferay-portal/pull/136944

**Pull request closed without merging**
