### PR TITLE
LPS-121591

### PR DESCRIPTION
**Pull request by brianikim**
Resent from https://github.com/liferay-lima/liferay-portal/pull/866 

@adolfopa ,

I kept the iterator implementation since extensions is a Set of String variables. 

The subString(1) implementation is also required so it works as intended with our sanitization method: https://github.com/liferay/liferay-portal/blob/e6216e4d78283091a798087bb064d71536a33bf8/portal-impl/src/com/liferay/portlet/documentlibrary/util/DLImpl.java#L704

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
Hello @liferay-lima ,

Please let me know if you have any issues with this PR.

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/885

**Pull request closed without merging**
