### PR TITLE
LPS-133355 Show audio icon shows in CKeditor after enabling FFmpeg

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
When enabling FFMpeg for audios, we want to show the audio icon to show the audios on DL in an item selector, as we were doing when we enabled xuggler.
So now we not only check if xuggler is enabled but if the audio processor is enabled.

I decided not to mix xuggler and audio processor for the future deletion of xuggler.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1257401_481

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Blogs failing test can be related to : https://issues.liferay.com/browse/LPS-133539

**Comment by Hanlf** [comment]
ci:reevaluate:1037401_9747

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
rebase due conflict

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
