### PR TITLE
LPS-156003 Uploaded document is cleared when changing Document Type in Documents and Media

### PR DESCRIPTION
**Pull request by boton**
Previous PR: #3425

I add a few things over #3425.

- Use the `<liferay-ui:message` in JSP instead of `Liferay.Language.get` a72272bc28750a2f9f3c9d092fa34cfab9012c62
- Avoid managing prev value in frontend 2dd2b9fe95bc1546e58160adca70258c3a56e100
- Shown the confirmation only when is needed e863742c226777963856d58451dfa12440c5eec7

@orsolyaDekany please check if it is fine for you.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:reevaluate:1267401_4751

**Comment by orsolyaDekany** [comment]
Hi @boton , the message is well displayed now and the modal does not show up in editing mode when a document has already been saved. It looks good, thanks!

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1387401_3384

**Comment by adolfopa** [comment]
ci:reevaluate:1387401_3384

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122518

**Pull request closed without merging**
