### PR TITLE
LPS-134514 Avoid NPE and make logic more robust

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hey @adolfopa 

Thank you for running the test. I forgot it :(

**Comment by AliciaGarciaGarcia** [comment]
re-running test cause failed I thinks is not related

```
Portal log assert failure, see above log for more information: 
com.liferay.portal.verify.VerifyException: com.liferay.commerce.currency.exception.NoSuchCurrencyException: No CommerceCurrency exists with the key {companyId=20101, code=USD}
com.liferay.portal.verify.VerifyException: com.liferay.commerce.currency.exception.NoSuchCurrencyException: No CommerceCurrency exists with the key {companyId=20101, code=USD}
```

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
