### PR TITLE
LPS-194213, LPS-194214 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://liferay.atlassian.net/browse/LPS-194213
https://liferay.atlassian.net/browse/LPS-194214

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
