### PR TITLE
LPS-125966 Upgrade

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1384 with the version numbers fixed. Everything else looks ok to me.

**Pull request closed without merging**
