### PR TITLE
LPS-61517 Validate redirect

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-61517

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-61517.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@marcogalluzzi This can be tested in a synthetic way (by forging the URL manually); There's no reusable piece of code, but the logic is pretty basic (set membership), so I think it is fine.

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
