### PR TITLE
LPS-155175 remove LPS-150762 Feature Flag

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-155175 remove FF from code
- LPS-155175 remove FF portal.properties
- LPS-155175 remove FF java test
- LPS-155175 remove FF usages from poshi test

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @austinchiang 

I modified the Poshi tests to delete the FF, but a review is needed by QA team

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:lima

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:autotagging

**Comment by liuxingye** [comment]
ci:test:auto-tagging

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1327401_4881

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:auto-tagging

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:auto-tagging

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:lima

**Comment by austinchiang** [comment]
ci:test:upgrades

**Comment by austinchiang** [comment]
ci:test:lima-upgrade

**Comment by austinchiang** [comment]
ci:test:lima-upgrade

**Comment by austinchiang** [comment]
LGTM

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
Pushed to BChan https://github.com/brianchandotcom/liferay-portal/pull/120856

**Pull request closed without merging**
