### PR TITLE
LPS-170077 Add new week warning to date expire option to KB settings

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
Due the baseline errors, resend of https://github.com/liferay-lima/liferay-portal/pull/3841

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
