### PR TITLE
LPS-161585 Can't create Redirect Entries with accented characters

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-161585 add test to check behavior adding or updating the redirection with accented characters
- LPS-161585 when we save the friendly URL for the page we are saving it normalized, so save the sourceURL as a normalized
- LPS-161585 show the sourceURL as decodeURL
- LPS-161585 fix tests
- LPS-161585 Update test for checking the invalid source URL
- LPS-161585 add tests to check LPS-158085

Hi @liuxingye and @Jeremy-Ch 
I rebased https://github.com/liferay-lima/liferay-portal/pull/3497 and added test to check LPS-158085

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
I made some rewording

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
