### PR TITLE
[TS] LPS-124261

### PR DESCRIPTION
**Pull request by jonathanmccann**
I wasn't sure who best to review this but figured it could start here since it concerns your widgets.

From @noornajj:

>https://issues.liferay.com/browse/LPS-124261
>
>The issue here was that the RSS toggle for blogs configuration was not being updated. This was caused by the typeSettings not getting updated because the old settings were overridding it.
To fix the issue, I created a resetConfiguration method for ConfigurationOverrideInstance and made a call to that method in processAction() for BlogsAdminConfigurationAction when the action is "update".

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@jonathanmccann @noornajj Can you please send this PR to Core Infrastructure? I think they're the owners of the configuration classes.

Thanks!

**Comment by jonathanmccann** [comment]
Great, thank you for taking a look.

https://github.com/shuyangzhou/liferay-portal/pull/9664

**Pull request closed without merging**
