### PR TITLE
[TS] LPS 144687 Temporary files created by DownloadEntriesMVCResourceCommand are not deleted in case of an Exception

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-144687

To correctly remove the temporary file, I have moved the "try...finally" block to inside the last else clause, where we are using ZipWriter and I have change the code to always delete its file

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:reevaluate:1327401_1802

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:reevaluate:1307401_1503

**Comment by jorgediaz-lr** [comment]
Hi @adolfopa 

The ci error **com.liferay.portal.kernel.repository.UndeployedExternalRepositoryException: Unable to load external repository class com.liferay.portal.repository.liferayrepository.LiferayRepository because its plugin is not deployed** seems to be unrelated to my changes, it was reported in https://issues.liferay.com/browse/LPS-103720 but closed as "No Longer Reproducible" some weeks ago.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1257401_1256

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
Hi all,

This PR has finally [passed the relevant ci tests](https://github.com/liferay-lima/liferay-portal/pull/2608#issuecomment-1008622789) and it was approved by @adolfopa

Can we forward it?

Thank you

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
