### PR TITLE
LPS-197738 Use Group settings instead of Company settings

### PR DESCRIPTION
**Pull request by marcogalluzzi**
# Description

The group configuration settings should be used when processing file entries, when they do exist, instead of the company settings.

Related issue: https://liferay.atlassian.net/browse/LPS-197738

NOTE: this PR was already reviewed in #4774. I've only made a change requested by @adolfopa changing the method name `forEachFileEntryInTrash`.

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:reevaluate:1347401_5022

**Comment by marcogalluzzi** [comment]
ci:reevaluate:1347401_5022

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
