### PR TITLE
LPS-177317 PDF Preview's limit: reduce space between title and description

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
BEFORE: 

Screenshot 2023-03-07 at 14 29 39

AFTER: 

Screenshot 2023-03-07 at 14 03 42

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
