### PR TITLE
LPS-195184 Auto translation using google cloud translation API not working

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-195184

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-195184.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
There is only one unique failure to this pull but it seems that QA should check it because it's about a testcase:

```
java.lang.Exception: Expected text "Internetinhalt" does not match actual text (case insensitive) "WebContent" at "//body[contains(@class,'cke_editable')]"
	at WebContent.viewCP(/opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/macros/journal/WebContent.macro:2091)
	at TranslationsWorkflow.CanResubmitImportedEntryFromZipFile(/opt/dev/projects/github/liferay-portal/modules/apps/translation/translation-test/src/testFunctional/tests/TranslationsWorkflow.testcase:885)
	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$22.assertTrue(BaseWebDriverImpl.java:4211)
	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4697)
	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl$Condition.waitFor(BaseWebDriverImpl.java:4673)
	at com.liferay.poshi.runner.selenium.BaseWebDriverImpl.waitForTextCaseInsensitive(BaseWebDriverImpl.java:3457)
	at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.liferay.poshi.runner.PoshiRunnerExecutor.lambda$invokeLiferaySeleniumMethod$0(PoshiRunnerExecutor.java:1298)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Expected text "Internetinhalt" does not match actual text (case insensitive) "WebContent" at "//body[contains(@class,'cke_editable')]"
	... 12 more
```

**Comment by WYZ-Issac** [comment]
The testcase failure is a flaky issue. It's unrelated to this PR. Forward directly.

**Comment by WYZ-Issac** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
