### PR TITLE
[TECHNICAL SUPPORT] LPS-146530 Document Does Not Checkin after Edit in Office 365

### PR DESCRIPTION
**Pull request by robertoDiaz**
This message was written by Norbert:

Hey,

[LPS-146530](https://issues.liferay.com/browse/LPS-146530)

I'd like to start with the requirement to reproduce this issue is you will need a company account at Office 365 with active license to the programs like word. I had to request it trough IS and it took a bit of time.
In case you want just reach out to me and we can schedule a call for reproduction on my machine with my credentials.

About the issue: We are using effects in a functional component in a dangerous way.
When the user edits a document trough office 365, we will open a new tab and reload the documents and media page.
The problem here, is that our Liferay.component registered modal is still alive and its open method will reference setState methods that are not part of the current React component's scope.

As per [the react documentation about useEffect](https://reactjs.org/docs/hooks-effect.html#example-using-hooks-1) I refactored the code to make sure we handle this effect in our component proper lifecycles and also clean up after we unmount the react component.

Please review my change

### CODE REVIEW

**Comment by NemethNorbert** [comment]
There is an SF error:
58:5  warning  React Hook useEffect has a missing dependency: 'bridgeComponentId'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

I was not comfortable adding it, as its not a dependancy just a const variable, that won't change. Removing the dependancy array will force the useEffect to run everytime a render happens, however I only want to run it once we mount the component and clean it up once we unmount the component.

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Review by boton — CHANGES_REQUESTED** [review]
Thanks for the PR @NemethNorbert , you are right, we are using it dangerously.

To fix the SF issue, we can move the `const bridgeComponentId = `${portletNamespace}DocumentLibraryCheckinModal`;` inside the effect and add only the `portletNamespace` in the useEffect dependencies array.

What do you think about it?

**Comment by NemethNorbert** [comment]
> Thanks for the PR @NemethNorbert , you are right, we are using it dangerously.
> 
> To fix the SF issue, we can move the `` const bridgeComponentId = `${portletNamespace}DocumentLibraryCheckinModal`; `` inside the effect and add only the `portletNamespace` in the useEffect dependencies array.
> 
> What do you think about it?

I still think that SF warning is a bit persuasive in this scenario, however we can argue if the portletNamespace is changed we should clean up and re-render. The only problem is we don't expect it to change and it will be a bit misleading for fellow engineers reading this code in the future. Of course this can only be changed by changing this SF rule.

New PR: https://github.com/liferay-lima/liferay-portal/pull/2704

**Comment by NemethNorbert** [comment]
ci:close

**Pull request closed without merging**
