### PR TITLE
LPD-20363 Show icon in the DL item selector

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi,
May I ask to review my PR?

included in this:
[https://liferay.atlassian.net/browse/LPD-20352](https://liferay.atlassian.net/browse/LPD-20352)
[https://liferay.atlassian.net/browse/LPD-20363](https://liferay.atlassian.net/browse/LPD-20363)

Add Lock icon into the document library to show, if the guest user does not have permission to view the item:

In this PR I added to the item selector(card, list and table)

The link for [figma](https://www.figma.com/file/YMcgShbEYvN2XMPPpc154t/LPD-16311-Define-and-manage-Site-default-D%26M-permissions?type=design&node-id=47-7787&mode=design)

Thank you!

### CODE REVIEW

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2563350252

**Comment by jkappler** [comment]
ci:forward:force

**Comment by gergelyszalay** [comment]
@jkappler thanks, hopefully now it is fine

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2564190519

**Comment by jkappler** [comment]
ci:report:2564190519

**Comment by jkappler** [comment]
ci:report:2564190519

**Pull request closed without merging**
