### PR TITLE
LPS-121880 Migrate v2 usages in item-selector/item-selector-web

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Depends on** #1525

The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan:** 
1. On the home page, edit and add something, like a button. 
2. Double click on the button
3. Go to the mapping section, and in the Content field, click on + button 
4. On the modal, click on "Blogs" tab => here is the management toolbar that we are replacing. 

Screenshot 2021-02-23 at 13 06 22

If there are no blogs, you will see that the management toolbar is disabled, including the Display Style button when it shouldn't. Well, this is fixed in pull https://github.com/liferay-lima/liferay-portal/pull/1525, in this specific [line](https://github.com/liferay-lima/liferay-portal/pull/1525/commits/bc125ba882fe46e9c4cf321106c6ffc48d474e8c#diff-0472a60df273abf88d70b40c81377e866387a3d0a1564d484dc1b62ee9d8acc2L156). So, once this pull is merged this icon will not get disabled ever (behaviour confirmed with Lexicon). 

MT item-selector-web

/cc @julien @markocikos @jonmak08

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by carloslancha — APPROVED** [review]
Reviewed on top of https://github.com/liferay-lima/liferay-portal/pull/1525. LGTM. Thx!

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
