### PR TITLE
LPS-134513 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-134513

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:translation

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
TranslationsWorkflow#RejectandResubmitImportToDraftWebContent failed at the Save button issue, details here: https://github.com/liferay-lima/liferay-portal/pull/2488#issuecomment-977542941
The two TranslationsSEO failires are other test fix issues, not related to these commits, will fix under LPS-142969.

**Comment by adolfopa** [comment]
@Hanlf Regarding your comments in #2488, I think this is the expected behavior. When a translation is rejected, it is internally marked as "PENDING" by wf; this usually happens when the reviewer asks for changes (i.e. the task is not deleted, but rejected temporarily), so the user needs to go to Translations, make the change (saving as draft), and then resubmit the task from the Workflow app.

AFAIK, other components behave in the same way (at least WC does).

**Comment by Hanlf** [comment]
@adolfopa hmm, I checked the Web Content, the button is 'Save' after rejecting, see the video below:

https://user-images.githubusercontent.com/8328450/143253018-1fc6b0b3-e14e-4060-8135-7b9353bd1c71.mp4

**Comment by adolfopa** [comment]
@Hanlf But isn't this a different issue? The "Publish" => "Submit for Publication" behavior is the same.

I'll check other components today to see what is the most common pattern for the "Save" button. Thanks!

**Comment by Hanlf** [comment]
@adolfopa  Let me know if you need a ticket for the "Save" button issue, I will create it then.

**Comment by adolfopa** [comment]
Don't worry; I'll push the changes into this PR.

**Comment by adolfopa** [comment]
@Hanlf We'll have to accept the current state as valid. The problem is that we cannot determine at that point whether there's a translation in course or not, we can only guess. This is because translations are entered in wf by language (i.e. if the zip file contains translations for multiple languages, multiple wf entries will be created), but we cannot known which languages were importing until we analyze the ZIP file (which is done after saving/publishing).

In case it is of help for updating the tests, the current behavior is:
- No workflow enabled for translations: [Cancel] [Save] [Publish]
- Workflow enabled, no pending translations: [Cancel] [Save as Draft] [Submit for Publication (enabled)]
- Workflow enabled, any pending translations (in any language): [Cancel] [Save as Draft] [Submit for Publication (disabled)]

**Comment by Hanlf** [comment]
@adolfopa ok, I will update the Poshi test, thanks!

**Comment by Hanlf** [comment]
ci:test:translation

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above translation tests failures are not related to this PR.

1. One is an exporting bug, reported it here: https://issues.liferay.com/browse/LPS-143086
2. The other error should be a TF: when translating an experience, the title shows with the experience name, like `Translation of page name (Segment Email Experience) to zh-CN`, I think it is the expected after [LPS-141748](https://issues.liferay.com/browse/LPS-141748), @adolfopa , could you confirm about it? if yes, I think we can fix it under other PR.

So from our QA side, I think it can be forwarded.

**Comment by adolfopa** [comment]
@Hanlf Yes, the name change is expected. I added the segment name to avoid ambiguities when translating multiple experiences of the same layout (previously, only the layout name was displayed).

Thanks for looking into this. I'll take a look at the exporting bug.

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
resend it here: https://github.com/liferay-lima/liferay-portal/pull/2504

**Pull request closed without merging**
