### PR TITLE
LPS-193614 D&M problem with impersonation permissions

### PR DESCRIPTION
**Pull request by marcogalluzzi**
This solves download and preview links when impersonating

See issue for more info: https://liferay.atlassian.net/browse/LPS-193614

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Pull request closed without merging**
