### PR TITLE
LPS-166147 Add Entry Title to subscriptionSender

### PR DESCRIPTION
**Pull request by tototrinh**
Hi guys,
Please help review this PR and leave your comments. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-166147

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failures are not related to this PR, sent it to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/127158

**Pull request closed without merging**
