### PR TITLE
LPS-183917 DM: Copy To option added to the Management Toolbar

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue: https://liferay.atlassian.net/browse/LPS-183917
Both folders and file entries can be selected. 

The selected entries can be read in backend via:
```
String entries = ParamUtil.getString(renderRequest, "selectedEntries");
```
Screenshot 2023-07-31 at 16 07 24

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hey @SamZiemer, as this is under FF, for now I redirected this option to "/document_library/copy_folder". You could change it when your API is ready ;-). I tested and all the selected elements are passed as a strings separated by `, `, let me know if you need something else.

**Comment by SamZiemer** [comment]
Thanks @ambrinchaudhary, these changes look good!

**Review by SamZiemer — APPROVED** [review]

**Pull request closed without merging**
