### PR TITLE
LPS-175711 PDF Preview limit validation

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Followed designs attached to the story https://issues.liferay.com/browse/LPS-173762

Screenshot 2023-02-23 at 23 50 16

Screenshot 2023-02-23 at 23 50 24

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
As discussed in a Slack channel, the value is already provided by the display context (currently injected as "value").

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
