### PR TITLE
LRQA-75044, LRQA-75103 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LRQA-75103
https://issues.liferay.com/browse/LRQA-75044

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
