### PR TITLE
LPS-164481 KB preview revamp: General styles                

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-164481

Test fix for PR https://github.com/liferay-lima/liferay-portal/pull/3541

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
cc @austinchiang @boton

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
Waiting to ci:test:knowledge-base before forwarding...

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
https://github.com/liferay-lima/liferay-portal/pull/3562

**Pull request closed without merging**
