### PR TITLE
LPS-161376 Apply builder pattern

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @adolfopa 
The above failure [com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning[/apps/item-selector/item-selector-criteria-api]](https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/83744//testReport/com.liferay.semantic.versioning/SemanticVersioningTest/testSemanticVersioning__apps_item_selector_item_selector_criteria_api_) should be related to this PR, could you please take a look? thanks!

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
