### PR TITLE
PS-127421 Info Panel should extend to bottom of window

### PR DESCRIPTION
**Pull request by boton**
Previously review #3041.

I make some changes to [avoid bug](https://github.com/liferay-lima/liferay-portal/pull/3041#issuecomment-1129711158) when DM is on portletBasedNavigation (widget) and minor SF.

BTW @pat270 I think Site Membership isn't part of lima components

/ cc @pat270 @Hanlf

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by pat270** [comment]
Thanks @boton! I couldn't figure out what the test was saying.

**Comment by boton** [comment]
Rebased!!

@pat270 I drop the commit of Site Memberships [b51ba26](https://github.com/liferay-lima/liferay-portal/pull/3041/commits/b51ba264c7582d319d8a5beb4a8ffcf8bc032b83), I think that Site Memberships is owned by USM.

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
