### PR TITLE
LPS-123626 As a last resort, generate a random id for the user

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
LGTM, but this only covers Test case 1.
If we check this on java maybe we can generate an automatic ID for the two cases.

**Comment by boton** [comment]
If we generate the UUID in front maybe is a good idea to use the `uuid/v1` library

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:stop

**Comment by boton** [comment]
See #1273.

**Pull request closed without merging**
