### PR TITLE
LPS 121326

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by liuxingye** [comment]
The following error is not related to the changes in this PR.
```
com.liferay.portal.kernel.security.auth.PrincipalException$MustHavePermission: User 44012 must have ADD_FOLDER permission for com.liferay.document.library 44790
```

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
