### PR TITLE
LPS-165707 [HR_164] Giving buttons a propper aria label

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
@EugenioAntunes I rebased with master and seems that other changes were merge, so there is just one change done in this pull. 

> Motivation
> =======
> [LPS-165707](https://issues.liferay.com/browse/LPS-165707)
> 
> Proposed Solution
> ========
>  1. Search button: Was added a proper aria-label
>  2. Eye button: Was added a proper aria-label
>  3. Table icon button: Working properly
> 
> Steps to Verify
> ========
> Tools: JAWS
>  1. Open the URL:https://hrportaldev.bankofamerica.com/
>  2. HR Portal home page will be opened.
>  3. Navigate "Menu button to the top left. Click on Content and Data-> Documents & Media->Document types ->Add new Document types.
>  4. Navigate the toggle buttons beside the side navigation bar.
>  5. Click on the "Builder" button. Drag "Rich text" and drop on the text side.
>  6. Select Advanced tab.In predefined values field. Click on the image icon and a dialog box will appear. Activate JAWS and observe announcement for "search" button 
>  7. Click on "Sites and libraries" and select "sample site" and observe SR announcement for "eye" button
> 
> Issue Description Actual Result
> ========================
> The following buttons doesn't have alt text and announced as Unlabeled buttons
>  1. Search button
>  2. Eye button
>  3. Table icon button
> 
> Expected Result
> =============
> Meaningful image buttons should have appropriate alt text
>  Ex: Search button
>

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
