### PR TITLE
LPS-140116

### PR DESCRIPTION
**Pull request by mbowerman**
Description from forwarded pull request:

> @mbowerman
> Just HTMLescaped the announcement type and tested with burp.

/cc @javalosjr96

https://issues.liferay.com/browse/LPS-140116

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@mbowerman The test failure seems to be related. Can you take a look at it?

**Comment by mbowerman** [comment]
@javalosjr96 Can you take a look at the failing [LocalFile.PGAnnouncements#CanViewPreviousAnnouncementEntries](https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/7455/testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_PGAnnouncements_CanViewPreviousAnnouncementEntries_) test?

**Comment by javalosjr96** [comment]
@adolfopa 
I did a couple of local tests and all passed.
Here's the stacktrace:
https://gist.github.com/javalosjr96/d4fd4a18d902a07fed900d9ff76f8450

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
