### PR TITLE
[TS] LPS-203491 If this reference is optional then ensure it exists prior to using it

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPS-184165 made this reference optional so it may not exist depending on the store the client chooses. In this case we should return early to avoid an NPE when the scheduled job is run.

### CODE REVIEW

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:stop

**Comment by SylviaLuan** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
