### PR TITLE
LPS 145475 Add the url Title to the methods from the fileEntryService and the repository and capability files.

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
On this PR, we are following the path to propagate the changes adding the urlTItle to the next layers

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by Hanlf** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
solved test issue and rebased

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Pull request closed without merging**
