### PR TITLE
[TS] LPS-155179 JS placed in the Description field of an SVG is executed

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forwad

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
