### PR TITLE
LPS-136846, LPS-136847, LPS-136850 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-136846
https://issues.liferay.com/browse/LPS-136847
https://issues.liferay.com/browse/LPS-136850

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
Close and resend this pull request.

**Comment by Jeremy-Ch** [comment]
See https://github.com/austinchiang/liferay-portal/pull/1206

**Pull request closed without merging**
