### PR TITLE
LPS-201182 video resolutions

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Added quality selector hls [plugin](https://www.npmjs.com/package/videojs-quality-selector-hls) for video.js 

Screenshot 2023-11-22 at 13 09 11

Video with resolutions for tests: https://storage.googleapis.com/sgad-demo/resolutions/manifest.mpd 

currently, there are no changes when a different resolution is selected, I can work on that on a different pull.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1297401_8732

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
