### PR TITLE
LPS-122354, LPS-120551 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-122354
https://issues.liferay.com/browse/LPS-120551

Backported this to 7.3.x: https://github.com/brianchandotcom/liferay-portal-ee/pull/31972

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
This PR has no response after trigger forward more than 2 hours. close it

**Comment by liuxingye** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/952

**Pull request closed without merging**
