### PR TITLE
Lps-133831 fux upgrade values changing them to the actual values that the DERendered read correctly.

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
The value of the old boolean changed from checkbox to checkbox_multiple, so now we need to search the *%checkbox%* fields.

On the other hand, the values of the numeric fields needed to be formatted to values without the thousand separator (and depending of the locale)

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa

 maybe is needed to be sent to @liferay-data-engine?

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa 

on the commit https://github.com/liferay-lima/liferay-portal/pull/1934/commits/752e497798adcf7a7480656a43464a433ff953a1  

I tested what happened if launched both and seem that is no longer needed and the second fixes that the first can not update.

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Yes, send this to DE for review.

**Comment by AliciaGarciaGarcia** [comment]
closed and sent to @liferay-data-engine https://github.com/liferay-data-engine/liferay-portal/pull/518

**Pull request closed without merging**
