### PR TITLE
LPS-122888 make consistent naming on method to obtain the fileEntry

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @4lejandrito can you review the last commit

It's about this comment https://github.com/brianchandotcom/liferay-portal/pull/96135#issuecomment-731568780 

I'm not 100% of the name, cause can be fileName or title, but I think it's the requested change

Thanks!!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Looks good @AliciaGarciaGarcia.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
