### PR TITLE
LPS-126804 | Master only

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-125009
https://issues.liferay.com/browse/LPS-126095
https://issues.liferay.com/browse/LPS-126804

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
fyi, the commit message has some issue: should be LPS-126**084**, instead of LPS-126**804**

**Comment by liuxingye** [comment]
ci:test:sf

**Pull request closed without merging**
