### PR TITLE
LPS-177940 Add User Agent selector for Redirect Patterns

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
issue: https://issues.liferay.com/browse/LPS-177940

**BEFORE:** 
Redirect Pattern BEFORE

**AFTER:** 
Redirect Pattern AFTER

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1357401_3930

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1357401_3930

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
