### PR TITLE
LPS-192614 Performance issues loading images - lot of DDM accesses

### PR DESCRIPTION
**Pull request by marcogalluzzi**
When accessing an image there a lot of DDM accesses to check the image size (method `AMImageValidatorImpl.isProcessingSupported()`), which is not needed if we already have the image. We need to know that only if no image exists and we need to create it (thumbnails).

See issue: https://liferay.atlassian.net/browse/LPS-192614

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
`Duplicate entry '20096-com.liferay.portal.workflow.kaleo.designer-4-com.liferay.p' for key 'IX_A9FF4B2C'], SQL: insert into ResourcePermission (mvccVersion, ctCollectionId, companyId, name, scope, primKey, primKeyId, roleId, ownerId, actionIds, viewActionId, resourcePermissionId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`
does not seems to be related with this PR

**Comment by austinchiang** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
