### PR TITLE
LPS-121870 Migrate v2 usages in depot/depot-web

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-lima,

Attached is an update for http://issues.liferay.com/browse/LPS-121870.

**Test plan:**

1. From the global menu, select the **Applications** tab
2. Navigate to **Asset Libraries**
3. Create a new Asset Library
4. Set the **Sites** tab
5. In the **Connected Sites** section click on the **Add** button
6. Select a site
7. From the global menu, select the **Control Panel** tab
8. Navigate to **Users and Organizations**
9. Select the **Test Test** user
10. In the **Roles** tab, scroll down to **Asset Library Roles**
11. Click on the **Select** button

**Additional Notes:**

Currently it seems that filtering is not working properly in master,
so this has the same issue.  See https://issues.liferay.com/browse/LPS-128902

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]
:+1: thanks @jonmak08

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
tested and LGTM. @julien @jonmak08 thanks for open the bug

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
