### PR TITLE
LPS-117460 Avoid clone themeDisplay in AssetDisplayPageFriendlyURLProviderImpl #582

### PR DESCRIPTION
**Pull request by cgoncas**
Continuation of https://github.com/liferay-lima/liferay-portal/pull/582

Hey @adolfopa !!

I have reviewed the broken test, and actually there is a change in the behavior but I am not able to reproduce it in portal (because the update action always gets the right URL):

Maybe this is a bug, but I am not sure, and this is a critical piece of code. 

I would keep the code the way we have it today, it is not the cleanest code, but it works for our use case and maybe we can create a technical task to look into this in the future.

With the code we already have on master, we can close the bug.

/cc @4lejandrito

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @adolfopa !!

I have reviewed the broken test, and actually there is a change in the behavior but I am not able to reproduce it in portal (because the update action always gets the right URL):

Maybe this is a bug. I would keep the code the way we have it today, is not the cleanest code, but it works for our use case and maybe we can create a technical task to look into this in the future.

With the code we already have on master, we can close the bug.

**Comment by 4lejandrito** [comment]
Thanks @cgoncas, I created https://issues.liferay.com/browse/LPS-119646 to track future work on this. I'll close the pull request for now. It is linked in the issue so we can revive it at any time.

**Pull request closed without merging**
