### PR TITLE
[DO NOT FORWARD] LPS-121527 LPS-121503

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @4lejandrito 

Only change is the addition of the feature flag. See 791a562.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by 4lejandrito — APPROVED** [review]

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/852

**Pull request closed without merging**
