### PR TITLE
LPS-121960 Depot (AL) Change vertical-card-v2 to vertical-card

### PR DESCRIPTION
**Pull request by carloslancha**
Follow up on https://github.com/liferay-lima/liferay-portal/pull/1118 and https://github.com/liferay-lima/liferay-portal/pull/1102

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hi @carloslancha, 

on the new version of the cards there is always an icon and here we don't want it, is there any way to hide it? 

**Before (master):** 
Depot view - before (master)

**After:** 
Depot view - After

**Comment by carloslancha** [comment]
Thx @ambrinchaudhary !! We have to fix that since we don't have a way to do it right now. Nice catch!

**Comment by ambrinchaudhary** [comment]
Closing pull because of the above comment.

**Comment by ambrinchaudhary** [comment]
ci:reopen

**Comment by markocikos** [comment]
@ambrinchaudhary the icon still shows after Clay update, we are working on it!

**Comment by ambrinchaudhary** [comment]
oh thanks for the clarification @markocikos, I don't know why but I thought this was fixed on the new version of clay. Then, if you don't mind, I would close it again. And once the issue is fixed, please send this again to us and we will forward it ;-). 
Thank you!

**Pull request closed without merging**
