### PR TITLE
LPS-137889 New image cannot be uploaded if file has pending status

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @adolfopa 
Could you take a look at this failure about portal-license-smoke-jdk8/0, it might be related to your commits. [here](https://testray.liferay.com/reports/production/logs/2021-09/test-1-28/test-portal-acceptance-pullrequest(master)/52/portal-license-smoke-jdk8/0/0/jenkins-console.txt.gz) is the console log.

**Comment by adolfopa** [comment]
@Hanlf For some reason, I don't have access to the log. Can you send it to me?

**Comment by Hanlf** [comment]
Hi @adolfopa 
How about the Jenkins link: https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=0/421202/consoleFull (use your email address)
Also pasted error log here: https://gist.github.com/Hanlf/598f096921a5fee6f1c3aaa0d68e7511

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @adolfopa lol, the ci:test:relevant tests passed today.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
