### PR TITLE
LPS-158065 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-158065

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:help

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:comment

**Comment by adolfopa** [comment]
ci:reevaluate:1277401_4015

**Comment by adolfopa** [comment]
ci:reevaluate:1357401_2024

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
