### PR TITLE
LPS-164481, LPS-164246, LPS-162852, LPS-162970 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-164481
https://issues.liferay.com/browse/LPS-164246
https://issues.liferay.com/browse/LPS-162852
https://issues.liferay.com/browse/LPS-162970

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_5366

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_5366

**Comment by austinchiang** [comment]
Impedibug detected and filed here https://issues.liferay.com/browse/LPS-165135

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/3571#issuecomment-1272778646

**Pull request closed without merging**
