### PR TITLE
LPS-195737 Add configuration icon for "move" action

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://issues.liferay.com/browse/LPS-195737

The action was not migrated to the new modal, but was deleted when removing the feature flag. We need to bring back the action, as there are functional tests failing.

# How am I fixing it?

I've recreated the class, but instead of the old URL, I've replicated the same logic used for the dropdown buttons (the configuration actions are converted into dropdown icons).

@ambrinchaudhary This is a starting point, as it doesn't work. I need you to hook it up correctly to the frontend logic.

**Final result:** 

Screenshot 2023-09-18 at 22 42 05

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Hey @adolfopa, this is now working, please review the changes. I know I have duplicated code in `MoveKBObject.js `and _KBDropdownPropsTranformer.js_, but I could not find a way to reuse it in both sides, so for now we can leave it this way and I will figure out how to solve this. 

Also, I added icons to each option same like there are in every dropdown.

**Comment by ambrinchaudhary** [comment]
ci:test:knowledge-base

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1267401_11057

**Comment by ambrinchaudhary** [comment]
@qa-lima could someone please check if these errors are related to this pull?

**Comment by adolfopa** [comment]
@ambrinchaudhary Looks great :+1: 

Can you approve and forward this pull? As I'm the one that created it, I cannot do it myself.

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by austinchiang** [comment]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
