### PR TITLE
Lps 186953

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-186953

I believe I followed the requirements based in LPS-180478, but please let me know if I missed anything. Individual user preferences still override the defaults set by either the group or instance settings.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
@SamZiemer Can you take a look at the sf errors? Other than that, this looks good.

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
Hi @adolfopa, I just checked and it looks like a relatively new SF rule to disallow multiple components with more than 1 service type. All of the other ManagedServiceFactory classes were not refactored to remove the multiple services however so I think we can suppress that check for this new class.

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
