### PR TITLE
LPS-164161 add the fields expirationDate and reviewDate to the methods add and update of the KBArticleService

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
On is the second PR we add the new fields to the KBArticleService and we let it prepare to the fields to be added on the pages.

LPS-164161 add expiration date and review date to service add and update methods
LPS-164161 buildService
LPS-164161 fix calls to KBArticleService

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
Hey @AliciaGarciaGarcia half the KB tests are failing because there is an issue with the /add-kb-article endpoint after these changes. There seems to be something we are missing here but I'm not sure what. Can you please take a look?

`ERROR [http-nio-8080-exec-4][JSONWebServiceServiceAction:126] Conversion failed: ; <--- java.lang.NumberFormatException: For input string: ""`

kb

https://testray.liferay.com/reports/production/logs/2022-10/test-1-39/test-portal-acceptance-pullrequest(master)/868/functional-tomcat90-mysql57-jdk8/0/12/jenkins-console.txt.gz?authuser=0

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1307401_4989

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1377401_5610

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1317401_5415

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/3568

**Pull request closed without merging**
