### PR TITLE
LPS-197778 Should be an action url, not a render (use same approach as com.liferay.wiki.web.internal.asset.model.WikiPageAssetRenderer.getURLExport)

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
Errors do not seem related

**Comment by austinchiang** [comment]
Checking failures

**Comment by austinchiang** [comment]
Test failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
