### PR TITLE
[7.4-only] LPS-121959 Migrate v2 usages of clay:vertical-card in blogs/blogs-web

### PR DESCRIPTION
**Pull request by julien**
One of the cards wasn't replaced in [#1101](https://github.com/liferay-lima/liferay-portal/pull/1101)

cc @carloslancha @markocikos

**Test plan**
- Deploy `blogs-web` module
- Navigate to **Content & Data** > **Blogs**
- Create a new Blog entry, upload a new blog image and publish
- Select the **Images** tab

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
The change in this PR is good :+1: 

However, it will introduce a bug, that we are fixing in https://github.com/liferay/clay/pull/3819. See screenshot on bottom. I'd recommend putting this PR on hold until the Clay ticket is fixed and the next Clay version is applied to portal. @carloslancha is on it, should hopefully be in two days. 

This PR is in the same bag as https://github.com/liferay-lima/liferay-portal/pull/1129

screen

**Comment by julien** [comment]
That's a good point.
I see that [BlogsEntryImageVerticalCard.java](https://github.com/liferay/liferay-portal/blob/c0247e3e06cb6b346a5ba9c5689c4f40ad92fc50/modules/apps/blogs/blogs-web/src/main/java/com/liferay/blogs/web/internal/servlet/taglib/clay/BlogsEntryImageVerticalCard.java) has both `getIcon` and `getSticker` methods. If we remove `getIcon` we get the same result as before this change.

**Comment by julien** [comment]
Forget my previous comment, I should have known that we're talking about `getStickerIcon` here not `getIcon`
So like @markocikos said, let's keep this on hold until the next version of clay is released.

**Comment by markocikos** [comment]
@julien As it turns out, I was also wrong with my analysis in https://github.com/liferay-lima/liferay-portal/pull/1151#pullrequestreview-541904348. The issue looks the same as the one https://github.com/liferay/clay/pull/3819 fixes, but it is different. It is not that we are rendering sticker that should not be rendered, but the content of sticker is not correct.

In the backend, we are defining both `stickerIcon` and `stickerImageSrc`. `stickerImageSrc` is in model object in blogs-web, `stickerIcon` is set by default in VerticalCardTag. In this case, we[ render icon with higher priority over image](https://github.com/liferay/liferay-portal/blob/c0247e3e06cb6b346a5ba9c5689c4f40ad92fc50/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/cards/VerticalCard.js#L64-L74). This is a bug, we should render image with higher priority over icon.

We can fix this easily, no need to wait for Clay release.

/cc @carloslancha @boton

**Comment by markocikos** [comment]
LGTM! @boton feel free to review this PR, and forward if all ok.

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by carloslancha — APPROVED** [review]

**Comment by boton** [comment]
I talked with @julien and we think it's better to wait for the next clay in portal to get the fluid images working properly.

**Comment by julien** [comment]
[A new version of clay](https://liferay.slack.com/archives/CNBG06JS3/p1607027478370900) was released yesterday so this should be fixed.

**Comment by boton** [comment]
I checked and the image still isn't fluid

**Comment by julien** [comment]
Let me check what's going on here :+1:

**Comment by julien** [comment]
@boton please re-check when you get a chance

2020-12-04-132726_951x866_scrot

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
Checked with @julien and looks good ❤️

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
c:st

**Comment by boton** [comment]
ci:stop

**Comment by julien** [comment]
ci:sf

**Comment by julien** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
