### PR TITLE
LPS-159934, LPS-159933, LPS-159440 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-159933
https://issues.liferay.com/browse/LPS-159934
https://issues.liferay.com/browse/LPS-159440

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:reevaluate:1377401_4082

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Sent directly to BChan https://github.com/brianchandotcom/liferay-portal/pull/121602

**Pull request closed without merging**
