### PR TITLE
LPS-146518 Editing Geolocation value of an existing Web Contents is not possible

### PR DESCRIPTION
**Pull request by veroglez**
Issue: https://issues.liferay.com/browse/LPS-146518

@boton

**What's going on?**
The `MapBase` constructor is being executed before the initialization of the `MapBase.MarkerImpl`, which is in the constructors of `MapOpenStreetMap.es.js` and `MapGoogleMaps.es.js`. The method in charge of adding the marker (`addMarker` in `MapBase.es.js`) is being run before the `MarkerImpl` is initialized with the corresponding value, so [this condition](https://github.com/liferay/liferay-portal/blob/3fe4354c47df856b15bccd54f64d52595f22e178/modules/apps/map/map-common/src/main/resources/META-INF/resources/js/MapBase.es.js#L557) is not met. This causes the marker is not painted when editing web content.

**The fix**
I have moved the initialization of the MapBase implementations to their constructor, receiving the values as arguments.

**UPDATE**
I've set the implementations on the constructor of `Google/OpenStreeMaps` just before calling `super(...args)`. In this way, we aren't changing how MapBase works now.

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
I debug the issue with @veroglez and the changes LGTM.

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
The failing tests are related to this PR; I try to fix them [here](https://github.com/veroglez/liferay-portal/pull/83) but implementing the solution I take into account that we are changing how MapBase works.

Maybe is better to set the implementations on the constructor of Google/OpenStreeMaps just before calling `super(...args)` instead of passing it down to MapBase. In this way, we aren't changing how MapBase works now. 

What do you think about it @veroglez?

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
Hi @boton, what you propose seems good to me, I update the PR with those changes

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:test:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
