### PR TITLE
LPS-166716 Deleting or Reverting a Document Version Redirects the User to the Document Preview Page

### PR DESCRIPTION
**Pull request by Mikellorza**
Motivation
=======
The user should not be redirected. They should remain in the Document Versions page.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-166716)

Proposed Solution
========
Add redirect to current page

Steps to Verify:
----------------

1. Create a Document
2. Edit the document 10 times
3. Go to the Content Dashboard
4. Select the Document created in Step 1
5. Open the Info Panel
6. Go to the Versions Tab
7. Click the "View More" button
8. Click the Kebab Menu next to any Version entry
9. Click Delete or Revert

https://user-images.githubusercontent.com/46810560/198293210-3aba9e3e-86f3-4b26-ab4a-c82ae138934b.mp4

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @Mikellorza 

Can you resend with the rebase conflicts solved?

thanks!!

**Comment by adolfopa** [comment]
@Mikellorza Sorry, too late ;-) https://github.com/brianchandotcom/liferay-portal/pull/125705

**Comment by Mikellorza** [comment]
Thanks @AliciaGarciaGarcia  @adolfopa  :)

**Pull request closed without merging**
