### PR TITLE
LPS-189073 DL Friendly urls have the group after the document path

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:test:stable

**Comment by Hanlf** [comment]
ci:forward:force

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
