### PR TITLE
LPS-142736 Fix exporting when all experiences are selected

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa _CanExportMultipleAvailableLanguagesForMultipleExperiences_. error seem legit

**Comment by adolfopa** [comment]
@austinchiang We need to fix the tests. When exporting all experiences for a page (or set of pages), we're now always including the name of the experience. Where previously we had:
- Page-en_US-es_ES.xlf
- Page (Exp)-en_US-es_ES.xlf
we now have:
- Page (Default)-en_US-es_ES.xlf
- Page (Exp)-en_US-es_ES.xlf.
This only affects the case of exporting multiple experiences.

**Comment by liuxingye** [comment]
Send a new pull based on changes. See https://github.com/liferay-lima/liferay-portal/pull/2996
cc @adolfopa

**Pull request closed without merging**
