### PR TITLE
[TS] LPS-156003 Uploaded document is cleared when changing Document Type in Documents and Media

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi @boton ,
Previous PR: https://github.com/liferay-lima/liferay-portal/pull/3315

As we have discussed, I added a confirmation message to alert the user about possible data loss when changing the Document Type.
Could you please review it?
Thanks!

cc. @robertoDiaz

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1317401_4774

**Comment by boton** [comment]
As I talked with @orsolyaDekany we need to check if `Liferay.Language.get` is working on this PR because it is apparently failing.

I put it on hold until is tested.

**Comment by boton** [comment]
See #3431

**Pull request closed without merging**
