### PR TITLE
LPS-133931 SEO Mapping Basic template UI and backend

### PR DESCRIPTION
**Pull request by boton**
I update the params and values to work with the value if the Feature Flag is enabled and with the selectedFieldKey in other cases.

**How to test it:**
1. Create a config file to enable the feature flag
```sh
cd ${LF_PORTAL_PATH} && echo "enabled=B\"true\"" > ../bundles/osgi/configs/com.liferay.layout.seo.web.internal.configuration.FFSEOInlineFieldMapping.config
```
2. Go to the Site menu > Design > Page Templates > Display Page Templates > [ + ] (create a new one)
3. **Blank**, add **Name:** whatever, **Content Type:** Web Content Article, **Subtype:** Basic Web Content
4. Click on the kebap menu of the new `Display Page Template` and select **configure**

**Before the changes:**

image

**After the changes:**

image

**Note:** the initial values don't work very well because we don't upgrade the current data yet.

### CODE REVIEW

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
The PR is ready for review and forward. I've updated the description to reflect this.

Also note that we need to do more changes in the backed: update the OpenGraph metatags so that title and description are processed as templates, and an upgrade process to change the internal format. We'll do these things in additional tickets.

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
Although is a huge PR, overall LGTM. 

But I'm a bit confuse about having two different componentes `MappingInput` and `MappingRichInput`, as they render something quite similar but changes a little bit the interation. 

The reason to use one or the other is basically this condition: 
```
ffSEOInlineFieldMappingEnabled && props.fieldType === 'text' ? (
					<MappingRichInput
						initialFields={fields}
						key={props.name}
						selectedSource={selectedSource}
						{...props}
					/>
				) : (
					<MappingInput
						initialFields={fields}
						key={props.name}
						selectedSource={selectedSource}
						{...props}
					/>
				)
```

They receive the same parameters, and for now the look and feel is identical I guess 🤔 . So is there any strong reason to have them separated? Do you expect that `MappingRichInput` would evolve to something different, like an editor or something similar? Otherwise... it seems we are increasing the complexity at least for understanding all this puzzle ;-) 

The names of the components also confuses me, but I can't think in different ones right now... maybe we can add a little descripction on each of them to make them more clear? 

/cc @boton

**Review by ambrinchaudhary — COMMENTED** [review]
Although is a huge PR, overall LGTM.

But I'm a bit confuse about having two different componentes `MappingInput` and `MappingRichInput`, as they render something quite similar but changes a little bit the interation.

The reason to use one or the other is basically this condition:

```
ffSEOInlineFieldMappingEnabled && props.fieldType === 'text' ? (
					<MappingRichInput
						initialFields={fields}
						key={props.name}
						selectedSource={selectedSource}
						{...props}
					/>
				) : (
					<MappingInput
						initialFields={fields}
						key={props.name}
						selectedSource={selectedSource}
						{...props}
					/>
				)
```

They receive the same parameters, and for now the look and feel is identical I guess 🤔 . So is there any strong reason to have them separated? Do you expect that MappingRichInput would evolve to something different, like an editor or something similar? Otherwise... it seems we are increasing the complexity at least for understanding all this puzzle ;-)

The names of the components also confuses me, but I can't think in different ones right now... maybe we can add a little descripction on each of them to make them more clear?

/cc @boton

**Comment by boton** [comment]
I'm a bit confused because the component doesn't look identical, the `MappingInput` looks like 
image
an the `MappingRichInput` looks like
image

But you are right, the `MappingRichInput` would evolve to a field with visual labels 🤔 

The `MappingInput` could be renamed to `MappingSelect` isn't a select really but is a real input only a read-only one to show the option selected in the panel.

We could rename the `MappingRichInput` to `MappingEditor`.

What do you think @ambrinchaudhary?

**Comment by ambrinchaudhary** [comment]
Thank you very much for your screenshots. 

> the MappingRichInput would evolve to a field with visual labels 🤔

Ok then. Let's see how it evolves. 

Thanks!

**Comment by boton** [comment]
Talking with @ambrinchaudhary we decided to change names to better understand the component role.

- `MappingInput` becomes `MappingSelector` because it's a read-only input that only shows the selected value
- `MappingRichInput` becomes `MappingInput` because it's the real input/textarea but not an editor yet
- `MappingInputs` becomes `MappingField` to avoid confusion with a collection exclusively of MappingInput

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
