### PR TITLE
LPS-134428 Process OpenGraph metatag values as templates

### PR DESCRIPTION
**Pull request by adolfopa**
Tried and tested; ready to forward when everything green.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
LGTM

baseline and then forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
The failure of `ContentPagesWithMapping#MapManualURLToImageFragment` has been fixed under [LRCI-2329](https://issues.liferay.com/browse/LRCI-2329).
Re-ran it.

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
