### PR TITLE
LPS-135850 update the parent id of the custom meta tag to the id of the property

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-135850

Update the parent id of the custom meta tag no to the id of the parent of the property, upgrade it to the id of the property itself

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — CHANGES_REQUESTED** [review]
See my comments about variable naming. Other than that, it looks good to me; but we'll need to send this through the Data Engine team.

Please send the followup to them directly.

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa about the updatePreparedStatement, It looked strange to me too, but it's the way they are naming the _preparedStatement_ for the update/delete/... So that is why I named it this way

**Comment by AliciaGarciaGarcia** [comment]
see https://github.com/liferay-forms/liferay-portal/pull/907

**Pull request closed without merging**
