### PR TITLE
LPS-171026 Cannot delete blog image

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-171026

The blogs repository has some special rule when checking deletion permissions: only users that can add blog entries, can also delete file entries.  The problem right now is that the document permissions are checked instead of the portlet ones.

Add an extension point to file entry permissions so that blogs can attach itself to it and add the custom checks when necessary.

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-171026.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
