### PR TITLE
LPS-200600 KB use the user timezone 

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-200660

Way I tested it:

- Enable feature flag
- Go to instance settings> Localization> Time zone
- Change the time zone to “UTC-7“
- Go to user account settings> Preferences> Display Settings
- Change the time zone to “UTC-7“
- Go to Kb admin 
- Add a kb article and set the scheduled date and a expiration Date with the same date.

On database the date of both fields are the same

- LPS-200660 use the user timezone when saving the schedule date (display date)

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Review by adolfopa — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
