### PR TITLE
LPS-144290 Preview window shows in Item Selector for non-previewable files

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-144290

---

Only enable the preview of the image files based on backed response type and mime-type as a fallback.

When you upload a video file, it is not previewable until the video is processed and transformed. We show the `No Preview` message in videos until is processed.

I'll try to add a more bulletproof approach showing only the image when the image is loaded but is a bit over-engineering, I think that makes sense to go with this simplest approach.

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
the failure about js-unit-jdk8 is not related to this PR.

**Comment by boton** [comment]
Looks like fronted test is failing I'll take a look

**Comment by boton** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
