### PR TITLE
LPS-131382 no need to load the react component if do you not have permissions

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-131382

If there is not permission to the article or the article is unreachable, there is no need to load the react component that was throwing the error of the translation component cause the InfoFieldSetEntriesData was null.

So I decided that there is no need to load it if there is no permission and that shows the message that it expected to be shown.

image

As [said on the ticket,](https://issues.liferay.com/browse/LPS-131382?focusedCommentId=2430258&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2430258) the error on console is thrown on the previous page and if they do not want it to be shown is another issue

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
We can't move the react component inside the form because the react component renders the complete form, including the buttons' navbar.

This works fine when the user hasn't permissions or the article is unreachable but breaks the UI in another case.

The failing test shows it.

image

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
@AliciaGarciaGarcia and I move the react into a `c:if` instead of reuse the actual `c:when`

**Pull request closed without merging**
