### PR TITLE
LPS-188637 Avoid calling `store.getFileVersions` when getting AM content

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-188637

AM files are always saved as version Store.DEFAULT_VERSION; by passing that directly we can avoid an internal extra call to `store.getFileVersions` when requesting specific AM files.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
Thanks @AliciaGarciaGarcia . Brian already picked this manually, so I'm closing this and sending only that SF commit.

**Pull request closed without merging**
