### PR TITLE
LPS-189056 Add a mechanism for massive regeneration of OpenOffice  previews

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@robertoDiaz Looks good, but can you fix the conflict? Also, if this change comes from Brian, can you link the pr where it asked you to do it?

**Comment by robertoDiaz** [comment]
@adolfopa 

updated :)

**Review by adolfopa — APPROVED** [review]

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
