### PR TITLE
LPS 114992

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/234.

**Comment by austinchiang** [comment]
@4lejandrito just FYI, those tests were failing due to https://issues.liferay.com/browse/LPS-115521. QA reverted those changes already so I think #234 should pass

**Pull request closed without merging**
