### PR TITLE
LPS-142400/ LPS-142411 Remove translations over segments when deleting segments

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — COMMENTED** [review]
@adolfopa  the changes of the second commit are to solve [It only shows 'Translation' as title in Translations Processes after adding a new translation with new experience](https://issues.liferay.com/browse/LPS-142400)  ? 

if it's maybe is better to change the commit name to the proper LPS? 

if not, ok

**Comment by adolfopa** [comment]
I wasn't aware of that bug :-D

I've updated the last commit message; I'll forward directly.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
