### PR TITLE
LPS-133206 SF

### PR DESCRIPTION
**Pull request by kevenleone**
Hello everyone, I belong to Solutions Team in Brazil, and we need to use a Component to preview a Document Library file (JPG, PNG, PDF) etc.

As designed by the team, is the same used in Document Library Web.

image

And i saw that this module `document-library-document-previewer` have everything we need, to display this preview.
Here's my question:

We want to avoid duplication code, this way I could import the React Component but the CSS belongs to `document-library-web`. Can you guys review this PR ? and see if this change will break anything working well?

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by boton** [comment]
Thanks for the PR @kevenleone, isn't possible to move the CSS of `css/document_library_preview.scss` because shared information is shared with others `document-library-preview-` modules.

These modules are created for use only `document-library` but it makes sense to export the module ready to use.

We are talking about how to export it in the best way, feel free to open an issue for it but we will open it anyway.

Sorry for the inconvenience.

**Comment by kevenleone** [comment]
Thanks @boton and lima team !

**Comment by carloslancha** [comment]
Hey @kevenleone FYI we're working on it in this pr https://github.com/liferay-lima/liferay-portal/pull/1911

**Comment by kevenleone** [comment]
Thank you @carloslancha 🎉

**Pull request closed without merging**
