### PR TITLE
LPS-203653 Deprecate content type for AM processors

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPS-203653

There's support for multiple content types, but only HTML is used and there are no plans to support additional ones. This extra flexibility is unnecessary, and it is causing some race conditions in integration tests.

# How am I fixing it?

This PR deprecates/removes content types and inlines the basic HTML processing (which is required for everything to work properly anyway).

# How can you verify that it works?

There should be no visible changes; all existing integration tests should pass.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
Good work! I think the only thing missing is removing the module reference from the file `modules.properties`:

```
project.name[com.liferay.adaptive.media.image.content.transformer]=:apps:adaptive-media:adaptive-media-image-content-transformer
```

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by marcogalluzzi** [comment]
Hi @adolfopa a baseline is needed:
```
java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
= ================================================== ========== ========== ========== ========== ==========
* com.liferay.adaptive.media.content.transformer     MAJOR      2.0.0      2.0.0      3.0.0      VERSION INCREASE REQUIRED
	<   class      com.liferay.adaptive.media.content.transformer.BaseRegexStringContentTransformer
		<   method     getContentTransformerContentType()
			-   access     abstract
	<   interface  com.liferay.adaptive.media.content.transformer.ContentTransformer
		<   method     getContentTransformerContentType()
			-   access     abstract
	>   interface  com.liferay.adaptive.media.content.transformer.ContentTransformerHandler
		+   method     transform(java.lang.String)
			+   access     abstract
			+   return     java.lang.String
[Baseline Warning] Bundle Version Change Recommended: 6.0.0
```

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
Hi @adolfopa Could you help to solve the SF issue? Thanks.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
The SF message doesn't make much sense. It is complaining about a generic type that I removed in this same PR :confused: I'll check out things internally, as this looks like an sf tooling bug.

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1367401_4740

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:stable

**Comment by austinchiang** [comment]
@adolfopa there is a compile failure `[exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:adaptive-media:adaptive-media-image-content-transformer-backwards-compatibility:compileJava'` that is reproducible after updating the branch to the latest upstream master

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
