### PR TITLE
LPS-168158 DM - Remove dev FF (AUI)

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:document

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1327401_6871

**Comment by Jeremy-Ch** [comment]
Updated the poshi tests and the new pull request see: https://github.com/liferay-lima/liferay-portal/pull/3717

**Pull request closed without merging**
