### PR TITLE
[TS] LPS-159600 Active redirections on widget pages do not let users add or configure widgets

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue link: https://issues.liferay.com/browse/LPS-159600 
Continuation of https://github.com/liferay-lima/liferay-portal/pull/3389

> Unfortunately, the toast info message that's shown when viewing a page (following the steps in [LPS-159600](https://issues.liferay.com/browse/LPS-159600)) cannot be closed manually and it won't automatically closed either after the specified time.

Fixed issue about closing the Alert. 

Screenshot 2022-08-19 at 13 20 32

Thanks @dacousalr and @ricardocousolr for your work here!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
Thank you, @ambrinchaudhary, for your help!

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
hey @ricardocousolr @dacousalr could you please check if the failing test are related? seems to be...

**Comment by ricardocousolr** [comment]
Hi @ambrinchaudhary,

This may have to do with the line
```
"test": "liferay-npm-scripts test"
```
in `package.json` and not having any tests in the module. Could you try removing that line?

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Errors does not seem related... :-(

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
