### PR TITLE
LPS-151172 [WIP] Make basic document type company scoped

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

Ignore this PR.  I'm sending this just to see if something fails in the CI.

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-151172.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1397401_2276

**Pull request closed without merging**
