### PR TITLE
LPS-156630 bug translation multiple selection export

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-156630

### CODE REVIEW

**Comment by boton** [comment]
@ambrinchaudhary I will ask you for an early review because I'm gonna apply the same logic on Layout [admin](https://github.com/liferay/liferay-portal/blob/1c5317531125e88f66bc14565823d374a903ef98/modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/js/LayoutsManagementToolbarPropsTransformer.js#L52-L70) and [DL Permissions](https://github.com/liferay/liferay-portal/blob/1c5317531125e88f66bc14565823d374a903ef98/modules/apps/document-library/document-library-web/src/main/resources/META-INF/resources/document_library/js/DLManagementToolbarPropsTransformer.js#L236-L253)

**Review by ambrinchaudhary — APPROVED** [review]

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
https://http.cat/414

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1257401_3341

**Comment by liuxingye** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1317401_3935

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1317401_3935

**Comment by adolfopa** [comment]
ci:reevaluate:1327401_4534

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
The failures in LocalFile.DisplayPageTemplatesWithMapping#ViewTypesDuringCreation and LocalFile.WebContent#PreviewScheduledWebContentInWCD are not related to the changes in this PR.

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failure are not related to this PR, re-run it.

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
