### PR TITLE
LPS-163779 Create custom UI for pattern redirections

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-163779 no longer needed
- LPS-163779 create configuration jsp for redirect pattern
- LPS-163779 generate provider to get the patterns from configuration
- LPS-163779 Auto SF
- LPS-163779 show the current pattern on page
- LPS-163779 insert react component to show the patterns as 2 different rows
- LPS-163779 add scope pk variable to the display context to know the scoped group
- LPS-163779 get Redirect Pattern Data for react component
- LPS-163779 create command to update the patterns
- LPS-163779 update patterns on saving the configuration
- LPS-163779 do no autogenerate the UI for the RedirectPatternConfiguration
- LPS-163779 rename variable destination to destinationURL and change message of the pattern redirection description
- LPS-163779 rename variable  'source' to `pattern`
- LPS-163779 obtain the redirection map from the RedirectProvider
- LPS-163779 use the RedirectProvider to obtain the  getRedirectionPatternsMap
- LPS-163779 baseline
- LPS-163779 buildLang
- LPS-163779 Wordsmith

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa can you take a look to the last commit to make sure all it's ok? 
Becuase :  https://github.com/brianchandotcom/liferay-portal/pull/124071#issuecomment-1267155488

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
