### PR TITLE
LPS-192780 Wiki toolbar dissapears after search. 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-192780. 

It was working on **7.4 DXP U75**. I checked this version and this was the result of the Filter and order dropdown while search is active: 

Screenshot 2023-08-11 at 14 29 18

Now something must have changed in the Clay Management Toolbar component, that when the filter items are null it fails. As this is an empty dropdown, I decided to set it to null while search is active, so now that dropdown does not appear. 

**Master - default page:** 
Screenshot 2023-08-11 at 14 21 37

**Master - on Search:** 

Screenshot 2023-08-11 at 14 36 25

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
Due to the priority and having one approval, I'm going to forward this. Thanks @adolfopa

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
