### PR TITLE
LPS-177568 add LogCapture to avoid unnecessary warning logs 

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
**https://issues.liferay.com/browse/LPS-177568**

- LPS-177568 add LogCapture to avoid unnecessary warning logs on MB test
- LPS-177568 add LogCapture to avoid unnecessary warning logs on Wiki test

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
