### PR TITLE
LPS-182756 Create Dropdown menu for categories and the modal

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-182756

It's under FF LPS-84424

To test :
Create some Categories 
Go to Documents & Media
You can see a modal with the categories from the company

- LPS-182756 add categories dropdown element
- LPS-182756 create the category modal
- LPS-182756 buildLang

image
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failure is not related to this PR.

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
