### PR TITLE
LPS-130463 / LPS-124408 / LPS-129242 Add Google Cloud auto translations

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
@boton Can you confirm the last commit is what is needed?

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
@adolfopa I'll update some little things to work with errors. See #1766

**Pull request closed without merging**
