### PR TITLE
LPS-130402 Generate urlTitle on conflict when saving draft

### PR DESCRIPTION
**Pull request by adolfopa**
When saving or updating a draft, generate a fresh urlTitle if the one provided by the user is already in use.

Note that we only do this when autosaving drafts; if the user saves explicitly, and error should be signalled. Where doing this for drafts to prevent the user from losing the entry's contents.

### CODE REVIEW

**Comment by adolfopa** [comment]
@boton I'm sending back to the UI the value for the new urlTitle. The value is sent corrrectly, and the input value is set as well (double checked with the inspector), but for some reason the input shows the old value to the user. Can you take a look at that?

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Review by boton — COMMENTED** [review]
It's working for me, triple check.

**Before the update**
image

**After the update**
image

Only I have a doubt, do you want to update the URL when is configurated automatic, custom or both of them?

**Comment by adolfopa** [comment]
@boton I want to update it when saving a draft (custom or not). This is to prevent the autosave feature to fail, as users may lose data if they are used to rely on it. It is an ugly compromise, but at least we prevent data loss.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
