### PR TITLE
LPS-155521 DM - adapt uploader component to not be a YUI plugin

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Enable FF in `portal-ext.properties`:
```feature.flag.LPS-118829=true```

### Motivation

Currently the `upload.js` is a YUI plugin. This is not valid anymore as the "host" object (`DocumentLibrary.js`) is not a YUI component. Also, remove all YUI code from `upload.js` is a tedious work that will require lot of effort, so the idea with this pull was to adapt the uploader component to not be a YUI plugin but a simple YUI component so it can be used along with `DocumentLibrary.js`. For that, and because this is behind FF and the original uploader must exist for now, I created new `DocumentLibraryUploaderComponent.js` which is based on `upload.js`

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
From the backend point of view it looks OK

**Review by boton — APPROVED** [review]
LGTM.

I only add an inline comment about removing the `_onDataRequest` method I think after a little research that it is unused now. I'm only able to find some uses on [6.2.x](https://github.com/liferay/liferay-portal/blob/6.2.x/portal-web/docroot/html/portlet/document_library/search_resources.jsp#L147-L165).

I discover a bug trying to drop files on folders I create a new issue: https://issues.liferay.com/browse/LPS-118829 but applies to master too.

**Comment by Hanlf** [comment]
ci:test:document

**Comment by adolfopa** [comment]
@boton Is it ok if we forward this?

**Comment by boton** [comment]
I remove the function, rebase and push.

> @boton Is it ok if we forward this?

Yes for the frontend POV

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Manually test for uploading and moving files: Passed.
[Ran related document Poshi tests with ff enabled:](https://github.com/Hanlf/liferay-portal/pull/365) No regression found.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
