### PR TITLE
LPS-133836 Remove feature flag for translations

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
@austinchiang I've modified one of the test cases to remove the feature flag. Can you review the changes?

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by austinchiang** [comment]
LGTM

**Review by austinchiang — APPROVED** [review]

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
