### PR TITLE
LPS-114788 Allow admins to define max size limits based on mime type

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:document

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:document

**Comment by adolfopa** [comment]
ci:test:document

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:document

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
There is no "mime-type" error when you try to upload a file 
and it's the general size not the mimetype size
image

maybe is because when called `dlEditFileEntryDisplayContext.getMaximumUploadSize()` `_getMimeType` is null and the value is not linked to the mimeType (fileversion is null)

once saved, if updated the message is correct

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Fixed the issue in https://github.com/liferay-lima/liferay-portal/pull/2736/commits/956fd70838d934259c74fdbb7d15dec3b07816b2 and push-forced.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1327401_2547

**Comment by adolfopa** [comment]
ci:reevaluate:1327401_2547

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1297401_1768

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_1842

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1277401_1879

**Comment by adolfopa** [comment]
ci:reevaluate:1277401_1879

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_1847

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1327401_2636

**Comment by boton** [comment]
ci:forward

**Comment by liuxingye** [comment]
Resend this to BChan https://github.com/brianchandotcom/liferay-portal/pull/113900

/cc @adolfopa @boton

**Pull request closed without merging**
