### PR TITLE
LPS-160824 DM folders - dropdown items

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ealonso** [comment]
@ambrinchaudhary @adolfopa 😘

**Comment by adolfopa** [comment]
ci:reevaluate:1257401_4188

**Comment by ambrinchaudhary** [comment]
poshi errors are related, QA needs to update them as we changed some markup after adding the dropdown items. Please @liuxingye @Jeremy-Ch could you help us here?

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
Hi @ambrinchaudhary & @ealonso 

I realized checking this bug https://issues.liferay.com/browse/LPS-160876 that on this PR neither is no message when we disable the recycle bin on the site. So this is maybe an impedibug on the task.

And because we are still waiting the poshi test to be fixed, the error can be fixed previously.

https://user-images.githubusercontent.com/47524751/185923200-70e03f27-2372-4e1c-ae97-9c053d0a96a6.mp4

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci stable is stuck on the limbo of the CIs

**Comment by Jeremy-Ch** [comment]
Hi @ealonso @AliciaGarciaGarcia @ambrinchaudhary  Based on this pull request, I have fixed the Poshi tests. See https://github.com/liferay-lima/liferay-portal/pull/3394. I found an issue during the testing, I'm not sure if it is related to this pull request. Could you help to take a look? The main thing is that the permissions can not be saved, details see below video. thanks.

https://user-images.githubusercontent.com/48118285/185926545-d37eed89-0fed-4a6f-9aab-e3a6c027ca4c.mp4

**Comment by Jeremy-Ch** [comment]
I close this pull request, if the above issue is related to this pr, please fix it based on the new pull request (https://github.com/liferay-lima/liferay-portal/pull/3394), thanks.

**Comment by AliciaGarciaGarcia** [comment]
No, the error is not related with this PR.
The error seems to be on the original code, so when was migrated, the code still has the `error` of not showing the message.

**Pull request closed without merging**
