### PR TITLE
LPS-193726 Duplicate Asset type when trying to select a Related Asset

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-193726)

Ey, @Liferay-lima ! 😄 

I opened this bug and I’m sending you the fix. What do you think?	

## Proposed solution

Remove unnecessary add for Basic Document type because it is already include in dlFileEntryTypes.

## Test Scenario 1

1. Navigate to Content and Data
2. Add a web content
3. Go to Related Assets
4. Try to select an Asset type

## Result:
261562592-1649c51f-5016-4d69-b41e-0dcc4730dd9d

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]
It looks good. Thanks!

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
