### PR TITLE
LPS-205235 Add new param to hide the language selector in liferay-friendly-url:input

### PR DESCRIPTION
**Pull request by veroglez**
Hi guys!

In Echo team we are making improvements for the input localized according to this story https://liferay.atlassian.net/browse/LPS-200663. As a requirement of this story, sometimes we will need to hide the language selector from the localized input. For this reason a new parameters `languagesDropdownVisible` was added to the `liferay-ui:input-localized` taglib here https://github.com/liferay-frontend/liferay-portal/pull/3876/commits/44cf2e2bb774e5b1f50379f1e7843f384050a887. 

Therefore, now it's necessary to add this same parameter to the `liferay-friendly-url:input taglib` to hide the language selector of the Friendly URL field (since a localized input is used inside of this taglib).

Only this commit eac3e9c0af6597cf94874b1d9ff1a71e91b8c577 needs your review. Thanks in advanced! :slightly_smiling_face:

### CODE REVIEW

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Review by marcogalluzzi — APPROVED** [review]
Good work, thanks!

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:forward:force

**Pull request closed without merging**
