### PR TITLE
LPS-70835 Check if wiki page already exists before syncing

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-70835

Site templates use export/import to sync with deriving sites.  As sites can make changes themselves this can cause inconsistenciues in wiki when restoring elements from trash.  When restoring elements from trash, don't assume the site is in its original state.

Note that this doesn't affect staging, as Live cannot be changed directly.

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-70835.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
LGTM. I would only change the names of the variables to something more meaningful like:
* existingPage1 -> trashPage / removedPage / deletedPage
* existingPage2 -> existingPage / activePage

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
