### PR TITLE
LPS-200309 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-200309

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:online-editing

**Comment by boton** [comment]
ci:reevaluate:1297401_8565

**Comment by austinchiang** [comment]
ci:test:online-editing

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
