### PR TITLE
LPS-184122 Use google's linear time regex engine

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-184122 
 
 Step to reproduce:

1. Go to redirection> Patterns
2. Add a patterns with below parameters
3. Pattern: "("
4. Destination UR: "https://www.liferay.com"
5. Save

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
