### PR TITLE
LPS-164157 Cards in ItemSelector Descriptor

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
In order to allow customize the item selector cards allow users define their own cards view.

[LPS-164157](https://issues.liferay.com/browse/LPS-164157)

Proposed Solution
========
Creates two new methods on ItemDescriptor to allow us define the vertical card or the horizontal card

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The failures are not related to this PR, sent to Bchan here: https://github.com/brianchandotcom/liferay-portal/pull/123863

**Pull request closed without merging**
