### PR TITLE
LPS-134658 Display preview title like how facebook and twitter does

### PR DESCRIPTION
**Pull request by balazssk**
Hi @liferay-lima ,

I'd like to suggest this improvement so that opengraph previews look more like how facebook or twitter would show them. (They don't display the optional og:site_name)

Can you please review?
https://issues.liferay.com/browse/LPS-134658

Thanks,
Balázs

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
Hi @balazssk,

Thanks for the PR, but we have a problem with this PR we desynchronize the preview and the real generation of the OG title metatag, we are misleading the user about what will be posted on FB.

image

Sure that the preview looks like you want but the metatag is generated <meta property="og:title" content="Home - Liferay"> in the other way.

image


Maybe we plan some story/task to enable/disable this titleSuffix in the preview and the generated <title> and metatags.

**Comment by boton** [comment]
ci:stop

**Comment by kgolebiowski** [comment]
Hi @boton  and @balazssk,
Sorry for jumping in the conversation after the PR has already been closed, but I think was the initial creator of the support ticket and I just wanted to clarify is actually wrong here.

The problem with preview happens **only** when the "Use Custom Title" has been selected:

OpenGraph setting and preview

Above you can see that there is no site name in the custom title, and it's also gone from the actual value of _og:title_ tag:

Actual value

This means that the preview generated by the social platforms will not contain the site name (as they present only the _og:title_ parameter) which is not consistent with the preview generated in Liferay.

Thanks,
KG

**Comment by boton** [comment]
Sorry, @balazssk @kgolebiowski you are right, It failed for me with the default title and I didn't really understand the second one, I'm going to reopen the ticket and work on top of this PR.

**Comment by boton** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/2048.

**Pull request closed without merging**
