### PR TITLE
LPS-165760 / LPS-162327 Allow to select display page and minor fixes

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

This renames the navigation fragment, puts it in the "Menu" section, and adds the last piece we missed in display page support: configuring a display page template per content.

image

# How do I test this?

When editing an article, open the "Display Page Template" section in the left pane and configure a specific display page template. Once saved, try to access the article with its url (e.g. /k/folder/article-1). Make sure the display page is not marked as default.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
LGTM

my only question is that this should be under the FF - LPS-125653 because we can not create Display Pages without it.

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Good point. I'll push additional changes and re-request the review.

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Can you take a look at the last two commits? The first one restricts the item selector so that only articles can be selected; the other one applies the feature flag. Thanks!

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
