### PR TITLE
LPS-114865 Export for translation's Modal

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Please check permissions in https://github.com/liferay-lima/liferay-portal/pull/159/commits/ba5b5f7a028c75780d51b023a8117108707fe235 and https://github.com/liferay-lima/liferay-portal/pull/159/commits/0523cc1ad87c2b92f34f5e666962152f25e9f536. I just checked if it has the UPDATE permission but I'm not sure at all. 

Also, as it has been developed in the "journal" module... should someone from the Echo team reviiew this?

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
Update permissions are not needed.

**Pull request closed without merging**
