### PR TITLE
LPS-145474 Add new friendly URL for documents and media

### PR DESCRIPTION
**Pull request by adolfopa**
This PR adds a new "friendlier" friendly URL to documents and
media. This one is much simpler than the existing ones, including only
group name and document url title.

To avoid conflict with existing URLs, and to be consistent with
display pages URLs, we're using the "/d" prefix. So, these new URLs
will have this general shape:
```
/documents/d/{group}/{urlTitle}[?version={vsn}&t={timestamp}]
```
where the part between square brackets is optional.

Note that the tests add the friendly URL manually. This is so because
we are not adding those in the DM services; we're working on that atm
as well.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

Stopping and restarting due to ci-infrastructure bug

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Working as a charm

https://user-images.githubusercontent.com/47524751/153846316-5f6331aa-85d8-4102-8e41-463855b9ec26.mp4

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1267401_1735

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_1810

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_1810

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_1810

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:reevaluate:1297401_1792

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
