### PR TITLE
LPS-148618 Change code order to improve performance

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

This code order modification improves the performance if a Layout with a Message Boards portlet can be found.

Thank you and best regards,
István

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Should be ci issue, many builds were aborted, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
jobs were aborted, re-run it.

**Comment by adolfopa** [comment]
@robertoDiaz Can you take a look at this? Thanks!

**Review by robertoDiaz — COMMENTED** [review]
It seems that it is related with https://github.com/IstvanD/liferay-portal/commit/38ba230fd578aab4e8841b005c351c5bcd7d343c

In this commit we solved an issue related with the url creation because the local port (8080) was added to the url in some cases.

If changing the logic order doesn't break this again, I'm ok with this changes. You could check the steps in https://issues.liferay.com/browse/LPS-145948

Thanks!

**Comment by IstvanD** [comment]
Hi @robertoDiaz 

I checked the reproduction of https://issues.liferay.com/browse/LPS-145948.

The generated email does not seem to have the issue:

> hi<br /><br />
> 
> Liferay Message Boards<br />
> http://roberto.es/web/guest/home/-/message_boards/view_message/39718<br />
> <br />

**Review by robertoDiaz — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
