### PR TITLE
LPS-132310 Use same preview message across all previewers for consistency

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-132310

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-132310.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
Hi  @adolfopa // @Jeremy-Ch 

Looking at the failing test, maybe we have to change the literal on `DMDocument.macro` 

?

**Comment by Jeremy-Ch** [comment]
Hi @AliciaGarciaGarcia Thanks for your checking. You are right, we need to modify the literal for the message. But the current failing tests are for other reasons. We will fix them from another ticket. For this pr, I will change the literal on DMDocument.macro and forward this pull request manually. Thanks.

**Comment by Jeremy-Ch** [comment]
Sent this pull request to BChan manually, see https://github.com/brianchandotcom/liferay-portal/pull/131128

**Pull request closed without merging**
