### PR TITLE
LPS-165496 Remove suggestions from template preview

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

Remove suggestions from template preview.

# How do I test this?

From the admin widget:

1. Create a new kb template.
2. Select "View" in the template dropdown action.
3. Assert that no suggestions are displayed below the preview.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — CHANGES_REQUESTED** [review]
@adolfopa can you fix the SF?

I thin that is unused imports on the init.jsp

**Comment by adolfopa** [comment]
Fixed sf and push-force'd.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
