### PR TITLE
LPS-149415 DM drag and drop notifications

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-149415

We move the notification logic from back to front, now we have instant notifications instead of on the next reload.

When some files fail on the upload, we don't add them to the interface (front validation) or remove them from the UI (backend validation). If we have a backend error and DM and media are empty we recover the Empty State.

We fix the errors on drag and drop uploading https://issues.liferay.com/browse/LPS-149479 with this PR too.

#### When all file uploads are successful we add a reload button to the notification
image

#### If the number of fails is less than or equal to 2 we show error message details for each file
image

#### If the number of fails is greater than 2 we hide error message details
image

#### When some file uploads are successful and another fails we show 2 notifications (the successful one without reload):

image

Notice the lack of separation between notification. When https://github.com/liferay-frontend/liferay-portal/pull/2146 is merged it will be fixed.

image

### CODE REVIEW

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by boton** [comment]
@ambrinchaudhary I completely forgot this problem https://github.com/liferay-lima/liferay-portal/pull/2972/commits/71f0250cac674567eb785d74cddc59f17b949487 we are attaching new handlers on every drop but I don't found the way to remove it without break things. 

Now it does not duplicate the notification but we launch unnecessary events

**Comment by boton** [comment]
Rebased!

@ambrinchaudhary I'm removing handlers here 0c78b40 but I'm not sure at all If I'm doing something crazy

**Comment by boton** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
@boton Could you take a look the SF failure when you get a chance? Thanks
```     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: There should be an empty line before line '130', as we finished referencing variable 'fileSizeException', see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/missing_empty_line_check.markdown: ./modules/apps/upload/upload-web/src/main/java/com/liferay/upload/web/internal/MultipleUploadResponseHandler.java 130 (Checkstyle:MissingEmptyLineCheck)
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:435)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:281)
```

**Comment by boton** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Hey @boton, overall LGTM. I see this [commit](https://github.com/liferay-lima/liferay-portal/pull/2972/commits/ef367b4389e33ee1ce83eb07a62ec21672ca4395) and I'm not sure if you want to send it (as it says "only for test purposes"). Also, it needs a rebase.

**Comment by boton** [comment]
thanks for the catch @ambrinchaudhary I'm going to rebase it and fixup this commit

**Comment by boton** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The DMFileEntry#CanRevertToOriginal failure is a test fix: [LPS-152901](https://issues.liferay.com/browse/LPS-152901)

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
