### PR TITLE
LPS-150762 Add option to force auto tagging on update

### PR DESCRIPTION
**Pull request by adolfopa**
This contains all backend changes necessary to force auto tagging on update. Missing things:

1. Lang keys.
2. I've added some placeholder markup so that this can be tested. You'll need to replace that with new markup that satisfies the design.

/cc @boton @ambrinchaudhary

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Updated keys and markup. 
Screenshot 2022-04-04 at 12 27 17

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_1464

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1327401_3371

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Reviewing the POSHI failures...

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Thanks @liuxingye. The DM failure looks legit; rerunning to see if the WC one disappears (shouldn't be caused by these changes).

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Hi @adolfopa, 
After re-run the tests, the external video [issue](https://github.com/liferay-lima/liferay-portal/pull/2901#issuecomment-1091004885) still occurs. I've summarized the steps from the POSHI test of LocalFile.DMVideoShortcut#AddYouTubeToWCViaItemSelector.

**Comment by AliciaGarciaGarcia** [comment]
I'll take a look

**Comment by AliciaGarciaGarcia** [comment]
as @adolfopa requested I added the feature.flag.LPS-150762 FF

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
@AliciaGarciaGarcia Thanks for looking into the issues.

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
