### PR TITLE
LPS-128746 Use modified date as publish date in FileEntryInfoItemFieldValuesProvider

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

Currently the publish date of a given document is set as lastPublishDate, this is not a real publish date, since this field is related with Staging only.

I have updated this field, so we will use the modifiedDate as the publishDate of a document.

Also I have updated BlogsEntryInfoItemFieldValuesProvider, FileEntryInfoItemFieldValuesProvider and JournalArticleInfoItemFieldValuesProviderto add create and modified date.

**How to test it**

I have added integration tests for the changes.

/cc @4lejandrito I think you worked a lot with the info framework, so maybe you can take a look to the changes (maybe this doesn't make sense)

/cc @adolfopa this is the pull I promise to you in our Slack conversation.

/cc @AliciaGarciaGarcia I don't have any particular comment to you, but, how are you doing?

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @cgoncas,

I think the changes are good, I can't think of a better way to do this at the moment. 

However it makes me sad that we have to repeat the same logic for every info item (blogs, files, articles...). If I were a customer trying to add my own entity I would not now which fields to declare. 

I think Echo & Jorge Ferrer would find this pull interesting. It may help them to come up with a more generic way in the future.

If this is urgent for your team I would say let's forward it and we can show it to Echo afterwards.

**Comment by cgoncas** [comment]
Hey @4lejandrito !!

As you say, we need to find a fast solution, because we need to finish this new feature for GA1 :(.

But I totally agree with you about show it to Echo and Jorge, and find a better pattern to implement it.

Thanks!!

**Comment by AliciaGarciaGarcia** [comment]
hey @cgoncas  :D



I'm doing ok 😄

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1087401_6996

**Comment by cgoncas** [comment]
ci:reevaluate:1087401_6996

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@JorgeFerrer, @liferay-echo,

> Hi @cgoncas,
> 
> I think the changes are good. I can't think of a better way to do this at the moment.
> 
> However it makes me sad that we have to repeat the same logic for every info item (blogs, files, articles...). If I were a customer trying to add my own entity I would not know which fields to declare.
> 
> I think Echo & Jorge Ferrer would find this pull interesting. It may help them to come up with a more generic way in the future.
> 
> If this is urgent for your team I would say let's forward it and we can show it to Echo afterwards.

**Comment by JorgeFerrer** [comment]
Hey @cgoncas ,
I fear that it may be confusing and cause bugs in the future to return the modifiedDate for a field called publishDate. 
I understand your point about the lastPublishDate not being so relevant since it's related to staging. However instead of changing its meaning, I think it's more clear to create a new field called modifiedDate and leverage that one (ignoring publishDate and just leaving it for backwards compatibility).

What do you think?

**Comment by cgoncas** [comment]
Hey @JorgeFerrer !!

This decision was made with the Lima Team in https://liferay.slack.com/archives/CLD39UKM5/p1614790986048100. So if they want to use another approach, I think it is ok.

For me to find this field always empty (even when this document was published), was really confusing too.

The publishDate is also used in WebContent an its value it is not related with Staging, so I think use lastPublishDate could be even more confusing.

Thanks!!

**Comment by JorgeFerrer** [comment]
Got it. If we are giving the "publishDate" the same meaning than what we are giving it for Web Content (or as similar as possible), then the change does make sense to me.

**Pull request closed without merging**
