### PR TITLE
LPS-173353 Configuration Listener is not updated after update the configuration

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
As the Figma says I put the configuration on the system level

if Company or group scope is needed, more work is needed too

- LPS-173353 put on system scope
- LPS-173353 id company no longer needed
- LPS-173353 It needs to be immediate for now since it is registering scheduler entries in its activate method
- LPS-173353 implements ConfigurationModelListener on the MessageListener to update the scheduler

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@marcogalluzzi I'll talk with maria about it. thanks pointing at it

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia The code looks ok, but it should be possible to support company scoped message listeners. You need to use a ManagedService to update the configuration (instead of the configurationProvider). See `CacheControlConfigurationManagedServiceFactory` as an example.

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa 

i have several questions about the messageListener. When we create the trigger for them we put an interval of time on the class that is created, and I'm not sure how to change this time for each scope/company/group 

In other question, the original ticket asked to put it on the system. I remember to talk about it, but  can not recall about what.

I'll contact you later

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
