### PR TITLE
LPS-102564 Show applications for each available category

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @boton 

The main thing that needs to be done here is to create a new Js component to handle the cards click events. Right now, users need to click on the link to navigate to each application; we should change things so that a click anywhere in the cards has that same effect.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
See #266.

**Pull request closed without merging**
