### PR TITLE
LPS-183052 Add tests to check DOWNLOAD permission

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-183052

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @adolfopa 
The failure [pmd-jdk8/0/0](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/494993//consoleText) should be related to this PR, could you take a look?
```
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-test-batch.xml:6926: 2 PMD violation(s) were found.
     [echo] 
     [echo] PMD VIOLATION: /opt/dev/projects/github/liferay-portal/modules/apps/document-library/document-library-test/src/testIntegration/java/com/liferay/document/library/service/test/DLFileEntryServiceTest.java:475 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)
     [echo] 
     [echo] PMD VIOLATION: /opt/dev/projects/github/liferay-portal/modules/apps/document-library/document-library-test/src/testIntegration/java/com/liferay/document/library/service/test/DLFileEntryServiceTest.java:498 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)
```

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
LGTM

**Comment by austinchiang** [comment]
Not sure if this requires backend review; won't forward for now

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
