### PR TITLE
LPS-137761 Use ballooneditor on contentEditor

### PR DESCRIPTION
**Pull request by diegonvs**
Forwarded from https://github.com/liferay-frontend/liferay-portal/pull/1663

## How to reproduce my changes:

1. Inside your `portal-ext.properties`, set ballooneditor as a default editor:

`editor.wysiwyg.portal-web.docroot.html.portlet.blogs.edit_entry.jsp=ballooneditor`

2. Create a file named `com.liferay.frontend.editor.ckeditor.web.internal.configuration.FFBalloonEditorConfiguration.config` on osgi/configs folder

3. Inside the content, set `enable="true"` and then start catalina again

4. Be sure you already have [liferay-ckeditor@4.16.2-liferay.4 ](https://github.com/brianchandotcom/liferay-portal/pull/110392) installed

5. Go to Blogs -> New Blogs Entry and 🎉 

## Do you want to see in action? 📹

Open https://drive.google.com/file/d/1Uk236EPvrMTVfmRRQYEF2Cy0WnA6mX10/view?usp=sharing 

Screen Shot 2021-11-25 at 17 11 07 😭

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The error of lpkg-base-jdk8/0/0 is a known issue, not related to this PR.
The errors of BalloonEditor tests only occur with these commits, which belong to Frontend,  @zhangyan0701 will take a look

**Comment by zhangyan0701** [comment]
Hi @diegonvs 

The BalloonEditor tests are using our frontend-editor-ckeditor-sample-web to test, but all of them failed because the sample portlet is empty. 

after2

So we need to enable balloon editor by adding the config file to make the sample work as well? Is it intended?

**Comment by markocikos** [comment]
See followup in https://github.com/liferay-lima/liferay-portal/pull/2563

**Comment by markocikos** [comment]
ci:close

**Pull request closed without merging**
