### PR TITLE
LPS-166761 Make xpaths more resilient

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:document

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Thanks @AliciaGarciaGarcia this should be a test issue then. I'm pushing up some changes now

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:test:document

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Sent to BChan https://github.com/brianchandotcom/liferay-portal/pull/126041

**Pull request closed without merging**
