### PR TITLE
LPS-157318 Improve accessibility in Rating widget

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Can you review this pull request, please?

You can see the list of accessibility improvements in [LPS-157318](https://issues.liferay.com/browse/LPS-157318).

Thanks.

Regards.

/cc @robertoDiaz

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@antonio-ortega Can you take a look at the test failures? Thanks!

**Comment by ambrinchaudhary** [comment]
Seems like some ratings tests broke, I'm going to take a look at them and send a new pull. 

Thanks @antonio-ortega for your work here.

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Just a question @antonio-ortega, you made accesibility changes only for the "selectedStars" type, don't the other rating's types have same issues? We have RatingsLike, RatingsStackedStars, RatingsStars and RatingsThumbs.

**Comment by antonio-ortega** [comment]
Hi @ambrinchaudhary ,

Thanks for taking a look into this. 

I only made changes in `selectedStars` because that was the place where it was reported by our customers. I'm actually not totally sure how to test the rest of Rating options you mentioned since I don't have a wide knowledge about this widget.

In any case, if I'm right the only one showing a dropdrown is `selectedStarts`, and 5 out of the 6 accessibility issues reported are related to that dropdown.

The other one is to add some description to buttons, what make sense to add to every case.

Thanks.

**Comment by ambrinchaudhary** [comment]
Fixes sent to https://github.com/liferay-lima/liferay-portal/pull/3265

**Pull request closed without merging**
