### PR TITLE
LPD-15746 kb lock show modal

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
### How to test it: 

1. Create a new kb article with current user (Test)
2. Access to edit the article but don't save it. It will be locked until it is saved or canceled. 
3. Create a different user with admin role. 
4. Impersonate user
5. Go to Knowledge Base and try to edit the created kb article (or Expire, or delete it)

Screenshot 2024-02-01 at 22 31 51

### Notes: 
I created separate tasks for hiding the toast message(https://liferay.atlassian.net/browse/LPD-16389) and checking other actions(https://liferay.atlassian.net/browse/LPD-16388)

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by marcogalluzzi — APPROVED** [review]
From Backend point of view :+1:

**Review by boton — APPROVED** [review]
LGTM!

Tested and working, nice and elegant job @ambrinchaudhary

**Comment by boton** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1367401_5044

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
Hi @ambrinchaudhary the unique failures don't seem to be related. We can safely force forwarding.

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Pull request closed without merging**
