### PR TITLE
LPS-119815 Remove category name from control bar

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Hey @austinchiang 

These changes break some of the tests, as they expect the folder/category name to be displayed in the top bar, but now the expected behaviour is to *not* show the folder name (only the app. name).

Can you guys update the poshi tests?

Thanks!

**Comment by liuxingye** [comment]
Reviewing the POSHI failure...

**Comment by liuxingye** [comment]
ci:test:bundle

**Comment by liuxingye** [comment]
ci:test:bundle

**Comment by liuxingye** [comment]
ci:stop

**Comment by liuxingye** [comment]
Hi @adolfopa I've updated poshi tests and resend a new pull, see https://github.com/liferay-lima/liferay-portal/pull/732

**Pull request closed without merging**
