### PR TITLE
[Technical Support] LPS-123305 Actions menu is duplicated

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi,
I am forwarding @robertoDiaz solution. Please review it.
Thank you

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:test:sf

**Comment by jpince** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
