### PR TITLE
LPD-35009 Fix failures in fileEntry.spec.ts @LPD-29609 Upload multiple file

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi Team,

This is: https://liferay.atlassian.net/browse/LPD-35009, trying to fix test failure in document-library-web/fileEntry.spec.ts.

Failed tests: LPD-29609 Error uploading multiples files with custom document type, LPD-16313 Show icon in the content admin and content editor

Added clickAndExpectToBeVisible, for this.page.getByRole('button', {name: 'Document Type'}), which the ci:test could not find.

Locally is passing

image

### CODE REVIEW

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Review by adolfopa — APPROVED** [review]

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
changed the size of the picture to less than 1KB.

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by jkappler** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:sf

**Comment by gergelyszalay** [comment]
ci:test:content-management-playwright

**Review by DiegoHu97 — APPROVED** [review]
LGTM!

**Comment by DiegoHu97** [comment]
ci:forward

**Pull request closed without merging**
