### PR TITLE
LPS-156658 Keep file entry type permissions in sync with its ddm structure

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @matthiasblaesing,

I've added a couple of commits on top of your changes. These are basically variable renames and other minor changes so that the PR conforms to our coding conventions.

Can you take a look at my changes to make sure everything is ok?

Thanks!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by matthiasblaesing** [comment]
@adolfopa I had a look at the updates and they look like good cleanups and optimizations. They look sane. I build from source, did a manual test and verified, that at least the creation and modification code paths work correctly. I retraced the steps to reproduce my issue and found it fixed. The staged workflow also still works.

Thank you.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by adolfopa** [comment]
Thanks a lot @matthiasblaesing. After @AliciaGarciaGarcia reviews and approves it, this should be ready to forward.

We really appreciate your contribution; the code was very good :-) Thanks!

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failures are not related to this PR, sent it to BChan: https://github.com/brianchandotcom/liferay-portal/pull/125019

**Comment by Hanlf** [comment]
Hi @adolfopa modules/apps/document-library/document-library-service/bnd.bnd has some conflicts with Bchan's upstream, so I closed https://github.com/brianchandotcom/liferay-portal/pull/125019. Could you please resolve the conflict, thanks!

**Comment by adolfopa** [comment]
Resolved conflicts in bnd.bnd and push-force'd. No other changes.

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The above failures are not related to this PR, sent it to BChan: https://github.com/brianchandotcom/liferay-portal/pull/125165

**Pull request closed without merging**
