### PR TITLE
LPS-135908 Look into portlet preferences to get where the portlet is used

### PR DESCRIPTION
**Pull request by ealonso**
Hey @adolfopa,

I've used portlet preferences to get where the portlet is used instead of a new method in FragmentEntryLink service, please let me know if it is enough for you. I've tested the issue (https://issues.liferay.com/browse/LPS-135908) following the description steps and it is working fine.

Resend from: https://github.com/liferay-echo/liferay-portal/pull/6703

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
