### PR TITLE
LPS-158064 KB Folder Navigation interaction with the Product Menu

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
There is one think I don't know how to fix: on reload when the product menu is closed, there is a css transition because the Vertical Bar should be open. I have no way to add the "expanded" class before the rendering (there is no way in backend to know if PM is open or closed), so I'm checking this in js and that is why the transition is triggered.  -> SOLVED.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — COMMENTED** [review]
> There is one think I don't know how to fix: on reload when the product menu is closed, there is a css transition because the Vretical Bar should be open. I have no way to add the "expanded" class before the rendering (there is no way in backend to know if PM is open or closed), so I'm checking this in js and that is why the transition is triggered.

After some research, I think I found a way to get the `open/closed` of the product menu.
[Here](https://github.com/liferay/liferay-portal/blob/b7336b16a8ac84055c75e8a8b23aa7507174a84a/modules/apps/product-navigation/product-navigation-product-menu-theme-contributor/src/main/java/com/liferay/product/navigation/product/menu/theme/contributor/internal/template/ProductMenuTemplateContextContributor.java#L55-L62) are some logic to add the open classes. Do you think it could work?

I think is time to add some proptype validation on [VerticalBar.js](https://github.com/liferay-lima/liferay-portal/pull/3323/files#diff-45b0d72fb5243fdfae799e54279454a7b2b726dd732a71f1953849b2223d996a). We can add it in a separate task if you prefer.

**Comment by ambrinchaudhary** [comment]
> > There is one think I don't know how to fix: on reload when the product menu is closed, there is a css transition because the Vretical Bar should be open. I have no way to add the "expanded" class before the rendering (there is no way in backend to know if PM is open or closed), so I'm checking this in js and that is why the transition is triggered.
> 
> After some research, I think I found a way to get the `open/closed` of the product menu. [Here](https://github.com/liferay/liferay-portal/blob/b7336b16a8ac84055c75e8a8b23aa7507174a84a/modules/apps/product-navigation/product-navigation-product-menu-theme-contributor/src/main/java/com/liferay/product/navigation/product/menu/theme/contributor/internal/template/ProductMenuTemplateContextContributor.java#L55-L62) are some logic to add the open classes. Do you think it could work?

That is exactly what @AliciaGarciaGarcia pointed but was not working for me, it was returning true every time... I'll try again, because based on that code should work. 

> I think is time to add some proptype validation on [VerticalBar.js](https://github.com/liferay-lima/liferay-portal/pull/3323/files#diff-45b0d72fb5243fdfae799e54279454a7b2b726dd732a71f1953849b2223d996a). We can add it in a separate task if you prefer.

Sure, I can add it in this pull. Thanks.

**Comment by boton** [comment]
> That is exactly what @AliciaGarciaGarcia pointed but was not working for me, it was returning true every time... I'll try again, because based on that code should work.

I think that the expected return values are string `open/closed`, for example [checking for open](https://github.com/liferay/liferay-portal/blob/b7336b16a8ac84055c75e8a8b23aa7507174a84a/modules/apps/product-navigation/product-navigation-product-menu-theme-contributor/src/main/java/com/liferay/product/navigation/product/menu/theme/contributor/internal/template/ProductMenuTemplateContextContributor.java#L60) and [set the default closed](https://github.com/liferay/liferay-portal/blob/b7336b16a8ac84055c75e8a8b23aa7507174a84a/modules/apps/product-navigation/product-navigation-product-menu-theme-contributor/src/main/java/com/liferay/product/navigation/product/menu/theme/contributor/internal/template/ProductMenuTemplateContextContributor.java#L58) value.

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
It is checked and updated with some changes in the navigation logic. 

@ambrinchaudhary can you review the changes, please?

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Sorry for creating a new [pull](https://github.com/liferay-lima/liferay-portal/pull/3345), I was having problems downloading this branch in my local.

**Pull request closed without merging**
