### PR TITLE
[NOT MERGE] LPS-123575 Video selector in CKEditor | master only

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
@4lejandrito please add this commits on top of your work

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1086.

**Pull request closed without merging**
