### PR TITLE
LPS-187934/ LPS-187938 Add configuration to limit copy batch size

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-187938

Screenshot 2023-06-19 at 09 36 06

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
