### PR TITLE
LPS-182018 Ratings from API

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Currently we have this values: 
0 -> no vote 
0.2 -> 1 star
0.4 -> 2 stars
0.6 -> 3 stars
0.8 -> 4 stars
1 -> 5 stars

From the UI only those values can be selected. But from the API you could vote from 0 to 1. So 0.5 rating should be valid, and now it is translated to 3 stars. 
See https://liferay.atlassian.net/browse/LPS-182018 for more details.

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
It works correctly when we have values with one decimal 👍

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1277401_10342

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
