### PR TITLE
LPS-131706 Upgrade Image table to include correct companyId

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
@achaparro please take a look at the "Add upgrade process" commit.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @adolfopa, @epgarcia,

The upgrade change makes total sense. It will work for DB Partition environments too because in those cases we execute the upgrade once per schema and we will get the proper companyIds in every case.

Thanks!

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The three Fragments tests failure will be fixed under [LPS-134824](https://issues.liferay.com/browse/LPS-134824).
The PortalSmokeUpgrade failures are caused by [LPS-134610](https://issues.liferay.com/browse/LPS-134610).
The failure of `com.liferay.document.library.convert.test.DocumentLibraryConvertProcessTest` is caused by [LPS-134095](https://issues.liferay.com/browse/LPS-134095)
The failure of `com.liferay.document.library.search.test.DLFileEntryIndexerIndexedFieldsTest.testIndexedFields` seems a flaky.

In addition, relevant personnel have been contacted to solve the first three failures.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The unique failure about `com.liferay.document.library.convert.test.DocumentLibraryConvertProcessTest.testMigrateDLWhenFileEntryEmpty` is not related to this PR, see [LPS-134095](https://issues.liferay.com/browse/LPS-134095).

**Review by AliciaGarciaGarcia — APPROVED** [review]
I'm not sure about the commit of the upgrade on d0fb0a3463918eca5775f9b5f6e28b981f4da487 cause I usually see only 2 actions on a upgrade, but if you thinks thats ok > LGTM

**Comment by adolfopa** [comment]
As this creates a new app, we need to create a new a qa ticket and review the app.bnd before forwarding. I've asked for information; I'll keep this PR up to date with the details.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
After further testing, this upgrade looks fine. This is ready for Brian.

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failures are not related to this PR.
The failures about modules-integration-mysql57-jdk8/0 also happened in other jobs: [LRCI-2354](https://issues.liferay.com/browse/LRCI-2354).
DatabasePartitioning#AddNewCompany is a fluke: [LPS-135932](https://issues.liferay.com/browse/LPS-135932).

**Comment by Hanlf** [comment]
Resend it to BChan here: https://github.com/brianchandotcom/liferay-portal/pull/104550

**Pull request closed without merging**
