### PR TITLE
LPS-137143

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Lima Team,

This is a follow-up pull request to https://github.com/liferay-lima/liferay-portal/pull/2253. It turns out the fix did not work if the user switches between the Asset Library tab and the Site tab. See the [video](https://issues.liferay.com/secure/attachment/422773/LPS-137143_Fail.mp4) on [LPS-137143](https://issues.liferay.com/browse/LPS-137143) for more details.

The reason for this is that the `scopeGroupType` parameter wasn't being propagated in the request when the user switches between the tabs.

https://issues.liferay.com/browse/LPS-137143

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Pull request closed without merging**
