### PR TITLE
LPS-168587 | master

### PR DESCRIPTION
**Pull request by sontruongces**
Hi team,

This is the fix for the [LPS-168587](https://issues.liferay.com/browse/LPS-168587), the original has passed my review at sontruongces#70. Please help me to review it and give feedback.

Thanks!
cc:@ces-binhtran

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
This change is OK. However there is a test failing related to the bundle version of the KB API. I would rebase with last master and update the bundle version afterwards.

**Comment by ces-binhtran** [comment]
ci:test:relevant

**Comment by ces-binhtran** [comment]
ci:test:stable

**Comment by ces-binhtran** [comment]
Thanks @marcogalluzzi, I updated the change.

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
