### PR TITLE
LPS-158794 do not let no user or not permission  download

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-158794 id no user, throw exception
- LPS-158794 check view permissions for user

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translations

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translation

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translation

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translation

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translation

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
