### PR TITLE
LPS-165650 Restrict navigation to specific folder in repository browser tag

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

In some cases, it is necessary to use a specific folder in a repository as the root folder. This PR adds a new `folderId` attribute for that purpose. If a value is provided, that folder will be used as root folder, and anything above it will not be visible.

# How to test this?

First, you need to add the tag to a page. For example replace the contents `blogs-web/*/view_images.jsp` with this:
```
<liferay-document-library:repository-browser folderId="<%= folderId %>" />
```
where `folderId` is an existing folder in Documents & Media (you may need to create sample folders and documents).

After doing that, go to Blogs > Images and verify that you can only navigate inside the folder you specified.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failed backend tests are not related to this pull request. They will be fixed on https://issues.liferay.com/browse/LPS-165793. Run the tests one more time.

- [com.liferay.document.library.service.test.DLFileEntryTypeFinderTest.testFilterCountByKeywordsAsPowerUser](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/71504//testReport/com.liferay.document.library.service.test/DLFileEntryTypeFinderTest/testFilterCountByKeywordsAsPowerUser)
- [com.liferay.document.library.service.test.DLFileEntryTypeFinderTest.testFilterFindByKeywordsAsPowerUser](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/71504//testReport/com.liferay.document.library.service.test/DLFileEntryTypeFinderTest/testFilterFindByKeywordsAsPowerUser)

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]
It looks good

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa 
semantic versioning failure relevant to this PR

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
