### PR TITLE
LPS-115230 Apply Builder Pattern in Info Framework (Resent after rebasing Tuesday)

### PR DESCRIPTION
**Pull request by JorgeFerrer**
@4lejandrito @adolfopa

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Resent as https://github.com/liferay-lima/liferay-portal/pull/261

**Pull request closed without merging**
