### PR TITLE
LPS 145475.delete deprecated methods

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-145475 Add url title to `add` and `update` methods
- LPS-145475 Update tests
- LPS-145475 Build service
- LPS-145475 delete deprecated methods
- LPS-145475 Build Service
- LPS-145475 Semver

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
remove the deprecated methods because : 
[LPS-145475.delete_deprecated_methods](https://github.com/brianchandotcom/liferay-portal/pull/113839#issuecomment-1049735908)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
not related to this PR, re-run.

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
