### PR TITLE
LPS-179847 Hide User Agent field on Redirect Patterns behind FF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Without FF**

Screenshot 2023-03-27 at 13 31 23

**With FF (feature.flag.LPS-175850=true)**

Screenshot 2023-03-27 at 13 33 55

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
