### PR TITLE
LPS-166408: fix typo ':' to '='

### PR DESCRIPTION
**Pull request by kristofloneck**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by adolfopa** [comment]
@kristofloneck There are two related tests failing. Can you take a look at them?

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by kristofloneck** [comment]
Condsidering it is just a typo change I don't think it should be break any test.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
I updated the Poshi tests. See the new pull request: https://github.com/liferay-lima/liferay-portal/pull/3660

**Pull request closed without merging**
