### PR TITLE
LPS-131054 Consume stdin/stderr to prevent processes from blocking

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
Test failing looks like related to the pr?

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Commerce failure is unrelated. Will send directly to BChan.

**Comment by austinchiang** [comment]
Resent in https://github.com/brianchandotcom/liferay-portal/pull/108035

**Pull request closed without merging**
