### PR TITLE
LPS-159876 Use CDATA when serializing url title map

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — APPROVED** [review]
I did not added the test
this assert
```
		Assert.assertEquals(
			"%C3%A9%C3%B6%C5%91",
			_friendlyURLNormalizerImpl.normalizeWithEncoding("éöő"));
```
To _testNormalizePercentageWithEncoding_ because maybe you wanted to test the `getXml` or another method

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1317401_4634

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1317401_4634

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
@adolfopa @AliciaGarciaGarcia resent in https://github.com/liferay-lima/liferay-portal/pull/3382 with baseline

**Pull request closed without merging**
