### PR TITLE
LPS-122267 LPS-132445 Add new methods to test class

### PR DESCRIPTION
**Pull request by vicnate5**
@AliciaGarciaGarcia

### CODE REVIEW

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The failure of PortalSmokeUpgrade is comment failure, see [LPS-132449](https://issues.liferay.com/browse/LPS-132449).

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
the fix code was added on 4251b0e32e9fb59c42470c4110470c0b8d894d5a

**Pull request closed without merging**
