### PR TITLE
LPS-148380 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-148380

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by boton** [comment]
We need to wait until exporting multiple experiences on multiple pages is ready and remove it at one time. /cc @adolfopa

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
ci:reevaluate:1267401_2565

**Comment by austinchiang** [comment]
@adolfopa @boton the translations app doesn't compile properly with the changes made in this pull now. I checked locally as well. Can you take a look?

**Pull request closed without merging**
