### PR TITLE
LPS-188918 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-188918
https://liferay.atlassian.net/browse/LPS-193083

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
