### PR TITLE
LPS-185879 Preview and thumbnails are not override when checkin with “Keep Current Version Number

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-185879

Steps to reproduce

It happens to with video (and I suppose that with audio/other preview)

1. Go to Content & Media > Documents and Media > “+” > File Upload
2. Select 1 PDF File which has Thumbnail and Publish
3. Select (⋮) button on it, and click “Checkout”
4. Select (⋮) button again and click “Edit”
5. Select PDF File (which is not include same Thumbnail with step3) and save
6. Note: Thumbnail is changed to New picture
7. Select (⋮) button, and click “Checkin”
8. Select “Keep Current Version Number” and Save

It happened that previews are no clean after the deletion of the fileVersion

The previous PR liferay-lima/liferay-portal/pull/4349 caused https://issues.liferay.com/browse/LPS-186487  

The reason seemed to be a race condition that deleted the resources of the Folder (on this case, the permissions) before the files that were on the folder, and when some files needed to be checked (on the model listener) the error was thrown.
This should be solved by : 
- LPS-185879 move the delete resources method after because some dependencies should need them to removal

- LPS-185879 when you delete a file entry that is a PWC make a cleanup of the previous trusted version of the file to make it new previews and thumbnails with the content con the correct version
- LPS-185879 remove the dlFileVersionPreview when removing the dlFileVersion
- LPS-185879 extract method
- LPS-185879 clean up the deleted file version previews and thumbnails
- LPS-185879 check null to prevent NPE when trying to delete the same file 2 times
- LPS-185879 move the delete resources method after because some dependencies should need them to removal

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:system

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa 
I reordered the calls made on _com.liferay.portlet.documentlibrary.service.impl.DLFolderLocalServiceImpl#deleteFolderDependencies_ so the  __resourceLocalService.deleteResource_ be after the  __dlFileEntryLocalService.deleteFileEntries_ 

In your opinion, Do you think there was a reason of the previous order?

Thanks!

**Comment by Hanlf** [comment]
Hi @AliciaGarciaGarcia 
not sure if this [modules-semantic-versioning-jdk8/0/0 failure](https://testray.liferay.com/reports/production/logs/2023-06/test-1-39/test-portal-acceptance-pullrequest(master)/5143/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0) is related to this PR, I don't see it happening on other PRs, could you take a look? 
Except for this failure, other failures are not related to this PR. And the Poshi tests run as expected on the ci:test:relevant job.
```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/document-library/document-library-api] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 22.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:82)
     [exec]         at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.junit.runners.Suite.runChild(Suite.java:128)
     [exec]         at org.junit.runners.Suite.runChild(Suite.java:27)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
     [exec]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec]         at java.lang.Thread.run(Thread.java:745)
```

**Comment by AliciaGarciaGarcia** [comment]
Thanks @Hanlf 
I did not make any change on /apps/document-library/document-library-api, and on this PR no change version should be necessary,  but I will take a look. maybe some change on master 🤷🏻‍♀️

**Comment by AliciaGarciaGarcia** [comment]
@Hanlf 

The semver error is caused by LPS-184965  

I will send a PR with this but on a different PR :)

**Comment by Hanlf** [comment]
@AliciaGarciaGarcia Thanks for taking care of it

**Comment by AliciaGarciaGarcia** [comment]
I think that CI is stuck...

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
