### PR TITLE
LPS-126764 Clean old DDM files

### PR DESCRIPTION
**Pull request by boton**
Delete unused files of DDM after moving to data engine.

I have deleted a CSS file and another JSP file thinking that they are no longer used but I would like someone to review them as well so that you would take a look at if there are really leftovers and the rest of the files in the DDM folder.

I have seen that some files are in use I do not know if it would make sense to rename it.

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
Hey @boton not reviewing the code since it's still in draft, just a suggestion about improving the commit and title descriptions. Reading current ones what first comes tu my mind is: What is no longer needed? Why?

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @boton ,

With the deletion of ddm_form_builder.jsp  the DLEditFileEntryTypeDisplayContext.java is not called and not used, so it's orphan code. 
orphan

**Comment by boton** [comment]
thanks, @AliciaGarciaGarcia for removing this orphan java file. 

What do you think guys about rename DDM files/folder to DE or something? Maybe it's doesn't make sense, or maybe we can create another task for it.

/cc @adolfopa @4lejandrito @AliciaGarciaGarcia

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by 4lejandrito — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
