### PR TITLE
LPS-125733 Asset Publisher scrolls up when clicking on Info button on further documents

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by boton** [comment]
Reading this https://github.com/liferay-frontend/liferay-portal/pull/726 I think that is good but I prefer that @ambrinchaudhary take a look if is possible :D

**Review by boton — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
Thank you very much @IstvanD, that is a better approach indeed. There is a small SF issue so I've sent another pull here: https://github.com/liferay-lima/liferay-portal/pull/1469

**Pull request closed without merging**
