### PR TITLE
LPS 124363

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
Failures look unrelated. However, upstream is not synced with BChan's origin so we should wait till that happens before running forward again

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1227.

**Pull request closed without merging**
