### PR TITLE
LPS-177568 add LogCapture on the creation of files that can be user poi libraries because warn message is thrown on test

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
After solving some issues with the warm message, more issues are shown.

- LPS-177568 move the log capture to the inner method
- LPS-177568 add LogCapture on the creation of files that can be user poi libraries because warn message is thrown on test

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:log

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1317401_7549

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
