### PR TITLE
LPS-121879 Migrate v2 management toolbar usages in item-selector-taglib

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Depends on** https://github.com/liferay-lima/liferay-portal/pull/1525

**Test plan:** 
1. Go to Blogs and create a blog entry
2. On the cover image, click on "Select Image" button
3. A modal is opened with the management toolbar

/cc @markocikos @julien @jonmak08

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Hey @ambrinchaudhary everything seems to work fine but the creation menu:

image

I've rebased the pr with today's master to test it. Could you please take a look?

Thx!

**Comment by ambrinchaudhary** [comment]
Hi @carloslancha, 
that is fixed in pull https://github.com/liferay-lima/liferay-portal/pull/1525/files#diff-65ea047035d6a3e49539908bf602aed4f63eb7a6b7e02ea00e3298f5e09da3b6R106. Would you be so kind to check that pull first, as it depends on other pulls like this one? 
Thanks a lot.

**Comment by carloslancha** [comment]
Sure @ambrinchaudhary 

Could you please add a comment or edit the description of every open pr that depends on that one so we can track when they're ready to be reviewed/forwared? Thx!

**Comment by ambrinchaudhary** [comment]
> Sure @ambrinchaudhary
> 
> Could you please add a comment or edit the description of every open pr that depends on that one so we can track when they're ready to be reviewed/forwared? Thx!

Done. For now we have detected this pull and this other one https://github.com/liferay-lima/liferay-portal/pull/1536 as dependencies.

**Review by carloslancha — APPROVED** [review]
Reviewed on top of https://github.com/liferay-lima/liferay-portal/pull/1525. LGTM. Thx!

**Comment by carloslancha** [comment]
ci:forward

**Pull request closed without merging**
