### PR TITLE
LPS-145132 Return the fileSize of the default image when AMImage is not ready

### PR DESCRIPTION
**Pull request by victorg1991**
Hi lima people! 👋 

Here is a fix for https://issues.liferay.com/browse/LPS-145132. Let me know what do you think :)

The same way we return the default image in the method `getPreviewAsStream` https://github.com/liferay/liferay-portal/blob/636033e171c4eb5e4397575821b38ab900118281/modules/apps/adaptive-media/adaptive-media-document-library-thumbnails/src/main/java/com/liferay/adaptive/media/document/library/thumbnails/internal/processor/AMImageEntryProcessor.java#L132 

This wasn't needed in the past since we didn't check the content length in the `WebServerServlet` so we ended up with a valid inputStream (the default image) but with a contentLength of 0, which now causes an exception due to 
874b5c60a974278f8417c4100d4807f76124638f

Reproduction steps in https://issues.liferay.com/browse/LPS-145132

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — COMMENTED** [review]
LGTM

The only thing is whether you find it useful or not to add or modify the  test cases with the new behavior:
```
AMImageEntryProcessorTest.testGetPreviewFileSizeDoesNotTriggerAMProcessorWhenNotSupported
AMImageEntryProcessorTest.testGetPreviewFileSizeDoesNotTriggerAMProcessorWhenInvalidSize
AMImageEntryProcessorTest.testGetPreviewFileSizeTriggersAMProcessorWhenNoAMImageExists

```

**Comment by victorg1991** [comment]
Sure thing :) I have added a new test covering the new _feature_ @AliciaGarciaGarcia

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Pull request closed without merging**
