### PR TITLE
LPS-164247 ComparisonFailure occurs on com.liferay.document.library.search.test.DLFileEntryIndexerIndexedFieldsTest

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-163433

Regression caused by this commit https://github.com/liferay-lima/liferay-portal/commit/892c42eac81ffd42cb2def90308f03a3d12c8fb5 of [LPS-163433](https://issues.liferay.com/browse/LPS-163433), that commit was necessary to avoid losing the empty DDMFormFieldValue nodes in some conversions, but it causes the side effect to index the "null" value.

I have added a check to avoid indexing the "null" value.

@AliciaGarciaGarcia

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:documents

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
