### PR TITLE
LPS-141975 Clarify the field names for mapping SEO - Modify the LayoutSEOTemplateProcessor to admit labels on the references

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-141975 add the possibility of contain the label on the template to the pattern to extract the variable name
- LPS-141975 Add test to check the new behavior on the LayoutSEOTemplateProcessor

I modified the pattern of the LayoutSEOTemplateProcessor to take on consideration that the references can have the label.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
I'm going to add some frontend commits on the PR before the next forward

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:reevaluate:1317401_1029

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The Above two failures are not related to this PR.
ContentPagesWithMapping#ViewMappableFieldsAreGroupedByFieldset failed at [LPS-142108](https://issues.liferay.com/browse/LPS-142108).

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1297401_679

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
