### PR TITLE
LRQA-64815 | master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRQA-64811
https://issues.liferay.com/browse/LRQA-64812
https://issues.liferay.com/browse/LRQA-64813
https://issues.liferay.com/browse/LRQA-64815
https://issues.liferay.com/browse/LRQA-64818
https://issues.liferay.com/browse/LRQA-64826

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
fluke, rerun it

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
