### PR TITLE
Lps 189723 dm copy to alignment

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**Before:** 
Screenshot 2023-07-05 at 12 11 11

**After:** 
Screenshot 2023-07-05 at 12 09 04

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by jaimelr10 — APPROVED** [review]
LGTM! :smile:

**Comment by jaimelr10** [comment]
ci:forward

**Pull request closed without merging**
