### PR TITLE
LPS-148821 translation json fmt

### PR DESCRIPTION
**Pull request by boton**
### Render container (zipped files) name when failing
Issue: https://issues.liferay.com/browse/LPS-148821

##### With FF `com.liferay.translation.web.internal.configuration.FFBulkTranslationConfiguration.config` disabled (default)
Without container
image
The filename and the container are the same.

With container
image

##### With FF `com.liferay.translation.web.internal.configuration.FFBulkTranslationConfiguration.config` enabled
image
All container files are set to `2 file - example web content-en_US fail & success.zip` but it is not true

---

##### With FF `com.liferay.translation.web.internal.configuration.FFBulkTranslationConfiguration.config` disabled (default)
Without container
image
With file container (zipped)
image

##### With FF `com.liferay.translation.web.internal.configuration.FFBulkTranslationConfiguration.config` enabled
image

On top of #2805.

/cc @adolfopa

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1287401_2389

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
Updated the download report CTA copy mentioned here https://issues.liferay.com/browse/LPS-142922?focusedCommentId=2628625&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2628625

**Comment by boton** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
