### PR TITLE
LPS 164161 reorder params

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-164161 add expiration date and review date to service add and update methods
- LPS-164161 buildService
- LPS-164161 fix calls to KBArticleService
- LPS-164161 add expirationDate reviewDate to macro addkBArticle
- LPS-164161 Declare missing parameters in other macros
- LPS-164161 reorder expirationDate and reviewDate as service.xml order
- LPS-164161 buildService
- LPS-164161 reorder sections param as service.xml order
- LPS-164161 buildService

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1287401_4783

**Comment by austinchiang** [comment]
LGTM, test failures not related to this pull

**Review by austinchiang — APPROVED** [review]

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
