### PR TITLE
LPS-142473 The image disappears from the folder when dragging and dropping a media file a second time in a row

### PR DESCRIPTION
**Pull request by boton**
BUG: https://issues.liferay.com/browse/LPS-142473

### CODE REVIEW

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
PortalSmoke#Smoke should be flaky

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
