### PR TITLE
LPS-134639 / LPS-134643 / LPS-134708 Update HttpClient version

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1237401_7895

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
Hi @adolfopa , Oh, the SF failures seem to come from QA side, let me check it.

**Comment by Hanlf** [comment]
Resent it with SF fixes under https://github.com/liferay-lima/liferay-portal/pull/1996

**Comment by Hanlf** [comment]
ci:stop

**Pull request closed without merging**
