### PR TITLE
LPS-115729 SF

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
I resent on https://github.com/liferay-lima/liferay-portal/pull/273

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
