### PR TITLE
LPS-200203 Change the Share label when it comes from a dropdown.

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-200203

In DM, where there is a dropdown for Share with two options, the current Share action is renamed to Invite to Collaborate:
Screenshot 2023-10-30 at 10 46 02

This doesn't affect to other Share actions like in Blogs: 
Screenshot 2023-10-30 at 11 29 08

### CODE REVIEW

**Review by marcogalluzzi — APPROVED** [review]
I would personally create a private method `_createShareDropdownItem` where you can additionally pass the desired label, but your change is also a good option 👍

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
