### PR TITLE
LPS-186580 Remove references to dl store

### PR DESCRIPTION
**Pull request by adolfopa**
https://issues.liferay.com/browse/LPS-186580

Addressed bchan's comment in https://github.com/brianchandotcom/liferay-portal/pull/136485; fixed in https://github.com/liferay-lima/liferay-portal/pull/4401/commits/57e6f02b420ecf67f9c9505f7090f8fb9802ed9d.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
Hi @adolfopa it seems there is a semantic versioning problem to solve:

```
[exec]   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec] = ================================================== ========== ========== ========== ========== ==========
     [exec] * com.liferay.portal.kernel.service                  MINOR      24.0.0     24.0.0     24.1.0     VERSION INCREASE REQUIRED
     [exec]   <   class      com.liferay.portal.kernel.service.ImageLocalServiceUtil
     [exec]     +   method     getImageInputStream(long,long,java.lang.String)
     [exec]       +   access     static
     [exec]       +   return     java.io.InputStream
     [exec]   <   class      com.liferay.portal.kernel.service.ImageLocalServiceWrapper
     [exec]     +   method     getImageInputStream(long,long,java.lang.String)
     [exec]       +   return     java.io.InputStream
     [exec]   <   interface  com.liferay.portal.kernel.service.ImageLocalService
     [exec]     +   method     getImageInputStream(long,long,java.lang.String)
     [exec]       +   access     abstract
     [exec]       +   annotated  com.liferay.portal.kernel.transaction.Transactional
     [exec]         +   property   propagation='SUPPORTS'
     [exec]         +   property   readOnly=true
     [exec]       +   return     java.io.InputStream
     [exec] [Baseline Warning] Bundle Version Change Recommended: 114.1.0
     [exec] [Baseline Report] Mode: diff (persisted)
     [exec] Semantic versioning is incorrect while checking /opt/dev/projects/github/liferay-portal/portal-kernel/portal-kernel.jar against /opt/dev/projects/github/liferay-portal/.gradle/caches/modules-2/files-2.1/com.liferay.portal/com.liferay.portal.kernel/114.0.0/66f8b6230e5309aa50dc662c7cf17779de773eb7/com.liferay.portal.kernel-114.0.0.jar
```

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
Hi @adolfopa, after checking the result. I found three backend test failures only appeared in your PR. Could you please have a look in these? Thanks. 
[com.liferay.object.admin.rest.resource.v1_0.test.ObjectDefinitionResourceTest](https://testray.liferay.com/home/-/testray/case_results/2354707658)
[PortalLogAssertorTest-modules-integration-mysql57-jdk8/2/24](https://testray.liferay.com/home/-/testray/case_results/2354707529)
[PortalLogAssertorTest-modules-integration-mysql57-jdk8/4/9](https://testray.liferay.com/home/-/testray/case_results/2354708179)

**Pull request closed without merging**
