### PR TITLE
 [NOT-FOR-GA5] LPS-117460 Avoid clone themeDisplay in AssetDisplayPageFriendlyURLProviderImpl

### PR DESCRIPTION
**Pull request by cgoncas**
Continuation of https://github.com/liferay-lima/liferay-portal/pull/577

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey @4lejandrito, everything looks fine to me, I have added a test, in order to avoid break this behavior in the future.

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @adolfopa,

Please don't forward this until the release has been made.

@austinchiang, can you please help us verify these changes don't break localized URL management?

Thanks!

**Comment by austinchiang** [comment]
ci:test:lima

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
Hey @cgoncas @4lejandrito 

Two tests are failing. The second failure (UpdateLanguageActionTest) seems legit; it looks like the new logic is not taking into account all conditions. I'll leave this on hold until one of you guys come back.

Thanks!

**Pull request closed without merging**
