### PR TITLE
LPS-154186 DM drag and drop a huge file to a folder disables it

### PR DESCRIPTION
**Pull request by boton**
### Before PR
image

### After PR
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
flaky issue, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
