### PR TITLE
LPS-196743 show File too big to preview on previewable documents

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
2. Go to : System Settings > D&M > File Entries >  Previewable Processor Maximum Size)
3. change the value and update
4. Upload a pdf with a side bigger than the value introduced

image

- LPS-196743 show preview size message on document preview. For this as we check the size on the method _checkForPreviewGenerationExceptions we should skip it previous this.
- LPS-196743 unify steps on behavior of image rendere with other rendered providers

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Test failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
