### PR TITLE
LPS-129820 Use SOAP 1.1 in Sharepoint Repository

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by Hanlf** [comment]
The SharePoint suite failures are not related to this PR, it is caused by [ISIT-27666](https://issues.liferay.com/browse/ISIT-27666)

**Comment by adolfopa** [comment]
@Hanlf I cannot see the Jira issue (no permissiosn). Are any of the Sharepoint tests executed? If all of them are failing, I'd prefer to wait and don't forward this.

**Comment by Hanlf** [comment]
ci:test:sharepoint

**Comment by Hanlf** [comment]
@adolfopa ,
Sorry for the late reply, I missed your above comment, since ISIT-27666 is a flaky issue, I will re-run SharePoint tests to see what happens.

**Comment by Hanlf** [comment]
Sad, all SharePoint tests failed at the ISIT-27666 again.

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by adolfopa** [comment]
ci:reopen

**Comment by adolfopa** [comment]
ci:test:sharepoint

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
ci:test:sharepoint

**Comment by Hanlf** [comment]
CRUD operations with SharePoint repositories based on this PR, no issues found.

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:reevaluate:1377401_1207

**Comment by Hanlf** [comment]
Sent it to BChan directly: https://github.com/brianchandotcom/liferay-portal/pull/115169

**Pull request closed without merging**
