### PR TITLE
LPS-130443 Clarify configuration usage

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@marianoalvarosaiz Waiting for the relase; We'll forward this when finished.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
