### PR TITLE
[NOT-FOR-7.3] LPS-119820 Do not escape the "+" character since it is used by the portal in some urls

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@robertoDiaz We'll hold this until the release is finished, as the issue is (relatively) minor, and this changes a class in the core (making any regression a serious issue). Other than that, it looks good.

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
This needs to be backported, so I'm forwarding it.

**Pull request closed without merging**
