### PR TITLE
LPS-164651 Bug in File Size limits

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://issues.liferay.com/browse/LPS-164651

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
cc/ @AliciaGarciaGarcia @marcogalluzzi

**Review by boton — APPROVED** [review]
LGTM, Tested and working on File Sizes.

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
