### PR TITLE
LPS-127092

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@boton,

We need to discuss with Emiliano how to make the button and the metadata sets feel like they are grouped together. I added a comment on the ticket.

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by boton** [comment]
See #1451.

**Pull request closed without merging**
