### PR TITLE
LPS-184127 Refactor DLAMImageCounterTest so that it doesn't depend on the images of a site initializer

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-184127)

Dear Team, working on https://issues.liferay.com/browse/LPS-177408, and after sending the PR we noticed that we would need to change by hand the variable relating to the images in a site initializer in DLAMImageCounterTest. So to avoid this, I refactored the tests. This way we won't need to change the tests when we add the future utility pages.

We also noticed that the second company was created even though it's only used in a test, so I moved it there. The time of test execution has been reduced by around 50% because of this. Also, there's no need to create the group for the second company, a simple cound should do.

Please let me know what you think.

Thanks!

## Change summary:

* Don't depend on a fix amount of images in the group
* Move creating the second company to the test where it's used

## Test Scenario

* Just run DLAMImageCounterTest

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:forward

**Pull request closed without merging**
