### PR TITLE
LPS-194101 KB Search in Move modal 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-194101 
**Result:** 

https://github.com/liferay-lima/liferay-portal/assets/8373764/430a54d8-14d9-4aef-99ee-dd6e770de8c1

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by jaimelr10 — APPROVED** [review]
LGTM!

**Comment by jaimelr10** [comment]
ci:forward

**Pull request closed without merging**
