### PR TITLE
LPS-107366 Handle exceptions

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @4lejandrito, there are 2 missing things: 
1. Add some permission checker 
2. Feature flag to not release this in GA3

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Just started reviewing :)

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/41.

**Pull request closed without merging**
