### PR TITLE
LPS-134027 Decouple MVC actions from Journal

### PR DESCRIPTION
**Pull request by adolfopa**
This removes all dependencies on Journal from the backend MVC action. I've also renamed a request parameter, from "articleId" to "key".

Further backend changes are needed (e.g. decouple display contexts), but those will be sent under a different issue.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]
LGTM

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by ambrinchaudhary** [comment]
Going to forward, as botoh backend and frontend stuff have been reviewed.

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Pull request closed without merging**
