### PR TITLE
LPS-121081 Publish button disabled on Blog entry page after a few seconds

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi @robertoDiaz

could you please check my changes?
The blogs.js::_saveEntry function was rewritten on the LPS-100101 which is causing this regression issue.
https://github.com/brianchandotcom/liferay-portal/pull/77387/files

Fix: remove the first then branch which returns response.json(); and exiting from the function.

https://issues.liferay.com/browse/LPS-121081

Thanks, Roland

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Hey @ambrinchaudhary 

This pr could be related with some changes introduced in LPS-100101. 

Can you review it??

Thanks!!!

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hey @rolandpakai, 
it is strange because I was not able to reproduce the original issue (https://issues.liferay.com/browse/LPS-121081), but I tested and the fix does not break anything. So I'm going to run the blogs's tests and if everything is ok, forward this.

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:blogs

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Thank you @ambrinchaudhary for re-testing the issue.
Did you waited a few second? 10-15 or so?
I tested it in vanilla bundle. The issue is related to saving the Draft in the background.

Thanks, Roland

**Comment by ambrinchaudhary** [comment]
>  Did you waited a few second? 10-15 or so?

Yes, I think it's 30sec what you have to wait so it is automatically saved as a draft in background. But I just tested in Chrome... 

Anyway, I'm just /cc our QA team (@austinchiang, @Jeremy-Ch, @Hanlf , @liuxingye ) in case they also want to test it again ;-)  

But as I just said, if `ci:test:blogs` suite passes, I'll forward the fix. 
Thanks!

**Comment by rolandpakai** [comment]
Thank you @ambrinchaudhary

**Comment by ambrinchaudhary** [comment]
ci:test:blogs

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
