### PR TITLE
LPS-164246 KB preview article info button

### PR DESCRIPTION
**Pull request by boton**
### After the PR:
image

image

image

At first, I only hide the label 4e5d2c98cffad96c47d9288ec98655794973d005. 

I need to fix vertical alignment 4e5d2c98cffad96c47d9288ec98655794973d005 and not render the label if not needed df27fb0ae99a46fcc0fc1a390650feaeb7821d54 but maybe it's better only use a `clay:link` 3fd0322d26415bcff6b418cd019137065d2b44be.

@ambrinchaudhary if this works for you, I will squash the last 3 commits on one and forward the PR to FI.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
@boton LGTM! Go on with the squash and forward to FI. Thanks!

**Comment by boton** [comment]
See https://github.com/liferay-frontend/liferay-portal/pull/2756

**Pull request closed without merging**
