### PR TITLE
LPS-154977 Use file extension item selector

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
@ambrinchaudhary @jaimelr10 I couldn't test the changes properly, so you should take this as a wip. Also, before forwarding anything upstream we'll need to talk with Tango.

**Comment by adolfopa** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
Closing in favor of https://github.com/liferay-lima/liferay-portal/pull/4068

**Pull request closed without merging**
