### PR TITLE
LPS-164707 Add new test for KB nesting

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
