### PR TITLE
LPS-137761 Use ballooneditor on contentEditor

### PR DESCRIPTION
**Pull request by markocikos**
This is a followup on https://github.com/liferay-lima/liferay-portal/pull/2544

As @diegonvs is on PTO, I'm jumping in to update PR. 

In this PR, we are enabling Balloon Editor in the sample module, see https://github.com/liferay-lima/liferay-portal/pull/2544#issuecomment-993280173. Nice analysis, @zhangyan0701 ! In addition, I added a minor code cleanup in https://github.com/liferay-lima/liferay-portal/commit/e0518714e21918448a8253c8dafde7b8869241cd.

Sample portlet is displayed correctly:
screen

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by boton** [comment]
Sorry, I´m on PTO too. 

I tried to do the steps described here #2544, create a config file add the property, and ensure the version and isn´t working for me, and redeploy only the affected modules and nothing is rendered. 

My properties, config and check the package version
image

Later I have done an ant all with this branch but the contentEditor isn´t rendered :( 
image

Could I be missing something?

/cc @markocikos @diegonvs

**Comment by markocikos** [comment]
@boton Why are you working on PTO? :angry:  Go relax!

Sidenote, from screenshot above, the content of your `.config` file does not look right. It should be  `enable="true"`, not `enabled=B"true"`.

**Comment by boton** [comment]
@markocikos sadly  I'm not on PTO today :( 

I think is only the B is only the [type](https://help.liferay.com/hc/en-us/articles/360017877292-Understanding-System-Configuration-Files#typed-values) for the config file.

Anyway, I tried without the `B` and it still doesn't work :(

**Comment by markocikos** [comment]
> I think the B is only the type for the config file.

@boton Oh cool, good to know! In your case, it's not just `B`. It's also `enable`, not `enabled`. No `d` on end.

**Comment by boton** [comment]
@markocikos ty that it! I didn't get the `d` difference :D

**Review by boton — CHANGES_REQUESTED** [review]
Wow, generally the new BallooonEditor works very well :D 

I only have a real problem with the plus floating menu, it isn't hiding on blur and the z-index is high.

When you open a modal with the plus menu open the result is weird:
image

And I have a question, how does the feature flag work in this case? 

In the current master if I add the `editor.wysiwyg.portal-web.docroot.html.portlet.blogs.edit_entry.jsp=ballooneditor` to my `portal-ext.properties` the ballooneditor works, but with these changes, if add the property but I don´t create the config file the result is that nothing renders.

image

Is this the expected behavior of the feature flag?

**Comment by diegonvs** [comment]
> When you open a modal with the plus menu open the result is weird:

Hey @boton, I tried to reproduce by opening the ItemSelector modal but there isn't an overlap in the modal. Could you describe more detailed repro steps? 💔 

See:

https://user-images.githubusercontent.com/7663513/148125707-c1c97f9e-fb47-459b-ad2d-97d1e3574775.mov

Happy new year!!!! 💖

**Comment by diegonvs** [comment]
>if add the property but I don´t create the config file the result is that nothing renders.

This is expected because we don't want to allow external ppl using ballooneditor unless the FF is enabled

(I'm trying to remember why not override this on blogs side, my brain is booting up from holidays 😂)

**Comment by boton** [comment]
Happy new year!!!! ❤️ 🥳 

> Hey @boton, I tried to reproduce by opening the ItemSelector modal but there isn't an overlap in the modal. Could you describe more detailed repro steps? 💔

Yep, sure

1. Open the ballooneditor plus menus
2. Click in another modal launcher like the blog cover image selector above the editor 

I'm not tested with other modals like categorization tags or categories but maybe the same happens

**Comment by diegonvs** [comment]
I noticed the z-index of the floating buttons is `1100` but there are some definitions that this number can be `10000`

Screen Shot 2022-01-06 at 14 58 45

On other hand, modal z-index is defined as `1050`.

Screen Shot 2022-01-06 at 15 00 12
 
I can change to a value lower than 1050, something like `1030` or `1040` but it evicendes that we should have a better strategy for defining our z-index layers as mentioned [here](https://github.com/liferay/liferay-frontend-projects/issues/332). @pat270 @edalgrin Does makes sense creating a ticket for it?

I can change the z-index value to `1040` arbitraily and I'll do it but I'm not sure if other issues related to it will blow up

**Comment by diegonvs** [comment]
I'll check AlloyEditor's panel z-index to see a more resilient value(probably it was changed quite times to fix bugs) and apply it for our panel z-index value :)

**Comment by pat270** [comment]
@diegonvs does the balloon editor menu get rendered as a direct child in the `body` element similar to our dropdown menu? If so, lowering the `z-index: 1040` will cause any editor inside a modal to not show the balloon editor menu (IDK if we have a case like this).

Personally, I think it would be better to remove the balloon menu if there is a click outside.

**Comment by diegonvs** [comment]
When adding a clickoutside handler inside ballooneditor plugin as 
```
			eventListeners.push(CKEDITOR.document.getWindow().on('click', (event) => {
				if (!editor.element.$.contains(event.data.$.target)) {
					editor.balloonToolbars.hide();
				}
			}));
```

inside `init` function, it's detecting the click outside but when calling `editor.balloonToolbars.hide();`, it doesn't hide the toolbars :/

I'm trying to understand what is going on here

**Comment by diegonvs** [comment]
Found a solution by not using `balloonToolbars.hide` and applying the click outside handler inside insertbutton plugin, considering `liferayToolbars` ctx. However, I'm not able to push changes to Marko's branch. I'll open another PR, okay?

**Comment by diegonvs** [comment]
I'm not able to close this PR. Hey @boton, could you do this? I opened this another PR containing the fix: https://github.com/liferay-lima/liferay-portal/pull/2624

**Comment by markocikos** [comment]
Followup in https://github.com/liferay-lima/liferay-portal/pull/2624

**Pull request closed without merging**
