### PR TITLE
LPS-162327 Create simple navigation fragment for kb articles

### PR DESCRIPTION
**Pull request by boton**
Followup up https://github.com/liferay-lima/liferay-portal/pull/3456

Added missing container with the fragmentElementId to make the styles work.

image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward (Cancelled original invocation)

**Pull request closed without merging**
