### PR TITLE
LPS-161585 Can't create Redirect Entries with accented characters

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
- LPS-161585 add test to check behavior adding or updating the redirection with accented characters
- LPS-161585 when we save the friendly URL for the page we are saving it normalized, so save the sourceURL as a normalized
- LPS-161585 show the sourceURL as decodeURL
- LPS-161585 fix tests
- LPS-161585 Update test for checking the invalid source URL

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
@AliciaGarciaGarcia could you help to resolve the conflicts when you get a chance? Thanks.

**Comment by AliciaGarciaGarcia** [comment]
closed in favor of https://github.com/liferay-lima/liferay-portal/pull/3507

**Pull request closed without merging**
