### PR TITLE
LPS-197415 Fix miscellaneous issues in the configuration screen for File Size Limits

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-197415

image

image

- LPS-197415 fix messages to match the behavior
- LPS-197415 make messages changes on copy size limits configuration
- LPS-197415 show info on the configuration page
- LPS-197415 add the type to the number inputs of the configurations
- LPS-197415 change configuration name
- LPS-197415 change name and add a new title to the conf
- LPS-197415 buildLang
- LPS-197415 change poshi test

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
@AliciaGarciaGarcia once conflicts are resolved, we can forward it.

**Comment by AliciaGarciaGarcia** [comment]
image

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
Checking the failures.

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:document

**Comment by Jeremy-Ch** [comment]
ci:test:stable

**Comment by Jeremy-Ch** [comment]
The failure are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:stop

**Pull request closed without merging**
