### PR TITLE
LPS-139069 Count global group on getGroupsCount

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you pleae review my fix?

**Description**
If a non admin user wants to select images from documents and media, the Global site is visible but the pagination total shows one less 

**Expected Result:**

The pagination will show the number of pages where the user has access - including the Global site

**Actual Result:**

 The Global site is visible, but it does not counts at the pagination total

Thanks, Roland

https://issues.liferay.com/browse/LPS-139069

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
