### PR TITLE
LPS-156146, LPS-157767, LPS-157571 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-157571
https://issues.liferay.com/browse/LPS-157767
https://issues.liferay.com/browse/LPS-156146

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:message-boards

**Comment by austinchiang** [comment]
ci:test:one-drive

**Comment by austinchiang** [comment]
ci:test:onedrive

**Pull request closed without merging**
