### PR TITLE
LPS-163083 Create documents and media browser tag

### PR DESCRIPTION
**Pull request by adolfopa**
This new tag offers a limited subset of the dm funcionality: folder navigation, create folders, rename folders/files and upload a file (via drag & drop).
To make it easier to test, I've replaced the Blogs images view with it. It should display the contents of DM:
image
*What is failing*:
* When trying to rename a file/folder, the page should be reloaded when saving. The name is updated correctly, but the modal seems to be ignoring the `onFormSuccess` callback I'm providing.

*What is missing*:
* Create folder. It should work roughly the same as the "rename" action: a modal that takes the folder name, make a PUT request to the servlet (I've included the impl) and then refresh so that the search container displays the updated contents.
* File upload. For the moment, it should be enough if we could integrate the single upload component in the tag.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hey @adolfopa, I've been cheecking this: 

> modal seems to be ignoring the onFormSuccess callback 

The thing is that the modal expects a json response and only then closes the modal an executes the _onFormSuccess_ fn provided, as you can see [here](https://github.com/liferay/liferay-portal/blame/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/components/SimpleInputModal.es.js#L77-L77). Unfortunately I've not been able to return a json in `RepositoryBrowserServlet.java` _doPost_ method. Same will happen for the action of create a folder.

**Comment by ambrinchaudhary** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/3528

**Pull request closed without merging**
