### PR TITLE
LPS-154333 Hide wiki tree html

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-154333

When the wiki tree pages are being displayed, the tree is seen in html and then changes to alloy-ui elements. This can be seen when clicking on pages in the tree or refreshing the page.

https://user-images.githubusercontent.com/31672551/170383584-d28b72af-c1af-43f0-8226-4962e31193a8.mov

A solution for this is to hide the tree so this change is not seen by adding the hidden attribute to the tree. Alloy-ui will still be able to change the tree and once it is fully built, we remove the hidden attribute.

If there are any questions or comments about this please let me know.
Thank you.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello, I am having issues running prettier to check the format and recieve the following:
`[error] No parser could be inferred for file: apps\wiki\wiki-navigation-web\src\main
\resources\META-INF\resources\tree_menu\view.jsp`

Any help with resolving this, so I can resolve sf build is much appreciated!

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Hi @fortunatomaldonado 
I ran SF locally, the sf error is caused by `wikiPageList.removeAttribute("hidden");` see https://github.com/Hanlf/liferay-portal/pull/355/commits/e1d82d221d02e35199a6f13be7b5c1d1356589f0

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by boton** [comment]
See #3092

**Pull request closed without merging**
