### PR TITLE
LPS-177305 Remove Dev FF for KB navigation and interactions

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:knowledge-base

**Comment by ambrinchaudhary** [comment]
I think the poshi failures are related and need to be updates. The workflow status is not in the management toolbar anymore, it was moved to the info panel(story https://issues.liferay.com/browse/LPS-166644)

**Comment by Jeremy-Ch** [comment]
Combined https://github.com/liferay-lima/liferay-portal/pull/4038 and https://github.com/liferay-lima/liferay-portal/pull/4052, new pull request please see https://github.com/liferay-lima/liferay-portal/pull/4060

**Pull request closed without merging**
