### PR TITLE
LPS-151865 Video empty state is not working when video previews is not enabled

### PR DESCRIPTION
**Pull request by boton**
Issue: https://issues.liferay.com/browse/LPS-151865

#### Before PR
image

#### After PR
image

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
