### PR TITLE
LPS-169658 some errors with tests checking the Existing External Reference Code

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-169658 fix test, blog entry can not have same urlTitle
- LPS-169658 throw proper exception
- LPS-169658 rename exception to match others
- LPS-169658 baseline
- LPS-169658 partial revert of LPS-163008 Remove_validateExternalReference method in LocalServices
- LPS-169658 rename exception
- LPS-169658 autoSF

@sergiojimcos @LuismiBarcos As we talked (thanks for the HELP) i will sent this PR with changes on the services to check the existence on KBArticle and WikiPage of the ERC and the group WITH the version

the revert is partial to this commit 02bcc1ecfcb5fdc37d0e7c691268c6ca7c7b4065

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci:test:blogs

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:blogs

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by Hanlf** [comment]
ci:test:knowledge-base and ci:test:blogs suite failures are not related to this PR.

**Comment by Hanlf** [comment]
ci:stop

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
