### PR TITLE
LPS-166740 Can not delete KB Display Page Template

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-166740 asset display page should be linked to the article not the version
- LPS-166740 obtain the asset display page by the resource prim key, that it is the id from the kbArticle not the version

If we link the asset display page to the KBArticle (resourcePrimKey) not to the version, we can delete it properly

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1317401_6406

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:reevaluate:1317401_6406

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1267401_6435

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
