### PR TITLE
[TS] LPS-124504

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
Added https://github.com/liferay-lima/liferay-portal/pull/1195/commits/d1acb1e8b3ae995c57f48da1e08978bdbd051286 to resolve similar issue in another test.

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
