### PR TITLE
LPS-164483 KB preview article child items

### PR DESCRIPTION
**Pull request by boton**
## Issue https://issues.liferay.com/browse/LPS-164483

Build on top of https://issues.liferay.com/browse/LPS-164481 #3541 we need to wait until #3562 is merged. Maybe I cause some poshi test failure because I update some markup.

### Before PR
image

### After PR
image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]
LGTM!

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1367401_2169

**Comment by Hanlf** [comment]
Hi @boton 
The Poshi tests need to be updated with the commits, could you please take care of the conflicts, after resolving the conflicts, the QA side will fix the tests, thanks!

**Comment by boton** [comment]
@Hanlf Rebased with today master

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Sent it with test fix under: https://github.com/liferay-lima/liferay-portal/pull/3591

**Pull request closed without merging**
