### PR TITLE
Lps 131302

### PR DESCRIPTION
**Pull request by SamZiemer**
From @noornajj :

> https://issues.liferay.com/browse/LPS-131302
> 
> The issue here is that the info button does not appear for searched documents that have a preview. This was occurring because all documents with a preview were being viewed by view_file_entry_simple_view.jsp. There is a condition to skip this view if showExtraInfo is equal to true, but this value was always set to false.
> To fix this, I removed the use of view_file_entry_simple_view.jsp and had all file entries be viewed by view_file_entry.jsp. I saw that view_file_entry_simple_view.jsp was introduced in LPS-42026 and tested the issue reported in this ticket and was not able to reproduce it with this change.
> After this change, there is no use for view_file_entry_simple_view.jsp. I will leave the decision on whether this fix is appropriate and if view_file_entry_simple_view.jsp should be deleted to the product team.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@boton This looks good to me, but can you check if it affects anything related to the detail/preview work you did? Thanks!

**Comment by boton** [comment]
Sorry @SamZiemer but the AssetPublisher uses the showExtraInfo parameter in its configuration and we can't just ignore the condition.

Maybe the way is to pass the showExtraInfo parameter with true value.

Feel free to resend the PR with this in mind.

**Comment by SamZiemer** [comment]
@noornajj, please see @boton's comment.

**Pull request closed without merging**
