### PR TITLE
LPS-148758 SF

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

@evibudai is OoO, therefore I overtook the work on the LPS.
https://github.com/liferay-lima/liferay-portal/pull/2810#issue-1163744413

Thank you and best regards,
István

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1277401_2291

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
Resend this to BChan https://github.com/brianchandotcom/liferay-portal/pull/114789.
/cc @IstvanD @AliciaGarciaGarcia

**Pull request closed without merging**
