### PR TITLE
LPS-163961 Adapt logic to take into account actions in vertical card, Copy logic from DDMStructrureElementsDefaultPropsTransformer.js

### PR DESCRIPTION
**Pull request by Hanlf**
Original pull request comment:

> **Motivation**
> In order to not use deprecated or old frontend cards, use the new clay card for horizontal cards in DL portlet
> 
> [LPS-163961](https://issues.liferay.com/browse/LPS-163961)
> 
> **Proposed Solution**
> Replace usages of frontend:horizontal-card with clay:horizontal-card

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
[DMLocalStaging#CommentDMDocumentOnLiveSite](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/110510//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DMLocalStaging_CommentDMDocumentOnLiveSite_) should be not related to this PR, re-run it.

**Comment by Hanlf** [comment]
[DMLocalStaging#CommentDMDocumentOnLiveSite](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/110510//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DMLocalStaging_CommentDMDocumentOnLiveSite_) should be not related to this PR, re-run it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]
I do not see any issues.

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Changes LGTM but I tested it and I found two issues for folders that was working before and not with this pull. If you check a folder and from the management toolbar and: 

- select "Download", it goes to a blank page. 
- select "Delete", it returns success message but the folder is not deleted. 

@ealonso do you have time to check why this issues could be happening? Otherwise I'll continue debugging it...

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-lima/liferay-portal/pull/3539

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
