### PR TITLE
[NOT-FOR-7.3] LPS-114569 Quarantine tests

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@austinchiang When you have time, can you take a look at the test failure? This has low priority right now, so no need to hurry. We'll not send it until the release is finished, so it is ok if you guys wait until then.

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/794

**Pull request closed without merging**
