### PR TITLE
LPS-180242 Don't consider missing refs an error when importing

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-180242

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-180242.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:close

**Pull request closed without merging**
