### PR TITLE
LPS-194647 Rename "File Size Limits" to "File Upload Limits" and update description

### PR DESCRIPTION
**Pull request by marcogalluzzi**
See https://liferay.atlassian.net/browse/LPS-186713 for more info.

Before:

Captura de pantalla 2023-08-28 a las 13 22 44

After: 

Captura de pantalla 2023-08-28 a las 14 11 23

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:reevaluate:1397401_7024

**Comment by austinchiang** [comment]
ci:forward:force

**Comment by austinchiang** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
