### PR TITLE
[TS] LPS-153629 Add assetCategoryIds to automatic draft saving request

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

https://issues.liferay.com/browse/LPS-153629

Issue:
The frontend request does not send the selected categories ("assetCategoryIds") during automatic draft saving. Upon debugging I found the same case for "assetTagnames". That means that these values are not saved during automatic draft saving.

Solution:

I added the missing parameters to the frontend request, so now the values are saved after automatic draft saving.

Please review my PR!

Best regards,
Évi

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
> Upon debugging I found the same case for "assetTagnames".

Thank you very much for your fix! I made small changes and send a new PR [here](https://github.com/liferay-lima/liferay-portal/pull/3055)

**Comment by ambrinchaudhary** [comment]
Pull request submitted to https://github.com/liferay-lima/liferay-portal/pull/3055

**Comment by evibudai** [comment]
Thank you!

**Pull request closed without merging**
