### PR TITLE
LPS-122502 Fix Twitter, Facebook, Linkedin social bookmarks only shae articles with the default locale if property "locale.prepend.friendly.url.style=2", add call to getAlternateURL method

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Steps to reproduce:
1. Define the following property: locale.prepend.friendly.url.style=2
2. Create a site with English as default language and other available languages, for this example, Spanish
3. Create an English journal article and the Spanish translation.
4. Create a page with an asset publisher
5. Configure the asset publisher:
    - Asset publisher -> Configuration -> Display Settings -> Set and Enable -> Social Bookmark.
    - Select Facebook and Twitter
6. At the asset publisher, click on Facebook or Twitter icon to share the created content (the link is shared with the default language)
7. Switch to Spanish. 
8. At the asset publisher, click on Facebook or Twitter icon to share the created content, the link to be shared is in English but the title in Spanish. Same thing for Twitter or LinkedIn.

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
