### PR TITLE
LPS-192046 Put margin inside the fieldset

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Issue https://liferay.atlassian.net/browse/LPS-192046 

**Before:** 
Screenshot 2023-07-28 at 10 16 47

**After the changes:** 
Screenshot 2023-07-28 at 12 16 08
Screenshot 2023-07-28 at 12 16 16

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
cc @sofiamendozalr

**Pull request closed without merging**
