### PR TITLE
LPS-167672: Ensure panel collapse listener is unregistered on navigate event

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The problem was observed in the documents and media administration panel: Every time the detail view of a file is opened a new collapse state save handler is registered. These handlers need to be unregistered when a navigation event happens.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failure should not be related to this PR, but there are some Poshi tests that only failed on this PR, re-run it to double-check.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by boton** [comment]
Hi @matthiasblaesing, thanks a lot for the PR.

The code is LGTM but I am the right person to review it.

Can you please move the PR to @liferay-fronted https://github.com/liferay-frontend/liferay-portal/pulls?

Thanks in advance

**Pull request closed without merging**
