### PR TITLE
LPS-116438 Small images are not appearing in the blogs

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi @robertoDiaz ,
Could you please review this pull request?
As we discussed in PTR-1797 I added LPS-68077 changes.
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by robertoDiaz** [comment]
Looks good to me 👯‍♂️

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/372

**Pull request closed without merging**
