### PR TITLE
[TS] LPP-47380 > LPS-171566 An error may occur when referencing the document directly from the URL | master 

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Hi team, 
I resend the PR after adding an integration test based on Brian Chan's comment.
brianchandotcom#128103
tickets:
https://issues.liferay.com/browse/LPS-171566
https://issues.liferay.com/browse/PTR-3533
Thanks a lot.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:reevaluate:1377401_7803

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1377401_7803

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures should not be related to this PR.

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr, send to BChan directly, see https://github.com/brianchandotcom/liferay-portal/pull/128805

**Pull request closed without merging**
