### PR TITLE
LPS-130384 Remove usage of "path" in DM queries/indexers

### PR DESCRIPTION
**Pull request by adolfopa**
All tests green; no appreciable difference in the number of results returned.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia I've pushe-force'd additional changes. Please review.

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by Hanlf** [comment]
The failure about `No Group exists with the primary key 0****` should be fixed under https://github.com/brianchandotcom/liferay-portal/pull/101203, Will re-run it to see if the above failure is gone.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa see https://github.com/liferay-lima/liferay-portal/pull/1780
but testTitleIndexedInTriplicateDistortsScores maybe we do not want to touch it

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1780

**Pull request closed without merging**
