### PR TITLE
LPS-164043 prevent NPE

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@boton the issue you commented on slack

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
@boton I will close this to make an experiment today

**Pull request closed without merging**
