### PR TITLE
LPS-181539 | Master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://issues.liferay.com/browse/LPS-181539

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by austinchiang — CHANGES_REQUESTED** [review]
We never add tests to acceptance if they have never run in CI before, please remove the properties and file a ticket to check if we need to add them to acceptance later

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Review by austinchiang — APPROVED** [review]

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
