### PR TITLE
LPS-115230 Apply Builder Pattern in Info Framework (Resent after rebasing Thursday 18th)

### PR DESCRIPTION
**Pull request by JorgeFerrer**
@4lejandrito @adolfopa

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@adolfopa Let's wait til tomorrow since this will probably break https://github.com/liferay-lima/liferay-portal/pull/260. I will do the necessary changes tomorrow and forward it.

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by JorgeFerrer** [comment]
Looking into the compile error

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
@adolfopa Could you take care of applying the builder pattern to the translations-web module?

**Comment by 4lejandrito** [comment]
I'll do tomorrow.

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/269.

**Pull request closed without merging**
