### PR TITLE
LPS-125994 Add user personal folder criterion

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
Hey @carolmariaabb,

I had to revert your changes for https://issues.liferay.com/browse/LPS-125456. This caused regressions in DM and Journal (we need that criterion to be there).

Thanks!

**Comment by carolmariaabb** [comment]
> Hey @carolmariaabb,
> 
> I had to revert your changes for https://issues.liferay.com/browse/LPS-125456. This caused regressions in DM and Journal (we need that criterion to be there).
> 
> Thanks!

Hi @adolfopa ,

Is there a way to disable/hide the breadcrumb so that a user cannot navigate through it and view the documents uploaded by other users (as described by [LPS-125456](https://issues.liferay.com/browse/LPS-125456))?

**Comment by adolfopa** [comment]
@carolmariaabb The "repository-entry-browser" tag has a "showBreadcrumb" attribute which can be customized. Right now it is always set to true, but the item selector view could be changed so that the attribute value is taken for the request.

As the field type is shared both by Forms and DM/Journal, the complicated thing would be to figure out when to disable the breadcrumbs (it has to be done only for Forms).

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1387

**Pull request closed without merging**
