### PR TITLE
LPS-181652 Can't see Knowledge Base Article Child when Parent Article still pending

### PR DESCRIPTION
**Pull request by diogomelo09**
Related issue: [LPS-181652](https://issues.liferay.com/browse/LPS-181652)

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
