### PR TITLE
LPS-128397 Tika MP4 parser does not remove temp files

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

I have applied the solution from [TIKA-3203](https://issues.apache.org/jira/browse/TIKA-3203) which is twofold:

1. since we have our own patched version of isoparser/mp4parser, we can't just update to the newest official version. I patched the library again, with the changes referenced [here](https://issues.apache.org/jira/browse/TIKA-3203?focusedCommentId=17211209&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17211209).
2. I updated Tika to 1.25 that includes [the solution on the Tika side](https://github.com/apache/tika/commit/d2449f9f9302a1479b067f408ee067aad221e45e)

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
@adolfopa, @IstvanD SF was failing due to wrong commit message in fake gradle cache commit. Every commit message must include a valid Jira issue identifier. I've renamed the commit, see: https://github.com/liferay-lima/liferay-portal/pull/1581

**Comment by IstvanD** [comment]
@marianoalvarosaiz I'm sorry for this mistake. Thank you for fixing the commit message.
I'll update the article which I used to contain the correct commit message format.

**Comment by marianoalvarosaiz** [comment]
Great @IstvanD, thanks a lot for all your work in this ticket. To commit the fake gradle cache you can use _gradlew commitCache_, that generates the files and the performs the commit all in one!

**Comment by IstvanD** [comment]
Many thanks @marianoalvarosaiz. I updated the article with this information.

**Comment by adolfopa** [comment]
Closing in favor of https://github.com/liferay-lima/liferay-portal/pull/1581

**Pull request closed without merging**
