### PR TITLE
[TS] LPS-151748

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
ci:test:sf

**Comment by crodriguezy** [comment]
Hi @liferay-lima , this has been previously reviewed and analyzed by @robertoDiaz

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
