### PR TITLE
LPS-166850 Permission error when trying to edit web content in an asset library

### PR DESCRIPTION
**Pull request by adolfopa**
# Motivation

https://issues.liferay.com/browse/LPS-166850

Users with roles that don't have the global group VIEW permission explicitly assigned won't be able to edit web content in an asset library (this may happen too in sites, but we haven't checked it).

The fix is to explicitly check for that permission before invoking the services.

# Change summary

- Make explicit permission check.
- Make sure the display context doesn't return a negative value.
- Minor SF changes.

# How to test the changes

1. Add a new asset library.
2. Add a new regular role and define the permissions below:
  * Asset Libraries: Access in Control Panel
    - Asset Libraries: View
    - Asset Library Settings > Asset Library Entry: View Site and Asset Library Administration Menu
4. Create a new user
5. Edit the new user > Memberships to select the added asset library and save it
6. Edit the new user > Roles to select the regular role(under REGULAR ROLES) and Asset Library Owner(under ASSET LIBRARY ROLES)
7. Login in with the new user
8. Go to the added asset library > Web Content
9. Try to add a new web content

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Will send to echo.

**Comment by adolfopa** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/10073

**Pull request closed without merging**
