### PR TITLE
LPS-149526 Reflect the changes of the creation/edition of the file when filling the urlTitle

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
When the FF is enabled : 

`echo enabled=B\"true\" > ../bundles/osgi/configs/com.liferay.document.library.configuration.FFFriendlyURLEntryFileEntryConfiguration.config`

When you create a File, a friendlyURL is generated:

https://user-images.githubusercontent.com/47524751/159013757-15dbb445-e378-4c29-a2fa-4b0107a98d30.mp4

On this PR we let the value of the field be reflected on the creation of the friendlyURL for the document

https://user-images.githubusercontent.com/47524751/159014068-094a18c5-14e2-45ba-a9a1-3c92da2d6d04.mp4

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
To pass this PR the PR : https://github.com/liferay-lima/liferay-portal/pull/2833 must be merged on master and then tested.

CI will fail till the https://github.com/liferay-lima/liferay-portal/pull/2833 is merged because needs methods on that PR

So till then DO NOT CI it :D

**Review by ambrinchaudhary — APPROVED** [review]

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
rebased because branch conflict

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:stop

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1347401_1330

**Comment by AliciaGarciaGarcia** [comment]
branch has conflicts > rebase

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
