### PR TITLE
LPS-160430 impedibug KB product menu sidebar interactions

### PR DESCRIPTION
**Pull request by boton**
**Issue:** https://issues.liferay.com/browse/LPS-160430

#### Before PR

https://user-images.githubusercontent.com/67901/186881459-a60d0db6-0119-42cd-bb1a-35913da0fc51.mp4

#### After PR

https://user-images.githubusercontent.com/67901/186881499-69761a48-995f-46e8-92df-f5c75cd2e825.mp4

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
