### PR TITLE
[TS] Adding Friendly URL redirect configuration for locale.prepend.friendly.url.style=2

### PR DESCRIPTION
**Pull request by danielmijarra**
Hello @liferay-lima,
this pull fixes [LPS-173562](https://issues.liferay.com/browse/LPS-173562).

The Friendly URL Redirection configuration functionality now also applies to `locale.prepend.friendly.url.style=2`.
We add a "Helper" in `portal-kernel` to allow `I18nFilter` to read this configuration.
We use `UploadServletRequestConfigurationHelper` as an example to do the `FriendlyURLRedirectionConfigurationHelper`.

I agreed with @robertoDiaz that he would do a pre-review.
Could you please assign him this pull then?

Previous pull: [3946](https://github.com/liferay-lima/liferay-portal/pull/3946)

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
There are some faults that occur only on this PR, re-run to check if they are related.

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Review by robertoDiaz — APPROVED** [review]

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
Hi @danielmijarra Could you help to solve the conflicts for this pr? Thanks.

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by adolfopa** [comment]
Manually fwd to bchan: https://github.com/brianchandotcom/liferay-portal/pull/129897

**Pull request closed without merging**
