### PR TITLE
LPS-154020 Fix NoClassDefFound exn when running sharepoint tests

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@austinchiang Can you double check that this fixes the sharepoint test failures? If it works, please do the ci forward.

**Comment by austinchiang** [comment]
ci:reevaluate:1257401_2864

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
