### PR TITLE
enable al staging

### PR DESCRIPTION
**Pull request by 4lejandrito**
@adolfopa please review the last 3 commits. They filter the apps and remove the public pages section.

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]
Looks good to me. I'll wait for https://github.com/liferay-lima/liferay-portal/pull/852 to be merged before forwarding this.

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
@4lejandrito Looks good to me.

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/872.

**Pull request closed without merging**
