### PR TITLE
Lps 129102

### PR DESCRIPTION
**Pull request by brianikim**
Re-sending from: https://github.com/brianchandotcom/liferay-portal/pull/100037

Test result: https://github.com/brianchandotcom/liferay-portal/pull/100037

BChan's question from previous PR:
> @brianikim can you use you need the TX callback? We have cases where this is not needed... I don't see why we would need it here. Please resend.

The queue system for the index is too fast and always fetches the old entries from the database. It's in a separate thread, so it's in a different transaction, so it doesn't see the correct updated value.

In the context of LPS-129102, headless-api will always return inaccurate results.

Please let me know if we can implement my solution differently to fit BChan's request, but as far as I can see, the current implementation is required.

The PR is the exact same as the one forwarded to BChan so if you do not see any issues, please forward with my explanation included so he doesn't close it again.

Sincerely,
Brian Kim

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
Hello @liferay-lima ,

Please let me know if you see any issues with this PR. This has already been forwarded to BChan before. 

Sincerely,
Brian Kim

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
