### PR TITLE
LPS-197819 add new fragment under FF

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
To see new fragment : LPS-197909

- LPS-197819 create the new fragment and only show it if the FF is active
- LPS-197819 FF
- LPS-197819 buildLang

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
Failures are unrelated.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
