### PR TITLE
[TS] LPS-173562 Adding Friendly URL redirect configuration for locale.prepend.friendly.url.style=2

### PR DESCRIPTION
**Pull request by danielmijarra**
Hello @liferay-lima,
this pull fixes https://issues.liferay.com/browse/LPS-173562.
The Friendly URL Redirection configuration functionality now also applies to _locale.prepend.friendly.url.style=2_.

Added the class name as part of the method name (https://github.com/liferay-lima/liferay-portal/commit/48010e7c2d062c8eb2032c02f597ae78bc126c61).

Previous pull: https://github.com/liferay-lima/liferay-portal/pull/4243.

Please let me note if you have any questions.

cc: @adolfopa @robertoDiaz @ling-alan-huang

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by adolfopa** [comment]
ci:forward:force

**Comment by Hanlf** [comment]
ci:forward:force

**Comment by Hanlf** [comment]
Forward manually to BChan: https://github.com/brianchandotcom/liferay-portal/pull/134107

**Pull request closed without merging**
