### PR TITLE
[TS] LPS-146180

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi @liferay-lima , as talked wit @robertoDiaz , we are reverting LPS-139726 due to performance issues. 

As mentioned in https://issues.liferay.com/browse/LPS-146180, as solution to this we are going to rollback this changes and add the  #LPS-109977 and #LPS-145630 to the branch (with this we set an expiration date for the cache, or allow disable it by mime type). 

Kind regards

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
@adolfopa 👍 

As @crodriguezy sayd we had agreed this rollback.

cc/ @dacousalr, @liferay-echo

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
