### PR TITLE
[TS] LPS-129863 | Cannot show preview for video with only audio

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @liferay-lima,

This is a solution for the issue [LPS-129863](https://issues.liferay.com/browse/LPS-129863). 

It's not a very common situation but not completely unusual either. It happens whenever one tries to preview a document whose _mimetype_ is a video but has no frames: it's actually audio only. See [LPS-129863](https://issues.liferay.com/browse/LPS-129863) for reproducing steps and an example file.

The problem is not actually on the creation of the preview, since although no frame exist, the audio is processed correctly; it comes only when trying to create the thumbnail for the video. Here it will check for streams with codec of type video but it won't find any. Nevertheless it will try to save the (nonexistent!) thumbnail picture in the Document Library and it will crash. 

The solution simply generates a black image thumbnail whenever it can't find any streams with codec of type video and it will save that. An alternative would have been avoiding the thumbnail creation but Liferay will try every time since the file is an actual video, so I think this is better. 

I've chosen a black image as the default because it seems a common choice, but I haven't checked if it's culturally universal. White might be another reasonable choice? 

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @ricardocousolr,

Do you think it would make sense to just ignore videos that have a video preview but not a thumbnail? That way we don't call Xuggler every time and we keep a consistent UI for missing thumbnails.

**Comment by 4lejandrito** [comment]
As discussed on Slack:

We are changing the way this works for 7.4 and I want to be sure we have a plan for this specific issue. I am happy to merge this so that you can backport it, but I prefer to have a quick chat about it with the team on Monday. 

We'll get back to this next week.

Thanks!

**Comment by 4lejandrito** [comment]
Hi @ricardocousolr,

We agreed to apply the same fix (black thumbnail) for our upcoming FFMPEG implementation. This means this pull request can safely be forwarded and backported.

Thanks!

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by ricardocousolr** [comment]
Thanks @4lejandrito!

**Pull request closed without merging**
