### PR TITLE
LPS-134736 No autoBatch needed for a select

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-134736

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa , I did not check the bug cause you must install and run DB2 on the machine and I do not know how.

But I think that the change made on this PR is needed (and maybe fix the bug)

let me read your thoughts

**Comment by AliciaGarciaGarcia** [comment]
I ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
