### PR TITLE
LPS-122753 AL Publish to Live opens in a Modal

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
https://issues.liferay.com/browse/LPS-122753

Current view: 

Screenshot 2020-10-28 at 22 21 24

@4lejandrito please check that works as expected (i.e. modal is not automatically closed, should be? should redirect to somewhere?)

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @ambrinchaudhary,

The same modal on sites also stays open and does not redirect. I think we should do the same. 

I didn't see any issues with your changes. I will fix some backend issues I detected and resend.

Thanks!

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/984.

**Pull request closed without merging**
