### PR TITLE
LPS-123711 mitigation to the error/redirect when cmd is empty

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa / @4lejandrito 

This can be useful to mitigate this or future errors or you see it irrelevant and superfluous?

Thanks for the feedback

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia I think we should check why `cmd` is empty. AFAIK it should always have a value; this feels like a symptom of a bug in the Js/JSP code.

**Comment by AliciaGarciaGarcia** [comment]
> @AliciaGarciaGarcia I think we should check why `cmd` is empty. AFAIK it should always have a value; this feels like a symptom of a bug in the Js/JSP code.

Yes, this is only mitigation for the real problem (and I think that the CMD must never be empty and this check can come on hand) 

For the real problem I told @boton and he is looking at it.
I was asking if (on parallel side of the proper fix) this can be useful

**Comment by adolfopa** [comment]
Oh, I see. I think it is not worth it. I'll prefer to wait for the real fix.

**Comment by boton** [comment]
Real fix discussed in liferay-app-builder#112.

**Comment by adolfopa** [comment]
Closing this in favor of https://github.com/liferay-data-engine/liferay-portal/pull/63

**Pull request closed without merging**
