### PR TITLE
[TS] LPS-173703 External video cannot be added because of file ending restrictions

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
When documents of only certain extensions are allowed, the extension validation will fail on external video shortcuts because those documents do not have an extension.

Proposed Solution
========
Skipping the extension validation for documents whose type is external video shortcut.

Steps to Verify
========
Please consult the linked LPS for reproduction steps.
https://issues.liferay.com/browse/LPS-173703

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by Hanlf** [comment]
The document suite failures are not related to this PR.

**Comment by ambrinchaudhary** [comment]
Just put on hold to decide internally with PMs if this is the expected behaviour.

**Comment by adolfopa** [comment]
@IstvanD Instead of checking the file type, why not simply skip the validation when the file name/extension is null? If there's no file, it's ok to not validate its properties.

**Comment by IstvanD** [comment]
@adolfopa if a document is added with no backing file (filename and extension are blank/null), [the filename will be created based on the document title](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLFileEntryLocalServiceImpl.java#L229-L236), so the validation will be performed regardless.
If we would allow the extension validation to pass for empty filename/extension the behavior would change for "fileless" basic documents as well.

Please let me know your thoughts.

Best regards,
István

**Comment by adolfopa** [comment]
@IstvanD But the seam

**Comment by IstvanD** [comment]
Hi @adolfopa 

I created a new fix that addresses the concerns.
https://github.com/liferay-lima/liferay-portal/pull/3966

**Pull request closed without merging**
