### PR TITLE
LPS-173321 Dev Feature Flag removal | Review and Expiration date in KB articles

### PR DESCRIPTION
**Pull request by marcogalluzzi**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
Good from a backend POV. @austinchiang Can you guys take a look at the test changes and do the forward if it's ok? Thanks!

**Comment by marcogalluzzi** [comment]
ci:stop

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @marcogalluzzi 

The SF errors was I suffered yesterday on another [PR](https://github.com/liferay-lima/liferay-portal/pull/4156)....
Are the result of another team that does not updated the FF

You should rebase and from portal-impl  run : `ant format-source-current-branch`

**Comment by marcogalluzzi** [comment]
ci:test:sf

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
The failures are not related to this PR. I will force forward it.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
