### PR TITLE
LPS-162327 Create simple navigation fragment for kb articles

### PR DESCRIPTION
**Pull request by adolfopa**
This implements a simple navigation fragment for kb articles.
image
This works for both display pages and explicitly mapped fragments in regular pages. There are two possible friendly urls for articles: 
1. `/k/article-url-title` if the root article hangs directly from the root folder.
2. `/k/folder-url-title/article-url-title` if the root article is in folder with url title `folder-url-title`.

In any case, I need for @boton or @ambrinchaudhary to apply some styles to the navigation pane. I've added some css classes to the markup (e.g. `kb-article-expanded`) in the places that you need to pay attention to.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@boton I rebased and added a minor improvement (last commit). With respect to the styles, they can be customized from the page editor, but I think we should provide a minimum: no bullets and emphasize current article (kb-article-selected).

**Comment by adolfopa** [comment]
@boton Other than the css tasks I mentioned above, everything is done. Once you apply some minimal styles this should be ready for review/forward.

**Comment by boton** [comment]
Pushed some changes, including a naif implementation of inline CSS 7fa4b8a8b3aa57c8ca5af361ff735751c52125fe.

I don't know how to wire the _writeCss method b3b0b2aebf997d6941d7b3e89657a5be0ff2be68.

**Pull request closed without merging**
