### PR TITLE
LPS-134653 Rename "Documents & media" tab to "files" to clarify users

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Tab renamed following the PTR https://issues.liferay.com/browse/PTR-2462

**Before:** 
Screenshot 2021-07-06 at 15 40 38

**After:** 
Screenshot 2021-07-06 at 15 37 21

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci.test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
