### PR TITLE
LPS-199428 XMATLAB case has to be handled in the metadata processor to avoid set wrong ContentTypes

### PR DESCRIPTION
**Pull request by robertoDiaz**
This is a followup for https://github.com/liferay-lima/liferay-portal/pull/4801

It seems that the wrong mime type is also appearing in the content type of the metadata extracted

@adolfopa I've added [LPS-199428 We want to replace part of the extracted contentType not o…](https://github.com/liferay-lima/liferay-portal/pull/4813/commits/cf14c72650058ed7cac69aa452b7edaa419d58a9) since it seems to be a bug (I see it while reviewing the previous pull - https://github.com/liferay-lima/liferay-portal/pull/4808)

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
updating the baseline and resending ASAP

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Hi @robertoDiaz , there are still rebase errors. Please fix it and then I will continue to analyze this PR and forward. Thanks.

**Comment by robertoDiaz** [comment]
Hi @WYZ-Issac 

I rebased it yesterday morning.

Please force forward it as fast as possible once I rebase it again because it's highly probable that this rebase error will happen again.

Regards

**Comment by robertoDiaz** [comment]
@WYZ-Issac updated! 😃

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
ci:stop

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
Because ci failure, force forward does not work. Forward this PR to BChan manually. https://github.com/brianchandotcom/liferay-portal/pull/142688

**Pull request closed without merging**
