### PR TITLE
LPS-124970 Set initial size and avoid substring call

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
WorkflowWiki#ApproveFrontPageUserEdit is a fluke issue, filed [LRQA-64350](https://issues.liferay.com/browse/LRQA-64350), rerun it.

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
Resend it here to quarantine failed test: https://github.com/liferay-lima/liferay-portal/pull/1360

**Pull request closed without merging**
