### PR TITLE
LPS-163941 | Automate ItemSelector#CanUploadImageInWikiPage

### PR DESCRIPTION
**Pull request by jaimelr10**
Description: Creation of Priority 3 test to check that an image can be uploaded from the Wiki image uploaderin [LPS-163941](https://issues.liferay.com/browse/LPS-163941)

Jira Ticket: https://issues.liferay.com/browse/LPS-163941

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
**Reviewing...** :eyes:

**Comment by austinchiang** [comment]
Sent in https://github.com/liferay-lima/liferay-portal/pull/3776

**Pull request closed without merging**
