### PR TITLE
LPS-124047 Returning the embeddable html directly from the item selector

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
SF failing due to a revert, will be fixed buy @4lejandrito

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1178.

**Pull request closed without merging**
