### PR TITLE
LPS-127252 Add external reference code to MBMessage

### PR DESCRIPTION
**Pull request by javierdearcos**
Hello team,

In the APIs we need to get and manage entities by an external reference code (ERC) so we need to add this new fields to all portal entities.

This issue come after a long discussion about reusing a existing field or creating a new one and the decision was creating a new one to be more confident that the new code does not interfere with any existing feature.

To be able to used the Service Builder generated code with the external-reference-code attribute we have made some modifications on Service Builder to specify if the scope of the ERC is Company (as it always has been) or Group. After this modification this is the first entity where we are using it to create a ERC scoped by group for MBMessage.

To try to make the least code modifications possible I've passed the externalReferenceCode as a Service Context attribute to get it in the addMessage and updateMessage methods in the MBMessageLocalServiceImpl. I've thought a lot about doing it this way instead overloading the methods. Please, check if this approach is desirable and tell me if you feel it is better to overload this methods passing the new externalReferenceCode parameter. In case there is no ERC, the messageId will be used as a String.

I've also modified the datahandler for import/export, made the database upgrade process populating the new externalReferenceCode column with the messageId, and made some tests to be sure the code is working.

Please, take a look at this PR when you can and let me know if you require any change or there is something you don't understand.

Thank you very much!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
Hello team,

As I was not sure about using the ServiceContext or overloading existing methods with the new externalReferenceCode parameter, I want to ask you:

Would it help in the review to send you an alternative implementation in other PR overloading the methods for you to check which you consider it is the best approach?

Thank you!

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
