### PR TITLE
LPS-116103 Not possible to create link to another wiki page in wiki content

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @liferay-lima Team

Could you please review this pull request?
The explanation is in the LPS.

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/348

**Pull request closed without merging**
