### PR TITLE
LPS-117012 Don't assume task submitter has owner view permissions

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-117012

When in workflow, implicitly grant VIEW permissions to the task submitter instead of assuming it will have owner VIEW permissions. Both DM and workflow rely on this assumption.

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-117012.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
As talked on Slack this will be the expected behavior (by now)

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
