### PR TITLE
LPS-130463 / LPS-124408 / LPS-129242 Add Google Cloud auto translations

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by boton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by adolfopa** [comment]
@boton I've push-force'd some minor changes:
- Add the .lfrbuild-portal file so that the module is deployed on ant all.
- Add missing configuration lang key.
- Add a couple of "Build lang" commits.
- Squash some of the changes in LPS-130463 into LPS-124408 to make the changeset cleaner.

**Comment by adolfopa** [comment]
@boton I push-force'd, adding an additional commit to use the new `compileIncludePlatform` directive.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1761

**Pull request closed without merging**
