### PR TITLE
LPS-136069 Don't assume endpoint/region are defined

### PR DESCRIPTION
**Pull request by adolfopa**
@AliciaGarciaGarcia We need to test this with Amazon S3. I've tested it with IBM S3 and it works fine.

Once you got the S3 credentials, you should try to migrate to the store providing only the required fields in S3StoreConfiguration (i.e. region and endpoint empty). If that works, this can be forwarded.

Also, we'll need to backport this to 7.3 and 7.2.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Tested with Amazon S3 and it works as expected. Ready to forward @AliciaGarciaGarcia

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
