### PR TITLE
LPS-128432 Check first if httpServletRequest is not null before sessionErrors to avoid a NPE

### PR DESCRIPTION
**Pull request by jkappler**
Hi @liferay-lima! Found this when working on some Rest APIs, let me know if you have any questions about it.

Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just to clarify: this was found in some testings, will not call it from an API (thanks @4lejandrito)

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
