### PR TITLE
LPS-169654, LPS-169653, LPS-169657 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://issues.liferay.com/browse/LPS-169654
https://issues.liferay.com/browse/LPS-169653
https://issues.liferay.com/browse/LPS-169657

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:stop

**Comment by Jeremy-Ch** [comment]
ci:forward

**Pull request closed without merging**
