### PR TITLE
LPS-189055 Add a mechanism for massive regeneration of Video and Audio previews

### PR DESCRIPTION
**Pull request by robertoDiaz**
based in LPS-188143

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Fixing conficts

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
Hi @robertoDiaz, failures are unrelated. Please fix the conflicts and resend. If there is no new issues I will forward this directly.

**Comment by robertoDiaz** [comment]
@WYZ-Issac 

Done!

**Comment by WYZ-Issac** [comment]
ci:test:sf

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
