### PR TITLE
LPS-127421 Info Panel should extend to bottom of window

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-127421
https://issues.liferay.com/browse/LPS-149662

This fixes the info panel in Documents and Media, Knowledge Base, Adaptive Media, Redirect Web, and Site Memberships. Let me know if I missed any of your components.

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
tested on Documents and Media, Knowledge Base, Adaptive Media, Redirect
image
image
image
image

**Comment by boton** [comment]
the Poshi test failures maybe are related to the changed markup.

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Hi @pat270
There is an info icon regression caused by the fix: No response after clicking the info icon on the DM widget. could you take a look? Thanks!
cc/ @boton

**Comment by pat270** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1277401_3377

**Comment by boton** [comment]
see #3057

**Pull request closed without merging**
