### PR TITLE
LPS 183824 1

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Removes old dependencies to DDMStructure located in portal-kernel

Proposed Solution
----
Removes 7.3 deprecated method in DLFileEntryType services. Since deprecated methods are only used **DLFileEntryTypeStagedModelDataHandler** copy some logic to keep the same logic between new methods and deprecated methods, this logic is related to DDMStructureLinks and DDMStructures validation.

Please note that I removed some logic in [f6423b8](https://github.com/liferay-lima/liferay-portal/pull/4489/commits/f6423b832fe4597b03600bf714f00bb7d95e2d02) related to **serviceContext.getAttribute("ddmForm")** since it is not set, and also I've removed some old logic related with **AUTO_** prefix in DDMStructure keys in [1c0b345](https://github.com/liferay-lima/liferay-portal/pull/4489/commits/1c0b3458d62eacf538a73873b841d445a4377255), maybe we can remove more code or maybe it is wrong and we cannot delete it.

Please let me know if you have any question.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Test failures unrelated

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
