### PR TITLE
LPS-118572 Fix the name of the location in Web Content and D&M tab

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
@4lejandrito could you please review this [commit](https://github.com/liferay-lima/liferay-portal/pull/565/commits/ce2d4ba6176631181ea3e0c3313e4da5d938308a) and [the last one](https://github.com/liferay-lima/liferay-portal/pull/565/commits/93e7386e7180133889d005181e93c0f9f0723e15)?

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/569.

**Pull request closed without merging**
