### PR TITLE
LRQA-59086, LRQA-59088 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LRQA-59086
https://issues.liferay.com/browse/LRQA-59088

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
```
[beanshell] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[beanshell] 	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
[beanshell] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
[beanshell] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
[beanshell] 	at org.apache.tools.ant.Task.perform(Task.java:348)
[beanshell] 	at org.apache.tools.ant.taskdefs.Parallel\$TaskRunnable.run(Parallel.java:453)
[beanshell] 	at java.lang.Thread.run(Thread.java:745)
```
This issue is not related to my changes, it could be solved on head.

**Comment by liuxingye** [comment]
LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive7210 is a fluke issue after analysis from the poshi report.

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
