### PR TITLE
LPS-157505 rename /admin/common/ jsp on knowledge base module

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
On this PR we are renaming the jsps of the folder `/admin/common/ `

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@ambrinchaudhary @boton

**Comment by AliciaGarciaGarcia** [comment]
ci:test:knowledge-base

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1307401_3942

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
