### PR TITLE
LPS-134422 A blank tab opens when editing a portal file in Office 365

### PR DESCRIPTION
**Pull request by marcogalluzzi**
I'm not sure why the blank tab opens in this particular case since it is not reproducible. However, I've found that one reason is that the corresponding file in OneDrive has been deleted. So, I know that a blank tab opens because a masked error. Now the error will be shown, and the blank tab will not open.

See issue: https://liferay.atlassian.net/browse/LPS-134422

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
Failures are unrelated. Forward directly.

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Pull request closed without merging**
