### PR TITLE
LPS-174903 Override the other getTitle method to avoid default behaviour of deleting the notification in some cases

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to override the other `getTitle` method of the `BaseModelUserNotificationHandler` class. The target of overriding that method is to avoid the `getTitle` invocation that deletes the `UserNotificationEvent` in case there is no `AssetRenderer`.

---

**Before the PR:**

Once the notification is shown, the next time there are no notifications in the notification list:

image

---

**After the PR:**

Once the notification is shown, the next time the notifications are shown in the notification list:

image

image

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:notifications

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:notifications

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
@ccorreagg 

Can you take a look to this error that is failing on the relevant that if is caused by this PR?

[LocalFile.ObjectFields#CannotEditERCField](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134376//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ObjectFields_CannotEditERCField_)

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
thanks!

> > @ccorreagg
> > Can you take a look to this error that is failing on the relevant that if is caused by this PR?
> > [LocalFile.ObjectFields#CannotEditERCField](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/134376//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ObjectFields_CannotEditERCField_)
> > Thanks!
> 
> Hi @AliciaGarciaGarcia ,
> 
> Our QA team confirm that it is a flaky test, so it could be forwarded manually

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr, manually send to BChan: https://github.com/brianchandotcom/liferay-portal/pull/129969

**Pull request closed without merging**
