### PR TITLE
LPS-192024 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://liferay.atlassian.net/browse/LPS-192024

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Waiting for https://liferay.atlassian.net/browse/LPS-191330 to be fixed before forwarding

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
