### PR TITLE
LPS-165775 Redirection error when saving page SEO settings

### PR DESCRIPTION
**Pull request by sontruongces**
Forwarded from sontruongces#50

Motivation
=======

This work solves the problem reported in the [LPS-165775](https://issues.liferay.com/browse/LPS-165775) ticket.

Proposed Solution
========

Cause:
- Regression-bug after [commit](https://github.com/brianchandotcom/liferay-portal/compare/57434f4e59...2ea93d113d). 
If we use `portlet:actionURL` and `portlet:param`, `HttpComponentsUtil#shortenURL` will remove `redirect` param because the URL is too long.

What I/we did to solve this problem:
- I use `aui:input` instead of `portlet:param` for `redirect` param.

Steps to Verify
========
1.Go to Site Builder and add a new widget page to the site.
2.Navigate to the configuration page of the site.
3.Click the SEO panel and save.

Actual result:
-Redirection to the page.
Expected Result:
-Stay in the SEO setting panel.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @sontruongces 
Please, remember that you have to change manually the status of the ticket, not only to assign it to you.

Thanks!!

**Comment by sontruongces** [comment]
> Hi @sontruongces Please, remember that you have to change manually the status of the ticket, not only to assign it to you.
> 
> Thanks!!

Hi @AliciaGarciaGarcia, thanks for your feedback. Right now, we don't have permission to change the status of the ticket. But we are requesting. We will update it ASAP. Sorry for this inconvenience!

**Comment by AliciaGarciaGarcia** [comment]
> @sontruongces

Oh! I didn't know about the permissions issue, I will change it myself!

Thanks for the feedback!

**Comment by AliciaGarciaGarcia** [comment]
@sontruongces let me know if you have another tickets you want me to status move!  ;)

**Comment by sontruongces** [comment]
Hi @Hanlf,
The fix was updated by @TaiPhamLR. Please help us to review. Many thanks!

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @sontruongces @TaiPhamLR 

I do not feel confortable duplicating the parameter.

I think that the main problem here is that on the fix I made on [commit](https://github.com/brianchandotcom/liferay-portal/compare/57434f4e59...2ea93d113d) 
I didn't realized that we were duplicating the params (in some cases, overwriting them) with the `copyCurrentRenderParameters="<%= true %>"` I do not think that on this case is needed, 

What do you think about this solution?

let me hear your feedback

Thanks!

**Comment by TaiPhamLR** [comment]
Hi @AliciaGarciaGarcia,
Thanks for your review. I fixed the code based on your comment.
Regard.

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
