### PR TITLE
LPS-89224 adapt to new implementation of Store

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/98441

**Comment by adolfopa** [comment]
Just started reviewing :)

**Pull request closed without merging**
