### PR TITLE
LPS-190823 escape html

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-190823

How to test:

1. Create a “Parent” wiki page with any content you want
2. Add a child page under the “Parent” page.
3. For the page content, enter <script>alert(123)</script>
4. There is no need to switch to “Source” mode when writing the content
5. View the “Parent” page.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
