### PR TITLE
LPS-170857

### PR DESCRIPTION
**Pull request by mbowerman**
Notes from @javalosjr96:

> Ticket: [LPS-170857](https://issues.liferay.com/browse/LPS-170857)
> 
> Issue:
> This bundle of libraries contains a vulnerability that was resolved in a different ticket, however it does make any changes to the contents of this bundle. 
> 
> Solution:
> Upgrade google.cloud:libraries-bom to 26.1.5

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:translation

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
waiting to ci:test:translation tests to forward

**Comment by javalosjr96** [comment]
@AliciaGarciaGarcia 
Looking at the error, I can see that it's translated, but the element is not found?

Is this something I need to take a look at?

**Comment by adolfopa** [comment]
ci:reevaluate:1307401_5798

**Comment by austinchiang** [comment]
@javalosjr96 @AliciaGarciaGarcia the failing test is not related to this pull. From the test perspective I think we're good here

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
