### PR TITLE
LPS-191375 Fix usages of '+' in friendly urls

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-191375

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-191375.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
IMHO, the commits messages and what is doing has no sense.

maybe we lost something on the rebase?

**Comment by adolfopa** [comment]
Sounds good.

**Pull request closed without merging**
