### PR TITLE
LPS-149230 Add Dynamic Rendering for JavaScript SEO

### PR DESCRIPTION
**Pull request by sammonsjl**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by sammonsjl** [comment]
ci:test:relevant

**Comment by sammonsjl** [comment]
ci:forward

**Pull request closed without merging**
