### PR TITLE
LPS-152217: Expose ERC in WikiPageAttachment

### PR DESCRIPTION
**Pull request by sergiojimcos**
Hi guys, I've opened this PR because most of the service changes I've made are related to your components. I'm going to introduced what are the changes that you should reviewed. Our team has verified that the errors appearing in the CI are not related, but we still want your approval, you can see [here](https://github.com/liferay-frontend/liferay-portal/pull/2512). You can check the desciption in the link of the PR from frontend-infra. Let's give you a little context.

## Main Objective
The main of this PR is to expose `externalReferenceCode` in WikiPageAttachments. For that reason I have made some changes in the service part and in the API part.

## Service part
The main changes that you should review, are the following:

- Those changes related to `PortletFileRepository` in portal-kernel. These changes are related because we add the new argument using `externalReferenceCode`.
- In the same way, in those modules I have implemented a new method to obtain a DLFile usign the `externalReferenceCode`, which is `getPortletFileEntryByExternalReferenceCode` .
- As there are some changes that affect the service part of DLFile, I want to be sure that the Staging mode works correctly, some changes are added.

## API part
However, this part can be ignored, beause it is reviewed by our members of the team.

If you have any problem, or any doubt, please contact me :smiley: 

**JIRA TICKET**
https://issues.liferay.com/browse/LPS-152217

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:wiki:norebase

**Comment by austinchiang** [comment]
ci:test:relevant:norebase

**Comment by AliciaGarciaGarcia** [comment]
Hi @sergiojimcos can you rebase and resent to check again the tests 

Thanks!

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci is working great...

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:relevant

**Comment by sergiojimcos** [comment]
ci:test:wiki

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1377401_3999

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by sergiojimcos** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The two failures should be flaky issues. re-run it.

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1297401_4065

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
Reviewing...

**Comment by liuxingye** [comment]
[LocalFile.DMPermissions#ViewDocumentWithOwnerAccessOnly](https://testray.liferay.com/home/-/testray/case_results/1943462862?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D1943461044%26testrayRunId%3D1943462399%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) is consistenty failing when forwarding this PR. But I cannot reproduce the issue locally about assign newly user to a site. Resend it here with fixes (assign newly user to a site via JSON) https://github.com/liferay-lima/liferay-portal/pull/3358

cc @sergiojimcos @AliciaGarciaGarcia

**Pull request closed without merging**
