### PR TITLE
LPS-158318 GroupThreadLocal.getGroupId() will always return as default value GroupConstants.DEFAULT_LIVE_GROUP_ID so we can cast to long and check if the value is that

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPS-158318 GroupThreadLocal.getGroupId() will always return as default value GroupConstants.DEFAULT_LIVE_GROUP_ID so we can cast to long and check if the value is that

https://user-images.githubusercontent.com/47524751/179209891-77325485-848c-489a-b692-422ab08d89df.mp4

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Pull request closed without merging**
