### PR TITLE
LPS-113659 Added frontend tests

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
@AliciaGarciaGarcia @4lejandrito SF error??!! :'-( I found that pattern in other .properties files...

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hey @wincent @jbalsas, [here](https://github.com/liferay-lima/liferay-portal/pull/46/commits/219ea7f42425dda40a6160175187a93562392907) I had to add an inline validation for an input to check whether it is a valid url or not. The requirement was to add the same validation present in "SEO configuration", where it is using `<aui:validator name="url" />`, so I replicated the REGEX_URL that was doing that(_/frontend-js-aui-web/src/main/resources/META-INF/resources/liferay/form.js_). What do you think, should I move this validation somewhere else? Should I use something different? 
Thanks in advance.

**Comment by wincent** [comment]
@ambrinchaudhary: I think it's probably ok to unblock yourself with a local workaround like this, but obviously in the long term we don't want multiple people to have to copy-paste a ghastly regex like that. I think we should probably open an issue on [liferay-frontend-guidelines](https://github.com/liferay/liferay-frontend-guidelines) specifically for form validation, so that we can start building a list of use cases and from there provide some out-of-the-box standard validations.

For reference, seeing as we already have [Formik](https://github.com/jaredpalmer/formik) in frontend-js-react-web, I think the most likely solution that we'd provide would be built around that. They have a [small example of sync form validation with Formik here](https://codesandbox.io/s/q8yRqQMp).

**Comment by jbalsas** [comment]
Not necessarily a form validation system and I think Formik has some facilities for this, but something I saw some weeks ago and I liked was [DeepWaters](https://antonioru.gitbook.io/deep-waters/). Just adding it here so I don't forget and we can bring this over to guidelines.

**Comment by AliciaGarciaGarcia** [comment]
see https://github.com/liferay-lima/liferay-portal/pull/55

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Pull request closed without merging**
