### PR TITLE
[TS] LPS-137263

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-137263

### Update overview

Resend of a past pull request.

* https://github.com/liferay-lima/liferay-portal/pull/2282
 
Renamed parameter (`parentDDMStorageId` -> `copyDDMStorageId`) which makes it more obvious that we're not trying to deprecate the old method, and renamed the method to `copyLayoutSEOEntry` based on feedback from Brian. Also applied the requested parameter reordering.

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:forward

**Pull request closed without merging**
