### PR TITLE
[TS] LPS-149025 | Sitemap shows all the available languages instead of only the current ones missing test

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-149025
Thank you!

--- 
This is a follow-up pull to provide the missing integration test for the LPS.
 The test was requested on this pull: https://github.com/brianchandotcom/liferay-portal/pull/114931

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:stop

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
