### PR TITLE
LPS-141436 The Document types and the Metadata Sets should not have guest & site member view permission by default

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
The Document types and the Metadata Sets should not have guest & site member view permission by default

image

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
We have to add paragraph to _BREAKING_CHANGES.markdown_?

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia The changes look ok, but I'm not sure if this will work. Can you verify if something fails when viewing (as guest) the details of a document of a type? The user should have permissions for the document, but not for the document type. I think that will fail (but I'm not sure); we may need to use some local services in DM to fix that.

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa the details (info) of the document type (and metadata) fail on guest always 
Because DE is searching the user and the user do not exists (I remember talking about it long time ago) so the behavior do not change with this.

When a site member do not have access to view it, the elements it is not show because it do not have permissions on https://github.com/liferay/liferay-portal/blob/8f954b387b2baad091750af112d76d6bfcf72379/modules/apps/data-engine/data-engine-rest-impl/src/main/java/com/liferay/data/engine/rest/internal/renderer/v2_0/DataLayoutRendererImpl.java#L63 . The field is present but the content is not shown.

we can talk about it on a meeting.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
