### PR TITLE
LPS-180179 Blog/DM with a DPT can not be accessed through the old friendly URL

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-180179
https://issues.liferay.com/browse/LPS-180047

This fixes two bugs related to the context path. When using a proxy (or changing the ROOT context path), friendly url redirection wouldn't include it and the redirection would fail.

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-180179.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by WYZ-Issac** [comment]
The above failures are not related to your pull. I will forward this directly,

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
ci:forward:force

**Comment by WYZ-Issac** [comment]
Forward to BChan. https://github.com/brianchandotcom/liferay-portal/pull/135629

**Pull request closed without merging**
