### PR TITLE
LPS-142767 Workflow issue when leaving comment and assigning to Self

### PR DESCRIPTION
**Pull request by holatuwol**
Additional details on https://issues.liferay.com/browse/LPS-142767
Redirected here from https://github.com/liferay-frontend/liferay-portal/pull/1762

### Steps to reproduce

1. Start liferay and enable the Single Approver workflow for Web Content Articles
1. Create a Web Content Article
1. Access the workflow for the Article
1. Add a comment to the workflow below
1. Assign the Review to yourself at top right corner

### Solution notes

We forced skipEditorLoading to true to resolve [LPS-81691](https://issues.liferay.com/browse/LPS-81691), but based on testing done by @fortunatomaldonado, the issue is no longer reproducible even when we set it to false, so this solution made sense to me.

Please let us know if there are any questions or anything else you'd like us to test.

### CODE REVIEW

**Comment by adolfopa** [comment]
@boton Can you take a look at this? This looks Ok to me.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
Thanks, @fortunatomaldonado @holatuwol for the PR, it works great. 

I don't understand it at first, because it seems like it couldn't be related to JS if there was a reload in the middle of the process. 

Then I figured out that the `Liferay.Portlet.refresh (`#p_p_id _ $ {portletDisplayId} _`, data, true);`  is updating the URL and it works fine once because CKEDITOR is loaded but we break all the following refresh if CKEDITOR isn't loaded.

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
