### PR TITLE
LPS-174587 add admin portlet to the search option

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
**Steps to reproduce:**

1. Navigate to Content & Data > Wiki
2. Click "Main" Wiki Node
3. Search for "front"
https://issues.liferay.com/browse/LPS-174587

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
