### PR TITLE
LPS-180446 Images missing after upgrade from U70 to U71

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-180446

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-180446.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by lucasperj** [comment]
Tested manually at `8ac53d398fd24e827769ffb1b41868aeaab72e2c` with the PR changes. Blocker not present.

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by adolfopa** [comment]
ci:reevaluate:1387401_7196

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward:force

**Pull request closed without merging**
