### PR TITLE
LPS-198670 check if the size of the items to be copied is allowed on destination

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-198670

image

**Note**: I left the same message than in source, but it appears once you select the destination and try to make the action.

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]
Frontend changes LGTM

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by Jeremy-Ch** [comment]
Checking

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Pull request closed without merging**
