### PR TITLE
LPS-129893

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @marianoalvarosaiz,

The tests failures are not related to your changes. Can you rebase and push force?

**Comment by marianoalvarosaiz** [comment]
@4lejandrito see https://github.com/liferay-lima/liferay-portal/pull/1702

**Pull request closed without merging**
