### PR TITLE
LPS-116622 Prevent "WARN Discrepancy between expected target -- and target in document --, Using --" with the reading of the file attribute

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa can you review it?
Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
The error on SF
```
 'sub' should not be followed by an uppercase character for variable 'startSubDocument': ./modules/apps/translation/translation-web/src/main/java/com/liferay/translation/web/internal/importer/XLIFFInfoFormTranslationImporter.java 180 (Checkstyle:CamelCaseNameCheck)
```


but If I change it:

```
 Typo in variable 'startSubdocument', expected variable name 'startSubDocument':
 ./modules/apps/translation/translation-web/src/main/java/com/liferay/translation/web/internal/importer/XLIFFInfoFormTranslationImporter.java 180(Checkstyle:VariableNameCheck)
```

Any suggerency?

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/443

**Pull request closed without merging**
