### PR TITLE
LPS-119610 LPS-119663 Visual issues with Blogs Cards and More Blogs entries

### PR DESCRIPTION
**Pull request by boton**
We have visual problems in `More Blogs entries` and In blogs with **display template:** `Card`.

**Steps to reproduce:**

1. Add blog entry with a long word in the title (this is not reproducible with no long word no matter how long the title is; see figure below)
2. Add another blog entry with a long word in the title
3. Configure blog widget > Display template: card

**Before the fix:**
image

**Fixed some issues: [LPS-119610](https://issues.liferay.com/browse/LPS-119610)** 
image
But discover other issues, the actions are misaligned and are unclickable in **display template:** `Card` and the card footer is not positioned at the bottom of the card.

**Fixed more issues: [LPS-119663](https://issues.liferay.com/browse/LPS-119663)**
image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
