### PR TITLE
LPS-131801 | master

### PR DESCRIPTION
**Pull request by liuxingye**
Steps to reproduce: 
- Go to Documents and Media 
- On + button, select File Upload or Google Drive shortcut

**Before** for File Upload option: 
Screenshot 2021-07-09 at 13 44 23

**After**  for File Upload option: 
Screenshot 2021-07-09 at 13 38 48

**Before** Google Drive shortcut:
image

**After** Google Drive shortcut: 
image

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@liuxingye Can we forward this? Or is this on hold?

**Comment by liuxingye** [comment]
ci:forward

**Comment by liuxingye** [comment]
@adolfopa Just forwarded it. Thanks

**Pull request closed without merging**
