### PR TITLE
LPS-141976 Refresh the modal data even if the input is not localizable

### PR DESCRIPTION
**Pull request by boton**
Now I always request to get the data from the server even if it is not localizable.

### CODE REVIEW

**Comment by boton** [comment]
@adolfopa It may be a better way not to request data for not localizable inputs, but we don't have enough data in front for now.

There is my state and I need to change the current for one value of the history array, but the current doesn't have `friendlyURLEntryId` nor `friendlyURLEntryLocalizationId`.

```
{
    "en_US": {
        "current": {
            "urlTitle": "/mb-1"
        },
        "history": [
            {
                "urlTitle": "/mb-2",
                "friendlyURLEntryId": 43502,
                "friendlyURLEntryLocalizationId": 516
            },
            {
                "urlTitle": "/mb",
                "friendlyURLEntryId": 43501,
                "friendlyURLEntryLocalizationId": 505
            }
        ]
    }
}
```

IMHO it's good enough but you can close this PR and we can work on it if you prefer.

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
