### PR TITLE
LPS-164481 KB preview general styles

### PR DESCRIPTION
**Pull request by boton**
## Issue: https://issues.liferay.com/browse/LPS-164481

**Before this PR**
image

**After this PR**
image

**Note:** I left the inside padding on the suggestion section because It's the default when we put panels inside a `.sheet`, removing it feels hacky.
image

**Note 2:** I noticed a bug when I working on this I open a issue on https://issues.liferay.com/browse/LPS-164491

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:reevaluate:1327401_6081

**Comment by boton** [comment]
These fails look legit https://github.com/liferay-lima/liferay-portal/pull/3541#issuecomment-1267171541 I update the markup of the title, we need to update some tests here. 🆘

**Comment by david-gutierrez-mesa** [comment]
test fix send here: https://github.com/liferay-lima/liferay-portal/pull/3559

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
