### PR TITLE
LPS-173703 External video cannot be added because of file ending restrictions

### PR DESCRIPTION
**Pull request by adolfopa**
Dear Team,

Could you please review this pull request?

Motivation
=======
When documents of only certain extensions are allowed, the extension validation will fail on external video shortcuts because those documents do not have an extension.

Proposed Solution
========
Skipping the extension validation for documents where an extension is not present in the name, no file is being uploaded, and the document type scope is system.

Steps to Verify
========
Please consult the linked LPS for reproduction steps.
https://issues.liferay.com/browse/LPS-173703

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr.

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_8681

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
As talked on Slack this will be the expected behavior (by now)

**Comment by Jeremy-Ch** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are not related to this pr, send ro BChan. https://github.com/brianchandotcom/liferay-portal/pull/129888

**Pull request closed without merging**
