### PR TITLE
LPS-196251, LPS-196252, LPS-196254, LPS-196266, LPS-196267, LPS-196268 | Master

### PR DESCRIPTION
**Pull request by Jeremy-Ch**
https://liferay.atlassian.net/browse/LPS-196251
https://liferay.atlassian.net/browse/LPS-196252
https://liferay.atlassian.net/browse/LPS-196254
https://liferay.atlassian.net/browse/LPS-196266
https://liferay.atlassian.net/browse/LPS-196267
https://liferay.atlassian.net/browse/LPS-196268

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Comment by Jeremy-Ch** [comment]
ci:test:sf

**Pull request closed without merging**
