### PR TITLE
LPS-190459 DM Versions - remove checkboxes and add pagination 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
The pagination does not work properly, please @AliciaGarciaGarcia help me reviewing this. Thanks a lot!

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @ambrinchaudhary 

I added the start/end to the obtain the version and NOW happens the same on the order.

I will take a look 

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
see https://liferay.atlassian.net/browse/LPS-191947

The last 2 commits mitigate the previous issue, but we have to think about it with time.

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by ambrinchaudhary** [comment]
Thanks @AliciaGarciaGarcia , looks fine to me. Let's wait to Sam's review.

**Review by SamZiemer — APPROVED** [review]
These changes look good to me

**Review by SamZiemer — APPROVED** [review]

**Comment by Jeremy-Ch** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Jeremy-Ch** [comment]
The failures are unrelated.

**Comment by Jeremy-Ch** [comment]
ci:forward:force

**Comment by SamZiemer** [comment]
ci:forward

**Pull request closed without merging**
