### PR TITLE
LPS-164481, LPS-164246, LPS-162852, LPS-162970 | Master

### PR DESCRIPTION
**Pull request by austinchiang**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
@boton @ambrinchaudhary I combined the KB pulls here. I was only able to solve some issues from the other pulls since I have some issues building the bundle locally today, so I am rerunning the tests here after a partial fix and will rebuild again to fix the rest of the issues.

**Comment by Jeremy-Ch** [comment]
Note: For the failure: [LocalFile.KBPageTree#PageTreeIsCollapsedAfterOpeningProductMenu](https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/261741//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_KBPageTree_PageTreeIsCollapsedAfterOpeningProductMenu_), we should update the test because https://issues.liferay.com/browse/LPS-164471

**Comment by austinchiang** [comment]
ci:test:knowledge-base

**Comment by austinchiang** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
Resent in https://github.com/liferay-lima/liferay-portal/pull/3567

**Pull request closed without merging**
