### PR TITLE
[TS] LPS-146530 Document Does Not Checkin after Edit in Office 36

### PR DESCRIPTION
**Pull request by boton**
Follow up #2704.

@NemethNorbert your changes are correct, I only add an Auto SF commit and fix the test to add a mock to `Liferay.destroyComponent`

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by NemethNorbert** [comment]
> Follow up #2704.
> 
> @NemethNorbert your changes are correct, I only add an Auto SF commit and fix the test to add a mock to `Liferay.destroyComponent`

LGTM :)

**Comment by boton** [comment]
ci:forward

**Pull request closed without merging**
