### PR TITLE
LPS-192974 DM Change filter title

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
**After the changes:** 

Screenshot 2023-08-08 at 18 12 11

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward:force

**Pull request closed without merging**
