### PR TITLE
LPS-152104 Remove LayoutSEOLinkManager and LayoutSEOCanonicalURLProvider deprecated methods

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-152104

See: https://github.com/brianchandotcom/liferay-portal/pull/116341#issuecomment-1103844397

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by lfbesada** [comment]
I am sorry for the source formatting issues, I just fixed them.
Thanks!

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Sorry for the inconvenience, this PR deletes the methods used by the other PR that I have sent with the integration tests. I should wait for that one to pass and then send this one making them call the new methods.
Sorry for the inconvenience, I'll forward this PR later

**Pull request closed without merging**
