### PR TITLE
LPS-194352 Sanitize html in all cases(BBCode as well)

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]
I tested this and works perfectly!!! 

As Roberto and I previously discussed, we think it makes sense to sanitize all the html code in MB. 
What was happening here is that even if we are supposed to write in bbode, the user could enter html code and it was not being sanitized (internally, it "escapes" when the content type to sanitize is not HTML)

**Comment by ambrinchaudhary** [comment]
ci:test:message-boards

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
Poshi failure could be related with this pull, we need to check it before forwarding

**Comment by ambrinchaudhary** [comment]
@robertoDiaz 
There is a poshi test that when you set the body to `<script>alert(123);</script>`, it saves it 
`Assert that 'THREAD_BODY' equals the value '<script>alert(123);</script>'`

But now with this fix the sanitizer removes the tag. What do you think, is the new behaviour correct and the poshi test should be updated?

**Comment by robertoDiaz** [comment]
It seems to be a happy test.

What's the point of assert this?

@manoelcyreno , @austinchiang is on PTO and told us to ask you for help in this cases.

We'd like to change this test (and assert current behavior -alert is been removed or "disabled", or remove the test directly)

Can you help us?

**Comment by epark18** [comment]
ci:test:relevant

**Comment by epark18** [comment]
Results here look good to me. I triggered the test suite before test was updated to be quarantined. This is good to go on QA side.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
