### PR TITLE
LPS-204350 Improve friendly url matching performance

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this trying to solve?

https://liferay.atlassian.net/browse/LPS-204350

This is a followup; there's a potential performance problem in the
original solution.

# How am I fixing it?

Improving the performance by avoiding iterating over all site pages.

# How can you verify that it works?

Follow the steps described in https://liferay.atlassian.net/browse/LPS-204350.

### CODE REVIEW

**Comment by adolfopa** [comment]
@mbowerman This is a followup to a fix you sent to us recently.

cc/ @robertoDiaz @lfbesada

**Review by marcogalluzzi — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by SylviaLuan** [comment]
ci:stop

**Comment by SylviaLuan** [comment]
ci:forward

**Pull request closed without merging**
