### PR TITLE
LPS-185879 Preview and thumbnails are not override when checkin with “Keep Current Version Number”

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://issues.liferay.com/browse/LPS-185879

Steps to reproduce

It happens to with video (and I suppose that with audio/other preview)

1. Go to Content & Media > Documents and Media > “+” > File Upload
2. Select 1 PDF File which has Thumbnail and Publish
3. Select (⋮) button on it, and click “Checkout”
4. Select (⋮) button again and click “Edit”
5. Select PDF File (which is not include same Thumbnail with step3) and save
6. Note: Thumbnail is changed to New picture
7. Select (⋮) button, and click “Checkin”
8. Select “Keep Current Version Number” and Save

It happened that previews are no clean after the deletion of the fileversion

- LPS-185879 when you delete a file entry that is a PWC make a cleanup of the previous trusted version of the file to make it new previews and thumbnails with the content con the correct version
- LPS-185879 remove the dlFileVersionPreview when removing the dlFileVersion
- LPS-185879 extract method
- LPS-185879 clean up the deleted file version previews and thumbnails

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by robertoDiaz — APPROVED** [review]

**Comment by robertoDiaz** [comment]
LGTM

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa 
BundleSiteInitializerTest portalLogErrors were relevant so I added some check.

Please contact via Slack for more info

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
rebased with master

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
