### PR TITLE
[TS] LPS-159600

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a proposal for [LPS-159600](https://issues.liferay.com/browse/LPS-159600) based on the conclusion obtained in [PTR-3223](https://issues.liferay.com/browse/PTR-3223)

This solution adds a new parameter that is added for pages' URLs in the page administration and read by FriendlyURLServlet and a new JSPDynamicInclude in order to know if an info message with a link to the skipped redirect has to be displayed.

Only users with update permissions can skip the redirect with the new parameter informed.

Additionally, the redirections are skipped for the exclusive and pop-up window states.

Please, feel free to let me know if any clarifications are needed or if any suggestion or any different approach could be taken for this fix.

Thanks in advance!

\cc @robertoDiaz

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:stop

**Comment by dacousalr** [comment]
SF error fixed in https://github.com/liferay-lima/liferay-portal/pull/3340

**Pull request closed without merging**
