### PR TITLE
LPS-122267 Add expirationDate and reviewDate to fileEntry and fileVersion tables. And add the addFileEntry to the local service

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
LPS-122267 Add expirationDate and reviewDate to fileEntry and fileVersion tables. And add the addFileEntry to the local service

First PR of the
Where we add the new fields to the table and to the addFileEntry method on the local service.

this PR do not have presence on the portal more than the tables. 
the next PR will update the update method, and go further to the front.

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Hi @AliciaGarciaGarcia ,

From the screenshots for the [PortalSmokeUpgrade tests](https://testray.liferay.com/zh/home/-/testray/case_results/1529318922) on the testray, the DM portlet is temporarily unavailable after ungrade, may be related to your pull, could you please take a look? If you need to a db dump or any other help, feel free to let me know.
screenshots

**Comment by AliciaGarciaGarcia** [comment]
ci:test:stable

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
WorkflowForms#SubmitPublishedFormWithTextField is a fluke and lpkg-base-jdk8/0 failure should be a comment failure, will rerun it.

**Comment by Hanlf** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Pull request closed without merging**
