### PR TITLE
LPS-132566 Language keys are missing for MB user moderation in workflow configuration

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Review by AliciaGarciaGarcia — APPROVED** [review]

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by Hanlf** [comment]
ci:forward

**Comment by Hanlf** [comment]
The above failure is not related to this PR, resent it to BChan directly here: https://github.com/brianchandotcom/liferay-portal/pull/103736

**Pull request closed without merging**
