### PR TITLE
LPS-191466 | Master

### PR DESCRIPTION
**Pull request by WYZ-Issac**
https://liferay.atlassian.net/browse/LPS-191466

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by WYZ-Issac** [comment]
ci:test:help

**Comment by WYZ-Issac** [comment]
ci:test:blogs

**Comment by WYZ-Issac** [comment]
ci:forward

**Pull request closed without merging**
