### PR TITLE
LPS-137249, LPS-137245, LPS-137248 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-137245
https://issues.liferay.com/browse/LPS-137249
https://issues.liferay.com/browse/LPS-137248

### CODE REVIEW

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Comment by Hanlf** [comment]
@austinchiang fyi, some SF failure here

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
