### PR TITLE
LPS-170387, LPS-170146, LPS-168604 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-170387
https://issues.liferay.com/browse/LPS-170146
https://issues.liferay.com/browse/LPS-168604

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
ci:test:depot

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
