### PR TITLE
LPS-197315 breaking changes amend

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @almonwork 

Can you review the message and tell me if this is correct?

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
Hi @adolfopa 

Thanks for the review, I wanted @almonwork to review it before. 

maybe my fault, I should put it as draft better.

I closed the Brian PR. I need the OK from Montero first .

**Comment by almonwork** [comment]
It looks good. Thank you very much @AliciaGarciaGarcia

**Comment by AliciaGarciaGarcia** [comment]
see https://github.com/liferay-lima/liferay-portal/pull/4759

**Pull request closed without merging**
