### PR TITLE
LPS-132333 show on the edition/creation page the new 

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
This PR is the result of the review made on https://github.com/brianchandotcom/liferay-portal/pull/102325 about the  LPS-132333 

> 1.)
> 
> src/main/java/com/liferay/document/library/web/internal/util/FFExpirationDateReviewDateConfigurationUtil.java
> and
> src/main/java/com/liferay/document/library/web/internal/util/FFImageEditorConfigurationUtil.java
> 
> should be in
>  com.liferay.document.library.web.internal.configuration.* and not in internal.util

And

> 
> 2.) DLFileEntryFinderImpl.java#findByReviewDate is not allowed. I don't want to add more finder methods.
> 
> Use the new DSLQuery API..

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
hi @adolfopa 

Please, can you check if https://github.com/liferay-lima/liferay-portal/pull/1881/commits/379648906a5bfc856eac34a5117454a225c90af6 is the correct way to apply the  new DSLQuery API. 

Thanks!!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
I'll rebase, baseline and commit the changes

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@AliciaGarciaGarcia Can you fix the rebase conflict?

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1227401_8234

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1257401_482

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1257401_482

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
