### PR TITLE
[TS] LPS-138585 

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

**Description**
If a non admin user wants to select images from documents and media, the pagination is shown wrong as it counts the private/restricted sites as well where the user does not have membership. Although the user does not see or has access to these sites.

**Expected Result:**
The pagination will show the number of pages where the user has access

**Actual Result:**
The pagination is shown wrong as it counts the private/restricted sites as well where the user does not have membership. Although the user does not see or has access to these sites.

**Solution**
Adding actionId ActionKeys.VIEW parameter to the groupParams will filter the groups

Thanks, Roland

https://issues.liferay.com/browse/LPS-138585

### CODE REVIEW

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:forward

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
@rolandpakai One of the test failures look legit. Can you take a look at it?

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
@adolfopa 
Looks better now.
Could you please push it forward?

Thanks, Roland

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
