### PR TITLE
LPS-152849 Add redirection support to display pages

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Review by AliciaGarciaGarcia — APPROVED** [review]
compiles and looks good

**Comment by AliciaGarciaGarcia** [comment]
LGTM @adolfopa when test passes > send to Echo

**Comment by adolfopa** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/8053

**Pull request closed without merging**
