### PR TITLE
LPS-142112 Blogs widget card: text overflow 

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
On a widget page with 30/70 columns: 

**BEFORE:**
30% column:
Blogs Before 30C

**AFTER:** 
30% column: 
Blogs After 30C

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by boton** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
