### PR TITLE
LPS-124162 Cast to PortletResponse because can be ResourceResponse not only RenderResponse and cast exception is happening

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @jeyvison
I made a small change on f83afb636e1e6d5f367e53cf49b8a22610a18e6c

**Comment by Hanlf** [comment]
Hi @AliciaGarciaGarcia 
AppBuilder#PublishAppAsWidgetWithOnlyTableView and PGDocumentsandmedia#RemovePortlet tests failed at [LPS-124465](https://issues.liferay.com/browse/LPS-124465) and quarantine tests under LRQA-63651.
Upgrade tests(like PortalSmokeUpgrade#ViewPortalSmokeArchive7210 ) should be caused by this pull request and only failed on this PR([history](https://testray.liferay.com/zh/home/-/testray/case_results/1361615664/history?delta=200&tab=result&testrayCaseId=1310700793&environmentHash=505855458&hideFilterPin=true&testrayRoutineId=1306753894&orderByCol=createDate_sortable&orderByType=desc&resetCur=false&cur=2)), no info panel shows after upgrading.

**Comment by Hanlf** [comment]
ci:test:bundle

**Comment by Hanlf** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
hey @AliciaGarciaGarcia ,

I think it should be a bug, there is no info **button**(not panel, sorry, typo in the last comment) after an upgrade. If I check the document and click the info button in the widget, no Automatically Extracted Metadata and Type information show up.

**Comment by AliciaGarciaGarcia** [comment]
Please see https://github.com/liferay-lima/liferay-portal/pull/1213

**Pull request closed without merging**
