### PR TITLE
LPS-164778 Use item select in Article portlet configuration

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

This PR includes 3 changes:
1. Move all Js logic into its own file.
2. Move all Java logic into a display context.
3. Instead of a custom JSP, use the KB article item selector when configuring the portlet.

We cannot (yet) remove the custom JSP, as that is used from the Display portlet to select both folders and articles (something we don't support yet in Item Selector).

# How do I test this?

1. Create a widget page.
2. Add the "Knowledge Base Article" widget.
3. Click on the portlet title ellipsis, select "Configuration".
4. Click the "Select" button; the Item Selector should open.
5. Select an article and save the configuration.
6. Double check that the article is displayed as expected.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by boton — APPROVED** [review]
Manually tested and LGTM.

image

I only added two little things:
- eb28b0742238deb6b7fe329f113b496ede18dd20 Remove the events listener before navigation for example when change the configuration tab
- 4c8d8205e6bdd897e17068a563b3d7b42709644c Remove the `_` on `PortletConfiguration` because feels weird to me

@adolfopa if you prefer `_PortletConfiguration` drop the last commit and feel free to forward it in any case.

**Comment by adolfopa** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward (Sorry, I had to abort the relevant test before it started becuase it was stuck in a long queue)

**Comment by boton** [comment]
Reopen because [we have some conflicts](https://github.com/brianchandotcom/liferay-portal/pull/124413#issuecomment-1275391541) rebased and fixed. @adolfopa @ambrinchaudhary please double-check that I don't break anything on the merge. I tested and feel good but maybe I forgot something.

**Comment by boton** [comment]
@adolfopa I can request a review for you because it is your PR, but if you have a moment, please take a look.

**Comment by adolfopa** [comment]
LGTM

**Pull request closed without merging**
