### PR TITLE
LPS-125016 Make global file size limit an instance scoped configuration

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci failing (`Could not get resource 'https://repository-cdn.liferay.com`)

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa rebase needed :(

**Comment by adolfopa** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:reevaluate:1277401_2175

**Comment by Hanlf** [comment]
Hi @adolfopa 

The failed Poshi tests need to be updated, but there should be some portal issues too.
Steps: Go to System Settings > Documents and Media > VIRTUAL INSTANCE SCOPE > Documents and Media Size Limits

**Comment by Hanlf** [comment]
Sent the Poshi fix commits here: https://github.com/liferay-lima/liferay-portal/pull/2826

**Pull request closed without merging**
