### PR TITLE
LPS-186176 the level can be retrieved from the config so we must put it before the assignation

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
https://liferay.atlassian.net/browse/LPS-186176

On https://liferay.atlassian.net/browse/LPS-164317 the order of the creation and the  Log4JUtil.setLevel was changed to prevent  `OutOfMemoryError from ObjectEntryLocalServiceTest`

On Log4JUtil.setLevel logger is updated and the priority is set to the loggerConfig, and it seems that is from loggerConfig where we take the priority for logging.

If we made Log4JUtil.setLevel after _loggerConfig = logger.get() we are not putting the correct priority to the config so when we take the priority on the logCapture we are comparing with the previous log level (INFO) so the log is not captured if the priority is not the same.

To test it:

- stop server
- wait 5 mins
- start server
- go to `(your portal folder)/modules/apps/message-boards/message-boards-test`
- run ` gw tI --tests "*testDeleteAttachmentsWhenDeletingMessage*"`

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:document

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1327401_708

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Review by adolfopa — COMMENTED** [review]
@AliciaGarciaGarcia The changes look good, but I don't understand why this works. Can you put a more in depth explanation in the pull request description and commit comment? Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:wiki

**Comment by AliciaGarciaGarcia** [comment]
ci:test:objects

**Comment by AliciaGarciaGarcia** [comment]
ci:test:object

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa more explained now?

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
