### PR TITLE
LPS-156216, LPS-170156 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LPS-156216
https://issues.liferay.com/browse/LPS-170156

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by austinchiang — APPROVED** [review]
LGTM

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
