### PR TITLE
LPS-202903 Fix image field values in some cases in the image fragment

### PR DESCRIPTION
**Pull request by robertoDiaz**
https://liferay.atlassian.net/browse/LPS-202903

### CODE REVIEW

**Review by marcogalluzzi — COMMENTED** [review]
It look good to me. Just a question: the second commit is just a SF change right?

**Review by marcogalluzzi — APPROVED** [review]

**Comment by marcogalluzzi** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
This was also reviewed with @jkappler (cc/ @ealonso)

**Comment by SylviaLuan** [comment]
Hi @robertoDiaz,

There are two unique issues caused by this pull request.
[com.liferay.adaptive.media.content.transformer.internal.HtmlContentTransformerImplTest](https://testray.liferay.com/home/-/testray/case_results/2488751433)
[com.liferay.adaptive.media.content.transformer.internal.ContentTransformerHandlerImplTest](https://testray.liferay.com/home/-/testray/case_results/2488751429)
```
[beanshell]      [exec] /opt/dev/projects/github/liferay-portal/modules/apps/adaptive-media/adaptive-media-content-transformer-impl/src/test/java/com/liferay/adaptive/media/content/transformer/internal/HtmlContentTransformerImplTest.java:205: error: constructor HtmlContentTransformerImpl in class com.liferay.adaptive.media.content.transformer.internal.HtmlContentTransformerImpl cannot be applied to given types;
[beanshell]      [exec] 		new HtmlContentTransformerImpl(
[beanshell]      [exec] 		^
[beanshell]      [exec]   required: com.liferay.adaptive.media.image.html.AMImageHTMLTagFactory,com.liferay.adaptive.media.image.mime.type.AMImageMimeTypeProvider,com.liferay.document.library.kernel.service.DLAppLocalService
[beanshell]      [exec]   found: com.liferay.adaptive.media.image.html.AMImageHTMLTagFactory,com.liferay.document.library.kernel.service.DLAppLocalService
[beanshell]      [exec]   reason: actual and formal argument lists differ in length
[beanshell]      [exec] 1 error
[beanshell]      [exec] 
[beanshell]      [exec] 
[beanshell]      [exec] > Task :apps:adaptive-media:adaptive-media-content-transformer-impl:compileTestJava FAILED
[beanshell]      [exec] 
[beanshell]      [exec] > Task :core:petra:petra-lang:autoUpdateXml SKIPPED
[beanshell]      [exec] > Task :core:petra:petra-string:autoUpdateXml SKIPPED
[beanshell]      [exec] Gradle build finished at 2024-01-17 12:10:42.923.
[beanshell]      [exec] 
[beanshell]      [exec] FAILURE: Build failed with an exception.
[beanshell]      [exec] 
[beanshell]      [exec] * What went wrong:
[beanshell]      [exec] Execution failed for task ':apps:adaptive-media:adaptive-media-content-transformer-impl:compileTestJava'.
[beanshell]      [exec] > Compilation failed; see the compiler error output for details.
[beanshell]      [exec] 
[beanshell]      [exec] * Try:
[beanshell]      [exec] > Run with --info or --debug option to get more log output.
[beanshell]      [exec] > Run with --scan to get full insights.
[beanshell]      [exec] 
[beanshell]      [exec] * Exception is:
[beanshell]      [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:adaptive-media:adaptive-media-content-transformer-impl:compileTestJava'.
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
[beanshell]      [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:131)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
[beanshell]      [exec] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
[beanshell]      [exec] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
[beanshell]      [exec] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
[beanshell]      [exec] 	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
[beanshell]      [exec] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
[beanshell]      [exec] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
[beanshell]      [exec] 	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
[beanshell]      [exec] 	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
[beanshell]      [exec] 	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
[beanshell]      [exec] 	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
[beanshell]      [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:402)
[beanshell]      [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:389)
[beanshell]      [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:382)
[beanshell]      [exec] 	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:368)
[beanshell]      [exec] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
[beanshell]      [exec] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
[beanshell]      [exec] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
[beanshell]      [exec] 	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
[beanshell]      [exec] 	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
[beanshell]      [exec] 	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
[beanshell]      [exec] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
[beanshell]      [exec] Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
```

**Comment by robertoDiaz** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:forward:force

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Comment by marcogalluzzi** [comment]
ci:forward:force

**Pull request closed without merging**
