### PR TITLE
LPS-130463 / LPS-124408 / LPS-129242 Add Google Cloud auto translations

### PR DESCRIPTION
**Pull request by boton**
This PR enables the Auto-translation for all the fields at once.

This PR is on top of this #1641 that has already been reviewed ✅ 

**Test Plan:**

- Enable `com.liferay.translation.web.internal.configuration.FFAutoTranslateConfiguration` feature flag.
 
   ```
   cd LIFERAY_PORTAL_PATH
   echo "enabled=B\"true\"" > ../bundles/osgi/configs/com.liferay.translation.web.internal.configuration.FFAutoTranslateConfiguration.config
  ```
  
- Configuration: System settings > Content and Data > category.translations (default cog icon) 

  image
- Enable and ask @adolfopa for google temporarily credentials only for this dev phase

- Go to Content and Data > Web Content > `[ + ]` create new WC (Basic WC or other)
- In the list open the kebap menu of this new web content `click` on `Translate`
- In the translation page must show an `Auto-translate` button.
- Select target language and auto-translate it

  image

We have different status when auto-translate it´s working
- **loading**
  
  image

- **success**
  
  image

- **error**
  
  image

### CODE REVIEW

**Comment by boton** [comment]
ci:test:sf

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
@adolfopa I do not know if the FF must affect to the GoogleCloudTranslatorConfiguration because if we can not auto-translate to let the user to see the option and introduce the configuration.

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
