### PR TITLE
LPS-143559 When replying to a thread with a user name with special characters the characters are displayed as HTML code

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I'm wishing you happy holidays!

Please let me know of any updates with the review.

Thank you and best regards,
István

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
