### PR TITLE
[TS] LPS-173703 External video cannot be added because of file ending restrictions

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
When documents of only certain extensions are allowed, the extension validation will fail on external video shortcuts because those documents do not have an extension.

Proposed Solution
========
Skipping the extension validation for documents where an extension is not present in the name, no file is being uploaded, and the document type scope is system.

Steps to Verify
========
Please consult the linked LPS for reproduction steps.
https://issues.liferay.com/browse/LPS-173703

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
The above failures are not related to this PR.

**Comment by adolfopa** [comment]
@IstvanD I've made some small changes. Can you take a look at https://github.com/liferay-lima/liferay-portal/pull/3969?

**Comment by IstvanD** [comment]
Hi @adolfopa it solves the issue as well.

**Comment by adolfopa** [comment]
Closing in favor of https://github.com/liferay-lima/liferay-portal/pull/3969

**Pull request closed without merging**
