### PR TITLE
LPS-116438 LPS-116438 Small images are not appearing in the blogs

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi @liferay-lima ,
Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
Hi @liferay-lima ,
Could you please check this pull request?
Thank you.

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
