### PR TITLE
LPS-153099 DM Checkin - no response when clicking saving

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey @boton, please check the resolution. 

I could not find a way to include the checkin_js.ftl from the java side like it was done before, so I added the script directly in the js code.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by boton** [comment]
ci:forward

**Comment by adolfopa** [comment]
ci:reevaluate:1377401_2127

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
