### PR TITLE
LPS-123757 update untranslated description map

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
Hi @AliciaGarciaGarcia,

I already sent this a few days ago in https://github.com/brianchandotcom/liferay-portal/pull/96048. (Waiting for brian to merge). Can we close this one to avoid conflicts on the other one?

**Pull request closed without merging**
