### PR TITLE
LPS-110425 SF - Inline method

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Hey @austinchiang 

It seems the markup for modals have changed in the last couple of days, so any tests relying on that should be failing (see previous failures in this PR). I've included a quick fix in the last commit; can you check if it is ok? I haven't changed the name of the path to minimize the amount of changes.

/cc @jbalsas

**Comment by jbalsas** [comment]
If usage has switched from AUI Modals to Clay Modals, markup would've changed. Beware of global selector changes as it might affect other instances where legacy Modals are still being used.

Ideally, we would at least pause to think what's that condition doing there and why. Are we asserting the title in the modal? What for? If so... how much value it is in that check? Is there a better way to ensure the result we're looking for? 

/cc @wincent, @markocikos, @john-co, @manoelcyreno

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
@adolfopa A few other tests (in Sharing and DDL) are failing due to the changes in that Poshi path since they depend on `h3`, so we'll create a separate locator for the site navigation modal to deal with the failing tests in this pull. Ideally there would be one locator that we could use for all paths related to modal titles, but the paths seems unique enough to warrant separate locators. In any case, @Hanlf was working on the issue [here](https://issues.liferay.com/browse/LRQA-58873) and will rebase and resend her changes off this pull once she's done.

Thanks for the tip @jbalsas. I believe it's still valuable to assert the modal title because it essentially serves as the prompt to the ["temporal task"](https://liferay.design/lexicon/core-components/modals/) that the modal is designed to accomplish. If the title is missing, the end user may not be primed enough (or might forget) to do what he was supposed to do inside the modal. So I think asserting this from a Poshi perspective is still the best thing to do to prevent UX regressions.

**Comment by Hanlf** [comment]
Resend it here: https://github.com/liferay-lima/liferay-portal/pull/97

**Pull request closed without merging**
