### PR TITLE
[7.4-only]  LPS-121962 Migrate v2 usages of clay:vertical-card in item-selector-web

### PR DESCRIPTION
**Pull request by julien**
In this change, we replace `<clay:vertical-card-v2 />`
(clay 2.x: Metal+soy) with `<clay:vertical-card />` (clay 3.x: React)

**Test plan**:
- Navigate to **Content & Data** > **Blogs**
- Create a new blog entry and publish it
- Create a content page
- Drag and drop an HTML fragment on the page
- Map the content of the HTML fragment to a blog entry

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
cc @carloslancha @markocikos

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
@liferay-lima please forward when you get a chance - thanks

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Hey @julien @carloslancha @markocikos, we have here the same issue with the aspect ratios like in https://github.com/liferay-lima/liferay-portal/pull/1101. 

**Before**: 
Item selector - Before

**After**:
Item Selector - After

**Comment by julien** [comment]
@ambrinchaudhary we've put this on hold until we talk about the image "aspect ratio" classes

**Comment by carloslancha** [comment]
@ambrinchaudhary @julien this has been addressed in https://github.com/liferay/clay/pull/3815/files

To not stay blocked with this I created [this ticket](https://issues.liferay.com/browse/LPS-123984) so we can fix the issue once the migration is done. 

So we can continue with this one. Thx! :)

**Comment by julien** [comment]
@carloslancha thanks!

**Comment by ambrinchaudhary** [comment]
ci:forward

**Pull request closed without merging**
