### PR TITLE
LPS-129359 no longer needed

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
LGTM.

**Review by carloslancha — APPROVED** [review]

**Review by boton — APPROVED** [review]
LGTM

**Comment by boton** [comment]
ci:forward

**Comment by AliciaGarciaGarcia** [comment]
ci:forward

**Pull request closed without merging**
