### PR TITLE
LPS-182480 Sorting order is important; partically revert SF change

### PR DESCRIPTION
**Pull request by adolfopa**
# What is this about?

https://issues.liferay.com/browse/LPS-182480

# How do I test it?

Follow the steps described in https://issues.liferay.com/browse/LPS-182480.

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Nevermind. Can you review the changes in https://github.com/robertoDiaz/liferay-portal/pull/896 and resend it here? Thanks!

**Comment by adolfopa** [comment]
Test failures unrelated to my changes.

**Comment by adolfopa** [comment]
ci:forward:force

**Pull request closed without merging**
