### PR TITLE
LPS 158632.2

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**
- LPS-158632 GroupThreadLocal does not is always initiated so use the service context instead
- LPS-158632 in some cases, the group initialised on the service context is not properly with the group of the friendlyGroupURL
- LPS-158632 restore the initial service context after we use it for obtaining the urlTitle

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
sent to Brian https://github.com/brianchandotcom/liferay-portal/pull/120747

**Pull request closed without merging**
