### PR TITLE
LPS-188200 Show journal field in DM (since it appears in previous versions)

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Review by marcogalluzzi — CHANGES_REQUESTED** [review]
The use of Web Content was explicitly removed by @adolfopa Are we sure we want to allow it again?

```
LPS-139710 Remove Journal field from DM

This was an accidental feature that is causing circularity problems
with Staging. Removing it, as we don't want to explicitly support this
use case.

1b0204cc Adolfo Pérez Álvarez <adolfo.perez@liferay.com> on 30/9/21 at 12:04
committed by Brian Chan <brian.chan@liferay.com> on 30/9/21 at 19:06
```

**Comment by robertoDiaz** [comment]
yes, I've agreed with @adolfopa pass this and try to fix the other case

**Comment by marcogalluzzi** [comment]
ci:test:stable

**Comment by marcogalluzzi** [comment]
ci:relevant

**Comment by marcogalluzzi** [comment]
ci:test:relevant

**Comment by marcogalluzzi** [comment]
ci:forward

**Pull request closed without merging**
