### PR TITLE
LPS-154955 | Master

### PR DESCRIPTION
**Pull request by austinchiang**
https://issues.liferay.com/browse/LPS-154955

### CODE REVIEW

**Comment by liferay-lima** [comment]
ci:test:sf

**Comment by liferay-lima** [comment]
ci:test:relevant

**Comment by austinchiang** [comment]
Passed testing in https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1867018226

**Comment by austinchiang** [comment]
ci:forward

**Pull request closed without merging**
