### PR TITLE
LPS-121370 Show the document type selector even when adding a new document

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:documents

**Comment by adolfopa** [comment]
ci:test:documents

**Comment by adolfopa** [comment]
@jonathanmccann @robertoDiaz Can you guys take a look at the poshi failures?

**Comment by adolfopa** [comment]
Same failures show up in https://github.com/liferay-lima/liferay-portal/pull/854, so it seems to be not related to these changes.

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by adolfopa** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/861

**Pull request closed without merging**
